root(0,ROOT,man).
det(0,man,a).
advmod(0,poor,very).
amod(0,man,poor).
det(0,carpenter,a).
nsubj(0,had,carpenter).
case(0,trade,by).
nmod:by(0,carpenter,trade).
acl:relcl(0,man,had).
det(0,image,a).
amod(0,image,wooden).
dobj(0,had,image).
case(0,mercury,of).
nmod:of(0,image,mercury).
mark(0,made,before).
dobj(0,made,which).
nsubj(0,made,he).
nsubj(0,begged,he).
acl:before(0,man,made).
dobj(0,made,offerings).
nmod:tmod(0,made,day).
case(0,day,by).
nmod:by(0,made,day).
cc(0,made,and).
acl:before(0,man,begged).
conj:and(0,made,begged).
det(0,idol,the).
dobj(0,begged,idol).
nsubj:xsubj(0,make,idol).
mark(0,make,to).
xcomp(0,begged,make).
nsubj(0,became,him).
dep(0,became,rich).
cc(0,entreaties,but).
case(0,entreaties,in).
mwe(0,in,spite).
mwe(0,in,of).
nmod:poss(0,entreaties,his).
nmod:in_spite_of(0,rich,entreaties).
nsubj(0,became,he).
xcomp(0,make,became).
xcomp(0,became,poorer).
cc(0,poorer,and).
xcomp(0,became,poorer).
conj:and(0,poorer,poorer).
had(0,carpenter,wooden_image).
became(0,he,poorer).
make(0,idol,him_became).
had(0,carpenter,wooden_image_of_mercury).
became(0,him,poorer).
make(0,idol,he_became).
had(0,carpenter,image).
carpenter_by(0,image,trade).
had(0,carpenter,image_of_mercury).
made(0,he,offerings).
begged(0,he,idol).
made_offerings_at_time(0,he,day).
make(0,idol,him_he_became).
carpenter_by(0,wooden_image,trade).
made_offerings_by(0,he,day).
root(1,ROOT,angry).
dep(1,angry,at).
advmod(1,angry,last).
cop(1,angry,being).
advmod(1,angry,very).
nsubj(1,took,he).
nsubj(1,dashed,he).
ccomp(1,angry,took).
nmod:poss(1,image,his).
dobj(1,took,image).
advmod(1,took,down).
case(1,pedestal,from).
nmod:poss(1,pedestal,its).
nmod:from(1,down,pedestal).
cc(1,took,and).
ccomp(1,angry,dashed).
conj:and(1,took,dashed).
dobj(1,dashed,it).
case(1,wall,against).
det(1,wall,the).
nmod:against(1,dashed,wall).
took_down(1,he,his_image).
took(1,he,his_image).
dashed(1,he,it).
root(2,ROOT,came).
advmod(2,came,when).
nmod:poss(2,head,its).
nsubj(2,came,head).
auxpass(2,knocked,was).
acl:relcl(2,head,knocked).
compound:prt(2,knocked,off).
advmod(2,knocked,out).
det(2,stream,a).
dobj(2,came,stream).
dobj(2,picked,stream).
case(2,gold,of).
nmod:of(2,stream,gold).
ref(2,stream,which).
det(2,carpenter,the).
nsubj(2,picked,carpenter).
nsubj(2,said,carpenter).
advmod(2,picked,quickly).
acl:relcl(2,stream,picked).
compound:prt(2,picked,up).
cc(2,picked,and).
acl:relcl(2,stream,said).
conj:and(2,picked,said).
root(3,ROOT,i).
dep(3,i,well).
acl:relcl(3,i,think).
nsubj(3,art,thou).
xcomp(3,think,art).
advmod(3,contradictory,altogether).
amod(3,art,contradictory).
cc(3,contradictory,and).
amod(3,art,unreasonable).
conj:and(3,contradictory,unreasonable).
root(4,ROOT,reaped).
mark(4,reaped,for).
advmod(4,reaped,when).
nsubj(4,reaped,i).
acl(4,i,paid).
nsubj(4,honor,you).
ccomp(4,paid,honor).
dobj(4,honor,i).
neg(4,benefits,no).
dobj(4,reaped,benefits).
cc(4,reaped,but).
advmod(4,loaded,now).
mark(4,loaded,that).
compound(4,maltreat,i).
nsubjpass(4,loaded,maltreat).
dep(4,maltreat,you).
dep(4,maltreat,i).
auxpass(4,loaded,am).
advcl:that(4,reaped,loaded).
case(4,abundance,with).
det(4,abundance,an).
nmod:with(4,loaded,abundance).
case(4,riches,of).
nmod:of(4,abundance,riches).
am_loaded_with(4,i_maltreat,abundance).
now_am_loaded_with(4,i_maltreat,abundance_of_riches).
am(4,i_maltreat,loaded).
am_loaded_with(4,i_maltreat,abundance_of_riches).
am(4,i_maltreat,now_loaded).
now_am_loaded_with(4,i_maltreat,abundance).
