root(0,ROOT,searching).
det(0,hunter,a).
nsubj(0,searching,hunter).
neg(0,bold,not).
advmod(0,bold,very).
amod(0,hunter,bold).
aux(0,searching,was).
case(0,tracks,for).
det(0,tracks,the).
nmod:for(0,searching,tracks).
case(0,lion,of).
det(0,lion,a).
nmod:of(0,tracks,lion).
root(1,ROOT,asked).
nsubj(1,asked,he).
nsubj(1,knew,he).
det(1,man,a).
dobj(1,asked,man).
amod(1,oaks,felling).
nmod:in(1,asked,oaks).
case(1,oaks,in).
det(1,forest,the).
dep(1,oaks,forest).
mark(1,seen,if).
nsubj(1,seen,he).
aux(1,seen,had).
advcl:if(1,asked,seen).
det(1,marks,any).
dobj(1,seen,marks).
case(1,footsteps,of).
nmod:poss(1,footsteps,his).
nmod:of(1,marks,footsteps).
cc(1,asked,or).
conj:or(1,asked,knew).
advmod(1,was,where).
nmod:poss(1,lair,his).
nsubj(1,was,lair).
ccomp(1,knew,was).
had_seen(1,he,marks_of_footsteps).
had_seen(1,he,marks_of_his_footsteps).
asked_man_in(1,he,felling_oaks).
asked(1,he,man).
asked_man_in(1,he,oaks).
marks_of(1,he,his_footsteps).
marks_of(1,he,footsteps).
root(2,ROOT,will).
nsubj(2,will,i).
root(3,ROOT,said).
det(3,man,the).
nsubj(3,said,man).
root(4,ROOT,show).
case(4,once,at).
advmod(4,show,once).
nsubj(4,lion,you).
det(4,lion,the).
xcomp(4,show,lion).
nsubj(4,show,himself).
show(4,himself,you_lion).
once_show(4,himself,you_lion).
root(5,ROOT,replied).
det(5,hunter,the).
nsubj(5,replied,hunter).
dep(5,hunter,turning).
advmod(5,pale,very).
xcomp(5,turning,pale).
cc(5,turning,and).
dep(5,hunter,chattering).
conj:and(5,turning,chattering).
case(5,teeth,with).
nmod:poss(5,teeth,his).
nmod:with(5,chattering,teeth).
case(5,fear,from).
nmod:from(5,chattering,fear).
root(6,ROOT,no).
dep(6,no,thank).
dobj(6,thank,you).
root(7,ROOT,ask).
nsubj(7,ask,i).
aux(7,ask,did).
neg(7,ask,not).
advmod(7,ask,that).
root(8,ROOT,search).
nsubj(8,track,it).
cop(8,track,is).
nmod:poss(8,track,his).
dep(8,search,track).
advmod(8,i,only).
nmod(8,track,i).
cop(8,search,am).
case(8,search,in).
case(8,lion,of).
neg(8,lion,not).
det(8,lion,the).
nmod:of(8,search,lion).
nsubj(8,search,himself).
is(8,it,his_track_only_i).
is(8,it,his_track_i).
is(8,it,his_track).
