root(0,ROOT,terrified).
det(0,pigeons,the).
nsubj(0,terrified,pigeons).
case(0,appearance,by).
det(0,appearance,the).
nmod:by(0,terrified,appearance).
case(0,kite,of).
det(0,kite,a).
nmod:of(0,appearance,kite).
acl(0,kite,called).
case(0,hawk,upon).
det(0,hawk,the).
nmod:upon(0,called,hawk).
mark(0,defend,to).
xcomp(0,called,defend).
dobj(0,defend,them).
terrified_by(0,pigeons,appearance_of_kite_called_upon_hawk).
terrified_by(0,pigeons,appearance_of_kite_called).
terrified_by(0,pigeons,appearance).
terrified_by(0,pigeons,appearance_of_kite).
root(1,ROOT,consented).
nsubj(1,consented,he).
case(1,once,at).
advmod(1,consented,once).
root(2,ROOT,admitted).
advmod(2,admitted,when).
nsubj(2,admitted,they).
aux(2,admitted,had).
dobj(2,admitted,him).
case(2,cote,into).
det(2,cote,the).
nmod:into(2,admitted,cote).
mark(2,made,cote).
nsubj(2,found,they).
acl:relcl(2,cote,found).
ref(2,cote,that).
nsubj(2,made,he).
ccomp(2,found,made).
advmod(2,havoc,more).
nmod(2,pounce,havoc).
cc(2,havoc,and).
conj:and(2,havoc,slew).
nmod(2,pounce,slew).
det(2,number,a).
amod(2,number,larger).
nsubj(2,pounce,number).
case(2,them,of).
nmod:of(2,number,them).
case(2,day,in).
nummod(2,day,one).
nmod:in(2,them,day).
case(2,kite,than).
det(2,kite,the).
nmod:than(2,day,kite).
aux(2,pounce,could).
ccomp(2,made,pounce).
case(2,year,upon).
case(2,year,in).
det(2,year,a).
amod(2,year,whole).
nmod:upon(2,pounce,year).
had_admitted(2,they,him).
