root(0,ROOT,started).
det(0,hound,a).
nsubj(0,started,hound).
det(0,hare,a).
nsubj(0,gave,hare).
conj:but(0,hare,hare).
nsubj(0,gave,hare).
case(0,lair,from).
nmod:poss(0,lair,his).
nmod:from(0,hare,lair).
cc(0,hare,but).
case(0,run,after).
det(0,run,a).
amod(0,run,long).
nmod:after(0,hare,run).
ccomp(0,started,gave).
compound:prt(0,gave,up).
det(0,chase,the).
dobj(0,gave,chase).
hare_after(0,chase,run).
hare_from(0,chase,his_lair).
gave_up(0,hare,chase).
hare_after(0,chase,long_run).
root(1,ROOT,mocked).
det(1,goat-herd,a).
nsubj(1,mocked,goat-herd).
acl(1,goat-herd,seeing).
nsubj(1,stop,him).
xcomp(1,seeing,stop).
nsubj(1,saying,him).
dep(1,mocked,saying).
root(2,ROOT,runner).
det(2,one,the).
amod(2,one,little).
nsubj(2,runner,one).
cop(2,runner,is).
det(2,runner,the).
amod(2,runner,best).
case(2,two,of).
det(2,two,the).
nmod:of(2,runner,two).
is(2,little_one,runner).
is_runner_of(2,little_one,two).
is(2,little_one,best_runner).
is_best_runner_of(2,little_one,two).
root(3,ROOT,replied).
det(3,hound,the).
nsubj(3,replied,hound).
root(4,ROOT,see).
nsubj(4,see,you).
aux(4,see,do).
neg(4,see,not).
det(4,difference,the).
dobj(4,see,difference).
case(4,us,between).
nmod:between(4,difference,us).
nsubj(4,running,i).
aux(4,running,was).
advmod(4,running,only).
acl:relcl(4,difference,running).
case(4,dinner,for).
det(4,dinner,a).
nmod:for(4,running,dinner).
case(4,he,but).
nmod:but(4,dinner,he).
case(4,life,for).
nmod:poss(4,life,his).
nmod:for(4,running,life).
