%% a heifer saw an ox hard at work harnessed to a plow and tormented him with reflections on his unhappy fate in being compelled to labor.
% dependencies.
root(0,root,see).
det(0,heifer,a).
nsubj(0,see,heifer).
nsubj(0,torment,heifer).
det(0,ox,a).
dobj(0,see,ox).
advmod(0,see,hard).
case(0,work,at).
nmod:at(0,see,work).
acl(0,work,harness).
mark(0,plow,to).
advmod(0,plow,a).
xcomp(0,harness,plow).
cc(0,see,and).
conj:and(0,see,torment).
dobj(0,torment,he).
case(0,reflection,with).
nmod:with(0,torment,reflection).
case(0,fate,on).
nmod:poss(0,fate,he).
amod(0,fate,unhappy).
nmod:on(0,reflection,fate).
mark(0,compel,in).
auxpass(0,compel,be).
advcl:in(0,torment,compel).
case(0,labor,to).
nmod:to(0,compel,labor).
% relations.
aos(0,torment,heifer,he).
aos(0,see,heifer,ox).
aos(0,see_hard,heifer,ox).
aos(0,see_ox_hard_at,heifer,work).
aos(0,see_ox_at,heifer,work).
aos(0,see_ox_hard_at,heifer,work_harness).
aos(0,see_ox_at,heifer,work_harness).
%% shortly afterwards at the harvest festival the owner released the ox from his yoke but bound the heifer with cords and led him away to the altar to be slain in honor of the occasion.
% dependencies.
root(1,root,release).
advmod(1,festival,shortly).
advmod(1,festival,afterwards).
case(1,festival,at).
det(1,festival,the).
compound(1,festival,harvest).
advcl:at(1,release,festival).
det(1,owner,the).
nsubj(1,release,owner).
nsubj(1,bind,owner).
nsubj(1,lead,owner).
det(1,ox,the).
dobj(1,release,ox).
case(1,yoke,from).
nmod:poss(1,yoke,he).
nmod:from(1,release,yoke).
cc(1,release,but).
conj:but(1,release,bind).
det(1,heifer,the).
dobj(1,bind,heifer).
case(1,cord,with).
nmod:with(1,bind,cord).
cc(1,release,and).
conj:but(1,release,lead).
dobj(1,lead,he).
advmod(1,lead,away).
case(1,altar,to).
det(1,altar,the).
nmod:to(1,away,altar).
mark(1,slay,to).
auxpass(1,slay,be).
advcl:to(1,lead,slay).
case(1,honor,in).
nmod:in(1,slay,honor).
case(1,occasion,of).
det(1,occasion,the).
nmod:of(1,honor,occasion).
% relations.
aos(1,release_ox_at,owner,shortly_harvest_festival).
aos(1,bind_heifer_with,owner,cord).
aos(1,lead,owner,he).
aos(1,release_ox_at,owner,harvest_festival).
aos(1,bind_with,owner,cord).
aos(1,bind,owner,heifer).
aos(1,lead_away,owner,he).
aos(1,release,owner,ox).
aos(1,release_ox_at,owner,shortly_afterwards_harvest_festival).
aos(1,release_ox_at,owner,afterwards_harvest_festival).
%% the ox saw what was being done and said with a smile to the heifer.
% dependencies.
root(2,root,see).
det(2,ox,the).
nsubj(2,see,ox).
nsubj(2,say,ox).
nsubjpass(2,do,what).
aux(2,do,be).
auxpass(2,do,be).
ccomp(2,see,do).
cc(2,see,and).
conj:and(2,see,say).
case(2,smile,with).
det(2,smile,a).
nmod:with(2,say,smile).
case(2,heifer,to).
det(2,heifer,the).
nmod:to(2,say,heifer).
% relations.
aos(2,say_to,ox,heifer).
aos(2,say_with,ox,smile).
%% for this you were allowed to live in idleness because you were presently to be sacrificed.
% dependencies.
root(3,root,allow).
case(3,this,for).
nmod:for(3,allow,this).
nsubjpass(3,allow,you).
nsubj:xsubj(3,live,you).
auxpass(3,allow,be).
mark(3,live,to).
xcomp(3,allow,live).
case(3,idleness,in).
nmod:in(3,live,idleness).
mark(3,be,because).
nsubj(3,be,you).
nsubjpass:xsubj(3,sacrifice,you).
advcl:because(3,live,be).
advmod(3,be,presently).
mark(3,sacrifice,to).
auxpass(3,sacrifice,be).
xcomp(3,be,sacrifice).
% relations.
aos(3,be,you,allow).
aos(3,live,you,be_presently).
aos(3,be_allow,you,live_in_idleness).
aos(3,live_in,you,idleness).
aos(3,live,you,be).
aos(3,be_allow,you,live).
aos(3,be_allow_for,you,this).
