root(0,ROOT,disturbed).
det(0,owl,an).
nsubjpass(0,disturbed,owl).
nsubj:xsubj(0,stop,owl).
acl(0,owl,accustomed).
mark(0,feed,to).
ccomp(0,accustomed,feed).
case(0,night,at).
nmod:at(0,feed,night).
cc(0,feed,and).
mark(0,sleep,to).
ccomp(0,accustomed,sleep).
conj:and(0,feed,sleep).
case(0,day,during).
det(0,day,the).
nmod:during(0,sleep,day).
auxpass(0,disturbed,was).
advmod(0,disturbed,greatly).
case(0,noise,by).
det(0,noise,the).
nmod:by(0,her,noise).
case(0,grasshopper,of).
det(0,grasshopper,a).
nmod:of(0,noise,grasshopper).
cc(0,her,and).
nmod(0,disturbed,earnestly).
conj:and(0,her,earnestly).
dep(0,earnestly,besought).
nmod(0,disturbed,her).
mark(0,stop,to).
xcomp(0,disturbed,stop).
xcomp(0,stop,chirping).
was(0,owl,greatly_disturbed).
was(0,owl,greatly_disturbed_by_noise_her).
was(0,owl,disturbed_by_noise_of_grasshopper_her).
was(0,owl,greatly_disturbed_by_noise_of_grasshopper_her).
was(0,owl,disturbed).
was(0,owl,greatly_disturbed_her).
was(0,owl,disturbed_her).
stop(0,owl,chirping).
was(0,owl,disturbed_by_noise_her).
root(1,ROOT,grasshopper).
det(1,grasshopper,the).
ccomp(1,grasshopper,refused).
mark(1,desist,to).
xcomp(1,refused,desist).
cc(1,refused,and).
ccomp(1,grasshopper,chirped).
conj:and(1,refused,chirped).
advmod(1,and,louder).
advmod(1,chirped,and).
advmod(1,and,louder).
det(1,more,the).
dep(1,owl,more).
det(1,owl,the).
dep(1,grasshopper,owl).
acl(1,owl,entreated).
root(2,ROOT,saw).
advmod(2,saw,when).
nsubj(2,saw,she).
mark(2,get,that).
nsubj(2,get,she).
aux(2,get,could).
ccomp(2,saw,get).
neg(2,redress,no).
dobj(2,get,redress).
cc(2,get,and).
mark(2,despised,that).
nmod:poss(2,words,her).
nsubjpass(2,despised,words).
auxpass(2,despised,were).
ccomp(2,saw,despised).
conj:and(2,get,despised).
det(2,owl,the).
dobj(2,despised,owl).
acl(2,owl,attacked).
det(2,chatterer,the).
dobj(2,attacked,chatterer).
case(2,stratagem,by).
det(2,stratagem,a).
nmod:by(2,attacked,stratagem).
were_despised(2,her_words,owl).
root(3,ROOT,sleep).
mark(3,sleep,since).
nsubj(3,sleep,i).
aux(3,sleep,can).
neg(3,sleep,not).
root(4,ROOT,said).
nsubj(4,said,she).
root(5,ROOT,song).
case(5,song,on).
mwe(5,on,account).
mwe(5,on,of).
nmod:poss(5,song,your).
nsubj(5,believe,song).
ref(5,song,which).
acl:relcl(5,song,believe).
nsubj(5,sweet,me).
cop(5,sweet,is).
ccomp(5,believe,sweet).
mark(5,gave,as).
det(5,lyre,the).
nsubj(5,gave,lyre).
case(5,apollo,of).
nmod:of(5,lyre,apollo).
nsubj(5,indulge,i).
aux(5,indulge,shall).
acl:relcl(5,apollo,indulge).
dobj(5,indulge,myself).
mark(5,drinking,in).
advcl:in(5,indulge,drinking).
det(5,nectar,some).
dobj(5,drinking,nectar).
nsubj(5,pallas,nectar).
ref(5,nectar,which).
acl:relcl(5,nectar,pallas).
advmod(5,pallas,lately).
advcl:as(5,sweet,gave).
dobj(5,gave,me).
root(6,ROOT,dislike).
mark(6,dislike,if).
nsubj(6,dislike,you).
aux(6,dislike,do).
neg(6,dislike,not).
nsubj(6,come,it).
ccomp(6,dislike,come).
case(6,me,to).
nmod:to(6,come,me).
cc(6,dislike,and).
nsubj(6,drink,we).
aux(6,drink,will).
conj:and(6,dislike,drink).
dobj(6,drink,it).
advmod(6,drink,together).
will_drink(6,we,it).
will_drink_together(6,we,it).
root(7,ROOT,flew).
det(7,grasshopper,the).
nsubj(7,thirsty,grasshopper).
nsubj(7,pleased,grasshopper).
nsubj(7,flew,grasshopper).
ref(7,grasshopper,who).
cop(7,thirsty,was).
acl:relcl(7,grasshopper,thirsty).
cc(7,thirsty,and).
acl:relcl(7,grasshopper,pleased).
conj:and(7,thirsty,pleased).
case(7,praise,with).
det(7,praise,the).
nmod:with(7,thirsty,praise).
case(7,voice,of).
nmod:poss(7,voice,her).
nmod:of(7,praise,voice).
advmod(7,flew,eagerly).
compound:prt(7,flew,up).
root(8,ROOT,came).
det(8,owl,the).
nsubj(8,came,owl).
advmod(8,seized,forth).
case(8,hollow,from).
nmod:poss(8,hollow,her).
nmod:from(8,forth,hollow).
ccomp(8,came,seized).
dobj(8,seized,her).
cc(8,seized,and).
ccomp(8,came,put).
conj:and(8,seized,put).
dobj(8,put,her).
case(8,death,to).
nmod:to(8,put,death).
put(8,her,her).
