root(0,ROOT,took).
det(0,soldier,a).
compound(0,soldier,horse).
nsubj(0,took,soldier).
det(0,pains,the).
amod(0,pains,utmost).
dobj(0,took,pains).
case(0,charger,with).
nmod:poss(0,charger,his).
nmod:with(0,took,charger).
took(0,horse_soldier,utmost_pains).
took_pains_with(0,horse_soldier,his_charger).
took(0,horse_soldier,pains).
root(1,ROOT,long).
advmod(1,long,as).
mark(1,lasted,as).
det(1,war,the).
nsubj(1,lasted,war).
dep(1,long,lasted).
nsubj(1,looked,he).
ccomp(1,lasted,looked).
case(1,him,upon).
nmod:upon(1,looked,him).
case(1,fellow-helper,as).
nmod:poss(1,fellow-helper,his).
nmod:as(1,looked,fellow-helper).
case(1,emergencies,in).
det(1,emergencies,all).
nmod:in(1,fellow-helper,emergencies).
cc(1,long,and).
conj:and(1,long,fed).
dobj(1,fed,him).
advmod(1,fed,carefully).
case(1,hay,with).
nmod:with(1,fed,hay).
cc(1,hay,and).
nmod:with(1,fed,corn).
conj:and(1,hay,corn).
looked_upon(1,he,him).
is_in(1,his_fellow-helper,emergencies).
looked_as(1,he,his_fellow-helper_in_emergencies).
root(2,ROOT,was).
cc(2,was,but).
advmod(2,was,when).
det(2,war,the).
nsubj(2,was,war).
mark(2,allowed,over).
nsubj(2,allowed,he).
nsubj(2,made,he).
advmod(2,allowed,only).
advcl:over(2,was,allowed).
dep(2,chaff,him).
dobj(2,allowed,chaff).
nsubj:xsubj(2,eat,chaff).
mark(2,eat,to).
xcomp(2,allowed,eat).
cc(2,allowed,and).
advcl:over(2,was,made).
conj:and(2,allowed,made).
nsubj(2,carry,him).
ccomp(2,made,carry).
amod(2,loads,heavy).
det:qmod(2,wood,loads).
mwe(2,loads,of).
dobj(2,carry,wood).
acl(2,wood,subjecting).
dobj(2,subjecting,him).
case(2,drudgery,to).
amod(2,drudgery,much).
amod(2,drudgery,slavish).
nmod:to(2,subjecting,drudgery).
cc(2,drudgery,and).
nmod:to(2,subjecting,ill-treatment).
conj:and(2,drudgery,ill-treatment).
allowed(2,he,eat).
only_allowed(2,he,eat).
only_allowed(2,he,chaff).
allowed(2,he,chaff).
was(2,war,he_only_allowed).
was(2,war,he_allowed).
root(3,ROOT,proclaimed).
nsubj(3,proclaimed,war).
cop(3,proclaimed,was).
advmod(3,proclaimed,again).
dep(3,proclaimed,however).
cc(3,however,and).
advmod(3,summoned,when).
det(3,trumpet,the).
nsubj(3,summoned,trumpet).
nsubj(3,mounted,trumpet).
dep(3,proclaimed,summoned).
conj:and(3,however,summoned).
dobj(3,summoned,him).
case(3,soldier,to).
nmod:poss(3,soldier,his).
amod(3,soldier,standard).
det(3,soldier,the).
nmod:to(3,summoned,soldier).
acl(3,soldier,put).
case(3,charger,on).
nmod:poss(3,charger,his).
nmod:on(3,put,charger).
nmod:poss(3,trappings,its).
amod(3,trappings,military).
dep(3,charger,trappings).
cc(3,summoned,and).
conj:and(3,however,mounted).
conj:and(3,summoned,mounted).
auxpass(3,clad,being).
xcomp(3,mounted,clad).
case(3,coat,in).
nmod:poss(3,coat,his).
amod(3,coat,heavy).
nmod:in(3,clad,coat).
case(3,mail,of).
nmod:of(3,coat,mail).
was(3,war,proclaimed).
was(3,war,again_proclaimed).
root(4,ROOT,fell).
det(4,horse,the).
nsubj(4,fell,horse).
nsubj(4,said,horse).
compound:prt(4,fell,down).
dobj(4,fell,straightway).
case(4,weight,under).
det(4,weight,the).
nmod:under(4,fell,weight).
neg(4,longer,no).
advmod(4,equal,longer).
amod(4,weight,equal).
case(4,burden,to).
det(4,burden,the).
nmod:to(4,fell,burden).
cc(4,fell,and).
conj:and(4,fell,said).
case(4,master,to).
nmod:poss(4,master,his).
nmod:to(4,said,master).
fell_down_under(4,horse,weight).
fell_down_straightway_under(4,horse,weight).
said_to(4,horse,his_master).
fell_down_straightway_to(4,horse,burden).
fell_down(4,horse,straightway).
fell_down_to(4,horse,burden).
fell_down_under(4,horse,weight_equal).
fell_down_straightway_under(4,horse,weight_equal).
root(5,ROOT,go).
nsubj(5,go,you).
aux(5,go,must).
advmod(5,go,now).
case(5,war,to).
det(5,war,the).
nmod:to(5,go,war).
case(5,foot,on).
nmod:on(5,war,foot).
mark(5,transformed,for).
nsubj(5,transformed,you).
aux(5,transformed,have).
advcl:for(5,go,transformed).
dobj(5,transformed,me).
case(5,horse,from).
det(5,horse,a).
nmod:from(5,transformed,horse).
case(5,ass,into).
det(5,ass,an).
nmod:into(5,transformed,ass).
must_go_to(5,you,war).
have_transformed(5,you,me).
must_go_to(5,you,war_on_foot).
must_now_go_to(5,you,war_on_foot).
must_now_go_to(5,you,war).
root(6,ROOT,can).
cc(6,can,and).
advmod(6,can,how).
dobj(6,can,you).
dep(6,can,expect).
det(6,i,that).
nsubj(6,turn,i).
aux(6,turn,can).
advmod(6,turn,again).
ccomp(6,expect,turn).
compound:prt(6,turn,in).
det(6,moment,a).
dobj(6,turn,moment).
case(6,ass,from).
det(6,ass,an).
nmod:from(6,moment,ass).
case(6,horse,to).
det(6,horse,a).
nmod:to(6,turn,horse).
moment_from(6,i,ass).
again_turn_in_moment_to(6,i,horse).
turn_in(6,i,moment_from_ass).
again_turn_in(6,i,moment).
turn_in(6,i,moment).
again_turn_in(6,i,moment_from_ass).
turn_in_moment_to(6,i,horse).
