root(0,ROOT,popular).
det(0,hare,a).
nsubj(0,popular,hare).
cop(0,popular,was).
advmod(0,popular,very).
case(0,beasts,with).
det(0,beasts,the).
amod(0,beasts,other).
nmod:with(0,popular,beasts).
dobj(0,claimed,beasts).
nsubj:xsubj(0,friends,beasts).
ref(0,beasts,who).
nsubj(0,claimed,all).
acl:relcl(0,beasts,claimed).
mark(0,friends,to).
cop(0,friends,be).
nmod:poss(0,friends,her).
xcomp(0,claimed,friends).
was(0,hare,very_popular).
was(0,hare,popular).
claimed(0,all,her_friends).
be(0,all,her_friends).
root(1,ROOT,day).
cc(1,day,but).
nummod(1,day,one).
nsubj(1,heard,she).
nsubj(1,hoped,she).
nsubj:xsubj(1,escape,she).
acl:relcl(1,day,heard).
det(1,hounds,the).
dobj(1,heard,hounds).
acl(1,hounds,approaching).
cc(1,heard,and).
acl:relcl(1,day,hoped).
conj:and(1,heard,hoped).
mark(1,escape,to).
xcomp(1,hoped,escape).
dobj(1,escape,them).
case(1,aid,by).
det(1,aid,the).
nmod:by(1,escape,aid).
case(1,friends,of).
nmod:poss(1,friends,her).
amod(1,friends,many).
nmod:of(1,aid,friends).
heard(1,she,hounds).
heard(1,she,hounds_approaching).
root(2,ROOT,went).
mark(2,went,so).
nsubj(2,went,she).
nsubj(2,asked,she).
case(2,horse,to).
det(2,horse,the).
nmod:to(2,went,horse).
cc(2,went,and).
conj:and(2,went,asked).
dobj(2,asked,him).
nsubj:xsubj(2,carry,him).
mark(2,carry,to).
xcomp(2,asked,carry).
dobj(2,carry,her).
advmod(2,carry,away).
case(2,hounds,from).
det(2,hounds,the).
nmod:from(2,carry,hounds).
case(2,back,on).
nmod:poss(2,back,his).
nmod:on(2,hounds,back).
went_to(2,she,horse).
carry(2,him,her).
carry_away(2,him,her).
asked(2,she,him).
root(3,ROOT,declined).
cc(3,declined,but).
nsubj(3,declined,he).
xcomp(3,declined,stating).
mark(3,had,that).
nsubj(3,had,he).
ccomp(3,stating,had).
amod(3,work,important).
dobj(3,had,work).
mark(3,do,to).
acl:to(3,work,do).
case(3,master,for).
nmod:poss(3,master,his).
nmod:for(3,do,master).
had(3,he,work_do).
had(3,he,work_do_for_his_master).
do_for(3,work,his_master).
had(3,he,important_work_do).
do_for(3,important_work,his_master).
declined(3,he,stating).
had(3,he,important_work_do_for_his_master).
root(4,ROOT,felt).
nsubj(4,felt,he).
xcomp(4,felt,sure).
felt(4,he,sure).
root(5,ROOT,said).
nsubj(5,said,he).
root(6,ROOT,come).
mark(6,come,that).
nsubj(6,come,all).
nmod:poss(6,friends,her).
amod(6,friends,other).
dep(6,all,friends).
aux(6,come,would).
case(6,assistance,to).
nmod:poss(6,assistance,her).
nmod:to(6,come,assistance).
would_come_to(6,all,her_assistance).
root(7,ROOT,applied).
nsubj(7,applied,she).
nsubj(7,hoped,she).
advmod(7,applied,then).
case(7,bull,to).
det(7,bull,the).
nmod:to(7,applied,bull).
cc(7,applied,and).
conj:and(7,applied,hoped).
mark(7,repel,that).
nsubj(7,repel,he).
aux(7,repel,would).
ccomp(7,hoped,repel).
det(7,hounds,the).
dobj(7,repel,hounds).
case(7,horns,with).
nmod:poss(7,horns,his).
nmod:with(7,repel,horns).
repel_hounds_with(7,he,his_horns).
applied_to(7,she,bull).
repel(7,he,hounds).
root(8,ROOT,replied).
det(8,bull,the).
nsubj(8,replied,bull).
root(9,ROOT,sorry).
nsubj(9,sorry,i).
cop(9,sorry,am).
advmod(9,sorry,very).
cc(9,have,but).
nsubj(9,have,i).
ccomp(9,sorry,have).
det(9,appointment,an).
dobj(9,have,appointment).
case(9,lady,with).
det(9,lady,a).
nmod:with(9,appointment,lady).
is_with(9,appointment,lady).
have(9,i,appointment_with_lady).
am(9,i,sorry).
am(9,i,very_sorry).
have(9,i,appointment).
root(10,ROOT,feel).
cc(10,feel,but).
nsubj(10,feel,i).
xcomp(10,feel,sure).
mark(10,do,that).
nmod:poss(10,friend,our).
nsubj(10,do,friend).
det(10,goat,the).
dep(10,friend,goat).
aux(10,do,will).
ccomp(10,sure,do).
dobj(10,want,what).
nsubj(10,want,you).
ccomp(10,do,want).
feel(10,i,sure).
root(11,ROOT,feared).
det(11,goat,the).
nsubj(11,feared,goat).
advmod(11,feared,however).
mark(11,do,that).
nmod:poss(11,back,his).
nsubj(11,do,back).
aux(11,do,might).
ccomp(11,feared,do).
dep(11,do,her).
det(11,harm,some).
dobj(11,do,harm).
mark(11,took,if).
nsubj(11,took,he).
dep(11,harm,took).
dobj(11,took,her).
case(11,it,upon).
nmod:upon(11,took,it).
took(11,he,her).
do(11,his_back,harm).
root(12,ROOT,friend).
det(12,ram,the).
nsubj(12,friend,ram).
nsubj(12,felt,he).
acl:relcl(12,ram,felt).
xcomp(12,felt,sure).
cop(12,friend,was).
det(12,friend,the).
amod(12,friend,proper).
mark(12,apply,to).
acl:to(12,friend,apply).
nmod(12,apply,to).
felt(12,he,sure).
root(13,ROOT,went).
mark(13,went,so).
nsubj(13,went,she).
nsubj(13,told,she).
case(13,ram,to).
det(13,ram,the).
nmod:to(13,went,ram).
cc(13,went,and).
conj:and(13,went,told).
nsubj(13,case,him).
det(13,case,the).
xcomp(13,told,case).
went_to(13,she,ram).
told(13,she,him_case).
root(14,ROOT,replied).
det(14,ram,the).
nsubj(14,replied,ram).
root(15,ROOT,time).
det(15,time,another).
nmod:poss(15,friend,my).
amod(15,friend,dear).
dep(15,time,friend).
root(16,ROOT,like).
nsubj(16,like,i).
nsubj:xsubj(16,interfere,i).
aux(16,like,do).
neg(16,like,not).
mark(16,interfere,to).
xcomp(16,like,interfere).
case(16,occasion,on).
det(16,occasion,the).
amod(16,occasion,present).
nmod:on(16,interfere,occasion).
mark(16,known,as).
nsubjpass(16,known,hounds).
nsubj:xsubj(16,eat,hounds).
aux(16,known,have).
auxpass(16,known,been).
advcl:as(16,interfere,known).
mark(16,eat,to).
xcomp(16,known,eat).
dobj(16,eat,sheep).
cc(16,sheep,as).
mwe(16,as,well).
mwe(16,as,as).
dobj(16,eat,hares).
conj:and(16,sheep,hares).
root(17,ROOT,applied).
det(17,hare,the).
nsubj(17,applied,hare).
advmod(17,applied,then).
case(17,hope,as).
det(17,hope,a).
amod(17,hope,last).
nmod:as(17,applied,hope).
case(17,calf,to).
det(17,calf,the).
nmod:to(17,hope,calf).
nsubj(17,regretted,calf).
ref(17,calf,who).
acl:relcl(17,calf,regretted).
mark(17,unable,that).
nsubj(17,unable,he).
nsubj:xsubj(17,help,he).
cop(17,unable,was).
ccomp(17,regretted,unable).
mark(17,help,to).
xcomp(17,unable,help).
dobj(17,help,her).
mark(17,like,as).
nsubj(17,like,he).
nsubj:xsubj(17,take,he).
aux(17,like,did).
neg(17,like,not).
advcl:as(17,help,like).
mark(17,take,to).
xcomp(17,like,take).
det(17,responsibility,the).
dobj(17,take,responsibility).
case(17,himself,upon).
nmod:upon(17,take,himself).
case(17,persons,as).
advmod(17,many,so).
amod(17,persons,many).
amod(17,persons,older).
nmod:as(17,applied,persons).
mark(17,declined,than).
nsubj(17,declined,himself).
aux(17,declined,had).
dep(17,persons,declined).
det(17,task,the).
dobj(17,declined,task).
was(17,he,unable).
take_responsibility_upon(17,he,himself).
root(18,ROOT,time).
case(18,time,by).
det(18,time,this).
det(18,hounds,the).
nsubj(18,near,hounds).
cop(18,near,were).
advmod(18,near,quite).
acl:relcl(18,time,near).
cc(18,near,and).
det(18,hare,the).
nsubj(18,took,hare).
nsubj(18,escaped,hare).
acl:relcl(18,time,took).
conj:and(18,near,took).
case(18,heels,to).
nmod:poss(18,heels,her).
nmod:to(18,took,heels).
cc(18,took,and).
advmod(18,escaped,luckily).
conj:and(18,near,escaped).
conj:and(18,took,escaped).
were(18,hounds,quite_near).
were(18,hounds,near).
took_to(18,hare,her_heels).
