root(0,ROOT,seen).
det(0,nightingale,a).
nsubjpass(0,seen,nightingale).
acl(0,nightingale,sitting).
advmod(0,sitting,aloft).
case(0,oak,upon).
det(0,oak,an).
nmod:upon(0,sitting,oak).
cc(0,oak,and).
nmod:upon(0,sitting,singing).
conj:and(0,oak,singing).
case(0,wont,according).
mwe(0,according,to).
nmod:poss(0,wont,his).
nmod:according_to(0,oak,wont).
auxpass(0,seen,was).
case(0,hawk,by).
det(0,hawk,a).
nmod:agent(0,seen,hawk).
nsubj(0,swooped,hawk).
nsubj(0,seized,hawk).
ref(0,hawk,who).
cop(0,need,being).
case(0,need,in).
csubj(0,swooped,need).
case(0,food,of).
nmod:of(0,need,food).
acl:relcl(0,hawk,swooped).
advmod(0,swooped,down).
cc(0,swooped,and).
acl:relcl(0,hawk,seized).
conj:and(0,swooped,seized).
dobj(0,seized,him).
seized(0,need,him).
was(0,nightingale,seen).
root(1,ROOT,nightingale).
det(1,nightingale,the).
dep(1,nightingale,about).
mark(1,lose,to).
xcomp(1,about,lose).
nmod:poss(1,life,his).
nsubj(1,begged,life).
advmod(1,begged,earnestly).
ccomp(1,lose,begged).
det(1,hawk,the).
dobj(1,begged,hawk).
mark(1,let,to).
acl:to(1,hawk,let).
nsubj(1,go,him).
ccomp(1,let,go).
xcomp(1,go,saying).
mark(1,big,that).
nsubj(1,big,he).
nsubj:xsubj(1,satisfy,he).
cop(1,big,was).
neg(1,big,not).
ccomp(1,saying,big).
advmod(1,big,enough).
mark(1,satisfy,to).
xcomp(1,big,satisfy).
det(1,hunger,the).
dobj(1,satisfy,hunger).
case(1,hawk,of).
det(1,hawk,a).
nmod:of(1,hunger,hawk).
dobj(1,wanted,hawk).
ref(1,hawk,who).
mark(1,wanted,if).
nsubj(1,wanted,he).
acl:relcl(1,hawk,wanted).
nsubj(1,ought,food).
nsubj:xsubj(1,pursue,food).
ccomp(1,wanted,ought).
mark(1,pursue,to).
xcomp(1,ought,pursue).
det(1,birds,the).
amod(1,birds,larger).
dobj(1,pursue,birds).
root(2,ROOT,said).
det(2,hawk,the).
nsubj(2,said,hawk).
acl(2,hawk,interrupting).
dobj(2,interrupting,him).
root(3,ROOT,lost).
nsubj(3,lost,i).
aux(3,lost,should).
advmod(3,lost,indeed).
aux(3,lost,have).
nmod:poss(3,senses,my).
dobj(3,lost,senses).
mark(3,let,if).
nsubj(3,let,i).
aux(3,let,should).
advcl:if(3,lost,let).
xcomp(3,let,go).
nsubj(3,ready,food).
xcomp(3,go,ready).
case(3,hand,in).
nmod:poss(3,hand,my).
nmod:in(3,ready,hand).
case(3,sake,for).
det(3,sake,the).
nmod:for(3,hand,sake).
mark(3,pursuing,of).
acl:of(3,sake,pursuing).
dobj(3,pursuing,birds).
nsubj(3,even,birds).
ref(3,birds,which).
cop(3,even,are).
neg(3,even,not).
advmod(3,even,yet).
acl:relcl(3,birds,even).
case(3,sight,within).
nmod:within(3,even,sight).
should_let(3,i,go).
ready_in(3,food,my_hand).
go(3,i,food_ready_in_my_hand).
go(3,i,food_ready).
