root(0,ROOT,saw).
det(0,heifer,a).
nsubj(0,saw,heifer).
nsubj(0,tormented,heifer).
det(0,ox,an).
dobj(0,saw,ox).
advmod(0,saw,hard).
case(0,work,at).
nmod:at(0,saw,work).
acl(0,work,harnessed).
mark(0,plow,to).
advmod(0,plow,a).
xcomp(0,harnessed,plow).
cc(0,saw,and).
conj:and(0,saw,tormented).
dobj(0,tormented,him).
case(0,reflections,with).
nmod:with(0,tormented,reflections).
case(0,fate,on).
nmod:poss(0,fate,his).
amod(0,fate,unhappy).
nmod:on(0,reflections,fate).
mark(0,compelled,in).
auxpass(0,compelled,being).
advcl:in(0,tormented,compelled).
case(0,labor,to).
nmod:to(0,compelled,labor).
tormented(0,heifer,him).
saw(0,heifer,ox).
saw_hard(0,heifer,ox).
saw_ox_hard_at(0,heifer,work).
saw_ox_at(0,heifer,work).
saw_ox_hard_at(0,heifer,work_harnessed).
saw_ox_at(0,heifer,work_harnessed).
root(1,ROOT,released).
advmod(1,festival,shortly).
advmod(1,festival,afterwards).
case(1,festival,at).
det(1,festival,the).
compound(1,festival,harvest).
advcl:at(1,released,festival).
det(1,owner,the).
nsubj(1,released,owner).
nsubj(1,bound,owner).
nsubj(1,led,owner).
det(1,ox,the).
dobj(1,released,ox).
case(1,yoke,from).
nmod:poss(1,yoke,his).
nmod:from(1,released,yoke).
cc(1,released,but).
conj:but(1,released,bound).
det(1,heifer,the).
dobj(1,bound,heifer).
case(1,cords,with).
nmod:with(1,bound,cords).
cc(1,released,and).
conj:but(1,released,led).
dobj(1,led,him).
advmod(1,led,away).
case(1,altar,to).
det(1,altar,the).
nmod:to(1,away,altar).
mark(1,slain,to).
auxpass(1,slain,be).
advcl:to(1,led,slain).
case(1,honor,in).
nmod:in(1,slain,honor).
case(1,occasion,of).
det(1,occasion,the).
nmod:of(1,honor,occasion).
released_ox_at(1,owner,shortly_harvest_festival).
bound_heifer_with(1,owner,cords).
led(1,owner,him).
released_ox_at(1,owner,harvest_festival).
bound_with(1,owner,cords).
bound(1,owner,heifer).
led_away(1,owner,him).
released(1,owner,ox).
released_ox_at(1,owner,shortly_afterwards_harvest_festival).
released_ox_at(1,owner,afterwards_harvest_festival).
root(2,ROOT,saw).
det(2,ox,the).
nsubj(2,saw,ox).
nsubj(2,said,ox).
nsubjpass(2,done,what).
aux(2,done,was).
auxpass(2,done,being).
ccomp(2,saw,done).
cc(2,saw,and).
conj:and(2,saw,said).
case(2,smile,with).
det(2,smile,a).
nmod:with(2,said,smile).
case(2,heifer,to).
det(2,heifer,the).
nmod:to(2,said,heifer).
said_to(2,ox,heifer).
said_with(2,ox,smile).
root(3,ROOT,allowed).
case(3,this,for).
nmod:for(3,allowed,this).
nsubjpass(3,allowed,you).
nsubj:xsubj(3,live,you).
auxpass(3,allowed,were).
mark(3,live,to).
xcomp(3,allowed,live).
case(3,idleness,in).
nmod:in(3,live,idleness).
mark(3,were,because).
nsubj(3,were,you).
nsubjpass:xsubj(3,sacrificed,you).
advcl:because(3,live,were).
advmod(3,were,presently).
mark(3,sacrificed,to).
auxpass(3,sacrificed,be).
xcomp(3,were,sacrificed).
were(3,you,allowed).
live(3,you,were_presently).
were_allowed(3,you,live_in_idleness).
live_in(3,you,idleness).
live(3,you,were).
were_allowed(3,you,live).
were_allowed_for(3,you,this).
