root(0,ROOT,had).
det(0,man,a).
nsubj(0,had,man).
nummod(0,gamecocks,two).
dobj(0,had,gamecocks).
case(0,poultry-yard,in).
nmod:poss(0,poultry-yard,his).
nmod:in(0,gamecocks,poultry-yard).
had(0,man,two_gamecocks).
is_in(0,two_gamecocks,his_poultry-yard).
had(0,man,two_gamecocks_in_his_poultry-yard).
root(1,ROOT,day).
nummod(1,day,one).
case(1,chance,by).
nmod:by(1,day,chance).
nsubj(1,found,he).
acl:relcl(1,chance,found).
det(1,partridge,a).
amod(1,partridge,tame).
dobj(1,found,partridge).
case(1,sale,for).
nmod:for(1,found,sale).
found(1,he,partridge).
found(1,he,tame_partridge).
found_partridge_for(1,he,sale).
root(2,ROOT,purchased).
nsubj(2,purchased,he).
nsubj(2,brought,he).
dobj(2,purchased,it).
cc(2,purchased,and).
conj:and(2,purchased,brought).
dobj(2,brought,it).
advmod(2,brought,home).
mark(2,reared,to).
auxpass(2,reared,be).
advcl:to(2,brought,reared).
case(2,gamecocks,with).
nmod:poss(2,gamecocks,his).
nmod:with(2,reared,gamecocks).
purchased(2,he,it).
brought_home(2,he,it).
brought(2,he,it).
root(3,ROOT,put).
advmod(3,put,when).
det(3,partridge,the).
nsubjpass(3,put,partridge).
nsubjpass(3,supposed,partridge).
auxpass(3,put,was).
case(3,poultry-yard,into).
det(3,poultry-yard,the).
nmod:into(3,put,poultry-yard).
nsubj(3,struck,they).
nsubj(3,followed,they).
acl:relcl(3,poultry-yard,struck).
case(3,it,at).
nmod:at(3,struck,it).
cc(3,struck,and).
acl:relcl(3,poultry-yard,followed).
conj:and(3,struck,followed).
dobj(3,followed,it).
case(3,so,about).
advmod(3,followed,so).
mark(3,became,that).
det(3,partridge,the).
nsubj(3,became,partridge).
ccomp(3,followed,became).
advmod(3,troubled,grievously).
xcomp(3,became,troubled).
cc(3,put,and).
conj:and(3,put,supposed).
mark(3,treated,that).
nsubjpass(3,treated,he).
auxpass(3,treated,was).
advmod(3,treated,thus).
advmod(3,treated,evilly).
ccomp(3,supposed,treated).
mark(3,stranger,because).
nsubj(3,stranger,he).
cop(3,stranger,was).
det(3,stranger,a).
advcl:because(3,treated,stranger).
struck_at(3,they,it).
became(3,partridge,grievously_troubled).
followed(3,they,it).
became(3,partridge,troubled).
followed_so(3,they,it).
was(3,partridge,put).
was(3,partridge,when_put).
root(4,ROOT,long).
dep(4,long,not).
advmod(4,saw,afterwards).
nsubj(4,saw,he).
ccomp(4,long,saw).
det(4,cocks,the).
nsubj(4,beaten,cocks).
dep(4,cocks,fighting).
advmod(4,fighting,together).
cc(4,fighting,and).
neg(4,separating,not).
dep(4,cocks,separating).
conj:and(4,fighting,separating).
case(4,one,before).
nmod:before(4,separating,one).
aux(4,beaten,had).
advmod(4,beaten,well).
ccomp(4,saw,beaten).
det(4,other,the).
dobj(4,beaten,other).
well_beaten(4,cocks,other).
root(5,ROOT,said).
nsubj(5,said,he).
advmod(5,said,then).
case(5,himself,to).
nmod:to(5,said,himself).
said_to(5,he,himself).
root(6,ROOT,shall).
nsubj(6,shall,i).
neg(6,longer,no).
advmod(6,shall,longer).
ccomp(6,shall,distress).
dobj(6,distress,myself).
mark(6,struck,at).
auxpass(6,struck,being).
acl:at(6,myself,struck).
case(6,gamecocks,at).
case(6,gamecocks,by).
det(6,gamecocks,these).
nmod:agent(6,struck,gamecocks).
advmod(6,see,when).
nsubj(6,see,i).
advcl(6,shall,see).
mark(6,refrain,that).
nsubj(6,refrain,they).
aux(6,refrain,can).
neg(6,refrain,not).
advmod(6,refrain,even).
ccomp(6,see,refrain).
mark(6,quarreling,from).
advcl:from(6,refrain,quarreling).
case(6,other,with).
det(6,other,each).
nmod:with(6,quarreling,other).
being_struck_at(6,myself,at_gamecocks).
being(6,myself,struck).
quarreling_with(6,they,other).
