root(0,ROOT,driven).
det:predet(0,goods,all).
det(0,goods,the).
nsubjpass(0,driven,goods).
auxpass(0,driven,were).
advmod(0,driven,once).
compound:prt(0,driven,out).
case(0,ills,by).
det(0,ills,the).
nmod:agent(0,driven,ills).
case(0,share,from).
det(0,share,that).
amod(0,share,common).
nmod:from(0,driven,share).
dobj(0,had,share).
ref(0,share,which).
nsubj(0,had,they).
dep(0,had,each).
acl:relcl(0,share,had).
case(0,affairs,in).
det(0,affairs,the).
nmod:in(0,had,affairs).
case(0,mankind,of).
nmod:of(0,affairs,mankind).
had_in(0,they,affairs_of_mankind).
were_driven_out_by(0,goods,ills).
had_in(0,they,affairs).
were_once_driven_out_by(0,goods,ills).
root(1,ROOT,prevailed).
mark(1,prevailed,for).
det(1,ills,the).
nsubj(1,prevailed,ills).
nsubj:xsubj(1,possess,ills).
case(1,reason,by).
nmod:by(1,ills,reason).
case(1,numbers,of).
nmod:poss(1,numbers,their).
nmod:of(1,reason,numbers).
aux(1,prevailed,had).
mark(1,possess,to).
xcomp(1,prevailed,possess).
det(1,earth,the).
dobj(1,possess,earth).
possess(1,ills,earth).
root(2,ROOT,wafted).
det(2,goods,the).
nsubj(2,wafted,goods).
nsubj(2,asked,goods).
dobj(2,wafted,themselves).
case(2,heaven,to).
nmod:to(2,wafted,heaven).
cc(2,wafted,and).
conj:and(2,wafted,asked).
case(2,vengeance,for).
det(2,vengeance,a).
amod(2,vengeance,righteous).
nmod:for(2,asked,vengeance).
case(2,persecutors,on).
nmod:poss(2,persecutors,their).
nmod:on(2,asked,persecutors).
wafted(2,goods,themselves).
asked_on(2,goods,their_persecutors).
asked_for(2,goods,righteous_vengeance).
asked_for(2,goods,vengeance).
root(3,ROOT,entreated).
nsubj(3,entreated,they).
nsubjpass(3,engaged,they).
dobj(3,entreated,jupiter).
mark(3,associated,that).
nsubjpass(3,associated,they).
aux(3,associated,might).
neg(3,longer,no).
advmod(3,associated,longer).
auxpass(3,associated,be).
ccomp(3,entreated,associated).
case(3,ills,with).
det(3,ills,the).
nmod:with(3,associated,ills).
mark(3,had,as).
nsubj(3,had,they).
nsubj(3,live,they).
advcl:as(3,associated,had).
dobj(3,had,nothing).
case(3,common,in).
nmod:in(3,nothing,common).
cc(3,had,and).
aux(3,live,could).
neg(3,live,not).
advcl:as(3,associated,live).
conj:and(3,had,live).
advmod(3,live,together).
cc(3,entreated,but).
auxpass(3,engaged,were).
conj:but(3,entreated,engaged).
case(3,warfare,in).
amod(3,warfare,unceasing).
nmod:in(3,engaged,warfare).
entreated(3,they,jupiter).
were_engaged_in(3,they,unceasing_warfare).
were_engaged_in(3,they,warfare).
nothing_in(3,they,common).
be_associated_with(3,they,ills).
were(3,they,engaged).
be(3,they,associated).
is_in(3,nothing,common).
root(4,ROOT,laid).
cc(4,laid,and).
mark(4,laid,that).
det(4,law,an).
amod(4,law,indissoluble).
nsubjpass(4,laid,law).
aux(4,laid,might).
auxpass(4,laid,be).
compound:prt(4,laid,down).
case(4,protection,for).
nmod:poss(4,protection,their).
amod(4,protection,future).
nmod:for(4,laid,protection).
root(5,ROOT,granted).
nsubj(5,granted,jupiter).
nsubj(5,decreed,jupiter).
nmod:poss(5,request,their).
dobj(5,granted,request).
cc(5,granted,and).
conj:and(5,granted,decreed).
mark(5,visit,that).
nsubj(5,visit,henceforth).
det(5,ills,the).
dep(5,henceforth,ills).
aux(5,visit,should).
ccomp(5,decreed,visit).
det(5,earth,the).
dobj(5,visit,earth).
case(5,company,in).
nmod:in(5,earth,company).
case(5,other,with).
det(5,other,each).
nmod:with(5,visit,other).
cc(5,visit,but).
mark(5,enter,that).
det(5,goods,the).
nsubj(5,enter,goods).
aux(5,enter,should).
advmod(5,enter,one).
case(5,one,by).
nmod:by(5,one,one).
ccomp(5,decreed,enter).
conj:but(5,visit,enter).
det(5,habitations,the).
dobj(5,enter,habitations).
case(5,men,of).
nmod:of(5,habitations,men).
is_in(5,earth,company).
visit(5,henceforth,earth).
should_enter(5,goods,habitations).
visit(5,henceforth,earth_in_company).
earth_in(5,henceforth,company).
habitations_of(5,goods,men).
granted(5,jupiter,their_request).
should_enter(5,goods,habitations_of_men).
root(6,ROOT,arises).
advmod(6,it,hence).
nsubj(6,arises,it).
mark(6,abound,that).
nsubj(6,abound,ills).
ccomp(6,arises,abound).
mark(6,come,for).
nsubj(6,come,they).
nsubj(6,come,they).
nsubj(6,come,they).
advcl:for(6,abound,come).
advcl:for(6,abound,come).
conj:and(6,come,come).
advcl:for(6,abound,come).
conj:but(6,come,come).
neg(6,come,not).
nmod:npmod(6,not,one).
case(6,one,by).
nmod:by(6,not,one).
cc(6,come,but).
case(6,troops,in).
nmod:in(6,come,troops).
cc(6,come,and).
case(6,means,by).
neg(6,means,no).
nmod:by(6,come,means).
advmod(6,proceed,singly).
mark(6,proceed,while).
det(6,goods,the).
nsubj(6,proceed,goods).
nsubjpass(6,given,goods).
advcl:while(6,come,proceed).
case(6,jupiter,from).
nmod:from(6,proceed,jupiter).
cc(6,proceed,and).
auxpass(6,given,are).
advcl:while(6,come,given).
conj:and(6,proceed,given).
neg(6,all,not).
advmod(6,all,alike).
case(6,all,to).
advcl:to(6,given,all).
cc(6,and,but).
advmod(6,and,singly).
dep(6,given,and).
advmod(6,and,separately).
root(7,ROOT,one).
cc(7,one,and).
case(7,one,by).
nmod:by(7,one,one).
case(7,those,to).
nmod:to(7,one,those).
nsubj(7,able,who).
nsubj:xsubj(7,discern,who).
cop(7,able,are).
advcl(7,one,able).
mark(7,discern,to).
xcomp(7,able,discern).
dobj(7,discern,them).
