%% a very poor man a carpenter by trade had a wooden image of mercury before which he made offerings day by day and begged the idol to make him rich but in spite of his entreaties he became poorer and poorer.
% dependencies.
root(0,root,man).
det(0,man,a).
advmod(0,poor,very).
amod(0,man,poor).
det(0,carpenter,a).
nsubj(0,have,carpenter).
case(0,trade,by).
nmod:by(0,carpenter,trade).
acl:relcl(0,man,have).
det(0,image,a).
amod(0,image,wooden).
dobj(0,have,image).
case(0,mercury,of).
nmod:of(0,image,mercury).
mark(0,make,before).
dobj(0,make,which).
nsubj(0,make,he).
nsubj(0,beg,he).
acl:before(0,man,make).
dobj(0,make,offering).
nmod:tmod(0,make,day).
case(0,day,by).
nmod:by(0,make,day).
cc(0,make,and).
acl:before(0,man,beg).
conj:and(0,make,beg).
det(0,idol,the).
dobj(0,beg,idol).
nsubj:xsubj(0,make,idol).
mark(0,make,to).
xcomp(0,beg,make).
nsubj(0,become,he).
dep(0,become,rich).
cc(0,entreaty,but).
case(0,entreaty,in).
mwe(0,in,spite).
mwe(0,in,of).
nmod:poss(0,entreaty,he).
nmod:in_spite_of(0,rich,entreaty).
nsubj(0,become,he).
xcomp(0,make,become).
xcomp(0,become,poorer).
cc(0,poorer,and).
xcomp(0,become,poorer).
conj:and(0,poorer,poorer).
% relations.
aos(0,have,carpenter,wooden_image).
aos(0,become,he,poorer).
aos(0,make,idol,he_become).
aos(0,have,carpenter,wooden_image_of_mercury).
aos(0,become,he,poorer).
aos(0,make,idol,he_become).
aos(0,have,carpenter,image).
aos(0,carpenter_by,image,trade).
aos(0,have,carpenter,image_of_mercury).
aos(0,make,he,offering).
aos(0,beg,he,idol).
aos(0,make_offering_at_time,he,day).
aos(0,make,idol,he_he_become).
aos(0,carpenter_by,wooden_image,trade).
aos(0,make_offering_by,he,day).
%% at last being very angry he took his image down from its pedestal and dashed it against the wall.
% dependencies.
root(1,root,angry).
dep(1,angry,at).
advmod(1,angry,last).
cop(1,angry,be).
advmod(1,angry,very).
nsubj(1,take,he).
nsubj(1,dash,he).
ccomp(1,angry,take).
nmod:poss(1,image,he).
dobj(1,take,image).
advmod(1,take,down).
case(1,pedestal,from).
nmod:poss(1,pedestal,its).
nmod:from(1,down,pedestal).
cc(1,take,and).
ccomp(1,angry,dash).
conj:and(1,take,dash).
dobj(1,dash,it).
case(1,wall,against).
det(1,wall,the).
nmod:against(1,dash,wall).
% relations.
aos(1,take_down,he,he_image).
aos(1,take,he,he_image).
aos(1,dash,he,it).
%% when its head was knocked off out came a stream of gold which the carpenter quickly picked up and said.
% dependencies.
root(2,root,come).
advmod(2,come,when).
nmod:poss(2,head,its).
nsubj(2,come,head).
auxpass(2,knock,be).
acl:relcl(2,head,knock).
compound:prt(2,knock,off).
advmod(2,knock,out).
det(2,stream,a).
dobj(2,come,stream).
dobj(2,pick,stream).
case(2,gold,of).
nmod:of(2,stream,gold).
ref(2,stream,which).
det(2,carpenter,the).
nsubj(2,pick,carpenter).
nsubj(2,say,carpenter).
advmod(2,pick,quickly).
acl:relcl(2,stream,pick).
compound:prt(2,pick,up).
cc(2,pick,and).
acl:relcl(2,stream,say).
conj:and(2,pick,say).
% relations.
%% well i think thou art altogether contradictory and unreasonable.
% dependencies.
root(3,root,i).
dep(3,i,well).
acl:relcl(3,i,think).
nsubj(3,art,thou).
xcomp(3,think,art).
advmod(3,contradictory,altogether).
amod(3,art,contradictory).
cc(3,contradictory,and).
amod(3,art,unreasonable).
conj:and(3,contradictory,unreasonable).
% relations.
%% for when i paid you honor i reaped no benefits but now that i maltreat you i am loaded with an abundance of riches.
% dependencies.
root(4,root,reap).
mark(4,reap,for).
advmod(4,reap,when).
nsubj(4,reap,i).
acl(4,i,pay).
nsubj(4,honor,you).
ccomp(4,pay,honor).
dobj(4,honor,i).
neg(4,benefit,no).
dobj(4,reap,benefit).
cc(4,reap,but).
advmod(4,load,now).
mark(4,load,that).
compound(4,maltreat,i).
nsubjpass(4,load,maltreat).
dep(4,maltreat,you).
dep(4,maltreat,i).
auxpass(4,load,be).
advcl:that(4,reap,load).
case(4,abundance,with).
det(4,abundance,a).
nmod:with(4,load,abundance).
case(4,riches,of).
nmod:of(4,abundance,riches).
% relations.
aos(4,be_load_with,i_maltreat,abundance).
aos(4,now_be_load_with,i_maltreat,abundance_of_riches).
aos(4,be,i_maltreat,load).
aos(4,be_load_with,i_maltreat,abundance_of_riches).
aos(4,be,i_maltreat,now_load).
aos(4,now_be_load_with,i_maltreat,abundance).
