root(0,ROOT,sought).
det(0,goatherd,a).
nsubj(0,sought,goatherd).
nsubj:xsubj(0,bring,goatherd).
aux(0,sought,had).
mark(0,bring,to).
xcomp(0,sought,bring).
compound:prt(0,bring,back).
det(0,goat,a).
amod(0,goat,stray).
dobj(0,bring,goat).
case(0,flock,to).
nmod:poss(0,flock,his).
nmod:to(0,bring,flock).
bring_back(0,goatherd,goat).
bring_back_goat_to(0,goatherd,his_flock).
bring_back(0,goatherd,stray_goat).
root(1,ROOT,whistled).
nsubj(1,whistled,he).
nsubj(1,sounded,he).
cc(1,whistled,and).
conj:and(1,whistled,sounded).
nmod:poss(1,horn,his).
dobj(1,sounded,horn).
case(1,vain,in).
nmod:in(1,sounded,vain).
sounded(1,he,his_horn).
root(2,ROOT,paid).
det(2,straggler,the).
nsubj(2,paid,straggler).
neg(2,attention,no).
dobj(2,paid,attention).
case(2,summons,to).
det(2,summons,the).
nmod:to(2,paid,summons).
root(3,ROOT,threw).
mark(3,threw,at).
amod(3,goatherd,last).
det(3,goatherd,the).
nsubj(3,threw,goatherd).
det(3,stone,a).
dobj(3,threw,stone).
cc(3,threw,and).
csubj(3,begged,breaking).
nmod:poss(3,horn,its).
dobj(3,breaking,horn).
conj:and(3,threw,begged).
det(3,goat,the).
dobj(3,begged,goat).
neg(3,tell,not).
mark(3,tell,to).
acl:to(3,goat,tell).
nmod:poss(3,master,his).
dobj(3,tell,master).
threw(3,last_goatherd,stone).
threw(3,goatherd,stone).
root(4,ROOT,replied).
det(4,goat,the).
nsubj(4,replied,goat).
root(5,ROOT,speak).
advmod(5,speak,why).
dep(5,why,you).
amod(5,fellow,silly).
dep(5,you,fellow).
det(5,horn,the).
nsubj(5,speak,horn).
aux(5,speak,will).
mark(5,silent,though).
nsubj(5,silent,i).
cop(5,silent,be).
advcl:though(5,speak,silent).
be(5,i,silent).
will_speak(5,horn,silent).
