%% a goatherd driving his flock from their pasture at eventide found some wild goats mingled among them and shut them up together with his own for the night.
% dependencies.
root(0,root,find).
det(0,goatherd,a).
nsubj(0,find,goatherd).
acl(0,goatherd,drive).
nmod:poss(0,flock,he).
dobj(0,drive,flock).
case(0,pasture,from).
nmod:poss(0,pasture,they).
nmod:from(0,drive,pasture).
case(0,eventide,at).
nmod:at(0,pasture,eventide).
det(0,goat,some).
amod(0,goat,wild).
nsubj(0,mingle,goat).
nsubj(0,shut,goat).
ccomp(0,find,mingle).
case(0,they,among).
nmod:among(0,mingle,they).
cc(0,mingle,and).
ccomp(0,find,shut).
conj:and(0,mingle,shut).
dobj(0,shut,they).
compound:prt(0,shut,up).
case(0,own,together).
mwe(0,together,with).
nmod:poss(0,own,he).
nmod:together_with(0,shut,own).
case(0,night,for).
det(0,night,the).
nmod:for(0,shut,night).
% relations.
drive_he_flock_from(0,goatherd,they_pasture).
mingle_among(0,wild_goat,they).
mingle_among(0,goat,they).
drive(0,goatherd,he_flock).
shut_up(0,goat,they).
drive_he_flock_from(0,goatherd,they_pasture_eventide).
shut_up(0,wild_goat,they).
%% the next day it snowed very hard so that he could not take the herd to their usual feeding places but was obliged to keep them in the fold.
% dependencies.
root(1,root,day).
det(1,day,the).
amod(1,day,next).
nsubj(1,snow,it).
acl:relcl(1,day,snow).
advmod(1,hard,very).
xcomp(1,snow,hard).
mark(1,take,so).
mwe(1,so,that).
nsubj(1,take,he).
aux(1,take,could).
neg(1,take,not).
advcl:so_that(1,snow,take).
det(1,herd,the).
dobj(1,take,herd).
case(1,place,to).
nmod:poss(1,place,they).
amod(1,place,usual).
compound(1,place,feeding).
nmod:to(1,take,place).
cc(1,oblige,but).
auxpass(1,oblige,be).
dep(1,day,oblige).
mark(1,keep,to).
xcomp(1,oblige,keep).
dobj(1,keep,they).
case(1,fold,in).
det(1,fold,the).
nmod:in(1,keep,fold).
% relations.
%% he gave his own goats just sufficient food to keep them alive but fed the strangers more abundantly in the hope of enticing them to stay with him and of making them his own.
% dependencies.
root(2,root,give).
nsubj(2,give,he).
nsubj(2,feed,he).
nmod:poss(2,goat,he).
amod(2,goat,own).
dep(2,give,goat).
advmod(2,sufficient,just).
amod(2,food,sufficient).
dobj(2,give,food).
mark(2,keep,to).
advcl:to(2,give,keep).
nsubj(2,alive,they).
xcomp(2,keep,alive).
cc(2,give,but).
conj:but(2,give,feed).
det(2,stranger,the).
dobj(2,feed,stranger).
advmod(2,abundantly,more).
advmod(2,feed,abundantly).
case(2,hope,in).
det(2,hope,the).
nmod:in(2,feed,hope).
mark(2,entice,of).
acl:of(2,hope,entice).
dobj(2,entice,they).
nsubj:xsubj(2,stay,they).
mark(2,stay,to).
xcomp(2,entice,stay).
case(2,he,with).
nmod:with(2,stay,he).
cc(2,hope,and).
mark(2,make,of).
nmod:in(2,feed,make).
conj:and(2,hope,make).
nsubj(2,own,they).
nmod:poss(2,own,he).
xcomp(2,make,own).
% relations.
give(2,he,just_sufficient_food).
feed(2,he,stranger).
keep(2,he,they_alive).
give(2,he,sufficient_food).
stay_with(2,they,he).
feed_more_abundantly(2,he,stranger).
feed_abundantly(2,he,stranger).
give(2,he,food).
give_food(2,he,keep).
%% when the thaw set in he led them all out to feed and the wild goats scampered away as fast as they could to the mountains.
% dependencies.
root(3,root,set).
advmod(3,set,when).
det(3,thaw,the).
nsubj(3,set,thaw).
mark(3,lead,in).
nsubj(3,lead,he).
advcl:in(3,set,lead).
dobj(3,lead,they).
dep(3,out,all).
advmod(3,lead,out).
mark(3,feed,to).
advcl:to(3,lead,feed).
cc(3,lead,and).
det(3,goat,the).
amod(3,goat,wild).
nsubj(3,scamper,goat).
advcl:in(3,set,scamper).
conj:and(3,lead,scamper).
advmod(3,fast,away).
advmod(3,fast,as).
advmod(3,scamper,fast).
mark(3,could,as).
nsubj(3,could,they).
advcl:as(3,scamper,could).
case(3,mountain,to).
det(3,mountain,the).
nmod:to(3,could,mountain).
% relations.
scamper_fast(3,wild_goat,they_could).
scamper_away_as_fast(3,goat,they_could).
scamper(3,goat,they_could_to_mountain).
scamper_fast(3,wild_goat,they_could_to_mountain).
scamper_as_fast(3,goat,they_could_to_mountain).
scamper_as_fast(3,goat,they_could).
scamper_away_fast(3,goat,they_could_to_mountain).
scamper_away_as_fast(3,wild_goat,they_could_to_mountain).
scamper(3,wild_goat,they_could_to_mountain).
lead(3,he,they).
scamper_away_fast(3,wild_goat,they_could).
scamper_as_fast(3,wild_goat,they_could).
scamper_away_fast(3,goat,they_could).
scamper_away_as_fast(3,goat,they_could_to_mountain).
scamper_fast(3,goat,they_could_to_mountain).
scamper_as_fast(3,wild_goat,they_could_to_mountain).
scamper(3,goat,they_could).
scamper(3,wild_goat,they_could).
scamper_fast(3,goat,they_could).
lead_out(3,he,they).
scamper_away_fast(3,wild_goat,they_could_to_mountain).
scamper_away_as_fast(3,wild_goat,they_could).
%% the goatherd scolded them for their ingratitude in leaving him when during the storm he had taken more care of them than of his own herd.
% dependencies.
root(4,root,scold).
det(4,goatherd,the).
nsubj(4,scold,goatherd).
dobj(4,scold,they).
case(4,ingratitude,for).
nmod:poss(4,ingratitude,they).
nmod:for(4,scold,ingratitude).
mark(4,leave,in).
advcl:in(4,scold,leave).
dobj(4,leave,he).
advmod(4,take,when).
case(4,storm,during).
det(4,storm,the).
nmod:during(4,take,storm).
nsubj(4,take,he).
aux(4,take,have).
advcl(4,leave,take).
advmod(4,take,more).
dobj(4,take,care).
case(4,they,of).
nmod:of(4,care,they).
case(4,herd,than).
case(4,herd,of).
nmod:poss(4,herd,he).
amod(4,herd,own).
nmod:of(4,take,herd).
% relations.
leave(4,goatherd,he).
have_take(4,he,care).
have_take_more(4,he,care_of_they).
have_take_more_care_than(4,he,than_he_own_herd).
have_take_more_care_during(4,he,storm).
have_take(4,he,care_of_they).
have_take_care_than(4,he,than_he_own_herd).
have_take_more(4,he,care).
have_take_more_care_than(4,he,than_he_herd).
have_take_care_during(4,he,storm).
scold(4,goatherd,they).
care_of(4,he,they).
have_take_care_than(4,he,than_he_herd).
%% one of them turning about said to him.
% dependencies.
root(5,root,say).
nsubj(5,say,one).
mark(5,turn,of).
nsubj(5,turn,they).
acl:of(5,one,turn).
advmod(5,turn,about).
case(5,he,to).
nmod:to(5,say,he).
% relations.
%% that is the very reason why we are so cautious.
% dependencies.
root(6,root,reason).
nsubj(6,reason,that).
cop(6,reason,be).
det(6,reason,the).
amod(6,reason,very).
advmod(6,cautious,why).
nsubj(6,cautious,we).
cop(6,cautious,be).
advmod(6,cautious,so).
acl:relcl(6,reason,cautious).
% relations.
be(6,we,why_cautious).
be(6,we,why_so_cautious).
be(6,we,cautious).
be(6,we,so_cautious).
%% for if you yesterday treated us better than the goats you have had so long it is plain also that if others came after us you would in the same manner prefer them to ourselves.
% dependencies.
root(7,root,have).
mark(7,have,for).
mark(7,treat,if).
nsubj(7,treat,you).
nmod:tmod(7,treat,yesterday).
advcl:if(7,have,treat).
nsubj(7,better,we).
xcomp(7,treat,better).
case(7,goat,than).
det(7,goat,the).
nmod:than(7,treat,goat).
nsubj(7,have,you).
aux(7,have,have).
advmod(7,long,so).
advmod(7,plain,long).
nsubj(7,plain,it).
cop(7,plain,be).
ccomp(7,have,plain).
advmod(7,plain,also).
mark(7,would,that).
mark(7,come,if).
nsubj(7,come,other).
advcl:if(7,would,come).
case(7,we,after).
nmod:after(7,come,we).
nsubj(7,would,you).
ccomp(7,plain,would).
mark(7,prefer,in).
det(7,manner,the).
amod(7,manner,same).
nsubj(7,prefer,manner).
advcl:in(7,have,prefer).
dobj(7,prefer,they).
case(7,ourselves,to).
nmod:to(7,prefer,ourselves).
% relations.
treat_than(7,you,goat).
treat_at_time(7,you,yesterday).
have_have(7,you,you_yesterday_treat_than_goat).
be(7,it,plain_also).
prefer(7,same_manner,they).
be(7,it,long_plain).
have_have(7,you,you_yesterday_treat).
be(7,it,long_plain_also).
be(7,it,plain).
be(7,it,so_long_plain).
be(7,it,so_long_plain_also).
have_have(7,you,you_treat_than_goat).
have_have(7,you,you_treat).
prefer(7,manner,they).
treat(7,you,we_better).
