root(0,ROOT,nourished).
det(0,hen,a).
nsubj(0,nourished,hen).
dep(0,hen,finding).
det(0,eggs,the).
dobj(0,finding,eggs).
case(0,viper,of).
det(0,viper,a).
nmod:of(0,eggs,viper).
cc(0,finding,and).
advmod(0,keeping,carefully).
dep(0,hen,keeping).
conj:and(0,finding,keeping).
nsubj(0,warm,them).
xcomp(0,keeping,warm).
dobj(0,nourished,them).
case(0,life,into).
nmod:into(0,nourished,life).
carefully_keeping(0,eggs,them_warm).
nourished(0,hen,them).
keeping(0,eggs,them_warm).
root(1,ROOT,a).
dep(1,a,swallow).
csubj(1,said,observing).
dobj(1,done,what).
nsubj(1,done,she).
aux(1,done,had).
ccomp(1,observing,done).
ccomp(1,swallow,said).
root(2,ROOT,creature).
dep(2,silly,you).
dep(2,creature,silly).
root(3,ROOT,hatched).
advmod(3,hatched,why).
aux(3,hatched,have).
nsubj(3,hatched,you).
det(3,vipers,these).
dobj(3,hatched,vipers).
dep(3,inflict,vipers).
ref(3,vipers,which).
advmod(3,grown,when).
nsubj(3,grown,they).
aux(3,grown,shall).
aux(3,grown,have).
advcl(3,inflict,grown).
aux(3,inflict,will).
acl:relcl(3,vipers,inflict).
dobj(3,inflict,injury).
case(3,all,on).
nmod:on(3,inflict,all).
acl(3,all,beginning).
case(3,yourself,with).
nmod:with(3,beginning,yourself).
