root(0,ROOT,persecuted).
det(0,hares,the).
nsubjpass(0,persecuted,hares).
auxpass(0,persecuted,were).
advmod(0,persecuted,so).
case(0,beasts,by).
det(0,beasts,the).
amod(0,beasts,other).
nmod:agent(0,persecuted,beasts).
nsubj(0,know,they).
nsubj:xsubj(0,go,they).
aux(0,know,did).
neg(0,know,not).
acl:relcl(0,beasts,know).
advmod(0,go,where).
mark(0,go,to).
xcomp(0,know,go).
were(0,hares,so_persecuted).
were(0,hares,persecuted).
root(1,ROOT,soon).
advmod(1,soon,as).
mark(1,saw,as).
nsubj(1,saw,they).
dep(1,soon,saw).
det(1,approach,a).
amod(1,approach,single).
compound(1,approach,animal).
dobj(1,saw,approach).
nsubj(1,used,them).
nsubj:xsubj(1,run,them).
case(1,they,off).
nmod:off(1,used,they).
acl:relcl(1,approach,used).
mark(1,run,to).
xcomp(1,used,run).
used(1,them,run).
used_off(1,them,they).
root(2,ROOT,day).
nummod(2,day,one).
nsubj(2,saw,they).
acl:relcl(2,day,saw).
det(2,troop,a).
dobj(2,saw,troop).
case(2,horses,of).
amod(2,horses,wild).
nmod:of(2,troop,horses).
dep(2,day,stampeding).
advmod(2,stampeding,about).
cc(2,stampeding,and).
case(2,panic,in).
advmod(2,panic,quite).
det(2,panic,a).
nmod:in(2,stampeding,panic).
det:predet(2,hares,all).
det(2,hares,the).
nsubj(2,scuttled,hares).
acl:relcl(2,panic,scuttled).
compound:prt(2,scuttled,off).
case(2,lake,to).
det(2,lake,a).
nmod:to(2,scuttled,lake).
advmod(2,panic,hard).
case(2,determined,by).
advcl:by(2,hard,determined).
mark(2,drown,to).
xcomp(2,determined,drown).
dobj(2,drown,themselves).
cc(2,drown,rather).
mwe(2,rather,than).
xcomp(2,determined,live).
conj:negcc(2,drown,live).
case(2,state,in).
amod(2,state,such).
det(2,state,a).
amod(2,state,continual).
nmod:in(2,live,state).
case(2,fear,of).
nmod:of(2,state,fear).
saw(2,they,troop_of_wild_horses).
scuttled_off_to(2,hares,lake).
troop_of(2,they,horses).
saw(2,they,troop_of_horses).
troop_of(2,they,wild_horses).
saw(2,they,troop).
root(3,ROOT,just).
cc(3,just,but).
mark(3,got,as).
nsubj(3,got,they).
dep(3,just,got).
case(3,bank,near).
det(3,bank,the).
nmod:near(3,got,bank).
case(3,lake,of).
det(3,lake,the).
nmod:of(3,bank,lake).
det(3,troop,a).
nsubj(3,scuttled,troop).
nsubj(3,jumped,troop).
case(3,frogs,of).
nmod:of(3,troop,frogs).
amod(3,frogs,frightened).
case(3,turn,in).
nmod:poss(3,turn,their).
nmod:in(3,frightened,turn).
case(3,approach,by).
det(3,approach,the).
nmod:by(3,turn,approach).
case(3,hares,of).
det(3,hares,the).
nmod:of(3,approach,hares).
ccomp(3,got,scuttled).
advmod(3,scuttled,off).
cc(3,scuttled,and).
ccomp(3,got,jumped).
conj:and(3,scuttled,jumped).
case(3,water,into).
det(3,water,the).
nmod:into(3,jumped,water).
jumped_into(3,troop,water).
root(4,ROOT,truly).
root(5,ROOT,said).
det:qmod(5,hares,one).
mwe(5,one,of).
det(5,hares,the).
nsubj(5,said,hares).
