%% a herdsman tending his flock in a forest lost a bull-calf from the fold.
% dependencies.
root(0,root,lose).
det(0,herdsman,a).
nsubj(0,lose,herdsman).
acl(0,herdsman,tend).
nmod:poss(0,flock,he).
dobj(0,tend,flock).
case(0,forest,in).
det(0,forest,a).
nmod:in(0,tend,forest).
det(0,bull-calf,a).
dobj(0,lose,bull-calf).
case(0,fold,from).
det(0,fold,the).
nmod:from(0,lose,fold).
% relations.
lose(0,herdsman,bull-calf).
tend_he_flock_in(0,herdsman,forest).
tend(0,herdsman,he_flock).
lose_bull-calf_from(0,herdsman,fold).
%% after a long and fruitless search he made a vow that if he could only discover the thief who had stolen the calf he would offer a lamb in sacrifice to hermes pan and the guardian deities of the forest.
% dependencies.
root(1,root,make).
case(1,search,after).
det(1,search,a).
amod(1,search,long).
cc(1,long,and).
conj:and(1,long,fruitless).
amod(1,search,fruitless).
nmod:after(1,make,search).
nsubj(1,make,he).
det(1,vow,a).
dobj(1,make,vow).
mark(1,offer,that).
mark(1,discover,if).
nsubj(1,discover,he).
aux(1,discover,could).
advmod(1,discover,only).
advcl:if(1,offer,discover).
det(1,thief,the).
dobj(1,discover,thief).
nsubj(1,steal,thief).
ref(1,thief,who).
aux(1,steal,have).
acl:relcl(1,thief,steal).
det(1,calf,the).
dobj(1,steal,calf).
nsubj(1,offer,he).
aux(1,offer,would).
ccomp(1,make,offer).
det(1,lamb,a).
dobj(1,offer,lamb).
case(1,sacrifice,in).
nmod:in(1,lamb,sacrifice).
case(1,pan,to).
compound(1,pan,herme).
nmod:to(1,offer,pan).
cc(1,pan,and).
det(1,deity,the).
compound(1,deity,guardian).
nmod:to(1,offer,deity).
conj:and(1,pan,deity).
case(1,forest,of).
det(1,forest,the).
nmod:of(1,deity,forest).
% relations.
offer_lamb_to(1,he,herme_pan).
make_vow_after(1,he,search).
offer(1,he,lamb_in_sacrifice).
make_vow_after(1,he,long_search).
make(1,he,vow).
offer(1,he,lamb).
lamb_in(1,he,sacrifice).
is_in(1,lamb,sacrifice).
%% not long afterwards as he ascended a small hillock he saw at its foot a lion feeding on the calf.
% dependencies.
root(2,root,see).
dep(2,long,not).
advmod(2,see,long).
advmod(2,ascend,afterwards).
mark(2,ascend,as).
nsubj(2,ascend,he).
advcl:as(2,long,ascend).
det(2,hillock,a).
amod(2,hillock,small).
nsubj(2,he,hillock).
xcomp(2,ascend,he).
case(2,foot,at).
nmod:poss(2,foot,its).
nmod:at(2,see,foot).
det(2,feeding,a).
compound(2,feeding,lion).
nsubj(2,see,feeding).
case(2,calf,on).
det(2,calf,the).
nmod:on(2,feeding,calf).
% relations.
long_see_at(2,lion_feeding,its_foot).
see_at(2,lion_feeding,its_foot).
%% terrified at the sight he lifted his eyes and his hands to heaven and said.
% dependencies.
root(3,root,terrify).
case(3,sight,at).
det(3,sight,the).
nmod:at(3,terrify,sight).
nsubj(3,lift,he).
nsubj(3,say,he).
acl:relcl(3,sight,lift).
nmod:poss(3,eye,he).
dobj(3,lift,eye).
cc(3,eye,and).
nmod:poss(3,hand,he).
dobj(3,lift,hand).
conj:and(3,eye,hand).
case(3,heaven,to).
nmod:to(3,lift,heaven).
cc(3,lift,and).
acl:relcl(3,sight,say).
conj:and(3,lift,say).
% relations.
lift(3,he,he_eye).
lift(3,he,he_hand).
%% just now i vowed to offer a lamb to the guardian deities of the forest if i could only find out who had robbed me.
% dependencies.
root(4,root,vow).
advmod(4,i,just).
advmod(4,i,now).
nmod(4,vow,i).
mark(4,offer,to).
xcomp(4,vow,offer).
det(4,lamb,a).
dobj(4,offer,lamb).
case(4,deity,to).
det(4,deity,the).
compound(4,deity,guardian).
nmod:to(4,offer,deity).
case(4,forest,of).
det(4,forest,the).
nmod:of(4,deity,forest).
mark(4,find,if).
nsubj(4,find,i).
aux(4,find,could).
advmod(4,find,only).
advcl:if(4,offer,find).
compound:prt(4,find,out).
nsubj(4,rob,who).
aux(4,rob,have).
ccomp(4,find,rob).
nsubj(4,vow,I).
nsubj:xsubj(4,offer,I).
% relations.
offer_lamb_to(4,I,guardian_deity_of_forest).
offer_lamb_to(4,I,guardian_deity).
offer(4,I,lamb).
%% but now that i have discovered the thief i would willingly add a full-grown bull to the calf i have lost if i may only secure my own escape from him in safety.
% dependencies.
root(5,root,now).
cc(5,now,but).
mark(5,discover,that).
nsubj(5,discover,i).
aux(5,discover,have).
dep(5,now,discover).
det(5,thief,the).
dobj(5,discover,thief).
nsubj(5,add,i).
aux(5,add,would).
advmod(5,add,willingly).
acl:relcl(5,thief,add).
det(5,bull,a).
amod(5,bull,full-grown).
dobj(5,add,bull).
case(5,calf,to).
det(5,calf,the).
nmod:to(5,add,calf).
nsubj(5,lose,i).
aux(5,lose,have).
acl:relcl(5,calf,lose).
mark(5,secure,if).
nsubj(5,secure,i).
aux(5,secure,may).
advmod(5,secure,only).
advcl:if(5,lose,secure).
nmod:poss(5,escape,my).
amod(5,escape,own).
dobj(5,secure,escape).
case(5,he,from).
nmod:from(5,secure,he).
case(5,safety,in).
nmod:in(5,secure,safety).
% relations.
would_add(5,i,full-grown_bull).
may_only_secure(5,i,my_own_escape).
may_secure(5,i,my_escape).
would_willingly_add(5,i,full-grown_bull).
would_add(5,i,bull).
would_willingly_add(5,i,bull).
may_only_secure(5,i,my_escape).
may_secure(5,i,my_own_escape).
