root(0,ROOT,feeding).
det(0,geese,the).
nsubj(0,feeding,geese).
cc(0,geese,and).
det(0,cranes,the).
conj:and(0,geese,cranes).
nsubj(0,feeding,cranes).
aux(0,feeding,were).
case(0,meadow,in).
det(0,meadow,the).
amod(0,meadow,same).
nmod:in(0,feeding,meadow).
advmod(0,came,when).
det(0,birdcatcher,a).
nsubj(0,came,birdcatcher).
nsubj:xsubj(0,ensnare,birdcatcher).
advcl(0,feeding,came).
mark(0,ensnare,to).
xcomp(0,came,ensnare).
dobj(0,ensnare,them).
case(0,nets,in).
nmod:poss(0,nets,his).
nmod:in(0,ensnare,nets).
were_feeding_in(0,cranes,meadow).
were_feeding_in(0,geese,meadow).
ensnare(0,birdcatcher,them).
were_feeding_in(0,geese,same_meadow).
were_feeding_in(0,cranes,same_meadow).
root(1,ROOT,fled).
det(1,cranes,the).
nsubj(1,fled,cranes).
cop(1,light,being).
dep(1,cranes,light).
case(1,wing,of).
nmod:of(1,light,wing).
advmod(1,fled,away).
case(1,approach,at).
nmod:poss(1,approach,his).
nmod:at(1,fled,approach).
fled_away_at(1,cranes,his_approach).
fled_at(1,cranes,his_approach).
root(2,ROOT,captured).
mark(2,captured,while).
det(2,geese,the).
nsubjpass(2,captured,geese).
cop(2,slower,being).
acl(2,geese,slower).
case(2,flight,of).
nmod:of(2,slower,flight).
cc(2,slower,and).
acl(2,geese,heavier).
conj:and(2,slower,heavier).
case(2,bodies,in).
nmod:poss(2,bodies,their).
nmod:in(2,slower,bodies).
auxpass(2,captured,were).
were(2,geese,captured).
