root(0,ROOT,waged).
det(0,hares,the).
nsubj(0,waged,hares).
nsubj(0,called,hares).
nsubj:xsubj(0,help,hares).
dobj(0,waged,war).
case(0,eagles,with).
det(0,eagles,the).
nmod:with(0,waged,eagles).
cc(0,waged,and).
conj:and(0,waged,called).
case(0,foxes,upon).
det(0,foxes,the).
nmod:upon(0,called,foxes).
mark(0,help,to).
xcomp(0,called,help).
dobj(0,help,them).
waged(0,hares,war).
waged_war_with(0,hares,eagles).
called_upon(0,hares,foxes).
root(1,ROOT,replied).
nsubj(1,replied,they).
root(2,ROOT,helped).
nsubj(2,helped,we).
aux(2,helped,would).
advmod(2,helped,willingly).
aux(2,helped,have).
dobj(2,helped,you).
mark(2,known,if).
nsubj(2,known,we).
aux(2,known,had).
neg(2,known,not).
advcl:if(2,helped,known).
dobj(2,were,who).
nsubj(2,were,you).
dep(2,known,were).
cc(2,were,and).
case(2,whom,with).
nmod:with(2,fighting,whom).
nsubj(2,fighting,you).
aux(2,fighting,were).
dep(2,known,fighting).
conj:and(2,were,fighting).
