%% a nightingale sitting aloft upon an oak and singing according to his wont was seen by a hawk who being in need of food swooped down and seized him.
% dependencies.
root(0,root,see).
det(0,nightingale,a).
nsubjpass(0,see,nightingale).
acl(0,nightingale,sit).
advmod(0,sit,aloft).
case(0,oak,upon).
det(0,oak,a).
nmod:upon(0,sit,oak).
cc(0,oak,and).
nmod:upon(0,sit,singing).
conj:and(0,oak,singing).
case(0,wont,accord).
mwe(0,accord,to).
nmod:poss(0,wont,he).
nmod:according_to(0,oak,wont).
auxpass(0,see,be).
case(0,hawk,by).
det(0,hawk,a).
nmod:agent(0,see,hawk).
nsubj(0,swoop,hawk).
nsubj(0,seize,hawk).
ref(0,hawk,who).
cop(0,need,be).
case(0,need,in).
csubj(0,swoop,need).
case(0,food,of).
nmod:of(0,need,food).
acl:relcl(0,hawk,swoop).
advmod(0,swoop,down).
cc(0,swoop,and).
acl:relcl(0,hawk,seize).
conj:and(0,swoop,seize).
dobj(0,seize,he).
% relations.
seize(0,need,he).
be(0,nightingale,see).
%% the nightingale about to lose his life earnestly begged the hawk to let him go saying that he was not big enough to satisfy the hunger of a hawk who if he wanted food ought to pursue the larger birds.
% dependencies.
root(1,root,nightingale).
det(1,nightingale,the).
dep(1,nightingale,about).
mark(1,lose,to).
xcomp(1,about,lose).
nmod:poss(1,life,he).
nsubj(1,beg,life).
advmod(1,beg,earnestly).
ccomp(1,lose,beg).
det(1,hawk,the).
dobj(1,beg,hawk).
mark(1,let,to).
acl:to(1,hawk,let).
nsubj(1,go,he).
ccomp(1,let,go).
xcomp(1,go,say).
mark(1,big,that).
nsubj(1,big,he).
nsubj:xsubj(1,satisfy,he).
cop(1,big,be).
neg(1,big,not).
ccomp(1,say,big).
advmod(1,big,enough).
mark(1,satisfy,to).
xcomp(1,big,satisfy).
det(1,hunger,the).
dobj(1,satisfy,hunger).
case(1,hawk,of).
det(1,hawk,a).
nmod:of(1,hunger,hawk).
dobj(1,want,hawk).
ref(1,hawk,who).
mark(1,want,if).
nsubj(1,want,he).
acl:relcl(1,hawk,want).
nsubj(1,ought,food).
nsubj:xsubj(1,pursue,food).
ccomp(1,want,ought).
mark(1,pursue,to).
xcomp(1,ought,pursue).
det(1,bird,the).
amod(1,bird,larger).
dobj(1,pursue,bird).
% relations.
%% the hawk interrupting him said.
% dependencies.
root(2,root,say).
det(2,hawk,the).
nsubj(2,say,hawk).
acl(2,hawk,interrupt).
dobj(2,interrupt,he).
% relations.
%% i should indeed have lost my senses if i should let go food ready in my hand for the sake of pursuing birds which are not yet even within sight.
% dependencies.
root(3,root,lose).
nsubj(3,lose,i).
aux(3,lose,should).
advmod(3,lose,indeed).
aux(3,lose,have).
nmod:poss(3,sens,my).
dobj(3,lose,sens).
mark(3,let,if).
nsubj(3,let,i).
aux(3,let,should).
advcl:if(3,lose,let).
xcomp(3,let,go).
nsubj(3,ready,food).
xcomp(3,go,ready).
case(3,hand,in).
nmod:poss(3,hand,my).
nmod:in(3,ready,hand).
case(3,sake,for).
det(3,sake,the).
nmod:for(3,hand,sake).
mark(3,pursue,of).
acl:of(3,sake,pursue).
dobj(3,pursue,bird).
nsubj(3,even,bird).
ref(3,bird,which).
cop(3,even,be).
neg(3,even,not).
advmod(3,even,yet).
acl:relcl(3,bird,even).
case(3,sight,within).
nmod:within(3,even,sight).
% relations.
should_let(3,i,go).
ready_in(3,food,my_hand).
go(3,i,food_ready_in_my_hand).
go(3,i,food_ready).
