root(0,ROOT,fled).
det(0,hart,a).
nsubj(0,fled,hart).
nsubj(0,buried,hart).
advmod(0,pursued,hotly).
acl(0,hart,pursued).
case(0,hounds,by).
det(0,hounds,the).
nmod:by(0,pursued,hounds).
case(0,refuge,for).
nmod:for(0,fled,refuge).
case(0,ox-stall,into).
det(0,ox-stall,an).
nmod:into(0,fled,ox-stall).
cc(0,fled,and).
conj:and(0,fled,buried).
dobj(0,buried,itself).
case(0,truss,in).
det(0,truss,a).
nmod:in(0,buried,truss).
case(0,hay,of).
nmod:of(0,truss,hay).
dep(0,buried,leaving).
dobj(0,leaving,nothing).
mark(0,seen,to).
auxpass(0,seen,be).
advcl:to(0,leaving,seen).
case(0,tips,but).
det(0,tips,the).
nmod:but(0,seen,tips).
case(0,horns,of).
nmod:poss(0,horns,his).
nmod:of(0,tips,horns).
hotly_pursued_by(0,hart,hounds).
leaving_nothing(0,itself,seen_but_tips).
leaving_nothing(0,itself,seen_but_tips_of_his_horns).
buried(0,hart,itself).
fled_for(0,hart,refuge).
leaving(0,itself,nothing).
fled_into(0,hart,ox-stall).
pursued_by(0,hart,hounds).
leaving_nothing(0,itself,seen).
root(1,ROOT,soon).
mark(1,came,after).
det(1,hunters,the).
nsubj(1,came,hunters).
nsubj(1,asked,hunters).
dep(1,soon,came).
advmod(1,came,up).
cc(1,came,and).
dep(1,soon,asked).
conj:and(1,came,asked).
mark(1,seen,if).
det(1,one,any).
nsubj(1,seen,one).
aux(1,seen,had).
advcl:if(1,asked,seen).
det(1,hart,the).
dobj(1,seen,hart).
root(2,ROOT,went).
det(2,boys,the).
amod(2,boys,stable).
nsubj(2,resting,boys).
nsubj(2,went,boys).
ref(2,boys,who).
aux(2,resting,had).
aux(2,resting,been).
acl:relcl(2,boys,resting).
mark(2,looked,after).
nmod:poss(2,dinner,their).
nsubj(2,looked,dinner).
nsubj(2,see,dinner).
advcl:after(2,resting,looked).
dobj(2,looked,round).
cc(2,looked,but).
aux(2,see,could).
advcl:after(2,resting,see).
conj:but(2,looked,see).
dobj(2,see,nothing).
cc(2,nothing,and).
det(2,hunters,the).
dobj(2,see,hunters).
conj:and(2,nothing,hunters).
advmod(2,went,away).
see(2,their_dinner,nothing).
see(2,their_dinner,hunters).
looked(2,their_dinner,round).
root(3,ROOT,came).
advmod(3,came,shortly).
advmod(3,master,afterwards).
det(3,master,the).
advmod(3,came,master).
nmod(3,came,in).
cc(3,came,and).
conj:and(3,came,looking).
amod(3,saw,round).
dobj(3,looking,saw).
dobj(3,taken,that).
nsubj(3,taken,something).
amod(3,something,unusual).
aux(3,taken,had).
dep(3,came,taken).
dobj(3,taken,place).
root(4,ROOT,pointed).
nsubj(4,pointed,he).
nsubj(4,said,he).
case(4,truss,to).
det(4,truss,the).
nmod:to(4,pointed,truss).
case(4,hay,of).
nmod:of(4,truss,hay).
cc(4,pointed,and).
conj:and(4,pointed,said).
pointed_to(4,he,truss).
pointed_to(4,he,truss_of_hay).
root(5,ROOT,sticking).
dobj(5,sticking,what).
aux(5,sticking,are).
det(5,things,those).
nummod(5,things,two).
amod(5,things,curious).
nsubj(5,sticking,things).
compound:prt(5,sticking,out).
case(5,hay,of).
det(5,hay,the).
nmod:of(5,sticking,hay).
root(6,ROOT,came).
cc(6,came,and).
advmod(6,came,when).
det(6,boys,the).
amod(6,boys,stable).
nsubj(6,came,boys).
nsubj:xsubj(6,look,boys).
mark(6,look,to).
xcomp(6,came,look).
nsubj(6,discovered,they).
nsubj(6,made,they).
ccomp(6,look,discovered).
det(6,hart,the).
dobj(6,discovered,hart).
cc(6,discovered,and).
advmod(6,made,soon).
ccomp(6,look,made).
conj:and(6,discovered,made).
det(6,end,an).
dobj(6,made,end).
case(6,him,of).
nmod:of(6,end,him).
made(6,they,end).
soon_made(6,they,end).
soon_made(6,they,end_of_him).
came(6,stable_boys,look).
made(6,they,end_of_him).
came(6,boys,look).
discovered(6,they,hart).
