root(0,ROOT,day).
nummod(0,day,one).
det(0,countryman,a).
nsubj(0,found,countryman).
acl(0,countryman,going).
case(0,nest,to).
det(0,nest,the).
nmod:to(0,going,nest).
case(0,goose,of).
nmod:poss(0,goose,his).
nmod:of(0,nest,goose).
acl:relcl(0,day,found).
expl(0,egg,there).
det(0,egg,an).
xcomp(0,found,egg).
det(0,yellow,all).
amod(0,egg,yellow).
cc(0,egg,and).
xcomp(0,found,glittering).
conj:and(0,egg,glittering).
found(0,countryman,egg).
going_to(0,countryman,nest).
going_to(0,countryman,nest_his_goose).
root(1,ROOT,took).
advmod(1,took,when).
nsubj(1,took,he).
dobj(1,took,it).
mark(1,heavy,up).
nsubj(1,heavy,it).
cop(1,heavy,was).
dep(1,heavy,as).
advcl:up(1,took,heavy).
case(1,lead,as).
nmod:as(1,heavy,lead).
cc(1,heavy,and).
nsubj(1,going,he).
nsubj:xsubj(1,throw,he).
aux(1,going,was).
advcl:up(1,took,going).
conj:and(1,heavy,going).
mark(1,throw,to).
xcomp(1,going,throw).
dobj(1,throw,it).
advmod(1,throw,away).
mark(1,thought,because).
nsubj(1,thought,he).
advcl:because(1,throw,thought).
det(1,trick,a).
nsubjpass(1,played,trick).
aux(1,played,had).
auxpass(1,played,been).
ccomp(1,thought,played).
case(1,him,upon).
nmod:upon(1,played,him).
was(1,it,heavy).
throw_away(1,he,it).
took(1,he,it).
was_heavy_as(1,it,lead).
throw(1,he,it).
root(2,ROOT,took).
cc(2,took,but).
nsubj(2,took,he).
dobj(2,took,it).
advmod(2,thoughts,home).
case(2,thoughts,on).
amod(2,thoughts,second).
dep(2,took,thoughts).
cc(2,thoughts,and).
dep(2,took,soon).
conj:and(2,thoughts,soon).
dep(2,took,found).
conj:and(2,thoughts,found).
case(2,delight,to).
nmod:poss(2,delight,his).
nmod:to(2,found,delight).
mark(2,egg,that).
nsubj(2,egg,it).
cop(2,egg,was).
det(2,egg,an).
ccomp(2,found,egg).
case(2,gold,of).
amod(2,gold,pure).
nmod:of(2,egg,gold).
was_egg_of(2,it,gold).
took(2,he,it).
was_egg_of(2,it,pure_gold).
was(2,it,egg).
root(3,ROOT,morning).
det(3,morning,every).
det(3,thing,the).
amod(3,thing,same).
nsubj(3,occurred,thing).
ccomp(3,morning,occurred).
cc(3,occurred,and).
nsubj(3,became,he).
advmod(3,became,soon).
ccomp(3,morning,became).
conj:and(3,occurred,became).
xcomp(3,became,rich).
mark(3,selling,by).
advcl:by(3,rich,selling).
nmod:poss(3,eggs,his).
dobj(3,selling,eggs).
root(4,ROOT,grew).
mark(4,grew,as).
nsubj(4,grew,he).
xcomp(4,grew,rich).
nsubj(4,grew,he).
ccomp(4,rich,grew).
xcomp(4,grew,greedy).
grew(4,he,greedy).
grew(4,he,rich).
root(5,ROOT,thinking).
cc(5,thinking,and).
mark(5,get,to).
xcomp(5,thinking,get).
case(5,gold,at).
advmod(5,gold,once).
det:predet(5,gold,all).
det(5,gold,the).
nmod:at(5,get,gold).
det(5,goose,the).
nsubj(5,give,goose).
aux(5,give,could).
acl:relcl(5,gold,give).
nsubj(5,killed,he).
nsubj(5,opened,he).
ccomp(5,give,killed).
dobj(5,killed,it).
cc(5,killed,and).
ccomp(5,give,opened).
conj:and(5,killed,opened).
dobj(5,opened,it).
advmod(5,opened,only).
mark(5,find,to).
advcl:to(5,opened,find).
dobj(5,find,nothing).
