root(0,ROOT,lost).
det(0,herdsman,a).
nsubj(0,lost,herdsman).
acl(0,herdsman,tending).
nmod:poss(0,flock,his).
dobj(0,tending,flock).
case(0,forest,in).
det(0,forest,a).
nmod:in(0,tending,forest).
det(0,bull-calf,a).
dobj(0,lost,bull-calf).
case(0,fold,from).
det(0,fold,the).
nmod:from(0,lost,fold).
lost(0,herdsman,bull-calf).
tending_his_flock_in(0,herdsman,forest).
tending(0,herdsman,his_flock).
lost_bull-calf_from(0,herdsman,fold).
root(1,ROOT,made).
case(1,search,after).
det(1,search,a).
amod(1,search,long).
cc(1,long,and).
conj:and(1,long,fruitless).
amod(1,search,fruitless).
nmod:after(1,made,search).
nsubj(1,made,he).
det(1,vow,a).
dobj(1,made,vow).
mark(1,offer,that).
mark(1,discover,if).
nsubj(1,discover,he).
aux(1,discover,could).
advmod(1,discover,only).
advcl:if(1,offer,discover).
det(1,thief,the).
dobj(1,discover,thief).
nsubj(1,stolen,thief).
ref(1,thief,who).
aux(1,stolen,had).
acl:relcl(1,thief,stolen).
det(1,calf,the).
dobj(1,stolen,calf).
nsubj(1,offer,he).
aux(1,offer,would).
ccomp(1,made,offer).
det(1,lamb,a).
dobj(1,offer,lamb).
case(1,sacrifice,in).
nmod:in(1,lamb,sacrifice).
case(1,pan,to).
compound(1,pan,hermes).
nmod:to(1,offer,pan).
cc(1,pan,and).
det(1,deities,the).
compound(1,deities,guardian).
nmod:to(1,offer,deities).
conj:and(1,pan,deities).
case(1,forest,of).
det(1,forest,the).
nmod:of(1,deities,forest).
offer_lamb_to(1,he,hermes_pan).
made_vow_after(1,he,search).
offer(1,he,lamb_in_sacrifice).
made_vow_after(1,he,long_search).
made(1,he,vow).
offer(1,he,lamb).
lamb_in(1,he,sacrifice).
is_in(1,lamb,sacrifice).
root(2,ROOT,saw).
dep(2,long,not).
advmod(2,saw,long).
advmod(2,ascended,afterwards).
mark(2,ascended,as).
nsubj(2,ascended,he).
advcl:as(2,long,ascended).
det(2,hillock,a).
amod(2,hillock,small).
nsubj(2,he,hillock).
xcomp(2,ascended,he).
case(2,foot,at).
nmod:poss(2,foot,its).
nmod:at(2,saw,foot).
det(2,feeding,a).
compound(2,feeding,lion).
nsubj(2,saw,feeding).
case(2,calf,on).
det(2,calf,the).
nmod:on(2,feeding,calf).
long_saw_at(2,lion_feeding,its_foot).
saw_at(2,lion_feeding,its_foot).
root(3,ROOT,terrified).
case(3,sight,at).
det(3,sight,the).
nmod:at(3,terrified,sight).
nsubj(3,lifted,he).
nsubj(3,said,he).
acl:relcl(3,sight,lifted).
nmod:poss(3,eyes,his).
dobj(3,lifted,eyes).
cc(3,eyes,and).
nmod:poss(3,hands,his).
dobj(3,lifted,hands).
conj:and(3,eyes,hands).
case(3,heaven,to).
nmod:to(3,lifted,heaven).
cc(3,lifted,and).
acl:relcl(3,sight,said).
conj:and(3,lifted,said).
lifted(3,he,his_eyes).
lifted(3,he,his_hands).
root(4,ROOT,vowed).
advmod(4,i,just).
advmod(4,i,now).
nmod(4,vowed,i).
mark(4,offer,to).
xcomp(4,vowed,offer).
det(4,lamb,a).
dobj(4,offer,lamb).
case(4,deities,to).
det(4,deities,the).
compound(4,deities,guardian).
nmod:to(4,offer,deities).
case(4,forest,of).
det(4,forest,the).
nmod:of(4,deities,forest).
mark(4,find,if).
nsubj(4,find,i).
aux(4,find,could).
advmod(4,find,only).
advcl:if(4,offer,find).
compound:prt(4,find,out).
nsubj(4,robbed,who).
aux(4,robbed,had).
ccomp(4,find,robbed).
nsubj(4,vowed,me).
nsubj:xsubj(4,offer,me).
offer_lamb_to(4,me,guardian_deities_of_forest).
offer_lamb_to(4,me,guardian_deities).
offer(4,me,lamb).
root(5,ROOT,now).
cc(5,now,but).
mark(5,discovered,that).
nsubj(5,discovered,i).
aux(5,discovered,have).
dep(5,now,discovered).
det(5,thief,the).
dobj(5,discovered,thief).
nsubj(5,add,i).
aux(5,add,would).
advmod(5,add,willingly).
acl:relcl(5,thief,add).
det(5,bull,a).
amod(5,bull,full-grown).
dobj(5,add,bull).
case(5,calf,to).
det(5,calf,the).
nmod:to(5,add,calf).
nsubj(5,lost,i).
aux(5,lost,have).
acl:relcl(5,calf,lost).
mark(5,secure,if).
nsubj(5,secure,i).
aux(5,secure,may).
advmod(5,secure,only).
advcl:if(5,lost,secure).
nmod:poss(5,escape,my).
amod(5,escape,own).
dobj(5,secure,escape).
case(5,him,from).
nmod:from(5,secure,him).
case(5,safety,in).
nmod:in(5,secure,safety).
would_add(5,i,full-grown_bull).
may_only_secure(5,i,my_own_escape).
may_secure(5,i,my_escape).
would_willingly_add(5,i,full-grown_bull).
would_add(5,i,bull).
would_willingly_add(5,i,bull).
may_only_secure(5,i,my_escape).
may_secure(5,i,my_own_escape).
