root(0,ROOT,drinking).
det(0,hart,the).
nsubj(0,drinking,hart).
nsubj(0,admiring,hart).
aux(0,drinking,was).
advmod(0,drinking,once).
case(0,pool,from).
det(0,pool,a).
nmod:from(0,drinking,pool).
cc(0,drinking,and).
conj:and(0,drinking,admiring).
det(0,figure,the).
amod(0,figure,noble).
dobj(0,admiring,figure).
nsubj(0,made,he).
acl:relcl(0,figure,made).
xcomp(0,made,there).
made(0,he,there).
was_once_drinking_from(0,hart,pool).
was_drinking_from(0,hart,pool).
root(1,ROOT,ah).
root(2,ROOT,said).
nsubj(2,said,he).
root(3,ROOT,see).
advmod(3,see,where).
aux(3,see,can).
nsubj(3,see,you).
amod(3,horns,such).
amod(3,horns,noble).
dobj(3,see,horns).
case(3,these,as).
nmod:as(3,see,these).
case(3,antlers,with).
amod(3,antlers,such).
nmod:with(3,these,antlers).
can_see(3,you,noble_horns).
can_see(3,you,such_noble_horns).
can_see(3,you,horns).
can_see(3,you,such_horns).
can_see_horns_as(3,you,these).
can_see_horns_as(3,you,these_with_antlers).
can_see_horns_as(3,you,these_with_such_antlers).
root(4,ROOT,wish).
nsubj(4,wish,i).
nsubj(4,had,i).
ccomp(4,wish,had).
nsubj(4,worthy,legs).
nsubj:xsubj(4,bear,legs).
advmod(4,worthy,more).
xcomp(4,had,worthy).
mark(4,bear,to).
xcomp(4,worthy,bear).
det:predet(4,crown,such).
det(4,crown,a).
amod(4,crown,noble).
dobj(4,bear,crown).
had(4,i,legs_worthy).
had(4,i,legs_more_worthy).
root(5,ROOT,pity).
nsubj(5,pity,it).
cop(5,pity,is).
det(5,pity,a).
nsubj(5,slim,they).
nsubj(5,slight,they).
cop(5,slim,are).
advmod(5,slim,so).
acl:relcl(5,pity,slim).
cc(5,slim,and).
acl:relcl(5,pity,slight).
conj:and(5,slim,slight).
is_pity(5,it,slim).
are(5,they,so_slim).
is_pity(5,it,so_slim).
are(5,they,slim).
root(6,ROOT,approached).
case(6,moment,at).
det(6,moment,that).
nmod:at(6,approached,moment).
det(6,hunter,a).
nsubj(6,approached,hunter).
nsubj(6,sent,hunter).
cc(6,approached,and).
conj:and(6,approached,sent).
det(6,arrow,an).
dobj(6,approached,arrow).
acl(6,arrow,whistling).
case(6,him,after).
nmod:after(6,whistling,him).
approached_arrow_at(6,hunter,moment).
approached(6,hunter,arrow_whistling).
whistling_after(6,arrow,him).
approached(6,hunter,arrow).
approached(6,hunter,arrow_whistling_after_him).
root(7,ROOT,was).
advmod(7,was,away).
dep(7,away,bounded).
det(7,hart,the).
dobj(7,bounded,hart).
cc(7,bounded,and).
dep(7,away,soon).
conj:and(7,bounded,soon).
case(7,aid,by).
det(7,aid,the).
nmod:by(7,soon,aid).
case(7,legs,of).
nmod:poss(7,legs,his).
amod(7,legs,nimble).
nmod:of(7,aid,legs).
advmod(7,sight,nearly).
case(7,sight,out).
mwe(7,out,of).
nmod:out_of(7,was,sight).
case(7,hunter,of).
det(7,hunter,the).
nmod:of(7,sight,hunter).
root(8,ROOT,noticing).
cc(8,not,but).
cc(8,noticing,not).
advmod(8,going,where).
nsubj(8,going,he).
aux(8,going,was).
advcl(8,noticing,going).
nsubj(8,passed,he).
ccomp(8,going,passed).
case(8,trees,under).
det(8,trees,some).
nmod:under(8,passed,trees).
case(8,branches,with).
nmod:with(8,passed,branches).
acl(8,branches,growing).
advmod(8,down,low).
advmod(8,growing,down).
mark(8,caught,in).
dobj(8,caught,which).
nmod:poss(8,antlers,his).
nsubjpass(8,caught,antlers).
auxpass(8,caught,were).
advcl:in(8,growing,caught).
mark(8,had,so).
mwe(8,so,that).
det(8,hunter,the).
nsubj(8,had,hunter).
advcl:so_that(8,caught,had).
dobj(8,had,time).
mark(8,come,to).
acl:to(8,time,come).
compound:prt(8,come,up).
passed_with(8,he,branches_growing_low_down).
passed_with(8,he,branches_growing).
passed_under(8,he,trees).
passed_with(8,he,branches_growing_down).
passed_with(8,he,branches).
root(9,ROOT,alas).
root(10,ROOT,alas).
