root(0,ROOT,came).
det(0,gnat,a).
nsubj(0,came,gnat).
nsubj(0,said,gnat).
cc(0,came,and).
conj:and(0,came,said).
case(0,lion,to).
det(0,lion,a).
nmod:to(0,came,lion).
came_to(0,gnat,lion).
root(1,ROOT,do).
nsubj(1,do,i).
nsubj(1,stronger,i).
xcomp(1,do,not).
case(1,fear,in).
det(1,fear,the).
amod(1,fear,least).
nmod:in(1,not,fear).
dep(1,not,you).
cc(1,do,nor).
cop(1,stronger,are).
nmod:npmod(1,stronger,you).
conj:nor(1,do,stronger).
mark(1,am,than).
nsubj(1,am,i).
ccomp(1,stronger,am).
do(1,i,not_in_least_fear).
do(1,i,not).
do(1,i,not_in_fear).
root(2,ROOT,does).
dep(2,does,for).
mark(2,does,in).
nsubj(2,does,what).
nmod:poss(2,strength,your).
nsubj(2,consist,strength).
ccomp(2,does,consist).
root(3,ROOT,scratch).
nsubj(3,scratch,you).
nsubj(3,bite,you).
aux(3,scratch,can).
case(3,claws,with).
nmod:poss(3,claws,your).
nmod:with(3,scratch,claws).
cc(3,scratch,and).
conj:and(3,scratch,bite).
case(3,teeth,with).
nmod:poss(3,teeth,your).
nmod:with(3,bite,teeth).
det:predet(3,woman,an).
det(3,woman,a).
dobj(3,bite,woman).
case(3,quarrels,in).
nmod:poss(3,quarrels,her).
nmod:in(3,woman,quarrels).
bite(3,you,woman_in_her_quarrels).
can_scratch_with(3,you,your_claws).
is_in(3,woman,her_quarrels).
bite_woman_with(3,you,your_teeth).
bite(3,you,woman).
root(4,ROOT,repeat).
dep(4,repeat,i).
dobj(4,powerful,that).
nsubj(4,powerful,i).
cop(4,powerful,am).
advmod(4,powerful,altogether).
advmod(4,powerful,more).
dep(4,repeat,powerful).
case(4,you,than).
nmod:than(4,powerful,you).
am(4,i,powerful).
am_powerful_than(4,i,you).
am_altogether_powerful_than(4,i,you).
am(4,i,more_powerful).
am_altogether_more_powerful_than(4,i,you).
am_more_powerful_than(4,i,you).
am(4,i,altogether_powerful).
am(4,i,altogether_more_powerful).
root(5,ROOT,doubt).
cc(5,doubt,and).
mark(5,doubt,if).
nsubj(5,doubt,you).
nsubj(5,let,it).
ccomp(5,doubt,let).
nsubj(5,fight,us).
nsubj(5,see,us).
ccomp(5,let,fight).
cc(5,fight,and).
ccomp(5,let,see).
conj:and(5,fight,see).
nsubj(5,conquer,who).
aux(5,conquer,will).
ccomp(5,doubt,conquer).
root(6,ROOT,gnat).
det(6,gnat,the).
aux(6,sounded,having).
dep(6,gnat,sounded).
nmod:poss(6,horn,his).
nsubj(6,fastened,horn).
nsubj(6,stung,horn).
nsubj(6,devoid,horn).
dep(6,sounded,fastened).
dobj(6,fastened,himself).
case(6,lion,upon).
det(6,lion,the).
nmod:upon(6,fastened,lion).
cc(6,fastened,and).
dep(6,sounded,stung).
conj:and(6,fastened,stung).
dobj(6,stung,him).
case(6,nostrils,on).
det(6,nostrils,the).
nmod:on(6,stung,nostrils).
cc(6,fastened,and).
det(6,parts,the).
dep(6,devoid,parts).
case(6,face,of).
det(6,face,the).
nmod:of(6,parts,face).
dep(6,sounded,devoid).
conj:and(6,fastened,devoid).
case(6,hair,of).
nmod:of(6,gnat,hair).
fastened(6,his_horn,himself).
stung(6,his_horn,him).
root(7,ROOT,tore).
mark(7,tore,while).
csubj(7,tore,trying).
mark(7,crush,to).
xcomp(7,trying,crush).
nsubj(7,lion,him).
det(7,lion,the).
xcomp(7,crush,lion).
dobj(7,tore,himself).
case(7,claws,with).
nmod:poss(7,claws,his).
nmod:with(7,tore,claws).
mark(7,punished,until).
nsubj(7,punished,he).
advcl:until(7,tore,punished).
dobj(7,punished,himself).
advmod(7,punished,severely).
trying(7,himself,crush).
punished_severely(7,he,himself).
tore(7,trying,himself).
punished(7,he,himself).
root(8,ROOT,flew).
det(8,gnat,the).
nsubj(8,flew,gnat).
advmod(8,prevailed,thus).
dep(8,gnat,prevailed).
case(8,lion,over).
det(8,lion,the).
nmod:over(8,prevailed,lion).
cc(8,prevailed,and).
dep(8,gnat,buzzing).
conj:and(8,prevailed,buzzing).
advmod(8,buzzing,about).
case(8,song,in).
det(8,song,a).
nmod:in(8,buzzing,song).
case(8,triumph,of).
nmod:of(8,song,triumph).
advmod(8,flew,away).
root(9,ROOT,shortly).
cc(9,shortly,but).
advmod(9,became,afterwards).
nsubj(9,became,he).
nsubjpass(9,eaten,he).
dep(9,shortly,became).
xcomp(9,became,entangled).
case(9,meshes,in).
det(9,meshes,the).
nmod:in(9,became,meshes).
case(9,cobweb,of).
det(9,cobweb,a).
nmod:of(9,meshes,cobweb).
cc(9,became,and).
auxpass(9,eaten,was).
dep(9,shortly,eaten).
conj:and(9,became,eaten).
case(9,spider,by).
det(9,spider,a).
nmod:agent(9,eaten,spider).
was(9,he,eaten).
was_eaten_by(9,he,spider).
root(10,ROOT,lamented).
nsubj(10,lamented,he).
advmod(10,lamented,greatly).
nmod:poss(10,fate,his).
dobj(10,lamented,fate).
xcomp(10,lamented,saying).
greatly_lamented(10,he,his_fate).
lamented(10,he,his_fate).
root(11,ROOT,me).
nsubj(11,me,woe).
cop(11,me,is).
is(11,woe,me).
root(12,ROOT,perish).
mark(12,perish,that).
nsubj(12,wage,i).
nsubj(12,perish,i).
ref(12,i,who).
aux(12,wage,can).
acl:relcl(12,i,wage).
dobj(12,wage,war).
advmod(12,wage,successfully).
case(12,beasts,with).
det(12,beasts,the).
amod(12,beasts,hugest).
nmod:with(12,wage,beasts).
aux(12,perish,should).
dobj(12,perish,myself).
case(12,spider,from).
det(12,spider,this).
nmod:from(12,perish,spider).
det(12,inconsiderable,the).
advmod(12,inconsiderable,most).
dep(12,spider,inconsiderable).
case(12,insects,of).
nmod:of(12,inconsiderable,insects).
