root(0,ROOT,travelling).
det(0,horse,a).
nsubj(0,travelling,horse).
cc(0,horse,and).
det(0,ass,an).
conj:and(0,horse,ass).
nsubj(0,travelling,ass).
aux(0,travelling,were).
advmod(0,travelling,together).
det(0,horse,the).
dobj(0,travelling,horse).
acl(0,horse,prancing).
advmod(0,prancing,along).
case(0,trappings,in).
nmod:poss(0,trappings,its).
amod(0,trappings,fine).
nmod:in(0,prancing,trappings).
det(0,ass,the).
nmod:tmod(0,prancing,ass).
acl(0,ass,carrying).
case(0,difficulty,with).
nmod:with(0,carrying,difficulty).
det(0,weight,the).
amod(0,weight,heavy).
dep(0,ass,weight).
case(0,panniers,in).
nmod:poss(0,panniers,its).
nmod:in(0,travelling,panniers).
were_travelling(0,ass,horse_prancing_ass_carrying).
were_travelling_together(0,ass,horse_prancing_along_in_its_trappings_ass).
were_travelling(0,horse,horse_prancing_along_in_its_trappings_ass).
were_travelling(0,horse,horse_prancing_in_its_fine_trappings_ass).
were_travelling(0,horse,horse_prancing_along_ass).
were_travelling_together(0,horse,horse_prancing_in_its_trappings_ass_carrying).
were_travelling_together(0,horse,horse_prancing_along_in_its_fine_trappings_ass).
were_travelling_together(0,horse,horse_prancing_in_its_trappings_ass_carrying_with_difficulty).
were_travelling_together(0,horse,horse_prancing_along_in_its_trappings_ass_carrying).
were_travelling(0,ass,horse_prancing_ass).
were_travelling(0,ass,horse_prancing_along_in_its_trappings_ass).
were_travelling(0,horse,horse_prancing_in_its_trappings_ass).
were_travelling_together(0,ass,horse_prancing_along_ass_carrying_with_difficulty).
were_travelling_together(0,ass,horse_prancing_in_its_fine_trappings).
were_travelling(0,ass,horse_prancing_in_its_trappings_ass_carrying_with_difficulty).
were_travelling(0,horse,horse_prancing_ass).
were_travelling(0,horse,horse_prancing_in_its_trappings).
were_travelling_together(0,ass,horse_prancing_along_in_its_fine_trappings_ass).
were_travelling_together(0,horse,horse_prancing_along).
were_travelling_together(0,ass,horse_prancing_in_its_fine_trappings_ass_carrying).
were_travelling(0,horse,horse_prancing_along_in_its_fine_trappings).
were_travelling(0,horse,horse).
were_travelling(0,ass,horse_prancing_in_its_trappings).
were_travelling_together(0,ass,horse_prancing_in_its_fine_trappings_ass).
were_travelling_together(0,ass,horse_prancing_along_in_its_fine_trappings_ass_carrying_with_difficulty).
were_travelling(0,horse,horse_prancing_in_its_trappings_ass_carrying).
were_travelling(0,horse,horse_prancing_along_ass_carrying).
were_travelling_together_horse_in(0,horse,its_panniers).
were_travelling(0,ass,horse_prancing_along_ass_carrying).
were_travelling_together(0,horse,horse_prancing_in_its_trappings).
were_travelling(0,horse,horse_prancing_along_in_its_trappings_ass_carrying_with_difficulty).
were_travelling_horse_in(0,horse,its_panniers).
were_travelling_together(0,ass,horse_prancing_along_in_its_fine_trappings).
were_travelling(0,ass,horse_prancing_in_its_fine_trappings_ass_carrying_with_difficulty).
were_travelling(0,ass,horse_prancing_in_its_fine_trappings_ass_carrying).
were_travelling_together(0,horse,horse_prancing_in_its_fine_trappings).
were_travelling_together(0,ass,horse).
were_travelling_together(0,ass,horse_prancing_in_its_trappings_ass).
were_travelling(0,ass,horse_prancing_along_in_its_fine_trappings_ass).
were_travelling(0,ass,horse_prancing_in_its_trappings_ass).
were_travelling_together(0,ass,horse_prancing_in_its_trappings).
were_travelling(0,ass,horse_prancing_along_in_its_fine_trappings_ass_carrying_with_difficulty).
were_travelling(0,ass,horse_prancing_in_its_trappings_ass_carrying).
were_travelling(0,ass,horse_prancing_along_ass_carrying_with_difficulty).
were_travelling_together(0,ass,horse_prancing_ass).
were_travelling(0,horse,horse_prancing_along).
were_travelling_together(0,ass,horse_prancing_ass_carrying_with_difficulty).
were_travelling(0,horse,horse_prancing_along_in_its_fine_trappings_ass_carrying).
were_travelling(0,horse,horse_prancing_along_in_its_fine_trappings_ass).
were_travelling(0,ass,horse_prancing_along_in_its_trappings_ass_carrying).
were_travelling(0,ass,horse_prancing_in_its_fine_trappings_ass).
were_travelling_horse_in(0,ass,its_panniers).
were_travelling(0,ass,horse).
were_travelling_together(0,ass,horse_prancing_ass_carrying).
were_travelling(0,horse,horse_prancing_in_its_trappings_ass_carrying_with_difficulty).
were_travelling(0,horse,horse_prancing_in_its_fine_trappings).
were_travelling_together(0,horse,horse_prancing_in_its_fine_trappings_ass_carrying_with_difficulty).
were_travelling_together(0,horse,horse_prancing_in_its_fine_trappings_ass_carrying).
were_travelling_together(0,ass,horse_prancing_along_in_its_trappings).
were_travelling_together(0,ass,horse_prancing_along_in_its_trappings_ass_carrying_with_difficulty).
were_travelling(0,ass,horse_prancing_along_ass).
were_travelling(0,horse,horse_prancing_along_in_its_trappings).
were_travelling(0,horse,horse_prancing_in_its_fine_trappings_ass_carrying).
were_travelling(0,ass,horse_prancing_along_in_its_fine_trappings).
were_travelling_together(0,horse,horse_prancing_ass_carrying_with_difficulty).
were_travelling_together(0,horse,horse_prancing).
were_travelling_together(0,horse,horse).
were_travelling_together(0,ass,horse_prancing_along_in_its_fine_trappings_ass_carrying).
were_travelling_together(0,horse,horse_prancing_along_ass).
were_travelling_together(0,horse,horse_prancing_in_its_fine_trappings_ass).
were_travelling(0,horse,horse_prancing).
were_travelling_together(0,ass,horse_prancing_in_its_trappings_ass_carrying).
were_travelling_together(0,horse,horse_prancing_along_in_its_trappings_ass_carrying_with_difficulty).
were_travelling_together(0,ass,horse_prancing).
were_travelling_together(0,horse,horse_prancing_ass).
were_travelling(0,ass,horse_prancing_ass_carrying_with_difficulty).
were_travelling_together(0,ass,horse_prancing_in_its_fine_trappings_ass_carrying_with_difficulty).
were_travelling_together(0,horse,horse_prancing_along_in_its_fine_trappings).
were_travelling_together(0,horse,horse_prancing_along_ass_carrying_with_difficulty).
were_travelling_together(0,horse,horse_prancing_ass_carrying).
were_travelling_together(0,horse,horse_prancing_along_in_its_trappings).
were_travelling(0,horse,horse_prancing_in_its_fine_trappings_ass_carrying_with_difficulty).
were_travelling_together(0,horse,horse_prancing_along_in_its_trappings_ass).
were_travelling(0,horse,horse_prancing_along_in_its_trappings_ass_carrying).
were_travelling(0,ass,horse_prancing_along_in_its_trappings_ass_carrying_with_difficulty).
were_travelling_together(0,ass,horse_prancing_along).
were_travelling(0,ass,horse_prancing_along_in_its_fine_trappings_ass_carrying).
were_travelling_together(0,horse,horse_prancing_along_in_its_fine_trappings_ass_carrying_with_difficulty).
were_travelling(0,ass,horse_prancing_along_in_its_trappings).
were_travelling_together(0,ass,horse_prancing_in_its_trappings_ass_carrying_with_difficulty).
were_travelling_together_horse_in(0,ass,its_panniers).
were_travelling_together(0,horse,horse_prancing_along_ass_carrying).
were_travelling(0,ass,horse_prancing_in_its_fine_trappings).
were_travelling_together(0,ass,horse_prancing_along_ass).
were_travelling_together(0,horse,horse_prancing_along_in_its_fine_trappings_ass_carrying).
were_travelling(0,horse,horse_prancing_ass_carrying).
were_travelling(0,horse,horse_prancing_along_in_its_fine_trappings_ass_carrying_with_difficulty).
were_travelling(0,ass,horse_prancing).
were_travelling_together(0,ass,horse_prancing_along_ass_carrying).
were_travelling_together(0,horse,horse_prancing_in_its_trappings_ass).
were_travelling(0,horse,horse_prancing_ass_carrying_with_difficulty).
were_travelling(0,horse,horse_prancing_along_ass_carrying_with_difficulty).
were_travelling(0,ass,horse_prancing_along).
were_travelling_together(0,ass,horse_prancing_along_in_its_trappings_ass_carrying).
root(1,ROOT,wish).
nsubj(1,wish,i).
nsubj(1,you,i).
cop(1,you,were).
ccomp(1,wish,you).
were(1,i,you).
root(2,ROOT,sighed).
det(2,ass,the).
nsubj(2,sighed,ass).
root(3,ROOT,nothing).
mark(3,do,to).
xcomp(3,nothing,do).
cc(3,nothing,and).
advmod(3,fed,well).
conj:and(3,nothing,fed).
cc(3,fed,and).
det:predet(3,harness,all).
det(3,harness,that).
amod(3,harness,fine).
conj:and(3,nothing,harness).
conj:and(3,fed,harness).
case(3,you,upon).
nmod:upon(3,harness,you).
root(4,ROOT,wounded).
amod(4,day,next).
nsubjpass(4,wounded,day).
advmod(4,was,however).
expl(4,was,there).
dep(4,day,was).
det(4,battle,a).
amod(4,battle,great).
nsubj(4,was,battle).
cc(4,battle,and).
det(4,horse,the).
nsubj(4,was,horse).
conj:and(4,battle,horse).
auxpass(4,wounded,was).
case(4,death,to).
nmod:to(4,wounded,death).
case(4,charge,in).
det(4,charge,the).
amod(4,charge,final).
nmod:in(4,wounded,charge).
case(4,day,of).
det(4,day,the).
nmod:of(4,charge,day).
was_wounded_in(4,day,charge).
was(4,next_day,wounded).
was_wounded_in(4,next_day,charge).
was_wounded_in(4,day,final_charge).
was_wounded_to(4,next_day,death).
was(4,next_day,wounded_to_death_in_final_charge_of_day).
was(4,next_day,wounded_to_death_in_charge).
was(4,day,wounded_to_death_in_final_charge).
was_wounded_in(4,day,final_charge_of_day).
was_wounded_in(4,day,charge_of_day).
was(4,next_day,wounded_to_death_in_charge_of_day).
was(4,next_day,wounded_to_death_in_final_charge).
was(4,day,wounded_to_death_in_final_charge_of_day).
was(4,day,wounded).
was_wounded_in(4,next_day,final_charge).
was_wounded_in(4,next_day,charge_of_day).
was(4,day,wounded_to_death_in_charge_of_day).
was(4,day,wounded_to_death_in_charge).
was_wounded_in(4,next_day,final_charge_of_day).
was_wounded_to(4,day,death).
root(5,ROOT,happened).
nmod:poss(5,friend,his).
nsubj(5,happened,friend).
nsubj:xsubj(5,pass,friend).
nsubj(5,found,friend).
det(5,ass,the).
dep(5,friend,ass).
mark(5,pass,to).
xcomp(5,happened,pass).
case(5,shortly,by).
advcl:by(5,pass,shortly).
advmod(5,pass,afterwards).
cc(5,happened,and).
conj:and(5,happened,found).
dobj(5,found,him).
case(5,point,on).
det(5,point,the).
nmod:on(5,found,point).
case(5,death,of).
nmod:of(5,point,death).
pass_by(5,his_friend,shortly).
happened(5,his_friend,pass_afterwards).
found(5,his_friend,him).
happened(5,his_friend,pass).
pass_afterwards_by(5,his_friend,shortly).
root(6,ROOT,wrong).
nsubj(6,wrong,i).
cop(6,wrong,was).
was(6,i,wrong).
