root(0,ROOT,harangued).
det(0,hares,the).
nsubj(0,harangued,hares).
nsubj(0,argued,hares).
det(0,assembly,the).
dobj(0,harangued,assembly).
cc(0,harangued,and).
conj:and(0,harangued,argued).
mark(0,equal,that).
nsubj(0,equal,all).
aux(0,equal,should).
cop(0,equal,be).
ccomp(0,argued,equal).
be(0,all,equal).
harangued(0,hares,assembly).
root(1,ROOT,made).
det(1,lions,the).
nsubj(1,made,lions).
det(1,reply,this).
dobj(1,made,reply).
made(1,lions,reply).
root(2,ROOT,words).
nmod:poss(2,words,your).
compound(2,hares,o).
dep(2,words,hares).
root(3,ROOT,good).
cop(3,good,are).
root(4,ROOT,lack).
cc(4,lack,but).
nsubj(4,lack,they).
cc:preconj(4,claws,both).
nsubj(4,have,claws).
cc(4,claws,and).
conj:and(4,claws,teeth).
nsubj(4,have,teeth).
case(4,we,such).
mwe(4,such,as).
nmod:such_as(4,claws,we).
ccomp(4,lack,have).
