root(0,ROOT,painted).
det(0,jackdaw,a).
nsubj(0,painted,jackdaw).
nsubj(0,joined,jackdaw).
acl(0,jackdaw,seeing).
det(0,doves,some).
dobj(0,seeing,doves).
case(0,cote,in).
det(0,cote,a).
nmod:in(0,doves,cote).
advmod(0,provided,abundantly).
amod(0,cote,provided).
case(0,food,with).
nmod:with(0,seeing,food).
nsubj(0,white,himself).
xcomp(0,painted,white).
cc(0,painted,and).
conj:and(0,painted,joined).
dobj(0,joined,them).
mark(0,share,in).
mwe(0,in,order).
mark(0,share,to).
advcl:in_order(0,joined,share).
nmod:poss(0,maintenance,their).
amod(0,maintenance,plentiful).
dobj(0,share,maintenance).
is_in(0,doves,cote_abundantly_provided).
joined(0,jackdaw,them).
painted(0,jackdaw,himself_white).
root(1,ROOT,doves).
det(1,doves,the).
advmod(1,long,as).
dep(1,doves,long).
mark(1,silent,as).
nsubj(1,silent,he).
nsubj(1,admitted,he).
cop(1,silent,was).
dep(1,long,silent).
ccomp(1,silent,supposed).
dobj(1,supposed,him).
nsubj:xsubj(1,one,him).
mark(1,one,to).
cop(1,one,be).
det:qmod(1,themselves,one).
mwe(1,one,of).
xcomp(1,supposed,themselves).
cc(1,silent,and).
dep(1,long,admitted).
conj:and(1,silent,admitted).
dobj(1,admitted,him).
case(1,cote,to).
nmod:poss(1,cote,their).
nmod:to(1,admitted,cote).
root(2,ROOT,forgot).
cc(2,forgot,but).
advmod(2,forgot,when).
nummod(2,day,one).
nmod:tmod(2,forgot,day).
nsubj(2,forgot,he).
nsubj(2,began,he).
dobj(2,forgot,himself).
cc(2,forgot,and).
conj:and(2,forgot,began).
case(2,chatter,to).
nmod:to(2,began,chatter).
nsubj(2,discovered,they).
nsubj(2,drove,they).
acl:relcl(2,chatter,discovered).
nmod:poss(2,character,his).
amod(2,character,true).
dobj(2,discovered,character).
cc(2,discovered,and).
acl:relcl(2,chatter,drove).
conj:and(2,discovered,drove).
dobj(2,drove,him).
advmod(2,drove,forth).
xcomp(2,drove,pecking).
dobj(2,pecking,him).
case(2,beaks,with).
nmod:poss(2,beaks,their).
nmod:with(2,pecking,beaks).
discovered(2,they,his_character).
discovered(2,they,his_true_character).
drove_forth(2,they,him).
pecking(2,him,him).
forgot(2,he,himself).
drove(2,they,him).
root(3,ROOT,failing).
mark(3,obtain,to).
xcomp(3,failing,obtain).
dobj(3,obtain,food).
case(3,doves,among).
det(3,doves,the).
nmod:among(3,obtain,doves).
nsubj(3,returned,he).
acl:relcl(3,doves,returned).
case(3,jackdaws,to).
det(3,jackdaws,the).
nmod:to(3,returned,jackdaws).
returned_to(3,he,jackdaws).
root(4,ROOT,they).
advmod(4,not,too).
dep(4,they,not).
dep(4,not,recognizing).
dobj(4,recognizing,him).
case(4,color,on).
mwe(4,on,account).
mwe(4,on,of).
nmod:poss(4,color,his).
nmod:on_account_of(4,recognizing,color).
root(5,ROOT,expelled).
dobj(5,expelled,him).
mark(5,living,from).
advcl:from(5,expelled,living).
nmod(5,living,with).
nsubj(5,expelled,them).
expelled(5,them,him).
root(6,ROOT,desiring).
advmod(6,desiring,so).
nummod(6,ends,two).
dobj(6,desiring,ends).
nsubj(6,obtained,he).
acl:relcl(6,ends,obtained).
xcomp(6,obtained,neither).
obtained(6,he,neither).
