root(0,ROOT,hunter).
det(0,hunter,a).
amod(0,hunter,certain).
aux(0,snared,having).
dep(0,hunter,snared).
det(0,hare,a).
nsubj(0,placed,hare).
ccomp(0,snared,placed).
dobj(0,placed,it).
case(0,shoulders,upon).
nmod:poss(0,shoulders,his).
nmod:upon(0,placed,shoulders).
cc(0,snared,and).
dep(0,hunter,set).
conj:and(0,snared,set).
compound:prt(0,set,out).
advmod(0,set,homewards).
placed(0,hare,it).
root(1,ROOT,met).
case(1,way,on).
nmod:poss(1,way,his).
nmod:on(1,met,way).
nsubj(1,met,he).
det(1,man,a).
dobj(1,met,man).
nsubj(1,begged,man).
case(1,horseback,on).
nmod:on(1,man,horseback).
ref(1,man,who).
acl:relcl(1,man,begged).
det(1,hare,the).
dobj(1,begged,hare).
case(1,him,of).
nmod:of(1,hare,him).
case(1,pretense,under).
det(1,pretense,the).
nmod:under(1,begged,pretense).
mark(1,purchasing,of).
acl:of(1,pretense,purchasing).
dobj(1,purchasing,it).
root(2,ROOT,however).
advmod(2,got,when).
det(2,horseman,the).
nsubj(2,got,horseman).
dep(2,however,got).
det(2,hare,the).
dobj(2,got,hare).
nsubj(2,rode,he).
acl:relcl(2,hare,rode).
compound:prt(2,rode,off).
case(2,fast,as).
advmod(2,rode,fast).
mark(2,could,as).
nsubj(2,could,he).
advcl:as(2,rode,could).
rode_off_fast(2,he,he_could).
rode_off(2,he,he_could).
root(3,ROOT,ran).
det(3,hunter,the).
nsubj(3,ran,hunter).
case(3,him,after).
nmod:after(3,ran,him).
mark(3,sure,as).
mwe(3,as,if).
nsubj(3,sure,he).
cop(3,sure,was).
advcl:as_if(3,ran,sure).
mark(3,overtaking,of).
advcl:of(3,sure,overtaking).
dobj(3,overtaking,him).
cc(3,sure,but).
det(3,horseman,the).
nsubj(3,increased,horseman).
advcl:as_if(3,ran,increased).
conj:but(3,sure,increased).
advmod(3,increased,more).
cc(3,more,and).
advmod(3,increased,more).
conj:and(3,more,more).
det(3,distance,the).
dobj(3,increased,distance).
case(3,them,between).
nmod:between(3,distance,them).
increased_more(3,horseman,distance).
increased_more_and_more(3,horseman,distance).
was(3,he,sure).
distance_between(3,horseman,them).
increased_more(3,horseman,distance_between_them).
overtaking(3,he,him).
increased_more_and_more(3,horseman,distance_between_them).
ran_after(3,hunter,him).
increased(3,horseman,distance).
increased(3,horseman,distance_between_them).
ran(3,hunter,sure).
root(4,ROOT,called).
det(4,hunter,the).
nsubj(4,called,hunter).
nsubj(4,said,hunter).
advmod(4,his,sorely).
case(4,his,against).
nmod:against(4,hunter,his).
aux(4,called,will).
compound:prt(4,called,out).
case(4,him,to).
nmod:to(4,called,him).
cc(4,called,and).
conj:and(4,called,said).
will_called_out_to(4,hunter,him).
root(5,ROOT,get).
compound:prt(5,get,along).
case(5,you,with).
nmod:with(5,get,you).
root(6,ROOT,make).
case(6,i,for).
nmod:for(6,make,i).
aux(6,make,will).
advmod(6,make,now).
dobj(6,make,you).
det(6,present,a).
nsubj(6,make,present).
case(6,hare,of).
det(6,hare,the).
nmod:of(6,present,hare).
will_now_make(6,present,you).
will_make(6,present,you).
