root(0,ROOT,hid).
det(0,hart,a).
nsubj(0,hid,hart).
advmod(0,pressed,hard).
acl(0,hart,pressed).
case(0,chase,in).
det(0,chase,the).
nmod:in(0,pressed,chase).
dobj(0,hid,himself).
case(0,leaves,beneath).
det(0,leaves,the).
amod(0,leaves,large).
nmod:beneath(0,hid,leaves).
case(0,vine,of).
det(0,vine,a).
nmod:of(0,leaves,vine).
hid(0,hart,himself).
pressed_in(0,hart,chase).
hard_pressed_in(0,hart,chase).
root(1,ROOT,overshot).
det(1,huntsmen,the).
nsubj(1,overshot,huntsmen).
case(1,haste,in).
nmod:poss(1,haste,their).
nmod:in(1,huntsmen,haste).
det(1,place,the).
dobj(1,overshot,place).
case(1,concealment,of).
nmod:poss(1,concealment,his).
nmod:of(1,place,concealment).
overshot(1,huntsmen,place_of_his_concealment).
is_in(1,huntsmen,their_haste).
overshot(1,huntsmen,place).
root(2,ROOT,supposing).
det(2,danger,all).
dobj(2,supposing,danger).
mark(2,passed,to).
aux(2,passed,have).
acl:to(2,danger,passed).
det(2,hart,the).
nsubj(2,began,hart).
nsubj:xsubj(2,nibble,hart).
ccomp(2,passed,began).
mark(2,nibble,to).
xcomp(2,began,nibble).
det(2,tendrils,the).
dobj(2,nibble,tendrils).
case(2,vine,of).
det(2,vine,the).
nmod:of(2,tendrils,vine).
root(3,ROOT,looked).
det:qmod(3,huntsmen,one).
mwe(3,one,of).
det(3,huntsmen,the).
nsubj(3,looked,huntsmen).
nsubj(3,seeing,huntsmen).
nsubj(3,struck,huntsmen).
acl(3,huntsmen,attracted).
case(3,rustling,by).
det(3,rustling,the).
nmod:by(3,attracted,rustling).
case(3,leaves,of).
det(3,leaves,the).
nmod:of(3,rustling,leaves).
advmod(3,looked,back).
cc(3,looked,and).
conj:and(3,looked,seeing).
det(3,hart,the).
nsubj(3,shot,hart).
ccomp(3,seeing,shot).
det(3,arrow,an).
dobj(3,shot,arrow).
case(3,bow,from).
nmod:poss(3,bow,his).
nmod:from(3,shot,bow).
cc(3,looked,and).
conj:and(3,looked,struck).
dobj(3,struck,it).
shot(3,hart,arrow).
shot_arrow_from(3,hart,his_bow).
root(4,ROOT,groaned).
det(4,hart,the).
nsubj(4,groaned,hart).
case(4,point,at).
det(4,point,the).
nmod:at(4,hart,point).
case(4,death,of).
nmod:of(4,point,death).
root(5,ROOT,maltreated).
nsubjpass(5,served,i).
auxpass(5,served,am).
advmod(5,served,rightly).
dep(5,maltreated,served).
case(5,i,for).
nmod:for(5,served,i).
aux(5,maltreated,should).
neg(5,maltreated,not).
aux(5,maltreated,have).
det(5,vine,the).
dobj(5,maltreated,vine).
nsubj(5,saved,vine).
ref(5,vine,that).
acl:relcl(5,vine,saved).
nsubj(5,maltreated,me).
am_served_for(5,i,i).
am(5,i,served).
am(5,i,rightly_served).
am_rightly_served_for(5,i,i).
