root(0,ROOT,had).
det(0,cottager,a).
nsubj(0,had,cottager).
cc(0,cottager,and).
nmod:poss(0,wife,his).
conj:and(0,cottager,wife).
nsubj(0,had,wife).
det(0,hen,a).
dobj(0,had,hen).
nsubj(0,laid,hen).
ref(0,hen,that).
acl:relcl(0,hen,laid).
det(0,egg,a).
amod(0,egg,golden).
dobj(0,laid,egg).
det(0,day,every).
nmod:tmod(0,laid,day).
root(1,ROOT,supposed).
nsubj(1,supposed,they).
mark(1,contain,that).
det(1,hen,the).
nsubj(1,contain,hen).
nsubj(1,get,hen).
aux(1,contain,must).
advcl:that(1,supposed,contain).
det(1,lump,a).
amod(1,lump,great).
dobj(1,contain,lump).
case(1,gold,of).
nmod:of(1,lump,gold).
case(1,inside,in).
nmod:poss(1,inside,its).
nmod:in(1,contain,inside).
cc(1,contain,and).
mark(1,get,in).
mwe(1,in,order).
mark(1,get,to).
advcl:that(1,supposed,get).
conj:and(1,contain,get).
det(1,gold,the).
dobj(1,get,gold).
nsubj(1,killed,they).
acl:relcl(1,gold,killed).
dobj(1,killed,it).
lump_of(1,hen,gold).
killed(1,they,it).
must_contain(1,hen,lump).
must_contain(1,hen,great_lump).
must_contain(1,hen,lump_of_gold).
must_contain(1,hen,great_lump_of_gold).
must_contain_lump_in(1,hen,its_inside).
great_lump_of(1,hen,gold).
root(2,ROOT,done).
aux(2,done,having).
mark(2,found,so).
nsubj(2,found,they).
advcl:so(2,done,found).
case(2,surprise,to).
nmod:poss(2,surprise,their).
nmod:to(2,found,surprise).
mark(2,differed,that).
det(2,hen,the).
nsubj(2,differed,hen).
ccomp(2,found,differed).
case(2,respect,in).
neg(2,respect,no).
nmod:in(2,differed,respect).
case(2,hens,from).
nmod:poss(2,hens,their).
amod(2,hens,other).
nmod:from(2,differed,hens).
found_to(2,they,their_surprise).
root(3,ROOT,pair).
det(3,pair,the).
amod(3,pair,foolish).
advmod(3,hoping,thus).
acl(3,pair,hoping).
mark(3,become,to).
xcomp(3,hoping,become).
xcomp(3,become,rich).
advmod(3,deprived,all).
case(3,all,at).
advmod(3,deprived,once).
dep(3,become,deprived).
dobj(3,deprived,themselves).
case(3,gain,of).
det(3,gain,the).
nmod:of(3,pair,gain).
nmod:of(3,assured,gain).
case(3,which,of).
ref(3,gain,which).
nsubjpass(3,assured,they).
auxpass(3,assured,were).
acl:relcl(3,gain,assured).
nmod:tmod(3,assured,day).
case(3,day,by).
nmod:agent(3,assured,day).
were(3,they,assured_day_by_day).
were_assured_by(3,they,day).
were(3,they,assured).
were_assured_at_time(3,they,day).
