root(0,ROOT,had).
case(0,time,at).
nummod(0,time,one).
nmod:at(0,had,time).
det(0,horse,the).
nsubj(0,had,horse).
det(0,plain,the).
dobj(0,had,plain).
advmod(0,had,entirely).
case(0,himself,to).
nmod:to(0,entirely,himself).
had_entirely(0,horse,plain).
had(0,horse,plain).
root(1,ROOT,stag).
dep(1,stag,then).
det(1,stag,a).
ccomp(1,stag,intruded).
case(1,domain,into).
nmod:poss(1,domain,his).
nmod:into(1,intruded,domain).
cc(1,intruded,and).
ccomp(1,stag,shared).
conj:and(1,intruded,shared).
nmod:poss(1,pasture,his).
dobj(1,shared,pasture).
root(2,ROOT,asked).
det(2,horse,the).
nsubj(2,asked,horse).
acl(2,horse,desiring).
mark(2,revenge,to).
xcomp(2,desiring,revenge).
dobj(2,revenge,himself).
case(2,stranger,on).
det(2,stranger,the).
nmod:on(2,revenge,stranger).
det(2,man,a).
dobj(2,asked,man).
mark(2,willing,if).
nsubj(2,willing,he).
nsubj:xsubj(2,help,he).
cop(2,willing,were).
advcl:if(2,asked,willing).
mark(2,help,to).
xcomp(2,willing,help).
dobj(2,help,him).
mark(2,punishing,in).
advcl:in(2,help,punishing).
det(2,stag,the).
dobj(2,punishing,stag).
asked_man(2,horse,willing).
help(2,he,him).
asked(2,horse,man).
were(2,he,willing).
root(3,ROOT,replied).
det(3,man,the).
nsubj(3,replied,man).
mark(3,contrive,that).
mark(3,receive,if).
det(3,horse,the).
nsubj(3,receive,horse).
nsubj(3,agree,horse).
nsubj:xsubj(3,carry,horse).
aux(3,receive,would).
advcl:if(3,contrive,receive).
det(3,bit,a).
dobj(3,receive,bit).
case(3,mouth,in).
nmod:poss(3,mouth,his).
nmod:in(3,bit,mouth).
cc(3,receive,and).
conj:and(3,receive,agree).
advcl:if(3,contrive,agree).
mark(3,carry,to).
xcomp(3,agree,carry).
dobj(3,carry,him).
nsubj(3,contrive,he).
aux(3,contrive,would).
ccomp(3,replied,contrive).
amod(3,weapons,effective).
dobj(3,contrive,weapons).
case(3,stag,against).
det(3,stag,the).
nmod:against(3,contrive,stag).
is_in(3,bit,his_mouth).
contrive(3,he,effective_weapons).
would_receive(3,horse,bit).
bit_in(3,horse,his_mouth).
contrive_weapons_against(3,he,stag).
contrive(3,he,weapons).
would_receive(3,horse,bit_in_his_mouth).
root(4,ROOT,consented).
det(4,horse,the).
nsubj(4,consented,horse).
nsubj(4,allowed,horse).
cc(4,consented,and).
conj:and(4,consented,allowed).
det(4,man,the).
dobj(4,consented,man).
mark(4,mount,to).
acl:to(4,man,mount).
dobj(4,mount,him).
root(5,ROOT,found).
case(5,hour,from).
det(5,hour,that).
nmod:from(5,found,hour).
nsubj(5,found,he).
mark(5,enslaved,that).
mark(5,obtaining,instead).
mwe(5,instead,of).
advcl:instead_of(5,enslaved,obtaining).
dobj(5,obtaining,revenge).
case(5,stag,on).
det(5,stag,the).
nmod:on(5,obtaining,stag).
nsubj(5,enslaved,he).
aux(5,enslaved,had).
ccomp(5,found,enslaved).
dobj(5,enslaved,himself).
case(5,service,to).
det(5,service,the).
nmod:to(5,enslaved,service).
case(5,man,of).
nmod:of(5,service,man).
obtaining_revenge_on(5,he,stag).
found_from(5,he,hour).
obtaining(5,he,revenge).
enslaved(5,he,himself).
