root(0,ROOT,settled).
det(0,gnat,a).
nsubj(0,settled,gnat).
nsubj(0,sat,gnat).
case(0,horn,on).
det(0,horn,the).
nmod:on(0,settled,horn).
case(0,bull,of).
det(0,bull,a).
nmod:of(0,horn,bull).
cc(0,settled,and).
conj:and(0,settled,sat).
expl(0,time,there).
det(0,time,a).
amod(0,time,long).
xcomp(0,sat,time).
sat(0,gnat,long_time).
settled_on(0,gnat,horn).
settled_on(0,gnat,horn_of_bull).
sat(0,gnat,time).
root(1,ROOT,just).
mark(1,about,as).
nsubj(1,about,he).
nsubj:xsubj(1,fly,he).
aux(1,about,was).
dep(1,just,about).
mark(1,fly,to).
xcomp(1,about,fly).
advmod(1,made,off).
nsubj(1,made,he).
nsubj(1,inquired,he).
ccomp(1,fly,made).
det(1,noise,a).
amod(1,noise,buzzing).
dobj(1,made,noise).
cc(1,made,and).
ccomp(1,fly,inquired).
conj:and(1,made,inquired).
case(1,bull,of).
det(1,bull,the).
nmod:of(1,inquired,bull).
mark(1,like,if).
nsubj(1,like,he).
aux(1,like,would).
advcl:if(1,inquired,like).
dobj(1,like,him).
nsubj:xsubj(1,go,him).
mark(1,go,to).
xcomp(1,like,go).
root(2,ROOT,replied).
det(2,bull,the).
nsubj(2,replied,bull).
root(3,ROOT,know).
nsubj(3,know,i).
aux(3,know,did).
neg(3,know,not).
nsubj(3,come,you).
aux(3,come,had).
xcomp(3,know,come).
cc(3,come,and).
nsubj(3,miss,i).
aux(3,miss,shall).
neg(3,miss,not).
xcomp(3,know,miss).
conj:and(3,come,miss).
dobj(3,miss,you).
advmod(3,go,when).
nsubj(3,go,you).
advcl(3,miss,go).
advmod(3,go,away).
root(4,ROOT,consequence).
det(4,men,some).
nsubj(4,consequence,men).
cop(4,consequence,are).
case(4,consequence,of).
amod(4,consequence,more).
case(4,eyes,in).
nmod:poss(4,eyes,their).
amod(4,eyes,own).
nmod:in(4,consequence,eyes).
advmod(4,consequence,than).
case(4,eyes,in).
det(4,eyes,the).
nmod:in(4,than,eyes).
case(4,neighbors,of).
nmod:poss(4,neighbors,their).
nmod:of(4,eyes,neighbors).
are_of(4,men,consequence_in_their_own_eyes_than_in_eyes_of_their_neighbors).
are_of(4,men,more_consequence_in_their_own_eyes_than_in_eyes_of_their_neighbors).
is_in(4,more_consequence,their_own_eyes).
