root(0,ROOT,used).
det(0,groom,a).
nsubj(0,used,groom).
nsubj:xsubj(0,spend,groom).
nsubj(0,rubbing,groom).
mark(0,spend,to).
xcomp(0,used,spend).
amod(0,days,whole).
nmod:tmod(0,spend,days).
case(0,currycombing,in).
nmod:in(0,spend,currycombing).
cc(0,used,and).
conj:and(0,used,rubbing).
compound:prt(0,rubbing,down).
nmod:poss(0,horse,his).
dobj(0,rubbing,horse).
cc(0,time,but).
case(0,time,at).
det(0,time,the).
amod(0,time,same).
nmod:at(0,rubbing,time).
acl:relcl(0,time,stole).
nmod:poss(0,oats,his).
dobj(0,stole,oats).
cc(0,stole,and).
acl:relcl(0,time,sold).
conj:and(0,stole,sold).
dobj(0,sold,them).
case(0,profit,for).
nmod:poss(0,profit,his).
amod(0,profit,own).
nmod:for(0,sold,profit).
used(0,groom,spend_days).
spend_in(0,groom,currycombing).
used(0,groom,spend_in_currycombing).
sold(0,his_oats,them).
used(0,groom,spend_whole_days).
spend_at_time(0,groom,whole_days).
spend_at_time(0,groom,days).
used(0,groom,spend_days_in_currycombing).
used(0,groom,spend).
used(0,groom,spend_whole_days_in_currycombing).
rubbing_down(0,groom,his_horse).
root(1,ROOT,alas).
root(2,ROOT,said).
det(2,horse,the).
nsubj(2,said,horse).
root(3,ROOT,wish).
mark(3,wish,if).
nsubj(3,wish,you).
advmod(3,wish,really).
dobj(3,wish,me).
nsubj:xsubj(3,condition,me).
mark(3,condition,to).
cop(3,condition,be).
case(3,condition,in).
amod(3,condition,good).
xcomp(3,wish,condition).
nsubj(3,groom,you).
nsubj(3,feed,you).
aux(3,groom,should).
acl:relcl(3,condition,groom).
nsubj(3,less,me).
xcomp(3,groom,less).
cc(3,groom,and).
acl:relcl(3,condition,feed).
conj:and(3,groom,feed).
dobj(3,feed,me).
advmod(3,feed,more).
feed_more(3,you,me).
really_wish(3,you,me).
wish(3,you,me).
feed(3,you,me).
should_groom(3,you,me_less).
