root(0,ROOT,found).
det(0,goatherd,a).
nsubj(0,found,goatherd).
acl(0,goatherd,driving).
nmod:poss(0,flock,his).
dobj(0,driving,flock).
case(0,pasture,from).
nmod:poss(0,pasture,their).
nmod:from(0,driving,pasture).
case(0,eventide,at).
nmod:at(0,pasture,eventide).
det(0,goats,some).
amod(0,goats,wild).
nsubj(0,mingled,goats).
nsubj(0,shut,goats).
ccomp(0,found,mingled).
case(0,them,among).
nmod:among(0,mingled,them).
cc(0,mingled,and).
ccomp(0,found,shut).
conj:and(0,mingled,shut).
dobj(0,shut,them).
compound:prt(0,shut,up).
case(0,own,together).
mwe(0,together,with).
nmod:poss(0,own,his).
nmod:together_with(0,shut,own).
case(0,night,for).
det(0,night,the).
nmod:for(0,shut,night).
driving_his_flock_from(0,goatherd,their_pasture).
mingled_among(0,wild_goats,them).
mingled_among(0,goats,them).
driving(0,goatherd,his_flock).
shut_up(0,goats,them).
driving_his_flock_from(0,goatherd,their_pasture_eventide).
shut_up(0,wild_goats,them).
root(1,ROOT,day).
det(1,day,the).
amod(1,day,next).
nsubj(1,snowed,it).
acl:relcl(1,day,snowed).
advmod(1,hard,very).
xcomp(1,snowed,hard).
mark(1,take,so).
mwe(1,so,that).
nsubj(1,take,he).
aux(1,take,could).
neg(1,take,not).
advcl:so_that(1,snowed,take).
det(1,herd,the).
dobj(1,take,herd).
case(1,places,to).
nmod:poss(1,places,their).
amod(1,places,usual).
compound(1,places,feeding).
nmod:to(1,take,places).
cc(1,obliged,but).
auxpass(1,obliged,was).
dep(1,day,obliged).
mark(1,keep,to).
xcomp(1,obliged,keep).
dobj(1,keep,them).
case(1,fold,in).
det(1,fold,the).
nmod:in(1,keep,fold).
root(2,ROOT,gave).
nsubj(2,gave,he).
nsubj(2,fed,he).
nmod:poss(2,goats,his).
amod(2,goats,own).
dep(2,gave,goats).
advmod(2,sufficient,just).
amod(2,food,sufficient).
dobj(2,gave,food).
mark(2,keep,to).
advcl:to(2,gave,keep).
nsubj(2,alive,them).
xcomp(2,keep,alive).
cc(2,gave,but).
conj:but(2,gave,fed).
det(2,strangers,the).
dobj(2,fed,strangers).
advmod(2,abundantly,more).
advmod(2,fed,abundantly).
case(2,hope,in).
det(2,hope,the).
nmod:in(2,fed,hope).
mark(2,enticing,of).
acl:of(2,hope,enticing).
dobj(2,enticing,them).
nsubj:xsubj(2,stay,them).
mark(2,stay,to).
xcomp(2,enticing,stay).
case(2,him,with).
nmod:with(2,stay,him).
cc(2,hope,and).
mark(2,making,of).
nmod:in(2,fed,making).
conj:and(2,hope,making).
nsubj(2,own,them).
nmod:poss(2,own,his).
xcomp(2,making,own).
gave(2,he,just_sufficient_food).
fed(2,he,strangers).
keep(2,he,them_alive).
gave(2,he,sufficient_food).
stay_with(2,them,him).
fed_more_abundantly(2,he,strangers).
fed_abundantly(2,he,strangers).
gave(2,he,food).
gave_food(2,he,keep).
root(3,ROOT,set).
advmod(3,set,when).
det(3,thaw,the).
nsubj(3,set,thaw).
mark(3,led,in).
nsubj(3,led,he).
advcl:in(3,set,led).
dobj(3,led,them).
dep(3,out,all).
advmod(3,led,out).
mark(3,feed,to).
advcl:to(3,led,feed).
cc(3,led,and).
det(3,goats,the).
amod(3,goats,wild).
nsubj(3,scampered,goats).
advcl:in(3,set,scampered).
conj:and(3,led,scampered).
advmod(3,fast,away).
advmod(3,fast,as).
advmod(3,scampered,fast).
mark(3,could,as).
nsubj(3,could,they).
advcl:as(3,scampered,could).
case(3,mountains,to).
det(3,mountains,the).
nmod:to(3,could,mountains).
scampered_fast(3,wild_goats,they_could).
scampered_away_as_fast(3,goats,they_could).
scampered(3,goats,they_could_to_mountains).
scampered_fast(3,wild_goats,they_could_to_mountains).
scampered_as_fast(3,goats,they_could_to_mountains).
scampered_as_fast(3,goats,they_could).
scampered_away_fast(3,goats,they_could_to_mountains).
scampered_away_as_fast(3,wild_goats,they_could_to_mountains).
scampered(3,wild_goats,they_could_to_mountains).
led(3,he,them).
scampered_away_fast(3,wild_goats,they_could).
scampered_as_fast(3,wild_goats,they_could).
scampered_away_fast(3,goats,they_could).
scampered_away_as_fast(3,goats,they_could_to_mountains).
scampered_fast(3,goats,they_could_to_mountains).
scampered_as_fast(3,wild_goats,they_could_to_mountains).
scampered(3,goats,they_could).
scampered(3,wild_goats,they_could).
scampered_fast(3,goats,they_could).
led_out(3,he,them).
scampered_away_fast(3,wild_goats,they_could_to_mountains).
scampered_away_as_fast(3,wild_goats,they_could).
root(4,ROOT,scolded).
det(4,goatherd,the).
nsubj(4,scolded,goatherd).
dobj(4,scolded,them).
case(4,ingratitude,for).
nmod:poss(4,ingratitude,their).
nmod:for(4,scolded,ingratitude).
mark(4,leaving,in).
advcl:in(4,scolded,leaving).
dobj(4,leaving,him).
advmod(4,taken,when).
case(4,storm,during).
det(4,storm,the).
nmod:during(4,taken,storm).
nsubj(4,taken,he).
aux(4,taken,had).
advcl(4,leaving,taken).
advmod(4,taken,more).
dobj(4,taken,care).
case(4,them,of).
nmod:of(4,care,them).
case(4,herd,than).
case(4,herd,of).
nmod:poss(4,herd,his).
amod(4,herd,own).
nmod:of(4,taken,herd).
leaving(4,goatherd,him).
had_taken(4,he,care).
had_taken_more(4,he,care_of_them).
had_taken_more_care_than(4,he,than_his_own_herd).
had_taken_more_care_during(4,he,storm).
had_taken(4,he,care_of_them).
had_taken_care_than(4,he,than_his_own_herd).
had_taken_more(4,he,care).
had_taken_more_care_than(4,he,than_his_herd).
had_taken_care_during(4,he,storm).
scolded(4,goatherd,them).
care_of(4,he,them).
had_taken_care_than(4,he,than_his_herd).
root(5,ROOT,said).
nsubj(5,said,one).
mark(5,turning,of).
nsubj(5,turning,them).
acl:of(5,one,turning).
advmod(5,turning,about).
case(5,him,to).
nmod:to(5,said,him).
root(6,ROOT,reason).
nsubj(6,reason,that).
cop(6,reason,is).
det(6,reason,the).
amod(6,reason,very).
advmod(6,cautious,why).
nsubj(6,cautious,we).
cop(6,cautious,are).
advmod(6,cautious,so).
acl:relcl(6,reason,cautious).
are(6,we,why_cautious).
are(6,we,why_so_cautious).
are(6,we,cautious).
are(6,we,so_cautious).
root(7,ROOT,had).
mark(7,had,for).
mark(7,treated,if).
nsubj(7,treated,you).
nmod:tmod(7,treated,yesterday).
advcl:if(7,had,treated).
nsubj(7,better,us).
xcomp(7,treated,better).
case(7,goats,than).
det(7,goats,the).
nmod:than(7,treated,goats).
nsubj(7,had,you).
aux(7,had,have).
advmod(7,long,so).
advmod(7,plain,long).
nsubj(7,plain,it).
cop(7,plain,is).
ccomp(7,had,plain).
advmod(7,plain,also).
mark(7,would,that).
mark(7,came,if).
nsubj(7,came,others).
advcl:if(7,would,came).
case(7,us,after).
nmod:after(7,came,us).
nsubj(7,would,you).
ccomp(7,plain,would).
mark(7,prefer,in).
det(7,manner,the).
amod(7,manner,same).
nsubj(7,prefer,manner).
advcl:in(7,had,prefer).
dobj(7,prefer,them).
case(7,ourselves,to).
nmod:to(7,prefer,ourselves).
treated_than(7,you,goats).
treated_at_time(7,you,yesterday).
have_had(7,you,you_yesterday_treated_than_goats).
is(7,it,plain_also).
prefer(7,same_manner,them).
is(7,it,long_plain).
have_had(7,you,you_yesterday_treated).
is(7,it,long_plain_also).
is(7,it,plain).
is(7,it,so_long_plain).
is(7,it,so_long_plain_also).
have_had(7,you,you_treated_than_goats).
have_had(7,you,you_treated).
prefer(7,manner,them).
treated(7,you,us_better).
