%% a raven saw a swan and desired to secure for himself the same beautiful plumage.
% dependencies.
root(0,root,see).
det(0,raven,a).
dep(0,see,raven).
det(0,swan,a).
dobj(0,see,swan).
nsubj:xsubj(0,secure,swan).
cc(0,swan,and).
dobj(0,see,desire).
conj:and(0,swan,desire).
nsubj:xsubj(0,secure,desire).
mark(0,secure,to).
xcomp(0,see,secure).
case(0,himself,for).
nmod:for(0,secure,himself).
det(0,plumage,the).
amod(0,plumage,same).
amod(0,plumage,beautiful).
nsubj(0,see,plumage).
% relations.
aos(0,see,same_beautiful_plumage,desire).
aos(0,see,plumage,swan).
aos(0,see,beautiful_plumage,swan).
aos(0,see,same_beautiful_plumage,swan).
aos(0,see,plumage,desire).
aos(0,see,same_plumage,swan).
aos(0,see,beautiful_plumage,desire).
aos(0,see,same_plumage,desire).
aos(0,secure_for,desire,himself).
%% supposing that the swan 's splendid white color arose from his washing in the water in which he swam the raven left the altars in the neighborhood where he picked up his living and took up residence in the lakes and pools.
% dependencies.
root(1,root,suppose).
mark(1,arise,that).
det(1,swan,the).
nmod:poss(1,color,swan).
case(1,swan,'s).
amod(1,color,splendid).
amod(1,color,white).
nsubj(1,arise,color).
ccomp(1,suppose,arise).
mark(1,wash,from).
nsubj(1,wash,he).
advcl:from(1,arise,wash).
case(1,water,in).
det(1,water,the).
nmod:in(1,wash,water).
nmod:in(1,swim,water).
case(1,which,in).
ref(1,water,which).
nsubj(1,swim,he).
acl:relcl(1,water,swim).
det(1,raven,the).
nsubj(1,leave,raven).
ccomp(1,swim,leave).
det(1,altar,the).
dobj(1,leave,altar).
case(1,neighborhood,in).
det(1,neighborhood,the).
nmod:in(1,leave,neighborhood).
advmod(1,pick,where).
nsubj(1,pick,he).
nsubj(1,take,he).
advcl(1,leave,pick).
compound:prt(1,pick,up).
nmod:poss(1,living,he).
dobj(1,pick,living).
cc(1,pick,and).
advcl(1,leave,take).
conj:and(1,pick,take).
compound:prt(1,take,up).
dobj(1,take,residence).
case(1,lakes,in).
det(1,lakes,the).
nmod:in(1,residence,lakes).
cc(1,lakes,and).
nmod:in(1,residence,pool).
conj:and(1,lakes,pool).
% relations.
aos(1,is_in,residence,lakes).
aos(1,has,swan,splendid_white_color).
%% but cleansing his feathers as often as he would he could not change their color while through want of food he perished.
% dependencies.
root(2,root,cleanse).
cc(2,cleanse,but).
nmod:poss(2,feather,he).
dobj(2,cleanse,feather).
advmod(2,often,as).
advmod(2,cleanse,often).
mark(2,would,as).
nsubj(2,would,he).
advcl:as(2,change,would).
nsubj(2,change,he).
aux(2,change,could).
neg(2,change,not).
dep(2,often,change).
nmod:poss(2,color,they).
dobj(2,change,color).
mark(2,perish,while).
mark(2,want,through).
advcl:through(2,perish,want).
case(2,food,of).
nmod:of(2,want,food).
nsubj(2,perish,he).
advcl:while(2,change,perish).
% relations.
