root(0,ROOT,saw).
det(0,travelers,some).
nsubj(0,saw,travelers).
dep(0,travelers,journeying).
case(0,seashore,along).
det(0,seashore,the).
nmod:along(0,journeying,seashore).
acl(0,seashore,climbed).
case(0,summit,to).
det(0,summit,the).
nmod:to(0,climbed,summit).
case(0,cliff,of).
det(0,cliff,a).
amod(0,cliff,tall).
nmod:of(0,summit,cliff).
cc(0,journeying,and).
dep(0,travelers,looking).
conj:and(0,journeying,looking).
case(0,sea,over).
det(0,sea,the).
nmod:over(0,looking,sea).
case(0,distance,in).
det(0,distance,the).
nmod:in(0,saw,distance).
dobj(0,thought,what).
nsubj(0,thought,they).
ccomp(0,saw,thought).
cop(0,ship,was).
det(0,ship,a).
amod(0,ship,large).
ccomp(0,thought,ship).
saw_in(0,travelers,distance).
root(1,ROOT,waited).
nsubj(1,waited,they).
case(1,hope,in).
det(1,hope,the).
nmod:in(1,found,hope).
mark(1,seeing,of).
acl:of(1,hope,seeing).
nsubj(1,enter,it).
advcl(1,seeing,enter).
det(1,harbor,the).
dobj(1,enter,harbor).
cc(1,enter,but).
mark(1,driven,as).
det(1,object,the).
nmod:on(1,looked,object).
nsubjpass(1,driven,object).
case(1,which,on).
ref(1,object,which).
nsubj(1,looked,they).
acl:relcl(1,object,looked).
auxpass(1,driven,was).
advcl(1,seeing,driven).
conj:but(1,enter,driven).
mark(1,shore,nearer).
mark(1,shore,to).
advcl:to(1,driven,shore).
case(1,wind,by).
det(1,wind,the).
nmod:by(1,shore,wind).
nsubj(1,found,they).
ccomp(1,waited,found).
mark(1,boat,that).
nsubj(1,boat,it).
aux(1,boat,could).
case(1,the,at).
advmod(1,boat,the).
advmod(1,boat,most).
cop(1,boat,be).
det(1,boat,a).
amod(1,boat,small).
ccomp(1,found,boat).
cc(1,boat,and).
neg(1,ship,not).
det(1,ship,a).
ccomp(1,found,ship).
conj:and(1,boat,ship).
enter(1,it,harbor).
root(2,ROOT,reached).
advmod(2,reached,when).
advmod(2,reached,however).
nsubj(2,reached,it).
det(2,beach,the).
dobj(2,reached,beach).
mark(2,faggot,beach).
nsubj(2,discovered,they).
acl:relcl(2,beach,discovered).
ref(2,beach,that).
nsubj(2,faggot,it).
cop(2,faggot,was).
advmod(2,faggot,only).
det(2,faggot,a).
amod(2,faggot,large).
ccomp(2,discovered,faggot).
case(2,sticks,of).
nmod:of(2,faggot,sticks).
cc(2,reached,and).
det:qmod(2,them,one).
mwe(2,one,of).
nsubj(2,said,them).
conj:and(2,reached,said).
case(2,companions,to).
nmod:poss(2,companions,his).
nmod:to(2,said,companions).
was_faggot_of(2,it,sticks).
was_only_faggot_of(2,it,sticks).
was(2,it,only_faggot).
was(2,it,only_large_faggot).
was_only_large_faggot_of(2,it,sticks).
was_large_faggot_of(2,it,sticks).
was(2,it,large).
was(2,it,faggot).
was(2,it,large_faggot).
root(3,ROOT,waited).
nsubj(3,waited,we).
aux(3,waited,have).
case(3,purpose,for).
neg(3,purpose,no).
nmod:for(3,waited,purpose).
mark(3,is,for).
case(3,all,after).
nmod:after(3,is,all).
expl(3,is,there).
advcl:for(3,waited,is).
nsubj(3,is,nothing).
mark(3,see,to).
acl:to(3,nothing,see).
case(3,load,but).
det(3,load,a).
nmod:but(3,see,load).
case(3,wood,of).
nmod:of(3,load,wood).
see_but(3,nothing,load_wood).
see_but(3,nothing,load_of_wood).
