root(0,ROOT,doe).
det(0,doe,the).
amod(0,doe,one-eyed).
det(0,doe,a).
nsubjpass(0,accustomed,doe).
nsubj:xsubj(0,graze,doe).
amod(0,doe,blind).
case(0,eye,in).
nummod(0,eye,one).
nmod:in(0,blind,eye).
auxpass(0,accustomed,was).
acl:relcl(0,doe,accustomed).
mark(0,graze,to).
xcomp(0,accustomed,graze).
advmod(0,graze,as).
case(0,edge,near).
mwe(0,near,to).
det(0,edge,the).
nmod:near_to(0,as,edge).
case(0,cliff,of).
det(0,cliff,the).
nmod:of(0,edge,cliff).
mark(0,could,as).
nsubj(0,could,she).
advmod(0,could,possibly).
advcl:as(0,graze,could).
case(0,hope,in).
det(0,hope,the).
nmod:in(0,doe,hope).
mark(0,securing,of).
acl:of(0,hope,securing).
nmod:poss(0,safety,her).
amod(0,safety,greater).
dobj(0,securing,safety).
was_accustomed(0,doe,graze).
was_accustomed(0,doe,graze_as).
was(0,doe,accustomed).
graze(0,doe,she_possibly_could).
graze_as(0,doe,she_possibly_could).
graze(0,doe,she_could).
graze_as(0,doe,she_could).
is_in(0,one-eyed_doe,hope_securing).
root(1,ROOT,turned).
nsubj(1,turned,she).
nmod:poss(1,eye,her).
compound(1,eye,sound).
dobj(1,turned,eye).
case(1,land,towards).
det(1,land,the).
nmod:towards(1,turned,land).
mark(1,get,that).
nsubj(1,get,she).
aux(1,get,might).
ccomp(1,turned,get).
det(1,tidings,the).
amod(1,tidings,earliest).
dobj(1,get,tidings).
case(1,approach,of).
det(1,approach,the).
nmod:of(1,tidings,approach).
case(1,hunter,of).
nmod:of(1,approach,hunter).
cc(1,hunter,or).
nmod:of(1,approach,hound).
conj:or(1,hunter,hound).
cc(1,approach,and).
nmod:poss(1,eye,her).
amod(1,eye,injured).
nmod:of(1,tidings,eye).
conj:and(1,approach,eye).
case(1,sea,towards).
det(1,sea,the).
nmod:towards(1,eye,sea).
case(1,whence,from).
nmod:from(1,get,whence).
nsubj(1,entertained,she).
acl:relcl(1,whence,entertained).
neg(1,anticipation,no).
dobj(1,entertained,anticipation).
case(1,danger,of).
nmod:of(1,anticipation,danger).
get(1,she,earliest_tidings).
get(1,she,earliest_tidings_of_approach).
tidings_of(1,she,approach_of_hunter).
tidings_of(1,she,approach).
get(1,she,tidings_of_approach).
earliest_tidings_of(1,she,approach).
get(1,she,tidings_of_approach_of_hunter).
earliest_tidings_of(1,she,approach_of_hunter).
turned(1,she,her_sound_eye).
get(1,she,earliest_tidings_of_approach_of_hunter).
get(1,she,tidings).
turned_towards(1,she,land).
root(2,ROOT,wounded).
det(2,sailing,some).
compound(2,sailing,boatmen).
nsubj(2,wounded,sailing).
case(2,saw,by).
nmod:by(2,sailing,saw).
dobj(2,saw,her).
cc(2,saw,and).
nmod:by(2,sailing,taking).
conj:and(2,saw,taking).
det(2,aim,a).
amod(2,aim,successful).
dobj(2,taking,aim).
advmod(2,taking,mortally).
dobj(2,wounded,her).
wounded(2,boatmen_sailing,her).
root(3,ROOT,yielding).
compound:prt(3,yielding,up).
nmod:poss(3,breath,her).
amod(3,breath,last).
dobj(3,yielding,breath).
nsubj(3,gasped,she).
acl:relcl(3,breath,gasped).
advmod(3,gasped,forth).
det(3,lament,this).
nmod:npmod(3,forth,lament).
root(4,ROOT,creature).
compound(4,creature,o).
amod(4,creature,wretched).
dobj(4,am,creature).
ref(4,creature,that).
nsubj(4,am,i).
acl:relcl(4,creature,am).
root(5,ROOT,take).
mark(5,take,to).
amod(5,precaution,such).
dobj(5,take,precaution).
case(5,land,against).
det(5,land,the).
nmod:against(5,take,land).
cc(5,take,and).
case(5,all,after).
nmod:after(5,take,all).
mark(5,find,to).
acl:to(5,all,find).
det(5,seashore,this).
nmod:to(5,come,seashore).
nsubj(5,perilous,seashore).
case(5,which,to).
ref(5,seashore,which).
nsubj(5,come,i).
aux(5,come,had).
acl:relcl(5,seashore,come).
case(5,safety,for).
nmod:for(5,come,safety).
advmod(5,much,so).
advmod(5,perilous,much).
advmod(5,perilous,more).
xcomp(5,find,perilous).
