root(0,ROOT,said).
det(0,rose,a).
nsubj(0,said,rose).
cc(0,rose,and).
det(0,amaranth,an).
conj:and(0,rose,amaranth).
nsubj(0,said,amaranth).
acl(0,amaranth,blossomed).
dobj(0,blossomed,side).
case(0,side,by).
nmod:by(0,blossomed,side).
case(0,garden,in).
det(0,garden,a).
nmod:in(0,blossomed,garden).
cc(0,garden,and).
det(0,amaranth,the).
nmod:in(0,blossomed,amaranth).
conj:and(0,garden,amaranth).
case(0,neighbor,to).
nmod:poss(0,neighbor,her).
nmod:to(0,said,neighbor).
blossomed_side_in(0,amaranth,garden).
said_to(0,amaranth,her_neighbor).
blossomed(0,amaranth,side).
blossomed_side_by(0,amaranth,side).
said_to(0,rose,her_neighbor).
root(1,ROOT,how).
dep(1,how,i).
dep(1,i,envy).
dep(1,envy,you).
nmod:poss(1,beauty,your).
dep(1,envy,beauty).
cc(1,beauty,and).
nmod:poss(1,scent,your).
amod(1,scent,sweet).
dep(1,envy,scent).
conj:and(1,beauty,scent).
root(2,ROOT,wonder).
neg(2,wonder,no).
nsubj(2,favorite,you).
cop(2,favorite,are).
case(2,favorite,such).
det(2,favorite,a).
amod(2,favorite,universal).
ccomp(2,wonder,favorite).
root(3,ROOT,rose).
cc(3,rose,but).
det(3,rose,the).
acl:relcl(3,rose,replied).
case(3,shade,with).
det(3,shade,a).
nmod:with(3,replied,shade).
case(3,sadness,of).
nmod:of(3,shade,sadness).
case(3,voice,in).
nmod:poss(3,voice,her).
nmod:in(3,rose,voice).
is_in(3,rose,her_voice).
root(4,ROOT,ah).
nmod:poss(4,friend,my).
amod(4,friend,dear).
dobj(4,ah,friend).
compound(4,bloom,i).
dep(4,friend,bloom).
cc(4,time,but).
case(4,time,for).
det(4,time,a).
nmod:for(4,bloom,time).
nmod:poss(4,petals,my).
nsubj(4,wither,petals).
nsubj(4,fall,petals).
advmod(4,wither,soon).
acl:relcl(4,bloom,wither).
cc(4,wither,and).
acl:relcl(4,bloom,fall).
conj:and(4,wither,fall).
cc(4,wither,and).
advmod(4,die,then).
nsubj(4,die,i).
acl:relcl(4,bloom,die).
conj:and(4,wither,die).
root(5,ROOT,fade).
cc(5,fade,but).
nmod:poss(5,flowers,your).
nsubj(5,fade,flowers).
neg(5,fade,never).
advmod(5,cut,even).
mark(5,cut,if).
nsubjpass(5,cut,they).
auxpass(5,cut,are).
advcl:if(5,fade,cut).
are(5,they,cut).
are(5,they,even_cut).
root(6,ROOT,everlasting).
mark(6,everlasting,for).
nsubj(6,everlasting,they).
cop(6,everlasting,are).
are(6,they,everlasting).
