root(0,ROOT,apple-tree).
det(0,peasant,a).
nsubj(0,apple-tree,peasant).
aux(0,apple-tree,had).
case(0,garden,in).
nmod:poss(0,garden,his).
nmod:in(0,apple-tree,garden).
det(0,apple-tree,an).
nsubj(0,bore,apple-tree).
nsubj(0,served,apple-tree).
ref(0,apple-tree,which).
acl:relcl(0,apple-tree,bore).
neg(0,fruit,no).
dobj(0,bore,fruit).
cc(0,bore,but).
advmod(0,served,only).
acl:relcl(0,apple-tree,served).
conj:but(0,bore,served).
case(0,harbor,as).
det(0,harbor,a).
nmod:as(0,served,harbor).
case(0,sparrows,for).
det(0,sparrows,the).
nmod:for(0,harbor,sparrows).
cc(0,sparrows,and).
nmod:for(0,harbor,grasshoppers).
conj:and(0,sparrows,grasshoppers).
root(1,ROOT,resolved).
nsubj(1,resolved,he).
nsubj:xsubj(1,cut,he).
mark(1,cut,to).
xcomp(1,resolved,cut).
dobj(1,cut,it).
advmod(1,and,down).
advmod(1,resolved,and).
conj(1,and,taking).
nmod:poss(1,axe,his).
dobj(1,taking,axe).
case(1,hand,in).
nmod:poss(1,hand,his).
nmod:in(1,taking,hand).
acl(1,hand,made).
det(1,stroke,a).
amod(1,stroke,bold).
dobj(1,made,stroke).
case(1,roots,at).
nmod:poss(1,roots,its).
nmod:at(1,made,roots).
cut(1,he,it).
root(2,ROOT,grasshoppers).
det(2,grasshoppers,the).
cc(2,grasshoppers,and).
conj:and(2,grasshoppers,sparrows).
acl:relcl(2,grasshoppers,entreated).
dobj(2,entreated,him).
nsubj:xsubj(2,cut,him).
neg(2,cut,not).
mark(2,cut,to).
xcomp(2,entreated,cut).
compound:prt(2,cut,down).
det(2,tree,the).
dobj(2,cut,tree).
nsubj(2,sheltered,tree).
ref(2,tree,that).
acl:relcl(2,tree,sheltered).
dobj(2,sheltered,them).
cc(2,spare,but).
mark(2,spare,to).
dep(2,grasshoppers,spare).
nsubj(2,sing,it).
nsubj(2,lighten,it).
cc(2,it,and).
conj:and(2,it,they).
nsubj(2,sing,they).
aux(2,sing,would).
ccomp(2,spare,sing).
case(2,him,to).
nmod:to(2,sing,him).
cc(2,sing,and).
ccomp(2,spare,lighten).
conj:and(2,sing,lighten).
nmod:poss(2,labors,his).
dobj(2,lighten,labors).
lighten(2,they,his_labors).
sing_to(2,it,him).
sing_to(2,they,him).
root(3,ROOT,paid).
nsubj(3,paid,he).
nsubj(3,gave,he).
neg(3,attention,no).
dobj(3,paid,attention).
case(3,request,to).
nmod:poss(3,request,their).
nmod:to(3,paid,request).
cc(3,paid,but).
conj:but(3,paid,gave).
det(3,tree,the).
iobj(3,gave,tree).
det(3,second,a).
dobj(3,gave,second).
cc(3,second,and).
det(3,blow,a).
amod(3,blow,third).
dobj(3,gave,blow).
conj:and(3,second,blow).
case(3,axe,with).
nmod:poss(3,axe,his).
nmod:with(3,gave,axe).
gave(3,he,third_blow).
gave(3,he,tree).
gave(3,he,second).
gave(3,he,blow).
gave_blow_with(3,he,his_axe).
root(4,ROOT,reached).
advmod(4,reached,when).
nsubj(4,reached,he).
det(4,hollow,the).
dobj(4,reached,hollow).
case(4,tree,of).
det(4,tree,the).
nmod:of(4,hollow,tree).
nsubj(4,found,he).
acl:relcl(4,tree,found).
det(4,full,a).
amod(4,full,hive).
dobj(4,found,full).
case(4,honey,of).
nmod:of(4,full,honey).
found(4,he,full).
found(4,he,hive_full).
found(4,he,full_of_honey).
reached(4,he,hollow).
found(4,he,hive_full_of_honey).
root(5,ROOT,tasted).
aux(5,tasted,having).
det(5,honeycomb,the).
dobj(5,tasted,honeycomb).
nsubj(5,threw,he).
acl:relcl(5,honeycomb,threw).
compound:prt(5,threw,down).
nmod:poss(5,axe,his).
dobj(5,threw,axe).
cc(5,tasted,and).
conj:and(5,tasted,looking).
case(5,tree,on).
det(5,tree,the).
nmod:on(5,looking,tree).
mark(5,took,as).
nsubj(5,took,sacred).
advcl:as(5,looking,took).
amod(5,care,great).
dobj(5,took,care).
case(5,it,of).
nmod:of(5,care,it).
great_care_of(5,sacred,it).
took(5,sacred,care).
took(5,sacred,great_care_of_it).
threw_down(5,he,his_axe).
took(5,sacred,great_care).
care_of(5,sacred,it).
took(5,sacred,care_of_it).
