root(0,ROOT,came).
det(0,frog,a).
nsubj(0,came,frog).
nsubj(0,proclaimed,frog).
advmod(0,came,once).
case(0,time,upon).
det(0,time,a).
nmod:upon(0,once,time).
advmod(0,came,forth).
case(0,home,from).
nmod:poss(0,home,his).
nmod:from(0,forth,home).
case(0,marsh,in).
det(0,marsh,the).
nmod:in(0,came,marsh).
cc(0,came,and).
conj:and(0,came,proclaimed).
case(0,beasts,to).
det:predet(0,beasts,all).
det(0,beasts,the).
nmod:to(0,proclaimed,beasts).
mark(0,physician,that).
nsubj(0,physician,he).
cop(0,physician,was).
det(0,physician,a).
amod(0,physician,learned).
ccomp(0,proclaimed,physician).
amod(0,physician,skilled).
case(0,use,in).
det(0,use,the).
nmod:in(0,skilled,use).
case(0,drugs,of).
nmod:of(0,use,drugs).
cc(0,skilled,and).
amod(0,physician,able).
conj:and(0,skilled,able).
mark(0,heal,to).
xcomp(0,able,heal).
det(0,diseases,all).
dobj(0,heal,diseases).
proclaimed_to(0,frog,beasts).
was(0,he,learned).
was(0,he,physician_skilled_in_use_of_drugs).
was(0,he,physician).
was(0,he,physician_skilled_in_use).
was(0,he,learned_physician_skilled_in_use).
was(0,he,learned_physician_skilled_in_use_of_drugs).
was(0,he,physician_skilled).
was(0,he,learned_physician_skilled).
was(0,he,skilled).
was(0,he,learned_physician).
root(1,ROOT,asked).
det(1,fox,a).
nsubj(1,asked,fox).
dobj(1,asked,him).
asked(1,fox,him).
root(2,ROOT,pretend).
advmod(2,pretend,how).
aux(2,pretend,can).
nsubj(2,pretend,you).
nsubj:xsubj(2,prescribe,you).
mark(2,prescribe,to).
xcomp(2,pretend,prescribe).
case(2,others,for).
nmod:for(2,prescribe,others).
advmod(2,unable,when).
nsubj(2,unable,you).
nsubj:xsubj(2,heal,you).
cop(2,unable,are).
advcl(2,prescribe,unable).
mark(2,heal,to).
xcomp(2,unable,heal).
nmod:poss(2,gait,your).
amod(2,gait,own).
amod(2,gait,lame).
dobj(2,heal,gait).
cc(2,gait,and).
amod(2,skin,wrinkled).
dobj(2,heal,skin).
conj:and(2,gait,skin).
heal(2,you,your_gait).
prescribe_for(2,you,others).
heal(2,you,your_own_lame_gait).
heal(2,you,skin).
can_pretend(2,you,prescribe_for_others).
are(2,you,unable).
heal(2,you,your_own_gait).
heal(2,you,your_lame_gait).
can_pretend(2,you,prescribe).
are(2,you,when_unable).
heal(2,you,wrinkled_skin).
