root(0,ROOT,asks).
det(0,scorpion,a).
nsubj(0,asks,scorpion).
cc(0,scorpion,and).
det(0,frog,a).
conj:and(0,scorpion,frog).
nsubj(0,asks,frog).
dep(0,frog,meet).
case(0,bank,on).
det(0,bank,the).
nmod:on(0,meet,bank).
case(0,stream,of).
det(0,stream,a).
nmod:of(0,bank,stream).
cc(0,stream,and).
det(0,scorpion,the).
nmod:of(0,bank,scorpion).
conj:and(0,stream,scorpion).
det(0,frog,the).
dobj(0,asks,frog).
mark(0,carry,to).
acl:to(0,frog,carry).
dobj(0,carry,him).
case(0,back,across).
case(0,back,on).
nmod:poss(0,back,its).
nmod:on(0,carry,back).
root(1,ROOT,asks).
det(1,frog,the).
nsubj(1,asks,frog).
root(2,ROOT,know).
advmod(2,know,how).
aux(2,know,do).
nsubj(2,know,i).
nsubj(2,sting,you).
aux(2,sting,wo).
neg(2,sting,n't).
ccomp(2,know,sting).
dobj(2,sting,me).
root(3,ROOT,says).
det(3,scorpion,the).
nsubj(3,says,scorpion).
root(4,ROOT,die).
mark(4,die,because).
mark(4,do,if).
nsubj(4,do,i).
csubj(4,die,do).
dobj(4,do,i).
aux(4,die,will).
advmod(4,die,too).
do(4,i,i).
root(5,ROOT,stings).
det(5,frog,the).
nsubj(5,satisfied,frog).
cop(5,satisfied,is).
dep(5,stings,satisfied).
cc(5,satisfied,and).
nsubj(5,set,they).
conj:and(5,satisfied,set).
dep(5,stings,set).
compound:prt(5,set,out).
cc(5,midstream,but).
case(5,midstream,in).
nmod:in(5,set,midstream).
det(5,scorpion,the).
dep(5,midstream,scorpion).
det(5,frog,the).
nsubj(5,stings,frog).
set_out_in(5,they,midstream).
root(6,ROOT,feels).
det(6,frog,the).
nsubj(6,feels,frog).
nsubj(6,starts,frog).
nsubj:xsubj(6,sink,frog).
det(6,onset,the).
dobj(6,feels,onset).
case(6,paralysis,of).
nmod:of(6,onset,paralysis).
cc(6,feels,and).
conj:and(6,feels,starts).
mark(6,sink,to).
xcomp(6,starts,sink).
xcomp(6,sink,knowing).
nsubj(6,drown,they).
nsubj(6,has,they).
dep(6,drown,both).
aux(6,drown,will).
ccomp(6,knowing,drown).
cc(6,drown,but).
ccomp(6,knowing,has).
conj:but(6,drown,has).
advmod(6,enough,just).
amod(6,time,enough).
dobj(6,has,time).
mark(6,gasp,to).
acl:to(6,time,gasp).
feels(6,frog,onset).
starts(6,frog,sink).
feels(6,frog,onset_of_paralysis).
root(7,ROOT,why).
root(8,ROOT,replies).
det(8,scorpion,the).
nsubj(8,replies,scorpion).
root(9,ROOT,its).
nmod:poss(9,nature,my).
dep(9,its,nature).
