root(0,ROOT,befriended).
det(0,scorpion,a).
nsubj(0,befriended,scorpion).
det(0,ladybug,a).
dobj(0,befriended,ladybug).
nsubj(0,became,ladybug).
ref(0,ladybug,who).
acl:relcl(0,ladybug,became).
det(0,companion,a).
amod(0,companion,loyal).
xcomp(0,became,companion).
case(0,him,to).
nmod:to(0,became,him).
root(1,ROOT,came).
det(1,time,a).
nsubj(1,came,time).
advmod(1,struggled,when).
nsubj(1,struggled,she).
nsubj:xsubj(1,cross,she).
advcl(1,came,struggled).
mark(1,cross,to).
xcomp(1,struggled,cross).
det(1,river,a).
amod(1,river,challenging).
cc(1,challenging,and).
conj:and(1,challenging,dangerous).
amod(1,river,dangerous).
dobj(1,cross,river).
cc(1,struggled,and).
mark(1,offered,so).
det(1,scorpion,the).
nsubj(1,offered,scorpion).
nsubj:xsubj(1,take,scorpion).
advcl(1,came,offered).
conj:and(1,struggled,offered).
mark(1,take,to).
xcomp(1,offered,take).
dobj(1,take,her).
case(1,side,to).
det(1,side,the).
amod(1,side,other).
nmod:to(1,take,side).
case(1,back,on).
nmod:poss(1,back,his).
nmod:on(1,side,back).
cross(1,she,river).
take(1,scorpion,her).
cross(1,she,challenging_river).
root(2,ROOT,come).
nsubj(2,come,he).
nsubj:xsubj(2,care,he).
nsubj(2,promised,he).
aux(2,come,had).
mark(2,care,to).
xcomp(2,come,care).
case(2,her,for).
nmod:for(2,care,her).
cc(2,come,and).
conj:and(2,come,promised).
nsubj(2,harm,he).
aux(2,harm,would).
neg(2,harm,never).
ccomp(2,promised,harm).
dobj(2,harm,her).
had_come(2,he,care).
had_come(2,he,care_for_her).
care_for(2,he,her).
root(3,ROOT,but).
advmod(3,river,safely).
case(3,river,across).
det(3,river,the).
nmod:across(3,but,river).
nsubj(3,allowed,he).
acl:relcl(3,river,allowed).
nmod:poss(3,tail,his).
dobj(3,allowed,tail).
mark(3,dip,to).
acl:to(3,tail,dip).
case(3,her,upon).
nmod:upon(3,dip,her).
case(3,sting,with).
nmod:poss(3,sting,its).
amod(3,sting,venomous).
nmod:with(3,dip,sting).
allowed(3,he,his_tail_dip_with_its_sting).
allowed(3,he,his_tail_dip_upon_her_with_its_venomous_sting).
allowed(3,he,his_tail_dip).
allowed(3,he,his_tail_dip_upon_her).
allowed(3,he,his_tail_dip_upon_her_with_its_sting).
allowed(3,he,his_tail_dip_with_its_venomous_sting).
root(4,ROOT,lay).
mark(4,lay,as).
nsubj(4,lay,she).
case(4,pain,in).
amod(4,pain,greatest).
nmod:in(4,said,pain).
nsubj(4,said,she).
ccomp(4,lay,said).
said_in(4,she,greatest_pain).
said_in(4,she,pain).
root(5,ROOT,promised).
cc(5,promised,but).
nsubj(5,promised,you).
root(6,ROOT,why).
root(7,ROOT,shrugged).
nsubj(7,shrugged,he).
nsubj(7,said,he).
cc(7,shrugged,and).
conj:and(7,shrugged,said).
advmod(7,said,sadly).
root(8,ROOT,nature).
mark(8,nature,because).
nsubj(8,nature,it).
cop(8,nature,is).
nmod:poss(8,nature,my).
is(8,it,my_nature).
root(9,ROOT,intent).
case(9,wishes,regardless).
mwe(9,regardless,of).
nmod:poss(9,wishes,our).
nmod:regardless_of(9,or,wishes).
dep(9,intent,or).
advmod(9,or,even).
nmod:poss(9,intent,our).
mark(9,faithful,intent).
nsubj(9,nature,it).
cop(9,nature,is).
case(9,nature,to).
nmod:poss(9,nature,our).
acl:relcl(9,intent,nature).
advmod(9,faithful,alone).
ref(9,intent,that).
nsubj(9,faithful,we).
aux(9,faithful,will).
cop(9,faithful,be).
dep(9,nature,faithful).
will(9,we,will_faithful).
is_to(9,it,our_nature).
will(9,we,alone_will_faithful).
