root(0,ROOT,caught).
det(0,fowler,a).
nsubj(0,caught,fowler).
det(0,partridge,a).
dobj(0,caught,partridge).
cc(0,caught,and).
aux(0,about,was).
conj:and(0,caught,about).
mark(0,kill,to).
xcomp(0,about,kill).
dobj(0,kill,it).
caught(0,fowler,partridge).
root(1,ROOT,begged).
det(1,partridge,the).
nsubj(1,begged,partridge).
advmod(1,begged,earnestly).
dobj(1,begged,him).
nsubj:xsubj(1,spare,him).
mark(1,spare,to).
xcomp(1,begged,spare).
nmod:poss(1,life,his).
dobj(1,spare,life).
acl(1,life,saying).
begged(1,partridge,him).
spare(1,him,his_life_saying).
earnestly_begged(1,partridge,him).
spare(1,him,his_life).
root(2,ROOT,permit).
compound(2,master,pray).
nsubj(2,permit,master).
dobj(2,permit,me).
nsubj:xsubj(2,live,me).
mark(2,live,to).
xcomp(2,permit,live).
cc(2,permit,and).
nsubj(2,entice,i).
aux(2,entice,will).
conj:and(2,permit,entice).
amod(2,partridges,many).
dobj(2,entice,partridges).
case(2,you,to).
nmod:to(2,entice,you).
case(2,recompense,in).
nmod:in(2,entice,recompense).
case(2,mercy,for).
nmod:poss(2,mercy,your).
nmod:for(2,recompense,mercy).
case(2,me,to).
nmod:to(2,entice,me).
permit(2,pray_master,me).
will_entice_partridges_in(2,i,recompense).
will_entice(2,i,partridges).
will_entice_partridges_in(2,i,recompense_for_your_mercy).
will_entice_partridges_to(2,i,me).
will_entice(2,i,many_partridges).
will_entice_partridges_to(2,i,you).
root(3,ROOT,replied).
det(3,fowler,the).
nsubj(3,replied,fowler).
root(4,ROOT,take).
nsubj(4,take,i).
aux(4,take,shall).
advmod(4,take,now).
case(4,scruple,with).
amod(4,scruple,less).
nmod:with(4,now,scruple).
nmod:poss(4,life,your).
dobj(4,take,life).
mark(4,willing,because).
nsubj(4,willing,you).
nsubj:xsubj(4,save,you).
cop(4,willing,are).
advcl:because(4,take,willing).
mark(4,save,to).
xcomp(4,willing,save).
dobj(4,save,it).
case(4,cost,at).
det(4,cost,the).
nmod:at(4,save,cost).
mark(4,betraying,of).
acl:of(4,cost,betraying).
nmod:poss(4,friends,your).
dobj(4,betraying,friends).
cc(4,friends,and).
dobj(4,betraying,relations).
conj:and(4,friends,relations).
are(4,you,willing).
shall_take(4,i,your_life).
shall_now_take(4,i,your_life).
save(4,you,it).
