root(0,ROOT,brought).
det(0,shepherd-boy,a).
nsubj(0,watched,shepherd-boy).
nsubj(0,brought,shepherd-boy).
ref(0,shepherd-boy,who).
acl:relcl(0,shepherd-boy,watched).
det(0,flock,a).
dobj(0,watched,flock).
case(0,sheep,of).
nmod:of(0,flock,sheep).
case(0,village,near).
det(0,village,a).
nmod:near(0,watched,village).
compound:prt(0,brought,out).
det(0,villagers,the).
dobj(0,brought,villagers).
nummod(0,times,three).
cc(0,three,or).
conj:or(0,three,four).
nummod(0,times,four).
nmod:tmod(0,villagers,times).
mark(0,crying,by).
advcl:by(0,brought,crying).
compound:prt(0,crying,out).
root(1,ROOT,wolf).
root(2,ROOT,wolf).
root(3,ROOT,came).
cc(3,came,and).
advmod(3,came,when).
nmod:poss(3,neighbors,his).
nsubj(3,came,neighbors).
nsubj:xsubj(3,help,neighbors).
mark(3,help,to).
xcomp(3,came,help).
nsubj(3,laughed,him).
ccomp(3,help,laughed).
case(3,them,at).
nmod:at(3,laughed,them).
case(3,pains,for).
nmod:poss(3,pains,their).
nmod:for(3,laughed,pains).
came(3,his_neighbors,help).
laughed_for(3,him,their_pains).
laughed_at(3,him,them).
root(4,ROOT,did).
det(4,wolf,the).
nsubj(4,did,wolf).
advmod(4,did,however).
advmod(4,did,truly).
dep(4,did,come).
case(4,last,at).
nmod:at(4,come,last).
root(5,ROOT,shouted).
det(5,shepherd-boy,the).
nsubj(5,shouted,shepherd-boy).
advmod(5,shepherd-boy,now).
advmod(5,alarmed,really).
amod(5,shepherd-boy,alarmed).
case(5,agony,in).
det(5,agony,an).
nmod:in(5,shouted,agony).
case(5,terror,of).
nmod:of(5,agony,terror).
shouted_in(5,shepherd-boy_alarmed,agony_of_terror).
shouted_in(5,shepherd-boy,agony).
shouted_in(5,shepherd-boy_alarmed,agony).
shouted_in(5,shepherd-boy,agony_of_terror).
root(6,ROOT,come).
nsubj(6,come,pray).
nsubj(6,help,pray).
aux(6,come,do).
cc(6,come,and).
conj:and(6,come,help).
dobj(6,come,me).
do_come(6,pray,me).
root(7,ROOT,killing).
det(7,wolf,the).
nsubj(7,killing,wolf).
aux(7,killing,is).
det(7,sheep,the).
dobj(7,killing,sheep).
is_killing(7,wolf,sheep).
root(8,ROOT,paid).
cc(8,paid,but).
neg(8,one,no).
nsubj(8,paid,one).
nsubj(8,heed,any).
ccomp(8,paid,heed).
dep(8,cries,to).
nsubj(8,cries,his).
nsubj(8,rendered,his).
ccomp(8,heed,cries).
cc(8,cries,nor).
ccomp(8,heed,rendered).
conj:nor(8,cries,rendered).
det(8,assistance,any).
dobj(8,rendered,assistance).
root(9,ROOT,lacerated).
det(9,wolf,the).
nsubj(9,lacerated,wolf).
nsubj(9,destroyed,wolf).
acl(9,wolf,having).
neg(9,cause,no).
dobj(9,having,cause).
case(9,fear,of).
nmod:of(9,cause,fear).
case(9,leisure,at).
nmod:poss(9,leisure,his).
nmod:at(9,fear,leisure).
cc(9,lacerated,or).
conj:or(9,lacerated,destroyed).
det(9,flock,the).
amod(9,flock,whole).
dobj(9,destroyed,flock).
destroyed(9,wolf,flock).
destroyed(9,wolf,whole_flock).
