%% some travelers journeying along the seashore climbed to the summit of a tall cliff and looking over the sea saw in the distance what they thought was a large ship.
% dependencies.
root(0,root,see).
det(0,traveler,some).
nsubj(0,see,traveler).
dep(0,traveler,journey).
case(0,seashore,along).
det(0,seashore,the).
nmod:along(0,journey,seashore).
acl(0,seashore,climb).
case(0,summit,to).
det(0,summit,the).
nmod:to(0,climb,summit).
case(0,cliff,of).
det(0,cliff,a).
amod(0,cliff,tall).
nmod:of(0,summit,cliff).
cc(0,journey,and).
dep(0,traveler,look).
conj:and(0,journey,look).
case(0,sea,over).
det(0,sea,the).
nmod:over(0,look,sea).
case(0,distance,in).
det(0,distance,the).
nmod:in(0,see,distance).
dobj(0,think,what).
nsubj(0,think,they).
ccomp(0,see,think).
cop(0,ship,be).
det(0,ship,a).
amod(0,ship,large).
ccomp(0,think,ship).
% relations.
see_in(0,traveler,distance).
%% they waited in the hope of seeing it enter the harbor but as the object on which they looked was driven nearer to shore by the wind they found that it could at the most be a small boat and not a ship.
% dependencies.
root(1,root,wait).
nsubj(1,wait,they).
case(1,hope,in).
det(1,hope,the).
nmod:in(1,find,hope).
mark(1,see,of).
acl:of(1,hope,see).
nsubj(1,enter,it).
advcl(1,see,enter).
det(1,harbor,the).
dobj(1,enter,harbor).
cc(1,enter,but).
mark(1,drive,as).
det(1,object,the).
nmod:on(1,look,object).
nsubjpass(1,drive,object).
case(1,which,on).
ref(1,object,which).
nsubj(1,look,they).
acl:relcl(1,object,look).
auxpass(1,drive,be).
advcl(1,see,drive).
conj:but(1,enter,drive).
mark(1,shore,nearer).
mark(1,shore,to).
advcl:to(1,drive,shore).
case(1,wind,by).
det(1,wind,the).
nmod:by(1,shore,wind).
nsubj(1,find,they).
ccomp(1,wait,find).
mark(1,boat,that).
nsubj(1,boat,it).
aux(1,boat,could).
case(1,the,at).
advmod(1,boat,the).
advmod(1,boat,most).
cop(1,boat,be).
det(1,boat,a).
amod(1,boat,small).
ccomp(1,find,boat).
cc(1,boat,and).
neg(1,ship,not).
det(1,ship,a).
ccomp(1,find,ship).
conj:and(1,boat,ship).
% relations.
enter(1,it,harbor).
%% when however it reached the beach they discovered that it was only a large faggot of sticks and one of them said to his companions.
% dependencies.
root(2,root,reach).
advmod(2,reach,when).
advmod(2,reach,however).
nsubj(2,reach,it).
det(2,beach,the).
dobj(2,reach,beach).
mark(2,faggot,beach).
nsubj(2,discover,they).
acl:relcl(2,beach,discover).
ref(2,beach,that).
nsubj(2,faggot,it).
cop(2,faggot,be).
advmod(2,faggot,only).
det(2,faggot,a).
amod(2,faggot,large).
ccomp(2,discover,faggot).
case(2,stick,of).
nmod:of(2,faggot,stick).
cc(2,reach,and).
det:qmod(2,they,one).
mwe(2,one,of).
nsubj(2,say,they).
conj:and(2,reach,say).
case(2,companion,to).
nmod:poss(2,companion,he).
nmod:to(2,say,companion).
% relations.
be_faggot_of(2,it,stick).
be_only_faggot_of(2,it,stick).
be(2,it,only_faggot).
be(2,it,only_large_faggot).
be_only_large_faggot_of(2,it,stick).
be_large_faggot_of(2,it,stick).
be(2,it,large).
be(2,it,faggot).
be(2,it,large_faggot).
%% we have waited for no purpose for after all there is nothing to see but a load of wood.
% dependencies.
root(3,root,wait).
nsubj(3,wait,we).
aux(3,wait,have).
case(3,purpose,for).
neg(3,purpose,no).
nmod:for(3,wait,purpose).
mark(3,be,for).
case(3,all,after).
nmod:after(3,be,all).
expl(3,be,there).
advcl:for(3,wait,be).
nsubj(3,be,nothing).
mark(3,see,to).
acl:to(3,nothing,see).
case(3,load,but).
det(3,load,a).
nmod:but(3,see,load).
case(3,wood,of).
nmod:of(3,load,wood).
% relations.
see_but(3,nothing,load_wood).
see_but(3,nothing,load_of_wood).
