root(0,ROOT,saw).
det(0,watch,a).
compound(0,watch,shepherd).
amod(0,watch,keeping).
nsubj(0,saw,watch).
nsubj(0,longed,watch).
nsubj:xsubj(0,make,watch).
case(0,sheep,over).
nmod:poss(0,sheep,his).
nmod:over(0,watch,sheep).
case(0,shore,near).
det(0,shore,the).
nmod:near(0,sheep,shore).
det(0,sea,the).
nsubj(0,calm,sea).
nsubj(0,smooth,sea).
advmod(0,calm,very).
xcomp(0,saw,calm).
cc(0,calm,and).
xcomp(0,saw,smooth).
conj:and(0,calm,smooth).
cc(0,saw,and).
conj:and(0,saw,longed).
mark(0,make,to).
xcomp(0,longed,make).
det(0,voyage,a).
dobj(0,make,voyage).
case(0,view,with).
det(0,view,a).
nmod:with(0,make,view).
case(0,commerce,to).
nmod:to(0,view,commerce).
saw(0,shepherd_keeping_watch,sea_calm).
saw(0,shepherd_keeping_watch,sea_very_calm).
saw(0,shepherd_watch,sea_calm).
saw(0,shepherd_watch,sea_very_calm).
root(1,ROOT,sold).
nsubj(1,sold,he).
det:predet(1,flock,all).
nmod:poss(1,flock,his).
nsubj(1,invested,flock).
ccomp(1,sold,invested).
dobj(1,invested,it).
case(1,cargo,in).
det(1,cargo,a).
nmod:in(1,invested,cargo).
case(1,dates,of).
nmod:of(1,cargo,dates).
cc(1,dates,and).
amod(1,sail,set).
nmod:of(1,cargo,sail).
conj:and(1,dates,sail).
invested(1,flock,it).
invested(1,his_flock,it).
root(2,ROOT,came).
cc(2,came,but).
det(2,tempest,a).
advmod(2,great,very).
amod(2,tempest,great).
nsubj(2,came,tempest).
nmod(2,came,on).
cc(2,came,and).
det(2,ship,the).
nsubj(2,danger,ship).
cop(2,danger,being).
case(2,danger,in).
conj:and(2,came,danger).
mark(2,sinking,of).
acl:of(2,danger,sinking).
nsubj(2,threw,he).
nsubj(2,escaped,he).
ccomp(2,sinking,threw).
det:predet(2,merchandise,all).
nmod:poss(2,merchandise,his).
dobj(2,threw,merchandise).
advmod(2,threw,overboard).
cc(2,threw,and).
advmod(2,escaped,barely).
ccomp(2,sinking,escaped).
conj:and(2,threw,escaped).
case(2,life,with).
nmod:poss(2,life,his).
nmod:with(2,escaped,life).
case(2,ship,in).
det(2,ship,the).
amod(2,ship,empty).
nmod:in(2,life,ship).
is_in(2,his_life,empty_ship).
being_in(2,ship,danger_sinking).
escaped_with(2,he,his_life_in_empty_ship).
threw_overboard(2,he,merchandise).
escaped_with(2,he,his_life_in_ship).
escaped_with(2,he,his_life).
threw_overboard(2,he,his_merchandise).
threw(2,he,merchandise).
threw(2,he,his_merchandise).
barely_escaped_with(2,he,his_life).
barely_escaped_with(2,he,his_life_in_empty_ship).
barely_escaped_with(2,he,his_life_in_ship).
root(3,ROOT,long).
dep(3,long,not).
advmod(3,when,afterwards).
advmod(3,interrupted,when).
nsubj(3,interrupted,someone).
nsubj(3,said,someone).
dep(3,someone,passed).
nmod(3,passed,by).
cc(3,passed,and).
dep(3,someone,observed).
conj:and(3,passed,observed).
det(3,calm,the).
amod(3,calm,unruffled).
dobj(3,observed,calm).
case(3,sea,of).
det(3,sea,the).
nmod:of(3,calm,sea).
dobj(3,passed,he).
dep(3,long,interrupted).
dobj(3,interrupted,him).
cc(3,interrupted,and).
dep(3,long,said).
conj:and(3,interrupted,said).
observed(3,he,calm).
observed(3,he,unruffled_calm_of_sea).
observed(3,he,unruffled_calm).
observed(3,he,calm_of_sea).
root(4,ROOT,want).
nsubj(4,want,it).
nsubj(4,looks,it).
cop(4,want,is).
advmod(4,want,again).
mark(4,want,in).
case(4,dates,of).
nmod:of(4,want,dates).
cc(4,want,and).
advmod(4,looks,therefore).
conj:and(4,want,looks).
xcomp(4,looks,quiet).
is(4,it,want).
is_want_of(4,it,dates).
looks(4,it,quiet).
is_again_want_of(4,it,dates).
is(4,it,again_want).
therefore_looks(4,it,quiet).
