root(0,ROOT,swooped).
det(0,eagle,an).
nsubj(0,swooped,eagle).
nsubj(0,seized,eagle).
compound:prt(0,swooped,down).
case(0,serpent,upon).
det(0,serpent,a).
nmod:upon(0,swooped,serpent).
cc(0,swooped,and).
conj:and(0,swooped,seized).
dobj(0,seized,it).
case(0,talons,in).
nmod:poss(0,talons,his).
nmod:in(0,seized,talons).
case(0,intention,with).
det(0,intention,the).
nmod:with(0,seized,intention).
mark(0,carrying,of).
acl:of(0,intention,carrying).
dobj(0,carrying,it).
compound:prt(0,carrying,off).
cc(0,carrying,and).
acl:of(0,intention,devouring).
conj:and(0,carrying,devouring).
dobj(0,devouring,it).
devouring(0,it,it).
seized(0,eagle,it).
swooped_down_upon(0,eagle,serpent).
root(1,ROOT,quick).
cc(1,quick,but).
det(1,serpent,the).
nsubj(1,quick,serpent).
nsubj(1,had,serpent).
cop(1,quick,was).
advmod(1,quick,too).
case(1,him,for).
nmod:for(1,quick,him).
cc(1,quick,and).
conj:and(1,quick,had).
nmod:poss(1,coils,its).
dobj(1,had,coils).
acl:relcl(1,coils,round).
dobj(1,round,him).
case(1,moment,in).
det(1,moment,a).
nmod:in(1,round,moment).
was_too_quick_for(1,serpent,him).
was(1,serpent,too_quick).
was(1,serpent,quick).
was_quick_for(1,serpent,him).
root(2,ROOT,then).
cc(2,then,and).
expl(2,ensued,there).
acl:relcl(2,then,ensued).
det(2,struggle,a).
amod(2,struggle,life-and-death).
dobj(2,ensued,struggle).
case(2,two,between).
det(2,two,the).
nmod:between(2,struggle,two).
root(3,ROOT,came).
det(3,countryman,a).
nsubj(3,witness,countryman).
nsubj(3,came,countryman).
nsubj(3,succeeded,countryman).
ref(3,countryman,who).
cop(3,witness,was).
det(3,witness,a).
acl:relcl(3,countryman,witness).
case(3,encounter,of).
det(3,encounter,the).
nmod:of(3,witness,encounter).
case(3,assistance,to).
det(3,assistance,the).
nmod:to(3,came,assistance).
case(3,eagle,of).
det(3,eagle,the).
nmod:of(3,assistance,eagle).
cc(3,came,and).
conj:and(3,came,succeeded).
mark(3,freeing,in).
advcl:in(3,succeeded,freeing).
dobj(3,freeing,him).
case(3,serpent,from).
det(3,serpent,the).
nmod:from(3,freeing,serpent).
cc(3,freeing,and).
advcl:in(3,succeeded,enabling).
conj:and(3,freeing,enabling).
dobj(3,enabling,him).
nsubj:xsubj(3,escape,him).
mark(3,escape,to).
xcomp(3,enabling,escape).
enabling(3,him,him).
root(4,ROOT,spat).
case(4,revenge,in).
nmod:in(4,spat,revenge).
det(4,serpent,the).
nsubj(4,spat,serpent).
dobj(4,spat,some).
case(4,poison,of).
nmod:poss(4,poison,his).
nmod:of(4,some,poison).
case(4,drinking-horn,into).
det(4,man,the).
nmod:poss(4,drinking-horn,man).
case(4,man,'s).
nmod:into(4,spat,drinking-horn).
spat(4,serpent,some).
into(4,man,drinking-horn).
spat(4,serpent,some_of_his_poison).
spat(4,serpent,some_his_poison).
root(5,ROOT,heated).
case(5,exertions,with).
nmod:poss(5,exertions,his).
nmod:with(5,heated,exertions).
det(5,man,the).
nsubj(5,about,man).
nsubj:xsubj(5,slake,man).
aux(5,about,was).
acl:relcl(5,exertions,about).
mark(5,slake,to).
xcomp(5,about,slake).
nmod:poss(5,thirst,his).
dobj(5,slake,thirst).
case(5,draught,with).
det(5,draught,a).
nmod:with(5,slake,draught).
case(5,horn,from).
det(5,horn,the).
nmod:from(5,draught,horn).
advmod(5,knocked,when).
det(5,eagle,the).
nsubj(5,knocked,eagle).
nsubj(5,spilled,eagle).
advcl(5,slake,knocked).
dobj(5,knocked,it).
compound:prt(5,knocked,out).
case(5,hand,of).
nmod:poss(5,hand,his).
nmod:of(5,knocked,hand).
cc(5,knocked,and).
advcl(5,slake,spilled).
conj:and(5,knocked,spilled).
nmod:poss(5,contents,its).
dobj(5,spilled,contents).
case(5,ground,upon).
det(5,ground,the).
nmod:upon(5,spilled,ground).
