root(0,ROOT,know).
nsubj(0,know,you).
aux(0,know,must).
mark(0,women,that).
advmod(0,women,sometimes).
amod(0,women,old).
dep(0,know,women).
case(0,glass,like).
det(0,glass,a).
dep(0,women,glass).
case(0,wine,of).
nmod:of(0,glass,wine).
root(1,ROOT,found).
det:qmod(1,sort,one).
mwe(1,one,of).
det(1,sort,this).
nsubj(1,found,sort).
nsubj(1,went,sort).
advmod(1,found,once).
det(1,wine-jar,a).
dobj(1,found,wine-jar).
amod(1,wine-jar,lying).
case(1,road,in).
det(1,road,the).
nmod:in(1,wine-jar,road).
cc(1,found,and).
advmod(1,went,eagerly).
conj:and(1,found,went).
compound:prt(1,went,up).
mark(1,hoping,to).
nsubj(1,hoping,it).
nsubj:xsubj(1,find,it).
advcl:to(1,went,hoping).
mark(1,find,to).
xcomp(1,hoping,find).
nsubj(1,full,it).
xcomp(1,find,full).
hoping(1,it,find).
find(1,it,it_full).
root(2,ROOT,took).
cc(2,took,but).
advmod(2,took,when).
nsubj(2,took,she).
nsubj(2,found,it).
dep(2,found,up).
nsubj(2,found,she).
xcomp(2,took,found).
mark(2,drunk,that).
det:predet(2,wine,all).
det(2,wine,the).
nsubj(2,drunk,wine).
aux(2,drunk,had).
cop(2,drunk,been).
ccomp(2,found,drunk).
dep(2,drunk,out).
case(2,it,of).
nmod:of(2,drunk,it).
took(2,she,it_found).
took(2,she,it_she_found).
been(2,wine,drunk).
took(2,she,she_found).
been_drunk_of(2,wine,it).
root(3,ROOT,still).
nsubj(3,took,she).
ccomp(3,still,took).
det(3,long,a).
nsubj(3,sniff,long).
ccomp(3,took,sniff).
case(3,mouth,at).
det(3,mouth,the).
nmod:at(3,sniff,mouth).
case(3,jar,of).
det(3,jar,the).
nmod:of(3,mouth,jar).
sniff_at(3,long,mouth).
sniff_at(3,long,mouth_of_jar).
root(4,ROOT,ah).
