root(0,ROOT,drove).
det(0,peddler,a).
nsubj(0,drove,peddler).
nmod:poss(0,ass,his).
dobj(0,drove,ass).
case(0,seashore,to).
det(0,seashore,the).
nmod:to(0,drove,seashore).
mark(0,buy,to).
advcl:to(0,drove,buy).
dobj(0,buy,salt).
drove(0,peddler,his_ass).
buy(0,peddler,salt).
root(1,ROOT,lay).
nmod:poss(1,home,his).
compound(1,home,road).
nsubj(1,lay,home).
case(1,stream,across).
det(1,stream,a).
nmod:across(1,lay,stream).
nmod:into(1,fell,stream).
case(1,which,into).
ref(1,stream,which).
nmod:poss(1,ass,his).
nsubj(1,fell,ass).
nsubj(1,rose,ass).
acl(1,ass,making).
det(1,step,a).
amod(1,step,false).
dobj(1,making,step).
acl:relcl(1,stream,fell).
case(1,accident,by).
nmod:by(1,fell,accident).
cc(1,fell,and).
acl:relcl(1,stream,rose).
conj:and(1,fell,rose).
compound:prt(1,rose,up).
advmod(1,load,again).
case(1,load,with).
nmod:poss(1,load,his).
nmod:with(1,rose,load).
advmod(1,lighter,considerably).
amod(1,load,lighter).
case(1,water,as).
det(1,water,the).
nmod:as(1,rose,water).
acl(1,water,melted).
det(1,sack,the).
dobj(1,melted,sack).
rose_up_as(1,his_ass,water).
rose_up_with(1,his_ass,his_load).
rose_up_with(1,his_ass,his_load_lighter).
fell_by(1,his_ass,accident).
rose_up_with(1,his_ass,again_his_load).
rose_up_with(1,his_ass,again_his_load_lighter).
rose_up_with(1,his_ass,his_load_considerably_lighter).
rose_up_with(1,his_ass,again_his_load_considerably_lighter).
root(2,ROOT,retraced).
det(2,peddler,the).
nsubj(2,retraced,peddler).
nsubj(2,refilled,peddler).
nmod:poss(2,steps,his).
dobj(2,retraced,steps).
cc(2,retraced,and).
conj:and(2,retraced,refilled).
nmod:poss(2,panniers,his).
dobj(2,refilled,panniers).
case(2,quantity,with).
det(2,quantity,a).
amod(2,quantity,larger).
nmod:with(2,refilled,quantity).
case(2,salt,of).
nmod:of(2,quantity,salt).
case(2,before,than).
dep(2,refilled,before).
retraced(2,peddler,his_steps).
refilled(2,peddler,his_panniers).
root(3,ROOT,came).
advmod(3,came,when).
nsubj(3,came,he).
advmod(3,came,again).
case(3,stream,to).
det(3,stream,the).
nmod:to(3,came,stream).
det(3,ass,the).
nsubj(3,fell,ass).
acl:relcl(3,stream,fell).
compound:prt(3,fell,down).
case(3,purpose,on).
nmod:on(3,fell,purpose).
case(3,spot,in).
det(3,spot,the).
amod(3,spot,same).
nmod:in(3,fell,spot).
cc(3,fell,and).
csubj(3,diminished,regaining).
nmod:poss(3,feet,his).
dobj(3,regaining,feet).
case(3,weight,with).
det(3,weight,the).
nmod:with(3,regaining,weight).
case(3,load,of).
nmod:poss(3,load,his).
nmod:of(3,weight,load).
advmod(3,diminished,much).
acl:relcl(3,stream,diminished).
conj:and(3,fell,diminished).
dep(3,diminished,brayed).
advmod(3,brayed,triumphantly).
mark(3,obtained,as).
mwe(3,as,if).
nsubj(3,obtained,he).
aux(3,obtained,had).
advcl:as_if(3,brayed,obtained).
dobj(3,desired,what).
nsubj(3,desired,he).
ccomp(3,obtained,desired).
fell_down_in(3,ass,spot).
fell_down_on(3,ass,purpose).
fell_down_in(3,ass,same_spot).
root(4,ROOT,saw).
det(4,peddler,the).
nsubj(4,saw,peddler).
nsubj(4,drove,peddler).
case(4,trick,through).
nmod:poss(4,trick,his).
nmod:through(4,saw,trick).
cc(4,saw,and).
conj:and(4,saw,drove).
dobj(4,drove,him).
case(4,time,for).
det(4,time,the).
amod(4,time,third).
nmod:for(4,drove,time).
case(4,coast,to).
det(4,coast,the).
nmod:to(4,time,coast).
advmod(4,bought,where).
nsubj(4,bought,he).
advcl(4,drove,bought).
det(4,cargo,a).
dobj(4,bought,cargo).
case(4,sponges,of).
nmod:of(4,cargo,sponges).
case(4,salt,instead).
mwe(4,instead,of).
nmod:instead_of(4,sponges,salt).
cargo_of(4,he,sponges).
saw_through(4,peddler,his_trick).
drove(4,peddler,him).
bought(4,he,cargo).
bought(4,he,cargo_of_sponges).
root(5,ROOT,fell).
det(5,ass,the).
nsubj(5,fell,ass).
advmod(5,playing,again).
acl(5,ass,playing).
det(5,fool,the).
dobj(5,playing,fool).
compound:prt(5,fell,down).
case(5,purpose,on).
nmod:on(5,fell,purpose).
advmod(5,reached,when).
nsubj(5,reached,he).
advcl(5,fell,reached).
det(5,stream,the).
dobj(5,reached,stream).
cc(5,became,but).
det(5,sponges,the).
nsubj(5,became,sponges).
dep(5,reached,became).
xcomp(5,became,swollen).
case(5,water,with).
nmod:with(5,became,water).
advmod(5,increasing,greatly).
acl(5,water,increasing).
nmod:poss(5,load,his).
dobj(5,increasing,load).
playing(5,ass,fool).
fell_down_on(5,ass,purpose).
again_playing(5,ass,fool).
reached(5,he,stream).
root(6,ROOT,trick).
cc(6,trick,and).
advmod(6,trick,thus).
nmod:poss(6,trick,his).
acl:relcl(6,trick,recoiled).
case(6,him,on).
nmod:on(6,recoiled,him).
mark(6,carried,for).
nsubj(6,carried,he).
advmod(6,carried,now).
advcl:for(6,recoiled,carried).
case(6,burden,on).
nmod:poss(6,burden,his).
advmod(6,a,back).
amod(6,burden,a).
amod(6,burden,double).
nmod:on(6,carried,burden).
now_carried_on(6,he,his_back_a_double_burden).
carried_on(6,he,his_double_burden).
now_carried_on(6,he,his_a_burden).
now_carried_on(6,he,his_burden).
carried_on(6,he,his_a_burden).
carried_on(6,he,his_burden).
now_carried_on(6,he,his_double_burden).
carried_on(6,he,his_back_a_double_burden).
carried_on(6,he,his_a_double_burden).
now_carried_on(6,he,his_back_a_burden).
now_carried_on(6,he,his_a_double_burden).
carried_on(6,he,his_back_a_burden).
