root(0,ROOT,saw).
det(0,shepherd,a).
nsubj(0,saw,shepherd).
acl(0,shepherd,driving).
nmod:poss(0,sheep,his).
dobj(0,driving,sheep).
case(0,wood,to).
det(0,wood,a).
nmod:to(0,driving,wood).
det(0,oak,an).
dobj(0,saw,oak).
case(0,size,of).
amod(0,size,unusual).
nmod:of(0,oak,size).
amod(0,oak,full).
case(0,acorns,of).
nmod:of(0,full,acorns).
cc(0,full,and).
amod(0,oak,spreading).
conj:and(0,full,spreading).
nmod:poss(0,cloak,his).
dobj(0,spreading,cloak).
case(0,branches,under).
det(0,branches,the).
nmod:under(0,spreading,branches).
nsubj(0,climbed,he).
nsubj(0,shook,he).
dep(0,spreading,climbed).
compound:prt(0,climbed,up).
case(0,tree,into).
det(0,tree,the).
nmod:into(0,climbed,tree).
cc(0,climbed,and).
dep(0,spreading,shook).
conj:and(0,climbed,shook).
dobj(0,shook,them).
compound:prt(0,shook,down).
saw(0,shepherd,oak_of_size_full).
saw(0,shepherd,oak_of_size_full_of_acorns).
saw(0,shepherd,oak_of_unusual_size).
saw(0,shepherd,oak_full_of_acorns).
saw(0,shepherd,oak).
driving_his_sheep_to(0,shepherd,wood).
saw(0,shepherd,oak_full).
saw(0,shepherd,oak_of_unusual_size_full).
saw(0,shepherd,oak_of_unusual_size_full_of_acorns).
driving(0,shepherd,his_sheep).
saw(0,shepherd,oak_of_size).
root(1,ROOT,sheep).
det(1,sheep,the).
dep(1,sheep,eating).
det(1,acorns,the).
dobj(1,eating,acorns).
advmod(1,frayed,inadvertently).
dep(1,acorns,frayed).
cc(1,frayed,and).
dep(1,acorns,tore).
conj:and(1,frayed,tore).
det(1,cloak,the).
dobj(1,tore,cloak).
root(2,ROOT,came).
advmod(2,came,when).
det(2,shepherd,the).
nsubj(2,came,shepherd).
nsubj(2,saw,shepherd).
advmod(2,came,down).
cc(2,came,and).
conj:and(2,came,saw).
nsubjpass(2,done,what).
auxpass(2,done,was).
ccomp(2,saw,done).
nsubj(2,said,he).
ccomp(2,done,said).
root(3,ROOT,o).
dep(3,o,you).
advmod(3,ungrateful,most).
amod(3,creatures,ungrateful).
dep(3,you,creatures).
root(4,ROOT,provide).
nsubj(4,provide,you).
dobj(4,provide,wool).
mark(4,make,to).
advcl:to(4,provide,make).
dobj(4,make,garments).
case(4,men,for).
det(4,men,all).
amod(4,men,other).
nmod:for(4,make,men).
cc(4,destroy,but).
nsubj(4,destroy,you).
dep(4,make,destroy).
det(4,clothes,the).
dobj(4,destroy,clothes).
nsubj(4,feeds,clothes).
case(4,him,of).
nmod:of(4,clothes,him).
ref(4,clothes,who).
acl:relcl(4,clothes,feeds).
dobj(4,feeds,you).
provide(4,you,wool).
make_garments_for(4,you,other_men).
