root(0,ROOT,placed).
det(0,peacock,a).
nsubj(0,placed,peacock).
advmod(0,placed,once).
det(0,petition,a).
dobj(0,placed,petition).
case(0,juno,before).
nmod:before(0,placed,juno).
acl(0,juno,desiring).
mark(0,have,to).
xcomp(0,desiring,have).
det(0,voice,the).
dobj(0,have,voice).
case(0,nightingale,of).
det(0,nightingale,a).
nmod:of(0,voice,nightingale).
case(0,addition,in).
nmod:in(0,nightingale,addition).
case(0,attractions,to).
nmod:poss(0,attractions,his).
amod(0,attractions,other).
nmod:to(0,have,attractions).
is_in(0,nightingale,addition).
once_placed_petition_before(0,peacock,juno_desiring).
placed_petition_before(0,peacock,juno_desiring).
placed(0,peacock,petition).
once_placed_petition_before(0,peacock,juno).
placed_petition_before(0,peacock,juno).
once_placed(0,peacock,petition).
root(1,ROOT,refused).
cc(1,refused,but).
nsubj(1,refused,juno).
nmod:poss(1,request,his).
dobj(1,refused,request).
refused(1,juno,his_request).
root(2,ROOT,persisted).
advmod(2,persisted,when).
nsubj(2,persisted,he).
nsubj(2,pointed,he).
cc(2,persisted,and).
conj:and(2,persisted,pointed).
compound:prt(2,pointed,out).
mark(2,bird,that).
nsubj(2,bird,he).
cop(2,bird,was).
nmod:poss(2,bird,her).
amod(2,bird,favourite).
ccomp(2,persisted,bird).
nsubj(2,said,she).
acl:relcl(2,bird,said).
root(3,ROOT,content).
cop(3,content,be).
case(3,lot,with).
nmod:poss(3,lot,your).
nmod:with(3,content,lot).
root(4,ROOT,everything).
nsubj(4,everything,one).
aux(4,everything,can).
neg(4,everything,not).
cop(4,everything,be).
advmod(4,everything,first).
case(4,everything,in).
