root(0,ROOT,sought).
det(0,oxen,the).
nsubj(0,sought,oxen).
nsubj:xsubj(0,destroy,oxen).
advmod(0,sought,once).
case(0,time,upon).
det(0,time,a).
nmod:upon(0,once,time).
mark(0,destroy,to).
xcomp(0,sought,destroy).
det(0,butchers,the).
dobj(0,destroy,butchers).
nsubj(0,practiced,butchers).
ref(0,butchers,who).
acl:relcl(0,butchers,practiced).
det(0,trade,a).
nsubj(0,destructive,trade).
xcomp(0,practiced,destructive).
case(0,race,to).
nmod:poss(0,race,their).
nmod:to(0,destructive,race).
destructive_to(0,trade,their_race).
root(1,ROOT,assembled).
nsubj(1,assembled,they).
nsubj:xsubj(1,carry,they).
nsubj(1,sharpened,they).
case(1,day,on).
det(1,day,a).
amod(1,day,certain).
nmod:on(1,assembled,day).
mark(1,carry,to).
xcomp(1,assembled,carry).
compound:prt(1,carry,out).
nmod:poss(1,purpose,their).
dobj(1,carry,purpose).
cc(1,assembled,and).
conj:and(1,assembled,sharpened).
nmod:poss(1,horns,their).
dobj(1,sharpened,horns).
case(1,contest,for).
det(1,contest,the).
nmod:for(1,sharpened,contest).
assembled_on(1,they,day).
sharpened(1,they,their_horns).
carry_out(1,they,their_purpose).
assembled_on(1,they,certain_day).
root(2,ROOT,them).
cc(2,one,but).
det:qmod(2,them,one).
mwe(2,one,of).
nsubj(2,old,them).
ref(2,them,who).
cop(2,old,was).
advmod(2,old,exceedingly).
acl:relcl(2,them,old).
punct(2,had,-LRB-).
mark(2,had,for).
amod(2,field,many).
det(2,field,a).
nsubj(2,had,field).
dep(2,old,had).
nsubj(2,plowed,he).
ccomp(2,had,plowed).
punct(2,had,-RRB-).
advmod(2,spoke,thus).
ccomp(2,old,spoke).
root(3,ROOT,butchers).
det(3,butchers,these).
nsubj(3,slaughter,it).
cop(3,slaughter,is).
amod(3,slaughter,true).
acl:relcl(3,butchers,slaughter).
nsubj(3,do,us).
nsubj(3,do,us).
cc(3,us,but).
conj:but(3,us,they).
nsubj(3,do,they).
acl:relcl(3,slaughter,do).
acl:relcl(3,slaughter,do).
conj:and(3,do,do).
advmod(3,do,so).
case(3,hands,with).
amod(3,hands,skillful).
nmod:with(3,do,hands).
cc(3,do,and).
case(3,pain,with).
neg(3,pain,no).
amod(3,pain,unnecessary).
nmod:with(3,do,pain).
root(4,ROOT,get).
mark(4,get,if).
nsubj(4,get,we).
amod(4,men,rid).
case(4,them,of).
nmod:of(4,rid,them).
nsubj(4,fall,we).
aux(4,fall,shall).
acl:relcl(4,them,fall).
case(4,hands,into).
det(4,hands,the).
dep(4,fall,hands).
case(4,operators,of).
amod(4,operators,unskillful).
nmod:of(4,hands,operators).
cc(4,hands,and).
dep(4,fall,thus).
conj:and(4,hands,thus).
dep(4,hands,suffer).
det(4,death,a).
amod(4,death,double).
dobj(4,suffer,death).
mark(4,assured,for).
nsubjpass(4,assured,you).
aux(4,assured,may).
auxpass(4,assured,be).
advcl:for(4,suffer,assured).
mark(4,will,that).
mark(4,perish,though).
det:predet(4,butchers,all).
det(4,butchers,the).
nsubj(4,perish,butchers).
aux(4,perish,should).
csubj(4,will,perish).
advmod(4,perish,yet).
ccomp(4,assured,will).
nsubj(4,want,men).
neg(4,want,never).
ccomp(4,get,want).
dobj(4,want,beef).
