root(0,ROOT,round).
det(0,olive-tree,the).
nsubj(0,round,olive-tree).
cc(0,olive-tree,and).
det(0,fig-tree,the).
conj:and(0,olive-tree,fig-tree).
nsubj(0,round,fig-tree).
det(0,olive-tree,the).
nsubj(0,ridiculed,olive-tree).
acl:relcl(0,fig-tree,ridiculed).
det(0,fig-tree,the).
dobj(0,ridiculed,fig-tree).
mark(0,green,because).
mark(0,green,while).
nsubj(0,green,she).
cop(0,green,was).
advcl:while(0,ridiculed,green).
det:predet(0,year,all).
det(0,year,the).
nmod:tmod(0,green,year).
det(0,fig-tree,the).
nsubj(0,changed,fig-tree).
ccomp(0,round,changed).
nmod:poss(0,leaves,its).
dobj(0,changed,leaves).
case(0,seasons,with).
det(0,seasons,the).
nmod:with(0,changed,seasons).
ridiculed_fig-tree(0,olive-tree,green_year).
was_green_at_time(0,she,year).
changed(0,fig-tree,its_leaves).
ridiculed(0,olive-tree,fig-tree).
root(1,ROOT,fell).
det(1,shower,a).
nsubj(1,fell,shower).
nsubj(1,finding,shower).
nsubj(1,broke,shower).
case(1,snow,of).
nmod:of(1,shower,snow).
case(1,them,upon).
nmod:upon(1,fell,them).
cc(1,fell,and).
conj:and(1,fell,finding).
det(1,full,the).
amod(1,full,olive).
dobj(1,finding,full).
case(1,foliage,of).
nmod:of(1,full,foliage).
nsubj(1,settled,it).
acl:relcl(1,full,settled).
case(1,branches,upon).
nmod:poss(1,branches,its).
nmod:upon(1,settled,branches).
cc(1,fell,and).
conj:and(1,fell,broke).
dobj(1,broke,them).
compound:prt(1,broke,down).
case(1,weight,with).
nmod:poss(1,weight,its).
nmod:with(1,broke,weight).
mark(1,despoiling,at).
advmod(1,despoiling,once).
acl:at(1,weight,despoiling).
dobj(1,despoiling,it).
case(1,beauty,of).
nmod:poss(1,beauty,its).
nmod:of(1,it,beauty).
cc(1,despoiling,and).
acl:at(1,weight,killing).
conj:and(1,despoiling,killing).
det(1,tree,the).
dobj(1,killing,tree).
broke_down(1,shower,them).
fell_upon(1,shower,them).
settled_upon(1,it,its_branches).
root(2,ROOT,finding).
cc(2,finding,but).
det(2,fig-tree,the).
nsubj(2,leaves,fig-tree).
acl(2,fig-tree,denuded).
nmod(2,denuded,of).
ccomp(2,finding,leaves).
det(2,snow,the).
nsubj(2,fell,snow).
nsubj(2,injure,snow).
ccomp(2,leaves,fell).
case(2,ground,through).
case(2,ground,to).
det(2,ground,the).
nmod:to(2,fell,ground).
cc(2,fell,and).
aux(2,injure,did).
neg(2,injure,not).
ccomp(2,leaves,injure).
conj:and(2,fell,injure).
dobj(2,injure,it).
case(2,all,at).
nmod:at(2,injure,all).
