root(0,ROOT,found).
det(0,peasant,a).
nsubj(0,found,peasant).
det(0,eagle,an).
nsubj(0,set,eagle).
acl(0,eagle,captured).
case(0,trap,in).
det(0,trap,a).
nmod:in(0,captured,trap).
cc(0,trap,and).
nmod:in(0,captured,much).
conj:and(0,trap,much).
xcomp(0,captured,admiring).
det(0,bird,the).
dobj(0,admiring,bird).
ccomp(0,found,set).
nsubj(0,free,him).
xcomp(0,set,free).
set(0,eagle,him_free).
captured_in(0,eagle,trap).
root(1,ROOT,prove).
det(1,eagle,the).
nsubj(1,prove,eagle).
aux(1,prove,did).
neg(1,prove,not).
xcomp(1,prove,ungrateful).
case(1,deliverer,to).
nmod:poss(1,deliverer,his).
nmod:to(1,ungrateful,deliverer).
mark(1,seeing,for).
advcl:for(1,prove,seeing).
det(1,peasant,the).
dobj(1,seeing,peasant).
acl(1,peasant,sitting).
case(1,wall,under).
det(1,wall,a).
nmod:under(1,sitting,wall).
nsubj(1,safe,wall).
ref(1,wall,which).
cop(1,safe,was).
neg(1,safe,not).
acl:relcl(1,wall,safe).
nsubj(1,flew,he).
advcl(1,safe,flew).
case(1,him,toward).
nmod:toward(1,flew,him).
cc(1,flew,and).
mark(1,snatched,with).
nmod:poss(1,talons,his).
nsubj(1,snatched,talons).
advcl(1,safe,snatched).
conj:and(1,flew,snatched).
det(1,bundle,a).
dobj(1,snatched,bundle).
case(1,head,from).
nmod:poss(1,head,his).
nmod:from(1,snatched,head).
snatched_bundle_from(1,his_talons,his_head).
snatched(1,his_talons,bundle).
flew_toward(1,he,him).
root(2,ROOT,rose).
advmod(2,rose,when).
det(2,peasant,the).
nsubj(2,rose,peasant).
case(2,pursuit,in).
nmod:in(2,rose,pursuit).
det(2,eagle,the).
dobj(2,rose,eagle).
dep(2,eagle,let).
det(2,fall,the).
compound(2,fall,bundle).
nmod:tmod(2,let,fall).
advmod(2,let,again).
rose(2,peasant,eagle).
rose_eagle_in(2,peasant,pursuit).
rose_in(2,peasant,pursuit).
root(3,ROOT,taking).
dobj(3,taking,it).
dep(3,man,up).
det(3,man,the).
nmod(3,taking,man).
acl:relcl(3,man,returned).
case(3,place,to).
det(3,place,the).
amod(3,place,same).
nmod:to(3,returned,place).
mark(3,find,to).
xcomp(3,returned,find).
mark(3,fallen,that).
det(3,wall,the).
nmod:under(3,sitting,wall).
nsubj(3,fallen,wall).
case(3,which,under).
ref(3,wall,which).
nsubj(3,sitting,he).
aux(3,sitting,had).
aux(3,sitting,been).
acl:relcl(3,wall,sitting).
aux(3,fallen,had).
ccomp(3,find,fallen).
case(3,pieces,to).
nmod:to(3,fallen,pieces).
root(4,ROOT,marveled).
cc(4,marveled,and).
nsubj(4,marveled,he).
case(4,service,at).
det(4,service,the).
nmod:at(4,marveled,service).
acl(4,service,rendered).
dobj(4,rendered,him).
case(4,eagle,by).
det(4,eagle,the).
nmod:by(4,rendered,eagle).
marveled_at(4,he,service).
