root(0,ROOT,shut).
det(0,pig,a).
amod(0,pig,young).
nsubjpass(0,shut,pig).
auxpass(0,shut,was).
compound:prt(0,shut,up).
case(0,fold-yard,in).
det(0,fold-yard,a).
nmod:in(0,shut,fold-yard).
case(0,goat,with).
det(0,goat,a).
nmod:with(0,shut,goat).
cc(0,goat,and).
det(0,sheep,a).
nmod:with(0,shut,sheep).
conj:and(0,goat,sheep).
was_shut_up_with(0,pig,goat).
was_shut_up_with(0,young_pig,goat).
was_shut_up_in(0,young_pig,fold-yard).
was_shut_up_in(0,pig,fold-yard).
root(1,ROOT,occasion).
case(1,occasion,on).
nummod(1,occasion,one).
advmod(1,laid,when).
det(1,shepherd,the).
nsubj(1,laid,shepherd).
nsubj(1,resisted,shepherd).
acl:relcl(1,occasion,laid).
dobj(1,laid,hold).
case(1,him,of).
nmod:of(1,hold,him).
nsubj(1,grunted,he).
nsubj(1,squeaked,he).
acl:relcl(1,hold,grunted).
cc(1,grunted,and).
acl:relcl(1,hold,squeaked).
conj:and(1,grunted,squeaked).
cc(1,laid,and).
acl:relcl(1,occasion,resisted).
conj:and(1,laid,resisted).
advmod(1,resisted,violently).
hold(1,shepherd,he_grunted).
root(2,ROOT,complained).
det(2,sheep,the).
nsubj(2,complained,sheep).
cc(2,sheep,and).
det(2,goat,the).
conj:and(2,sheep,goat).
nsubj(2,complained,goat).
case(2,distressing,of).
nmod:poss(2,distressing,his).
nmod:of(2,cries,distressing).
ccomp(2,complained,cries).
xcomp(2,cries,saying).
root(3,ROOT,handles).
nsubj(3,handles,he).
advmod(3,handles,often).
nsubj(3,cry,us).
cc(3,us,and).
conj:and(3,us,we).
nsubj(3,cry,we).
aux(3,cry,do).
neg(3,cry,not).
ccomp(3,handles,cry).
compound:prt(3,cry,out).
root(4,ROOT,this).
dep(4,this,to).
det(4,pig,the).
nsubj(4,replied,pig).
acl:relcl(4,this,replied).
root(5,ROOT,things).
nmod:poss(5,handling,your).
nsubj(5,things,handling).
cc(5,handling,and).
conj:and(5,handling,mine).
nsubj(5,things,mine).
cop(5,things,are).
advmod(5,different,very).
amod(5,things,different).
are(5,mine,things).
are(5,mine,very_different_things).
are(5,your_handling,things).
are(5,mine,different_things).
are(5,your_handling,very_different_things).
are(5,your_handling,different_things).
root(6,ROOT,catches).
nsubj(6,catches,he).
dobj(6,catches,you).
advmod(6,wool,only).
case(6,wool,for).
nmod:poss(6,wool,your).
nmod:for(6,catches,wool).
cc(6,wool,or).
nmod:poss(6,milk,your).
nmod:for(6,catches,milk).
conj:or(6,wool,milk).
cc(6,lays,but).
nsubj(6,lays,he).
dep(6,catches,lays).
dobj(6,lays,hold).
case(6,me,on).
nmod:on(6,hold,me).
case(6,very,for).
nmod:poss(6,very,my).
nmod:for(6,hold,very).
nmod:tmod(6,lays,life).
hold_for(6,he,my_very).
catches(6,he,you).
hold_on(6,he,me).
