root(0,ROOT,dragged).
det(0,wagon,a).
amod(0,wagon,heavy).
nsubjpass(0,dragged,wagon).
aux(0,dragged,was).
auxpass(0,dragged,being).
case(0,lane,along).
det(0,lane,a).
compound(0,lane,country).
nmod:along(0,dragged,lane).
case(0,team,by).
det(0,team,a).
nmod:agent(0,dragged,team).
case(0,oxen,of).
nmod:of(0,team,oxen).
was(0,wagon,was_dragged_by_team).
was(0,heavy_wagon,was_dragged_along_country_lane).
was(0,heavy_wagon,was_dragged_along_country_lane_by_team).
was(0,wagon,was_dragged_along_country_lane).
was(0,wagon,was_dragged_along_country_lane_by_team_of_oxen).
was(0,wagon,was_dragged_by_team_of_oxen).
was(0,heavy_wagon,was_dragged_by_team_of_oxen).
was(0,heavy_wagon,was_dragged_by_team).
was(0,wagon,was_dragged_along_country_lane_by_team).
was(0,heavy_wagon,was_dragged_along_country_lane_by_team_of_oxen).
was(0,heavy_wagon,was_dragged).
was(0,wagon,was_dragged).
root(1,ROOT,groaned).
det(1,axle-trees,the).
nsubj(1,groaned,axle-trees).
nsubj(1,creaked,axle-trees).
cc(1,groaned,and).
conj:and(1,groaned,creaked).
advmod(1,creaked,terribly).
root(2,ROOT,whereupon).
det(2,oxen,the).
nsubj(2,addressed,oxen).
acl(2,oxen,turning).
dobj(2,turning,round).
advmod(2,turning,thus).
acl:relcl(2,whereupon,addressed).
det(2,wheels,the).
dobj(2,addressed,wheels).
turning(2,oxen,round).
addressed(2,oxen,wheels).
turning_thus(2,oxen,round).
root(3,ROOT,hullo).
dep(3,hullo,there).
root(4,ROOT,make).
advmod(4,make,why).
aux(4,make,do).
nsubj(4,make,you).
advmod(4,much,so).
amod(4,noise,much).
dobj(4,make,noise).
do_make(4,you,so_much_noise).
do_make(4,you,much_noise).
do_make(4,you,noise).
root(5,ROOT,bear).
nsubj(5,bear,we).
dep(5,labor,all).
det(5,labor,the).
dobj(5,bear,labor).
cc(5,labor,and).
dobj(5,bear,we).
conj:and(5,labor,we).
dep(5,ought,not).
nsubj(5,ought,you).
nsubj:xsubj(5,cry,you).
dep(5,bear,ought).
mark(5,cry,to).
xcomp(5,ought,cry).
compound:prt(5,cry,out).
bear(5,we,labor).
bear(5,we,we).
