%% a shepherd keeping watch over his sheep near the shore saw the sea very calm and smooth and longed to make a voyage with a view to commerce.
% dependencies.
root(0,root,see).
det(0,watch,a).
compound(0,watch,shepherd).
amod(0,watch,keep).
nsubj(0,see,watch).
nsubj(0,long,watch).
nsubj:xsubj(0,make,watch).
case(0,sheep,over).
nmod:poss(0,sheep,he).
nmod:over(0,watch,sheep).
case(0,shore,near).
det(0,shore,the).
nmod:near(0,sheep,shore).
det(0,sea,the).
nsubj(0,calm,sea).
nsubj(0,smooth,sea).
advmod(0,calm,very).
xcomp(0,see,calm).
cc(0,calm,and).
xcomp(0,see,smooth).
conj:and(0,calm,smooth).
cc(0,see,and).
conj:and(0,see,long).
mark(0,make,to).
xcomp(0,long,make).
det(0,voyage,a).
dobj(0,make,voyage).
case(0,view,with).
det(0,view,a).
nmod:with(0,make,view).
case(0,commerce,to).
nmod:to(0,view,commerce).
% relations.
aos(0,see,shepherd_keep_watch,sea_calm).
aos(0,see,shepherd_keep_watch,sea_very_calm).
aos(0,see,shepherd_watch,sea_calm).
aos(0,see,shepherd_watch,sea_very_calm).
%% he sold all his flock invested it in a cargo of dates and set sail.
% dependencies.
root(1,root,sell).
nsubj(1,sell,he).
det:predet(1,flock,all).
nmod:poss(1,flock,he).
nsubj(1,invest,flock).
ccomp(1,sell,invest).
dobj(1,invest,it).
case(1,cargo,in).
det(1,cargo,a).
nmod:in(1,invest,cargo).
case(1,date,of).
nmod:of(1,cargo,date).
cc(1,date,and).
amod(1,sail,set).
nmod:of(1,cargo,sail).
conj:and(1,date,sail).
% relations.
aos(1,invest,flock,it).
aos(1,invest,he_flock,it).
%% but a very great tempest came on and the ship being in danger of sinking he threw all his merchandise overboard and barely escaped with his life in the empty ship.
% dependencies.
root(2,root,come).
cc(2,come,but).
det(2,tempest,a).
advmod(2,great,very).
amod(2,tempest,great).
nsubj(2,come,tempest).
nmod(2,come,on).
cc(2,come,and).
det(2,ship,the).
nsubj(2,danger,ship).
cop(2,danger,be).
case(2,danger,in).
conj:and(2,come,danger).
mark(2,sink,of).
acl:of(2,danger,sink).
nsubj(2,throw,he).
nsubj(2,escape,he).
ccomp(2,sink,throw).
det:predet(2,merchandise,all).
nmod:poss(2,merchandise,he).
dobj(2,throw,merchandise).
advmod(2,throw,overboard).
cc(2,throw,and).
advmod(2,escape,barely).
ccomp(2,sink,escape).
conj:and(2,throw,escape).
case(2,life,with).
nmod:poss(2,life,he).
nmod:with(2,escape,life).
case(2,ship,in).
det(2,ship,the).
amod(2,ship,empty).
nmod:in(2,life,ship).
% relations.
aos(2,is_in,he_life,empty_ship).
aos(2,be_in,ship,danger_sink).
aos(2,escape_with,he,he_life_in_empty_ship).
aos(2,throw_overboard,he,merchandise).
aos(2,escape_with,he,he_life_in_ship).
aos(2,escape_with,he,he_life).
aos(2,throw_overboard,he,he_merchandise).
aos(2,throw,he,merchandise).
aos(2,throw,he,he_merchandise).
aos(2,barely_escape_with,he,he_life).
aos(2,barely_escape_with,he,he_life_in_empty_ship).
aos(2,barely_escape_with,he,he_life_in_ship).
%% not long afterwards when someone passed by and observed the unruffled calm of the sea he interrupted him and said.
% dependencies.
root(3,root,long).
dep(3,long,not).
advmod(3,when,afterwards).
advmod(3,interrupt,when).
nsubj(3,interrupt,someone).
nsubj(3,say,someone).
dep(3,someone,pass).
nmod(3,pass,by).
cc(3,pass,and).
dep(3,someone,observe).
conj:and(3,pass,observe).
det(3,calm,the).
amod(3,calm,unruffled).
dobj(3,observe,calm).
case(3,sea,of).
det(3,sea,the).
nmod:of(3,calm,sea).
dobj(3,pass,he).
dep(3,long,interrupt).
dobj(3,interrupt,he).
cc(3,interrupt,and).
dep(3,long,say).
conj:and(3,interrupt,say).
% relations.
aos(3,observe,he,calm).
aos(3,observe,he,unruffled_calm_of_sea).
aos(3,observe,he,unruffled_calm).
aos(3,observe,he,calm_of_sea).
%% it is again in want of dates and therefore looks quiet.
% dependencies.
root(4,root,want).
nsubj(4,want,it).
nsubj(4,look,it).
cop(4,want,be).
advmod(4,want,again).
mark(4,want,in).
case(4,date,of).
nmod:of(4,want,date).
cc(4,want,and).
advmod(4,look,therefore).
conj:and(4,want,look).
xcomp(4,look,quiet).
% relations.
aos(4,be,it,want).
aos(4,be_want_of,it,date).
aos(4,look,it,quiet).
aos(4,be_again_want_of,it,date).
aos(4,be,it,again_want).
aos(4,therefore_look,it,quiet).
