root(0,ROOT,saw).
det(0,raven,a).
dep(0,saw,raven).
det(0,swan,a).
dobj(0,saw,swan).
nsubj:xsubj(0,secure,swan).
cc(0,swan,and).
dobj(0,saw,desired).
conj:and(0,swan,desired).
nsubj:xsubj(0,secure,desired).
mark(0,secure,to).
xcomp(0,saw,secure).
case(0,himself,for).
nmod:for(0,secure,himself).
det(0,plumage,the).
amod(0,plumage,same).
amod(0,plumage,beautiful).
nsubj(0,saw,plumage).
saw(0,same_beautiful_plumage,desired).
saw(0,plumage,swan).
saw(0,beautiful_plumage,swan).
saw(0,same_beautiful_plumage,swan).
saw(0,plumage,desired).
saw(0,same_plumage,swan).
saw(0,beautiful_plumage,desired).
saw(0,same_plumage,desired).
secure_for(0,desired,himself).
root(1,ROOT,supposing).
mark(1,arose,that).
det(1,swan,the).
nmod:poss(1,color,swan).
case(1,swan,'s).
amod(1,color,splendid).
amod(1,color,white).
nsubj(1,arose,color).
ccomp(1,supposing,arose).
mark(1,washing,from).
nsubj(1,washing,his).
advcl:from(1,arose,washing).
case(1,water,in).
det(1,water,the).
nmod:in(1,washing,water).
nmod:in(1,swam,water).
case(1,which,in).
ref(1,water,which).
nsubj(1,swam,he).
acl:relcl(1,water,swam).
det(1,raven,the).
nsubj(1,left,raven).
ccomp(1,swam,left).
det(1,altars,the).
dobj(1,left,altars).
case(1,neighborhood,in).
det(1,neighborhood,the).
nmod:in(1,left,neighborhood).
advmod(1,picked,where).
nsubj(1,picked,he).
nsubj(1,took,he).
advcl(1,left,picked).
compound:prt(1,picked,up).
nmod:poss(1,living,his).
dobj(1,picked,living).
cc(1,picked,and).
advcl(1,left,took).
conj:and(1,picked,took).
compound:prt(1,took,up).
dobj(1,took,residence).
case(1,lakes,in).
det(1,lakes,the).
nmod:in(1,residence,lakes).
cc(1,lakes,and).
nmod:in(1,residence,pools).
conj:and(1,lakes,pools).
is_in(1,residence,lakes).
has(1,swan,splendid_white_color).
root(2,ROOT,cleansing).
cc(2,cleansing,but).
nmod:poss(2,feathers,his).
dobj(2,cleansing,feathers).
advmod(2,often,as).
advmod(2,cleansing,often).
mark(2,would,as).
nsubj(2,would,he).
advcl:as(2,change,would).
nsubj(2,change,he).
aux(2,change,could).
neg(2,change,not).
dep(2,often,change).
nmod:poss(2,color,their).
dobj(2,change,color).
mark(2,perished,while).
mark(2,want,through).
advcl:through(2,perished,want).
case(2,food,of).
nmod:of(2,want,food).
nsubj(2,perished,he).
advcl:while(2,change,perished).
