root(0,ROOT,about).
det(0,shepherd,a).
nsubj(0,about,shepherd).
nsubj:xsubj(0,shut,shepherd).
acl(0,shepherd,penning).
nmod:poss(0,sheep,his).
dobj(0,penning,sheep).
case(0,fold,in).
det(0,fold,the).
nmod:in(0,penning,fold).
case(0,night,for).
det(0,night,the).
nmod:for(0,fold,night).
aux(0,about,was).
mark(0,shut,to).
xcomp(0,about,shut).
compound:prt(0,shut,up).
det(0,wolf,a).
dobj(0,shut,wolf).
case(0,them,with).
nmod:with(0,wolf,them).
advmod(0,said,when).
nmod:poss(0,dog,his).
nsubj(0,said,dog).
acl(0,dog,perceiving).
det(0,wolf,the).
dobj(0,perceiving,wolf).
advcl(0,shut,said).
shut_up(0,shepherd,wolf_with_them).
penning_his_sheep_in(0,shepherd,fold_night).
is_with(0,wolf,them).
penning_his_sheep_in(0,shepherd,fold).
penning(0,shepherd,his_sheep).
shut_up(0,shepherd,wolf).
root(1,ROOT,master).
advmod(1,can,how).
dep(1,master,can).
dobj(1,can,you).
dep(1,can,expect).
det(1,sheep,the).
dobj(1,expect,sheep).
mark(1,safe,to).
cop(1,safe,be).
acl:to(1,sheep,safe).
mark(1,admit,if).
nsubj(1,admit,you).
advcl:if(1,safe,admit).
det(1,wolf,a).
dobj(1,admit,wolf).
case(1,fold,into).
det(1,fold,the).
nmod:into(1,admit,fold).
