root(0,ROOT,came).
det(0,serpent,a).
nsubj(0,came,serpent).
case(0,course,in).
det(0,course,the).
nmod:in(0,serpent,course).
case(0,wanderings,of).
nmod:poss(0,wanderings,its).
nmod:of(0,course,wanderings).
case(0,shop,into).
det(0,armourer,an).
nmod:poss(0,shop,armourer).
case(0,armourer,'s).
nmod:into(0,came,shop).
is_in(0,serpent,course_of_its_wanderings).
came_into(0,serpent,armourer_s_shop).
into(0,armourer,shop).
root(1,ROOT,glided).
mark(1,glided,as).
nsubj(1,glided,he).
case(1,floor,over).
det(1,floor,the).
nmod:over(1,glided,floor).
nsubj(1,felt,he).
acl:relcl(1,floor,felt).
nmod:poss(1,skin,his).
dobj(1,felt,skin).
acl(1,skin,pricked).
case(1,file,by).
det(1,file,a).
nmod:by(1,pricked,file).
acl(1,file,lying).
advmod(1,lying,there).
felt(1,he,his_skin_pricked_by_file).
felt(1,he,his_skin_pricked_by_file_lying_there).
felt(1,he,his_skin).
felt(1,he,his_skin_pricked_by_file_lying).
felt(1,he,his_skin_pricked).
root(2,ROOT,turned).
case(2,rage,in).
det(2,rage,a).
nmod:in(2,turned,rage).
nsubj(2,turned,he).
nsubj(2,tried,he).
nsubj:xsubj(2,dart,he).
dobj(2,turned,round).
case(2,it,upon).
nmod:upon(2,turned,it).
cc(2,turned,and).
conj:and(2,turned,tried).
mark(2,dart,to).
xcomp(2,tried,dart).
nmod:poss(2,fangs,his).
dobj(2,dart,fangs).
case(2,it,into).
nmod:into(2,dart,it).
turned_in(2,he,rage).
turned_round_in(2,he,rage).
turned_upon(2,he,it).
turned(2,he,round).
turned_round_upon(2,he,it).
root(3,ROOT,do).
cc(3,do,but).
nsubj(3,do,he).
nsubj(3,had,he).
aux(3,do,could).
neg(3,harm,no).
dobj(3,do,harm).
case(3,iron,to).
amod(3,iron,heavy).
nmod:to(3,do,iron).
cc(3,do,and).
conj:and(3,do,had).
advmod(3,give,soon).
mark(3,give,to).
ccomp(3,had,give).
compound:prt(3,give,over).
nmod:poss(3,wrath,his).
dobj(3,give,wrath).
