root(0,ROOT,mocked).
det(0,peacock,a).
nsubj(0,mocked,peacock).
acl(0,peacock,spreading).
nmod:poss(0,tail,its).
amod(0,tail,gorgeous).
dobj(0,spreading,tail).
det(0,crane,a).
dobj(0,mocked,crane).
nsubj(0,passed,crane).
ref(0,crane,that).
acl:relcl(0,crane,passed).
mark(0,ridiculing,by).
advcl:by(0,passed,ridiculing).
det(0,hue,the).
amod(0,hue,ashen).
dobj(0,ridiculing,hue).
case(0,plumage,of).
nmod:poss(0,plumage,its).
nmod:of(0,hue,plumage).
cc(0,ridiculing,and).
advcl:by(0,passed,saying).
conj:and(0,ridiculing,saying).
spreading(0,peacock,its_gorgeous_tail).
spreading(0,peacock,its_tail).
root(1,ROOT,robed).
nsubjpass(1,robed,i).
auxpass(1,robed,am).
case(1,king,like).
det(1,king,a).
nmod:like(1,robed,king).
case(1,gold,in).
nmod:in(1,king,gold).
cc(1,gold,and).
nmod:in(1,king,purple).
conj:and(1,gold,purple).
cc(1,king,and).
det:predet(1,colors,all).
det(1,colors,the).
nmod:like(1,robed,colors).
conj:and(1,king,colors).
case(1,rainbow,of).
det(1,rainbow,the).
nmod:of(1,colors,rainbow).
am(1,i,robed).
is_in(1,king,gold).
root(2,ROOT,have).
mark(2,have,while).
nsubj(2,have,you).
neg(2,have,not).
det:qmod(2,color,a).
mwe(2,a,bit).
mwe(2,a,of).
dep(2,have,color).
case(2,wings,on).
nmod:poss(2,wings,your).
nmod:on(2,color,wings).
root(3,ROOT,true).
root(4,ROOT,replied).
det(4,crane,the).
nsubj(4,replied,crane).
root(5,ROOT,i).
cc(5,i,but).
dep(5,i,soar).
case(5,heights,to).
det(5,heights,the).
nmod:to(5,soar,heights).
case(5,heaven,of).
nmod:of(5,heights,heaven).
cc(5,soar,and).
dep(5,i,lift).
conj:and(5,soar,lift).
compound:prt(5,lift,up).
nmod:poss(5,voice,my).
dobj(5,lift,voice).
case(5,stars,to).
det(5,stars,the).
nmod:to(5,lift,stars).
mark(5,walk,while).
nsubj(5,walk,you).
advcl:while(5,lift,walk).
case(5,cock,below).
case(5,cock,like).
det(5,cock,a).
nmod:like(5,walk,cock).
case(5,birds,among).
det(5,birds,the).
nmod:among(5,cock,birds).
case(5,dunghill,of).
det(5,dunghill,the).
nmod:of(5,birds,dunghill).
