%% an owl in her wisdom counseled the birds that when the acorn first began to sprout to pull it all up out of the ground and not allow it to grow.
% dependencies.
root(0,root,counsel).
det(0,owl,a).
nsubj(0,counsel,owl).
case(0,wisdom,in).
nmod:poss(0,wisdom,she).
nmod:in(0,owl,wisdom).
det(0,bird,the).
dobj(0,counsel,bird).
dobj(0,sprout,that).
nsubj:xsubj(0,pull,that).
nsubj:xsubj(0,allow,that).
advmod(0,begin,when).
det(0,acorn,the).
nsubj(0,begin,acorn).
nsubj:xsubj(0,sprout,acorn).
advmod(0,begin,first).
dep(0,bird,begin).
mark(0,sprout,to).
xcomp(0,begin,sprout).
mark(0,pull,to).
xcomp(0,sprout,pull).
dobj(0,pull,it).
dep(0,up,all).
advmod(0,pull,up).
compound:prt(0,pull,out).
case(0,ground,of).
det(0,ground,the).
nmod:of(0,pull,ground).
cc(0,pull,and).
neg(0,allow,not).
xcomp(0,sprout,allow).
conj:and(0,pull,allow).
dobj(0,allow,it).
nsubj:xsubj(0,grow,it).
mark(0,grow,to).
xcomp(0,allow,grow).
% relations.
aos(0,is_in,owl,she_wisdom).
aos(0,counsel,owl,bird).
%% she said acorns would produce mistletoe from which an irremediable poison the bird- lime would be extracted and by which they would be captured.
% dependencies.
root(1,root,say).
nsubj(1,say,she).
nsubj(1,produce,acorn).
aux(1,produce,would).
ccomp(1,say,produce).
dobj(1,produce,mistletoe).
mark(1,extract,from).
dobj(1,extract,which).
det(1,poison,a).
amod(1,poison,irremediable).
nsubjpass(1,extract,poison).
det(1,bird,the).
dep(1,poison,bird).
punct(1,bird,-).
dep(1,bird,lime).
aux(1,extract,would).
auxpass(1,extract,be).
dep(1,produce,extract).
cc(1,extract,and).
mark(1,capture,by).
dobj(1,capture,which).
nsubjpass(1,capture,they).
aux(1,capture,would).
auxpass(1,capture,be).
dep(1,produce,capture).
conj:and(1,extract,capture).
% relations.
%% the owl next advised them to pluck up the seed of the flax which men had sown as it was a plant which boded no good to them.
% dependencies.
root(2,root,advise).
det(2,owl,the).
nsubj(2,advise,owl).
amod(2,owl,next).
dobj(2,advise,they).
nsubj:xsubj(2,pluck,they).
mark(2,pluck,to).
xcomp(2,advise,pluck).
compound:prt(2,pluck,up).
det(2,seed,the).
dobj(2,pluck,seed).
case(2,flax,of).
det(2,flax,the).
nmod:of(2,seed,flax).
dobj(2,sow,flax).
ref(2,flax,which).
nsubj(2,sow,man).
aux(2,sow,have).
acl:relcl(2,flax,sow).
mark(2,plant,as).
nsubj(2,plant,it).
cop(2,plant,be).
det(2,plant,a).
advcl:as(2,sow,plant).
nsubj(2,bode,plant).
ref(2,plant,which).
acl:relcl(2,plant,bode).
neg(2,good,no).
dobj(2,bode,good).
case(2,they,to).
nmod:to(2,bode,they).
% relations.
aos(2,pluck_up,they,seed).
aos(2,advise,owl,they).
aos(2,advise,owl_next,they).
%% and lastly the owl seeing an archer approach predicted that this man being on foot would contrive darts armed with feathers which would fly faster than the wings of the birds themselves.
% dependencies.
root(3,root,lastly).
cc(3,lastly,and).
det(3,owl,the).
nsubj(3,predict,owl).
acl(3,owl,see).
det(3,approach,a).
compound(3,approach,archer).
dobj(3,see,approach).
ccomp(3,lastly,predict).
mark(3,contrive,that).
det(3,man,this).
nsubj(3,contrive,man).
cop(3,foot,be).
case(3,foot,on).
dep(3,man,foot).
aux(3,contrive,would).
ccomp(3,predict,contrive).
dobj(3,contrive,darts).
acl(3,darts,arm).
case(3,feather,with).
nmod:with(3,arm,feather).
nsubj(3,fly,feather).
ref(3,feather,which).
aux(3,fly,would).
acl:relcl(3,feather,fly).
dobj(3,fly,faster).
case(3,wing,than).
det(3,wing,the).
nmod:than(3,fly,wing).
case(3,bird,of).
det(3,bird,the).
nmod:of(3,wing,bird).
advmod(3,bird,themselves).
% relations.
aos(3,contrive,man,darts).
aos(3,see,owl,archer_approach).
aos(3,contrive,man,darts_arm).
%% the birds gave no credence to these warning words but considered the owl to be beside herself and said that she was mad.
% dependencies.
root(4,root,give).
det(4,bird,the).
nsubj(4,give,bird).
nsubj(4,consider,bird).
nsubj(4,say,bird).
neg(4,credence,no).
dobj(4,give,credence).
case(4,word,to).
det(4,word,these).
amod(4,word,warn).
nmod:to(4,give,word).
cc(4,give,but).
conj:but(4,give,consider).
det(4,owl,the).
dobj(4,consider,owl).
mark(4,herself,to).
cop(4,herself,be).
case(4,herself,beside).
advcl:to(4,consider,herself).
cc(4,give,and).
conj:but(4,give,say).
mark(4,mad,that).
nsubj(4,mad,she).
cop(4,mad,be).
ccomp(4,say,mad).
% relations.
aos(4,consider_beside,bird,herself).
aos(4,consider,bird,owl).
aos(4,consider_owl_beside,bird,herself).
%% but afterwards finding her words were true they wondered at her knowledge and deemed her to be the wisest of birds.
% dependencies.
root(5,root,find).
cc(5,find,but).
advmod(5,find,afterwards).
nmod:poss(5,word,she).
nsubj(5,true,word).
cop(5,true,be).
ccomp(5,find,true).
nsubj(5,wonder,they).
nsubj(5,deem,they).
ccomp(5,true,wonder).
case(5,knowledge,at).
nmod:poss(5,knowledge,she).
nmod:at(5,wonder,knowledge).
cc(5,wonder,and).
ccomp(5,true,deem).
conj:and(5,wonder,deem).
dobj(5,deem,she).
nsubj:xsubj(5,wisest,she).
mark(5,wisest,to).
cop(5,wisest,be).
det(5,wisest,the).
xcomp(5,deem,wisest).
case(5,bird,of).
nmod:of(5,wisest,bird).
% relations.
aos(5,deem,they,wisest_of_bird).
aos(5,be,she_word,true).
aos(5,wonder_at,they,she_knowledge).
aos(5,deem,they,she).
aos(5,deem,they,wisest).
%% hence it is that when she appears they look to her as knowing all things while she no longer gives them advice but in solitude laments their past folly.
% dependencies.
root(6,root,be).
advmod(6,it,hence).
nsubj(6,be,it).
mark(6,look,that).
advmod(6,appear,when).
nsubj(6,appear,she).
advcl(6,look,appear).
nsubj(6,look,they).
ccomp(6,be,look).
case(6,she,to).
nmod:to(6,look,she).
mark(6,know,as).
advcl:as(6,look,know).
det(6,thing,all).
dobj(6,know,thing).
mark(6,give,while).
nsubj(6,give,she).
neg(6,longer,no).
advmod(6,give,longer).
dep(6,thing,give).
iobj(6,give,they).
dobj(6,give,advice).
cc(6,give,but).
mark(6,lament,in).
nsubj(6,lament,solitude).
dep(6,thing,lament).
conj:but(6,give,lament).
nmod:poss(6,folly,they).
amod(6,folly,past).
dobj(6,lament,folly).
% relations.
aos(6,look_to,they,she).
