root(0,ROOT,pomegranate).
det(0,pomegranate,the).
cc(0,pomegranate,and).
conj:and(0,pomegranate,apple-tree).
acl(0,pomegranate,disputed).
case(0,was,as).
mark(0,was,to).
nsubj(0,was,which).
dep(0,disputed,was).
det(0,beautiful,the).
advmod(0,beautiful,most).
dep(0,pomegranate,beautiful).
root(1,ROOT,height).
advmod(1,height,when).
nmod:poss(1,strife,their).
nsubj(1,height,strife).
cop(1,height,was).
case(1,height,at).
nmod:poss(1,height,its).
det(1,bramble,a).
nsubj(1,lifted,bramble).
nsubj(1,said,bramble).
case(1,hedge,from).
det(1,hedge,the).
amod(1,hedge,neighboring).
nmod:from(1,bramble,hedge).
acl:relcl(1,height,lifted).
compound:prt(1,lifted,up).
nmod:poss(1,voice,its).
dobj(1,lifted,voice).
cc(1,lifted,and).
acl:relcl(1,height,said).
conj:and(1,lifted,said).
case(1,tone,in).
det(1,tone,a).
amod(1,tone,boastful).
nmod:in(1,said,tone).
said_in(1,bramble,tone).
said_in(1,bramble,boastful_tone).
bramble_from(1,its_voice,hedge).
lifted_up(1,bramble,its_voice).
bramble_from(1,its_voice,neighboring_hedge).
root(2,ROOT,pray).
nmod:poss(2,friends,my).
amod(2,friends,dear).
dobj(2,pray,friends).
case(2,presence,in).
nmod:poss(2,presence,my).
nmod:in(2,pray,presence).
advmod(2,pray,at).
mwe(2,at,least).
dep(2,pray,cease).
case(2,disputings,from).
amod(2,disputings,such).
amod(2,disputings,vain).
nmod:from(2,cease,disputings).
