root(0,ROOT,seagull).
det(0,seagull,a).
aux(0,bolted,having).
dep(0,seagull,bolted).
advmod(0,bolted,down).
advmod(0,large,too).
advmod(0,burst,large).
det(0,burst,a).
compound(0,burst,fish).
nmod:npmod(0,down,burst).
nmod:poss(0,gullet-bag,its).
amod(0,gullet-bag,deep).
dobj(0,bolted,gullet-bag).
cc(0,bolted,and).
dep(0,seagull,lay).
conj:and(0,bolted,lay).
compound:prt(0,lay,down).
case(0,shore,on).
det(0,shore,the).
nmod:on(0,lay,shore).
mark(0,die,to).
xcomp(0,lay,die).
lay_down_on(0,its_deep_gullet-bag,shore).
lay_down_on(0,its_gullet-bag,shore).
lay_down(0,its_deep_gullet-bag,die).
lay_down(0,its_gullet-bag,die).
root(1,ROOT,saw).
det(1,kite,a).
nsubj(1,saw,kite).
nsubj(1,exclaimed,kite).
dobj(1,saw,him).
cc(1,saw,and).
conj:and(1,saw,exclaimed).
saw(1,kite,him).
root(2,ROOT,you).
advmod(2,deserve,richly).
dep(2,you,deserve).
nmod:poss(2,fate,your).
dobj(2,deserve,fate).
root(3,ROOT,has).
mark(3,has,for).
det(3,bird,a).
nsubj(3,has,bird).
case(3,air,of).
det(3,air,the).
nmod:of(3,bird,air).
neg(3,business,no).
dobj(3,has,business).
mark(3,seek,to).
acl:to(3,business,seek).
nmod:poss(3,food,its).
dobj(3,seek,food).
case(3,sea,from).
det(3,sea,the).
nmod:from(3,seek,sea).
