%% a frog once upon a time came forth from his home in the marsh and proclaimed to all the beasts that he was a learned physician skilled in the use of drugs and able to heal all diseases.
% dependencies.
root(0,root,come).
det(0,frog,a).
nsubj(0,come,frog).
nsubj(0,proclaim,frog).
advmod(0,come,once).
case(0,time,upon).
det(0,time,a).
nmod:upon(0,once,time).
advmod(0,come,forth).
case(0,home,from).
nmod:poss(0,home,he).
nmod:from(0,forth,home).
case(0,marsh,in).
det(0,marsh,the).
nmod:in(0,come,marsh).
cc(0,come,and).
conj:and(0,come,proclaim).
case(0,beast,to).
det:predet(0,beast,all).
det(0,beast,the).
nmod:to(0,proclaim,beast).
mark(0,physician,that).
nsubj(0,physician,he).
cop(0,physician,be).
det(0,physician,a).
amod(0,physician,learn).
ccomp(0,proclaim,physician).
amod(0,physician,skilled).
case(0,use,in).
det(0,use,the).
nmod:in(0,skilled,use).
case(0,drug,of).
nmod:of(0,use,drug).
cc(0,skilled,and).
amod(0,physician,able).
conj:and(0,skilled,able).
mark(0,heal,to).
xcomp(0,able,heal).
det(0,disease,all).
dobj(0,heal,disease).
% relations.
proclaim_to(0,frog,beast).
be(0,he,learn).
be(0,he,physician_skilled_in_use_of_drug).
be(0,he,physician).
be(0,he,physician_skilled_in_use).
be(0,he,learn_physician_skilled_in_use).
be(0,he,learn_physician_skilled_in_use_of_drug).
be(0,he,physician_skilled).
be(0,he,learn_physician_skilled).
be(0,he,skilled).
be(0,he,learn_physician).
%% a fox asked him.
% dependencies.
root(1,root,ask).
det(1,fox,a).
nsubj(1,ask,fox).
dobj(1,ask,he).
% relations.
ask(1,fox,he).
%% how can you pretend to prescribe for others when you are unable to heal your own lame gait and wrinkled skin.
% dependencies.
root(2,root,pretend).
advmod(2,pretend,how).
aux(2,pretend,can).
nsubj(2,pretend,you).
nsubj:xsubj(2,prescribe,you).
mark(2,prescribe,to).
xcomp(2,pretend,prescribe).
case(2,other,for).
nmod:for(2,prescribe,other).
advmod(2,unable,when).
nsubj(2,unable,you).
nsubj:xsubj(2,heal,you).
cop(2,unable,be).
advcl(2,prescribe,unable).
mark(2,heal,to).
xcomp(2,unable,heal).
nmod:poss(2,gait,you).
amod(2,gait,own).
amod(2,gait,lame).
dobj(2,heal,gait).
cc(2,gait,and).
amod(2,skin,wrinkled).
dobj(2,heal,skin).
conj:and(2,gait,skin).
% relations.
heal(2,you,you_gait).
prescribe_for(2,you,other).
heal(2,you,you_own_lame_gait).
heal(2,you,skin).
can_pretend(2,you,prescribe_for_other).
be(2,you,unable).
heal(2,you,you_own_gait).
heal(2,you,you_lame_gait).
can_pretend(2,you,prescribe).
be(2,you,when_unable).
heal(2,you,wrinkled_skin).
