root(0,ROOT,prophet).
det(0,prophet,the).
det(0,wizard,a).
nsubj(0,telling,wizard).
acl(0,wizard,sitting).
case(0,marketplace,in).
det(0,marketplace,the).
nmod:in(0,sitting,marketplace).
aux(0,telling,was).
acl:relcl(0,prophet,telling).
det(0,fortunes,the).
dobj(0,telling,fortunes).
case(0,passers-by,of).
det(0,passers-by,the).
nmod:of(0,prophet,passers-by).
advmod(0,ran,when).
det(0,person,a).
nsubj(0,ran,person).
nsubj(0,announced,person).
acl:relcl(0,passers-by,ran).
compound:prt(0,ran,up).
case(0,haste,in).
amod(0,haste,great).
nmod:in(0,ran,haste).
cc(0,ran,and).
acl:relcl(0,passers-by,announced).
conj:and(0,ran,announced).
case(0,him,to).
nmod:to(0,announced,him).
mark(0,broken,that).
det(0,doors,the).
nsubjpass(0,broken,doors).
case(0,house,of).
nmod:poss(0,house,his).
nmod:of(0,doors,house).
aux(0,broken,had).
auxpass(0,broken,been).
ccomp(0,announced,broken).
xcomp(0,broken,open).
cc(0,broken,and).
mark(0,stolen,that).
det:predet(0,goods,all).
nmod:poss(0,goods,his).
nsubjpass(0,stolen,goods).
aux(0,stolen,were).
auxpass(0,stolen,being).
ccomp(0,announced,stolen).
conj:and(0,broken,stolen).
sitting_in(0,wizard,marketplace).
sitting_in(0,wizard_fortunes,marketplace).
announced_to(0,person,him).
were(0,his_goods,were_stolen).
was_telling(0,wizard,fortunes).
were(0,goods,were_stolen).
been(0,doors,broken).
ran_up_in(0,person,great_haste).
been_broken(0,doors,open).
ran_up_in(0,person,haste).
root(1,ROOT,sighed).
nsubj(1,sighed,he).
nsubj(1,hastened,he).
advmod(1,sighed,heavily).
cc(1,sighed,and).
conj:and(1,sighed,hastened).
advmod(1,fast,away).
advmod(1,fast,as).
advmod(1,hastened,fast).
mark(1,run,as).
nsubj(1,run,he).
aux(1,run,could).
advcl:as(1,hastened,run).
hastened(1,he,he_could_run).
hastened_fast(1,he,he_could_run).
hastened_away_fast(1,he,he_could_run).
hastened_as_fast(1,he,he_could_run).
hastened_away_as_fast(1,he,he_could_run).
root(2,ROOT,saw).
det(2,neighbor,a).
nsubj(2,saw,neighbor).
nsubj(2,said,neighbor).
nsubj(2,running,him).
dep(2,saw,running).
cc(2,saw,and).
conj:and(2,saw,said).
root(3,ROOT,oh).
root(4,ROOT,you).
dep(4,you,fellow).
dep(4,you,there).
root(5,ROOT,say).
nsubj(5,say,you).
nsubj(5,foretell,you).
aux(5,foretell,can).
ccomp(5,say,foretell).
det(5,fortunes,the).
dobj(5,foretell,fortunes).
case(5,others,of).
nmod:of(5,fortunes,others).
root(6,ROOT,is).
advmod(6,is,how).
nsubj(6,is,it).
nsubj(6,foresee,you).
aux(6,foresee,did).
neg(6,foresee,not).
acl:relcl(6,it,foresee).
nmod:poss(6,own,your).
dobj(6,foresee,own).
