root(0,ROOT,made).
det(0,man,a).
amod(0,man,certain).
nsubj(0,made,man).
nsubj(0,offered,man).
det(0,image,a).
amod(0,image,wooden).
dobj(0,made,image).
case(0,mercury,of).
nmod:of(0,image,mercury).
cc(0,made,and).
conj:and(0,made,offered).
dobj(0,offered,it).
case(0,sale,for).
nmod:for(0,offered,sale).
made(0,certain_man,image).
made(0,man,wooden_image).
made(0,man,image_of_mercury).
made(0,certain_man,image_of_mercury).
made(0,man,image).
made(0,certain_man,wooden_image).
made(0,man,wooden_image_of_mercury).
offered(0,certain_man,it).
offered(0,man,it).
made(0,certain_man,wooden_image_of_mercury).
root(1,ROOT,appeared).
advmod(1,appeared,when).
neg(1,one,no).
nsubj(1,appeared,one).
xcomp(1,appeared,willing).
mark(1,buy,to).
xcomp(1,willing,buy).
dobj(1,buy,it).
mark(1,attract,in).
mwe(1,in,order).
mark(1,attract,to).
advcl:in_order(1,buy,attract).
dobj(1,attract,purchasers).
mark(1,had,purchasers).
nsubj(1,cried,he).
acl:relcl(1,purchasers,cried).
compound:prt(1,cried,out).
ref(1,purchasers,that).
nsubj(1,had,he).
ccomp(1,cried,had).
det(1,statue,the).
dobj(1,had,statue).
mark(1,sell,to).
acl:to(1,statue,sell).
case(1,benefactor,of).
det(1,benefactor,a).
nmod:of(1,sell,benefactor).
nsubj(1,bestowed,benefactor).
nsubj(1,helped,benefactor).
nsubj:xsubj(1,heap,benefactor).
ref(1,benefactor,who).
acl:relcl(1,benefactor,bestowed).
dobj(1,bestowed,wealth).
cc(1,bestowed,and).
acl:relcl(1,benefactor,helped).
conj:and(1,bestowed,helped).
mark(1,heap,to).
xcomp(1,helped,heap).
compound:prt(1,heap,up).
dobj(1,heap,riches).
root(2,ROOT,said).
det:qmod(2,bystanders,one).
mwe(2,one,of).
det(2,bystanders,the).
nsubj(2,said,bystanders).
case(2,him,to).
nmod:to(2,said,him).
root(3,ROOT,fellow).
nmod:poss(3,fellow,my).
amod(3,fellow,good).
advmod(3,do,why).
dep(3,fellow,do).
nsubj(3,sell,you).
ccomp(3,do,sell).
nsubj(3,one,him).
cop(3,one,being).
case(3,one,such).
det(3,one,a).
dep(3,sell,one).
mark(3,describe,as).
nsubj(3,describe,you).
advcl:as(3,do,describe).
advmod(3,may,when).
nsubj(3,may,you).
advcl(3,describe,may).
dobj(3,may,yourself).
dep(3,may,enjoy).
det(3,things,the).
amod(3,things,good).
dobj(3,enjoy,things).
nsubj(3,has,he).
nsubj:xsubj(3,give,he).
acl:relcl(3,things,has).
mark(3,give,to).
xcomp(3,has,give).
root(4,ROOT,').
root(5,ROOT,why).
root(6,ROOT,replied).
nsubj(6,replied,he).
root(7,ROOT,need).
nsubj(7,need,i).
cop(7,need,am).
case(7,need,in).
case(7,help,of).
amod(7,help,immediate).
nmod:of(7,need,help).
cc(7,need,and).
nsubj(7,wont,he).
nsubj:xsubj(7,give,he).
cop(7,wont,is).
conj:and(7,need,wont).
mark(7,give,to).
xcomp(7,wont,give).
nmod:poss(7,gifts,his).
amod(7,gifts,good).
dobj(7,give,gifts).
advmod(7,slowly,very).
advmod(7,give,slowly).
give_slowly(7,he,his_good_gifts).
am_in(7,i,need_of_help).
give_slowly(7,he,his_gifts).
give_very_slowly(7,he,his_good_gifts).
am_in(7,i,need_of_immediate_help).
is(7,he,wont).
give(7,he,his_good_gifts).
give_very_slowly(7,he,his_gifts).
am_in(7,i,need).
give(7,he,his_gifts).
