root(0,ROOT,had).
det(0,doe,a).
nsubj(0,had,doe).
nsubj(0,see,doe).
aux(0,had,had).
det(0,misfortune,the).
dobj(0,had,misfortune).
mark(0,lose,to).
advcl:to(0,had,lose).
dobj(0,lose,one).
case(0,eyes,of).
nmod:poss(0,eyes,her).
nmod:of(0,one,eyes).
cc(0,had,and).
aux(0,see,could).
neg(0,see,not).
conj:and(0,had,see).
det(0,one,any).
nsubj(0,approaching,one).
dep(0,see,approaching).
dobj(0,approaching,her).
case(0,side,on).
det(0,side,that).
nmod:on(0,approaching,side).
lose(0,doe,one_her_eyes).
lose(0,doe,one_of_her_eyes).
had_had(0,doe,misfortune).
root(1,ROOT,so).
mark(1,avoid,to).
xcomp(1,so,avoid).
det(1,danger,any).
dobj(1,avoid,danger).
nsubj(1,used,she).
nsubj:xsubj(1,feed,she).
advmod(1,used,always).
acl:relcl(1,danger,used).
mark(1,feed,to).
xcomp(1,used,feed).
case(1,cliff,on).
det(1,cliff,a).
amod(1,cliff,high).
nmod:on(1,feed,cliff).
case(1,sea,near).
det(1,sea,the).
nmod:near(1,cliff,sea).
case(1,eye,with).
nmod:poss(1,eye,her).
compound(1,eye,sound).
nmod:with(1,feed,eye).
acl(1,eye,looking).
case(1,land,towards).
det(1,land,the).
nmod:towards(1,looking,land).
root(2,ROOT,this).
case(2,this,by).
acl:relcl(2,this,means).
nsubj(2,see,she).
aux(2,see,could).
ccomp(2,means,see).
advmod(2,approached,whenever).
det(2,hunters,the).
nsubj(2,approached,hunters).
advcl(2,see,approached).
dobj(2,approached,her).
case(2,land,on).
nmod:on(2,approached,land).
cc(2,this,and).
advmod(2,escaped,often).
conj:and(2,this,escaped).
case(2,this,by).
nmod:by(2,escaped,this).
dep(2,this,means).
approached(2,hunters,her).
root(3,ROOT,hunters).
cc(3,hunters,but).
det(3,hunters,the).
acl(3,hunters,found).
mark(3,blind,out).
mark(3,blind,that).
nsubj(3,blind,she).
nsubj(3,hiring,she).
cop(3,blind,was).
advcl:that(3,found,blind).
case(3,eye,of).
nummod(3,eye,one).
nmod:of(3,blind,eye).
cc(3,blind,and).
advcl:that(3,found,hiring).
conj:and(3,blind,hiring).
det(3,boat,a).
dobj(3,hiring,boat).
acl(3,boat,rowed).
case(3,cliff,under).
det(3,cliff,the).
nmod:under(3,rowed,cliff).
advmod(3,used,where).
nsubj(3,used,she).
nsubj:xsubj(3,feed,she).
nsubj(3,shot,she).
acl:relcl(3,cliff,used).
mark(3,feed,to).
xcomp(3,used,feed).
cc(3,used,and).
acl:relcl(3,cliff,shot).
conj:and(3,used,shot).
dobj(3,shot,her).
case(3,sea,from).
det(3,sea,the).
nmod:from(3,shot,sea).
was_blind_of(3,she,one_eye).
was(3,she,blind).
shot(3,she,her).
hiring(3,she,boat).
used(3,she,feed).
hiring(3,she,boat_rowed).
root(4,ROOT,ah).
