root(0,ROOT,found).
det(0,woman,an).
amod(0,woman,old).
nsubj(0,found,woman).
det(0,jar,an).
amod(0,jar,empty).
dobj(0,found,jar).
nsubj(0,full,which).
aux(0,full,had).
advmod(0,full,lately).
cop(0,full,been).
dep(0,found,full).
case(0,wine,of).
amod(0,wine,prime).
amod(0,wine,old).
nmod:of(0,full,wine).
cc(0,full,and).
nsubj(0,retained,which).
advmod(0,retained,still).
dep(0,found,retained).
conj:and(0,full,retained).
det(0,smell,the).
amod(0,smell,fragrant).
dobj(0,retained,smell).
case(0,contents,of).
nmod:poss(0,contents,its).
amod(0,contents,former).
nmod:of(0,smell,contents).
found(0,old_woman,jar).
found(0,woman,jar).
found(0,old_woman,empty_jar).
found(0,woman,empty_jar).
root(1,ROOT,placed).
nsubj(1,placed,she).
advmod(1,placed,greedily).
dobj(1,placed,it).
amod(1,times,several).
nmod:tmod(1,placed,times).
case(1,nose,to).
nmod:poss(1,nose,her).
nmod:to(1,placed,nose).
cc(1,placed,and).
csubj(1,said,drawing).
dobj(1,drawing,it).
advmod(1,drawing,backwards).
cc(1,backwards,and).
advmod(1,drawing,forwards).
conj:and(1,backwards,forwards).
conj:and(1,placed,said).
placed(1,she,it).
greedily_placed(1,she,it).
root(2,ROOT,o).
advmod(2,delicious,most).
amod(2,o,delicious).
root(3,ROOT,must).
advmod(3,must,how).
nsubj(3,must,nice).
det(3,wine,the).
xcomp(3,must,wine).
nsubj(3,been,itself).
aux(3,been,have).
acl:relcl(3,wine,been).
advmod(3,leaves,when).
nsubj(3,leaves,it).
advcl(3,been,leaves).
case(3,vessel,behind).
case(3,vessel,in).
det(3,vessel,the).
advmod(3,vessel,very).
nmod:in(3,leaves,vessel).
nsubj(3,contained,vessel).
ref(3,vessel,which).
acl:relcl(3,vessel,contained).
nsubj(3,sweet,it).
advmod(3,sweet,so).
xcomp(3,contained,sweet).
det(3,perfume,a).
dep(3,wine,perfume).
wine(3,nice,itself_have_been).
