root(0,ROOT,lived).
det(0,man,a).
amod(0,man,rich).
nsubj(0,lived,man).
case(0,tanner,near).
det(0,tanner,a).
nmod:near(0,lived,tanner).
cc(0,tanner,and).
neg(0,able,not).
cop(0,able,being).
nmod:near(0,lived,able).
conj:and(0,tanner,able).
mark(0,bear,to).
xcomp(0,able,bear).
det(0,smell,the).
amod(0,smell,unpleasant).
dobj(0,bear,smell).
case(0,tan-yard,of).
det(0,tan-yard,the).
nmod:of(0,smell,tan-yard).
nsubj(0,pressed,he).
acl:relcl(0,tan-yard,pressed).
nmod:poss(0,neighbor,his).
dobj(0,pressed,neighbor).
mark(0,go,to).
acl:to(0,neighbor,go).
advmod(0,go,away).
root(1,ROOT,put).
det(1,tanner,the).
nsubj(1,put,tanner).
compound:prt(1,put,off).
nmod:poss(1,departure,his).
dobj(1,put,departure).
mark(1,saying,from).
dep(1,time,time).
dep(1,time,to).
advmod(1,saying,time).
advcl:from(1,put,saying).
mark(1,leave,that).
nsubj(1,leave,he).
aux(1,leave,would).
ccomp(1,saying,leave).
advmod(1,leave,soon).
put_off(1,tanner,his_departure).
root(2,ROOT,continued).
cc(2,continued,but).
mark(2,continued,as).
nsubj(2,continued,he).
nsubj:xsubj(2,stay,he).
advmod(2,continued,still).
mark(2,stay,to).
xcomp(2,continued,stay).
mark(2,went,as).
nsubj(2,went,time).
advcl:as(2,stay,went).
case(2,man,on).
det(2,man,the).
amod(2,man,rich).
nmod:on(2,went,man).
acl:relcl(2,man,became).
xcomp(2,became,accustomed).
case(2,smell,to).
det(2,smell,the).
nmod:to(2,accustomed,smell).
cc(2,smell,and).
nmod:to(2,accustomed,feeling).
conj:and(2,smell,feeling).
neg(2,manner,no).
nsubj(2,made,manner).
case(2,inconvenience,of).
nmod:of(2,manner,inconvenience).
ccomp(2,became,made).
neg(2,complaints,no).
amod(2,complaints,further).
dobj(2,made,complaints).
continued(2,he,stay).
stay(2,he,time_went).
still_continued(2,he,stay).
