root(0,ROOT,counseled).
det(0,owl,an).
nsubj(0,counseled,owl).
case(0,wisdom,in).
nmod:poss(0,wisdom,her).
nmod:in(0,owl,wisdom).
det(0,birds,the).
dobj(0,counseled,birds).
dobj(0,sprout,that).
nsubj:xsubj(0,pull,that).
nsubj:xsubj(0,allow,that).
advmod(0,began,when).
det(0,acorn,the).
nsubj(0,began,acorn).
nsubj:xsubj(0,sprout,acorn).
advmod(0,began,first).
dep(0,birds,began).
mark(0,sprout,to).
xcomp(0,began,sprout).
mark(0,pull,to).
xcomp(0,sprout,pull).
dobj(0,pull,it).
dep(0,up,all).
advmod(0,pull,up).
compound:prt(0,pull,out).
case(0,ground,of).
det(0,ground,the).
nmod:of(0,pull,ground).
cc(0,pull,and).
neg(0,allow,not).
xcomp(0,sprout,allow).
conj:and(0,pull,allow).
dobj(0,allow,it).
nsubj:xsubj(0,grow,it).
mark(0,grow,to).
xcomp(0,allow,grow).
is_in(0,owl,her_wisdom).
counseled(0,owl,birds).
root(1,ROOT,said).
nsubj(1,said,she).
nsubj(1,produce,acorns).
aux(1,produce,would).
ccomp(1,said,produce).
dobj(1,produce,mistletoe).
mark(1,extracted,from).
dobj(1,extracted,which).
det(1,poison,an).
amod(1,poison,irremediable).
nsubjpass(1,extracted,poison).
det(1,bird,the).
dep(1,poison,bird).
punct(1,bird,-).
dep(1,bird,lime).
aux(1,extracted,would).
auxpass(1,extracted,be).
dep(1,produce,extracted).
cc(1,extracted,and).
mark(1,captured,by).
dobj(1,captured,which).
nsubjpass(1,captured,they).
aux(1,captured,would).
auxpass(1,captured,be).
dep(1,produce,captured).
conj:and(1,extracted,captured).
root(2,ROOT,advised).
det(2,owl,the).
nsubj(2,advised,owl).
amod(2,owl,next).
dobj(2,advised,them).
nsubj:xsubj(2,pluck,them).
mark(2,pluck,to).
xcomp(2,advised,pluck).
compound:prt(2,pluck,up).
det(2,seed,the).
dobj(2,pluck,seed).
case(2,flax,of).
det(2,flax,the).
nmod:of(2,seed,flax).
dobj(2,sown,flax).
ref(2,flax,which).
nsubj(2,sown,men).
aux(2,sown,had).
acl:relcl(2,flax,sown).
mark(2,plant,as).
nsubj(2,plant,it).
cop(2,plant,was).
det(2,plant,a).
advcl:as(2,sown,plant).
nsubj(2,boded,plant).
ref(2,plant,which).
acl:relcl(2,plant,boded).
neg(2,good,no).
dobj(2,boded,good).
case(2,them,to).
nmod:to(2,boded,them).
pluck_up(2,them,seed).
advised(2,owl,them).
advised(2,owl_next,them).
root(3,ROOT,lastly).
cc(3,lastly,and).
det(3,owl,the).
nsubj(3,predicted,owl).
acl(3,owl,seeing).
det(3,approach,an).
compound(3,approach,archer).
dobj(3,seeing,approach).
ccomp(3,lastly,predicted).
mark(3,contrive,that).
det(3,man,this).
nsubj(3,contrive,man).
cop(3,foot,being).
case(3,foot,on).
dep(3,man,foot).
aux(3,contrive,would).
ccomp(3,predicted,contrive).
dobj(3,contrive,darts).
acl(3,darts,armed).
case(3,feathers,with).
nmod:with(3,armed,feathers).
nsubj(3,fly,feathers).
ref(3,feathers,which).
aux(3,fly,would).
acl:relcl(3,feathers,fly).
dobj(3,fly,faster).
case(3,wings,than).
det(3,wings,the).
nmod:than(3,fly,wings).
case(3,birds,of).
det(3,birds,the).
nmod:of(3,wings,birds).
advmod(3,birds,themselves).
contrive(3,man,darts).
seeing(3,owl,archer_approach).
contrive(3,man,darts_armed).
root(4,ROOT,gave).
det(4,birds,the).
nsubj(4,gave,birds).
nsubj(4,considered,birds).
nsubj(4,said,birds).
neg(4,credence,no).
dobj(4,gave,credence).
case(4,words,to).
det(4,words,these).
amod(4,words,warning).
nmod:to(4,gave,words).
cc(4,gave,but).
conj:but(4,gave,considered).
det(4,owl,the).
dobj(4,considered,owl).
mark(4,herself,to).
cop(4,herself,be).
case(4,herself,beside).
advcl:to(4,considered,herself).
cc(4,gave,and).
conj:but(4,gave,said).
mark(4,mad,that).
nsubj(4,mad,she).
cop(4,mad,was).
ccomp(4,said,mad).
considered_beside(4,birds,herself).
considered(4,birds,owl).
considered_owl_beside(4,birds,herself).
root(5,ROOT,finding).
cc(5,finding,but).
advmod(5,finding,afterwards).
nmod:poss(5,words,her).
nsubj(5,true,words).
cop(5,true,were).
ccomp(5,finding,true).
nsubj(5,wondered,they).
nsubj(5,deemed,they).
ccomp(5,true,wondered).
case(5,knowledge,at).
nmod:poss(5,knowledge,her).
nmod:at(5,wondered,knowledge).
cc(5,wondered,and).
ccomp(5,true,deemed).
conj:and(5,wondered,deemed).
dobj(5,deemed,her).
nsubj:xsubj(5,wisest,her).
mark(5,wisest,to).
cop(5,wisest,be).
det(5,wisest,the).
xcomp(5,deemed,wisest).
case(5,birds,of).
nmod:of(5,wisest,birds).
deemed(5,they,wisest_of_birds).
were(5,her_words,true).
wondered_at(5,they,her_knowledge).
deemed(5,they,her).
deemed(5,they,wisest).
root(6,ROOT,is).
advmod(6,it,hence).
nsubj(6,is,it).
mark(6,look,that).
advmod(6,appears,when).
nsubj(6,appears,she).
advcl(6,look,appears).
nsubj(6,look,they).
ccomp(6,is,look).
case(6,her,to).
nmod:to(6,look,her).
mark(6,knowing,as).
advcl:as(6,look,knowing).
det(6,things,all).
dobj(6,knowing,things).
mark(6,gives,while).
nsubj(6,gives,she).
neg(6,longer,no).
advmod(6,gives,longer).
dep(6,things,gives).
iobj(6,gives,them).
dobj(6,gives,advice).
cc(6,gives,but).
mark(6,laments,in).
nsubj(6,laments,solitude).
dep(6,things,laments).
conj:but(6,gives,laments).
nmod:poss(6,folly,their).
amod(6,folly,past).
dobj(6,laments,folly).
look_to(6,they,her).
