root(0,ROOT,displeased).
det(0,she-goats,the).
nsubj(0,displeased,she-goats).
nsubj(0,made,she-goats).
aux(0,obtained,having).
acl(0,she-goats,obtained).
det(0,beard,a).
dobj(0,obtained,beard).
case(0,request,by).
nmod:by(0,obtained,request).
mark(0,jupiter,to).
advcl:to(0,obtained,jupiter).
det(0,he-goats,the).
dobj(0,jupiter,he-goats).
cop(0,displeased,were).
advmod(0,displeased,sorely).
cc(0,displeased,and).
conj:and(0,displeased,made).
dobj(0,made,complaint).
mark(0,equaled,that).
det(0,females,the).
nsubj(0,equaled,females).
ccomp(0,made,equaled).
dobj(0,equaled,them).
case(0,dignity,in).
nmod:in(0,equaled,dignity).
were(0,she-goats,sorely_displeased).
were(0,she-goats,displeased).
made(0,she-goats,complaint).
equaled(0,females,them).
root(1,ROOT,allow).
dobj(1,allow,them).
root(2,ROOT,said).
nsubj(2,said,jupiter).
root(3,ROOT,equals).
mark(3,enjoy,to).
csubj(3,equals,enjoy).
det(3,honor,an).
amod(3,honor,empty).
dobj(3,enjoy,honor).
cc(3,enjoy,and).
mark(3,assume,to).
conj:and(3,enjoy,assume).
csubj(3,equals,assume).
det(3,badge,the).
dobj(3,assume,badge).
case(3,sex,of).
nmod:poss(3,sex,your).
amod(3,sex,nobler).
nmod:of(3,badge,sex).
advmod(3,long,so).
advmod(3,assume,long).
mark(3,your,as).
nsubj(3,your,they).
cop(3,your,are).
neg(3,your,not).
advcl:as(3,long,your).
case(3,strength,in).
nmod:in(3,equals,strength).
cc(3,strength,or).
nmod:in(3,equals,courage).
conj:or(3,strength,courage).
root(4,ROOT,matters).
nsubj(4,matters,it).
xcomp(4,matters,little).
mark(4,us,if).
nsubj(4,inferior,those).
nsubj(4,us,those).
ref(4,those,who).
cop(4,inferior,are).
acl:relcl(4,those,inferior).
case(4,us,to).
nmod:to(4,inferior,us).
case(4,merit,in).
nmod:in(4,inferior,merit).
aux(4,us,should).
cop(4,us,be).
case(4,us,like).
advcl:like(4,matters,us).
case(4,appearances,in).
amod(4,appearances,outside).
nmod:in(4,us,appearances).
matters_like(4,it,should_us_in_appearances).
matters_like(4,it,should_us_in_outside_appearances).
matters(4,it,little).
matters_like(4,it,should_us).
