%% the north wind and the sun disputed as to which was the most powerful and agreed that he should be declared the victor who could first strip a wayfaring man of his clothes.
% dependencies.
root(0,root,wind).
det(0,wind,the).
compound(0,wind,north).
cc(0,wind,and).
det(0,sun,the).
conj:and(0,wind,sun).
dep(0,wind,dispute).
case(0,powerful,as).
mark(0,powerful,to).
nsubj(0,powerful,which).
cop(0,powerful,be).
det(0,powerful,the).
advmod(0,powerful,most).
dep(0,dispute,powerful).
cc(0,dispute,and).
dep(0,wind,agree).
conj:and(0,dispute,agree).
mark(0,declare,that).
nsubjpass(0,declare,he).
aux(0,declare,should).
auxpass(0,declare,be).
ccomp(0,agree,declare).
det(0,victor,the).
dobj(0,declare,victor).
nsubj(0,strip,victor).
ref(0,victor,who).
aux(0,strip,could).
advmod(0,strip,first).
acl:relcl(0,victor,strip).
det(0,man,a).
amod(0,man,wayfaring).
dobj(0,strip,man).
case(0,clothes,of).
nmod:poss(0,clothes,he).
nmod:of(0,man,clothes).
% relations.
be(0,he,declare).
%% the north wind first tried his power and blew with all his might but the keener his blasts the closer the traveler wrapped his cloak around him until at last resigning all hope of victory the wind called upon the sun to see what he could do.
% dependencies.
root(1,root,wind).
det(1,wind,the).
compound(1,wind,north).
advmod(1,try,first).
acl:relcl(1,wind,try).
nmod:poss(1,power,he).
dobj(1,try,power).
cc(1,try,and).
acl:relcl(1,wind,blow).
conj:and(1,try,blow).
case(1,all,with).
nmod:with(1,blow,all).
nsubj(1,might,he).
acl:relcl(1,all,might).
case(1,keener,but).
det(1,keener,the).
nmod:but(1,blow,keener).
nmod:poss(1,blast,he).
dobj(1,try,blast).
det(1,closer,the).
dep(1,traveler,closer).
det(1,traveler,the).
dep(1,wind,traveler).
acl:relcl(1,traveler,wrap).
nmod:poss(1,cloak,he).
dobj(1,wrap,cloak).
case(1,he,around).
nmod:around(1,wrap,he).
case(1,last,until).
case(1,last,at).
nmod:at(1,wrap,last).
acl(1,last,resign).
det(1,hope,all).
dobj(1,resign,hope).
case(1,wind,of).
compound(1,wind,victory).
det(1,wind,the).
nmod:of(1,traveler,wind).
acl(1,wind,call).
case(1,sun,upon).
det(1,sun,the).
nmod:upon(1,call,sun).
mark(1,see,to).
xcomp(1,call,see).
dobj(1,do,what).
nsubj(1,do,he).
aux(1,do,could).
ccomp(1,see,do).
% relations.
blow_but(1,he_power,keener).
%% the sun suddenly shone out with all his warmth.
% dependencies.
root(2,root,shine).
det(2,sun,the).
dep(2,shine,sun).
advmod(2,shine,suddenly).
compound:prt(2,shine,out).
case(2,all,with).
nmod:with(2,shine,all).
nmod:poss(2,warmth,he).
nsubj(2,shine,warmth).
% relations.
suddenly_shine_out_with(2,he_warmth,all).
shine_out_with(2,he_warmth,all).
%% the traveler no sooner felt his genial rays than he took off one garment after another and at last fairly overcome with heat undressed and bathed in a stream that lay in his path.
% dependencies.
root(3,root,feel).
det(3,traveler,the).
nsubj(3,feel,traveler).
neg(3,sooner,no).
advmod(3,feel,sooner).
nmod:poss(3,ray,he).
amod(3,ray,genial).
dobj(3,feel,ray).
mark(3,take,than).
nsubj(3,take,he).
advcl:than(3,feel,take).
compound:prt(3,take,off).
nummod(3,garment,one).
dobj(3,take,garment).
dobj(3,take,garment).
conj:and(3,garment,garment).
case(3,another,after).
nmod:after(3,garment,another).
cc(3,garment,and).
case(3,last,at).
nmod:at(3,garment,last).
advmod(3,overcome,fairly).
dep(3,last,overcome).
case(3,heat,with).
nmod:with(3,overcome,heat).
amod(3,heat,undressed).
cc(3,overcome,and).
dep(3,last,bath).
conj:and(3,overcome,bath).
case(3,stream,in).
det(3,stream,a).
nmod:in(3,bath,stream).
nsubj(3,lay,stream).
ref(3,stream,that).
acl:relcl(3,stream,lay).
case(3,path,in).
nmod:poss(3,path,he).
nmod:in(3,lay,path).
% relations.
take_off(3,he,one_garment).
take_off(3,he,one_garment_at_last).
feel(3,traveler,he_genial_ray).
take_off(3,he,one_garment_after_another).
feel(3,traveler,he_ray).
take_off(3,he,one_garment_after_another_at_last).
