root(0,ROOT,bent).
det(0,labourer,an).
amod(0,labourer,old).
nsubj(0,bent,labourer).
nsubj(0,toil,labourer).
advmod(0,age,double).
case(0,age,with).
nmod:with(0,bent,age).
cc(0,bent,and).
conj:and(0,bent,toil).
aux(0,gathering,was).
ccomp(0,toil,gathering).
dobj(0,gathering,sticks).
case(0,forest,in).
det(0,forest,a).
nmod:in(0,sticks,forest).
bent_with(0,old_labourer,age).
bent_with(0,labourer,double_age).
is_in(0,sticks,forest).
bent_with(0,labourer,age).
bent_with(0,old_labourer,double_age).
root(1,ROOT,grew).
case(1,last,at).
nmod:at(1,grew,last).
nsubj(1,grew,he).
advmod(1,tired,so).
xcomp(1,grew,tired).
cc(1,tired,and).
xcomp(1,grew,hopeless).
conj:and(1,tired,hopeless).
mark(1,threw,that).
nsubj(1,threw,he).
nsubj(1,cried,he).
ccomp(1,tired,threw).
compound:prt(1,threw,down).
det(1,bundle,the).
dobj(1,threw,bundle).
case(1,sticks,of).
nmod:of(1,bundle,sticks).
cc(1,threw,and).
ccomp(1,tired,cried).
conj:and(1,threw,cried).
compound:prt(1,cried,out).
grew(1,he,tired).
grew_at(1,he,last).
grew(1,he,so_tired).
threw_down(1,he,bundle_of_sticks).
threw_down(1,he,bundle).
bundle_of(1,he,sticks).
root(2,ROOT,bear).
nsubj(2,bear,i).
aux(2,bear,can).
neg(2,bear,not).
det(2,life,this).
dobj(2,bear,life).
det(2,longer,any).
advmod(2,bear,longer).
root(3,ROOT,i).
dep(3,i,ah).
compound(3,death,wish).
nsubj(3,come,death).
nsubj(3,take,death).
aux(3,come,would).
advmod(3,come,only).
acl:relcl(3,i,come).
cc(3,come,and).
acl:relcl(3,i,take).
conj:and(3,come,take).
dobj(3,come,me).
would_only_come(3,wish_death,me).
would_come(3,wish_death,me).
root(4,ROOT,spoke).
mark(4,spoke,as).
nsubj(4,spoke,he).
dobj(4,spoke,death).
det(4,skeleton,a).
amod(4,skeleton,grisly).
nsubj(4,appeared,skeleton).
nsubj(4,said,skeleton).
acl:relcl(4,death,appeared).
cc(4,appeared,and).
acl:relcl(4,death,said).
conj:and(4,appeared,said).
case(4,him,to).
nmod:to(4,appeared,him).
appeared_to(4,skeleton,him).
appeared_to(4,grisly_skeleton,him).
root(5,ROOT,wouldst).
dep(5,wouldst,what).
nmod:npmod(5,mortal,thou).
amod(5,wouldst,mortal).
root(6,ROOT,heard).
nsubj(6,heard,i).
nsubj(6,call,thee).
ccomp(6,heard,call).
dobj(6,call,me).
call(6,thee,me).
root(7,ROOT,please).
dobj(7,please,sir).
root(8,ROOT,replied).
det(8,woodcutter,the).
nsubj(8,replied,woodcutter).
root(9,ROOT,help).
aux(9,help,would).
nsubj(9,help,you).
advmod(9,help,kindly).
dobj(9,help,me).
mark(9,lift,to).
advcl:to(9,help,lift).
det(9,faggot,this).
dobj(9,lift,faggot).
case(9,sticks,of).
nmod:of(9,faggot,sticks).
case(9,shoulder,on).
case(9,shoulder,to).
nmod:poss(9,shoulder,my).
nmod:to(9,lift,shoulder).
would_help(9,you,me).
would_kindly_help(9,you,me).
lift_faggot_on(9,you,on_my_shoulder).
lift(9,you,faggot_of_sticks).
lift(9,you,faggot).
