root(0,ROOT,wind).
det(0,wind,the).
compound(0,wind,north).
cc(0,wind,and).
det(0,sun,the).
conj:and(0,wind,sun).
dep(0,wind,disputed).
case(0,powerful,as).
mark(0,powerful,to).
nsubj(0,powerful,which).
cop(0,powerful,was).
det(0,powerful,the).
advmod(0,powerful,most).
dep(0,disputed,powerful).
cc(0,disputed,and).
dep(0,wind,agreed).
conj:and(0,disputed,agreed).
mark(0,declared,that).
nsubjpass(0,declared,he).
aux(0,declared,should).
auxpass(0,declared,be).
ccomp(0,agreed,declared).
det(0,victor,the).
dobj(0,declared,victor).
nsubj(0,strip,victor).
ref(0,victor,who).
aux(0,strip,could).
advmod(0,strip,first).
acl:relcl(0,victor,strip).
det(0,man,a).
amod(0,man,wayfaring).
dobj(0,strip,man).
case(0,clothes,of).
nmod:poss(0,clothes,his).
nmod:of(0,man,clothes).
be(0,he,declared).
root(1,ROOT,wind).
det(1,wind,the).
compound(1,wind,north).
advmod(1,tried,first).
acl:relcl(1,wind,tried).
nmod:poss(1,power,his).
dobj(1,tried,power).
cc(1,tried,and).
acl:relcl(1,wind,blew).
conj:and(1,tried,blew).
case(1,all,with).
nmod:with(1,blew,all).
nsubj(1,might,his).
acl:relcl(1,all,might).
case(1,keener,but).
det(1,keener,the).
nmod:but(1,blew,keener).
nmod:poss(1,blasts,his).
dobj(1,tried,blasts).
det(1,closer,the).
dep(1,traveler,closer).
det(1,traveler,the).
dep(1,wind,traveler).
acl:relcl(1,traveler,wrapped).
nmod:poss(1,cloak,his).
dobj(1,wrapped,cloak).
case(1,him,around).
nmod:around(1,wrapped,him).
case(1,last,until).
case(1,last,at).
nmod:at(1,wrapped,last).
acl(1,last,resigning).
det(1,hope,all).
dobj(1,resigning,hope).
case(1,wind,of).
compound(1,wind,victory).
det(1,wind,the).
nmod:of(1,traveler,wind).
acl(1,wind,called).
case(1,sun,upon).
det(1,sun,the).
nmod:upon(1,called,sun).
mark(1,see,to).
xcomp(1,called,see).
dobj(1,do,what).
nsubj(1,do,he).
aux(1,do,could).
ccomp(1,see,do).
blew_but(1,his_power,keener).
root(2,ROOT,shone).
det(2,sun,the).
dep(2,shone,sun).
advmod(2,shone,suddenly).
compound:prt(2,shone,out).
case(2,all,with).
nmod:with(2,shone,all).
nmod:poss(2,warmth,his).
nsubj(2,shone,warmth).
suddenly_shone_out_with(2,his_warmth,all).
shone_out_with(2,his_warmth,all).
root(3,ROOT,felt).
det(3,traveler,the).
nsubj(3,felt,traveler).
neg(3,sooner,no).
advmod(3,felt,sooner).
nmod:poss(3,rays,his).
amod(3,rays,genial).
dobj(3,felt,rays).
mark(3,took,than).
nsubj(3,took,he).
advcl:than(3,felt,took).
compound:prt(3,took,off).
nummod(3,garment,one).
dobj(3,took,garment).
dobj(3,took,garment).
conj:and(3,garment,garment).
case(3,another,after).
nmod:after(3,garment,another).
cc(3,garment,and).
case(3,last,at).
nmod:at(3,garment,last).
advmod(3,overcome,fairly).
dep(3,last,overcome).
case(3,heat,with).
nmod:with(3,overcome,heat).
amod(3,heat,undressed).
cc(3,overcome,and).
dep(3,last,bathed).
conj:and(3,overcome,bathed).
case(3,stream,in).
det(3,stream,a).
nmod:in(3,bathed,stream).
nsubj(3,lay,stream).
ref(3,stream,that).
acl:relcl(3,stream,lay).
case(3,path,in).
nmod:poss(3,path,his).
nmod:in(3,lay,path).
took_off(3,he,one_garment).
took_off(3,he,one_garment_at_last).
felt(3,traveler,his_genial_rays).
took_off(3,he,one_garment_after_another).
felt(3,traveler,his_rays).
took_off(3,he,one_garment_after_another_at_last).
