root(0,ROOT,went).
det(0,man,a).
nsubjpass(0,bitten,man).
nsubj(0,went,man).
ref(0,man,who).
aux(0,bitten,had).
auxpass(0,bitten,been).
acl:relcl(0,man,bitten).
case(0,dog,by).
det(0,dog,a).
nmod:agent(0,bitten,dog).
advmod(0,went,about).
case(0,quest,in).
nmod:in(0,went,quest).
nsubj(0,heal,quest).
case(0,someone,of).
nmod:of(0,quest,someone).
ref(0,quest,who).
aux(0,heal,might).
acl:relcl(0,quest,heal).
dobj(0,heal,him).
root(1,ROOT,said).
det(1,meeting,a).
compound(1,meeting,friend).
nsubj(1,said,meeting).
dep(1,meeting,him).
cc(1,him,and).
acl(1,him,learning).
dobj(1,wanted,what).
nsubj(1,wanted,he).
ccomp(1,learning,wanted).
root(2,ROOT,cured).
mark(2,cured,if).
nsubjpass(2,cured,you).
aux(2,cured,would).
auxpass(2,cured,be).
ccomp(2,cured,take).
det(2,piece,a).
dobj(2,take,piece).
case(2,bread,of).
nmod:of(2,piece,bread).
cc(2,take,and).
ccomp(2,cured,dip).
conj:and(2,take,dip).
dobj(2,dip,it).
case(2,blood,in).
det(2,blood,the).
nmod:in(2,dip,blood).
case(2,wound,from).
nmod:poss(2,wound,your).
nmod:from(2,blood,wound).
cc(2,dip,and).
conj:and(2,take,go).
conj:and(2,dip,go).
cc(2,go,and).
conj:and(2,dip,give).
conj:and(2,go,give).
dobj(2,go,it).
case(2,dog,to).
det(2,dog,the).
nmod:to(2,go,dog).
case(2,bit,that).
nmod:that(2,dog,bit).
dobj(2,dip,you).
dip(2,piece,you).
go_to(2,you,dog_bit).
dip(2,piece,it).
go(2,you,it).
would(2,you,would_cured).
go_to(2,you,dog).
root(3,ROOT,laughed).
det(3,man,the).
nsubjpass(3,bitten,man).
nsubj(3,laughed,man).
nsubj(3,said,man).
ref(3,man,who).
aux(3,bitten,had).
auxpass(3,bitten,been).
acl:relcl(3,man,bitten).
case(3,advice,at).
det(3,advice,this).
nmod:at(3,laughed,advice).
cc(3,laughed,and).
conj:and(3,laughed,said).
root(4,ROOT,why).
root(5,ROOT,do).
mark(5,do,if).
nsubj(5,do,i).
aux(5,do,should).
advmod(5,be,so).
nsubj(5,be,it).
aux(5,be,would).
ccomp(5,do,be).
mark(5,beg,as).
mwe(5,as,if).
nsubj(5,beg,i).
aux(5,beg,should).
advcl:as_if(5,be,beg).
det(5,dog,every).
dobj(5,beg,dog).
case(5,town,in).
det(5,town,the).
nmod:in(5,beg,town).
mark(5,bite,to).
acl:to(5,town,bite).
dobj(5,bite,me).
should_beg(5,i,dog).
root(6,ROOT,bestowed).
nsubj(6,bestowed,benefits).
case(6,increase,upon).
det(6,increase,the).
amod(6,increase,evil-disposed).
nmod:upon(6,bestowed,increase).
nmod:poss(6,means,their).
dobj(6,bestowed,means).
mark(6,injuring,of).
acl:of(6,means,injuring).
dobj(6,injuring,you).
