%% the weasels and the mice waged a perpetual war with each other in which much blood was shed.
% dependencies.
root(0,root,wage).
det(0,weasel,the).
nsubj(0,wage,weasel).
cc(0,weasel,and).
det(0,mouse,the).
conj:and(0,weasel,mouse).
nsubj(0,wage,mouse).
det(0,war,a).
amod(0,war,perpetual).
dobj(0,wage,war).
case(0,other,with).
det(0,other,each).
nmod:with(0,wage,other).
nmod:in(0,shed,other).
case(0,which,in).
ref(0,other,which).
amod(0,blood,much).
nsubjpass(0,shed,blood).
auxpass(0,shed,be).
acl:relcl(0,other,shed).
% relations.
wage(0,mouse,perpetual_war).
wage(0,mouse,war).
wage(0,weasel,perpetual_war).
wage(0,weasel,war).
be(0,blood,shed).
be(0,much_blood,shed).
%% the weasels were always the victors.
% dependencies.
root(1,root,victor).
det(1,weasel,the).
nsubj(1,victor,weasel).
cop(1,victor,be).
advmod(1,victor,always).
det(1,victor,the).
% relations.
be(1,weasel,victor).
be(1,weasel,always_victor).
%% the mice thought that the cause of their frequent defeats was that they had no leaders set apart from the general army to command them and that they were exposed to dangers from lack of discipline.
% dependencies.
root(2,root,think).
det(2,mouse,the).
nsubj(2,think,mouse).
mark(2,defeat,that).
det(2,cause,the).
nsubj(2,defeat,cause).
case(2,frequent,of).
nmod:poss(2,frequent,they).
nmod:of(2,cause,frequent).
ccomp(2,think,defeat).
ccomp(2,defeat,be).
mark(2,have,that).
nsubj(2,have,they).
ccomp(2,be,have).
neg(2,leader,no).
dobj(2,have,leader).
acl:relcl(2,leader,set).
advmod(2,set,apart).
case(2,army,from).
det(2,army,the).
amod(2,army,general).
nmod:from(2,set,army).
mark(2,command,to).
xcomp(2,set,command).
dobj(2,command,they).
cc(2,be,and).
mark(2,expose,that).
nsubjpass(2,expose,they).
auxpass(2,expose,be).
ccomp(2,defeat,expose).
conj:and(2,be,expose).
case(2,danger,to).
nmod:to(2,expose,danger).
case(2,lack,from).
nmod:from(2,expose,lack).
case(2,discipline,of).
nmod:of(2,lack,discipline).
% relations.
%% they therefore chose as leaders mice that were most renowned for their family descent strength and counsel as well as those most noted for their courage in the fight so that they might be better marshaled in battle array and formed into troops regiments and battalions.
% dependencies.
root(3,root,choose).
nsubj(3,choose,they).
advmod(3,choose,therefore).
case(3,mouse,as).
compound(3,mouse,leader).
nmod:as(3,choose,mouse).
nsubj(3,renowned,mouse).
ref(3,mouse,that).
cop(3,renowned,be).
advmod(3,renowned,most).
acl:relcl(3,mouse,renowned).
case(3,strength,for).
nmod:poss(3,strength,they).
compound(3,strength,family).
compound(3,strength,descent).
nmod:for(3,renowned,strength).
cc(3,strength,and).
nmod:for(3,renowned,counsel).
conj:and(3,strength,counsel).
cc(3,strength,as).
mwe(3,as,well).
mwe(3,as,as).
nmod:for(3,renowned,those).
conj:and(3,strength,those).
advmod(3,note,most).
acl(3,those,note).
case(3,courage,for).
nmod:poss(3,courage,they).
nmod:for(3,note,courage).
case(3,fight,in).
det(3,fight,the).
nmod:in(3,courage,fight).
mark(3,marshal,so).
mwe(3,so,that).
nsubjpass(3,marshal,they).
nsubjpass(3,form,they).
aux(3,marshal,might).
auxpass(3,marshal,be).
advmod(3,marshal,better).
advcl:so_that(3,renowned,marshal).
case(3,array,in).
compound(3,array,battle).
nmod:in(3,marshal,array).
cc(3,marshal,and).
advcl:so_that(3,renowned,form).
conj:and(3,marshal,form).
case(3,regiment,into).
compound(3,regiment,troops).
nmod:into(3,form,regiment).
cc(3,regiment,and).
nmod:into(3,form,battalion).
conj:and(3,regiment,battalion).
% relations.
is_in(3,they_courage,fight).
most_note_for(3,those,they_courage_fight).
might(3,they,might_better_marshal_in_battle_array).
note_for(3,those,they_courage_fight).
might(3,they,might_marshal).
note_for(3,those,they_courage).
might(3,they,might_better_marshal).
most_note_for(3,those,they_courage).
might(3,they,might_marshal_in_battle_array).
form_into(3,they,troops_regiment).
%% when all this was done and the army disciplined and the herald mouse had duly proclaimed war by challenging the weasels the newly chosen generals bound their heads with straws that they might be more conspicuous to all their troops.
% dependencies.
root(4,root,do).
advmod(4,do,when).
det:predet(4,this,all).
nsubjpass(4,do,this).
auxpass(4,do,be).
cc(4,do,and).
det(4,army,the).
nsubj(4,discipline,army).
conj:and(4,do,discipline).
cc(4,discipline,and).
nsubj(4,herald,the).
conj:and(4,do,herald).
conj:and(4,discipline,herald).
nsubj(4,have,mouse).
ccomp(4,herald,have).
advmod(4,proclaimed,duly).
amod(4,war,proclaimed).
dobj(4,have,war).
mark(4,challenge,by).
advcl:by(4,have,challenge).
det(4,weasel,the).
dobj(4,challenge,weasel).
mark(4,conspicuous,weasel).
det(4,general,the).
advmod(4,choose,newly).
amod(4,general,choose).
nsubj(4,bind,general).
acl:relcl(4,weasel,bind).
nmod:poss(4,head,they).
dobj(4,bind,head).
case(4,straw,with).
nmod:with(4,bind,straw).
ref(4,weasel,that).
nsubj(4,conspicuous,they).
aux(4,conspicuous,might).
cop(4,conspicuous,be).
advmod(4,conspicuous,more).
ccomp(4,bind,conspicuous).
case(4,troops,to).
det:predet(4,troops,all).
nmod:poss(4,troops,they).
nmod:to(4,conspicuous,troops).
% relations.
be_more_conspicuous_to(4,they,troops).
bind_with(4,general,straw).
have(4,mouse,war).
bind(4,choose_general,they_head).
be(4,this,do).
be_conspicuous_to(4,they,they_troops).
bind_with(4,choose_general,straw).
be_more_conspicuous_to(4,they,they_troops).
have(4,mouse,proclaimed_war).
be(4,this,when_do).
have(4,mouse,duly_proclaimed_war).
be_conspicuous_to(4,they,troops).
bind(4,general,they_head).
%% scarcely had the battle begun when a great rout overwhelmed the mice who scampered off as fast as they could to their holes.
% dependencies.
root(5,root,have).
advmod(5,have,scarcely).
det(5,battle,the).
dobj(5,have,battle).
acl(5,battle,begin).
advmod(5,overwhelm,when).
det(5,rout,a).
amod(5,rout,great).
nsubj(5,overwhelm,rout).
advcl(5,begin,overwhelm).
det(5,mouse,the).
dobj(5,overwhelm,mouse).
nsubj(5,scamper,mouse).
ref(5,mouse,who).
acl:relcl(5,mouse,scamper).
compound:prt(5,scamper,off).
case(5,fast,as).
advmod(5,scamper,fast).
mark(5,could,as).
nsubj(5,could,they).
dep(5,have,could).
case(5,hole,to).
nmod:poss(5,hole,they).
nmod:to(5,could,hole).
% relations.
%% the generals not being able to get in on account of the ornaments on their heads were all captured and eaten by the weasels.
% dependencies.
root(6,root,capture).
det(6,general,the).
nsubjpass(6,capture,general).
nsubjpass(6,eat,general).
neg(6,able,not).
cop(6,able,be).
acl(6,general,able).
mark(6,get,to).
xcomp(6,able,get).
case(6,ornament,in).
case(6,ornament,on).
mwe(6,on,account).
mwe(6,on,of).
det(6,ornament,the).
nmod:on_account_of(6,get,ornament).
case(6,head,on).
nmod:poss(6,head,they).
nmod:on(6,ornament,head).
auxpass(6,capture,be).
advmod(6,capture,all).
cc(6,capture,and).
conj:and(6,capture,eat).
case(6,weasel,by).
det(6,weasel,the).
nmod:agent(6,capture,weasel).
% relations.
