root(0,ROOT,woman).
det(0,woman,an).
amod(0,woman,old).
aux(0,lost,having).
dep(0,woman,lost).
det(0,use,the).
dobj(0,lost,use).
case(0,eyes,of).
nmod:poss(0,eyes,her).
nmod:of(0,use,eyes).
dep(0,eyes,called).
case(0,physician,in).
det(0,physician,a).
nmod:in(0,called,physician).
mark(0,heal,to).
xcomp(0,called,heal).
dobj(0,heal,them).
cc(0,called,and).
dep(0,eyes,made).
conj:and(0,called,made).
det(0,bargain,this).
dobj(0,made,bargain).
case(0,him,with).
nmod:with(0,bargain,him).
case(0,presence,in).
det(0,presence,the).
nmod:in(0,made,presence).
case(0,witnesses,of).
nmod:of(0,presence,witnesses).
mark(0,receive,that).
mark(0,cure,if).
nsubj(0,cure,he).
aux(0,cure,should).
advcl:if(0,receive,cure).
nmod:poss(0,blindness,her).
dobj(0,cure,blindness).
nsubj(0,receive,he).
aux(0,receive,should).
ccomp(0,made,receive).
case(0,sum,from).
nmod:poss(0,sum,her).
det(0,sum,a).
nmod:from(0,receive,sum).
case(0,money,of).
nmod:of(0,sum,money).
receive_from(0,he,her_sum).
receive_from(0,he,her_sum_of_money).
is_with(0,bargain,him).
should_cure(0,he,her_blindness).
root(1,ROOT,remained).
cc(1,remained,but).
mark(1,remained,if).
nmod:poss(1,infirmity,her).
nsubj(1,remained,infirmity).
nsubj(1,give,she).
aux(1,give,should).
ccomp(1,remained,give).
iobj(1,give,him).
dobj(1,give,nothing).
give(1,she,nothing).
give(1,she,him).
root(2,ROOT,took).
det(2,agreement,this).
nsubj(2,took,agreement).
auxpass(2,made,being).
acl(2,agreement,made).
det(2,time,the).
compound(2,time,physician).
dobj(2,made,time).
mark(2,applied,after).
nsubj(2,applied,time).
nsubj(2,applied,time).
advcl:after(2,made,applied).
advcl:after(2,made,applied).
conj:and(2,applied,applied).
nmod:poss(2,salve,his).
dobj(2,applied,salve).
case(2,eyes,to).
nmod:poss(2,eyes,her).
nmod:to(2,applied,eyes).
cc(2,applied,and).
case(2,visit,on).
det(2,visit,every).
nmod:on(2,applied,visit).
dobj(2,took,something).
advmod(2,stealing,away).
xcomp(2,took,stealing).
det:predet(2,property,all).
nmod:poss(2,property,her).
dobj(2,stealing,property).
advmod(2,stealing,little).
case(2,little,by).
nmod:by(2,stealing,little).
away_stealing_little(2,something,property).
stealing_property_by(2,something,little).
away_stealing_little(2,something,her_property).
stealing_little(2,something,property).
away_stealing(2,something,her_property).
stealing(2,something,property).
stealing_property_little_by(2,something,little).
away_stealing_property_by(2,something,little).
took(2,agreement,something).
away_stealing(2,something,property).
away_stealing_property_little_by(2,something,little).
stealing(2,something,her_property).
stealing_little(2,something,her_property).
root(3,ROOT,got).
cc(3,got,and).
advmod(3,got,when).
nsubj(3,got,he).
aux(3,got,had).
dobj(3,got,all).
nsubj(3,had,she).
acl:relcl(3,all,had).
nsubj(3,healed,he).
nsubj(3,demanded,he).
ccomp(3,had,healed).
dobj(3,healed,her).
cc(3,healed,and).
ccomp(3,had,demanded).
conj:and(3,healed,demanded).
det(3,payment,the).
amod(3,payment,promised).
dobj(3,demanded,payment).
demanded(3,he,promised_payment).
healed(3,he,her).
demanded(3,he,payment).
root(4,ROOT,give).
det(4,woman,the).
amod(4,woman,old).
nsubj(4,give,woman).
advmod(4,recovered,when).
nsubj(4,recovered,she).
nsubj(4,saw,she).
acl:relcl(4,woman,recovered).
nmod:poss(4,sight,her).
dobj(4,recovered,sight).
cc(4,recovered,and).
acl:relcl(4,woman,saw).
conj:and(4,recovered,saw).
dobj(4,saw,none).
case(4,goods,of).
nmod:poss(4,goods,her).
nmod:of(4,none,goods).
case(4,house,in).
nmod:poss(4,house,her).
nmod:in(4,saw,house).
aux(4,give,would).
iobj(4,give,him).
dobj(4,give,nothing).
saw(4,she,none).
saw_none_in(4,she,her_house).
recovered(4,she,her_sight).
saw(4,she,none_of_her_goods).
root(5,ROOT,insisted).
det(5,physician,the).
nsubj(5,insisted,physician).
case(5,claim,on).
nmod:poss(5,claim,his).
nmod:on(5,insisted,claim).
cc(5,claim,and).
insisted_on(5,physician,his_claim).
root(6,ROOT,refused).
mark(6,refused,as).
nsubj(6,refused,she).
advmod(6,refused,still).
ccomp(6,refused,summoned).
dobj(6,summoned,her).
case(6,judge,before).
det(6,judge,the).
nmod:before(6,summoned,judge).
root(7,ROOT,argued).
det(7,woman,the).
amod(7,woman,old).
nsubj(7,argued,woman).
acl(7,woman,standing).
compound:prt(7,standing,up).
case(7,court,in).
det(7,court,the).
nmod:in(7,standing,court).
root(8,ROOT,speaks).
det(8,man,this).
nsubj(8,speaks,man).
advmod(8,speaks,here).
det(8,truth,the).
dobj(8,speaks,truth).
nmod:in(8,says,truth).
case(8,what,in).
ref(8,truth,what).
nsubj(8,says,he).
acl:relcl(8,truth,says).
root(9,ROOT,did).
mark(9,did,for).
nsubj(9,did,i).
dobj(9,did,promise).
mark(9,give,to).
advcl:to(9,did,give).
iobj(9,give,him).
det(9,sum,a).
dobj(9,give,sum).
case(9,money,of).
nmod:of(9,sum,money).
mark(9,recover,if).
nsubj(9,recover,i).
aux(9,recover,should).
dep(9,sum,recover).
nmod:poss(9,sight,my).
dobj(9,recover,sight).
cc(9,recover,but).
mark(9,continued,if).
nsubj(9,continued,i).
dep(9,sum,continued).
conj:but(9,recover,continued).
xcomp(9,continued,blind).
nsubj(9,was,i).
nsubj:xsubj(9,give,i).
ccomp(9,blind,was).
mark(9,give,to).
xcomp(9,was,give).
iobj(9,give,him).
dobj(9,give,nothing).
give(9,i,nothing).
continued(9,i,blind).
did(9,i,promise).
give(9,i,sum_of_money).
give(9,i,him).
give(9,i,him).
give(9,i,sum).
root(10,ROOT,declares).
advmod(10,declares,now).
nsubj(10,declares,he).
mark(10,healed,that).
nsubjpass(10,healed,i).
auxpass(10,healed,am).
ccomp(10,declares,healed).
am(10,i,healed).
root(11,ROOT,i).
case(11,affirm,on).
det(11,affirm,the).
amod(11,affirm,contrary).
nmod:on(11,i,affirm).
dobj(11,blind,affirm).
ref(11,affirm,that).
nsubj(11,blind,i).
cop(11,blind,am).
advmod(11,blind,still).
acl:relcl(11,affirm,blind).
am(11,i,blind).
am(11,i,still_blind).
root(12,ROOT,able).
mark(12,able,for).
advmod(12,lost,when).
nsubj(12,lost,i).
advcl(12,able,lost).
det(12,use,the).
dobj(12,lost,use).
case(12,eyes,of).
nmod:poss(12,eyes,my).
nmod:of(12,use,eyes).
nmod(12,lost,i).
dep(12,i,saw).
case(12,chattels,in).
nmod:poss(12,chattels,my).
compound(12,chattels,house).
amod(12,chattels,various).
nmod:in(12,saw,chattels).
cc(12,chattels,and).
amod(12,goods,valuable).
nmod:in(12,saw,goods).
conj:and(12,chattels,goods).
cc(12,lost,but).
advmod(12,swears,now).
mark(12,swears,though).
nsubj(12,swears,he).
advcl:though(12,lost,swears).
nsubjpass(12,cured,i).
auxpass(12,cured,am).
ccomp(12,swears,cured).
case(12,blindness,of).
nmod:poss(12,blindness,my).
nmod:of(12,cured,blindness).
nsubj(12,able,i).
nsubj:xsubj(12,see,i).
cop(12,able,am).
neg(12,able,not).
mark(12,see,to).
xcomp(12,able,see).
det(12,thing,a).
amod(12,thing,single).
dobj(12,see,thing).
case(12,it,in).
nmod:in(12,see,it).
lost(12,i,use_of_my_eyes).
lost_use(12,i,he_swears).
am(12,i,cured).
lost_use(12,i,now_he_swears).
is_in(12,saw,my_house_various_chattels).
am_cured_of(12,i,my_blindness).
lost(12,i,use).
