root(0,ROOT,galloped).
det(0,mule,the).
nsubj(0,galloped,mule).
nsubj(0,said,mule).
conj:and(0,mule,mule).
nsubj(0,galloped,mule).
det(0,frolicsome,a).
amod(0,frolicsome,mule).
nmod:from(0,mule,frolicsome).
case(0,frolicsome,from).
dep(0,frolicsome,lack).
case(0,work,of).
nmod:of(0,lack,work).
cc(0,mule,and).
case(0,corn,from).
advmod(0,much,too).
amod(0,corn,much).
nmod:from(0,mule,corn).
advmod(0,galloped,about).
case(0,manner,in).
det(0,manner,a).
advmod(0,manner,very).
amod(0,manner,extravagant).
nmod:in(0,galloped,manner).
cc(0,galloped,and).
conj:and(0,galloped,said).
case(0,himself,to).
nmod:to(0,said,himself).
galloped_about_in(0,mule,very_extravagant_manner).
said_to(0,mule,himself).
galloped_about_in(0,mule,manner).
galloped_in(0,mule,very_extravagant_manner).
galloped_in(0,mule,extravagant_manner).
galloped_about_in(0,mule,extravagant_manner).
galloped_in(0,mule,very_manner).
galloped_about_in(0,mule,very_manner).
galloped_in(0,mule,manner).
root(1,ROOT,racer).
nmod:poss(1,father,my).
nsubj(1,racer,father).
advmod(1,racer,surely).
cop(1,racer,was).
det(1,racer,a).
amod(1,racer,high-mettled).
cc(1,racer,and).
nsubj(1,child,i).
cop(1,child,am).
nmod:poss(1,child,his).
amod(1,child,own).
conj:and(1,racer,child).
case(1,speed,in).
nmod:in(1,child,speed).
cc(1,speed,and).
nmod:in(1,child,spirit).
conj:and(1,speed,spirit).
am(1,i,his_own_child).
is_in(1,his_own_child,speed).
was(1,my_father,surely_high-mettled_racer).
am(1,i,his_own_child_in_speed).
am(1,i,his_child).
was(1,my_father,high-mettled_racer).
was(1,father,high-mettled).
was(1,my_father,racer).
was(1,my_father,surely_racer).
am(1,i,his_child_in_speed).
root(2,ROOT,day).
case(2,day,on).
det(2,day,the).
amod(2,day,next).
auxpass(2,driven,being).
acl(2,day,driven).
det(2,journey,a).
amod(2,journey,long).
nsubj(2,wearied,journey).
cc(2,journey,and).
conj:and(2,journey,feeling).
nsubj(2,wearied,feeling).
advmod(2,feeling,very).
ccomp(2,driven,wearied).
nsubj(2,exclaimed,he).
ccomp(2,wearied,exclaimed).
case(2,tone,in).
det(2,tone,a).
amod(2,tone,disconsolate).
nmod:in(2,exclaimed,tone).
exclaimed_in(2,he,disconsolate_tone).
exclaimed_in(2,he,tone).
root(3,ROOT,made).
nsubj(3,made,i).
aux(3,made,must).
aux(3,made,have).
det(3,mistake,a).
dobj(3,made,mistake).
root(4,ROOT,father).
nmod:poss(4,father,my).
mark(4,ass,after).
nsubj(4,ass,all).
aux(4,ass,could).
aux(4,ass,have).
cop(4,ass,been).
advmod(4,ass,only).
det(4,ass,an).
dep(4,father,ass).
could(4,all,could_have_ass).
could(4,all,could_have_only_ass).
