root(0,ROOT,driving).
det(0,miller,a).
nsubj(0,driving,miller).
cc(0,miller,and).
nmod:poss(0,son,his).
conj:and(0,miller,son).
nsubj(0,driving,son).
aux(0,driving,were).
nmod:poss(0,ass,their).
dobj(0,driving,ass).
case(0,a,to).
nmod:to(0,driving,a).
amod(0,a,neighboring).
amod(0,a,fair).
mark(0,sell,to).
xcomp(0,fair,sell).
dobj(0,sell,him).
were_driving(0,his_son,their_ass).
were_driving(0,miller,their_ass).
root(1,ROOT,gone).
nsubj(1,gone,they).
aux(1,gone,had).
neg(1,gone,not).
advmod(1,when,far).
advmod(1,met,when).
nsubj(1,met,they).
advcl(1,gone,met).
mark(1,round,with).
det(1,troop,a).
nsubj(1,round,troop).
case(1,women,of).
nmod:of(1,troop,women).
acl(1,women,collected).
advcl:with(1,met,round).
det(1,well,a).
dobj(1,round,well).
xcomp(1,round,talking).
cc(1,talking,and).
xcomp(1,round,laughing).
conj:and(1,talking,laughing).
root(2,ROOT,look).
advmod(2,look,there).
root(3,ROOT,cried).
det:qmod(3,them,one).
mwe(3,one,of).
nsubj(3,cried,them).
root(4,ROOT,did).
nsubj(4,see,you).
advmod(4,see,ever).
ccomp(4,did,see).
amod(4,fellows,such).
dobj(4,see,fellows).
nsubj:xsubj(4,trudging,fellows).
mark(4,trudging,to).
aux(4,trudging,be).
xcomp(4,see,trudging).
advmod(4,trudging,along).
det(4,road,the).
nsubj(4,did,road).
case(4,foot,on).
nmod:on(4,road,foot).
advmod(4,ride,when).
nsubj(4,ride,they).
aux(4,ride,might).
acl:relcl(4,road,ride).
ever_see(4,you,fellows).
ever_see(4,you,such_fellows).
see(4,you,fellows).
see(4,you,such_fellows).
root(5,ROOT,made).
punct(5,made,').
det(5,hearing,the).
amod(5,hearing,old).
compound(5,hearing,man).
dep(5,made,hearing).
dep(5,quickly,this).
advmod(5,made,quickly).
nmod:poss(5,son,his).
nsubj(5,mount,son).
ccomp(5,made,mount).
det(5,ass,the).
dobj(5,mount,ass).
cc(5,made,and).
conj:and(5,made,continued).
mark(5,walk,to).
xcomp(5,continued,walk).
case(5,merrily,along).
advcl:along(5,walk,merrily).
case(5,side,by).
nmod:poss(5,side,his).
nmod:by(5,walk,side).
mount(5,his_son,ass).
root(6,ROOT,came).
dep(6,they,presently).
dep(6,came,they).
compound:prt(6,came,up).
case(6,group,to).
det(6,group,a).
nmod:to(6,came,group).
case(6,men,of).
amod(6,men,old).
nmod:of(6,group,men).
case(6,debate,in).
amod(6,debate,earnest).
nmod:in(6,came,debate).
root(7,ROOT,there).
root(8,ROOT,said).
det:qmod(8,them,one).
mwe(8,one,of).
nsubj(8,said,them).
root(9,ROOT,proves).
nsubj(9,proves,it).
dobj(9,a-saying,what).
nsubj(9,a-saying,i).
cop(9,a-saying,was).
ccomp(9,proves,a-saying).
root(10,ROOT,shown).
det(10,respect,what).
nsubjpass(10,shown,respect).
auxpass(10,shown,is).
case(10,age,to).
amod(10,age,old).
nmod:to(10,shown,age).
case(10,days,in).
det(10,days,these).
nmod:in(10,age,days).
is_in(10,old_age,days).
root(11,ROOT,do).
nsubj(11,see,you).
ccomp(11,do,see).
det(11,lad,that).
amod(11,lad,idle).
dobj(11,see,lad).
acl(11,lad,riding).
mark(11,has,while).
nmod:poss(11,father,his).
amod(11,father,old).
nsubj(11,has,father).
nsubj:xsubj(11,walk,father).
advcl:while(11,riding,has).
mark(11,walk,to).
xcomp(11,has,walk).
see(11,you,idle_lad_riding).
has(11,his_old_father,walk).
see(11,you,lad_riding).
has(11,his_father,walk).
see(11,you,lad).
see(11,you,idle_lad).
root(12,ROOT,get).
compound:prt(12,get,down).
dep(12,scapegrace,you).
amod(12,scapegrace,young).
dobj(12,get,scapegrace).
cc(12,get,and).
conj:and(12,get,let).
det(12,man,the).
amod(12,man,old).
nsubj(12,rest,man).
ccomp(12,let,rest).
nmod:poss(12,limbs,his).
amod(12,limbs,weary).
dobj(12,rest,limbs).
rest(12,old_man,his_weary_limbs).
rest(12,man,his_limbs).
rest(12,man,his_weary_limbs).
rest(12,old_man,his_limbs).
root(13,ROOT,this).
case(13,this,upon).
det(13,man,the).
amod(13,man,old).
nsubj(13,made,man).
nsubj(13,got,man).
acl:relcl(13,this,made).
nmod:poss(13,dismount,his).
compound(13,dismount,son).
dobj(13,made,dismount).
cc(13,made,and).
acl:relcl(13,this,got).
conj:and(13,made,got).
compound:prt(13,got,up).
dobj(13,got,himself).
got_up(13,old_man,himself).
got_up(13,man,himself).
made(13,man,his_son_dismount).
made(13,old_man,his_son_dismount).
root(14,ROOT,proceeded).
case(14,manner,in).
det(14,manner,this).
nmod:in(14,proceeded,manner).
nsubj(14,proceeded,they).
aux(14,proceeded,had).
neg(14,proceeded,not).
advmod(14,when,far).
advmod(14,met,when).
nsubj(14,met,they).
advcl(14,proceeded,met).
det(14,company,a).
dobj(14,met,company).
case(14,women,of).
nmod:of(14,company,women).
cc(14,women,and).
nmod:of(14,company,children).
conj:and(14,women,children).
root(15,ROOT,why).
dep(15,why,you).
amod(15,fellow,lazy).
amod(15,fellow,old).
dep(15,you,fellow).
root(16,ROOT,cried).
amod(16,tongues,several).
nsubj(16,cried,tongues).
case(16,once,at).
advmod(16,tongues,once).
root(17,ROOT,ride).
advmod(17,ride,how).
aux(17,ride,can).
nsubj(17,ride,you).
case(17,beast,upon).
det(17,beast,the).
nmod:upon(17,ride,beast).
case(17,lad,while).
det(17,lad,that).
amod(17,lad,poor).
amod(17,lad,little).
nmod:while(17,ride,lad).
expl(17,keep,there).
aux(17,keep,can).
advmod(17,keep,hardly).
acl:relcl(17,lad,keep).
dobj(17,keep,pace).
case(17,side,by).
det(17,side,the).
nmod:by(17,keep,side).
case(17,you,of).
nmod:of(17,side,you).
can_ride_upon(17,you,beast).
root(18,ROOT,took).
punct(18,took,').
det(18,miller,the).
amod(18,miller,good-natured).
dep(18,took,miller).
advmod(18,took,immediately).
compound:prt(18,took,up).
nmod:poss(18,son,his).
dobj(18,took,son).
case(18,him,behind).
nmod:behind(18,took,him).
root(19,ROOT,reached).
nsubj(19,reached,they).
aux(19,reached,had).
advmod(19,almost,now).
advmod(19,reached,almost).
det(19,town,the).
dobj(19,reached,town).
had_now_almost_reached(19,they,town).
had_almost_reached(19,they,town).
had_reached(19,they,town).
root(20,ROOT,pray).
amod(20,friend,honest).
dep(20,pray,friend).
root(21,ROOT,said).
det(21,citizen,a).
nsubj(21,said,citizen).
root(22,ROOT,that).
cop(22,that,is).
nsubj(22,that,ass).
nmod:poss(22,own,your).
dep(22,ass,own).
is(22,ass,that).
root(23,ROOT,').
root(24,ROOT,yes).
root(25,ROOT,replied).
det(25,man,the).
amod(25,man,old).
nsubj(25,replied,man).
root(26,ROOT,thought).
nsubj(26,thought,o).
nummod(26,o,one).
aux(26,thought,would).
neg(26,thought,not).
aux(26,thought,have).
advmod(26,thought,so).
root(27,ROOT,said).
det(27,other,the).
nsubj(27,said,other).
root(28,ROOT,load).
case(28,way,by).
det(28,way,the).
nmod:by(28,load,way).
nsubj(28,load,you).
dobj(28,load,him).
load(28,you,him).
root(29,ROOT,able).
advmod(29,able,why).
nsubj(29,able,you).
nsubj:xsubj(29,carry,you).
nummod(29,fellows,two).
dep(29,you,fellows).
cop(29,able,are).
advmod(29,able,better).
mark(29,carry,to).
xcomp(29,able,carry).
det(29,beast,the).
amod(29,beast,poor).
dobj(29,carry,beast).
mark(29,you,than).
dep(29,you,he).
advcl:than(29,carry,you).
root(30,ROOT,anything).
mark(30,please,to).
dep(30,anything,please).
dobj(30,please,you).
root(31,ROOT,said).
det(31,man,the).
amod(31,man,old).
nsubj(31,said,man).
root(32,ROOT,try).
nsubj(32,try,we).
aux(32,try,can).
advmod(32,try,but).
root(33,ROOT,alighting).
advmod(33,alighting,so).
case(33,son,with).
nmod:poss(33,son,his).
nmod:with(33,alighting,son).
nsubj(33,tied,they).
advcl(33,alighting,tied).
det(33,legs,the).
dobj(33,tied,legs).
case(33,ass,of).
det(33,ass,the).
nmod:of(33,legs,ass).
advmod(33,tied,together).
cc(33,tied,and).
mark(33,endeavored,with).
det(33,help,the).
nsubj(33,endeavored,help).
nsubj:xsubj(33,carry,help).
case(33,pole,of).
det(33,pole,a).
nmod:of(33,help,pole).
advcl(33,alighting,endeavored).
conj:and(33,tied,endeavored).
mark(33,carry,to).
xcomp(33,endeavored,carry).
dobj(33,carry,him).
case(33,shoulders,on).
nmod:poss(33,shoulders,their).
nmod:on(33,carry,shoulders).
case(33,bridge,over).
det(33,bridge,a).
nmod:over(33,shoulders,bridge).
case(33,entrance,near).
det(33,entrance,the).
nmod:near(33,bridge,entrance).
case(33,town,to).
det(33,town,the).
nmod:to(33,carry,town).
tied_together(33,they,legs).
carry(33,help,him).
tied(33,they,legs).
tied(33,they,legs_of_ass).
tied_together(33,they,legs_of_ass).
legs_of(33,they,ass).
root(34,ROOT,brought).
det(34,sight,this).
amod(34,sight,entertaining).
nsubj(34,brought,sight).
det(34,people,the).
dobj(34,brought,people).
case(34,crowds,in).
nmod:in(34,brought,crowds).
case(34,laugh,to).
nmod:to(34,crowds,laugh).
case(34,it,at).
nmod:at(34,brought,it).
mark(34,fell,till).
det(34,ass,the).
nsubj(34,fell,ass).
neg(34,liking,not).
dep(34,ass,liking).
det(34,noise,the).
dobj(34,liking,noise).
cc(34,noise,nor).
det(34,handling,the).
amod(34,handling,strange).
dobj(34,liking,handling).
conj:nor(34,noise,handling).
mark(34,subject,that).
nsubj(34,subject,he).
nsubj:xsubj(34,broke,he).
cop(34,subject,was).
dep(34,handling,subject).
mark(34,broke,to).
xcomp(34,subject,broke).
det(34,cords,the).
dobj(34,broke,cords).
nsubj(34,bound,cords).
ref(34,cords,that).
acl:relcl(34,cords,bound).
dobj(34,bound,him).
cc(34,liking,and).
dep(34,ass,tumbling).
conj:and(34,liking,tumbling).
compound:prt(34,tumbling,off).
det(34,pole,the).
dobj(34,tumbling,pole).
advcl:till(34,brought,fell).
case(34,river,into).
det(34,river,the).
nmod:into(34,fell,river).
root(35,ROOT,made).
case(35,man,upon).
det(35,man,this).
det(35,old,the).
amod(35,man,old).
nmod:upon(35,made,man).
dep(35,man,vexed).
cc(35,vexed,and).
dep(35,man,ashamed).
conj:and(35,vexed,ashamed).
det(35,best,the).
nsubj(35,made,best).
case(35,home,of).
nmod:poss(35,home,his).
compound(35,home,way).
nmod:of(35,best,home).
advmod(35,convinced,again).
dep(35,home,convinced).
mark(35,had,that).
mark(35,endeavoring,by).
advcl:by(35,had,endeavoring).
mark(35,please,to).
xcomp(35,endeavoring,please).
dobj(35,please,everybody).
nsubj(35,had,he).
nsubj(35,lost,he).
dep(35,best,had).
amod(35,nobody,pleased).
dobj(35,had,nobody).
cc(35,had,and).
dep(35,best,lost).
conj:and(35,had,lost).
nmod:poss(35,ass,his).
dobj(35,lost,ass).
case(35,bargain,in).
det(35,bargain,the).
nmod:in(35,lost,bargain).
had(35,he,pleased_nobody).
made_upon(35,best,old_man).
had(35,he,nobody).
lost(35,he,his_ass).
made_upon(35,best,man).
had_nobody(35,he,endeavoring).
