root(0,ROOT,hound).
det(0,hound,the).
amod(0,hound,old).
nsubj(0,yielded,hound).
det(0,hound,a).
nsubj(0,yielded,hound).
nsubj(0,encountered,hound).
ref(0,hound,who).
ref(0,hound,who).
case(0,days,in).
det(0,days,the).
nmod:in(0,yielded,days).
case(0,youth,of).
nmod:poss(0,youth,his).
nmod:of(0,days,youth).
cc(0,youth,and).
nmod:of(0,days,strength).
conj:and(0,youth,strength).
aux(0,yielded,had).
neg(0,yielded,never).
acl:relcl(0,hound,yielded).
case(0,beast,to).
det(0,beast,any).
nmod:to(0,yielded,beast).
case(0,forest,of).
det(0,forest,the).
nmod:of(0,beast,forest).
acl:relcl(0,hound,encountered).
case(0,age,in).
nmod:poss(0,age,his).
amod(0,age,old).
nmod:in(0,encountered,age).
det(0,boar,a).
dobj(0,encountered,boar).
case(0,chase,in).
det(0,chase,the).
nmod:in(0,boar,chase).
is_in(0,boar,chase).
root(1,ROOT,seized).
nsubj(1,seized,he).
nsubj(1,retain,he).
dobj(1,seized,him).
advmod(1,seized,boldly).
case(1,ear,by).
det(1,ear,the).
nmod:by(1,boldly,ear).
cc(1,seized,but).
aux(1,retain,could).
neg(1,retain,not).
conj:but(1,seized,retain).
nmod:poss(1,hold,his).
dobj(1,retain,hold).
case(1,decay,because).
mwe(1,because,of).
det(1,decay,the).
nmod:because_of(1,retain,decay).
case(1,teeth,of).
nmod:poss(1,teeth,his).
nmod:of(1,decay,teeth).
mark(1,escaped,so).
mwe(1,so,that).
det(1,boar,the).
nsubj(1,escaped,boar).
advcl:so_that(1,retain,escaped).
root(2,ROOT,disappointed).
nmod:poss(2,master,his).
nsubj(2,disappointed,master).
nsubj(2,abused,master).
advmod(2,coming,quickly).
acl(2,master,coming).
compound:prt(2,coming,up).
cop(2,disappointed,was).
advmod(2,much,very).
advmod(2,disappointed,much).
cc(2,disappointed,and).
advmod(2,abused,fiercely).
conj:and(2,disappointed,abused).
det(2,dog,the).
dobj(2,abused,dog).
was(2,his_master,much_disappointed).
fiercely_abused(2,his_master,dog).
abused(2,his_master,dog).
was(2,his_master,very_much_disappointed).
was(2,his_master,disappointed).
root(3,ROOT,looked).
det(3,hound,the).
nsubj(3,looked,hound).
nsubj(3,said,hound).
advmod(3,looked,up).
cc(3,looked,and).
conj:and(3,looked,said).
root(4,ROOT,fault).
nsubj(4,fault,it).
cop(4,fault,was).
neg(4,fault,not).
nmod:poss(4,fault,my).
root(5,ROOT,master).
nmod:poss(5,spirit,my).
nsubj(5,good,spirit).
cop(5,good,was).
advmod(5,good,as).
acl:relcl(5,master,good).
case(5,ever,as).
advcl:as(5,good,ever).
cc(5,good,but).
nsubj(5,help,i).
aux(5,help,could).
neg(5,help,not).
acl:relcl(5,master,help).
conj:but(5,good,help).
nmod:poss(5,infirmities,my).
dobj(5,help,infirmities).
root(6,ROOT,deserve).
dep(6,rather,i).
cc(6,deserve,rather).
mark(6,praised,to).
auxpass(6,praised,be).
xcomp(6,deserve,praised).
mark(6,than,for).
dobj(6,blamed,what).
nsubj(6,than,i).
nsubjpass:xsubj(6,blamed,i).
aux(6,than,have).
aux(6,than,been).
advcl:for(6,praised,than).
mark(6,blamed,to).
auxpass(6,blamed,be).
xcomp(6,than,blamed).
mark(6,am,for).
dobj(6,am,what).
nsubj(6,am,i).
advcl:for(6,blamed,am).
