root(0,ROOT,used).
det(0,dog,a).
nsubj(0,used,dog).
mark(0,run,to).
ccomp(0,used,run).
compound:prt(0,run,up).
advmod(0,run,quietly).
case(0,heels,to).
det(0,heels,the).
nmod:to(0,run,heels).
case(0,everyone,of).
nmod:of(0,heels,everyone).
nsubj(0,met,he).
acl:relcl(0,everyone,met).
cc(0,run,and).
mark(0,bite,to).
ccomp(0,used,bite).
conj:and(0,run,bite).
dobj(0,bite,them).
case(0,notice,without).
nmod:without(0,bite,notice).
root(1,ROOT,suspended).
nmod:poss(1,master,his).
nsubj(1,suspended,master).
det(1,bell,a).
dobj(1,suspended,bell).
case(1,neck,about).
nmod:poss(1,neck,his).
nmod:about(1,suspended,neck).
mark(1,give,so).
mwe(1,so,that).
det(1,dog,the).
nsubj(1,give,dog).
aux(1,give,might).
advcl:so_that(1,suspended,give).
dobj(1,give,notice).
case(1,presence,of).
nmod:poss(1,presence,his).
nmod:of(1,notice,presence).
advmod(1,went,wherever).
nsubj(1,went,he).
advcl(1,give,went).
suspended(1,his_master,bell).
suspended_bell_about(1,his_master,his_neck).
might_give(1,dog,notice).
notice_of(1,dog,his_presence).
might_give(1,dog,notice_of_his_presence).
root(2,ROOT,thinking).
nsubj(2,mark,it).
det(2,mark,a).
xcomp(2,thinking,mark).
case(2,distinction,of).
nmod:of(2,mark,distinction).
det(2,dog,the).
nsubj(2,grew,dog).
nsubj(2,went,dog).
acl:relcl(2,distinction,grew).
xcomp(2,grew,proud).
case(2,bell,of).
nmod:poss(2,bell,his).
nmod:of(2,grew,bell).
cc(2,grew,and).
acl:relcl(2,distinction,went).
conj:and(2,grew,went).
xcomp(2,went,tinkling).
dobj(2,tinkling,it).
dep(2,marketplace,all).
case(2,marketplace,over).
det(2,marketplace,the).
nmod:over(2,tinkling,marketplace).
grew(2,dog,proud).
grew_of(2,dog,his_bell).
root(3,ROOT,said).
nummod(3,day,one).
nsubj(3,said,day).
det(3,hound,an).
amod(3,hound,old).
dep(3,day,hound).
case(3,him,to).
nmod:to(3,said,him).
advmod(3,do,why).
advcl(3,said,do).
nsubj(3,make,you).
ccomp(3,do,make).
det:predet(3,exhibition,such).
det(3,exhibition,an).
dobj(3,make,exhibition).
case(3,yourself,of).
nmod:of(3,exhibition,yourself).
root(4,ROOT,believe).
case(4,bell,that).
nmod:that(4,believe,bell).
mark(4,carry,that).
nsubj(4,carry,you).
dep(4,bell,carry).
aux(4,believe,is).
neg(4,believe,not).
iobj(4,believe,me).
det(4,order,any).
dobj(4,believe,order).
case(4,merit,of).
nmod:of(4,order,merit).
cc(4,order,but).
case(4,contrary,on).
det(4,contrary,the).
dobj(4,believe,contrary).
conj:but(4,order,contrary).
det(4,mark,a).
nsubj(4,believe,mark).
case(4,disgrace,of).
nmod:of(4,mark,disgrace).
det(4,notice,a).
amod(4,notice,public).
dep(4,mark,notice).
case(4,men,to).
det(4,men,all).
nmod:to(4,notice,men).
mark(4,avoid,to).
acl:to(4,notice,avoid).
dobj(4,avoid,you).
case(4,dog,as).
det(4,dog,an).
amod(4,mannered,ill).
amod(4,dog,mannered).
nmod:as(4,avoid,dog).
