root(0,ROOT,prowling).
det(0,wolf,a).
amod(0,wolf,famished).
nsubj(0,prowling,wolf).
aux(0,prowling,was).
advmod(0,prowling,about).
case(0,morning,in).
det(0,morning,the).
nmod:in(0,prowling,morning).
case(0,search,in).
nmod:in(0,morning,search).
case(0,food,of).
nmod:of(0,search,food).
was_prowling_in(0,famished_wolf,morning_in_search).
was_prowling_in(0,famished_wolf,morning_in_search_of_food).
was_prowling_in(0,wolf,morning).
is_in(0,morning,search_of_food).
was_prowling_in(0,famished_wolf,morning).
was_prowling_about_in(0,famished_wolf,morning).
was_prowling_about_in(0,wolf,morning_in_search_of_food).
was_prowling_in(0,wolf,morning_in_search_of_food).
was_prowling_in(0,wolf,morning_in_search).
was_prowling_about_in(0,famished_wolf,morning_in_search_of_food).
was_prowling_about_in(0,wolf,morning).
was_prowling_about_in(0,wolf,morning_in_search).
was_prowling_about_in(0,famished_wolf,morning_in_search).
root(1,ROOT,passed).
mark(1,passed,as).
nsubj(1,passed,he).
det(1,door,the).
dobj(1,passed,door).
case(1,cottage,of).
det(1,cottage,a).
nmod:of(1,door,cottage).
acl(1,cottage,built).
case(1,forest,in).
det(1,forest,the).
nmod:in(1,built,forest).
nsubj(1,heard,he).
acl:relcl(1,forest,heard).
det(1,mother,a).
nsubj(1,say,mother).
ccomp(1,heard,say).
case(1,child,to).
nmod:poss(1,child,her).
nmod:to(1,say,child).
passed(1,he,door_of_cottage_built).
passed(1,he,door_of_cottage).
passed(1,he,door).
say_to(1,mother,her_child).
root(2,ROOT,quiet).
cop(2,quiet,be).
cc(2,quiet,or).
conj:or(2,quiet,i).
aux(2,throw,will).
acl:relcl(2,i,throw).
dobj(2,throw,you).
advmod(2,throw,out).
case(2,window,of).
det(2,window,the).
nmod:of(2,i,window).
cc(2,window,and).
det(2,wolf,the).
nmod:of(2,i,wolf).
conj:and(2,window,wolf).
aux(2,eat,shall).
acl:relcl(2,wolf,eat).
dobj(2,eat,you).
root(3,ROOT,sat).
det(3,wolf,the).
nsubj(3,sat,wolf).
det(3,day,all).
dobj(3,sat,day).
acl(3,day,waiting).
case(3,door,at).
det(3,door,the).
nmod:at(3,waiting,door).
sat(3,wolf,day_waiting_at_door).
root(4,ROOT,heard).
case(4,evening,in).
det(4,evening,the).
nmod:in(4,heard,evening).
nsubj(4,heard,he).
det(4,woman,the).
amod(4,woman,same).
dobj(4,heard,woman).
dep(4,heard,fondling).
nmod:poss(4,child,her).
dobj(4,fondling,child).
cc(4,fondling,and).
dep(4,heard,saying).
conj:and(4,fondling,saying).
heard(4,he,same_woman).
heard(4,he,woman).
heard_woman_in(4,he,evening).
fondling(4,he,her_child).
root(5,ROOT,quiet).
nsubj(5,quiet,you).
cop(5,quiet,are).
advmod(5,quiet,now).
cc(5,quiet,and).
mark(5,come,if).
det(5,wolf,the).
nsubj(5,come,wolf).
aux(5,come,should).
advcl:if(5,kill,come).
nsubj(5,kill,we).
aux(5,kill,will).
conj:and(5,quiet,kill).
dobj(5,kill,him).
are(5,you,quiet_now).
are(5,you,quiet).
will_kill(5,we,him).
root(6,ROOT,hearing).
det(6,hearing,the).
compound(6,hearing,wolf).
det(6,words,these).
nsubj(6,went,words).
acl:relcl(6,hearing,went).
dobj(6,went,home).
acl(6,home,gasping).
case(6,cold,with).
nmod:with(6,gasping,cold).
cc(6,cold,and).
nmod:with(6,gasping,hunger).
conj:and(6,cold,hunger).
went(6,words,home).
went(6,words,home_gasping).
went(6,words,home_gasping_with_cold).
root(7,ROOT,reached).
advmod(7,reached,when).
nsubj(7,reached,he).
nmod:poss(7,wolf,his).
compound(7,wolf,den).
compound(7,wolf,mistress).
nsubj(7,inquired,wolf).
ccomp(7,reached,inquired).
case(7,him,of).
nmod:of(7,inquired,him).
advmod(7,returned,why).
nsubj(7,returned,he).
advcl(7,inquired,returned).
xcomp(7,returned,wearied).
cc(7,wearied,and).
xcomp(7,returned,supperless).
conj:and(7,wearied,supperless).
advmod(7,contrary,so).
advmod(7,returned,contrary).
case(7,wont,to).
nmod:poss(7,wont,his).
nmod:to(7,returned,wont).
returned(7,he,wearied).
returned_to(7,he,his_wont).
returned_contrary_to(7,he,his_wont).
returned_contrary(7,he,wearied).
inquired_of(7,his_den_mistress_wolf,him).
returned_so_contrary(7,he,wearied).
returned_so_contrary_to(7,he,his_wont).
root(8,ROOT,replied).
nsubj(8,replied,he).
root(9,ROOT,why).
dep(9,why,forsooth).
root(10,ROOT,use).
nsubj(10,gave,i).
acl:relcl(10,use,gave).
dobj(10,gave,credence).
case(10,words,to).
det(10,words,the).
nmod:to(10,gave,words).
case(10,woman,of).
det(10,woman,a).
nmod:of(10,words,woman).
gave(10,i,credence).
gave_credence_to(10,i,words_of_woman).
gave_credence_to(10,i,words).
