%% a horse ox and dog driven to great straits by the cold sought shelter and protection from man.
% dependencies.
root(0,root,drive).
det(0,ox,a).
compound(0,ox,horse).
nsubj(0,drive,ox).
cc(0,ox,and).
conj:and(0,ox,dog).
nsubj(0,drive,dog).
case(0,strait,to).
amod(0,strait,great).
nmod:to(0,drive,strait).
case(0,cold,by).
det(0,cold,the).
nmod:by(0,drive,cold).
acl(0,cold,seek).
dobj(0,seek,shelter).
cc(0,shelter,and).
dobj(0,seek,protection).
conj:and(0,shelter,protection).
case(0,man,from).
nmod:from(0,seek,man).
% relations.
aos(0,drive_to,dog,strait).
aos(0,drive_by,dog,cold).
aos(0,drive_to,horse_ox,great_strait).
aos(0,drive_to,horse_ox,strait).
aos(0,drive_to,dog,great_strait).
aos(0,drive_by,horse_ox,cold).
%% he received them kindly lighted a fire and warmed them.
% dependencies.
root(1,root,receive).
nsubj(1,receive,he).
nsubj(1,light,they).
nsubj(1,warm,they).
advmod(1,light,kindly).
ccomp(1,receive,light).
det(1,fire,a).
dobj(1,light,fire).
cc(1,light,and).
ccomp(1,receive,warm).
conj:and(1,light,warm).
dobj(1,warm,they).
% relations.
aos(1,warm,they,they).
aos(1,kindly_light,they,fire).
aos(1,light,they,fire).
%% he let the horse make free with his oats gave the ox an abundance of hay and fed the dog with meat from his own table.
% dependencies.
root(2,root,let).
nsubj(2,let,he).
det(2,horse,the).
nsubj(2,make,horse).
ccomp(2,let,make).
xcomp(2,make,free).
mark(2,give,with).
nmod:poss(2,oats,he).
nsubj(2,give,oats).
nsubj(2,feed,oats).
advcl:with(2,make,give).
det(2,ox,the).
iobj(2,give,ox).
det(2,abundance,a).
dobj(2,give,abundance).
case(2,hay,of).
nmod:of(2,abundance,hay).
cc(2,give,and).
advcl:with(2,make,feed).
conj:and(2,give,feed).
det(2,dog,the).
dobj(2,feed,dog).
case(2,meat,with).
nmod:with(2,dog,meat).
case(2,table,from).
nmod:poss(2,table,he).
amod(2,table,own).
nmod:from(2,feed,table).
% relations.
aos(2,give,he_oats,abundance).
aos(2,feed_dog_from,he_oats,he_own_table).
aos(2,feed,he_oats,dog).
aos(2,is_with,dog,meat).
aos(2,give,he_oats,ox).
aos(2,feed_dog_from,he_oats,he_table).
aos(2,give,he_oats,abundance_of_hay).
aos(2,feed,he_oats,dog_with_meat).
aos(2,make,horse,free).
aos(2,abundance_of,he_oats,hay).
%% grateful for these favors the animals determined to repay him to the best of their ability.
% dependencies.
root(3,root,grateful).
mark(3,favor,for).
nsubj(3,favor,these).
ccomp(3,grateful,favor).
det(3,animal,the).
nsubj(3,determine,animal).
nsubj:xsubj(3,repay,animal).
ccomp(3,favor,determine).
mark(3,repay,to).
xcomp(3,determine,repay).
dobj(3,repay,he).
case(3,best,to).
det(3,best,the).
nmod:to(3,repay,best).
case(3,ability,of).
nmod:poss(3,ability,they).
nmod:of(3,best,ability).
% relations.
aos(3,repay,animal,he).
%% for this purpose they divided the term of his life between them and each endowed one portion of it with the qualities which chiefly characterized himself.
% dependencies.
root(4,root,divide).
case(4,purpose,for).
det(4,purpose,this).
nmod:for(4,divide,purpose).
nsubj(4,divide,they).
det(4,term,the).
dobj(4,divide,term).
case(4,life,of).
nmod:poss(4,life,he).
nmod:of(4,term,life).
case(4,they,between).
nmod:between(4,life,they).
cc(4,life,and).
det(4,portion,each).
amod(4,portion,endowed).
nmod:tmod(4,endowed,one).
nmod:of(4,term,portion).
conj:and(4,life,portion).
case(4,it,of).
nmod:of(4,portion,it).
case(4,quality,with).
det(4,quality,the).
nmod:with(4,divide,quality).
nsubj(4,characterize,quality).
ref(4,quality,which).
advmod(4,characterize,chiefly).
acl:relcl(4,quality,characterize).
dobj(4,characterize,himself).
% relations.
aos(4,divide_term_for,they,purpose).
aos(4,divide,they,term).
aos(4,divide_for,they,purpose).
%% the horse chose his earliest years and gave them his own attributes hence every man is in his youth impetuous headstrong and obstinate in maintaining his own opinion.
% dependencies.
root(5,root,choose).
det(5,horse,the).
nsubj(5,choose,horse).
nsubj(5,give,horse).
nmod:poss(5,year,he).
amod(5,year,earliest).
nmod:tmod(5,choose,year).
cc(5,choose,and).
conj:and(5,choose,give).
iobj(5,give,they).
nmod:poss(5,attribute,he).
amod(5,attribute,own).
dobj(5,give,attribute).
advmod(5,man,hence).
det(5,man,every).
dobj(5,choose,man).
cop(5,headstrong,be).
case(5,headstrong,in).
nmod:poss(5,headstrong,he).
compound(5,headstrong,youth).
amod(5,headstrong,impetuous).
acl:relcl(5,man,headstrong).
cc(5,headstrong,and).
acl:relcl(5,man,obstinate).
conj:and(5,headstrong,obstinate).
mark(5,maintain,in).
advcl:in(5,headstrong,maintain).
nmod:poss(5,opinion,he).
amod(5,opinion,own).
dobj(5,maintain,opinion).
% relations.
aos(5,give,horse,they).
aos(5,give,horse,he_own_attribute).
aos(5,give,horse,he_attribute).
%% the ox took under his patronage the next term of life and therefore man in his middle age is fond of work devoted to labor and resolute to amass wealth and to husband his resources.
% dependencies.
root(6,root,fond).
det(6,ox,the).
nsubj(6,take,ox).
dep(6,fond,take).
case(6,man,under).
nmod:poss(6,man,he).
compound(6,man,patronage).
det(6,term,the).
amod(6,term,next).
compound(6,man,term).
case(6,life,of).
nmod:of(6,term,life).
cc(6,term,and).
advmod(6,term,therefore).
nmod:under(6,take,man).
case(6,age,in).
nmod:poss(6,age,he).
amod(6,age,middle).
nmod:in(6,take,age).
cop(6,fond,be).
conj:and(6,fond,fond).
case(6,work,of).
nmod:of(6,fond,work).
acl(6,work,devote).
case(6,wealth,to).
compound(6,wealth,labor).
cc(6,labor,and).
conj:and(6,labor,resolute).
compound(6,wealth,resolute).
mark(6,amass,to).
xcomp(6,resolute,amass).
nmod:to(6,devote,wealth).
cc(6,fond,and).
case(6,husband,to).
nmod:to(6,fond,husband).
nmod:poss(6,resource,he).
nsubj(6,fond,resource).
nsubj(6,fond,resource).
% relations.
aos(6,take_under,ox,he_patronage_term_therefore_man).
aos(6,be_fond_of,he_resource,work_devote_to_labor_wealth).
aos(6,take_under,ox,he_patronage_next_term_of_life_man).
aos(6,take_in,ox,he_middle_age).
aos(6,take_in,ox,he_age).
aos(6,be_fond_of,he_resource,work_devote).
aos(6,be,he_resource,fond_of_work_to_husband).
aos(6,take_under,ox,he_patronage_term_of_life_therefore_man).
aos(6,take_under,ox,he_patronage_term_man).
aos(6,be,he_resource,fond_of_work_devote_to_labor_wealth_to_husband).
aos(6,be,he_resource,fond_of_work_devote_to_husband).
aos(6,take_under,ox,he_patronage_term_of_life_man).
aos(6,take_under,ox,he_patronage_next_term_therefore_man).
aos(6,be_fond_to,he_resource,husband).
aos(6,take_under,ox,he_patronage_next_term_man).
aos(6,be_fond_of,he_resource,work).
aos(6,take_under,ox,he_patronage_next_term_of_life_therefore_man).
aos(6,be,he_resource,fond).
%% the end of life was reserved for the dog wherefore the old man is often snappish irritable hard to please and selfish tolerant only of his own household but averse to strangers and to all who do not administer to his comfort or to his necessities.
% dependencies.
root(7,root,reserve).
det(7,end,the).
nsubjpass(7,reserve,end).
nsubjpass(7,reserve,end).
nsubjpass(7,reserve,end).
case(7,life,of).
nmod:of(7,end,life).
auxpass(7,reserve,be).
conj:and(7,reserve,reserve).
conj:and(7,reserve,reserve).
case(7,dog,for).
det(7,dog,the).
nmod:for(7,reserve,dog).
acl:relcl(7,dog,wherefore).
det(7,man,the).
amod(7,man,old).
nsubj(7,hard,man).
nsubj:xsubj(7,please,man).
cop(7,hard,be).
advmod(7,hard,often).
amod(7,irritable,snappish).
dep(7,often,irritable).
ccomp(7,wherefore,hard).
mark(7,please,to).
xcomp(7,hard,please).
cc(7,reserve,and).
amod(7,stranger,selfish).
compound(7,stranger,tolerant).
advmod(7,tolerant,only).
case(7,household,of).
nmod:poss(7,household,he).
amod(7,household,own).
nmod:of(7,tolerant,household).
cc(7,tolerant,but).
conj:but(7,tolerant,averse).
compound(7,stranger,averse).
dep(7,averse,to).
conj(7,dog,stranger).
cc(7,reserve,and).
case(7,all,to).
nmod:to(7,reserve,all).
nsubj(7,administer,all).
nsubj(7,administer,all).
ref(7,all,who).
aux(7,administer,do).
neg(7,administer,not).
acl:relcl(7,all,administer).
acl:relcl(7,all,administer).
conj:or(7,administer,administer).
case(7,comfort,to).
nmod:poss(7,comfort,he).
nmod:to(7,administer,comfort).
cc(7,administer,or).
case(7,necessity,to).
nmod:poss(7,necessity,he).
nmod:to(7,administer,necessity).
% relations.
aos(7,be,old_man,often_hard).
aos(7,be,old_man,hard).
aos(7,be,man,often_hard).
aos(7,be,man,hard).
