root(0,ROOT,came).
det(0,man,a).
nsubj(0,came,man).
nsubj(0,begged,man).
case(0,wood,into).
det(0,wood,a).
nmod:into(0,came,wood).
nummod(0,day,one).
nmod:tmod(0,wood,day).
case(0,axe,with).
det(0,axe,an).
nmod:with(0,came,axe).
case(0,hand,in).
nmod:poss(0,hand,his).
nmod:in(0,axe,hand).
cc(0,came,and).
conj:and(0,came,begged).
det:predet(0,trees,all).
det(0,trees,the).
dobj(0,begged,trees).
nsubj:xsubj(0,give,trees).
mark(0,give,to).
xcomp(0,begged,give).
iobj(0,give,him).
det(0,branch,a).
amod(0,branch,small).
dobj(0,give,branch).
dobj(0,wanted,branch).
ref(0,branch,which).
nsubj(0,wanted,he).
acl:relcl(0,branch,wanted).
case(0,purpose,for).
det(0,purpose,a).
amod(0,purpose,particular).
nmod:for(0,wanted,purpose).
wanted_for(0,he,purpose).
came_into(0,man,wood).
is_in(0,axe,his_hand).
came_into(0,man,wood_one_day).
give(0,trees,him).
begged(0,man,trees).
came_with(0,man,axe).
came_with(0,man,axe_in_his_hand).
wanted_for(0,he,particular_purpose).
root(1,ROOT,good-natured).
det(1,trees,the).
nsubj(1,good-natured,trees).
nsubj(1,gave,trees).
cop(1,good-natured,were).
cc(1,good-natured,and).
conj:and(1,good-natured,gave).
iobj(1,gave,him).
dobj(1,gave,one).
case(1,branches,of).
nmod:poss(1,branches,their).
nmod:of(1,one,branches).
gave(1,trees,him).
gave(1,trees,one_of_their_branches).
were(1,trees,good-natured).
gave(1,trees,one_their_branches).
root(2,ROOT,fix).
dobj(2,fix,what).
aux(2,fix,did).
det(2,man,the).
nsubj(2,fix,man).
nsubj(2,set,man).
nsubj:xsubj(2,work,man).
aux(2,fix,do).
cc(2,fix,but).
dobj(2,fix,it).
case(2,head,into).
det(2,head,the).
amod(2,head,axe).
nmod:into(2,fix,head).
cc(2,fix,and).
advmod(2,set,soon).
conj:and(2,fix,set).
mark(2,work,to).
xcomp(2,set,work).
xcomp(2,work,cutting).
compound:prt(2,cutting,down).
dobj(2,cutting,tree).
case(2,tree,after).
nmod:after(2,cutting,tree).
soon_set(2,man,work).
set(2,man,work).
root(3,ROOT,saw).
advmod(3,trees,then).
det(3,trees,the).
nsubj(3,saw,trees).
advmod(3,giving,how).
dep(3,how,foolish).
nsubj(3,giving,they).
aux(3,giving,had).
cop(3,giving,been).
mark(3,giving,in).
ccomp(3,saw,giving).
nmod:poss(3,enemy,their).
dep(3,giving,enemy).
det(3,means,the).
dobj(3,giving,means).
mark(3,destroying,of).
acl:of(3,means,destroying).
dobj(3,destroying,themselves).
