root(0,ROOT,waged).
det(0,weasels,the).
nsubj(0,waged,weasels).
cc(0,weasels,and).
det(0,mice,the).
conj:and(0,weasels,mice).
nsubj(0,waged,mice).
det(0,war,a).
amod(0,war,perpetual).
dobj(0,waged,war).
case(0,other,with).
det(0,other,each).
nmod:with(0,waged,other).
nmod:in(0,shed,other).
case(0,which,in).
ref(0,other,which).
amod(0,blood,much).
nsubjpass(0,shed,blood).
auxpass(0,shed,was).
acl:relcl(0,other,shed).
waged(0,mice,perpetual_war).
waged(0,mice,war).
waged(0,weasels,perpetual_war).
waged(0,weasels,war).
was(0,blood,shed).
was(0,much_blood,shed).
root(1,ROOT,victors).
det(1,weasels,the).
nsubj(1,victors,weasels).
cop(1,victors,were).
advmod(1,victors,always).
det(1,victors,the).
were(1,weasels,victors).
were(1,weasels,always_victors).
root(2,ROOT,thought).
det(2,mice,the).
nsubj(2,thought,mice).
mark(2,defeats,that).
det(2,cause,the).
nsubj(2,defeats,cause).
case(2,frequent,of).
nmod:poss(2,frequent,their).
nmod:of(2,cause,frequent).
ccomp(2,thought,defeats).
ccomp(2,defeats,was).
mark(2,had,that).
nsubj(2,had,they).
ccomp(2,was,had).
neg(2,leaders,no).
dobj(2,had,leaders).
acl:relcl(2,leaders,set).
advmod(2,set,apart).
case(2,army,from).
det(2,army,the).
amod(2,army,general).
nmod:from(2,set,army).
mark(2,command,to).
xcomp(2,set,command).
dobj(2,command,them).
cc(2,was,and).
mark(2,exposed,that).
nsubjpass(2,exposed,they).
auxpass(2,exposed,were).
ccomp(2,defeats,exposed).
conj:and(2,was,exposed).
case(2,dangers,to).
nmod:to(2,exposed,dangers).
case(2,lack,from).
nmod:from(2,exposed,lack).
case(2,discipline,of).
nmod:of(2,lack,discipline).
root(3,ROOT,chose).
nsubj(3,chose,they).
advmod(3,chose,therefore).
case(3,mice,as).
compound(3,mice,leaders).
nmod:as(3,chose,mice).
nsubj(3,renowned,mice).
ref(3,mice,that).
cop(3,renowned,were).
advmod(3,renowned,most).
acl:relcl(3,mice,renowned).
case(3,strength,for).
nmod:poss(3,strength,their).
compound(3,strength,family).
compound(3,strength,descent).
nmod:for(3,renowned,strength).
cc(3,strength,and).
nmod:for(3,renowned,counsel).
conj:and(3,strength,counsel).
cc(3,strength,as).
mwe(3,as,well).
mwe(3,as,as).
nmod:for(3,renowned,those).
conj:and(3,strength,those).
advmod(3,noted,most).
acl(3,those,noted).
case(3,courage,for).
nmod:poss(3,courage,their).
nmod:for(3,noted,courage).
case(3,fight,in).
det(3,fight,the).
nmod:in(3,courage,fight).
mark(3,marshaled,so).
mwe(3,so,that).
nsubjpass(3,marshaled,they).
nsubjpass(3,formed,they).
aux(3,marshaled,might).
auxpass(3,marshaled,be).
advmod(3,marshaled,better).
advcl:so_that(3,renowned,marshaled).
case(3,array,in).
compound(3,array,battle).
nmod:in(3,marshaled,array).
cc(3,marshaled,and).
advcl:so_that(3,renowned,formed).
conj:and(3,marshaled,formed).
case(3,regiments,into).
compound(3,regiments,troops).
nmod:into(3,formed,regiments).
cc(3,regiments,and).
nmod:into(3,formed,battalions).
conj:and(3,regiments,battalions).
is_in(3,their_courage,fight).
most_noted_for(3,those,their_courage_fight).
might(3,they,might_better_marshaled_in_battle_array).
noted_for(3,those,their_courage_fight).
might(3,they,might_marshaled).
noted_for(3,those,their_courage).
might(3,they,might_better_marshaled).
most_noted_for(3,those,their_courage).
might(3,they,might_marshaled_in_battle_array).
formed_into(3,they,troops_regiments).
root(4,ROOT,done).
advmod(4,done,when).
det:predet(4,this,all).
nsubjpass(4,done,this).
auxpass(4,done,was).
cc(4,done,and).
det(4,army,the).
nsubj(4,disciplined,army).
conj:and(4,done,disciplined).
cc(4,disciplined,and).
nsubj(4,herald,the).
conj:and(4,done,herald).
conj:and(4,disciplined,herald).
nsubj(4,had,mouse).
ccomp(4,herald,had).
advmod(4,proclaimed,duly).
amod(4,war,proclaimed).
dobj(4,had,war).
mark(4,challenging,by).
advcl:by(4,had,challenging).
det(4,weasels,the).
dobj(4,challenging,weasels).
mark(4,conspicuous,weasels).
det(4,generals,the).
advmod(4,chosen,newly).
amod(4,generals,chosen).
nsubj(4,bound,generals).
acl:relcl(4,weasels,bound).
nmod:poss(4,heads,their).
dobj(4,bound,heads).
case(4,straws,with).
nmod:with(4,bound,straws).
ref(4,weasels,that).
nsubj(4,conspicuous,they).
aux(4,conspicuous,might).
cop(4,conspicuous,be).
advmod(4,conspicuous,more).
ccomp(4,bound,conspicuous).
case(4,troops,to).
det:predet(4,troops,all).
nmod:poss(4,troops,their).
nmod:to(4,conspicuous,troops).
be_more_conspicuous_to(4,they,troops).
bound_with(4,generals,straws).
had(4,mouse,war).
bound(4,chosen_generals,their_heads).
was(4,this,done).
be_conspicuous_to(4,they,their_troops).
bound_with(4,chosen_generals,straws).
be_more_conspicuous_to(4,they,their_troops).
had(4,mouse,proclaimed_war).
was(4,this,when_done).
had(4,mouse,duly_proclaimed_war).
be_conspicuous_to(4,they,troops).
bound(4,generals,their_heads).
root(5,ROOT,had).
advmod(5,had,scarcely).
det(5,battle,the).
dobj(5,had,battle).
acl(5,battle,begun).
advmod(5,overwhelmed,when).
det(5,rout,a).
amod(5,rout,great).
nsubj(5,overwhelmed,rout).
advcl(5,begun,overwhelmed).
det(5,mice,the).
dobj(5,overwhelmed,mice).
nsubj(5,scampered,mice).
ref(5,mice,who).
acl:relcl(5,mice,scampered).
compound:prt(5,scampered,off).
case(5,fast,as).
advmod(5,scampered,fast).
mark(5,could,as).
nsubj(5,could,they).
dep(5,had,could).
case(5,holes,to).
nmod:poss(5,holes,their).
nmod:to(5,could,holes).
root(6,ROOT,captured).
det(6,generals,the).
nsubjpass(6,captured,generals).
nsubjpass(6,eaten,generals).
neg(6,able,not).
cop(6,able,being).
acl(6,generals,able).
mark(6,get,to).
xcomp(6,able,get).
case(6,ornaments,in).
case(6,ornaments,on).
mwe(6,on,account).
mwe(6,on,of).
det(6,ornaments,the).
nmod:on_account_of(6,get,ornaments).
case(6,heads,on).
nmod:poss(6,heads,their).
nmod:on(6,ornaments,heads).
auxpass(6,captured,were).
advmod(6,captured,all).
cc(6,captured,and).
conj:and(6,captured,eaten).
case(6,weasels,by).
det(6,weasels,the).
nmod:agent(6,captured,weasels).
