root(0,ROOT,manslayer).
det(0,manslayer,the).
det(0,man,a).
nsubj(0,committed,man).
nsubjpass(0,pursued,man).
acl:relcl(0,manslayer,committed).
det(0,murder,a).
dobj(0,committed,murder).
cc(0,committed,and).
auxpass(0,pursued,was).
acl:relcl(0,manslayer,pursued).
conj:and(0,committed,pursued).
case(0,relations,by).
det(0,relations,the).
nmod:agent(0,pursued,relations).
case(0,man,of).
det(0,man,the).
nmod:of(0,manslayer,man).
dobj(0,murdered,man).
ref(0,man,whom).
nsubj(0,murdered,he).
acl:relcl(0,man,murdered).
was(0,man,pursued).
committed(0,man,murder).
was_pursued_by(0,man,relations).
root(1,ROOT,reaching).
mark(1,reaching,on).
nsubj(1,reaching,his).
det(1,river,the).
dobj(1,reaching,river).
mark(1,saw,nile).
nsubj(1,saw,he).
acl:nile(1,river,saw).
det(1,lion,a).
dobj(1,saw,lion).
case(1,bank,on).
nmod:poss(1,bank,its).
nmod:on(1,saw,bank).
cc(1,saw,and).
cop(1,afraid,being).
advmod(1,afraid,fearfully).
csubj(1,climbed,afraid).
acl:nile(1,river,climbed).
conj:and(1,saw,climbed).
case(1,tree,up).
det(1,tree,a).
advmod(1,climbed,tree).
root(2,ROOT,found).
nsubj(2,found,he).
det(2,serpent,a).
dobj(2,found,serpent).
case(2,branches,in).
det(2,branches,the).
amod(2,branches,upper).
nmod:in(2,serpent,branches).
case(2,tree,of).
det(2,tree,the).
nmod:of(2,branches,tree).
cc(2,tree,and).
advmod(2,alarmed,again).
cop(2,alarmed,being).
advmod(2,alarmed,greatly).
nmod:of(2,branches,alarmed).
conj:and(2,tree,alarmed).
nsubj(2,threw,he).
ccomp(2,alarmed,threw).
dobj(2,threw,himself).
case(2,river,into).
det(2,river,the).
nmod:into(2,threw,river).
advmod(2,caught,where).
det(2,crocodile,a).
nsubj(2,caught,crocodile).
nsubj(2,ate,crocodile).
advcl(2,threw,caught).
dobj(2,caught,him).
cc(2,caught,and).
advcl(2,threw,ate).
conj:and(2,caught,ate).
dobj(2,ate,him).
found(2,he,serpent_in_branches).
found(2,he,serpent_in_upper_branches_of_tree).
found(2,he,serpent_in_upper_branches).
is_in(2,serpent,upper_branches_of_tree).
found(2,he,serpent).
found(2,he,serpent_in_branches_of_tree).
root(3,ROOT,earth).
dep(3,earth,thus).
det(3,earth,the).
det(3,air,the).
nsubj(3,refused,air).
cc(3,air,and).
det(3,water,the).
conj:and(3,air,water).
nsubj(3,refused,water).
advmod(3,refused,alike).
ccomp(3,earth,refused).
dobj(3,refused,shelter).
case(3,murderer,to).
det(3,murderer,a).
nmod:to(3,refused,murderer).
alike_refused_to(3,air,murderer).
refused_to(3,water,murderer).
refused_to(3,air,murderer).
refused_shelter_to(3,air,murderer).
alike_refused_shelter_to(3,water,murderer).
alike_refused(3,air,shelter).
alike_refused_to(3,water,murderer).
alike_refused_shelter_to(3,air,murderer).
alike_refused(3,water,shelter).
refused(3,air,shelter).
refused(3,water,shelter).
refused_shelter_to(3,water,murderer).
