root(0,ROOT,day).
nummod(0,day,one).
mark(0,labour,day).
det(0,countrymen,the).
nsubj(0,noticed,countrymen).
acl:relcl(0,day,noticed).
ref(0,day,that).
det(0,mountains,the).
nsubj(0,labour,mountains).
cop(0,labour,were).
case(0,labour,in).
ccomp(0,noticed,labour).
were_in(0,mountains,labour).
root(1,ROOT,came).
nsubj(1,came,smoke).
case(1,summits,out).
mwe(1,out,of).
nmod:poss(1,summits,their).
nmod:out_of(1,came,summits).
det(1,earth,the).
nsubj(1,quaking,earth).
aux(1,quaking,was).
ccomp(1,came,quaking).
case(1,feet,at).
nmod:poss(1,feet,their).
nmod:at(1,quaking,feet).
nsubj(1,crashing,trees).
aux(1,crashing,were).
acl:relcl(1,feet,crashing).
cc(1,crashing,and).
amod(1,rocks,huge).
nsubj(1,tumbling,rocks).
aux(1,tumbling,were).
acl:relcl(1,feet,tumbling).
conj:and(1,crashing,tumbling).
came_out_of(1,smoke,their_summits).
root(2,ROOT,felt).
nsubj(2,felt,they).
xcomp(2,felt,sure).
mark(2,going,that).
nsubj(2,going,something).
nsubj:xsubj(2,happen,something).
amod(2,something,horrible).
aux(2,going,was).
ccomp(2,felt,going).
mark(2,happen,to).
xcomp(2,going,happen).
going(2,something_horrible,happen).
going(2,something,happen).
felt(2,they,sure).
root(3,ROOT,gathered).
nsubj(3,gathered,they).
nsubj:xsubj(3,see,they).
advmod(3,gathered,all).
advmod(3,gathered,together).
case(3,place,in).
nummod(3,place,one).
nmod:in(3,gathered,place).
mark(3,see,to).
xcomp(3,gathered,see).
dobj(3,be,what).
amod(3,thing,terrible).
nsubj(3,be,thing).
dep(3,thing,this).
aux(3,be,could).
ccomp(3,see,be).
gathered(3,they,see).
gathered_together(3,they,see).
all_gathered_in(3,they,one_place).
gathered_in(3,they,one_place).
gathered_together_in(3,they,one_place).
all_gathered_together_in(3,they,one_place).
all_gathered_together(3,they,see).
all_gathered(3,they,see).
root(4,ROOT,waited).
nsubj(4,waited,they).
cc(4,waited,and).
nsubj(4,waited,they).
nsubj(4,came,they).
conj:and(4,waited,waited).
cc(4,waited,but).
advmod(4,waited,nothing).
conj:and(4,waited,came).
conj:but(4,waited,came).
root(5,ROOT,last).
dep(5,last,at).
expl(5,was,there).
acl:relcl(5,last,was).
det(5,earthquake,a).
advmod(5,violent,still).
advmod(5,violent,more).
amod(5,earthquake,violent).
nsubj(5,was,earthquake).
cc(5,was,and).
det(5,gap,a).
amod(5,gap,huge).
nsubj(5,appeared,gap).
acl:relcl(5,last,appeared).
conj:and(5,was,appeared).
case(5,side,in).
det(5,side,the).
nmod:in(5,appeared,side).
case(5,mountains,of).
det(5,mountains,the).
nmod:of(5,side,mountains).
appeared_in(5,gap,side).
appeared_in(5,huge_gap,side_of_mountains).
appeared_in(5,huge_gap,side).
appeared_in(5,gap,side_of_mountains).
root(6,ROOT,fell).
nsubj(6,fell,they).
nsubj(6,waited,they).
advmod(6,fell,all).
compound:prt(6,fell,down).
case(6,knees,upon).
nmod:poss(6,knees,their).
nmod:upon(6,fell,knees).
cc(6,fell,and).
conj:and(6,fell,waited).
fell_down_upon(6,they,their_knees).
all_fell_down_upon(6,they,their_knees).
