root(0,ROOT,gave).
det(0,beasts,the).
nsubj(0,gave,beasts).
case(0,forest,of).
det(0,forest,the).
nmod:of(0,beasts,forest).
det(0,entertainment,a).
amod(0,entertainment,splendid).
dobj(0,gave,entertainment).
nmod:at(0,stood,entertainment).
case(0,which,at).
ref(0,entertainment,which).
det(0,monkey,the).
nsubj(0,stood,monkey).
nsubj(0,danced,monkey).
acl:relcl(0,entertainment,stood).
advmod(0,stood,up).
cc(0,stood,and).
acl:relcl(0,entertainment,danced).
conj:and(0,stood,danced).
root(1,ROOT,having).
advmod(1,delighted,vastly).
xcomp(1,having,delighted).
det(1,assembly,the).
dep(1,delighted,assembly).
nsubj(1,sat,he).
acl:relcl(1,assembly,sat).
advmod(1,sat,down).
case(1,applause,amidst).
amod(1,applause,universal).
nmod:amidst(1,sat,applause).
sat_down_amidst(1,he,universal_applause).
sat_amidst(1,he,universal_applause).
sat_down_amidst(1,he,applause).
sat_amidst(1,he,applause).
root(2,ROOT,praises).
det(2,camel,the).
nsubj(2,praises,camel).
amod(2,camel,envious).
case(2,the,of).
nmod:of(2,camel,the).
xcomp(2,praises,bestowed).
case(2,monkey,on).
det(2,monkey,the).
nmod:on(2,bestowed,monkey).
cc(2,bestowed,and).
xcomp(2,praises,desiring).
conj:and(2,bestowed,desiring).
mark(2,divert,to).
xcomp(2,desiring,divert).
case(2,himself,to).
nmod:to(2,divert,himself).
det(2,favor,the).
nsubj(2,proposed,favor).
nsubj:xsubj(2,stand,favor).
case(2,guests,of).
det(2,guests,the).
nmod:of(2,favor,guests).
ccomp(2,praises,proposed).
mark(2,stand,to).
xcomp(2,proposed,stand).
compound:prt(2,stand,up).
case(2,turn,in).
nmod:poss(2,turn,his).
nmod:in(2,stand,turn).
cc(2,turn,and).
nmod:in(2,stand,dance).
conj:and(2,turn,dance).
case(2,amusement,for).
nmod:poss(2,amusement,their).
nmod:for(2,turn,amusement).
praises(2,camel_envious,bestowed).
praises(2,camel,bestowed_on_monkey).
bestowed_on(2,camel_envious,monkey).
praises(2,camel_envious,bestowed_on_monkey).
bestowed_on(2,camel,monkey).
stand_up_in(2,favor,his_turn).
praises(2,camel,bestowed).
stand_up_in(2,favor,his_turn_for_their_amusement).
root(3,ROOT,moved).
nsubj(3,moved,he).
nsubj(3,drove,he).
advmod(3,moved,about).
case(3,manner,in).
advmod(3,ridiculous,so).
advmod(3,ridiculous,utterly).
amod(3,manner,ridiculous).
det(3,manner,a).
nmod:in(3,about,manner).
mark(3,set,that).
det(3,beasts,the).
nsubj(3,set,beasts).
case(3,fit,in).
det(3,fit,a).
nmod:in(3,beasts,fit).
case(3,indignation,of).
nmod:of(3,fit,indignation).
ccomp(3,moved,set).
case(3,him,upon).
nmod:upon(3,set,him).
case(3,clubs,with).
nmod:with(3,set,clubs).
cc(3,moved,and).
conj:and(3,moved,drove).
dobj(3,drove,him).
compound:prt(3,drove,out).
case(3,assembly,of).
det(3,assembly,the).
nmod:of(3,drove,assembly).
is_in(3,beasts,fit_of_indignation).
drove_out(3,he,him).
set_upon(3,beasts,him).
set_with(3,beasts,clubs).
