root(0,ROOT,trudging).
nummod(0,mules,two).
nsubj(0,trudging,mules).
amod(0,mules,well-laden).
case(0,packs,with).
nmod:with(0,mules,packs).
aux(0,trudging,were).
advmod(0,trudging,along).
is_with(0,two_mules_well-laden,packs).
root(1,ROOT,carried).
nsubj(1,carried,one).
nsubj(1,filled,panniers).
ccomp(1,carried,filled).
case(1,money,with).
nmod:with(1,filled,money).
det(1,sacks,the).
amod(1,sacks,other).
dobj(1,filled,sacks).
acl(1,sacks,weighted).
case(1,grain,with).
nmod:with(1,weighted,grain).
weighted_with(1,sacks,grain).
filled(1,panniers,other_sacks).
filled(1,panniers,other_sacks_weighted).
weighted_with(1,other_sacks,grain).
filled(1,panniers,sacks_weighted_with_grain).
filled(1,panniers,sacks_weighted).
filled_sacks_with(1,panniers,money).
filled(1,panniers,sacks).
filled(1,panniers,other_sacks_weighted_with_grain).
root(2,ROOT,walked).
det(2,mule,the).
nsubj(2,walked,mule).
acl(2,mule,carrying).
det(2,treasure,the).
dobj(2,carrying,treasure).
case(2,head,with).
nmod:with(2,walked,head).
ccomp(2,walked,erect).
mark(2,fastened,as).
mark(2,conscious,if).
csubj(2,fastened,conscious).
case(2,value,of).
det(2,value,the).
nmod:of(2,conscious,value).
case(2,burden,of).
nmod:poss(2,burden,his).
nmod:of(2,value,burden).
cc(2,conscious,and).
conj:and(2,conscious,tossed).
csubj(2,fastened,tossed).
compound:prt(2,tossed,up).
cc(2,up,and).
dep(2,up,down).
det(2,bells,the).
amod(2,bells,clear-toned).
dobj(2,tossed,bells).
advcl:as(2,erect,fastened).
case(2,neck,to).
nmod:poss(2,neck,his).
nmod:to(2,fastened,neck).
walked_with(2,mule,head).
root(3,ROOT,followed).
nmod:poss(3,companion,his).
nsubj(3,followed,companion).
case(3,step,with).
amod(3,step,quiet).
cc(3,quiet,and).
conj:and(3,quiet,easy).
amod(3,step,easy).
nmod:with(3,followed,step).
followed_with(3,his_companion,quiet_step).
followed_with(3,his_companion,step).
root(4,ROOT,rushed).
det:qmod(4,robbers,all).
mwe(4,all,of).
det(4,robbers,a).
amod(4,robbers,sudden).
nsubj(4,rushed,robbers).
nsubj(4,rushed,robbers).
conj:and(4,rushed,rushed).
case(4,them,upon).
nmod:upon(4,rushed,them).
case(4,hiding-places,from).
nmod:poss(4,hiding-places,their).
nmod:from(4,rushed,hiding-places).
cc(4,rushed,and).
case(4,scuffle,in).
det(4,scuffle,the).
nmod:in(4,rushed,scuffle).
case(4,owners,with).
nmod:poss(4,owners,their).
nmod:with(4,scuffle,owners).
acl(4,owners,wounded).
case(4,sword,with).
det(4,sword,a).
nmod:with(4,wounded,sword).
det(4,mule,the).
dobj(4,wounded,mule).
acl(4,mule,carrying).
det(4,treasure,the).
dobj(4,carrying,treasure).
dobj(4,seized,treasure).
ref(4,treasure,which).
nsubj(4,seized,they).
advmod(4,seized,greedily).
acl:relcl(4,treasure,seized).
mark(4,taking,while).
advcl:while(4,seized,taking).
neg(4,notice,no).
dobj(4,taking,notice).
case(4,grain,of).
det(4,grain,the).
nmod:of(4,notice,grain).
is_with(4,scuffle,their_owners_wounded).
root(5,ROOT,bewailed).
det(5,mule,the).
nsubjpass(5,robbed,mule).
nsubjpass(5,wounded,mule).
nsubj(5,bewailed,mule).
ref(5,mule,which).
aux(5,robbed,had).
auxpass(5,robbed,been).
acl:relcl(5,mule,robbed).
cc(5,robbed,and).
acl:relcl(5,mule,wounded).
conj:and(5,robbed,wounded).
nmod:poss(5,misfortunes,his).
dobj(5,bewailed,misfortunes).
root(6,ROOT,replied).
det(6,other,the).
nsubj(6,replied,other).
root(7,ROOT,glad).
nsubj(7,glad,i).
cop(7,glad,am).
advmod(7,glad,indeed).
mark(7,thought,that).
nsubjpass(7,thought,i).
auxpass(7,thought,was).
ccomp(7,glad,thought).
advmod(7,little,so).
advmod(7,thought,little).
mark(7,lost,of).
mark(7,lost,for).
nsubj(7,lost,i).
aux(7,lost,have).
advcl:for(7,little,lost).
dobj(7,lost,nothing).
cc(7,nothing,nor).
cop(7,i,am).
dobj(7,lost,i).
conj:nor(7,nothing,i).
acl(7,i,hurt).
case(7,wound,with).
det(7,wound,any).
nmod:with(7,hurt,wound).
am(7,i,glad).
was(7,i,thought_so_little).
was(7,i,thought_little).
was(7,i,thought).
am(7,i,indeed_glad).
