root(0,ROOT,took).
det(0,sailor,a).
nsubj(0,took,sailor).
acl(0,sailor,bound).
case(0,voyage,on).
det(0,voyage,a).
amod(0,voyage,long).
nmod:on(0,bound,voyage).
case(0,him,with).
nmod:with(0,took,him).
det(0,monkey,a).
dobj(0,took,monkey).
mark(0,amuse,to).
acl:to(0,monkey,amuse).
dobj(0,amuse,him).
mark(0,shipboard,while).
case(0,shipboard,on).
advcl:on(0,amuse,shipboard).
root(1,ROOT,sailed).
mark(1,sailed,as).
nsubj(1,sailed,he).
compound:prt(1,sailed,off).
det(1,coast,the).
dobj(1,sailed,coast).
nmod:in(1,wrecked,coast).
case(1,greece,of).
nmod:of(1,coast,greece).
det(1,tempest,a).
amod(1,tempest,violent).
nsubj(1,arose,tempest).
acl:relcl(1,coast,arose).
case(1,which,in).
ref(1,coast,which).
det(1,ship,the).
nsubjpass(1,wrecked,ship).
auxpass(1,wrecked,was).
dep(1,arose,wrecked).
cc(1,wrecked,and).
dep(1,monkey,he).
nmod:poss(1,monkey,his).
dep(1,arose,monkey).
conj:and(1,wrecked,monkey).
cc(1,arose,and).
det:predet(1,crew,all).
det(1,crew,the).
nsubjpass(1,obliged,crew).
nsubj:xsubj(1,swim,crew).
auxpass(1,obliged,were).
acl:relcl(1,coast,obliged).
conj:and(1,arose,obliged).
mark(1,swim,to).
xcomp(1,obliged,swim).
case(1,lives,for).
nmod:poss(1,lives,their).
nmod:for(1,swim,lives).
were_obliged(1,crew,swim_for_their_lives).
swim_for(1,crew,their_lives).
were(1,crew,obliged).
were_obliged(1,crew,swim).
root(2,ROOT,saw).
det(2,dolphin,a).
nsubj(2,saw,dolphin).
det(2,monkey,the).
nsubj(2,came,monkey).
nsubj(2,placed,monkey).
dep(2,monkey,contending).
case(2,waves,with).
det(2,waves,the).
nmod:with(2,contending,waves).
cc(2,contending,and).
dep(2,monkey,supposing).
conj:and(2,contending,supposing).
dobj(2,supposing,him).
nsubj:xsubj(2,man,him).
mark(2,man,to).
cop(2,man,be).
det(2,man,a).
xcomp(2,supposing,man).
punct(2,said,-LRB-).
dobj(2,befriend,whom).
nsubjpass(2,said,he).
nsubj:xsubj(2,befriend,he).
auxpass(2,said,is).
advmod(2,said,always).
dep(2,man,said).
mark(2,befriend,to).
xcomp(2,said,befriend).
punct(2,said,-RRB-).
ccomp(2,saw,came).
cc(2,came,and).
ccomp(2,saw,placed).
conj:and(2,came,placed).
dobj(2,placed,himself).
case(2,him,under).
nmod:under(2,placed,him).
mark(2,convey,to).
advcl:to(2,placed,convey).
dobj(2,convey,him).
case(2,back,on).
nmod:poss(2,back,his).
nmod:on(2,convey,back).
case(2,safety,in).
nmod:in(2,back,safety).
case(2,shore,to).
det(2,shore,the).
nmod:to(2,convey,shore).
be(2,him,man).
is(2,he,always_said).
is_in(2,his_back,safety).
placed(2,monkey,himself).
is(2,he,said).
root(3,ROOT,arrived).
advmod(3,arrived,when).
det(3,dolphin,the).
nsubj(3,arrived,dolphin).
case(3,burden,with).
nmod:poss(3,burden,his).
nmod:with(3,arrived,burden).
case(3,sight,in).
nmod:in(3,burden,sight).
case(3,land,of).
nmod:of(3,sight,land).
dep(3,far,not).
advmod(3,arrived,far).
case(3,athens,from).
nmod:from(3,arrived,athens).
nsubj(3,asked,he).
acl:relcl(3,athens,asked).
det(3,monkey,the).
dobj(3,asked,monkey).
mark(3,athenian,if).
nsubj(3,athenian,he).
cop(3,athenian,were).
det(3,athenian,an).
advcl:if(3,asked,athenian).
arrived_far_with(3,dolphin,his_burden).
arrived_far_with(3,dolphin,his_burden_in_sight_of_land).
asked(3,he,monkey).
is_in(3,his_burden,sight_of_land).
arrived_with(3,dolphin,his_burden_in_sight_of_land).
arrived_with(3,dolphin,his_burden_in_sight).
arrived_with(3,dolphin,his_burden).
were(3,he,athenian).
asked_monkey(3,he,athenian).
arrived_far_with(3,dolphin,his_burden_in_sight).
root(4,ROOT,replied).
det(4,latter,the).
nsubj(4,replied,latter).
mark(4,was,that).
nsubj(4,was,he).
ccomp(4,replied,was).
cc(4,was,and).
mark(4,descended,that).
nsubjpass(4,descended,he).
auxpass(4,descended,was).
ccomp(4,replied,descended).
conj:and(4,was,descended).
case(4,one,from).
det:qmod(4,families,one).
mwe(4,one,of).
det(4,families,the).
advmod(4,noble,most).
amod(4,families,noble).
nmod(4,descended,families).
case(4,city,in).
det(4,city,that).
nmod:in(4,families,city).
is_in(4,noble_families,city).
was(4,he,descended).
root(5,ROOT,inquired).
det(5,dolphin,the).
nsubj(5,inquired,dolphin).
advmod(5,inquired,then).
mark(5,knew,if).
nsubj(5,knew,he).
advcl:if(5,inquired,knew).
det(5,piraeus,the).
dobj(5,knew,piraeus).
punct(5,harbor,-LRB-).
det(5,harbor,the).
amod(5,harbor,famous).
dep(5,piraeus,harbor).
case(5,athens,of).
nmod:of(5,harbor,athens).
punct(5,harbor,-RRB-).
inquired(5,dolphin,he_knew).
knew(5,he,piraeus).
root(6,ROOT,supposing).
mark(6,meant,that).
det(6,man,a).
nsubjpass(6,meant,man).
auxpass(6,meant,was).
ccomp(6,supposing,meant).
det(6,monkey,the).
dobj(6,meant,monkey).
acl(6,monkey,answered).
mark(6,knew,that).
nsubj(6,knew,he).
ccomp(6,answered,knew).
dobj(6,knew,him).
advmod(6,well,very).
advmod(6,knew,well).
cc(6,knew,and).
mark(6,friend,that).
nsubj(6,friend,he).
cop(6,friend,was).
det(6,friend,an).
amod(6,friend,intimate).
ccomp(6,answered,friend).
conj:and(6,knew,friend).
was(6,he,intimate).
root(7,ROOT,dipped).
det(7,indignant,the).
compound(7,indignant,dolphin).
nsubj(7,dipped,indignant).
nsubj(7,drowned,indignant).
case(7,falsehoods,at).
det(7,falsehoods,these).
nmod:at(7,indignant,falsehoods).
det(7,monkey,the).
dobj(7,dipped,monkey).
case(7,water,under).
det(7,water,the).
nmod:under(7,dipped,water).
cc(7,dipped,and).
conj:and(7,dipped,drowned).
dobj(7,drowned,him).
drowned(7,dolphin_indignant,him).
dipped(7,dolphin_indignant,monkey).
dipped_monkey_under(7,dolphin_indignant,water).
