root(0,ROOT,time).
advmod(0,time,once).
case(0,time,upon).
det(0,time,a).
nsubj(0,used,time).
nsubj:xsubj(0,hide,time).
expl(0,was,there).
acl:relcl(0,time,was).
det(0,miser,a).
nsubj(0,was,miser).
nsubj(0,used,miser).
nsubj:xsubj(0,hide,miser).
ref(0,time,who).
ref(0,miser,who).
acl:relcl(0,miser,used).
mark(0,hide,to).
xcomp(0,used,hide).
nmod:poss(0,gold,his).
dobj(0,hide,gold).
case(0,foot,at).
det(0,foot,the).
nmod:at(0,hide,foot).
case(0,tree,of).
det(0,tree,a).
nmod:of(0,foot,tree).
case(0,garden,in).
nmod:poss(0,garden,his).
nmod:in(0,tree,garden).
is_in(0,tree,his_garden).
root(1,ROOT,week).
cc(1,week,but).
det(1,week,every).
nsubj(1,used,he).
nsubj:xsubj(1,go,he).
nsubj:xsubj(1,dig,he).
acl:relcl(1,week,used).
mark(1,go,to).
xcomp(1,used,go).
cc(1,go,and).
xcomp(1,used,dig).
conj:and(1,go,dig).
dobj(1,dig,it).
compound:prt(1,dig,up).
cc(1,dig,and).
conj:and(1,go,gloat).
conj:and(1,dig,gloat).
case(1,gains,over).
nmod:poss(1,gains,his).
nmod:over(1,gloat,gains).
root(2,ROOT,robber).
det(2,robber,a).
nsubj(2,noticed,robber).
nsubj(2,decamped,robber).
ref(2,robber,who).
aux(2,noticed,had).
acl:relcl(2,robber,noticed).
nsubj(2,went,this).
nsubj(2,dug,this).
ccomp(2,noticed,went).
cc(2,went,and).
ccomp(2,noticed,dug).
conj:and(2,went,dug).
compound:prt(2,went,up).
det(2,gold,the).
dobj(2,went,gold).
cc(2,noticed,and).
acl:relcl(2,robber,decamped).
conj:and(2,noticed,decamped).
case(2,it,with).
nmod:with(2,decamped,it).
root(3,ROOT,came).
advmod(3,came,when).
det(3,miser,the).
advmod(3,came,miser).
case(3,miser,next).
mark(3,gloat,to).
xcomp(3,came,gloat).
case(3,treasures,over).
nmod:poss(3,treasures,his).
nmod:over(3,gloat,treasures).
nsubj(3,found,he).
acl:relcl(3,treasures,found).
dobj(3,found,nothing).
case(3,hole,but).
det(3,hole,the).
amod(3,hole,empty).
nmod:but(3,nothing,hole).
nothing_but(3,he,hole).
nothing_but(3,he,empty_hole).
found(3,he,nothing_but_empty_hole).
found(3,he,nothing).
found(3,he,nothing_but_hole).
root(4,ROOT,tore).
nsubj(4,tore,he).
nsubj(4,raised,he).
nmod:poss(4,hair,his).
dobj(4,tore,hair).
cc(4,tore,and).
conj:and(4,tore,raised).
det:predet(4,outcry,such).
det(4,outcry,an).
dobj(4,raised,outcry).
mark(4,came,that).
det:predet(4,neighbours,all).
det(4,neighbours,the).
nsubj(4,came,neighbours).
ccomp(4,raised,came).
case(4,him,around).
nmod:around(4,came,him).
cc(4,came,and).
nsubj(4,told,he).
ccomp(4,raised,told).
conj:and(4,came,told).
dobj(4,told,them).
advmod(4,used,how).
nsubj(4,used,he).
nsubj:xsubj(4,come,he).
nsubj:xsubj(4,visit,he).
dep(4,told,used).
mark(4,come,to).
xcomp(4,used,come).
cc(4,come,and).
xcomp(4,used,visit).
conj:and(4,come,visit).
nmod:poss(4,gold,his).
dobj(4,come,gold).
came_around(4,neighbours,him).
tore(4,he,his_hair).
come(4,he,his_gold).
told(4,he,them).
root(5,ROOT,did).
nsubj(5,take,you).
advmod(5,take,ever).
ccomp(5,did,take).
dobj(5,take,any).
case(5,it,of).
nmod:of(5,any,it).
compound:prt(5,take,out).
take_out(5,you,any).
ever_take_out(5,you,any_of_it).
take_out(5,you,any_of_it).
ever_take_out(5,you,any).
root(6,ROOT,asked).
det:qmod(6,them,one).
mwe(6,one,of).
nsubj(6,asked,them).
root(7,ROOT,nay).
root(8,ROOT,said).
nsubj(8,said,he).
root(9,ROOT,came).
nsubj(9,came,i).
nsubj:xsubj(9,look,i).
advmod(9,came,only).
mark(9,look,to).
xcomp(9,came,look).
case(9,it,at).
nmod:at(9,look,it).
came(9,i,look_at_it).
only_came(9,i,look).
look_at(9,i,it).
only_came(9,i,look_at_it).
came(9,i,look).
root(10,ROOT,come).
advmod(10,come,then).
advmod(10,come,again).
cc(10,come,and).
conj:and(10,come,look).
case(10,hole,at).
det(10,hole,the).
nmod:at(10,look,hole).
root(11,ROOT,said).
det(11,neighbour,a).
nsubj(11,said,neighbour).
root(12,ROOT,do).
nsubj(12,do,it).
aux(12,do,will).
nsubj(12,good,you).
advmod(12,much,just).
advmod(12,much,as).
nmod:npmod(12,good,much).
xcomp(12,do,good).
will_do(12,it,you_as_much_good).
will_do(12,it,you_good).
will_do(12,it,you_just_much_good).
good(12,you,just_as_much).
will_do(12,it,you_just_as_much_good).
good(12,you,as_much).
good(12,you,much).
will_do(12,it,you_much_good).
good(12,you,just_much).
