root(0,ROOT,miser).
det(0,miser,the).
det(0,miser,a).
nsubj(0,sold,miser).
nsubj(0,went,miser).
nsubj:xsubj(0,look,miser).
ccomp(0,miser,sold).
dobj(0,sold,all).
mark(0,had,that).
nsubj(0,had,he).
nsubj(0,bought,he).
ccomp(0,sold,had).
cc(0,had,and).
ccomp(0,sold,bought).
conj:and(0,had,bought).
det(0,lump,a).
dobj(0,bought,lump).
dobj(0,buried,lump).
case(0,gold,of).
nmod:of(0,lump,gold).
ref(0,lump,which).
nsubj(0,buried,he).
acl:relcl(0,lump,buried).
case(0,hole,in).
det(0,hole,a).
nmod:in(0,buried,hole).
case(0,ground,in).
det(0,ground,the).
nmod:in(0,hole,ground).
case(0,side,by).
det(0,side,the).
nmod:by(0,buried,side).
case(0,wall,of).
det(0,wall,an).
amod(0,wall,old).
nmod:of(0,side,wall).
cc(0,sold,and).
ccomp(0,miser,went).
conj:and(0,sold,went).
mark(0,look,to).
xcomp(0,went,look).
case(0,daily,at).
nmod:at(0,look,daily).
went(0,miser,look_at_daily).
buried_in(0,he,hole_in_ground).
buried_by(0,he,side_of_wall).
is_in(0,hole,ground).
buried_by(0,he,side_of_old_wall).
sold(0,miser,all).
buried_in(0,he,hole).
buried_by(0,he,side).
went(0,miser,look).
root(1,ROOT,observed).
nsubj(1,observed,one).
nsubj(1,decided,one).
nsubj:xsubj(1,watch,one).
case(1,workmen,of).
nmod:poss(1,workmen,his).
nmod:of(1,one,workmen).
nmod:poss(1,visits,his).
amod(1,visits,frequent).
dobj(1,observed,visits).
case(1,spot,to).
det(1,spot,the).
nmod:to(1,observed,spot).
cc(1,observed,and).
conj:and(1,observed,decided).
mark(1,watch,to).
xcomp(1,decided,watch).
nmod:poss(1,movements,his).
dobj(1,watch,movements).
root(2,ROOT,discovered).
nsubj(2,discovered,he).
nsubj(2,stole,he).
advmod(2,discovered,soon).
det(2,secret,the).
dobj(2,discovered,secret).
case(2,treasure,of).
det(2,treasure,the).
amod(2,treasure,hidden).
nmod:of(2,secret,treasure).
cc(2,treasure,and).
nmod:of(2,secret,digging).
conj:and(2,treasure,digging).
advmod(2,came,down).
acl(2,treasure,came).
case(2,lump,to).
det(2,lump,the).
nmod:to(2,came,lump).
case(2,gold,of).
nmod:of(2,lump,gold).
cc(2,discovered,and).
conj:and(2,discovered,stole).
dobj(2,stole,it).
discovered(2,he,secret_of_treasure_down_came).
soon_discovered(2,he,secret_of_treasure_down_came_to_lump_of_gold).
soon_discovered(2,he,secret_of_hidden_treasure).
discovered(2,he,secret).
soon_discovered(2,he,secret_of_treasure_down_came).
soon_discovered(2,he,secret_of_treasure_came_to_lump).
stole(2,he,it).
soon_discovered(2,he,secret_of_treasure_came).
discovered(2,he,secret_of_treasure_came).
soon_discovered(2,he,secret_of_hidden_treasure_down_came_to_lump_of_gold).
soon_discovered(2,he,secret).
soon_discovered(2,he,secret_of_hidden_treasure_down_came_to_lump).
soon_discovered(2,he,secret_of_hidden_treasure_came).
discovered(2,he,secret_of_hidden_treasure_came_to_lump_of_gold).
soon_discovered(2,he,secret_of_treasure).
discovered(2,he,secret_of_hidden_treasure_came).
soon_discovered(2,he,secret_of_hidden_treasure_came_to_lump_of_gold).
discovered(2,he,secret_of_treasure_down_came_to_lump).
soon_discovered(2,he,secret_of_treasure_came_to_lump_of_gold).
soon_discovered(2,he,secret_of_hidden_treasure_down_came).
discovered(2,he,secret_of_hidden_treasure_down_came).
discovered(2,he,secret_of_treasure_down_came_to_lump_of_gold).
discovered(2,he,secret_of_treasure_came_to_lump).
soon_discovered(2,he,secret_of_treasure_down_came_to_lump).
discovered(2,he,secret_of_treasure).
soon_discovered(2,he,secret_of_hidden_treasure_came_to_lump).
discovered(2,he,secret_of_hidden_treasure).
discovered(2,he,secret_of_hidden_treasure_down_came_to_lump_of_gold).
discovered(2,he,secret_of_treasure_came_to_lump_of_gold).
discovered(2,he,secret_of_hidden_treasure_came_to_lump).
discovered(2,he,secret_of_hidden_treasure_down_came_to_lump).
root(3,ROOT,found).
det(3,miser,the).
nsubj(3,found,miser).
nsubj(3,began,miser).
case(3,visit,on).
nmod:poss(3,visit,his).
amod(3,visit,next).
nmod:on(3,miser,visit).
det(3,hole,the).
nsubj(3,empty,hole).
xcomp(3,found,empty).
cc(3,found,and).
conj:and(3,found,began).
mark(3,tear,to).
ccomp(3,began,tear).
nmod:poss(3,hair,his).
dobj(3,tear,hair).
cc(3,tear,and).
mark(3,make,to).
ccomp(3,began,make).
conj:and(3,tear,make).
amod(3,lamentations,loud).
dobj(3,make,lamentations).
found(3,miser,hole_empty).
make(3,his_hair,lamentations).
make(3,his_hair,loud_lamentations).
root(4,ROOT,said).
det(4,neighbor,a).
nsubj(4,said,neighbor).
dep(4,neighbor,seeing).
nsubj(4,overcome,him).
ccomp(4,seeing,overcome).
case(4,grief,with).
nmod:with(4,overcome,grief).
cc(4,seeing,and).
dep(4,neighbor,learning).
conj:and(4,seeing,learning).
det(4,cause,the).
dobj(4,learning,cause).
overcome_with(4,him,grief).
root(5,ROOT,grieve).
nsubj(5,grieve,pray).
aux(5,grieve,do).
neg(5,grieve,not).
advmod(5,grieve,so).
root(6,ROOT,go).
cc(6,go,but).
cc(6,go,and).
conj:and(6,go,take).
det(6,stone,a).
dobj(6,take,stone).
cc(6,stone,and).
dobj(6,take,place).
conj:and(6,stone,place).
xcomp(6,take,it).
case(6,hole,in).
det(6,hole,the).
nmod:in(6,take,hole).
cc(6,hole,and).
nmod:in(6,take,fancy).
conj:and(6,hole,fancy).
mark(6,lying,that).
det(6,gold,the).
nsubj(6,lying,gold).
aux(6,lying,is).
advmod(6,lying,still).
ccomp(6,take,lying).
advmod(6,lying,there).
root(7,ROOT,do).
nsubj(7,do,it).
aux(7,do,will).
nsubj(7,service,you).
advmod(7,service,quite).
det(7,service,the).
amod(7,service,same).
xcomp(7,do,service).
will_do(7,it,you_quite_same_service).
will_do(7,it,you_same_service).
will_do(7,it,you_service).
will_do(7,it,you_quite_service).
root(8,ROOT,had).
mark(8,had,for).
advmod(8,there,when).
det(8,gold,the).
nsubj(8,there,gold).
cop(8,there,was).
advcl(8,had,there).
nsubj(8,had,you).
dobj(8,had,it).
dep(8,make,not).
mark(8,make,as).
nsubj(8,make,you).
aux(8,make,did).
neg(8,make,not).
advcl:as(8,had,make).
det(8,use,the).
amod(8,use,slightest).
dobj(8,make,use).
case(8,it,of).
nmod:of(8,use,it).
slightest_use_of(8,you,it).
