root(0,ROOT,lay).
det(0,lion,the).
amod(0,lion,old).
nsubj(0,lay,lion).
det(0,lion,a).
nsubj(0,worn,lion).
nsubj(0,powerless,lion).
acl:relcl(0,lion,worn).
compound:prt(0,worn,out).
case(0,years,with).
nmod:with(0,worn,years).
cc(0,worn,and).
acl:relcl(0,lion,powerless).
conj:and(0,worn,powerless).
case(0,disease,from).
nmod:from(0,powerless,disease).
case(0,ground,on).
det(0,ground,the).
nmod:on(0,lay,ground).
case(0,point,at).
det(0,point,the).
nmod:at(0,lay,point).
case(0,death,of).
nmod:of(0,point,death).
worn_out_with(0,lion,years).
root(1,ROOT,rushed).
det(1,boar,a).
nsubj(1,rushed,boar).
nsubj(1,avenged,boar).
case(1,him,upon).
nmod:upon(1,rushed,him).
cc(1,rushed,and).
conj:and(1,rushed,avenged).
case(1,stroke,with).
det(1,stroke,a).
nmod:with(1,avenged,stroke).
case(1,tusks,of).
nmod:poss(1,tusks,his).
nmod:of(1,stroke,tusks).
det(1,injury,a).
amod(1,injury,long-remembered).
dep(1,tusks,injury).
avenged_with(1,boar,stroke).
rushed_upon(1,boar,him).
avenged_with(1,boar,stroke_of_his_tusks).
root(2,ROOT,gored).
advmod(2,gored,shortly).
advmod(2,bull,afterwards).
det(2,bull,the).
advmod(2,shortly,bull).
case(2,horns,with).
nmod:poss(2,horns,his).
nmod:with(2,shortly,horns).
dobj(2,gored,him).
nmod(2,gored,as).
mark(2,enemy,if).
nsubj(2,enemy,he).
cop(2,enemy,were).
det(2,enemy,an).
dep(2,gored,enemy).
were(2,he,enemy).
root(3,ROOT,saw).
advmod(3,saw,when).
det(3,ass,the).
nsubj(3,saw,ass).
mark(3,assailed,that).
det(3,beast,the).
amod(3,beast,huge).
nsubjpass(3,assailed,beast).
aux(3,assailed,could).
auxpass(3,assailed,be).
ccomp(3,saw,assailed).
case(3,impunity,with).
nmod:with(3,assailed,impunity).
nsubj(3,let,he).
acl:relcl(3,impunity,let).
dobj(3,let,drive).
case(3,forehead,at).
nmod:poss(3,forehead,his).
nmod:at(3,let,forehead).
case(3,heels,with).
nmod:poss(3,heels,his).
nmod:with(3,let,heels).
let_drive_with(3,he,his_heels).
let(3,he,drive).
be(3,huge_beast,assailed).
let_at(3,he,his_forehead).
let_with(3,he,his_heels).
be(3,beast,assailed).
let_drive_at(3,he,his_forehead).
root(4,ROOT,said).
det(4,lion,the).
amod(4,lion,expiring).
nsubj(4,said,lion).
root(5,ROOT,i).
aux(5,brooked,have).
advmod(5,brooked,reluctantly).
acl:relcl(5,i,brooked).
det(5,insults,the).
nsubj(5,brave,insults).
case(5,the,of).
nmod:of(5,insults,the).
ccomp(5,brooked,brave).
cc(5,compelled,but).
mark(5,compelled,to).
auxpass(5,compelled,be).
dep(5,i,compelled).
mark(5,endure,to).
xcomp(5,compelled,endure).
amod(5,treatment,such).
dobj(5,endure,treatment).
case(5,thee,from).
nmod:from(5,endure,thee).
det(5,disgrace,a).
nsubj(5,is,disgrace).
nsubj:xsubj(5,die,disgrace).
case(5,nature,to).
nmod:to(5,disgrace,nature).
acl:relcl(5,thee,is).
advmod(5,is,indeed).
mark(5,die,to).
xcomp(5,is,die).
det(5,death,a).
amod(5,death,double).
dobj(5,die,death).
die(5,disgrace,death).
die(5,disgrace,double_death).
