root(0,ROOT,men).
case(0,men,in).
det(0,men,the).
amod(0,men,old).
compound(0,men,days).
dep(0,men,used).
case(0,stocks,to).
compound(0,stocks,worship).
nmod:to(0,used,stocks).
cc(0,stocks,and).
nmod:to(0,used,stones).
conj:and(0,stocks,stones).
cc(0,stones,and).
conj:and(0,stocks,idols).
conj:and(0,stones,idols).
cc(0,used,and).
dep(0,men,prayed).
conj:and(0,used,prayed).
case(0,them,to).
nmod:to(0,prayed,them).
mark(0,give,to).
xcomp(0,prayed,give).
iobj(0,give,them).
dobj(0,give,luck).
root(1,ROOT,happened).
nsubj(1,happened,it).
mark(1,prayed,that).
det(1,man,a).
nsubj(1,prayed,man).
aux(1,prayed,had).
advmod(1,prayed,often).
ccomp(1,happened,prayed).
case(1,idol,to).
det(1,idol,a).
amod(1,idol,wooden).
nmod:to(1,prayed,idol).
nsubj(1,received,he).
aux(1,received,had).
acl:relcl(1,idol,received).
case(1,father,from).
nmod:poss(1,father,his).
nmod:from(1,received,father).
cc(1,received,but).
nmod:poss(1,luck,his).
nsubj(1,seemed,luck).
nsubj:xsubj(1,change,luck).
neg(1,seemed,never).
acl:relcl(1,idol,seemed).
conj:but(1,received,seemed).
mark(1,change,to).
xcomp(1,seemed,change).
had_received_from(1,he,his_father).
root(2,ROOT,prayed).
nsubj(2,prayed,he).
cc(2,prayed,and).
nsubj(2,prayed,he).
dep(2,prayed,prayed).
cc(2,prayed,but).
advmod(2,remained,still).
nsubj(2,remained,he).
dep(2,prayed,remained).
conj:but(2,prayed,remained).
case(2,unlucky,as).
advcl:as(2,remained,unlucky).
case(2,ever,as).
advcl:as(2,remained,ever).
remained_as(2,he,ever).
still_remained_as(2,he,unlucky).
still_remained_as(2,he,ever).
remained_as(2,he,unlucky).
root(3,ROOT,swept).
nummod(3,day,one).
nsubj(3,swept,day).
case(3,rage,in).
det(3,rage,the).
amod(3,rage,greatest).
nmod:in(3,day,rage).
nsubj(3,went,he).
nsubj(3,went,he).
acl:relcl(3,rage,went).
acl:relcl(3,rage,went).
conj:and(3,went,went).
case(3,god,to).
det(3,god,the).
amod(3,god,wooden).
nmod:to(3,went,god).
cc(3,went,and).
case(3,blow,with).
nummod(3,blow,one).
nmod:with(3,went,blow).
dobj(3,swept,it).
compound:prt(3,swept,down).
case(3,pedestal,from).
nmod:poss(3,pedestal,its).
nmod:from(3,swept,pedestal).
is_in(3,one_day,greatest_rage).
root(4,ROOT,broke).
det(4,idol,the).
nsubj(4,broke,idol).
case(4,two,in).
dep(4,broke,two).
cc(4,two,and).
nsubj(4,did,what).
dep(4,broke,did).
conj:and(4,two,did).
nsubj(4,see,he).
ccomp(4,did,see).
root(5,ROOT,number).
det(5,number,an).
amod(5,number,immense).
case(5,coins,of).
nmod:of(5,number,coins).
acl(5,coins,flying).
dobj(5,flying,all).
case(5,place,over).
det(5,place,the).
nmod:over(5,all,place).
all_over(5,flying,place).
