root(0,ROOT,agitated).
det(0,mountain,a).
nsubjpass(0,agitated,mountain).
auxpass(0,agitated,was).
advmod(0,agitated,once).
advmod(0,agitated,greatly).
was(0,mountain,once_agitated).
was(0,mountain,once_greatly_agitated).
was(0,mountain,greatly_agitated).
was(0,mountain,agitated).
root(1,ROOT,groans).
advmod(1,groans,loud).
cc(1,groans,and).
conj:and(1,groans,noises).
auxpass(1,heard,were).
dep(1,groans,heard).
cc(1,heard,and).
nsubj(1,came,crowds).
nsubj:xsubj(1,see,crowds).
case(1,people,of).
nmod:of(1,crowds,people).
dep(1,groans,came).
conj:and(1,heard,came).
case(1,parts,from).
det(1,parts,all).
nmod:from(1,came,parts).
mark(1,see,to).
xcomp(1,came,see).
nsubj(1,matter,what).
cop(1,matter,was).
det(1,matter,the).
dep(1,groans,matter).
came_from(1,crowds,parts).
root(2,ROOT,assembled).
mark(2,assembled,while).
nsubjpass(2,assembled,they).
auxpass(2,assembled,were).
case(2,expectation,in).
amod(2,expectation,anxious).
nmod:in(2,assembled,expectation).
case(2,calamity,of).
det(2,calamity,some).
amod(2,calamity,terrible).
nmod:of(2,expectation,calamity).
advmod(2,came,out).
acl(2,calamity,came).
det(2,mouse,a).
dobj(2,came,mouse).
were_assembled_in(2,they,expectation_of_calamity).
were_assembled_in(2,they,expectation_of_terrible_calamity_out_came).
were_assembled_in(2,they,anxious_expectation_of_terrible_calamity).
were_assembled_in(2,they,anxious_expectation_of_calamity_out_came).
were_assembled_in(2,they,expectation_of_terrible_calamity).
were_assembled_in(2,they,expectation_of_terrible_calamity_came).
were_assembled_in(2,they,expectation).
were_assembled_in(2,they,anxious_expectation_of_calamity).
were_assembled_in(2,they,anxious_expectation_of_terrible_calamity_out_came).
were_assembled_in(2,they,anxious_expectation_of_terrible_calamity_came).
were_assembled_in(2,they,anxious_expectation).
were_assembled_in(2,they,anxious_expectation_of_calamity_came).
were_assembled_in(2,they,expectation_of_calamity_came).
were(2,they,assembled).
were_assembled_in(2,they,expectation_of_calamity_out_came).
