root(0,ROOT,formed).
det(0,mouse,a).
nsubj(0,lived,mouse).
nsubj(0,formed,mouse).
ref(0,mouse,who).
advmod(0,lived,always).
acl:relcl(0,mouse,lived).
case(0,land,on).
det(0,land,the).
nmod:on(0,lived,land).
case(0,chance,by).
det(0,chance,an).
amod(0,chance,unlucky).
nmod:by(0,lived,chance).
det(0,acquaintance,an).
amod(0,acquaintance,intimate).
dobj(0,formed,acquaintance).
case(0,frog,with).
det(0,frog,a).
nmod:with(0,formed,frog).
nsubj(0,lived,frog).
ref(0,frog,who).
acl:relcl(0,frog,lived).
case(0,part,for).
det(0,part,the).
amod(0,part,most).
nmod:for(0,lived,part).
case(0,water,in).
det(0,water,the).
nmod:in(0,lived,water).
root(1,ROOT,bound).
det(1,intent,the).
compound(1,intent,frog).
nummod(1,intent,one).
compound(1,intent,day).
nsubj(1,bound,intent).
case(1,mischief,on).
nmod:on(1,intent,mischief).
det(1,foot,the).
dobj(1,bound,foot).
case(1,mouse,of).
det(1,mouse,the).
nmod:of(1,foot,mouse).
advmod(1,mouse,tightly).
case(1,own,to).
nmod:poss(1,own,his).
nmod:to(1,tightly,own).
root(2,ROOT,joined).
advmod(2,joined,thus).
advmod(2,joined,together).
det(2,frog,the).
dobj(2,joined,frog).
advmod(2,all,first).
case(2,all,of).
nmod:of(2,frog,all).
dep(2,joined,led).
nmod:poss(2,friend,his).
dobj(2,led,friend).
det(2,mouse,the).
nsubj(2,joined,mouse).
case(2,meadow,to).
det(2,meadow,the).
nmod:to(2,mouse,meadow).
advmod(2,accustomed,where).
nsubjpass(2,accustomed,they).
nsubj:xsubj(2,find,they).
auxpass(2,accustomed,were).
acl:relcl(2,meadow,accustomed).
mark(2,find,to).
xcomp(2,accustomed,find).
nmod:poss(2,food,their).
dobj(2,find,food).
joined_together(2,mouse,frog_of_all).
thus_joined_together(2,mouse,frog_first_of_all).
joined(2,mouse,frog_of_all).
were(2,they,where_accustomed).
thus_joined(2,mouse,frog_first_of_all).
joined(2,mouse,frog).
thus_joined(2,mouse,frog_of_all).
find(2,they,their_food).
thus_joined_together(2,mouse,frog).
joined(2,mouse,frog_first_of_all).
thus_joined_together(2,mouse,frog_of_all).
joined_together(2,mouse,frog_first_of_all).
thus_joined(2,mouse,frog).
joined_together(2,mouse,frog).
were(2,they,accustomed).
root(3,ROOT,led).
mark(3,led,after).
det(3,he,this).
nsubj(3,led,he).
advmod(3,led,gradually).
dobj(3,led,him).
case(3,pool,towards).
det(3,pool,the).
nmod:towards(3,led,pool).
nmod:in(3,lived,pool).
case(3,which,in).
ref(3,pool,which).
nsubj(3,lived,he).
acl:relcl(3,pool,lived).
mark(3,reaching,until).
advcl:until(3,lived,reaching).
det(3,brink,the).
advmod(3,brink,very).
dobj(3,reaching,brink).
nsubj(3,jumped,he).
advmod(3,jumped,suddenly).
acl:relcl(3,brink,jumped).
mark(3,dragging,in).
advcl:in(3,jumped,dragging).
det(3,mouse,the).
dobj(3,dragging,mouse).
case(3,him,with).
nmod:with(3,dragging,him).
led(3,he,him).
dragging(3,he,mouse).
gradually_led(3,he,him).
dragging_mouse_with(3,he,him).
root(4,ROOT,enjoyed).
det(4,frog,the).
nsubj(4,enjoyed,frog).
nsubj(4,swam,frog).
det(4,water,the).
dobj(4,enjoyed,water).
advmod(4,enjoyed,amazingly).
cc(4,enjoyed,and).
conj:and(4,enjoyed,swam).
xcomp(4,swam,croaking).
advmod(4,croaking,about).
mark(4,done,as).
mwe(4,as,if).
nsubj(4,done,he).
aux(4,done,had).
advcl:as_if(4,croaking,done).
det(4,deed,a).
amod(4,deed,good).
dobj(4,done,deed).
swam(4,frog,croaking_about).
had_done(4,he,good_deed).
swam(4,frog,croaking).
had_done(4,he,deed).
enjoyed(4,frog,water).
enjoyed_amazingly(4,frog,water).
root(5,ROOT,floated).
det(5,mouse,the).
amod(5,mouse,unhappy).
nsubj(5,floated,mouse).
auxpass(5,suffocated,was).
advmod(5,suffocated,soon).
acl:relcl(5,mouse,suffocated).
case(5,water,by).
det(5,water,the).
nmod:agent(5,suffocated,water).
cc(5,water,and).
nmod:poss(5,body,his).
amod(5,body,dead).
nmod:agent(5,suffocated,body).
conj:and(5,water,body).
advmod(5,floated,about).
case(5,surface,on).
det(5,surface,the).
nmod:on(5,floated,surface).
acl(5,surface,tied).
case(5,foot,to).
det(5,foot,the).
nmod:to(5,tied,foot).
case(5,frog,of).
det(5,frog,the).
nmod:of(5,foot,frog).
root(6,ROOT,carried).
det(6,hawk,a).
nsubj(6,carried,hawk).
dep(6,hawk,observed).
dobj(6,observed,it).
cc(6,observed,and).
dep(6,hawk,pouncing).
conj:and(6,observed,pouncing).
case(6,it,upon).
nmod:upon(6,pouncing,it).
case(6,talons,with).
nmod:poss(6,talons,his).
nmod:with(6,pouncing,talons).
dobj(6,carried,it).
advmod(6,carried,aloft).
pouncing_with(6,it,his_talons).
carried_aloft(6,hawk,it).
pouncing_upon(6,it,it).
carried(6,hawk,it).
root(7,ROOT,carried).
det(7,frog,the).
nsubjpass(7,carried,frog).
nsubjpass(7,eaten,frog).
auxpass(7,fastened,being).
advmod(7,fastened,still).
acl(7,frog,fastened).
case(7,leg,to).
det(7,leg,the).
nmod:to(7,fastened,leg).
case(7,mouse,of).
det(7,mouse,the).
nmod:of(7,leg,mouse).
auxpass(7,carried,was).
advmod(7,carried,also).
compound:prt(7,carried,off).
det(7,prisoner,a).
dobj(7,carried,prisoner).
cc(7,carried,and).
auxpass(7,eaten,was).
conj:and(7,carried,eaten).
case(7,hawk,by).
det(7,hawk,the).
nmod:agent(7,eaten,hawk).
was_eaten_by(7,frog,hawk).
was(7,frog,eaten).
was_also_carried_off(7,frog,prisoner).
was_carried_off(7,frog,prisoner).
