root(0,ROOT,carrying).
det(0,farmer,a).
nmod:poss(0,daughter,farmer).
case(0,farmer,'s).
nsubj(0,carrying,daughter).
aux(0,carrying,was).
nmod:poss(0,pail,her).
dobj(0,carrying,pail).
case(0,milk,of).
nmod:of(0,pail,milk).
case(0,field,from).
det(0,field,the).
nmod:from(0,carrying,field).
case(0,farmhouse,to).
det(0,farmhouse,the).
nmod:to(0,field,farmhouse).
advmod(0,fell,when).
nsubj(0,fell,she).
acl:relcl(0,farmhouse,fell).
dobj(0,fell,a-musing).
was_carrying(0,farmer_s_daughter,her_pail).
fell(0,she,a-musing).
was_carrying(0,farmer_s_daughter,her_pail_of_milk).
has(0,farmer,daughter).
root(1,ROOT,buy).
det(1,money,the).
nmod:for(1,sold,money).
nsubj(1,buy,money).
case(1,which,for).
ref(1,money,which).
det(1,milk,this).
nsubjpass(1,sold,milk).
aux(1,sold,will).
auxpass(1,sold,be).
acl:relcl(1,money,sold).
aux(1,buy,will).
case(1,least,at).
nmod:npmod(1,hundred,least).
compound(1,hundred,three).
nummod(1,eggs,hundred).
dobj(1,buy,eggs).
will(1,milk,will_sold).
root(2,ROOT,produce).
det(2,eggs,the).
nsubj(2,produce,eggs).
acl(2,eggs,allowing).
case(2,mishaps,for).
det(2,mishaps,all).
nmod:for(2,allowing,mishaps).
aux(2,produce,will).
nummod(2,hundred,two).
dobj(2,produce,hundred).
cc(2,hundred,and).
nummod(2,chickens,fifty).
dobj(2,produce,chickens).
conj:and(2,hundred,chickens).
will_produce(2,eggs,fifty_chickens).
allowing_for(2,eggs,mishaps).
root(3,ROOT,become).
det(3,chickens,the).
nsubj(3,become,chickens).
aux(3,become,will).
xcomp(3,become,ready).
case(3,market,for).
det(3,market,the).
nmod:for(3,ready,market).
advmod(3,fetch,when).
nsubj(3,fetch,poultry).
aux(3,fetch,will).
advcl(3,become,fetch).
det(3,price,the).
amod(3,price,highest).
dobj(3,fetch,price).
mark(3,have,so).
mwe(3,so,that).
case(3,end,by).
det(3,end,the).
nmod:by(3,have,end).
case(3,year,of).
det(3,year,the).
nmod:of(3,end,year).
nsubj(3,have,i).
aux(3,have,shall).
advcl:so_that(3,fetch,have).
dobj(3,have,money).
advmod(3,have,enough).
case(3,share,from).
nmod:poss(3,share,my).
nmod:from(3,enough,share).
mark(3,buy,to).
advcl:to(3,have,buy).
det(3,gown,a).
amod(3,gown,new).
dobj(3,buy,gown).
shall_have(3,i,money).
will_fetch(3,poultry,highest_price).
shall_have_enough(3,i,money).
buy(3,i,gown).
buy(3,i,new_gown).
will_fetch(3,poultry,price).
shall_have_money_enough_by(3,i,end_of_year).
shall_have_money_enough_by(3,i,end).
shall_have_money_by(3,i,end_of_year).
will_become(3,chickens,ready_for_market).
will_become(3,chickens,ready).
shall_have_money_by(3,i,end).
root(4,ROOT,go).
case(4,dress,in).
det(4,dress,this).
nmod:in(4,go,dress).
nsubj(4,go,i).
aux(4,go,will).
case(4,parties,to).
det(4,parties,the).
compound(4,parties,christmas).
nmod:to(4,go,parties).
advmod(4,propose,where).
det:predet(4,fellows,all).
det(4,fellows,the).
amod(4,fellows,young).
nsubj(4,propose,fellows).
aux(4,propose,will).
advcl(4,go,propose).
case(4,me,to).
nmod:to(4,propose,me).
cc(4,propose,but).
nsubj(4,toss,i).
nsubj(4,refuse,i).
aux(4,toss,will).
advcl(4,go,toss).
conj:but(4,propose,toss).
nmod:poss(4,head,my).
dobj(4,toss,head).
cc(4,toss,and).
conj:but(4,propose,refuse).
conj:and(4,toss,refuse).
nsubj(4,one,them).
det(4,one,every).
xcomp(4,refuse,one).
will_propose_to(4,young_fellows,me).
will_go_in(4,i,dress).
will_toss(4,i,my_head).
will_go_to(4,i,christmas_parties).
root(5,ROOT,tossed).
case(5,moment,at).
det(5,moment,this).
nmod:at(5,tossed,moment).
nsubj(5,tossed,she).
nmod:poss(5,head,her).
dobj(5,tossed,head).
case(5,unison,in).
nmod:in(5,tossed,unison).
case(5,thoughts,with).
nmod:poss(5,thoughts,her).
nmod:with(5,tossed,thoughts).
advmod(5,down,when).
advmod(5,fell,down).
advcl(5,tossed,fell).
det(5,pail,the).
compound(5,pail,milk).
dobj(5,fell,pail).
case(5,ground,to).
det(5,ground,the).
nmod:to(5,fell,ground).
cc(5,fell,and).
dobj(5,perished,all).
nmod:poss(5,schemes,her).
amod(5,schemes,imaginary).
nsubj(5,perished,schemes).
advcl(5,tossed,perished).
conj:and(5,fell,perished).
case(5,moment,in).
det(5,moment,a).
nmod:in(5,perished,moment).
fell(5,she,milk_pail).
when_down_fell_to(5,she,ground).
down_fell_milk_pail_to(5,she,ground).
down_fell(5,she,milk_pail).
when_down_fell(5,she,milk_pail).
fell_to(5,she,ground).
perished(5,her_imaginary_schemes,all).
when_down_fell_milk_pail_to(5,she,ground).
down_fell_to(5,she,ground).
fell_milk_pail_to(5,she,ground).
tossed(5,she,her_head).
perished_in(5,her_imaginary_schemes,moment).
