%% a sailor bound on a long voyage took with him a monkey to amuse him while on shipboard.
% dependencies.
root(0,root,take).
det(0,sailor,a).
nsubj(0,take,sailor).
acl(0,sailor,bind).
case(0,voyage,on).
det(0,voyage,a).
amod(0,voyage,long).
nmod:on(0,bind,voyage).
case(0,he,with).
nmod:with(0,take,he).
det(0,monkey,a).
dobj(0,take,monkey).
mark(0,amuse,to).
acl:to(0,monkey,amuse).
dobj(0,amuse,he).
mark(0,shipboard,while).
case(0,shipboard,on).
advcl:on(0,amuse,shipboard).
% relations.
%% as he sailed off the coast of greece a violent tempest arose in which the ship was wrecked and he his monkey and all the crew were obliged to swim for their lives.
% dependencies.
root(1,root,sail).
mark(1,sail,as).
nsubj(1,sail,he).
compound:prt(1,sail,off).
det(1,coast,the).
dobj(1,sail,coast).
nmod:in(1,wreck,coast).
case(1,greece,of).
nmod:of(1,coast,greece).
det(1,tempest,a).
amod(1,tempest,violent).
nsubj(1,arise,tempest).
acl:relcl(1,coast,arise).
case(1,which,in).
ref(1,coast,which).
det(1,ship,the).
nsubjpass(1,wreck,ship).
auxpass(1,wreck,be).
dep(1,arise,wreck).
cc(1,wreck,and).
dep(1,monkey,he).
nmod:poss(1,monkey,he).
dep(1,arise,monkey).
conj:and(1,wreck,monkey).
cc(1,arise,and).
det:predet(1,crew,all).
det(1,crew,the).
nsubjpass(1,oblige,crew).
nsubj:xsubj(1,swim,crew).
auxpass(1,oblige,be).
acl:relcl(1,coast,oblige).
conj:and(1,arise,oblige).
mark(1,swim,to).
xcomp(1,oblige,swim).
case(1,life,for).
nmod:poss(1,life,they).
nmod:for(1,swim,life).
% relations.
be_oblige(1,crew,swim_for_they_life).
swim_for(1,crew,they_life).
be(1,crew,oblige).
be_oblige(1,crew,swim).
%% a dolphin saw the monkey contending with the waves and supposing him to be a man ( whom he is always said to befriend ) came and placed himself under him to convey him on his back in safety to the shore.
% dependencies.
root(2,root,see).
det(2,dolphin,a).
nsubj(2,see,dolphin).
det(2,monkey,the).
nsubj(2,come,monkey).
nsubj(2,place,monkey).
dep(2,monkey,contend).
case(2,wave,with).
det(2,wave,the).
nmod:with(2,contend,wave).
cc(2,contend,and).
dep(2,monkey,suppose).
conj:and(2,contend,suppose).
dobj(2,suppose,he).
nsubj:xsubj(2,man,he).
mark(2,man,to).
cop(2,man,be).
det(2,man,a).
xcomp(2,suppose,man).
punct(2,say,-LRB-).
dobj(2,befriend,whom).
nsubjpass(2,say,he).
nsubj:xsubj(2,befriend,he).
auxpass(2,say,be).
advmod(2,say,always).
dep(2,man,say).
mark(2,befriend,to).
xcomp(2,say,befriend).
punct(2,say,-RRB-).
ccomp(2,see,come).
cc(2,come,and).
ccomp(2,see,place).
conj:and(2,come,place).
dobj(2,place,himself).
case(2,he,under).
nmod:under(2,place,he).
mark(2,convey,to).
advcl:to(2,place,convey).
dobj(2,convey,he).
case(2,back,on).
nmod:poss(2,back,he).
nmod:on(2,convey,back).
case(2,safety,in).
nmod:in(2,back,safety).
case(2,shore,to).
det(2,shore,the).
nmod:to(2,convey,shore).
% relations.
be(2,he,man).
be(2,he,always_say).
be_in(2,he_back,safety).
place(2,monkey,himself).
be(2,he,say).
%% when the dolphin arrived with his burden in sight of land not far from athens he asked the monkey if he were an athenian.
% dependencies.
root(3,root,arrive).
advmod(3,arrive,when).
det(3,dolphin,the).
nsubj(3,arrive,dolphin).
case(3,burden,with).
nmod:poss(3,burden,he).
nmod:with(3,arrive,burden).
case(3,sight,in).
nmod:in(3,burden,sight).
case(3,land,of).
nmod:of(3,sight,land).
dep(3,far,not).
advmod(3,arrive,far).
case(3,athen,from).
nmod:from(3,arrive,athen).
nsubj(3,ask,he).
acl:relcl(3,athen,ask).
det(3,monkey,the).
dobj(3,ask,monkey).
mark(3,athenian,if).
nsubj(3,athenian,he).
cop(3,athenian,be).
det(3,athenian,a).
advcl:if(3,ask,athenian).
% relations.
arrive_far_with(3,dolphin,he_burden).
arrive_far_with(3,dolphin,he_burden_in_sight_of_land).
ask(3,he,monkey).
be_in(3,he_burden,sight_of_land).
arrive_with(3,dolphin,he_burden_in_sight_of_land).
arrive_with(3,dolphin,he_burden_in_sight).
arrive_with(3,dolphin,he_burden).
be(3,he,athenian).
ask_monkey(3,he,athenian).
arrive_far_with(3,dolphin,he_burden_in_sight).
%% the latter replied that he was and that he was descended from one of the most noble families in that city.
% dependencies.
root(4,root,reply).
det(4,latter,the).
nsubj(4,reply,latter).
mark(4,be,that).
nsubj(4,be,he).
ccomp(4,reply,be).
cc(4,be,and).
mark(4,descend,that).
nsubjpass(4,descend,he).
auxpass(4,descend,be).
ccomp(4,reply,descend).
conj:and(4,be,descend).
case(4,one,from).
det:qmod(4,family,one).
mwe(4,one,of).
det(4,family,the).
advmod(4,noble,most).
amod(4,family,noble).
nmod(4,descend,family).
case(4,city,in).
det(4,city,that).
nmod:in(4,family,city).
% relations.
be_in(4,noble_family,city).
be(4,he,descend).
%% the dolphin then inquired if he knew the piraeus ( the famous harbor of athens ).
% dependencies.
root(5,root,inquire).
det(5,dolphin,the).
nsubj(5,inquire,dolphin).
advmod(5,inquire,then).
mark(5,know,if).
nsubj(5,know,he).
advcl:if(5,inquire,know).
det(5,piraeus,the).
dobj(5,know,piraeus).
punct(5,harbor,-LRB-).
det(5,harbor,the).
amod(5,harbor,famous).
dep(5,piraeus,harbor).
case(5,athen,of).
nmod:of(5,harbor,athen).
punct(5,harbor,-RRB-).
% relations.
inquire(5,dolphin,he_know).
know(5,he,piraeus).
%% supposing that a man was meant the monkey answered that he knew him very well and that he was an intimate friend.
% dependencies.
root(6,root,suppose).
mark(6,mean,that).
det(6,man,a).
nsubjpass(6,mean,man).
auxpass(6,mean,be).
ccomp(6,suppose,mean).
det(6,monkey,the).
dobj(6,mean,monkey).
acl(6,monkey,answer).
mark(6,know,that).
nsubj(6,know,he).
ccomp(6,answer,know).
dobj(6,know,he).
advmod(6,well,very).
advmod(6,know,well).
cc(6,know,and).
mark(6,friend,that).
nsubj(6,friend,he).
cop(6,friend,be).
det(6,friend,a).
amod(6,friend,intimate).
ccomp(6,answer,friend).
conj:and(6,know,friend).
% relations.
be(6,he,intimate).
%% the dolphin indignant at these falsehoods dipped the monkey under the water and drowned him.
% dependencies.
root(7,root,dip).
det(7,indignant,the).
compound(7,indignant,dolphin).
nsubj(7,dip,indignant).
nsubj(7,drown,indignant).
case(7,falsehood,at).
det(7,falsehood,these).
nmod:at(7,indignant,falsehood).
det(7,monkey,the).
dobj(7,dip,monkey).
case(7,water,under).
det(7,water,the).
nmod:under(7,dip,water).
cc(7,dip,and).
conj:and(7,dip,drown).
dobj(7,drown,he).
% relations.
drown(7,dolphin_indignant,he).
dip(7,dolphin_indignant,monkey).
dip_monkey_under(7,dolphin_indignant,water).
