root(0,ROOT,bitten).
det(0,bull,a).
nsubjpass(0,bitten,bull).
nsubjpass(0,angered,bull).
auxpass(0,bitten,was).
case(0,mouse,by).
det(0,mouse,a).
nmod:agent(0,bitten,mouse).
cc(0,bitten,and).
conj:and(0,bitten,angered).
case(0,wound,by).
det(0,wound,the).
nmod:by(0,angered,wound).
acl:relcl(0,wound,tried).
mark(0,capture,to).
xcomp(0,tried,capture).
dobj(0,capture,him).
was(0,bull,bitten).
was_bitten_by(0,bull,mouse).
root(1,ROOT,reached).
cc(1,reached,but).
det(1,mouse,the).
nsubj(1,reached,mouse).
nmod:poss(1,hole,his).
dobj(1,reached,hole).
case(1,safety,in).
nmod:in(1,reached,safety).
reached(1,mouse,his_hole).
root(2,ROOT,dug).
mark(2,dug,though).
det(2,bull,the).
nsubj(2,dug,bull).
case(2,walls,into).
det(2,walls,the).
nmod:into(2,dug,walls).
case(2,horns,with).
nmod:poss(2,horns,his).
nmod:with(2,walls,horns).
nsubj(2,tired,he).
ccomp(2,dug,tired).
mark(2,rout,before).
nsubj(2,rout,he).
aux(2,rout,could).
advcl:before(2,tired,rout).
case(2,mouse,out).
det(2,mouse,the).
nmod:out(2,rout,mouse).
cc(2,rout,and).
csubj(2,went,crouching).
compound:prt(2,crouching,down).
advcl:before(2,tired,went).
conj:and(2,rout,went).
mark(2,sleep,to).
xcomp(2,went,sleep).
case(2,hole,outside).
det(2,hole,the).
nmod:outside(2,sleep,hole).
tired(2,he,he_could_rout).
dug_into(2,bull,walls_with_his_horns).
dug_into(2,bull,walls).
could_rout_out(2,he,mouse).
tired(2,he,he_could_rout_out_mouse).
is_with(2,walls,his_horns).
root(3,ROOT,peeped).
det(3,mouse,the).
nsubj(3,peeped,mouse).
compound:prt(3,peeped,out).
dep(3,peeped,crept).
advmod(3,crept,furtively).
case(3,flank,up).
nmod:poss(3,flank,his).
nmod:up(3,crept,flank).
cc(3,crept,and).
advmod(3,biting,again).
dep(3,peeped,biting).
conj:and(3,crept,biting).
nsubj(3,retreated,him).
ccomp(3,biting,retreated).
case(3,hole,to).
nmod:poss(3,hole,his).
nmod:to(3,retreated,hole).
retreated_to(3,him,his_hole).
root(4,ROOT,perplexed).
det(4,bull,the).
nsubj(4,perplexed,bull).
dep(4,bull,rising).
compound:prt(4,rising,up).
cc(4,rising,and).
neg(4,knowing,not).
dep(4,bull,knowing).
conj:and(4,rising,knowing).
nsubj(4,do,what).
mark(4,do,to).
ccomp(4,knowing,do).
cop(4,perplexed,was).
advmod(4,perplexed,sadly).
was(4,bull,sadly_perplexed).
root(5,ROOT,said).
case(5,which,at).
nmod:at(5,said,which).
det(5,mouse,the).
nsubj(5,said,mouse).
root(6,ROOT,prevail).
det(6,great,the).
dep(6,prevail,great).
aux(6,prevail,do).
neg(6,prevail,not).
advmod(6,prevail,always).
root(7,ROOT,are).
expl(7,are,there).
nsubj(7,are,times).
advmod(7,strongest,when).
dep(7,small,the).
nsubj(7,strongest,small).
cc(7,small,and).
conj:and(7,small,lowly).
nsubj(7,strongest,lowly).
cop(7,strongest,are).
det(7,strongest,the).
acl:relcl(7,times,strongest).
mark(7,do,to).
dep(7,strongest,do).
dobj(7,do,mischief).
are(7,lowly,when_strongest).
are(7,lowly,strongest).
do(7,lowly,mischief).
are(7,small,strongest).
are(7,small,when_strongest).
