root(0,ROOT,came).
det(0,lion,a).
nsubj(0,came,lion).
case(0,hare,across).
det(0,hare,a).
nmod:across(0,came,hare).
nsubj(0,asleep,hare).
ref(0,hare,who).
cop(0,asleep,was).
advmod(0,asleep,fast).
acl:relcl(0,hare,asleep).
root(1,ROOT,act).
nsubj(1,act,he).
cop(1,act,was).
advmod(1,act,just).
case(1,act,in).
det(1,act,the).
mark(1,seizing,of).
acl:of(1,act,seizing).
dobj(1,seizing,her).
advmod(1,trotted,when).
det(1,hart,a).
amod(1,hart,fine).
amod(1,hart,young).
nsubj(1,trotted,hart).
advcl(1,seizing,trotted).
nmod(1,trotted,by).
cc(1,trotted,and).
nsubj(1,left,he).
advcl(1,seizing,left).
conj:and(1,trotted,left).
det(1,hare,the).
dobj(1,left,hare).
mark(1,follow,to).
acl:to(1,hare,follow).
dobj(1,follow,him).
root(2,ROOT,awoke).
det(2,hare,the).
nsubj(2,awoke,hare).
nsubj(2,scudded,hare).
acl(2,hare,scared).
case(2,noise,by).
det(2,noise,the).
nmod:by(2,scared,noise).
cc(2,awoke,and).
conj:and(2,awoke,scudded).
advmod(2,scudded,away).
root(3,ROOT,unable).
det(3,lion,the).
nsubj(3,unable,lion).
nsubj:xsubj(3,catch,lion).
nsubj(3,returned,lion).
nsubj:xsubj(3,feed,lion).
cop(3,unable,was).
case(3,chase,after).
det(3,chase,a).
amod(3,chase,long).
nmod:after(3,unable,chase).
mark(3,catch,to).
xcomp(3,unable,catch).
det(3,hart,the).
dobj(3,catch,hart).
cc(3,unable,and).
conj:and(3,unable,returned).
mark(3,feed,to).
xcomp(3,returned,feed).
case(3,hare,upon).
det(3,hare,the).
nmod:upon(3,feed,hare).
was(3,lion,unable).
catch(3,lion,hart).
was_unable_after(3,lion,chase).
returned(3,lion,feed).
was_unable_after(3,lion,long_chase).
returned(3,lion,feed_upon_hare).
root(4,ROOT,finding).
mark(4,finding,on).
mark(4,run,that).
det(4,hare,the).
nsubj(4,run,hare).
advmod(4,run,also).
aux(4,run,had).
ccomp(4,finding,run).
mark(4,said,off).
nsubj(4,said,he).
advcl:off(4,run,said).
run(4,hare,he_said).
also_run(4,hare,he_said).
root(5,ROOT,served).
nsubjpass(5,served,i).
auxpass(5,served,am).
advmod(5,served,rightly).
mark(5,having,for).
advcl:for(5,served,having).
ccomp(5,having,let).
xcomp(5,let,go).
case(5,food,of).
det(5,food,the).
nmod:of(5,go,food).
dobj(5,had,food).
ref(5,food,that).
nsubj(5,had,i).
acl:relcl(5,food,had).
case(5,hand,in).
nmod:poss(5,hand,my).
nmod:in(5,had,hand).
case(5,chance,for).
det(5,chance,the).
nmod:for(5,go,chance).
mark(5,obtaining,of).
acl:of(5,chance,obtaining).
dobj(5,obtaining,more).
am_served(5,i,having).
am(5,i,served).
am_rightly_served(5,i,having).
am(5,i,rightly_served).
had_in(5,i,my_hand).
