root(0,ROOT,days).
dep(0,days,in).
det(0,days,the).
amod(0,days,old).
advmod(0,allowed,when).
nsubjpass(0,allowed,men).
nsubj:xsubj(0,have,men).
auxpass(0,allowed,were).
acl:relcl(0,days,allowed).
mark(0,have,to).
xcomp(0,allowed,have).
amod(0,wives,many).
dobj(0,have,wives).
nsubj(0,old,wives).
det(0,man,a).
amod(0,man,middle-aged).
nsubj(0,had,man).
acl:relcl(0,wives,had).
nummod(0,wife,one).
dobj(0,had,wife).
nsubj(0,old,wife).
ref(0,wives,that).
ref(0,wife,that).
cop(0,old,was).
acl:relcl(0,wife,old).
cc(0,days,and).
conj:and(0,days,one).
nsubj(0,young,one).
ref(0,one,that).
cop(0,young,was).
acl:relcl(0,one,young).
were(0,men,allowed).
were(0,men,when_allowed).
root(1,ROOT,loved).
nsubj(1,loved,each).
dobj(1,loved,him).
advmod(1,much,very).
xcomp(1,loved,much).
cc(1,much,and).
xcomp(1,loved,desired).
conj:and(1,much,desired).
mark(1,see,to).
xcomp(1,desired,see).
dobj(1,see,him).
case(1,herself,like).
nmod:like(1,see,herself).
loved(1,each,him).
root(2,ROOT,turning).
advmod(2,turning,now).
det(2,man,the).
nmod:poss(2,hair,man).
case(2,man,'s).
nsubj(2,turning,hair).
aux(2,turning,was).
xcomp(2,turning,grey).
dobj(2,like,which).
det(2,wife,the).
amod(2,wife,young).
nsubj(2,like,wife).
aux(2,like,did).
neg(2,like,not).
ccomp(2,turning,like).
mark(2,made,as).
nsubj(2,made,it).
advcl:as(2,like,made).
nsubj(2,look,him).
ccomp(2,made,look).
advmod(2,old,too).
xcomp(2,look,old).
case(2,husband,for).
nmod:poss(2,husband,her).
nmod:for(2,old,husband).
has(2,man,hair).
root(3,ROOT,night).
dep(3,night,so).
det(3,night,every).
nsubj(3,used,she).
nsubj:xsubj(3,comb,she).
nsubj:xsubj(3,pick,she).
ccomp(3,night,used).
mark(3,comb,to).
xcomp(3,used,comb).
nmod:poss(3,hair,his).
dobj(3,comb,hair).
cc(3,comb,and).
xcomp(3,used,pick).
conj:and(3,comb,pick).
compound:prt(3,pick,out).
det(3,ones,the).
amod(3,ones,white).
dobj(3,pick,ones).
root(4,ROOT,saw).
cc(4,saw,but).
det(4,wife,the).
amod(4,wife,elder).
nsubj(4,saw,wife).
nmod:poss(4,husband,her).
dobj(4,saw,husband).
xcomp(4,saw,growing).
xcomp(4,growing,grey).
case(4,pleasure,with).
amod(4,pleasure,great).
nmod:with(4,grey,pleasure).
mark(4,like,for).
nsubj(4,like,she).
nsubjpass:xsubj(4,mistaken,she).
aux(4,like,did).
neg(4,like,not).
advcl:for(4,growing,like).
mark(4,mistaken,to).
auxpass(4,mistaken,be).
xcomp(4,like,mistaken).
case(4,mother,for).
nmod:poss(4,mother,his).
nmod:for(4,mistaken,mother).
saw(4,wife,her_husband).
saw(4,elder_wife,her_husband).
be_mistaken_for(4,she,his_mother).
be_mistaken_for(4,she,mother).
root(5,ROOT,morning).
dep(5,morning,so).
det(5,morning,every).
nsubj(5,used,she).
nsubj:xsubj(5,arrange,she).
nsubj:xsubj(5,pick,she).
ccomp(5,morning,used).
mark(5,arrange,to).
xcomp(5,used,arrange).
nmod:poss(5,hair,his).
dobj(5,arrange,hair).
cc(5,arrange,and).
xcomp(5,used,pick).
conj:and(5,arrange,pick).
compound:prt(5,pick,out).
case(5,many,as).
det:qmod(5,ones,many).
mwe(5,many,of).
det(5,ones,the).
amod(5,ones,black).
nmod(5,pick,ones).
mark(5,could,as).
nsubj(5,could,she).
advcl:as(5,pick,could).
root(6,ROOT,man).
det(6,consequence,the).
nsubj(6,man,consequence).
cop(6,man,was).
det(6,man,the).
advmod(6,found,soon).
acl(6,man,found).
nsubj(6,bald,himself).
advmod(6,bald,entirely).
xcomp(6,found,bald).
was(6,consequence,man).
was(6,consequence,man_soon_found).
was(6,consequence,man_found).
