root(0,ROOT,wearing).
det(0,lion,a).
amod(0,lion,funny).
amod(0,lion,old).
nsubj(0,had,lion).
nsubj(0,wearing,lion).
ref(0,lion,who).
acl:relcl(0,lion,had).
det(0,misfortune,the).
dobj(0,had,misfortune).
mark(0,lose,to).
acl:to(0,misfortune,lose).
nmod:poss(0,mane,his).
dobj(0,lose,mane).
aux(0,wearing,was).
det(0,wig,a).
dobj(0,wearing,wig).
mark(0,taking,as).
nsubj(0,taking,he).
aux(0,taking,was).
advcl:as(0,wearing,taking).
nsubj(0,stroll,a).
ccomp(0,taking,stroll).
case(0,day,on).
det(0,day,a).
advmod(0,windy,very).
amod(0,day,windy).
nmod:on(0,stroll,day).
root(1,ROOT,looking).
mark(1,spied,up).
nsubj(1,spied,he).
advcl:up(1,looking,spied).
det:qmod(1,sisters,one).
mwe(1,one,of).
det(1,sisters,the).
amod(1,sisters,charming).
compound(1,sisters,tiger).
dobj(1,spied,sisters).
case(1,street,across).
det(1,street,the).
nmod:across(1,spied,street).
cc(1,looking,and).
conj:and(1,looking,wishing).
mark(1,make,to).
xcomp(1,wishing,make).
det(1,impression,an).
nsubj(1,smiled,impression).
nsubj(1,made,impression).
ccomp(1,make,smiled).
advmod(1,smiled,blandly).
cc(1,smiled,and).
ccomp(1,make,made).
conj:and(1,smiled,made).
det(1,bow,a).
amod(1,bow,beautiful).
amod(1,bow,low).
dobj(1,made,bow).
made(1,impression,beautiful_low_bow).
made(1,impression,beautiful_bow).
made(1,impression,bow).
made(1,impression,low_bow).
root(2,ROOT,moment).
dep(2,moment,at).
det(2,moment,that).
det(2,gust,a).
advmod(2,smart,very).
amod(2,gust,smart).
nsubj(2,came,gust).
case(2,wind,of).
nmod:of(2,gust,wind).
acl:relcl(2,moment,came).
advmod(2,came,up).
cc(2,came,and).
det(2,consequence,the).
nsubj(2,was,consequence).
acl:relcl(2,moment,was).
conj:and(2,came,was).
mark(2,flew,that).
nmod:poss(2,wig,his).
nsubj(2,flew,wig).
nsubj(2,left,wig).
ccomp(2,was,flew).
advmod(2,flew,off).
cc(2,flew,and).
ccomp(2,was,left).
conj:and(2,flew,left).
nsubj(2,feeling,him).
nsubj(2,looking,him).
expl(2,feeling,there).
xcomp(2,left,feeling).
xcomp(2,feeling,foolish).
cc(2,feeling,and).
xcomp(2,left,looking).
conj:and(2,feeling,looking).
xcomp(2,looking,worse).
case(2,head,with).
nmod:poss(2,head,his).
amod(2,head,bald).
nmod:with(2,moment,head).
acl(2,head,glistening).
case(2,ball,like).
det(2,ball,a).
amod(2,ball,billiard).
nmod:like(2,glistening,ball).
feeling(2,him,foolish).
looking(2,him,worse).
left(2,his_wig,him_feeling).
is_with(2,moment,his_bald_head_glistening_like_billiard_ball).
root(3,ROOT,smiled).
mark(3,smiled,though).
advmod(3,embarrassed,somewhat).
advcl(3,smiled,embarrassed).
case(3,first,at).
advcl:at(3,embarrassed,first).
nsubj(3,smiled,he).
nsubj(3,said,he).
case(3,lady,at).
det(3,lady,the).
nmod:at(3,smiled,lady).
cc(3,smiled,and).
conj:and(3,smiled,said).
smiled_at(3,he,lady).
root(4,ROOT,it).
cop(4,it,is).
det(4,wonder,a).
nsubj(4,it,wonder).
mark(4,keep,that).
det(4,fellow,another).
nmod:poss(4,hair,fellow).
case(4,fellow,'s).
nsubj(4,keep,hair).
aux(4,keep,should).
neg(4,keep,n't).
dep(4,it,keep).
case(4,head,on).
nmod:poss(4,head,my).
nmod:on(4,keep,head).
advmod(4,stay,when).
nmod:poss(4,own,my).
nsubj(4,stay,own).
aux(4,stay,would).
neg(4,stay,n't).
advcl(4,keep,stay).
advmod(4,stay,there).
has(4,fellow,hair).
