root(0,ROOT,lay).
det(0,boy,a).
amod(0,boy,little).
nsubj(0,lay,boy).
acl(0,boy,wearied).
case(0,journey,with).
det(0,journey,a).
amod(0,journey,long).
nmod:with(0,wearied,journey).
compound:prt(0,lay,down).
dep(0,lay,overcome).
case(0,fatigue,with).
nmod:with(0,overcome,fatigue).
case(0,brink,on).
det(0,brink,the).
advmod(0,brink,very).
nmod:on(0,overcome,brink).
case(0,well,of).
dep(0,well,a).
advmod(0,well,deep).
acl:of(0,brink,well).
root(1,ROOT,inch).
cop(1,inch,being).
case(1,inch,within).
det(1,inch,an).
mark(1,falling,of).
acl:of(1,inch,falling).
case(1,water,into).
det(1,water,the).
nmod:into(1,falling,water).
ccomp(1,falling,dame).
dobj(1,dame,fortune).
nsubjpass(1,said,it).
auxpass(1,said,is).
dep(1,dame,said).
dep(1,said,appeared).
case(1,him,to).
nmod:to(1,appeared,him).
cc(1,falling,and).
acl:of(1,inch,waking).
conj:and(1,falling,waking).
dobj(1,waking,him).
case(1,slumber,from).
nmod:poss(1,slumber,his).
nmod:from(1,waking,slumber).
advmod(1,addressed,thus).
acl(1,slumber,addressed).
dobj(1,addressed,him).
appeared_to(1,it,him).
root(2,ROOT,boy).
amod(2,boy,little).
dep(2,boy,pray).
dobj(2,pray,wake).
advmod(2,pray,up).
case(2,had,for).
advcl:for(2,up,had).
nsubj(2,fallen,you).
ccomp(2,had,fallen).
case(2,well,into).
det(2,well,the).
nmod:into(2,fallen,well).
det(2,blame,the).
nsubjpass(2,thrown,blame).
aux(2,thrown,will).
auxpass(2,thrown,be).
dep(2,had,thrown).
case(2,me,on).
nmod:on(2,thrown,me).
cc(2,thrown,and).
nsubj(2,get,i).
aux(2,get,shall).
dep(2,had,get).
conj:and(2,thrown,get).
det(2,name,an).
amod(2,name,ill).
dobj(2,get,name).
case(2,mortals,among).
nmod:among(2,get,mortals).
root(3,ROOT,find).
mark(3,find,for).
nsubj(3,find,i).
det(3,men,that).
nsubj(3,sure,men).
nsubj:xsubj(3,blame,men).
cop(3,sure,are).
ccomp(3,find,sure).
mark(3,blame,to).
xcomp(3,sure,blame).
nmod:poss(3,calamities,their).
dobj(3,blame,calamities).
case(3,me,to).
nmod:to(3,blame,me).
advmod(3,folly,however).
advmod(3,folly,much).
case(3,folly,by).
nmod:poss(3,folly,their).
amod(3,folly,own).
nmod:by(3,blame,folly).
nsubj(3,brought,they).
aux(3,brought,have).
advmod(3,brought,really).
acl:relcl(3,folly,brought).
dobj(3,brought,them).
case(3,themselves,on).
nmod:on(3,brought,themselves).
blame(3,men,their_calamities).
have_really_brought(3,they,them).
are(3,men,sure).
have_brought(3,they,them).
