root(0,ROOT,lion).
det(0,lion,a).
dep(0,lion,growing).
amod(0,lay,old).
amod(0,sick,lay).
dobj(0,growing,sick).
case(0,cave,in).
nmod:poss(0,cave,his).
nmod:in(0,sick,cave).
root(1,ROOT,came).
det:predet(1,beasts,all).
det(1,beasts,the).
nsubj(1,came,beasts).
nsubj:xsubj(1,visit,beasts).
mark(1,visit,to).
xcomp(1,came,visit).
nmod:poss(1,king,their).
dobj(1,visit,king).
case(1,fox,except).
det(1,fox,the).
nmod:except(1,visit,fox).
visit(1,beasts,their_king).
root(2,ROOT,accused).
det(2,wolf,the).
nsubj(2,accused,wolf).
advmod(2,thinking,therefore).
acl(2,wolf,thinking).
mark(2,had,that).
nsubj(2,had,he).
ccomp(2,thinking,had).
det(2,opportunity,a).
compound(2,opportunity,capital).
dobj(2,had,opportunity).
det(2,fox,the).
dobj(2,accused,fox).
case(2,lion,to).
det(2,lion,the).
nmod:to(2,accused,lion).
mark(2,paying,of).
neg(2,paying,not).
acl:of(2,lion,paying).
det(2,respect,any).
dobj(2,paying,respect).
nsubj(2,had,respect).
case(2,him,to).
nmod:to(2,respect,him).
ref(2,respect,who).
acl:relcl(2,respect,had).
det(2,rule,the).
dobj(2,had,rule).
case(2,them,over).
nmod:over(2,rule,them).
det(2,them,all).
cc(2,lion,and).
mark(2,coming,of).
neg(2,coming,not).
nmod:to(2,accused,coming).
conj:and(2,lion,coming).
mark(2,visit,to).
xcomp(2,coming,visit).
dobj(2,visit,him).
accused(2,wolf,fox).
root(3,ROOT,moment).
case(3,that,at).
dep(3,moment,that).
advmod(3,moment,very).
det(3,fox,the).
nsubj(3,came,fox).
nsubj(3,heard,fox).
acl:relcl(3,moment,came).
nmod(3,came,in).
cc(3,came,and).
acl:relcl(3,moment,heard).
conj:and(3,came,heard).
det(3,words,these).
amod(3,words,last).
dobj(3,heard,words).
case(3,wolf,of).
det(3,wolf,the).
nmod:of(3,words,wolf).
heard(3,fox,last_words_of_wolf).
heard(3,fox,words_of_wolf).
heard(3,fox,words).
heard(3,fox,last_words).
words_of(3,heard,wolf).
last_words_of(3,heard,wolf).
root(4,ROOT,lion).
det(4,lion,the).
dep(4,lion,roaring).
compound:prt(4,roaring,out).
case(4,rage,in).
det(4,rage,a).
nmod:in(4,roaring,rage).
case(4,him,against).
nmod:against(4,rage,him).
det(4,fox,the).
nsubj(4,sought,fox).
nsubj(4,said,fox).
acl:relcl(4,rage,sought).
det(4,opportunity,an).
dobj(4,sought,opportunity).
mark(4,defend,to).
advcl:to(4,sought,defend).
dobj(4,defend,himself).
cc(4,sought,and).
acl:relcl(4,rage,said).
conj:and(4,sought,said).
defend(4,fox,himself).
sought(4,fox,opportunity).
root(5,ROOT,benefited).
cc(5,benefited,and).
nsubj(5,benefited,who).
case(5,those,of).
det:predet(5,those,all).
nsubj(5,come,those).
nmod:of(5,benefited,those).
ref(5,those,who).
aux(5,come,have).
acl:relcl(5,those,come).
case(5,you,to).
nmod:to(5,come,you).
aux(5,benefited,have).
dobj(5,benefited,you).
advmod(5,much,so).
advmod(5,benefited,much).
case(5,i,as).
nmod:as(5,benefited,i).
nsubj(5,traveled,i).
nsubj(5,sought,i).
ref(5,i,who).
aux(5,traveled,have).
acl:relcl(5,i,traveled).
case(5,place,from).
nmod:from(5,traveled,place).
case(5,place,to).
nmod:to(5,traveled,place).
case(5,direction,in).
det(5,direction,every).
nmod:in(5,place,direction).
cc(5,traveled,and).
aux(5,sought,have).
acl:relcl(5,i,sought).
conj:and(5,traveled,sought).
cc(5,sought,and).
conj:and(5,traveled,learnt).
conj:and(5,sought,learnt).
case(5,physicians,from).
det(5,physicians,the).
nmod:from(5,learnt,physicians).
det(5,means,the).
dobj(5,sought,means).
case(5,healing,of).
nmod:of(5,means,healing).
dobj(5,traveled,you).
is_in(5,place,direction).
root(6,ROOT,commanded).
punct(6,lion,').
det(6,lion,the).
nmod(6,commanded,lion).
dobj(6,commanded,him).
advmod(6,commanded,immediately).
mark(6,tell,to).
advcl:to(6,commanded,tell).
dobj(6,tell,him).
det(6,cure,the).
nsubj(6,commanded,cure).
advmod(6,replied,when).
nsubj(6,replied,he).
ccomp(6,cure,replied).
commanded(6,cure,him).
commanded_immediately(6,cure,him).
tell(6,cure,him).
root(7,ROOT,flay).
nsubj(7,flay,you).
nsubj(7,wrap,you).
aux(7,flay,must).
det(7,wolf,a).
nsubj(7,alive,wolf).
xcomp(7,flay,alive).
cc(7,flay,and).
conj:and(7,flay,wrap).
nmod:poss(7,skin,his).
nsubj(7,warm,skin).
advmod(7,warm,yet).
xcomp(7,wrap,warm).
case(7,you,around).
nmod:around(7,warm,you).
wrap(7,you,his_skin_warm).
wrap(7,you,his_skin_yet_warm_around_you).
warm_around(7,his_skin,you).
wrap(7,you,his_skin_warm_around_you).
must_flay(7,you,wolf_alive).
yet_warm_around(7,his_skin,you).
wrap(7,you,his_skin_yet_warm).
root(8,ROOT,taken).
det(8,wolf,the).
nsubjpass(8,taken,wolf).
nsubjpass(8,flayed,wolf).
auxpass(8,taken,was).
case(8,once,at).
advmod(8,taken,once).
cc(8,taken,and).
conj:and(8,taken,flayed).
was(8,wolf,at_once_taken).
was(8,wolf,taken).
root(9,ROOT,whereon).
det(9,fox,the).
nsubj(9,said,fox).
acl(9,fox,turning).
case(9,him,to).
nmod:to(9,turning,him).
acl:relcl(9,whereon,said).
case(9,smile,with).
det(9,smile,a).
nmod:with(9,said,smile).
said_with(9,fox,smile).
turning_to(9,fox,him).
root(10,ROOT,moved).
nsubj(10,moved,you).
nsubj(10,moved,you).
aux(10,moved,should).
aux(10,moved,have).
conj:but(10,moved,moved).
nmod:poss(10,master,your).
dobj(10,moved,master).
neg(10,ill,not).
case(10,ill,to).
nmod:to(10,moved,ill).
cc(10,moved,but).
case(10,good,to).
nmod:to(10,moved,good).
dep(10,good,will).
