root(0,ROOT,saw).
det(0,roaming,a).
compound(0,roaming,lion).
nsubj(0,saw,roaming).
nsubj(0,suggested,roaming).
case(0,seashore,by).
det(0,seashore,the).
nmod:by(0,roaming,seashore).
det(0,lift,a).
compound(0,lift,dolphin).
dobj(0,saw,lift).
case(0,head,up).
nmod:poss(0,head,its).
nmod:up(0,saw,head).
case(0,waves,out).
mwe(0,out,of).
det(0,waves,the).
nmod:out_of(0,saw,waves).
cc(0,saw,and).
conj:and(0,saw,suggested).
mark(0,contract,that).
nsubj(0,contract,they).
ccomp(0,suggested,contract).
det(0,alliance,an).
nsubj(0,saying,alliance).
dep(0,contract,saying).
mark(0,ought,that).
case(0,animals,of).
det:predet(0,animals,all).
det(0,animals,the).
nmod:of(0,ought,animals).
nsubj(0,ought,they).
nsubj:xsubj(0,friends,they).
ccomp(0,saying,ought).
mark(0,friends,to).
cop(0,friends,be).
det(0,friends,the).
amod(0,friends,best).
xcomp(0,ought,friends).
mark(0,king,since).
det(0,one,the).
nsubj(0,king,one).
cop(0,king,was).
det(0,king,the).
advcl:since(0,friends,king).
case(0,beasts,of).
nmod:of(0,king,beasts).
case(0,earth,on).
det(0,earth,the).
nmod:on(0,beasts,earth).
cc(0,ought,and).
det(0,other,the).
nsubj(0,ruler,other).
cop(0,ruler,was).
det(0,ruler,the).
amod(0,ruler,sovereign).
ccomp(0,saying,ruler).
conj:and(0,ought,ruler).
case(0,inhabitants,of).
det:predet(0,inhabitants,all).
det(0,inhabitants,the).
nmod:of(0,ruler,inhabitants).
case(0,ocean,of).
det(0,ocean,the).
nmod:of(0,inhabitants,ocean).
saw(0,lion_roaming,dolphin_lift).
saw_dolphin_lift_out_of(0,lion_roaming,waves).
root(1,ROOT,consented).
det(1,dolphin,the).
nsubj(1,consented,dolphin).
advmod(1,consented,gladly).
case(1,request,to).
det(1,request,this).
nmod:to(1,consented,request).
gladly_consented_to(1,dolphin,request).
consented_to(1,dolphin,request).
root(2,ROOT,long).
dep(2,long,not).
advmod(2,had,afterwards).
det(2,lion,the).
nsubj(2,had,lion).
nsubj(2,called,lion).
nsubj:xsubj(2,help,lion).
ccomp(2,long,had).
det(2,combat,a).
dobj(2,had,combat).
case(2,bull,with).
det(2,bull,a).
amod(2,bull,wild).
nmod:with(2,combat,bull).
cc(2,had,and).
ccomp(2,long,called).
conj:and(2,had,called).
case(2,dolphin,on).
det(2,dolphin,the).
nmod:on(2,called,dolphin).
mark(2,help,to).
xcomp(2,called,help).
dobj(2,help,him).
is_with(2,combat,wild_bull).
afterwards_had(2,lion,combat).
combat_with(2,lion,wild_bull).
combat_with(2,lion,bull).
called_on(2,lion,dolphin).
had(2,lion,combat_with_wild_bull).
afterwards_had(2,lion,combat_with_bull).
afterwards_had(2,lion,combat_with_wild_bull).
had(2,lion,combat).
had(2,lion,combat_with_bull).
root(3,ROOT,dolphin).
det(3,dolphin,the).
mark(3,unable,though).
advmod(3,willing,quite).
amod(3,assistance,willing).
mark(3,give,to).
xcomp(3,willing,give).
dobj(3,give,him).
nsubj(3,unable,assistance).
nsubj:xsubj(3,do,assistance).
cop(3,unable,was).
dep(3,dolphin,unable).
mark(3,do,to).
xcomp(3,unable,do).
advmod(3,reach,so).
mark(3,reach,as).
nsubj(3,reach,he).
aux(3,reach,could).
neg(3,reach,not).
case(3,means,by).
det(3,means,any).
nmod:by(3,reach,means).
advcl:as(3,do,reach).
det(3,land,the).
dobj(3,reach,land).
root(4,ROOT,abused).
det(4,lion,the).
nsubj(4,abused,lion).
dobj(4,abused,him).
case(4,traitor,as).
det(4,traitor,a).
nmod:as(4,abused,traitor).
abused(4,lion,him).
root(5,ROOT,replied).
det(5,dolphin,the).
nsubj(5,replied,dolphin).
root(6,ROOT,nay).
nmod:poss(6,blame,my).
compound(6,blame,friend).
dobj(6,nay,blame).
neg(6,me,not).
nmod(6,nay,me).
cc(6,nature,but).
dep(6,nay,nature).
nsubj(6,denied,nature).
ref(6,nature,which).
mark(6,denied,while).
csubj(6,denied,giving).
iobj(6,giving,me).
det(6,sovereignty,the).
dobj(6,giving,sovereignty).
case(6,sea,of).
det(6,sea,the).
nmod:of(6,sovereignty,sea).
aux(6,denied,has).
advmod(6,denied,quite).
acl:relcl(6,nature,denied).
dobj(6,denied,me).
det(6,power,the).
nsubj(6,nay,power).
mark(6,living,of).
acl:of(6,power,living).
case(6,land,upon).
det(6,land,the).
nmod:upon(6,living,land).
giving(6,me,me).
giving(6,me,sovereignty_of_sea).
giving(6,me,sovereignty).
