root(0,ROOT,man).
det(0,man,a).
cc(0,man,and).
det(0,lion,a).
conj:and(0,man,lion).
acl(0,man,traveled).
advmod(0,traveled,together).
case(0,forest,through).
det(0,forest,the).
nmod:through(0,traveled,forest).
traveled_together_through(0,man,forest).
traveled_through(0,man,forest).
root(1,ROOT,began).
nsubj(1,began,they).
nsubj:xsubj(1,boast,they).
advmod(1,began,soon).
mark(1,boast,to).
xcomp(1,began,boast).
case(1,superiority,of).
nmod:poss(1,superiority,their).
amod(1,superiority,respective).
nmod:of(1,boast,superiority).
case(1,other,to).
det(1,other,each).
nmod:to(1,boast,other).
case(1,strength,in).
nmod:in(1,other,strength).
cc(1,strength,and).
nmod:in(1,other,prowess).
conj:and(1,strength,prowess).
soon_began(1,they,boast).
began(1,they,boast_of_their_superiority).
began(1,they,boast_of_their_respective_superiority).
began(1,they,boast).
soon_began(1,they,boast_of_their_respective_superiority).
soon_began(1,they,boast_of_their_superiority).
boast_of(1,they,their_superiority).
boast_of(1,they,their_respective_superiority).
root(2,ROOT,disputing).
mark(2,disputing,as).
nsubj(2,disputing,they).
aux(2,disputing,were).
nsubj(2,passed,they).
ccomp(2,disputing,passed).
det(2,statue,a).
nsubj(2,carved,statue).
ccomp(2,passed,carved).
case(2,stone,in).
nmod:in(2,carved,stone).
nsubj(2,represented,stone).
ref(2,stone,which).
acl:relcl(2,stone,represented).
root(3,ROOT,strangled).
det(3,lion,a).
nsubj(3,strangled,lion).
case(3,man,by).
det(3,man,a).
nmod:by(3,strangled,man).
strangled_by(3,lion,man).
root(4,ROOT,pointed).
det(4,traveler,the).
nsubj(4,pointed,traveler).
nsubj(4,said,traveler).
case(4,it,to).
nmod:to(4,pointed,it).
cc(4,pointed,and).
conj:and(4,pointed,said).
pointed_to(4,traveler,it).
root(5,ROOT,see).
advmod(5,see,there).
root(6,ROOT,are).
advmod(6,strong,how).
dep(6,are,strong).
nsubj(6,are,we).
cc(6,are,and).
advmod(6,prevail,how).
nsubj(6,prevail,we).
conj:and(6,are,prevail).
case(6,king,over).
advmod(6,king,even).
det(6,king,the).
nmod:over(6,prevail,king).
case(6,beasts,of).
nmod:of(6,king,beasts).
prevail_over(6,we,even_king).
prevail_over(6,we,king).
prevail_over(6,we,king_of_beasts).
prevail_over(6,we,even_king_of_beasts).
root(7,ROOT,replied).
det(7,lion,the).
nsubj(7,replied,lion).
root(8,ROOT,made).
det(8,statue,this).
nsubjpass(8,made,statue).
auxpass(8,made,was).
case(8,one,by).
nmod:agent(8,made,one).
case(8,men,of).
dep(8,men,you).
nmod:of(8,one,men).
was_made_by(8,statue,one_of_men).
was_made_by(8,statue,one_men).
was(8,statue,made).
root(9,ROOT,knew).
mark(9,knew,if).
dep(9,lions,we).
nsubj(9,knew,lions).
advmod(9,erect,how).
mark(9,erect,to).
ccomp(9,knew,erect).
dobj(9,erect,statues).
nsubj(9,see,you).
aux(9,see,would).
acl:relcl(9,statues,see).
det(9,man,the).
dobj(9,see,man).
acl(9,man,placed).
case(9,paw,under).
det(9,paw,the).
nmod:under(9,placed,paw).
case(9,lion,of).
det(9,lion,the).
nmod:of(9,paw,lion).
would_see(9,you,man_placed_under_paw_of_lion).
would_see(9,you,man_placed).
would_see(9,you,man_placed_under_paw).
would_see(9,you,man).
