root(0,ROOT,fell).
det(0,lion,a).
nsubj(0,fell,lion).
nsubj(0,proposed,lion).
advmod(0,fell,once).
case(0,love,in).
nmod:in(0,fell,love).
case(0,maiden,with).
det(0,maiden,a).
amod(0,maiden,beautiful).
nmod:with(0,fell,maiden).
cc(0,fell,and).
conj:and(0,fell,proposed).
dobj(0,proposed,marriage).
case(0,parents,to).
nmod:poss(0,parents,her).
nmod:to(0,proposed,parents).
once_fell_with(0,lion,maiden).
proposed(0,lion,marriage).
fell_in(0,lion,love).
fell_with(0,lion,beautiful_maiden).
once_fell_in(0,lion,love).
fell_with(0,lion,maiden).
once_fell_with(0,lion,beautiful_maiden).
proposed_marriage_to(0,lion,her_parents).
root(1,ROOT,know).
det(1,people,the).
amod(1,people,old).
nsubj(1,know,people).
aux(1,know,did).
neg(1,know,not).
nsubj(1,say,what).
mark(1,say,to).
ccomp(1,know,say).
root(2,ROOT,like).
nsubj(2,like,they).
nsubj:xsubj(2,give,they).
aux(2,like,did).
neg(2,like,not).
mark(2,give,to).
xcomp(2,like,give).
nmod:poss(2,daughter,their).
dobj(2,give,daughter).
case(2,lion,to).
det(2,lion,the).
nmod:to(2,give,lion).
advmod(2,wish,yet).
nsubj(2,wish,they).
nsubj:xsubj(2,enrage,they).
aux(2,wish,did).
neg(2,wish,not).
dep(2,give,wish).
mark(2,enrage,to).
xcomp(2,wish,enrage).
det(2,king,the).
dobj(2,enrage,king).
case(2,beasts,of).
nmod:of(2,king,beasts).
enrage(2,they,king_of_beasts).
give_daughter_to(2,they,lion).
enrage(2,they,king).
root(3,ROOT,said).
case(3,last,at).
nmod:at(3,said,last).
det(3,father,the).
nsubj(3,said,father).
said_at(3,father,last).
root(4,ROOT,feel).
nsubj(4,feel,we).
advmod(4,honoured,highly).
xcomp(4,feel,honoured).
case(4,proposal,by).
nmod:poss(4,majesty,your).
nmod:poss(4,proposal,majesty).
case(4,majesty,'s).
nmod:by(4,honoured,proposal).
cc(4,feel,but).
nsubj(4,see,you).
conj:but(4,feel,see).
nmod:poss(4,daughter,our).
nsubj(4,thing,daughter).
cop(4,thing,is).
det(4,thing,a).
compound(4,thing,tender).
amod(4,thing,young).
ccomp(4,see,thing).
cc(4,feel,and).
nsubj(4,fear,we).
conj:but(4,feel,fear).
mark(4,do,that).
case(4,vehemence,in).
det(4,vehemence,the).
nmod:in(4,do,vehemence).
case(4,affection,of).
nmod:poss(4,affection,your).
nmod:of(4,vehemence,affection).
nsubj(4,do,you).
aux(4,do,might).
advmod(4,do,possibly).
ccomp(4,fear,do).
dep(4,do,her).
det(4,injury,some).
dobj(4,do,injury).
feel(4,we,highly_honoured_by_your_majesty_s_proposal).
possibly_do(4,you,injury).
do_injury_in(4,you,vehemence_of_your_affection).
is(4,daughter,young).
feel(4,we,highly_honoured).
is(4,our_daughter,tender_thing).
do(4,you,injury).
honoured_by(4,we,your_majesty_s_proposal).
feel(4,we,honoured).
feel(4,we,honoured_by_your_majesty_s_proposal).
possibly_do_injury_in(4,you,vehemence).
highly_honoured_by(4,we,your_majesty_s_proposal).
is(4,our_daughter,tender_young_thing).
do_injury_in(4,you,vehemence).
possibly_do_injury_in(4,you,vehemence_of_your_affection).
by(4,majesty,proposal).
root(5,ROOT,might).
nsubj(5,might,i).
mark(5,have,i).
nsubj(5,suggest,venture).
mark(5,suggest,to).
acl:relcl(5,i,suggest).
ref(5,i,that).
nmod:poss(5,majesty,your).
nsubj(5,have,majesty).
aux(5,have,should).
ccomp(5,suggest,have).
nmod:poss(5,claws,your).
dobj(5,have,claws).
acl(5,claws,removed).
cc(5,i,and).
nmod:poss(5,teeth,your).
nsubj(5,might,teeth).
conj:and(5,i,teeth).
mark(5,have,teeth).
acl(5,teeth,extracted).
advmod(5,extracted,then).
nsubj(5,consider,we).
aux(5,consider,would).
advmod(5,consider,gladly).
ccomp(5,extracted,consider).
nmod:poss(5,proposal,your).
dobj(5,consider,proposal).
advmod(5,consider,again).
gladly_consider_again(5,we,your_proposal).
consider_again(5,we,your_proposal).
gladly_consider(5,we,your_proposal).
consider(5,we,your_proposal).
root(6,ROOT,much).
det(6,lion,the).
nsubj(6,much,lion).
cop(6,much,was).
advmod(6,much,so).
case(6,love,in).
nmod:in(6,much,love).
mark(6,had,that).
nsubj(6,had,he).
ccomp(6,much,had).
nmod:poss(6,claws,his).
dobj(6,had,claws).
acl(6,claws,trimmed).
cc(6,claws,and).
nmod:poss(6,teeth,his).
amod(6,teeth,big).
dobj(6,had,teeth).
conj:and(6,claws,teeth).
acl(6,teeth,taken).
compound:prt(6,taken,out).
was(6,lion,much).
was_much_in(6,lion,love).
had(6,he,his_claws).
had(6,he,his_teeth).
had(6,he,his_claws_trimmed).
was_so_much_in(6,lion,love).
was(6,lion,so_much).
had(6,he,his_big_teeth).
root(7,ROOT,came).
cc(7,came,but).
advmod(7,came,when).
nsubj(7,came,he).
advmod(7,came,again).
case(7,parents,to).
det(7,parents,the).
nmod:to(7,came,parents).
case(7,girl,of).
det(7,girl,the).
amod(7,girl,young).
nmod:of(7,parents,girl).
nsubj(7,laughed,they).
nsubj(7,bade,they).
advmod(7,laughed,simply).
acl:relcl(7,girl,laughed).
case(7,face,in).
nmod:poss(7,face,his).
nmod:in(7,laughed,face).
cc(7,laughed,and).
acl:relcl(7,girl,bade).
conj:and(7,laughed,bade).
nsubj(7,do,him).
ccomp(7,bade,do).
nmod:poss(7,worst,his).
dobj(7,do,worst).
came_again_to(7,he,parents).
laughed_in(7,they,his_face).
do(7,him,his_worst).
came_to(7,he,parents).
simply_laughed_in(7,they,his_face).
