root(0,ROOT,deserved).
det(0,lioness,the).
dep(0,beasts,lioness).
nsubj(0,deserved,lioness).
det(0,controversy,a).
nsubj(0,prevailed,controversy).
acl:relcl(0,lioness,prevailed).
case(0,beasts,among).
det(0,beasts,the).
nmod:among(0,prevailed,beasts).
case(0,field,of).
det(0,field,the).
nmod:of(0,beasts,field).
mark(0,which,as).
case(0,which,to).
ref(0,lioness,which).
case(0,animals,of).
det(0,animals,the).
nmod:of(0,lioness,animals).
dobj(0,deserved,the).
advmod(0,the,most).
xcomp(0,deserved,credit).
mark(0,producing,for).
acl:for(0,credit,producing).
det(0,number,the).
amod(0,number,greatest).
dobj(0,producing,number).
case(0,whelps,of).
nmod:of(0,number,whelps).
case(0,birth,at).
det(0,birth,a).
nmod:at(0,whelps,birth).
prevailed_among(0,controversy,beasts).
prevailed_among(0,controversy,beasts_of_field).
producing(0,credit,number).
producing(0,credit,number_of_whelps).
producing(0,credit,number_of_whelps_at_birth).
producing(0,credit,greatest_number_of_whelps).
producing(0,credit,greatest_number_of_whelps_at_birth).
producing(0,credit,greatest_number).
root(1,ROOT,rushed).
nsubj(1,rushed,they).
nsubj(1,demanded,they).
advmod(1,rushed,clamorously).
case(1,presence,into).
det(1,presence,the).
nmod:into(1,rushed,presence).
case(1,lioness,of).
det(1,lioness,the).
nmod:of(1,presence,lioness).
cc(1,rushed,and).
conj:and(1,rushed,demanded).
case(1,settlement,of).
nmod:poss(1,settlement,her).
det(1,settlement,the).
nmod:of(1,demanded,settlement).
case(1,dispute,of).
det(1,dispute,the).
nmod:of(1,settlement,dispute).
rushed_into(1,they,presence_of_lioness).
rushed_clamorously_into(1,they,presence).
rushed_clamorously_into(1,they,presence_of_lioness).
rushed_into(1,they,presence).
demanded_of(1,they,her_settlement_of_dispute).
demanded_of(1,they,her_settlement).
root(2,ROOT,you).
cc(2,you,and).
root(3,ROOT,said).
nsubj(3,said,they).
root(4,ROOT,have).
advmod(4,many,how).
dep(4,have,many).
nsubj(4,have,sons).
dobj(4,have,you).
case(4,birth,at).
det(4,birth,a).
nmod:at(4,have,birth).
have(4,sons,you).
root(5,ROOT,laughed).
punct(5,laughed,').
det(5,lioness,the).
nsubj(5,laughed,lioness).
nsubj(5,said,lioness).
case(5,them,at).
nmod:at(5,laughed,them).
cc(5,laughed,and).
conj:and(5,laughed,said).
laughed_at(5,lioness,them).
root(6,ROOT,why).
root(7,ROOT,have).
nsubj(7,have,i).
advmod(7,one,only).
dobj(7,have,one).
have(7,i,only_one).
root(8,ROOT,lion).
cc(8,lion,but).
mark(8,lion,that).
nsubj(8,lion,one).
cop(8,lion,is).
advmod(8,lion,altogether).
det(8,lion,a).
amod(8,lion,thoroughbred).
is(8,one,altogether_thoroughbred_lion).
is(8,one,thoroughbred).
is(8,one,altogether_lion).
is(8,one,lion).
is(8,one,thoroughbred_lion).
