%% a funny old lion who had the misfortune to lose his mane was wearing a wig as he was taking a stroll on a very windy day.
% dependencies.
root(0,root,wear).
det(0,lion,a).
amod(0,lion,funny).
amod(0,lion,old).
nsubj(0,have,lion).
nsubj(0,wear,lion).
ref(0,lion,who).
acl:relcl(0,lion,have).
det(0,misfortune,the).
dobj(0,have,misfortune).
mark(0,lose,to).
acl:to(0,misfortune,lose).
nmod:poss(0,mane,he).
dobj(0,lose,mane).
aux(0,wear,be).
det(0,wig,a).
dobj(0,wear,wig).
mark(0,take,as).
nsubj(0,take,he).
aux(0,take,be).
advcl:as(0,wear,take).
nsubj(0,stroll,a).
ccomp(0,take,stroll).
case(0,day,on).
det(0,day,a).
advmod(0,windy,very).
amod(0,day,windy).
nmod:on(0,stroll,day).
% relations.
%% looking up he spied one of the charming tiger sisters across the street and wishing to make an impression smiled blandly and made a beautiful low bow.
% dependencies.
root(1,root,look).
mark(1,spy,up).
nsubj(1,spy,he).
advcl:up(1,look,spy).
det:qmod(1,sister,one).
mwe(1,one,of).
det(1,sister,the).
amod(1,sister,charming).
compound(1,sister,tiger).
dobj(1,spy,sister).
case(1,street,across).
det(1,street,the).
nmod:across(1,spy,street).
cc(1,look,and).
conj:and(1,look,wish).
mark(1,make,to).
xcomp(1,wish,make).
det(1,impression,a).
nsubj(1,smile,impression).
nsubj(1,make,impression).
ccomp(1,make,smile).
advmod(1,smile,blandly).
cc(1,smile,and).
ccomp(1,make,make).
conj:and(1,smile,make).
det(1,bow,a).
amod(1,bow,beautiful).
amod(1,bow,low).
dobj(1,make,bow).
% relations.
make(1,impression,beautiful_low_bow).
make(1,impression,beautiful_bow).
make(1,impression,bow).
make(1,impression,low_bow).
%% at that moment a very smart gust of wind came up and the consequence was that his wig flew off and left him there feeling foolish and looking worse with his bald head glistening like a billiard ball.
% dependencies.
root(2,root,moment).
dep(2,moment,at).
det(2,moment,that).
det(2,gust,a).
advmod(2,smart,very).
amod(2,gust,smart).
nsubj(2,come,gust).
case(2,wind,of).
nmod:of(2,gust,wind).
acl:relcl(2,moment,come).
advmod(2,come,up).
cc(2,come,and).
det(2,consequence,the).
nsubj(2,be,consequence).
acl:relcl(2,moment,be).
conj:and(2,come,be).
mark(2,fly,that).
nmod:poss(2,wig,he).
nsubj(2,fly,wig).
nsubj(2,leave,wig).
ccomp(2,be,fly).
advmod(2,fly,off).
cc(2,fly,and).
ccomp(2,be,leave).
conj:and(2,fly,leave).
nsubj(2,feel,he).
nsubj(2,look,he).
expl(2,feel,there).
xcomp(2,leave,feel).
xcomp(2,feel,foolish).
cc(2,feel,and).
xcomp(2,leave,look).
conj:and(2,feel,look).
xcomp(2,look,worse).
case(2,head,with).
nmod:poss(2,head,he).
amod(2,head,bald).
nmod:with(2,moment,head).
acl(2,head,glisten).
case(2,ball,like).
det(2,ball,a).
amod(2,ball,billiard).
nmod:like(2,glisten,ball).
% relations.
feel(2,he,foolish).
look(2,he,worse).
leave(2,he_wig,he_feel).
is_with(2,moment,he_bald_head_glisten_like_billiard_ball).
%% though somewhat embarrassed at first he smiled at the lady and said.
% dependencies.
root(3,root,smile).
mark(3,smile,though).
advmod(3,embarrassed,somewhat).
advcl(3,smile,embarrassed).
case(3,first,at).
advcl:at(3,embarrassed,first).
nsubj(3,smile,he).
nsubj(3,say,he).
case(3,lady,at).
det(3,lady,the).
nmod:at(3,smile,lady).
cc(3,smile,and).
conj:and(3,smile,say).
% relations.
smile_at(3,he,lady).
%% is it a wonder that another fellow 's hair should n't keep on my head when my own would n't stay there.
% dependencies.
root(4,root,it).
cop(4,it,be).
det(4,wonder,a).
nsubj(4,it,wonder).
mark(4,keep,that).
det(4,fellow,another).
nmod:poss(4,hair,fellow).
case(4,fellow,'s).
nsubj(4,keep,hair).
aux(4,keep,should).
neg(4,keep,not).
dep(4,it,keep).
case(4,head,on).
nmod:poss(4,head,my).
nmod:on(4,keep,head).
advmod(4,stay,when).
nmod:poss(4,own,my).
nsubj(4,stay,own).
aux(4,stay,would).
neg(4,stay,not).
advcl(4,keep,stay).
advmod(4,stay,there).
% relations.
has(4,fellow,hair).
