root(0,ROOT,had).
det(0,man,a).
nsubj(0,had,man).
det(0,wife,a).
dobj(0,had,wife).
nsubj(0,made,wife).
ref(0,wife,who).
acl:relcl(0,wife,made).
nsubj(0,hated,herself).
ccomp(0,made,hated).
case(0,members,by).
det:predet(0,members,all).
det(0,members,the).
nmod:by(0,hated,members).
case(0,household,of).
nmod:poss(0,household,his).
nmod:of(0,members,household).
hated_by(0,herself,members_of_household).
hated_by(0,herself,members_of_his_household).
root(1,ROOT,wishing).
mark(1,find,to).
xcomp(1,wishing,find).
compound:prt(1,find,out).
mark(1,had,if).
nsubj(1,had,she).
advcl:if(1,find,had).
det(1,effect,the).
amod(1,effect,same).
dobj(1,had,effect).
case(1,persons,on).
det(1,persons,the).
nmod:on(1,effect,persons).
case(1,house,in).
nmod:poss(1,father,her).
nmod:poss(1,house,father).
case(1,father,'s).
nmod:in(1,had,house).
nsubj(1,made,he).
acl:relcl(1,house,made).
det(1,excuse,some).
dobj(1,made,excuse).
mark(1,send,to).
acl:to(1,excuse,send).
nmod:poss(1,home,her).
dobj(1,send,home).
case(1,visit,on).
det(1,visit,a).
nmod:on(1,send,visit).
case(1,father,to).
nmod:poss(1,father,her).
nmod:to(1,visit,father).
effect_on(1,she,persons).
in(1,father,house).
had(1,she,same_effect).
had(1,she,effect).
had(1,she,same_effect_on_persons).
had(1,she,effect_on_persons).
same_effect_on(1,she,persons).
root(2,ROOT,time).
case(2,time,after).
det(2,time,a).
amod(2,time,short).
nsubj(2,returned,she).
acl:relcl(2,time,returned).
cc(2,time,and).
advmod(2,inquired,when).
nsubj(2,inquired,he).
conj:and(2,time,inquired).
advmod(2,got,how).
nsubj(2,got,she).
aux(2,got,had).
dep(2,inquired,got).
nmod(2,got,on).
cc(2,got,and).
advmod(2,treated,how).
det(2,servants,the).
nsubj(2,treated,servants).
aux(2,treated,had).
dep(2,inquired,treated).
conj:and(2,got,treated).
dobj(2,treated,her).
nsubj(2,replied,she).
dep(2,treated,replied).
had_treated(2,servants,her).
root(3,ROOT,looks).
det(3,herdsmen,the).
nsubj(3,looks,herdsmen).
cc(3,herdsmen,and).
conj:and(3,herdsmen,shepherds).
nsubj(3,looks,shepherds).
acl(3,herdsmen,cast).
case(3,me,on).
nmod:on(3,cast,me).
case(3,aversion,of).
nmod:of(3,looks,aversion).
looks_of(3,herdsmen,aversion).
looks_of(3,shepherds,aversion).
cast_on(3,herdsmen,me).
root(4,ROOT,said).
nsubj(4,said,he).
root(5,ROOT,wife).
compound(5,wife,o).
mark(5,disliked,if).
nsubjpass(5,disliked,you).
auxpass(5,disliked,were).
dep(5,wife,disliked).
case(5,those,by).
nmod:agent(5,disliked,those).
nsubj(5,go,those).
nsubj(5,return,those).
ref(5,those,who).
acl:relcl(5,those,go).
advmod(5,early,out).
advmod(5,go,early).
case(5,morning,in).
det(5,morning,the).
nmod:in(5,go,morning).
case(5,flocks,with).
nmod:poss(5,flocks,their).
nmod:with(5,morning,flocks).
cc(5,go,and).
acl:relcl(5,those,return).
conj:and(5,go,return).
advmod(5,return,late).
case(5,evening,in).
det(5,evening,the).
nmod:in(5,late,evening).
nsubjpass(5,felt,evening).
ref(5,evening,what).
aux(5,felt,must).
aux(5,felt,have).
auxpass(5,felt,been).
acl:relcl(5,evening,felt).
case(5,you,towards).
nmod:towards(5,felt,you).
case(5,those,by).
nmod:agent(5,felt,those).
mark(5,passed,with).
dobj(5,passed,whom).
nsubj(5,passed,you).
acl:with(5,those,passed).
det(5,day,the).
amod(5,day,whole).
nmod:tmod(5,passed,day).
is_with(5,morning,their_flocks).
were(5,you,disliked).
