root(0,ROOT,man).
det(0,man,a).
amod(0,man,middle-aged).
nmod:poss(0,hair,man).
ref(0,man,whose).
nsubj(0,begun,hair).
nsubj:xsubj(0,turn,hair).
aux(0,begun,had).
acl:relcl(0,man,begun).
mark(0,turn,to).
xcomp(0,begun,turn).
dobj(0,turn,gray).
acl(0,gray,courted).
nummod(0,women,two).
dobj(0,courted,women).
case(0,time,at).
det(0,time,the).
amod(0,time,same).
nmod:at(0,courted,time).
courted(0,gray,two_women).
turn(0,hair,gray).
root(1,ROOT,young).
det:qmod(1,them,one).
mwe(1,one,of).
nsubjpass(1,young,them).
nsubjpass(1,advanced,them).
auxpass(1,young,was).
cc(1,young,and).
det(1,other,the).
nmod:npmod(1,well,other).
advmod(1,advanced,well).
conj:and(1,young,advanced).
case(1,years,in).
nmod:in(1,advanced,years).
root(2,ROOT,ashamed).
det(2,woman,the).
amod(2,woman,elder).
dep(2,ashamed,woman).
mark(2,courted,to).
auxpass(2,courted,be).
xcomp(2,ashamed,courted).
case(2,younger,by).
det(2,younger,a).
dep(2,younger,man).
nmod:agent(2,courted,younger).
mark(2,made,than).
nsubj(2,made,herself).
dep(2,younger,made).
det(2,point,a).
dobj(2,made,point).
advmod(2,visited,whenever).
nmod:poss(2,admirer,her).
nsubj(2,visited,admirer).
advcl(2,made,visited).
dobj(2,visited,her).
nsubj:xsubj(2,pull,her).
mark(2,pull,to).
xcomp(2,visited,pull).
compound:prt(2,pull,out).
det(2,portion,some).
dobj(2,pull,portion).
case(2,hairs,of).
nmod:poss(2,hairs,his).
amod(2,hairs,black).
nmod:of(2,portion,hairs).
pull_out(2,her,portion_of_his_hairs).
pull_out(2,her,portion).
visited(2,her_admirer,her).
pull_out(2,her,portion_of_his_black_hairs).
root(3,ROOT,zealous).
det(3,younger,the).
nsubj(3,zealous,younger).
case(3,contrary,on).
det(3,contrary,the).
nmod:on(3,younger,contrary).
neg(3,wishing,not).
acl(3,contrary,wishing).
mark(3,become,to).
xcomp(3,wishing,become).
det(3,wife,the).
xcomp(3,become,wife).
case(3,man,of).
det(3,man,an).
amod(3,man,old).
nmod:of(3,wife,man).
cop(3,zealous,was).
advmod(3,zealous,equally).
mark(3,removing,in).
advcl:in(3,zealous,removing).
det(3,hair,every).
amod(3,hair,gray).
dobj(3,removing,hair).
nsubj(3,find,she).
aux(3,find,could).
acl:relcl(3,hair,find).
root(4,ROOT,came).
advmod(4,it,thus).
nsubj(4,came,it).
nsubj:xsubj(4,pass,it).
mark(4,pass,to).
xcomp(4,came,pass).
dobj(4,pass,that).
mark(4,had,that).
case(4,them,between).
nmod:between(4,that,them).
dobj(4,found,both).
nsubj(4,found,he).
advmod(4,soon,very).
advmod(4,found,soon).
acl:relcl(4,that,found).
ref(4,that,that).
nsubj(4,had,he).
ccomp(4,found,had).
neg(4,hair,not).
det(4,hair,a).
dobj(4,had,hair).
acl:relcl(4,hair,left).
case(4,head,on).
nmod:poss(4,head,his).
nmod:on(4,left,head).
found(4,he,both).
soon_found(4,he,both).
very_soon_found(4,he,both).
