root(0,ROOT,seated).
det(0,jackdaw,a).
amod(0,jackdaw,half-famished).
nsubj(0,seated,jackdaw).
nsubj(0,waited,jackdaw).
dobj(0,seated,himself).
case(0,fig-tree,on).
det(0,fig-tree,a).
nmod:on(0,seated,fig-tree).
nsubj(0,produced,fig-tree).
ref(0,fig-tree,which).
aux(0,produced,had).
acl:relcl(0,fig-tree,produced).
det(0,fruit,some).
nmod:npmod(0,entirely,fruit).
advmod(0,season,entirely).
case(0,season,out).
mwe(0,out,of).
nmod:out_of(0,produced,season).
cc(0,seated,and).
conj:and(0,seated,waited).
case(0,hope,in).
det(0,hope,the).
nmod:in(0,waited,hope).
mark(0,ripen,that).
det(0,figs,the).
nsubj(0,ripen,figs).
aux(0,ripen,would).
ccomp(0,waited,ripen).
waited_in(0,jackdaw,hope).
seated(0,jackdaw,himself).
waited_in(0,half-famished_jackdaw,hope).
seated(0,half-famished_jackdaw,himself).
root(1,ROOT,said).
det(1,fox,a).
nsubj(1,said,fox).
acl(1,fox,seeing).
nsubj(1,sitting,him).
nsubj(1,learning,him).
ccomp(1,seeing,sitting).
advmod(1,long,so).
advmod(1,sitting,long).
cc(1,sitting,and).
ccomp(1,seeing,learning).
conj:and(1,sitting,learning).
det(1,reason,the).
dobj(1,learning,reason).
case(1,his,of).
nmod:of(1,reason,his).
acl(1,reason,doing).
advmod(1,doing,so).
case(1,him,to).
nmod:to(1,said,him).
learning(1,him,reason_of_his_doing).
learning(1,him,reason_of_his_doing_so).
said_to(1,fox,him).
learning(1,him,reason_doing).
learning(1,him,reason).
learning(1,him,reason_doing_so).
learning(1,him,reason_of_his).
root(2,ROOT,sir).
nsubj(2,sir,you).
cop(2,sir,are).
advmod(2,sir,indeed).
advmod(2,sir,sadly).
dep(2,sir,deceiving).
dobj(2,deceiving,yourself).
are(2,you,indeed_sir).
are(2,you,sir).
are(2,you,sir_sadly).
are(2,you,indeed_sir_sadly).
root(3,ROOT,indulging).
nsubj(3,indulging,you).
aux(3,indulging,are).
det(3,hope,a).
dobj(3,indulging,hope).
amod(3,hope,strong).
advmod(3,strong,enough).
mark(3,cheat,to).
xcomp(3,strong,cheat).
dobj(3,cheat,you).
cc(3,indulging,but).
nsubj(3,reward,which).
aux(3,reward,will).
neg(3,reward,never).
conj:but(3,indulging,reward).
dobj(3,reward,you).
case(3,enjoyment,with).
nmod:with(3,reward,enjoyment).
are_indulging(3,you,hope).
are_indulging(3,you,hope_strong_enough).
are_indulging(3,you,hope_strong).
