%% a king whose only son was fond of martial exercises had a dream in which he was warned that his son would be killed by a lion.
% dependencies.
root(0,root,have).
det(0,king,a).
nmod:poss(0,son,king).
nsubj(0,have,king).
ref(0,king,whose).
amod(0,son,only).
nsubj(0,fond,son).
cop(0,fond,be).
acl:relcl(0,king,fond).
case(0,exercise,of).
amod(0,exercise,martial).
nmod:of(0,fond,exercise).
det(0,dream,a).
dobj(0,have,dream).
nmod:in(0,warn,dream).
case(0,which,in).
ref(0,dream,which).
nsubjpass(0,warn,he).
auxpass(0,warn,be).
acl:relcl(0,dream,warn).
mark(0,kill,that).
nmod:poss(0,son,he).
nsubjpass(0,kill,son).
aux(0,kill,would).
auxpass(0,kill,be).
ccomp(0,warn,kill).
case(0,lion,by).
det(0,lion,a).
nmod:agent(0,kill,lion).
% relations.
aos(0,be_fond_of,son,martial_exercise).
aos(0,be,he_son,kill).
aos(0,be_fond_of,only_son,exercise).
aos(0,be,son,fond).
aos(0,be_kill_by,he_son,lion).
aos(0,be_fond_of,only_son,martial_exercise).
aos(0,be,he,warn).
aos(0,be,only_son,fond).
aos(0,be_fond_of,son,exercise).
%% afraid the dream should prove true he built for his son a pleasant palace and adorned its walls for his amusement with all kinds of life-sized animals among which was the picture of a lion.
% dependencies.
root(1,root,kind).
amod(1,kind,afraid).
det(1,dream,the).
nsubj(1,prove,dream).
nsubj(1,adorn,dream).
aux(1,prove,should).
ccomp(1,afraid,prove).
xcomp(1,prove,true).
nsubj(1,build,he).
ccomp(1,true,build).
case(1,son,for).
nmod:poss(1,son,he).
nmod:for(1,build,son).
det(1,palace,a).
amod(1,palace,pleasant).
dobj(1,prove,palace).
cc(1,prove,and).
ccomp(1,afraid,adorn).
conj:and(1,prove,adorn).
nmod:poss(1,wall,its).
dobj(1,adorn,wall).
case(1,amusement,for).
nmod:poss(1,amusement,he).
nmod:for(1,adorn,amusement).
case(1,all,with).
nmod:with(1,adorn,all).
case(1,animal,of).
amod(1,animal,life-sized).
nmod:of(1,kind,animal).
mark(1,picture,among).
nsubj(1,picture,which).
cop(1,picture,be).
det(1,picture,the).
acl:among(1,animal,picture).
case(1,lion,of).
det(1,lion,a).
nmod:of(1,picture,lion).
% relations.
aos(1,prove,dream,pleasant_palace).
aos(1,build_for,he,he_son).
aos(1,prove,dream,true).
aos(1,adorn,dream,its_wall).
aos(1,prove,dream,palace).
%% when the young prince saw this his grief at being thus confined burst out afresh and standing near the lion he said.
% dependencies.
root(2,root,see).
advmod(2,see,when).
det(2,prince,the).
amod(2,prince,young).
nsubj(2,see,prince).
det:predet(2,grief,this).
nmod:poss(2,grief,he).
dobj(2,see,grief).
mark(2,confine,at).
auxpass(2,confine,be).
advmod(2,confine,thus).
advcl:at(2,see,confine).
dobj(2,confine,burst).
case(2,afresh,out).
nmod:out(2,confine,afresh).
cc(2,afresh,and).
nmod:out(2,confine,standing).
conj:and(2,afresh,standing).
case(2,lion,near).
det(2,lion,the).
nmod:near(2,standing,lion).
nsubj(2,say,he).
acl:relcl(2,lion,say).
% relations.
aos(2,be_thus_confine,prince,burst).
aos(2,be_confine,young_prince,burst).
aos(2,be_confine_burst_out,prince,afresh).
aos(2,be_confine,prince,burst).
aos(2,be_thus_confine_burst_out,prince,afresh).
aos(2,be_thus_confine,young_prince,burst).
aos(2,be_thus_confine_burst_out,young_prince,afresh).
aos(2,see,prince,he_grief).
aos(2,see,young_prince,he_grief).
aos(2,be_confine_burst_out,young_prince,afresh).
%% o you most detestable of animals.
% dependencies.
root(3,root,o).
dep(3,o,you).
advmod(3,detestable,most).
amod(3,you,detestable).
case(3,animal,of).
nmod:of(3,you,animal).
% relations.
%% through a lying dream of my father 's which he saw in his sleep i am shut up on your account in this palace as if i had been a girl what shall i now do to you.
% dependencies.
root(4,root,dream).
case(4,dream,through).
det(4,dream,a).
amod(4,dream,lie).
case(4,father,of).
nmod:poss(4,father,my).
nmod:'s(4,dream,father).
dobj(4,see,father).
case(4,father,'s).
ref(4,father,which).
nsubj(4,see,he).
advcl(4,shut,see).
case(4,sleep,in).
nmod:poss(4,sleep,he).
nmod:in(4,see,sleep).
nsubjpass(4,shut,i).
auxpass(4,shut,be).
acl:relcl(4,father,shut).
compound:prt(4,shut,up).
case(4,account,on).
nmod:poss(4,account,you).
nmod:on(4,shut,account).
case(4,palace,in).
det(4,palace,this).
nmod:in(4,account,palace).
mark(4,do,as).
mark(4,girl,if).
nsubj(4,girl,i).
aux(4,girl,have).
cop(4,girl,be).
det(4,girl,a).
nsubj(4,shall,girl).
advcl:if(4,do,girl).
ref(4,girl,what).
acl:relcl(4,girl,shall).
nsubj(4,do,i).
advmod(4,do,now).
advcl:as(4,shut,do).
case(4,you,to).
nmod:to(4,do,you).
% relations.
aos(4,is_in,you_account,palace).
aos(4,now_do_to,i,you).
aos(4,do_to,i,you).
aos(4,see_in,he,he_sleep).
aos(4,be_shut_up,i,i_do).
aos(4,be_shut_up_on,i,you_account_in_palace).
aos(4,be_shut_up,i,i_do_to_you).
aos(4,be_shut_up,i,i_now_do).
aos(4,be_shut_up_on,i,you_account).
aos(4,be_shut_up,i,i_now_do_to_you).
%% ' with these words he stretched out his hands toward a thorn-tree meaning to cut a stick from its branches so that he might beat the lion.
% dependencies.
root(5,root,stretch).
punct(5,word,').
case(5,word,with).
det(5,word,these).
advcl:with(5,stretch,word).
nsubj(5,stretch,he).
compound:prt(5,stretch,out).
nmod:poss(5,hand,he).
dobj(5,stretch,hand).
case(5,meaning,toward).
det(5,meaning,a).
amod(5,meaning,thorn-tree).
nmod:toward(5,hand,meaning).
mark(5,cut,to).
advcl:to(5,stretch,cut).
det(5,stick,a).
dobj(5,cut,stick).
case(5,branch,from).
nmod:poss(5,branch,its).
nmod:from(5,cut,branch).
mark(5,beat,so).
mwe(5,so,that).
nsubj(5,beat,he).
aux(5,beat,might).
advcl:so_that(5,cut,beat).
det(5,lion,the).
dobj(5,beat,lion).
% relations.
aos(5,might_beat,he,lion).
aos(5,stretch_out,he,he_hand).
aos(5,cut_stick_from,he,its_branch).
aos(5,stretch_out,he,he_hand_toward_meaning).
aos(5,cut,he,stick).
aos(5,stretch_out,he,he_hand_toward_thorn-tree_meaning).
%% but one of the tree 's prickles pierced his finger and caused great pain and inflammation so that the young prince fell down in a fainting fit.
% dependencies.
root(6,root,pierce).
cc(6,one,but).
nsubj(6,pierce,one).
nsubj(6,cause,one).
case(6,prickle,of).
det(6,tree,the).
nmod:poss(6,prickle,tree).
case(6,tree,'s).
nmod:of(6,one,prickle).
nmod:poss(6,finger,he).
dobj(6,pierce,finger).
cc(6,pierce,and).
conj:and(6,pierce,cause).
amod(6,pain,great).
dobj(6,cause,pain).
cc(6,pain,and).
dobj(6,cause,inflammation).
conj:and(6,pain,inflammation).
mark(6,fall,so).
mwe(6,so,that).
det(6,prince,the).
amod(6,prince,young).
nsubj(6,fall,prince).
advcl:so_that(6,cause,fall).
compound:prt(6,fall,down).
case(6,fit,in).
det(6,fit,a).
amod(6,fit,faint).
nmod:in(6,fall,fit).
% relations.
aos(6,of,tree,prickle).
aos(6,fall_down_in,prince,faint_fit).
aos(6,fall_down_in,prince,fit).
aos(6,fall_down_in,young_prince,faint_fit).
aos(6,fall_down_in,young_prince,fit).
%% a violent fever suddenly set in from which he died not many days later.
% dependencies.
root(7,root,set).
det(7,fever,a).
amod(7,fever,violent).
nsubj(7,set,fever).
advmod(7,set,suddenly).
case(7,die,in).
mark(7,die,from).
dobj(7,die,which).
nsubj(7,die,he).
dep(7,set,die).
neg(7,day,not).
amod(7,day,many).
nmod:tmod(7,die,day).
advmod(7,die,later).
% relations.
