root(0,ROOT,made).
det(0,lark,a).
nsubj(0,made,lark).
aux(0,made,had).
nmod:poss(0,nest,her).
dobj(0,made,nest).
case(0,spring,in).
det(0,spring,the).
amod(0,spring,early).
nmod:in(0,made,spring).
case(0,wheat,on).
det(0,wheat,the).
amod(0,wheat,young).
amod(0,wheat,green).
nmod:on(0,spring,wheat).
had_made(0,lark,her_nest).
root(1,ROOT,grown).
det(1,brood,the).
nsubj(1,grown,brood).
nsubj(1,attained,brood).
aux(1,grown,had).
advmod(1,grown,almost).
case(1,strength,to).
nmod:poss(1,strength,their).
amod(1,strength,full).
nmod:to(1,grown,strength).
cc(1,grown,and).
conj:and(1,grown,attained).
det(1,use,the).
dobj(1,attained,use).
case(1,wings,of).
nmod:poss(1,wings,their).
nmod:of(1,use,wings).
cc(1,use,and).
det(1,plumage,the).
amod(1,plumage,full).
dobj(1,attained,plumage).
conj:and(1,use,plumage).
case(1,feathers,of).
nmod:poss(1,feathers,their).
nmod:of(1,plumage,feathers).
advmod(1,said,when).
det(1,owner,the).
nsubj(1,said,owner).
case(1,field,of).
det(1,field,the).
nmod:of(1,owner,field).
acl(1,field,looking).
case(1,crop,over).
nmod:poss(1,crop,his).
amod(1,crop,ripe).
nmod:over(1,looking,crop).
advcl(1,attained,said).
attained(1,brood,use_of_their_wings).
full_plumage_of(1,use,their_feathers).
had_grown_to(1,brood,their_strength).
attained(1,brood,plumage_of_their_feathers).
had_almost_grown_to(1,brood,their_strength).
had_almost_grown_to(1,brood,their_full_strength).
attained(1,brood,plumage).
had_grown_to(1,brood,their_full_strength).
attained(1,brood,use).
attained(1,brood,full_plumage).
plumage_of(1,use,their_feathers).
attained(1,brood,full_plumage_of_their_feathers).
root(2,ROOT,come).
det(2,time,the).
nsubj(2,come,time).
aux(2,come,has).
advmod(2,ask,when).
nsubj(2,ask,i).
aux(2,ask,must).
advcl(2,come,ask).
det:predet(2,neighbors,all).
nmod:poss(2,neighbors,my).
dobj(2,ask,neighbors).
nsubj:xsubj(2,help,neighbors).
mark(2,help,to).
xcomp(2,ask,help).
dobj(2,help,me).
case(2,harvest,with).
nmod:poss(2,harvest,my).
nmod:with(2,help,harvest).
must_ask(2,i,my_neighbors).
must_ask(2,i,neighbors).
help(2,my_neighbors,me).
help(2,neighbors,me).
root(3,ROOT,heard).
det:qmod(3,larks,one).
mwe(3,one,of).
det(3,larks,the).
amod(3,larks,young).
nsubj(3,heard,larks).
nsubj(3,related,larks).
nmod:poss(3,speech,his).
dobj(3,heard,speech).
cc(3,heard,and).
conj:and(3,heard,related).
dobj(3,related,it).
case(3,mother,to).
nmod:poss(3,mother,his).
nmod:to(3,it,mother).
acl(3,mother,inquiring).
case(3,her,of).
nmod:of(3,inquiring,her).
case(3,place,to).
det(3,place,what).
nmod:to(3,inquiring,place).
nsubj(3,move,they).
aux(3,move,should).
acl:relcl(3,place,move).
case(3,safety,for).
nmod:for(3,move,safety).
should_move_for(3,they,safety).
root(4,ROOT,is).
expl(4,is,there).
neg(4,occasion,no).
nsubj(4,is,occasion).
mark(4,move,to).
acl:to(4,occasion,move).
advmod(4,move,yet).
nmod:poss(4,son,my).
dobj(4,move,son).
root(5,ROOT,replied).
nsubj(5,replied,she).
root(6,ROOT,earnest).
det(6,man,the).
nsubj(6,sends,man).
nsubj(6,earnest,man).
ref(6,man,who).
advmod(6,sends,only).
acl:relcl(6,man,sends).
case(6,friends,to).
nmod:poss(6,friends,his).
nmod:to(6,sends,friends).
mark(6,help,to).
acl:to(6,friends,help).
dobj(6,help,him).
case(6,harvest,with).
nmod:poss(6,harvest,his).
nmod:with(6,help,harvest).
cop(6,earnest,is).
neg(6,earnest,not).
advmod(6,earnest,really).
case(6,earnest,in).
root(7,ROOT,came).
det(7,owner,the).
nsubj(7,came,owner).
nsubj(7,saw,owner).
case(7,field,of).
det(7,field,the).
nmod:of(7,owner,field).
advmod(7,days,again).
det(7,days,a).
amod(7,days,few).
nmod:npmod(7,later,days).
advmod(7,came,later).
cc(7,came,and).
conj:and(7,came,saw).
det(7,wheat,the).
dobj(7,saw,wheat).
xcomp(7,saw,shedding).
det(7,grain,the).
dobj(7,shedding,grain).
case(7,excess,from).
nmod:from(7,shedding,excess).
case(7,ripeness,of).
nmod:of(7,excess,ripeness).
shedding(7,wheat,grain).
shedding_grain_from(7,wheat,excess).
shedding_grain_from(7,wheat,excess_of_ripeness).
saw(7,owner,wheat).
root(8,ROOT,said).
nsubj(8,said,he).
root(9,ROOT,come).
nsubj(9,come,i).
nsubj(9,come,i).
aux(9,come,will).
conj:and(9,come,come).
dobj(9,come,myself).
nmod:tmod(9,come,tomorrow).
case(9,laborers,with).
nmod:poss(9,laborers,my).
nmod:with(9,come,laborers).
cc(9,come,and).
case(9,reapers,with).
advmod(9,many,as).
nummod(9,reapers,many).
nmod:with(9,come,reapers).
mark(9,hire,as).
nsubj(9,hire,i).
nsubj(9,get,i).
aux(9,hire,can).
advcl:as(9,come,hire).
cc(9,hire,and).
aux(9,get,will).
advcl:as(9,come,get).
conj:and(9,hire,get).
case(9,harvest,in).
det(9,harvest,the).
nmod:in(9,get,harvest).
get_in(9,i,harvest).
will_come_with(9,i,many_reapers).
will_come_with(9,i,as_many_reapers).
will_come_with(9,i,reapers).
root(10,ROOT,said).
det(10,lark,the).
nsubj(10,said,lark).
mark(10,hearing,on).
acl:on(10,lark,hearing).
det(10,words,these).
dobj(10,hearing,words).
case(10,brood,to).
nmod:poss(10,brood,her).
nmod:to(10,said,brood).
root(11,ROOT,earnest).
nsubj(11,time,it).
nsubj:xsubj(11,ones,it).
aux(11,time,is).
dep(11,earnest,time).
advmod(11,time,now).
mark(11,ones,to).
cop(11,ones,be).
compound:prt(11,ones,off).
nmod:poss(11,ones,my).
amod(11,ones,little).
xcomp(11,time,ones).
case(11,man,for).
det(11,man,the).
nmod:for(11,ones,man).
cop(11,earnest,is).
case(11,earnest,in).
det(11,time,this).
nsubj(11,earnest,time).
is_in(11,time,earnest).
root(12,ROOT,friends).
nsubj(12,friends,he).
nsubj(12,reap,he).
advmod(12,friends,no).
advmod(12,trusts,longer).
nmod:npmod(12,no,trusts).
nmod:poss(12,friends,his).
cc(12,friends,but).
aux(12,reap,will).
conj:but(12,friends,reap).
det(12,field,the).
nsubj(12,himself,field).
xcomp(12,reap,himself).
reap(12,he,field_himself).
