root(0,ROOT,fell).
det(0,lion,a).
nsubj(0,fell,lion).
acl(0,lion,fatigued).
case(0,heat,by).
det(0,heat,the).
nmod:by(0,fatigued,heat).
case(0,day,of).
det(0,summer,a).
nmod:poss(0,day,summer).
case(0,summer,'s).
nmod:of(0,heat,day).
advmod(0,fell,fast).
dep(0,fast,asleep).
case(0,den,in).
nmod:poss(0,den,his).
nmod:in(0,fell,den).
fell_fast_in(0,lion,his_den).
fatigued_by(0,lion,heat).
of(0,summer,day).
fell_in(0,lion,his_den).
fatigued_by(0,lion,heat_summer_day).
root(1,ROOT,ran).
det(1,mouse,a).
nsubj(1,ran,mouse).
nsubj(1,woke,mouse).
case(1,mane,over).
nmod:poss(1,mane,his).
nmod:over(1,ran,mane).
cc(1,mane,and).
nmod:over(1,ran,ears).
conj:and(1,mane,ears).
cc(1,ran,and).
conj:and(1,ran,woke).
dobj(1,woke,him).
case(1,slumbers,from).
nmod:poss(1,slumbers,his).
nmod:from(1,woke,slumbers).
woke(1,mouse,him).
ran_over(1,mouse,his_mane).
root(2,ROOT,rose).
nsubj(2,rose,he).
nsubj(2,shook,he).
advmod(2,rose,up).
cc(2,rose,and).
conj:and(2,rose,shook).
dobj(2,shook,himself).
case(2,wrath,in).
amod(2,wrath,great).
nmod:in(2,shook,wrath).
cc(2,shook,and).
conj:and(2,rose,searched).
conj:and(2,shook,searched).
det(2,corner,every).
dobj(2,searched,corner).
case(2,den,of).
nmod:poss(2,den,his).
nmod:of(2,corner,den).
mark(2,find,to).
acl:to(2,den,find).
det(2,mouse,the).
dobj(2,find,mouse).
shook(2,he,himself).
root(3,ROOT,said).
det(3,fox,a).
nsubj(3,said,fox).
acl(3,fox,seeing).
dobj(3,seeing,him).
root(4,ROOT,lion).
det(4,lion,a).
amod(4,lion,fine).
nsubj(4,are,you).
nsubjpass:xsubj(4,frightened,you).
acl:relcl(4,lion,are).
mark(4,frightened,to).
auxpass(4,frightened,be).
xcomp(4,are,frightened).
case(4,mouse,of).
det(4,mouse,a).
nmod:of(4,lion,mouse).
be(4,you,frightened).
are(4,you,frightened).
root(5,ROOT,mouse).
nsubj(5,mouse,').
dep(5,mouse,t).
cop(5,mouse,is).
neg(5,mouse,not).
det(5,mouse,the).
dep(5,mouse,i).
dep(5,i,fear).
root(6,ROOT,said).
det(6,lion,the).
nsubj(6,said,lion).
root(7,ROOT,resent).
nsubj(7,resent,i).
nsubj(7,ill-breeding,i).
nmod:poss(7,familiarity,his).
dobj(7,resent,familiarity).
cc(7,resent,and).
conj:and(7,resent,ill-breeding).
resent(7,i,his_familiarity).
