root(0,ROOT,entered).
det(0,fox,a).
nsubj(0,entered,fox).
case(0,partnership,into).
nmod:into(0,entered,partnership).
case(0,lion,with).
det(0,lion,a).
nmod:with(0,entered,lion).
case(0,pretense,on).
det(0,pretense,the).
nmod:on(0,entered,pretense).
mark(0,becoming,of).
acl:of(0,pretense,becoming).
nmod:poss(0,servant,his).
xcomp(0,becoming,servant).
entered_into(0,fox,partnership).
entered_on(0,fox,pretense_becoming).
entered_with(0,fox,lion).
root(1,ROOT,undertook).
nsubj(1,undertook,each).
nmod:poss(1,duty,his).
amod(1,duty,proper).
dobj(1,undertook,duty).
case(1,accordance,in).
nmod:in(1,undertook,accordance).
case(1,nature,with).
nmod:poss(1,nature,his).
amod(1,nature,own).
nmod:with(1,undertook,nature).
cc(1,nature,and).
nmod:with(1,undertook,powers).
conj:and(1,nature,powers).
undertook(1,each,his_duty).
undertook(1,each,his_proper_duty).
root(2,ROOT,discovered).
det(2,fox,the).
nsubj(2,discovered,fox).
nsubj(2,pointed,fox).
cc(2,discovered,and).
conj:and(2,discovered,pointed).
compound:prt(2,pointed,out).
det(2,prey,the).
dobj(2,pointed,prey).
pointed_out(2,fox,prey).
root(3,ROOT,sprang).
det(3,lion,the).
nsubj(3,sprang,lion).
nsubj(3,seized,lion).
case(3,it,on).
nmod:on(3,sprang,it).
cc(3,sprang,and).
conj:and(3,sprang,seized).
dobj(3,seized,it).
sprang_on(3,lion,it).
seized(3,lion,it).
root(4,ROOT,became).
det(4,fox,the).
nsubj(4,became,fox).
nsubj(4,said,fox).
advmod(4,became,soon).
xcomp(4,became,jealous).
case(4,lion,of).
det(4,lion,the).
nmod:of(4,jealous,lion).
acl(4,lion,carrying).
compound:prt(4,carrying,off).
det(4,lion,the).
nmod:poss(4,share,lion).
case(4,lion,'s).
dobj(4,carrying,share).
cc(4,became,and).
conj:and(4,became,said).
mark(4,find,that).
nsubj(4,find,he).
nsubj(4,capture,he).
aux(4,find,would).
neg(4,longer,no).
advmod(4,find,longer).
ccomp(4,said,find).
compound:prt(4,find,out).
det(4,prey,the).
dobj(4,find,prey).
cc(4,find,but).
aux(4,capture,would).
ccomp(4,said,capture).
conj:but(4,find,capture).
dobj(4,capture,it).
case(4,account,on).
nmod:poss(4,account,his).
amod(4,account,own).
nmod:on(4,capture,account).
became(4,fox,jealous_of_lion).
soon_became(4,fox,jealous_of_lion).
became(4,fox,jealous).
has(4,lion,share).
soon_became(4,fox,jealous).
root(5,ROOT,day).
det(5,day,the).
amod(5,day,next).
nsubj(5,attempted,he).
nsubj:xsubj(5,snatch,he).
acl:relcl(5,day,attempted).
mark(5,snatch,to).
xcomp(5,attempted,snatch).
det(5,lamb,a).
dobj(5,snatch,lamb).
case(5,fold,from).
det(5,fold,the).
nmod:from(5,snatch,fold).
case(5,he,but).
nmod:but(5,day,he).
nsubj(5,fell,himself).
acl:relcl(5,he,fell).
dobj(5,fell,prey).
case(5,huntsmen,to).
det(5,huntsmen,the).
nmod:to(5,fell,huntsmen).
cc(5,huntsmen,and).
nmod:to(5,fell,hounds).
conj:and(5,huntsmen,hounds).
fell_prey_to(5,himself,huntsmen).
snatch_lamb_from(5,he,fold).
snatch(5,he,lamb).
fell_to(5,himself,huntsmen).
fell(5,himself,prey).
