root(0,ROOT,had).
compound(0,kites,tee).
nsubj(0,had,kites).
case(0,times,of).
nummod(0,times,olden).
nmod:of(0,kites,times).
cc(0,times,as).
mwe(0,as,well).
mwe(0,as,as).
det(0,swans,the).
nmod:of(0,kites,swans).
conj:and(0,times,swans).
det(0,privilege,the).
dobj(0,had,privilege).
case(0,song,of).
nmod:of(0,privilege,song).
root(1,ROOT,heard).
cc(1,heard,but).
aux(1,heard,having).
det(1,neigh,the).
dobj(1,heard,neigh).
case(1,horse,of).
det(1,horse,the).
nmod:of(1,neigh,horse).
mark(1,tried,horse).
nsubj(1,enchanted,they).
cop(1,enchanted,were).
advmod(1,enchanted,so).
acl:relcl(1,horse,enchanted).
case(1,sound,with).
det(1,sound,the).
nmod:with(1,enchanted,sound).
ref(1,horse,that).
nsubj(1,tried,they).
nsubj:xsubj(1,imitate,they).
ccomp(1,enchanted,tried).
mark(1,imitate,to).
xcomp(1,tried,imitate).
dobj(1,imitate,it).
were(1,they,enchanted).
imitate(1,they,it).
were_enchanted_with(1,they,sound).
were(1,they,so_enchanted).
were_so_enchanted_with(1,they,sound).
root(2,ROOT,and).
mark(2,trying,in).
dep(2,and,trying).
mark(2,neigh,to).
xcomp(2,trying,neigh).
nsubj(2,forgot,they).
ccomp(2,neigh,forgot).
advmod(2,sing,how).
mark(2,sing,to).
ccomp(2,forgot,sing).
root(3,ROOT,involves).
det(3,desire,the).
nsubj(3,involves,desire).
case(3,benefits,for).
amod(3,benefits,imaginary).
nmod:for(3,desire,benefits).
advmod(3,involves,often).
det(3,loss,the).
dobj(3,involves,loss).
case(3,blessings,of).
amod(3,blessings,present).
nmod:of(3,loss,blessings).
often_involves(3,desire,loss_of_blessings).
often_involves(3,desire,loss).
involves(3,desire,loss_of_present_blessings).
involves(3,desire,loss_of_blessings).
involves(3,desire,loss).
often_involves(3,desire,loss_of_present_blessings).
