root(0,ROOT,discussing).
det(0,man,a).
nsubj(0,discussing,man).
cc(0,man,and).
det(0,lion,a).
conj:and(0,man,lion).
nsubj(0,discussing,lion).
aux(0,discussing,were).
det(0,strength,the).
amod(0,strength,relative).
dobj(0,discussing,strength).
case(0,men,of).
nmod:of(0,strength,men).
cc(0,men,and).
nmod:of(0,strength,lions).
conj:and(0,men,lions).
case(0,general,in).
advcl:in(0,discussing,general).
were_discussing(0,lion,strength).
were_discussing(0,lion,relative_strength).
were_discussing(0,man,relative_strength).
were_discussing(0,lion,strength_of_men).
were_discussing_strength_in(0,man,general).
were_discussing(0,man,strength_of_men).
were_discussing(0,man,strength).
were_discussing(0,man,relative_strength_of_men).
were_discussing(0,lion,relative_strength_of_men).
were_discussing_strength_in(0,lion,general).
root(1,ROOT,contended).
det(1,man,the).
nsubj(1,contended,man).
mark(1,stronger,that).
nsubj(1,stronger,he).
cc(1,he,and).
nmod:poss(1,fellows,his).
conj:and(1,he,fellows).
nsubj(1,stronger,fellows).
cop(1,stronger,were).
ccomp(1,contended,stronger).
case(1,lions,than).
nmod:than(1,stronger,lions).
case(1,reason,by).
nmod:by(1,stronger,reason).
case(1,intelligence,of).
nmod:poss(1,intelligence,their).
amod(1,intelligence,greater).
nmod:of(1,reason,intelligence).
were_stronger_by(1,his_fellows,reason).
were(1,his_fellows,stronger_than_lions_by_reason_of_their_greater_intelligence).
were(1,he,stronger_by_reason).
were(1,he,stronger_than_lions_by_reason_of_their_greater_intelligence).
were(1,he,stronger_than_lions_by_reason).
were(1,he,stronger_by_reason_of_their_greater_intelligence).
were(1,his_fellows,stronger_than_lions_by_reason).
were(1,he,stronger_than_lions_by_reason_of_their_intelligence).
were_stronger_by(1,he,reason_of_their_greater_intelligence).
were(1,his_fellows,stronger_than_lions_by_reason_of_their_intelligence).
were_stronger_than(1,his_fellows,lions).
were(1,he,stronger).
were(1,he,stronger_by_reason_of_their_intelligence).
were_stronger_by(1,he,reason).
were(1,he,stronger_than_lions).
were(1,his_fellows,stronger).
were_stronger_by(1,his_fellows,reason_of_their_greater_intelligence).
were_stronger_than(1,he,lions).
were_stronger_by(1,his_fellows,reason_of_their_intelligence).
were_stronger_by(1,he,reason_of_their_intelligence).
root(2,ROOT,come).
advmod(2,come,now).
case(2,me,with).
nmod:with(2,come,me).
root(3,ROOT,cried).
nsubj(3,cried,he).
root(4,ROOT,i).
cc(4,i,and).
mark(4,i,i).
aux(4,prove,will).
advmod(4,prove,soon).
acl:relcl(4,i,prove).
ref(4,i,that).
dep(4,prove,i).
advmod(4,right,am).
dep(4,i,right).
root(5,ROOT,so).
nsubj(5,took,he).
nsubj(5,showed,he).
ccomp(5,so,took).
dobj(5,took,him).
case(5,gardens,into).
det(5,gardens,the).
amod(5,gardens,public).
nmod:into(5,took,gardens).
cc(5,took,and).
ccomp(5,so,showed).
conj:and(5,took,showed).
nsubj(5,statue,him).
det(5,statue,a).
xcomp(5,showed,statue).
case(5,hercules,of).
nmod:of(5,statue,hercules).
dep(5,hercules,overcoming).
det(5,lion,the).
dobj(5,overcoming,lion).
cc(5,overcoming,and).
dep(5,hercules,tearing).
conj:and(5,overcoming,tearing).
nmod:poss(5,mouth,his).
dobj(5,tearing,mouth).
case(5,two,in).
nmod:in(5,tearing,two).
took(5,he,him).
showed(5,he,him_statue).
showed(5,he,him_statue_of_hercules).
statue_of(5,him,hercules).
tearing(5,lion,his_mouth).
root(6,ROOT,is).
nsubj(6,is,that).
dep(6,very,all).
advmod(6,is,very).
advmod(6,is,well).
root(7,ROOT,said).
det(7,lion,the).
nsubj(7,said,lion).
root(8,ROOT,proves).
cc(8,proves,but).
dobj(8,proves,nothing).
mark(8,man,for).
nsubj(8,man,it).
cop(8,man,was).
det(8,man,a).
advcl:for(8,proves,man).
nsubj(8,made,man).
ref(8,man,who).
acl:relcl(8,man,made).
det(8,statue,the).
dobj(8,made,statue).
