root(0,ROOT,once).
advmod(0,asleep,when).
det(0,lion,a).
nsubj(0,asleep,lion).
cop(0,asleep,was).
dep(0,once,asleep).
det(0,mouse,a).
amod(0,mouse,little).
nmod:tmod(0,asleep,mouse).
acl:relcl(0,mouse,began).
xcomp(0,began,running).
advmod(0,running,up).
cc(0,up,and).
advmod(0,running,down).
conj:and(0,up,down).
case(0,him,upon).
nmod:upon(0,running,him).
root(1,ROOT,wakened).
nsubj(1,wakened,this).
nsubj(1,opened,this).
advmod(1,wakened,soon).
det(1,lion,the).
dobj(1,wakened,lion).
nsubj(1,placed,lion).
ref(1,lion,who).
acl:relcl(1,lion,placed).
nmod:poss(1,paw,his).
amod(1,paw,huge).
dobj(1,placed,paw).
case(1,him,upon).
nmod:upon(1,placed,him).
cc(1,wakened,and).
conj:and(1,wakened,opened).
nmod:poss(1,jaws,his).
amod(1,jaws,big).
dobj(1,opened,jaws).
mark(1,swallow,to).
advcl:to(1,opened,swallow).
dobj(1,swallow,him).
root(2,ROOT,pardon).
compound(2,king,o).
dep(2,pardon,king).
root(3,ROOT,cried).
det(3,mouse,the).
amod(3,mouse,little).
nsubj(3,cried,mouse).
root(4,ROOT,forgive).
dobj(4,forgive,me).
det(4,time,this).
nsubj(4,forgive,time).
nsubj(4,knows,time).
nsubj(4,forget,i).
aux(4,forget,shall).
neg(4,forget,never).
acl:relcl(4,time,forget).
dobj(4,forget,it).
ref(4,time,who).
dep(4,forget,knows).
cc(4,knows,but).
dobj(4,do,what).
nsubj(4,able,i).
nsubj:xsubj(4,do,i).
aux(4,able,may).
cop(4,able,be).
dep(4,forget,able).
conj:but(4,knows,able).
mark(4,do,to).
xcomp(4,able,do).
iobj(4,do,you).
det(4,turn,a).
dobj(4,do,turn).
det:qmod(4,days,some).
mwe(4,some,of).
det(4,days,these).
nmod:tmod(4,do,days).
do(4,i,turn).
do(4,i,you).
be(4,i,may_able).
root(5,ROOT,tickled).
det(5,lion,the).
nsubj(5,tickled,lion).
cop(5,tickled,was).
advmod(5,tickled,so).
mark(5,able,at).
det(5,idea,the).
nsubj(5,able,idea).
nsubj:xsubj(5,help,idea).
nsubj:xsubj(5,let,idea).
case(5,mouse,of).
det(5,mouse,the).
nmod:of(5,idea,mouse).
cop(5,able,being).
advcl:at(5,tickled,able).
mark(5,help,to).
xcomp(5,able,help).
dobj(5,help,him).
mark(5,lifted,that).
nsubj(5,lifted,he).
ccomp(5,help,lifted).
compound:prt(5,lifted,up).
nmod:poss(5,paw,his).
dobj(5,lifted,paw).
cc(5,help,and).
xcomp(5,able,let).
conj:and(5,help,let).
nsubj(5,go,him).
ccomp(5,let,go).
was(5,lion,so_tickled).
being(5,idea,able).
was_so_tickled(5,lion,able).
lifted_up(5,he,his_paw).
help(5,idea,him).
was_tickled(5,lion,able).
was(5,lion,tickled).
root(6,ROOT,tied).
det(6,time,some).
nsubj(6,tied,time).
mark(6,caught,after).
det(6,lion,the).
nsubjpass(6,caught,lion).
auxpass(6,caught,was).
acl:after(6,time,caught).
case(6,trap,in).
det(6,trap,a).
nmod:in(6,caught,trap).
cc(6,trap,and).
det(6,hunters,the).
nmod:in(6,caught,hunters).
conj:and(6,trap,hunters).
nsubj(6,desired,hunters).
nsubj:xsubj(6,carry,hunters).
ref(6,hunters,who).
acl:relcl(6,hunters,desired).
mark(6,carry,to).
xcomp(6,desired,carry).
nsubj(6,alive,him).
xcomp(6,carry,alive).
case(6,king,to).
det(6,king,the).
nmod:to(6,alive,king).
dobj(6,tied,him).
case(6,tree,to).
det(6,tree,a).
nmod:to(6,tied,tree).
mark(6,went,while).
nsubj(6,went,they).
nsubj:xsubj(6,carry,they).
advcl:while(6,tied,went).
case(6,search,in).
nmod:in(6,went,search).
case(6,waggon,of).
det(6,waggon,a).
nmod:of(6,search,waggon).
mark(6,carry,to).
xcomp(6,went,carry).
dobj(6,carry,him).
nmod(6,carry,on).
was(6,lion,caught).
went_in(6,they,search_of_waggon).
went_in(6,they,search).
carry(6,they,him).
was_caught_in(6,lion,trap).
root(7,ROOT,happened).
advmod(7,mouse,just).
advmod(7,mouse,then).
det(7,mouse,the).
amod(7,mouse,little).
nsubj(7,happened,mouse).
nsubj:xsubj(7,pass,mouse).
nsubj:xsubj(7,seeing,mouse).
nsubj(7,gnawed,mouse).
mark(7,pass,to).
xcomp(7,happened,pass).
nmod(7,pass,by).
cc(7,pass,and).
xcomp(7,happened,seeing).
conj:and(7,pass,seeing).
det(7,plight,the).
amod(7,plight,sad).
dobj(7,seeing,plight).
nmod:in(7,went,plight).
case(7,which,in).
ref(7,plight,which).
det(7,lion,the).
nsubjpass(7,went,lion).
auxpass(7,went,was).
acl:relcl(7,plight,went).
compound:prt(7,went,up).
case(7,him,to).
nmod:to(7,went,him).
cc(7,happened,and).
advmod(7,gnawed,soon).
conj:and(7,happened,gnawed).
compound:prt(7,gnawed,away).
det(7,ropes,the).
dobj(7,gnawed,ropes).
nsubj(7,bound,ropes).
ref(7,ropes,that).
acl:relcl(7,ropes,bound).
det(7,king,the).
dobj(7,bound,king).
case(7,beasts,of).
det(7,beasts,the).
nmod:of(7,king,beasts).
happened(7,mouse,pass).
happened(7,little_mouse,pass_by).
was_went_up_to(7,lion,him).
happened(7,mouse,pass_by).
happened(7,little_mouse,pass).
root(8,ROOT,was).
nsubj(8,was,i).
dep(8,right,not).
advmod(8,i,right).
root(9,ROOT,said).
det(9,mouse,the).
amod(9,mouse,little).
nsubj(9,said,mouse).
