root(0,ROOT,inflicted).
det(0,snake,a).
nsubj(0,inflicted,snake).
aux(0,made,having).
dep(0,snake,made).
nmod:poss(0,close,his).
compound(0,close,hole).
dobj(0,made,close).
case(0,porch,to).
det(0,porch,the).
nmod:to(0,made,porch).
case(0,cottage,of).
det(0,cottage,a).
nmod:of(0,porch,cottage).
det(0,bite,a).
amod(0,bite,mortal).
dobj(0,inflicted,bite).
case(0,son,on).
det(0,cottager,the).
nmod:poss(0,son,cottager).
case(0,cottager,'s).
amod(0,son,infant).
nmod:on(0,inflicted,son).
inflicted(0,snake,mortal_bite).
inflicted(0,snake,bite).
on(0,cottager,infant_son).
inflicted_bite_on(0,snake,cottager_s_infant_son).
inflicted_bite_on(0,snake,cottager_s_son).
root(1,ROOT,grieving).
case(1,loss,over).
nmod:poss(1,loss,his).
nmod:over(1,grieving,loss).
det(1,father,the).
dobj(1,grieving,father).
acl(1,father,resolved).
mark(1,kill,to).
xcomp(1,resolved,kill).
det(1,snake,the).
dobj(1,kill,snake).
root(2,ROOT,missed).
det(2,day,the).
amod(2,day,next).
nsubj(2,missed,day).
nsubj(2,cut,day).
advmod(2,came,when).
nsubj(2,came,it).
acl:relcl(2,day,came).
case(2,hole,out).
mwe(2,out,of).
nmod:poss(2,hole,its).
nmod:out_of(2,came,hole).
case(2,food,for).
nmod:for(2,hole,food).
nsubj(2,took,he).
ccomp(2,came,took).
compound:prt(2,took,up).
nmod:poss(2,axe,his).
dobj(2,took,axe).
cc(2,swinging,but).
mark(2,swinging,by).
dep(2,took,swinging).
advmod(2,hastily,too).
dobj(2,swinging,hastily).
nmod:poss(2,head,its).
dobj(2,missed,head).
cc(2,missed,and).
conj:and(2,missed,cut).
compound:prt(2,cut,off).
advmod(2,end,only).
det(2,end,the).
dobj(2,cut,end).
case(2,tail,of).
nmod:poss(2,tail,its).
nmod:of(2,end,tail).
took_up(2,he,his_axe).
came_out_of(2,it,its_hole_for_food).
swinging(2,he,too_hastily).
swinging(2,his_axe,too_hastily).
came_out_of(2,it,its_hole).
swinging(2,he,hastily).
swinging(2,his_axe,hastily).
root(3,ROOT,endeavored).
mark(3,endeavored,after).
det(3,time,some).
nsubj(3,endeavored,time).
nsubj:xsubj(3,make,time).
nsubj(3,placed,time).
det(3,cottager,the).
nmod:npmod(3,afraid,cottager).
amod(3,time,afraid).
mark(3,bite,that).
det(3,snake,the).
nsubj(3,bite,snake).
aux(3,bite,would).
ccomp(3,afraid,bite).
dobj(3,bite,him).
advmod(3,bite,also).
mark(3,make,to).
xcomp(3,endeavored,make).
dobj(3,make,peace).
cc(3,endeavored,and).
conj:and(3,endeavored,placed).
det(3,bread,some).
dobj(3,placed,bread).
cc(3,bread,and).
dobj(3,placed,salt).
conj:and(3,bread,salt).
case(3,hole,in).
det(3,hole,the).
nmod:in(3,bread,hole).
placed(3,time,salt).
afraid(3,time,cottager).
make(3,time,peace).
placed(3,time,bread).
placed(3,time_afraid,bread).
placed(3,time_afraid,salt).
placed(3,time_afraid,bread_in_hole).
is_in(3,bread,hole).
make(3,time_afraid,peace).
placed(3,time,bread_in_hole).
bite(3,snake,him).
bite_also(3,snake,him).
bread_in(3,salt,hole).
root(4,ROOT,said).
det(4,snake,the).
nsubj(4,said,snake).
advmod(4,hissing,slightly).
acl(4,snake,hissing).
root(5,ROOT,peace).
nsubj(5,peace,there).
aux(5,peace,can).
advmod(5,peace,henceforth).
cop(5,peace,be).
neg(5,peace,no).
case(5,us,between).
nmod:between(5,peace,us).
root(6,ROOT,thinking).
mark(6,thinking,for).
advmod(6,see,whenever).
nsubj(6,see,i).
advcl(6,thinking,see).
dobj(6,see,you).
nsubj(6,remember,i).
aux(6,remember,shall).
dep(6,see,remember).
det(6,loss,the).
dobj(6,remember,loss).
case(6,tail,of).
nmod:poss(6,tail,my).
nmod:of(6,loss,tail).
cc(6,remember,and).
advmod(6,see,whenever).
nsubj(6,see,you).
dep(6,see,see).
conj:and(6,remember,see).
dobj(6,see,me).
nsubj(6,thinking,you).
aux(6,thinking,will).
aux(6,thinking,be).
case(6,death,of).
det(6,death,the).
nmod:of(6,thinking,death).
case(6,son,of).
nmod:poss(6,son,your).
nmod:of(6,death,son).
loss_of(6,i,my_tail).
see(6,you,me).
see(6,i,you).
root(7,ROOT,forgets).
neg(7,one,no).
nsubj(7,forgets,one).
advmod(7,forgets,truly).
dobj(7,forgets,injuries).
nsubj(7,caused,injuries).
case(7,presence,in).
det(7,presence,the).
nmod:in(7,injuries,presence).
case(7,him,of).
nmod:of(7,presence,him).
ref(7,injuries,who).
acl:relcl(7,injuries,caused).
det(7,injury,the).
dobj(7,caused,injury).
