root(0,ROOT,lion).
det(0,lion,the).
det(0,fox,the).
nsubj(0,entered,fox).
nsubj:xsubj(0,assist,fox).
cc(0,fox,and).
det(0,ass,the).
conj:and(0,fox,ass).
nsubj(0,entered,ass).
nsubj:xsubj(0,assist,ass).
ccomp(0,lion,entered).
case(0,agreement,into).
det(0,agreement,an).
nmod:into(0,entered,agreement).
mark(0,assist,to).
xcomp(0,entered,assist).
det(0,other,each).
dobj(0,assist,other).
case(0,chase,in).
det(0,chase,the).
nmod:in(0,assist,chase).
entered_into(0,fox,agreement).
entered_into(0,ass,agreement).
root(1,ROOT,secured).
aux(1,secured,having).
det(1,booty,a).
amod(1,booty,large).
dobj(1,secured,booty).
det(1,lion,the).
nsubj(1,asked,lion).
case(1,return,on).
nmod:poss(1,return,their).
nmod:on(1,lion,return).
case(1,forest,from).
det(1,forest,the).
nmod:from(1,return,forest).
acl:relcl(1,booty,asked).
det(1,ass,the).
dobj(1,asked,ass).
mark(1,allot,to).
acl:to(1,ass,allot).
nmod:poss(1,portion,his).
amod(1,portion,due).
dobj(1,allot,portion).
case(1,each,to).
nmod:to(1,allot,each).
case(1,partners,of).
det(1,partners,the).
nummod(1,partners,three).
nmod:of(1,each,partners).
case(1,treaty,in).
det(1,treaty,the).
nmod:in(1,partners,treaty).
root(2,ROOT,divided).
det(2,ass,the).
nsubj(2,divided,ass).
nsubj(2,requested,ass).
advmod(2,divided,carefully).
det(2,spoil,the).
dobj(2,divided,spoil).
case(2,shares,into).
nummod(2,shares,three).
amod(2,shares,equal).
nmod:into(2,divided,shares).
cc(2,divided,and).
advmod(2,requested,modestly).
conj:and(2,divided,requested).
det(2,others,the).
nummod(2,others,two).
dobj(2,requested,others).
nsubj:xsubj(2,make,others).
mark(2,make,to).
xcomp(2,requested,make).
det(2,choice,the).
amod(2,choice,first).
dobj(2,make,choice).
make(2,two_others,choice).
carefully_divided_into(2,ass,three_shares).
divided_spoil_into(2,ass,three_shares).
divided_into(2,ass,three_equal_shares).
make(2,two_others,first_choice).
divided_into(2,ass,three_shares).
carefully_divided(2,ass,spoil).
modestly_requested(2,ass,two_others).
divided_spoil_into(2,ass,three_equal_shares).
divided(2,ass,spoil).
requested(2,ass,two_others).
carefully_divided_spoil_into(2,ass,three_equal_shares).
carefully_divided_spoil_into(2,ass,three_shares).
carefully_divided_into(2,ass,three_equal_shares).
root(3,ROOT,devoured).
det(3,lion,the).
nsubj(3,devoured,lion).
acl(3,lion,bursting).
compound:prt(3,bursting,out).
case(3,rage,into).
det(3,rage,a).
amod(3,rage,great).
nmod:into(3,bursting,rage).
det(3,ass,the).
dobj(3,devoured,ass).
devoured(3,lion,ass).
root(4,ROOT,requested).
advmod(4,he,then).
nsubj(4,requested,he).
det(4,fox,the).
dobj(4,requested,fox).
mark(4,do,to).
acl:to(4,fox,do).
iobj(4,do,him).
det(4,favor,the).
dobj(4,do,favor).
mark(4,make,to).
acl:to(4,favor,make).
det(4,division,a).
dobj(4,make,division).
root(5,ROOT,accumulated).
det(5,fox,the).
nsubj(5,accumulated,fox).
advmod(5,accumulated,all).
mark(5,killed,that).
nsubj(5,killed,they).
nsubj(5,left,they).
aux(5,killed,had).
ccomp(5,accumulated,killed).
case(5,heap,into).
nummod(5,heap,one).
amod(5,heap,large).
nmod:into(5,killed,heap).
cc(5,killed,and).
ccomp(5,accumulated,left).
conj:and(5,killed,left).
case(5,himself,to).
nmod:to(5,left,himself).
det(5,morsel,the).
amod(5,morsel,smallest).
amod(5,morsel,possible).
dobj(5,killed,morsel).
killed(5,they,smallest_possible_morsel).
left_to(5,they,himself).
killed(5,they,possible_morsel).
root(6,ROOT,said).
det(6,lion,the).
nsubj(6,said,lion).
root(7,ROOT,taught).
nsubj(7,taught,who).
aux(7,taught,has).
nsubj(7,fellow,you).
nmod:poss(7,fellow,my).
advmod(7,excellent,very).
amod(7,fellow,excellent).
xcomp(7,taught,fellow).
det(7,art,the).
dep(7,fellow,art).
case(7,division,of).
nmod:of(7,fellow,division).
root(8,ROOT,perfect).
nsubj(8,perfect,you).
cop(8,perfect,are).
case(8,fraction,to).
det(8,fraction,a).
nmod:to(8,perfect,fraction).
are(8,you,perfect).
are_perfect_to(8,you,fraction).
root(9,ROOT,replied).
nsubj(9,replied,he).
root(10,ROOT,learned).
nsubj(10,learned,i).
dobj(10,learned,it).
case(10,ass,from).
det(10,ass,the).
nmod:from(10,learned,ass).
mark(10,witnessing,by).
advcl:by(10,learned,witnessing).
nmod:poss(10,fate,his).
dobj(10,witnessing,fate).
learned(10,i,it).
witnessing(10,i,his_fate).
