root(0,ROOT,had).
det(0,beasts,the).
nsubj(0,had,beasts).
case(0,field,of).
det(0,field,the).
nmod:of(0,beasts,field).
cc(0,field,and).
nmod:of(0,beasts,forest).
conj:and(0,field,forest).
det(0,lion,a).
dobj(0,had,lion).
case(0,king,as).
nmod:poss(0,king,their).
nmod:as(0,lion,king).
had(0,beasts,lion_as_their_king).
had(0,beasts,lion).
root(1,ROOT,cruel).
nsubj(1,cruel,he).
nsubj(1,tyrannical,he).
cop(1,cruel,was).
cc:preconj(1,cruel,neither).
amod(1,cruel,wrathful).
cc(1,cruel,nor).
conj:nor(1,cruel,tyrannical).
cc(1,just,but).
dep(1,tyrannical,just).
cc(1,tyrannical,and).
conj:nor(1,cruel,gentle).
conj:and(1,tyrannical,gentle).
mark(1,be,as).
det(1,king,a).
nsubj(1,be,king).
aux(1,be,could).
dep(1,gentle,be).
was(1,he,wrathful_cruel).
was(1,he,cruel).
root(2,ROOT,reign).
dep(2,reign,during).
nmod:poss(2,reign,his).
nsubj(2,made,he).
nsubj(2,drew,he).
acl:relcl(2,reign,made).
det(2,proclamation,a).
amod(2,proclamation,royal).
dobj(2,made,proclamation).
case(2,assembly,for).
det(2,assembly,a).
amod(2,assembly,general).
nmod:for(2,made,assembly).
case(2,birds,of).
det:predet(2,birds,all).
det(2,birds,the).
nmod:of(2,assembly,birds).
cc(2,birds,and).
nmod:of(2,assembly,beasts).
conj:and(2,birds,beasts).
cc(2,made,and).
acl:relcl(2,reign,drew).
conj:and(2,made,drew).
compound:prt(2,drew,up).
dobj(2,drew,conditions).
case(2,league,for).
det(2,league,a).
amod(2,league,universal).
nmod:for(2,reign,league).
nmod:in(2,live,league).
case(2,which,in).
ref(2,league,which).
det(2,wolf,the).
nsubj(2,live,wolf).
cc(2,wolf,and).
det(2,lamb,the).
conj:and(2,wolf,lamb).
nsubj(2,live,lamb).
det(2,panther,the).
dep(2,lamb,panther).
cc(2,lamb,and).
det(2,kid,the).
conj:and(2,wolf,kid).
conj:and(2,lamb,kid).
det(2,tiger,the).
dep(2,kid,tiger).
cc(2,kid,and).
det(2,stag,the).
conj:and(2,lamb,stag).
conj:and(2,kid,stag).
det(2,dog,the).
dep(2,stag,dog).
cc(2,dog,and).
det(2,hare,the).
dep(2,stag,hare).
conj:and(2,dog,hare).
aux(2,live,should).
acl:relcl(2,league,live).
advmod(2,live,together).
case(2,peace,in).
amod(2,peace,perfect).
nmod:in(2,live,peace).
cc(2,peace,and).
nmod:in(2,live,amity).
conj:and(2,peace,amity).
live(2,lamb,kid).
should_live_together_in(2,lamb,peace).
made(2,he,proclamation).
drew_up(2,he,conditions).
should_live_in(2,wolf,peace).
should_live_together_in(2,wolf,peace).
should_live_in(2,lamb,peace).
made(2,he,royal_proclamation).
live_together(2,lamb,kid).
root(3,ROOT,said).
det(3,hare,the).
nsubj(3,said,hare).
root(4,ROOT,oh).
advmod(4,longed,how).
nsubj(4,longed,i).
nsubj:xsubj(4,see,i).
aux(4,longed,have).
ccomp(4,oh,longed).
mark(4,see,to).
xcomp(4,longed,see).
det(4,day,this).
dobj(4,see,day).
nmod:in(4,take,day).
case(4,which,in).
ref(4,day,which).
det(4,weak,the).
nsubj(4,take,weak).
aux(4,take,shall).
acl:relcl(4,day,take).
nmod:poss(4,place,their).
dobj(4,take,place).
case(4,impunity,with).
nmod:with(4,take,impunity).
case(4,side,by).
det(4,side,the).
nmod:by(4,take,side).
case(4,strong,of).
det(4,strong,the).
nmod:of(4,side,strong).
shall_take(4,weak,their_place).
root(5,ROOT,said).
cc(5,said,and).
mark(5,said,after).
det(5,hare,the).
nsubj(5,said,hare).
dobj(5,said,this).
nsubj(5,ran,he).
acl:relcl(5,this,ran).
case(5,life,for).
nmod:poss(5,life,his).
nmod:for(5,ran,life).
ran_for(5,he,his_life).
