root(0,ROOT,created).
det(0,lark,the).
nsubjpass(0,created,lark).
punct(0,legend,-LRB-).
case(0,legend,according).
mwe(0,according,to).
det(0,legend,an).
amod(0,legend,ancient).
nmod:according_to(0,lark,legend).
punct(0,legend,-RRB-).
auxpass(0,created,was).
mark(0,itself,before).
det(0,earth,the).
dep(0,itself,earth).
advcl:before(0,created,itself).
cc(0,itself,and).
advmod(0,died,when).
nmod:poss(0,father,her).
nsubj(0,died,father).
advcl(0,find,died).
mark(0,was,as).
expl(0,was,there).
advcl:as(0,died,was).
neg(0,earth,no).
nsubj(0,was,earth).
nsubj(0,find,she).
aux(0,find,could).
advcl:before(0,created,find).
conj:and(0,itself,find).
neg(0,place,no).
dobj(0,find,place).
case(0,burial,of).
nmod:of(0,place,burial).
case(0,him,for).
nmod:for(0,find,him).
was(0,lark,created).
was_created(0,lark,itself).
root(1,ROOT,let).
nsubj(1,let,she).
nsubj(1,lie,him).
ccomp(1,let,lie).
xcomp(1,lie,uninterred).
xcomp(1,lie,uninterred).
conj:and(1,uninterred,uninterred).
case(1,days,for).
nummod(1,days,five).
nmod:for(1,uninterred,days).
cc(1,uninterred,and).
case(1,day,on).
det(1,day,the).
amod(1,day,sixth).
nmod:on(1,uninterred,day).
neg(1,knowing,not).
acl(1,day,knowing).
dobj(1,knowing,what).
advmod(1,what,else).
mark(1,do,to).
dep(1,what,do).
dobj(1,do,she).
acl(1,what,buried).
dobj(1,buried,him).
case(1,head,in).
nmod:poss(1,head,her).
amod(1,head,own).
nmod:in(1,buried,head).
lie(1,him,uninterred).
lie(1,him,uninterred_for_five_days).
root(2,ROOT,obtained).
advmod(2,she,hence).
nsubj(2,obtained,she).
nmod:poss(2,crest,her).
dobj(2,obtained,crest).
nsubjpass(2,said,crest).
nsubj:xsubj(2,grave-hillock,crest).
ref(2,crest,which).
auxpass(2,said,is).
advmod(2,said,popularly).
acl:relcl(2,crest,said).
mark(2,grave-hillock,to).
cop(2,grave-hillock,be).
nmod:poss(2,father,her).
nmod:poss(2,grave-hillock,father).
case(2,father,'s).
xcomp(2,said,grave-hillock).
has(2,father,grave-hillock).
