root(0,ROOT,bulls).
nummod(0,bulls,three).
case(0,time,for).
det(0,time,a).
amod(0,time,long).
nmod:for(0,bulls,time).
acl(0,time,pastured).
advmod(0,pastured,together).
root(1,ROOT,lay).
det(1,lion,a).
nsubj(1,lay,lion).
nsubj(1,afraid,lion).
nsubj:xsubj(1,attack,lion).
case(1,ambush,in).
nmod:in(1,lay,ambush).
case(1,hope,in).
det(1,hope,the).
nmod:in(1,lay,hope).
mark(1,making,of).
acl:of(1,hope,making).
nsubj(1,prey,them).
nmod:poss(1,prey,his).
xcomp(1,making,prey).
cc(1,lay,but).
cop(1,afraid,was).
conj:but(1,lay,afraid).
mark(1,attack,to).
xcomp(1,afraid,attack).
dobj(1,attack,them).
mark(1,kept,while).
nsubj(1,kept,they).
advcl:while(1,attack,kept).
advmod(1,kept,together).
lay_in(1,lion,ambush).
lay_in(1,lion,hope_making).
root(2,ROOT,having).
amod(2,last,at).
dobj(2,having,last).
case(2,speeches,by).
amod(2,speeches,guileful).
nmod:by(2,last,speeches).
dep(2,having,succeeded).
mark(2,separating,in).
advcl:in(2,succeeded,separating).
dobj(2,separating,them).
nsubj(2,attacked,he).
dep(2,separating,attacked).
dobj(2,attacked,them).
case(2,fear,without).
nmod:without(2,attacked,fear).
mark(2,fed,as).
nsubj(2,fed,they).
nsubj(2,feasted,they).
advcl:as(2,attacked,fed).
advmod(2,fed,alone).
cc(2,fed,and).
advcl:as(2,attacked,feasted).
conj:and(2,fed,feasted).
case(2,them,on).
nmod:on(2,feasted,them).
nsubj(2,having,one).
case(2,one,by).
nmod:by(2,one,one).
case(2,leisure,at).
nmod:poss(2,leisure,his).
amod(2,leisure,own).
nmod:at(2,one,leisure).
attacked(2,he,them).
feasted_on(2,they,them).
root(3,ROOT,strength).
nsubj(3,strength,union).
cop(3,strength,is).
is(3,union,strength).
