root(0,ROOT,resorted).
det(0,lion,a).
nsubj(0,resorted,lion).
nsubj:xsubj(0,ensure,lion).
advmod(0,desiring,greatly).
dep(0,lion,desiring).
mark(0,capture,to).
xcomp(0,desiring,capture).
det(0,bull,a).
dobj(0,capture,bull).
cc(0,desiring,and).
advmod(0,afraid,yet).
dep(0,lion,afraid).
conj:and(0,desiring,afraid).
mark(0,attack,to).
xcomp(0,afraid,attack).
dobj(0,attack,him).
case(0,size,on).
mwe(0,on,account).
mwe(0,on,of).
nmod:poss(0,size,his).
amod(0,size,great).
nmod:on_account_of(0,attack,size).
case(0,trick,to).
det(0,trick,a).
nmod:to(0,resorted,trick).
mark(0,ensure,to).
xcomp(0,resorted,ensure).
nmod:poss(0,destruction,his).
dobj(0,ensure,destruction).
resorted_to(0,lion,trick).
resorted(0,lion,ensure).
ensure(0,lion,his_destruction).
root(1,ROOT,approached).
nsubj(1,approached,he).
nsubj(1,said,he).
det(1,bull,the).
dobj(1,approached,bull).
cc(1,approached,and).
conj:and(1,approached,said).
approached(1,he,bull).
root(2,ROOT,slain).
advmod(2,slain,i).
aux(2,slain,have).
det(2,sheep,a).
amod(2,sheep,fine).
dobj(2,slain,sheep).
nmod:poss(2,friend,my).
nsubj(2,slain,friend).
i_have_slain(2,my_friend,fine_sheep).
i_have_slain(2,my_friend,sheep).
have_slain(2,my_friend,sheep).
have_slain(2,my_friend,fine_sheep).
root(3,ROOT,come).
cc(3,come,and).
mark(3,come,if).
nsubj(3,come,you).
nsubj(3,partake,you).
aux(3,come,will).
dobj(3,come,home).
cc(3,come,and).
conj:and(3,come,partake).
case(3,him,of).
nmod:of(3,partake,him).
case(3,me,with).
nmod:with(3,partake,me).
nsubj(3,delighted,i).
nsubj:xsubj(3,have,i).
aux(3,delighted,shall).
cop(3,delighted,be).
acl:relcl(3,me,delighted).
mark(3,have,to).
xcomp(3,delighted,have).
nmod:poss(3,company,your).
dobj(3,have,company).
will_come(3,you,home).
shall(3,i,shall_delighted).
partake_of(3,you,him).
have(3,i,your_company).
root(4,ROOT,said).
det(4,lion,the).
nsubj(4,said,lion).
dobj(4,said,this).
case(4,hope,in).
det(4,hope,the).
nmod:in(4,this,hope).
mark(4,act,that).
mark(4,act,as).
det(4,bull,the).
nsubj(4,act,bull).
cop(4,act,was).
case(4,act,in).
det(4,act,the).
advcl:in(4,said,act).
mark(4,reclining,of).
acl:of(4,act,reclining).
mark(4,eat,to).
xcomp(4,reclining,eat).
nsubj(4,attack,he).
nsubj(4,make,he).
aux(4,attack,might).
ccomp(4,eat,attack).
dobj(4,attack,him).
case(4,advantage,to).
nmod:to(4,attack,advantage).
cc(4,attack,and).
ccomp(4,eat,make).
conj:and(4,attack,make).
nmod:poss(4,meal,his).
dobj(4,make,meal).
case(4,him,on).
nmod:on(4,make,him).
make(4,he,his_meal).
said(4,lion,this_in_hope).
reclining(4,bull,eat).
said_in(4,lion,act_reclining).
attack(4,he,him).
said(4,lion,this).
was_in(4,bull,act_reclining).
root(5,ROOT,saw).
det(5,bull,the).
nsubj(5,saw,bull).
mark(5,approaching,on).
acl:on(5,bull,approaching).
det(5,lion,the).
nmod:poss(5,den,lion).
case(5,lion,'s).
dobj(5,approaching,den).
det(5,spits,the).
amod(5,spits,huge).
dobj(5,saw,spits).
cc(5,spits,and).
amod(5,caldrons,giant).
dobj(5,saw,caldrons).
conj:and(5,spits,caldrons).
cc(5,spits,and).
neg(5,sign,no).
dobj(5,saw,sign).
conj:and(5,spits,sign).
nsubj(5,took,whatever).
case(5,sheep,of).
det(5,sheep,the).
nmod:of(5,took,sheep).
cc(5,sheep,and).
mark(5,saying,without).
conj:and(5,sheep,saying).
nmod:of(5,took,saying).
det(5,word,a).
dobj(5,saying,word).
advmod(5,saying,quietly).
acl:relcl(5,sign,took).
nmod:poss(5,departure,his).
dobj(5,took,departure).
has(5,lion,den).
root(6,ROOT,inquired).
det(6,lion,the).
nsubj(6,inquired,lion).
advmod(6,went,why).
nsubj(6,went,he).
advcl(6,inquired,went).
advmod(6,so,off).
advmod(6,went,so).
advmod(6,word,abruptly).
case(6,word,without).
det(6,word,a).
nmod:without(6,went,word).
case(6,salutation,of).
nmod:of(6,word,salutation).
case(6,host,to).
nmod:poss(6,host,his).
nmod:to(6,went,host).
nsubj(6,given,host).
ref(6,host,who).
aux(6,given,had).
neg(6,given,not).
acl:relcl(6,host,given).
iobj(6,given,him).
det(6,cause,any).
dobj(6,given,cause).
case(6,offense,for).
nmod:for(6,cause,offense).
went_off_so_without(6,he,word_of_salutation).
went_without(6,he,abruptly_word).
went_so_without(6,he,abruptly_word_of_salutation).
went_without(6,he,word).
went_off_so_without(6,he,abruptly_word_of_salutation).
went_so_without(6,he,abruptly_word).
went_off_so_without(6,he,abruptly_word).
went_without(6,he,abruptly_word_of_salutation).
went_so_without(6,he,word).
went_off_so_without(6,he,word).
went_without(6,he,word_of_salutation).
went_so_without(6,he,word_of_salutation).
root(7,ROOT,have).
advmod(7,have,i).
dobj(7,have,reasons).
nsubj(7,have,enough).
i_have(7,enough,reasons).
have(7,enough,reasons).
root(8,ROOT,said).
det(8,bull,the).
nsubj(8,said,bull).
root(9,ROOT,see).
dep(9,see,i).
neg(9,indication,no).
dobj(9,see,indication).
nsubj(9,slaughtered,whatever).
case(9,your,of).
nmod:of(9,slaughtered,your).
aux(9,slaughtered,having).
acl:relcl(9,indication,slaughtered).
det(9,sheep,a).
dobj(9,slaughtered,sheep).
mark(9,do,while).
nsubj(9,do,i).
advcl:while(9,slaughtered,do).
ccomp(9,do,see).
advmod(9,plainly,very).
xcomp(9,see,plainly).
det(9,preparation,every).
nsubj(9,see,preparation).
case(9,dining,for).
nmod:poss(9,dining,your).
nmod:for(9,preparation,dining).
case(9,bull,on).
det(9,bull,a).
nmod:on(9,dining,bull).
