root(0,ROOT,boasted).
det(0,lamp,the).
nsubj(0,boasted,lamp).
det(0,lamp,a).
nsubj(0,soaked,lamp).
nsubj(0,flaring,lamp).
acl:relcl(0,lamp,soaked).
case(0,oil,with).
advmod(0,much,too).
amod(0,oil,much).
nmod:with(0,soaked,oil).
cc(0,soaked,and).
acl:relcl(0,lamp,flaring).
conj:and(0,soaked,flaring).
advmod(0,flaring,brightly).
mark(0,gave,that).
nsubj(0,gave,it).
ccomp(0,boasted,gave).
advmod(0,light,more).
xcomp(0,gave,light).
case(0,sun,than).
det(0,sun,the).
nmod:than(0,gave,sun).
soaked_with(0,lamp,much_oil).
gave(0,it,light).
gave(0,it,more_light).
gave_than(0,it,sun).
soaked_with(0,lamp,oil).
soaked_with(0,lamp,too_much_oil).
root(1,ROOT,puff).
dep(1,puff,then).
det(1,puff,a).
amod(1,puff,sudden).
mark(1,arose,of).
nsubj(1,arose,wind).
acl:of(1,puff,arose).
cc(1,arose,and).
det(1,lamp,the).
nsubjpass(1,extinguished,lamp).
auxpass(1,extinguished,was).
advmod(1,extinguished,immediately).
acl:of(1,puff,extinguished).
conj:and(1,arose,extinguished).
was(1,lamp,immediately_extinguished).
was(1,lamp,extinguished).
root(2,ROOT,lit).
nmod:poss(2,owner,its).
nsubj(2,lit,owner).
nsubj(2,said,owner).
dobj(2,lit,it).
advmod(2,lit,again).
cc(2,lit,and).
conj:and(2,lit,said).
lit_again(2,its_owner,it).
lit(2,its_owner,it).
root(3,ROOT,boast).
neg(3,more,no).
advmod(3,boast,more).
cc(3,boast,but).
advmod(3,content,henceforth).
cop(3,content,be).
conj:but(3,boast,content).
mark(3,give,to).
xcomp(3,content,give).
nmod:poss(3,light,thy).
dobj(3,give,light).
case(3,silence,in).
nmod:in(3,give,silence).
root(4,ROOT,know).
mark(4,need,that).
neg(4,stars,not).
advmod(4,stars,even).
det(4,stars,the).
nsubj(4,need,stars).
nsubjpass:xsubj(4,relit,stars).
ccomp(4,know,need).
mark(4,relit,to).
auxpass(4,relit,be).
xcomp(4,need,relit).
