root(0,ROOT,gave).
det(0,lion,the).
nmod:npmod(0,once,lion).
advmod(0,gave,once).
compound:prt(0,gave,out).
mark(0,death,that).
nsubj(0,death,he).
nsubj(0,summoned,he).
cop(0,death,was).
amod(0,death,sick).
amod(0,death,unto).
dep(0,gave,death).
cc(0,death,and).
dep(0,gave,summoned).
conj:and(0,death,summoned).
det(0,animals,the).
dobj(0,summoned,animals).
mark(0,come,to).
advcl:to(0,summoned,come).
cc(0,come,and).
advcl:to(0,summoned,hear).
conj:and(0,come,hear).
nmod:poss(0,will,his).
amod(0,will,last).
dobj(0,come,will).
cc(0,will,and).
dobj(0,come,testament).
conj:and(0,will,testament).
was(0,he,death).
was(0,he,sick_unto_death).
was(0,he,sick_death).
was(0,he,unto_death).
summoned(0,he,animals).
summoned_animals(0,he,come).
root(1,ROOT,came).
mark(1,came,so).
det(1,goat,the).
nsubj(1,came,goat).
nsubj(1,stopped,goat).
case(1,cave,to).
det(1,lion,the).
nmod:poss(1,cave,lion).
case(1,lion,'s).
nmod:to(1,came,cave).
cc(1,came,and).
conj:and(1,came,stopped).
expl(1,listening,there).
dep(1,stopped,listening).
case(1,time,for).
det(1,time,a).
amod(1,time,long).
nmod:for(1,listening,time).
listening_for(1,stopped,long_time).
came_to(1,goat,lion_s_cave).
to(1,lion,cave).
listening_for(1,stopped,time).
root(2,ROOT,sheep).
dep(2,sheep,then).
det(2,sheep,a).
ccomp(2,sheep,went).
mark(2,came,in).
cc(2,came,and).
advcl:in(2,went,before).
conj:and(2,came,before).
nsubj(2,came,she).
advcl:in(2,went,came).
compound:prt(2,came,out).
det(2,calf,a).
nsubj(2,came,calf).
nsubj:xsubj(2,receive,calf).
ccomp(2,came,came).
compound:prt(2,came,up).
mark(2,receive,to).
xcomp(2,came,receive).
det(2,wishes,the).
amod(2,wishes,last).
dobj(2,receive,wishes).
case(2,lord,of).
det(2,lord,the).
nmod:of(2,wishes,lord).
case(2,beasts,of).
det(2,beasts,the).
nmod:of(2,lord,beasts).
receive(2,calf,wishes_of_lord_of_beasts).
receive(2,calf,last_wishes_of_lord).
receive(2,calf,last_wishes).
receive(2,calf,wishes_of_lord).
receive(2,calf,last_wishes_of_lord_of_beasts).
receive(2,calf,wishes).
root(3,ROOT,seemed).
cc(3,seemed,but).
advmod(3,seemed,soon).
det(3,lion,the).
nsubj(3,seemed,lion).
nsubj:xsubj(3,recover,lion).
nsubj(3,came,lion).
mark(3,recover,to).
xcomp(3,seemed,recover).
cc(3,seemed,and).
conj:and(3,seemed,came).
case(3,mouth,to).
det(3,mouth,the).
nmod:to(3,came,mouth).
case(3,cave,of).
nmod:poss(3,cave,his).
nmod:of(3,mouth,cave).
cc(3,came,and).
conj:and(3,seemed,saw).
conj:and(3,came,saw).
det(3,fox,the).
dobj(3,saw,fox).
nsubj(3,waiting,fox).
ref(3,fox,who).
aux(3,waiting,had).
aux(3,waiting,been).
acl:relcl(3,fox,waiting).
advmod(3,waiting,outside).
case(3,time,for).
det(3,time,some).
nmod:for(3,waiting,time).
came_to(3,lion,mouth_of_his_cave).
soon_seemed(3,lion,recover).
seemed(3,lion,recover).
came_to(3,lion,mouth).
root(4,ROOT,come).
advmod(4,come,why).
aux(4,come,do).
nsubj(4,come,you).
nsubj:xsubj(4,pay,you).
advmod(4,come,not).
mark(4,pay,to).
xcomp(4,come,pay).
nmod:poss(4,respects,your).
dobj(4,pay,respects).
case(4,me,to).
nmod:to(4,pay,me).
pay(4,you,your_respects).
root(5,ROOT,said).
det(5,lion,the).
nsubj(5,said,lion).
case(5,fox,to).
det(5,fox,the).
nmod:to(5,lion,fox).
root(6,ROOT,beg).
dep(6,beg,i).
nmod:poss(6,majesty,your).
nmod:poss(6,pardon,majesty).
case(6,majesty,'s).
dobj(6,beg,pardon).
has(6,majesty,pardon).
root(7,ROOT,said).
det(7,fox,the).
nsubj(7,said,fox).
root(8,ROOT,i).
cc(8,i,but).
acl(8,i,noticed).
det(8,track,the).
dobj(8,noticed,track).
case(8,animals,of).
det(8,animals,the).
nmod:of(8,track,animals).
nsubj(8,come,animals).
ref(8,animals,that).
aux(8,come,have).
advmod(8,come,already).
acl:relcl(8,animals,come).
case(8,you,to).
nmod:to(8,come,you).
noticed(8,i,track).
root(9,ROOT,see).
cc(9,see,and).
mark(9,see,while).
nsubj(9,see,i).
amod(9,hoof-marks,many).
nsubj(9,see,hoof-marks).
acl(9,hoof-marks,going).
case(9,i,in).
nmod:in(9,going,i).
ccomp(9,see,see).
dobj(9,see,none).
acl(9,none,coming).
compound:prt(9,coming,out).
going_in(9,hoof-marks,i).
going_in(9,many_hoof-marks,i).
root(10,ROOT,animals).
case(10,animals,till).
det(10,animals,the).
nsubj(10,entered,animals).
ref(10,animals,that).
aux(10,entered,have).
acl:relcl(10,animals,entered).
nmod:poss(10,cave,your).
dobj(10,entered,cave).
acl(10,cave,come).
compound:prt(10,come,out).
advmod(10,come,again).
nsubj(10,prefer,i).
nsubj:xsubj(10,remain,i).
acl:relcl(10,cave,prefer).
mark(10,remain,to).
xcomp(10,prefer,remain).
case(10,air,in).
det(10,air,the).
amod(10,air,open).
nmod:in(10,remain,air).
prefer(10,i,remain).
remain_in(10,i,air).
remain_in(10,i,open_air).
prefer(10,i,remain_in_air).
prefer(10,i,remain_in_open_air).
