root(0,ROOT,wearied).
det(0,lion,the).
nsubj(0,wearied,lion).
dobj(0,wearied,jupiter).
case(0,complaints,with).
nmod:poss(0,complaints,his).
amod(0,complaints,frequent).
nmod:with(0,wearied,complaints).
wearied(0,lion,jupiter).
wearied_jupiter_with(0,lion,his_frequent_complaints).
wearied_jupiter_with(0,lion,his_complaints).
root(1,ROOT,jupiter).
nsubj(1,jupiter,it).
cop(1,jupiter,is).
amod(1,jupiter,true).
compound(1,jupiter,o).
is(1,it,true_o_jupiter).
is(1,it,o_jupiter).
root(2,ROOT,said).
nsubj(2,said,he).
root(3,ROOT,gigantic).
mark(3,gigantic,that).
nsubj(3,gigantic,i).
nsubj(3,powerful,i).
cop(3,gigantic,am).
case(3,strength,in).
nmod:in(3,gigantic,strength).
amod(3,strength,handsome).
case(3,shape,in).
nmod:in(3,strength,shape).
cc(3,gigantic,and).
conj:and(3,gigantic,powerful).
case(3,attack,in).
nmod:in(3,powerful,attack).
am_gigantic_in(3,i,strength_handsome).
is_in(3,strength_handsome,shape).
am_gigantic_in(3,i,strength_in_shape).
am_gigantic_in(3,i,strength_handsome_in_shape).
am(3,i,gigantic).
am_gigantic_in(3,i,strength).
root(4,ROOT,provided).
advmod(4,provided,i).
aux(4,provided,have).
nmod:npmod(4,well,jaws).
advmod(4,provided,well).
case(4,teeth,with).
nmod:with(4,provided,teeth).
cc(4,teeth,and).
nmod:with(4,provided,feet).
conj:and(4,teeth,feet).
acl(4,teeth,furnished).
case(4,claws,with).
nmod:with(4,furnished,claws).
cc(4,claws,and).
compound(4,lord,i).
nmod:with(4,furnished,lord).
conj:and(4,claws,lord).
dep(4,provided,it).
case(4,beasts,over).
det:predet(4,beasts,all).
det(4,beasts,the).
nmod:over(4,provided,beasts).
case(4,forest,of).
det(4,forest,the).
nmod:of(4,beasts,forest).
cc(4,beasts,and).
dobj(4,frightened,what).
det(4,disgrace,a).
mark(4,i,disgrace).
nsubjpass(4,frightened,disgrace).
nsubj(4,is,it).
acl:relcl(4,disgrace,is).
ref(4,disgrace,that).
cop(4,such,being).
csubj(4,i,such).
case(4,i,as).
nmod:as(4,such,i).
cop(4,i,am).
ccomp(4,is,i).
aux(4,frightened,should).
auxpass(4,frightened,be).
nmod:over(4,provided,frightened).
conj:and(4,beasts,frightened).
case(4,crowing,by).
det(4,crowing,the).
nmod:agent(4,frightened,crowing).
case(4,cock,of).
det(4,cock,a).
nmod:of(4,crowing,cock).
root(5,ROOT,replied).
nsubj(5,replied,jupiter).
root(6,ROOT,blame).
advmod(6,blame,why).
aux(6,blame,do).
nsubj(6,blame,you).
dobj(6,blame,me).
case(6,cause,without).
det(6,cause,a).
nmod:without(6,blame,cause).
do_blame(6,you,me).
root(7,ROOT,given).
nsubj(7,given,i).
aux(7,given,have).
iobj(7,given,you).
det:predet(7,attributes,all).
det(7,attributes,the).
dobj(7,given,attributes).
dep(7,possess,attributes).
ref(7,attributes,which).
nsubj(7,possess,i).
acl:relcl(7,attributes,possess).
dobj(7,possess,myself).
cc(7,possess,and).
nmod:poss(7,courage,your).
nsubj(7,fails,courage).
neg(7,fails,never).
acl:relcl(7,attributes,fails).
conj:and(7,possess,fails).
dobj(7,fails,you).
case(7,instance,except).
case(7,instance,in).
det(7,instance,this).
nummod(7,instance,one).
nmod:in(7,fails,instance).
root(8,ROOT,groaned).
case(8,hearing,on).
nmod:on(8,groaned,hearing).
det:predet(8,lion,this).
det(8,lion,the).
nsubj(8,groaned,lion).
nsubj(8,lamented,lion).
cc(8,groaned,and).
conj:and(8,groaned,lamented).
advmod(8,much,very).
csubj(8,wished,much).
cc(8,much,and).
conj:and(8,much,reproaching).
csubj(8,wished,reproaching).
dobj(8,reproaching,himself).
case(8,cowardice,with).
nmod:poss(8,cowardice,his).
nmod:with(8,reproaching,cowardice).
ccomp(8,lamented,wished).
mark(8,die,that).
nsubj(8,die,he).
aux(8,die,might).
ccomp(8,wished,die).
groaned_on(8,lion,hearing).
root(9,ROOT,passed).
mark(9,passed,as).
det(9,thoughts,these).
nsubj(9,passed,thoughts).
case(9,mind,through).
nmod:poss(9,mind,his).
nmod:through(9,passed,mind).
nsubj(9,met,he).
nsubj(9,came,he).
nsubj:xsubj(9,hold,he).
acl:relcl(9,mind,met).
det(9,elephant,an).
dobj(9,met,elephant).
cc(9,met,and).
acl:relcl(9,mind,came).
conj:and(9,met,came).
advmod(9,came,close).
mark(9,hold,to).
xcomp(9,came,hold).
det(9,conversation,a).
dobj(9,hold,conversation).
case(9,him,with).
nmod:with(9,hold,him).
met(9,he,elephant).
root(10,ROOT,observed).
case(10,time,after).
det(10,time,a).
nmod:after(10,observed,time).
nsubj(10,observed,he).
mark(10,shook,that).
det(10,elephant,the).
nsubj(10,shook,elephant).
ccomp(10,observed,shook).
nmod:poss(10,ears,his).
dobj(10,shook,ears).
advmod(10,often,very).
advmod(10,shook,often).
cc(10,shook,and).
nsubj(10,inquired,he).
ccomp(10,observed,inquired).
conj:and(10,shook,inquired).
nsubj(10,matter,what).
cop(10,matter,was).
det(10,matter,the).
dep(10,inquired,matter).
cc(10,matter,and).
advmod(10,moved,why).
nmod:poss(10,ears,his).
nsubj(10,moved,ears).
dep(10,inquired,moved).
conj:and(10,matter,moved).
case(10,tremor,with).
amod(10,tremor,such).
det(10,tremor,a).
nmod:with(10,moved,tremor).
dep(10,now,every).
advmod(10,moved,now).
cc(10,now,and).
advmod(10,moved,then).
conj:and(10,now,then).
moved_now_with(10,his_ears,such_tremor).
moved_with(10,his_ears,such_tremor).
moved_now_and_then_with(10,his_ears,tremor).
shook(10,elephant,his_ears).
moved_now_and_then_with(10,his_ears,such_tremor).
shook_often(10,elephant,his_ears).
shook_very_often(10,elephant,his_ears).
moved_with(10,his_ears,tremor).
observed_after(10,he,time).
moved_now_with(10,his_ears,tremor).
root(11,ROOT,moment).
advmod(11,moment,just).
case(11,moment,at).
det(11,moment,that).
det(11,gnat,a).
nsubj(11,settled,gnat).
acl:relcl(11,moment,settled).
case(11,head,on).
det(11,head,the).
nmod:on(11,settled,head).
case(11,elephant,of).
det(11,elephant,the).
nmod:of(11,head,elephant).
cc(11,settled,and).
nsubj(11,replied,he).
acl:relcl(11,moment,replied).
conj:and(11,settled,replied).
settled_on(11,gnat,head).
settled_on(11,gnat,head_of_elephant).
root(12,ROOT,do).
nsubj(12,see,you).
ccomp(12,do,see).
nsubj(12,buzzing,that).
dep(12,buzzing,little).
xcomp(12,see,buzzing).
dobj(12,buzzing,insect).
see(12,you,buzzing).
root(13,ROOT,enters).
mark(13,enters,if).
nsubj(13,enters,it).
nmod:poss(13,ear,my).
dobj(13,enters,ear).
nmod:poss(13,fate,my).
nsubjpass(13,sealed,fate).
auxpass(13,sealed,is).
acl:relcl(13,ear,sealed).
is(13,my_fate,sealed).
root(14,ROOT,die).
nsubj(14,die,i).
aux(14,die,should).
advmod(14,die,presently).
root(15,ROOT,said).
det(15,lion,the).
nsubj(15,said,lion).
root(16,ROOT,well).
mark(16,huge,since).
advmod(16,huge,so).
dep(16,well,huge).
det(16,beast,a).
nsubj(16,afraid,beast).
cop(16,afraid,is).
ccomp(16,huge,afraid).
case(16,gnat,of).
det(16,gnat,a).
amod(16,gnat,tiny).
nmod:of(16,afraid,gnat).
nsubj(16,complain,i).
aux(16,complain,will).
neg(16,more,no).
advmod(16,complain,more).
acl:relcl(16,gnat,complain).
cc(16,huge,nor).
dep(16,well,wish).
conj:nor(16,huge,wish).
nsubj(16,dead,myself).
xcomp(16,wish,dead).
is(16,beast,afraid).
root(17,ROOT,find).
dep(17,find,i).
dobj(17,find,myself).
advmod(17,find,even).
case(17,i,as).
nmod:as(17,find,i).
advmod(17,better,am).
nsubj(17,find,better).
advmod(17,better,off).
case(17,elephant,than).
det(17,elephant,the).
nmod:than(17,off,elephant).
find_even(17,better,myself).
find(17,better,myself).
