root(0,ROOT,day).
case(0,day,on).
det(0,day,a).
compound(0,day,summer).
advmod(0,induced,when).
det(0,heat,the).
amod(0,heat,great).
nsubj(0,induced,heat).
acl:relcl(0,day,induced).
det(0,thirst,a).
amod(0,thirst,general).
dobj(0,induced,thirst).
case(0,beasts,among).
det(0,beasts,the).
nmod:among(0,induced,beasts).
det(0,lion,a).
nsubj(0,came,lion).
nsubj:xsubj(0,drink,lion).
cc(0,lion,and).
det(0,boar,a).
conj:and(0,lion,boar).
nsubj(0,came,boar).
nsubj:xsubj(0,drink,boar).
acl:relcl(0,beasts,came).
case(0,moment,at).
det(0,moment,the).
amod(0,moment,same).
nmod:at(0,came,moment).
case(0,well,to).
det(0,well,a).
amod(0,well,small).
nmod:to(0,came,well).
mark(0,drink,to).
xcomp(0,came,drink).
induced(0,great_heat,thirst).
came_at(0,boar,same_moment).
came_to(0,boar,small_well).
came(0,boar,drink).
came_to(0,lion,well).
came_to(0,lion,small_well).
induced(0,heat,thirst).
came_to(0,boar,well).
induced(0,heat,general_thirst).
came_at(0,lion,moment).
induced(0,great_heat,general_thirst).
came_at(0,lion,same_moment).
came(0,lion,drink).
came_at(0,boar,moment).
root(1,ROOT,disputed).
nsubj(1,disputed,they).
nsubjpass(1,engaged,they).
advmod(1,disputed,fiercely).
nsubj(1,drink,which).
case(1,them,of).
nmod:of(1,drink,them).
aux(1,drink,should).
ccomp(1,disputed,drink).
dobj(1,drink,first).
cc(1,disputed,and).
auxpass(1,engaged,were).
advmod(1,engaged,soon).
conj:and(1,disputed,engaged).
case(1,agonies,in).
det(1,agonies,the).
nmod:in(1,engaged,agonies).
case(1,combat,of).
det(1,combat,a).
amod(1,combat,mortal).
nmod:of(1,agonies,combat).
were_soon_engaged_in(1,they,agonies).
were_engaged_in(1,they,agonies_of_combat).
were_soon_engaged_in(1,they,agonies_of_combat).
were(1,they,soon_engaged).
were_soon_engaged_in(1,they,agonies_of_mortal_combat).
were(1,they,engaged).
were_engaged_in(1,they,agonies_of_mortal_combat).
were_engaged_in(1,they,agonies).
root(2,ROOT,stopped).
advmod(2,stopped,when).
nsubj(2,stopped,they).
nsubj:xsubj(2,catch,they).
advmod(2,stopped,suddenly).
mark(2,catch,to).
xcomp(2,stopped,catch).
nmod:poss(2,breath,their).
dobj(2,catch,breath).
case(2,renewal,for).
det(2,renewal,a).
amod(2,renewal,fiercer).
nmod:for(2,catch,renewal).
case(2,fight,of).
det(2,fight,the).
nmod:of(2,renewal,fight).
nsubj(2,saw,they).
acl:relcl(2,fight,saw).
det(2,vultures,some).
dobj(2,saw,vultures).
acl(2,vultures,waiting).
case(2,distance,in).
det(2,distance,the).
nmod:in(2,waiting,distance).
mark(2,feast,to).
xcomp(2,waiting,feast).
case(2,one,on).
det(2,one,the).
nmod:on(2,feast,one).
nsubj(2,fall,one).
ref(2,one,that).
aux(2,fall,should).
acl:relcl(2,one,fall).
advmod(2,fall,first).
catch(2,they,their_breath).
saw(2,they,vultures_waiting).
saw(2,they,vultures).
saw(2,they,vultures_waiting_in_distance).
root(3,ROOT,they).
case(3,once,at).
nmod:at(3,they,once).
acl(3,once,made).
compound:prt(3,made,up).
dobj(3,made,their).
dep(3,made,quarrel).
xcomp(3,quarrel,saying).
root(4,ROOT,is).
nsubj(4,is,it).
advmod(4,is,better).
mark(4,make,for).
nsubj(4,make,us).
mark(4,make,to).
advcl:to(4,better,make).
dobj(4,make,friends).
mark(4,become,than).
mark(4,become,to).
advcl:to(4,make,become).
det(4,food,the).
xcomp(4,become,food).
case(4,crows,of).
nmod:of(4,food,crows).
cc(4,crows,or).
nmod:of(4,food,vultures).
conj:or(4,crows,vultures).
