root(0,ROOT,had).
det(0,king,a).
nmod:poss(0,son,king).
nsubj(0,had,king).
ref(0,king,whose).
amod(0,son,only).
nsubj(0,fond,son).
cop(0,fond,was).
acl:relcl(0,king,fond).
case(0,exercises,of).
amod(0,exercises,martial).
nmod:of(0,fond,exercises).
det(0,dream,a).
dobj(0,had,dream).
nmod:in(0,warned,dream).
case(0,which,in).
ref(0,dream,which).
nsubjpass(0,warned,he).
auxpass(0,warned,was).
acl:relcl(0,dream,warned).
mark(0,killed,that).
nmod:poss(0,son,his).
nsubjpass(0,killed,son).
aux(0,killed,would).
auxpass(0,killed,be).
ccomp(0,warned,killed).
case(0,lion,by).
det(0,lion,a).
nmod:agent(0,killed,lion).
was_fond_of(0,son,martial_exercises).
be(0,his_son,killed).
was_fond_of(0,only_son,exercises).
was(0,son,fond).
be_killed_by(0,his_son,lion).
was_fond_of(0,only_son,martial_exercises).
was(0,he,warned).
was(0,only_son,fond).
was_fond_of(0,son,exercises).
root(1,ROOT,kinds).
amod(1,kinds,afraid).
det(1,dream,the).
nsubj(1,prove,dream).
nsubj(1,adorned,dream).
aux(1,prove,should).
ccomp(1,afraid,prove).
xcomp(1,prove,true).
nsubj(1,built,he).
ccomp(1,true,built).
case(1,son,for).
nmod:poss(1,son,his).
nmod:for(1,built,son).
det(1,palace,a).
amod(1,palace,pleasant).
dobj(1,prove,palace).
cc(1,prove,and).
ccomp(1,afraid,adorned).
conj:and(1,prove,adorned).
nmod:poss(1,walls,its).
dobj(1,adorned,walls).
case(1,amusement,for).
nmod:poss(1,amusement,his).
nmod:for(1,adorned,amusement).
case(1,all,with).
nmod:with(1,adorned,all).
case(1,animals,of).
amod(1,animals,life-sized).
nmod:of(1,kinds,animals).
mark(1,picture,among).
nsubj(1,picture,which).
cop(1,picture,was).
det(1,picture,the).
acl:among(1,animals,picture).
case(1,lion,of).
det(1,lion,a).
nmod:of(1,picture,lion).
prove(1,dream,pleasant_palace).
built_for(1,he,his_son).
prove(1,dream,true).
adorned(1,dream,its_walls).
prove(1,dream,palace).
root(2,ROOT,saw).
advmod(2,saw,when).
det(2,prince,the).
amod(2,prince,young).
nsubj(2,saw,prince).
det:predet(2,grief,this).
nmod:poss(2,grief,his).
dobj(2,saw,grief).
mark(2,confined,at).
auxpass(2,confined,being).
advmod(2,confined,thus).
advcl:at(2,saw,confined).
dobj(2,confined,burst).
case(2,afresh,out).
nmod:out(2,confined,afresh).
cc(2,afresh,and).
nmod:out(2,confined,standing).
conj:and(2,afresh,standing).
case(2,lion,near).
det(2,lion,the).
nmod:near(2,standing,lion).
nsubj(2,said,he).
acl:relcl(2,lion,said).
being_thus_confined(2,prince,burst).
being_confined(2,young_prince,burst).
being_confined_burst_out(2,prince,afresh).
being_confined(2,prince,burst).
being_thus_confined_burst_out(2,prince,afresh).
being_thus_confined(2,young_prince,burst).
being_thus_confined_burst_out(2,young_prince,afresh).
saw(2,prince,his_grief).
saw(2,young_prince,his_grief).
being_confined_burst_out(2,young_prince,afresh).
root(3,ROOT,o).
dep(3,o,you).
advmod(3,detestable,most).
amod(3,you,detestable).
case(3,animals,of).
nmod:of(3,you,animals).
root(4,ROOT,dream).
case(4,dream,through).
det(4,dream,a).
amod(4,dream,lying).
case(4,father,of).
nmod:poss(4,father,my).
nmod:s(4,dream,father).
dobj(4,saw,father).
case(4,father,'s).
ref(4,father,which).
nsubj(4,saw,he).
advcl(4,shut,saw).
case(4,sleep,in).
nmod:poss(4,sleep,his).
nmod:in(4,saw,sleep).
nsubjpass(4,shut,i).
auxpass(4,shut,am).
acl:relcl(4,father,shut).
compound:prt(4,shut,up).
case(4,account,on).
nmod:poss(4,account,your).
nmod:on(4,shut,account).
case(4,palace,in).
det(4,palace,this).
nmod:in(4,account,palace).
mark(4,do,as).
mark(4,girl,if).
nsubj(4,girl,i).
aux(4,girl,had).
cop(4,girl,been).
det(4,girl,a).
nsubj(4,shall,girl).
advcl:if(4,do,girl).
ref(4,girl,what).
acl:relcl(4,girl,shall).
nsubj(4,do,i).
advmod(4,do,now).
advcl:as(4,shut,do).
case(4,you,to).
nmod:to(4,do,you).
is_in(4,your_account,palace).
now_do_to(4,i,you).
do_to(4,i,you).
saw_in(4,he,his_sleep).
am_shut_up(4,i,i_do).
am_shut_up_on(4,i,your_account_in_palace).
am_shut_up(4,i,i_do_to_you).
am_shut_up(4,i,i_now_do).
am_shut_up_on(4,i,your_account).
am_shut_up(4,i,i_now_do_to_you).
root(5,ROOT,stretched).
punct(5,words,').
case(5,words,with).
det(5,words,these).
advcl:with(5,stretched,words).
nsubj(5,stretched,he).
compound:prt(5,stretched,out).
nmod:poss(5,hands,his).
dobj(5,stretched,hands).
case(5,meaning,toward).
det(5,meaning,a).
amod(5,meaning,thorn-tree).
nmod:toward(5,hands,meaning).
mark(5,cut,to).
advcl:to(5,stretched,cut).
det(5,stick,a).
dobj(5,cut,stick).
case(5,branches,from).
nmod:poss(5,branches,its).
nmod:from(5,cut,branches).
mark(5,beat,so).
mwe(5,so,that).
nsubj(5,beat,he).
aux(5,beat,might).
advcl:so_that(5,cut,beat).
det(5,lion,the).
dobj(5,beat,lion).
might_beat(5,he,lion).
stretched_out(5,he,his_hands).
cut_stick_from(5,he,its_branches).
stretched_out(5,he,his_hands_toward_meaning).
cut(5,he,stick).
stretched_out(5,he,his_hands_toward_thorn-tree_meaning).
root(6,ROOT,pierced).
cc(6,one,but).
nsubj(6,pierced,one).
nsubj(6,caused,one).
case(6,prickles,of).
det(6,tree,the).
nmod:poss(6,prickles,tree).
case(6,tree,'s).
nmod:of(6,one,prickles).
nmod:poss(6,finger,his).
dobj(6,pierced,finger).
cc(6,pierced,and).
conj:and(6,pierced,caused).
amod(6,pain,great).
dobj(6,caused,pain).
cc(6,pain,and).
dobj(6,caused,inflammation).
conj:and(6,pain,inflammation).
mark(6,fell,so).
mwe(6,so,that).
det(6,prince,the).
amod(6,prince,young).
nsubj(6,fell,prince).
advcl:so_that(6,caused,fell).
compound:prt(6,fell,down).
case(6,fit,in).
det(6,fit,a).
amod(6,fit,fainting).
nmod:in(6,fell,fit).
of(6,tree,prickles).
fell_down_in(6,prince,fainting_fit).
fell_down_in(6,prince,fit).
fell_down_in(6,young_prince,fainting_fit).
fell_down_in(6,young_prince,fit).
root(7,ROOT,set).
det(7,fever,a).
amod(7,fever,violent).
nsubj(7,set,fever).
advmod(7,set,suddenly).
case(7,died,in).
mark(7,died,from).
dobj(7,died,which).
nsubj(7,died,he).
dep(7,set,died).
neg(7,days,not).
amod(7,days,many).
nmod:tmod(7,died,days).
advmod(7,died,later).
