root(0,ROOT,boasted).
det(0,bear,a).
nsubj(0,boasted,bear).
advmod(0,much,very).
xcomp(0,boasted,much).
case(0,philanthropy,of).
nmod:poss(0,philanthropy,his).
nmod:of(0,much,philanthropy).
acl(0,philanthropy,saying).
mark(0,tender,that).
case(0,animals,of).
det(0,animals,all).
nmod:of(0,tender,animals).
nsubj(0,tender,he).
cop(0,tender,was).
det(0,tender,the).
advmod(0,tender,most).
ccomp(0,saying,tender).
case(0,regard,in).
nmod:poss(0,regard,his).
nmod:in(0,tender,regard).
case(0,man,for).
nmod:for(0,regard,man).
mark(0,had,for).
nsubj(0,had,he).
advcl:for(0,tender,had).
amod(0,respect,such).
dobj(0,had,respect).
case(0,him,for).
nmod:for(0,respect,him).
mark(0,touch,that).
nsubj(0,touch,he).
aux(0,touch,would).
neg(0,touch,not).
advmod(0,touch,even).
ccomp(0,boasted,touch).
nmod:poss(0,body,his).
amod(0,body,dead).
dobj(0,touch,body).
root(1,ROOT,hearing).
det(1,hearing,a).
compound(1,hearing,fox).
det(1,words,these).
nsubj(1,said,words).
acl:relcl(1,hearing,said).
case(1,smile,with).
det(1,smile,a).
nmod:with(1,said,smile).
case(1,bear,to).
det(1,bear,the).
nmod:to(1,said,bear).
said_with(1,words,smile).
said_to(1,words,bear).
root(2,ROOT,oh).
root(3,ROOT,eat).
mark(3,eat,that).
nsubj(3,eat,you).
aux(3,eat,would).
det(3,dead,the).
dobj(3,eat,dead).
cc(3,dead,and).
neg(3,living,not).
det(3,living,the).
dobj(3,eat,living).
conj:and(3,dead,living).
