root(0,ROOT,had).
det(0,brazier,a).
nsubj(0,had,brazier).
det(0,dog,a).
amod(0,dog,little).
dobj(0,had,dog).
nsubj(0,favorite,dog).
ref(0,dog,which).
cop(0,favorite,was).
det(0,favorite,a).
amod(0,favorite,great).
acl:relcl(0,dog,favorite).
case(0,master,with).
nmod:poss(0,master,his).
nmod:with(0,favorite,master).
cc(0,master,and).
nmod:poss(0,companion,his).
amod(0,companion,constant).
nmod:with(0,favorite,companion).
conj:and(0,master,companion).
root(1,ROOT,hammered).
mark(1,hammered,while).
nsubj(1,hammered,he).
advmod(1,hammered,away).
case(1,metals,at).
nmod:poss(1,metals,his).
nmod:at(1,away,metals).
det(1,dog,the).
nsubj(1,slept,dog).
ccomp(1,hammered,slept).
root(2,ROOT,went).
cc(2,went,but).
advmod(2,went,when).
case(2,hand,on).
det(2,hand,the).
amod(2,hand,other).
nmod:on(2,went,hand).
nsubj(2,went,he).
nsubj(2,began,he).
nsubj:xsubj(2,eat,he).
case(2,dinner,to).
nmod:to(2,went,dinner).
cc(2,went,and).
conj:and(2,went,began).
mark(2,eat,to).
xcomp(2,began,eat).
det(2,dog,the).
nsubj(2,woke,dog).
nsubj(2,wagged,dog).
ccomp(2,eat,woke).
advmod(2,woke,up).
cc(2,woke,and).
ccomp(2,eat,wagged).
conj:and(2,woke,wagged).
nmod:poss(2,tail,his).
dobj(2,wagged,tail).
mark(2,ask,as).
mwe(2,as,if).
nsubj(2,ask,he).
aux(2,ask,would).
advcl:as_if(2,wagged,ask).
case(2,share,for).
det(2,share,a).
nmod:for(2,ask,share).
case(2,meal,of).
nmod:poss(2,meal,his).
nmod:of(2,share,meal).
began(2,he,eat).
went_to(2,he,dinner).
would_ask_for(2,he,share).
would_ask_for(2,he,share_of_his_meal).
went_on(2,he,hand).
wagged(2,dog,his_tail).
went_on(2,he,other_hand).
root(3,ROOT,said).
nmod:poss(3,day,his).
compound(3,day,master).
nummod(3,day,one).
nsubj(3,said,day).
dep(3,day,pretending).
mark(3,angry,to).
cop(3,angry,be).
xcomp(3,pretending,angry).
cc(3,pretending,and).
dep(3,day,shaking).
conj:and(3,pretending,shaking).
nmod:poss(3,stick,his).
dobj(3,shaking,stick).
case(3,him,at).
nmod:at(3,shaking,him).
root(4,ROOT,wretched).
nsubj(4,wretched,you).
amod(4,sluggard,little).
dobj(4,wretched,sluggard).
wretched(4,you,little_sluggard).
wretched(4,you,sluggard).
root(5,ROOT,shall).
nsubj(5,shall,what).
xcomp(5,shall,i).
acl:relcl(5,i,do).
case(5,you,to).
nmod:to(5,do,you).
root(6,ROOT,hammering).
mark(6,hammering,while).
nsubj(6,hammering,i).
aux(6,hammering,am).
case(6,anvil,on).
det(6,anvil,the).
nmod:on(6,hammering,anvil).
nsubj(6,sleep,you).
acl:relcl(6,anvil,sleep).
case(6,mat,on).
det(6,mat,the).
nmod:on(6,sleep,mat).
sleep_on(6,you,mat).
root(7,ROOT,begin).
cc(7,begin,and).
advmod(7,begin,when).
nsubj(7,begin,i).
nsubj:xsubj(7,eat,i).
mark(7,eat,to).
xcomp(7,begin,eat).
mark(7,toil,after).
nsubj(7,toil,my).
advcl:after(7,eat,toil).
nsubj(7,wake,you).
ccomp(7,toil,wake).
compound:prt(7,wake,up).
cc(7,eat,and).
xcomp(7,begin,wag).
conj:and(7,eat,wag).
nmod:poss(7,tail,your).
dobj(7,wag,tail).
case(7,food,for).
nmod:for(7,wag,food).
begin(7,i,eat).
eat(7,i,my_toil).
root(8,ROOT,know).
aux(8,know,do).
dobj(8,know,you).
neg(8,know,not).
mark(8,source,that).
nsubj(8,source,labor).
cop(8,source,is).
det(8,source,the).
ccomp(8,know,source).
case(8,blessing,of).
det(8,blessing,every).
nmod:of(8,source,blessing).
cc(8,source,and).
mark(8,entitled,that).
nsubjpass(8,entitled,none).
nsubj:xsubj(8,eat,none).
case(8,those,but).
nmod:but(8,none,those).
nsubj(8,work,those).
ref(8,those,who).
acl:relcl(8,those,work).
auxpass(8,entitled,are).
ccomp(8,know,entitled).
conj:and(8,source,entitled).
mark(8,eat,to).
xcomp(8,entitled,eat).
