root(0,ROOT,caught).
det(0,cat,a).
nsubj(0,caught,cat).
nsubj(0,pondered,cat).
det(0,cock,a).
dobj(0,caught,cock).
cc(0,caught,and).
conj:and(0,caught,pondered).
advmod(0,find,how).
nsubj(0,find,he).
aux(0,find,might).
ccomp(0,pondered,find).
det(0,excuse,a).
amod(0,excuse,reasonable).
dobj(0,find,excuse).
mark(0,eating,for).
advcl:for(0,find,eating).
dobj(0,eating,him).
find(0,he,excuse).
caught(0,cat,cock).
find(0,he,reasonable_excuse).
eating(0,he,him).
root(1,ROOT,accused).
nsubj(1,accused,he).
dobj(1,accused,him).
mark(1,nuisance,of).
cop(1,nuisance,being).
det(1,nuisance,a).
advcl:of(1,accused,nuisance).
case(1,men,to).
nmod:to(1,nuisance,men).
mark(1,crowing,by).
advcl:by(1,accused,crowing).
case(1,nighttime,in).
det(1,nighttime,the).
nmod:in(1,crowing,nighttime).
cc(1,crowing,and).
neg(1,permitting,not).
advcl:by(1,accused,permitting).
conj:and(1,crowing,permitting).
dobj(1,permitting,them).
nsubj:xsubj(1,sleep,them).
mark(1,sleep,to).
xcomp(1,permitting,sleep).
accused(1,he,him).
being_nuisance_to(1,he,men).
being(1,he,nuisance).
root(2,ROOT,defended).
det(2,cock,the).
nsubj(2,defended,cock).
dobj(2,defended,himself).
mark(2,saying,by).
advcl:by(2,defended,saying).
mark(2,did,that).
nsubj(2,did,he).
ccomp(2,saying,did).
dobj(2,did,this).
case(2,benefit,for).
det(2,benefit,the).
nmod:for(2,did,benefit).
case(2,men,of).
nmod:of(2,benefit,men).
mark(2,rise,that).
nsubj(2,rise,they).
aux(2,rise,might).
ccomp(2,did,rise).
case(2,time,in).
nmod:in(2,rise,time).
case(2,labors,for).
nmod:poss(2,labors,their).
nmod:for(2,time,labors).
defended(2,cock,himself).
root(3,ROOT,replied).
det(3,cat,the).
nsubj(3,replied,cat).
root(4,ROOT,abound).
mark(4,abound,although).
nsubj(4,abound,you).
case(4,apologies,in).
amod(4,apologies,specious).
nmod:in(4,remain,apologies).
nsubj(4,remain,i).
aux(4,remain,shall).
neg(4,remain,not).
ccomp(4,abound,remain).
xcomp(4,remain,supperless).
root(5,ROOT,made).
cc(5,made,and).
nsubj(5,made,he).
det(5,meal,a).
dobj(5,made,meal).
case(5,him,of).
nmod:of(5,meal,him).
made(5,he,meal).
made(5,he,meal_of_him).
