root(0,ROOT,disputing).
det(0,gods,the).
nsubj(0,disputing,gods).
aux(0,disputing,were).
advmod(0,disputing,once).
mark(0,possible,whether).
nsubj(0,possible,it).
nsubj:xsubj(0,change,it).
cop(0,possible,was).
ccomp(0,disputing,possible).
case(0,living,for).
det(0,living,a).
nmod:for(0,possible,living).
amod(0,living,being).
mark(0,change,to).
xcomp(0,possible,change).
nmod:poss(0,nature,its).
dobj(0,change,nature).
was_possible_for(0,it,living_being).
was_possible_for(0,it,living).
was(0,it,possible).
change(0,it,its_nature).
root(1,ROOT,said).
nsubj(1,said,jupiter).
root(2,ROOT,yes).
root(3,ROOT,said).
cc(3,said,but).
nsubj(3,said,venus).
root(4,ROOT,no).
root(5,ROOT,so).
mark(5,try,to).
xcomp(5,so,try).
det(5,jupiter,the).
compound(5,jupiter,question).
nsubj(5,turned,jupiter).
nsubj(5,gave,jupiter).
ccomp(5,try,turned).
det(5,cat,a).
dobj(5,turned,cat).
case(5,maiden,into).
det(5,maiden,a).
nmod:into(5,turned,maiden).
cc(5,turned,and).
ccomp(5,try,gave).
conj:and(5,turned,gave).
dobj(5,gave,her).
case(5,man,to).
det(5,man,a).
amod(5,man,young).
nmod:to(5,gave,man).
case(5,wife,for).
det(5,wife,a).
nmod:for(5,man,wife).
turned_cat_into(5,question_jupiter,maiden).
turned_into(5,question_jupiter,maiden).
turned(5,question_jupiter,cat).
gave(5,question_jupiter,her).
root(6,ROOT,performed).
det(6,wedding,the).
nsubjpass(6,performed,wedding).
auxpass(6,performed,was).
advmod(6,performed,duly).
cc(6,performed,and).
det(6,couple,the).
amod(6,couple,young).
nsubj(6,sat,couple).
conj:and(6,performed,sat).
advmod(6,sat,down).
case(6,wedding-feast,to).
det(6,wedding-feast,the).
nmod:to(6,down,wedding-feast).
was(6,wedding,duly_performed).
was(6,wedding,performed).
root(7,ROOT,see).
root(8,ROOT,said).
nsubj(8,said,jupiter).
case(8,venus,to).
nmod:to(8,jupiter,venus).
root(9,ROOT,behaves).
advmod(9,behaves,how).
advmod(9,behaves,becomingly).
nsubj(9,behaves,she).
root(10,ROOT,tell).
nsubj(10,tell,who).
aux(10,tell,could).
mark(10,cat,that).
nmod:tmod(10,cat,yesterday).
nsubj(10,cat,she).
cop(10,cat,was).
case(10,cat,but).
det(10,cat,a).
ccomp(10,tell,cat).
was_but(10,she,yesterday_cat).
was_but(10,she,cat).
root(11,ROOT,nature).
dep(11,nature,surely).
nmod:poss(11,nature,her).
auxpass(11,changed,is).
acl:relcl(11,nature,changed).
root(12,ROOT,wait).
det(12,minute,a).
dobj(12,wait,minute).
root(13,ROOT,replied).
nsubj(13,loose,venus).
cc(13,let,and).
dep(13,venus,let).
xcomp(13,replied,loose).
det(13,mouse,a).
nsubj(13,replied,mouse).
case(13,room,into).
det(13,room,the).
nmod:into(13,mouse,room).
replied(13,mouse,venus_loose).
root(14,ROOT,see).
neg(14,sooner,no).
advmod(14,see,sooner).
aux(14,see,did).
det(14,bride,the).
dobj(14,see,bride).
nsubj(14,see,this).
mark(14,jumped,than).
nsubj(14,jumped,she).
nsubj(14,tried,she).
nsubj:xsubj(14,pounce,she).
dep(14,see,jumped).
compound:prt(14,jumped,up).
case(14,seat,from).
nmod:poss(14,seat,her).
nmod:from(14,jumped,seat).
cc(14,jumped,and).
dep(14,see,tried).
conj:and(14,jumped,tried).
mark(14,pounce,to).
xcomp(14,tried,pounce).
case(14,mouse,upon).
det(14,mouse,the).
nmod:upon(14,pounce,mouse).
tried(14,she,pounce_upon_mouse).
tried(14,she,pounce).
root(15,ROOT,ah).
nsubj(15,see,you).
ccomp(15,ah,see).
root(16,ROOT,said).
nsubj(16,said,venus).
root(17,ROOT,will).
nsubj(17,will,nature).
advmod(17,will,out).
