root(0,ROOT,accustomed).
det(0,man,a).
amod(0,man,blind).
nsubjpass(0,accustomed,man).
auxpass(0,accustomed,was).
mark(0,distinguishing,to).
advcl:to(0,accustomed,distinguishing).
amod(0,animals,different).
dobj(0,distinguishing,animals).
mark(0,touching,by).
advcl:by(0,distinguishing,touching).
dobj(0,touching,them).
case(0,hands,with).
nmod:poss(0,hands,his).
nmod:with(0,touching,hands).
was(0,blind_man,accustomed).
distinguishing(0,blind_man,different_animals).
distinguishing(0,blind_man,animals).
distinguishing(0,man,animals).
was(0,man,accustomed).
distinguishing(0,man,different_animals).
root(1,ROOT,brought).
det(1,whelp,the).
nsubjpass(1,brought,whelp).
case(1,wolf,of).
det(1,wolf,a).
nmod:of(1,whelp,wolf).
auxpass(1,brought,was).
dobj(1,brought,him).
case(1,request,with).
det(1,request,a).
nmod:with(1,brought,request).
mark(1,feel,that).
nsubj(1,feel,he).
nsubj(1,say,he).
aux(1,feel,would).
ccomp(1,brought,feel).
dobj(1,feel,it).
cc(1,feel,and).
ccomp(1,brought,say).
conj:and(1,feel,say).
dobj(1,was,what).
nsubj(1,was,it).
ccomp(1,say,was).
was_brought(1,whelp,him).
feel(1,he,it).
root(2,ROOT,felt).
nsubj(2,felt,he).
dobj(2,felt,it).
cc(2,felt,and).
cop(2,doubt,being).
case(2,doubt,in).
csubj(2,said,doubt).
conj:and(2,felt,said).
felt(2,he,it).
root(3,ROOT,know).
nsubj(3,know,i).
aux(3,know,do).
neg(3,know,not).
advmod(3,know,quite).
mark(3,cub,whether).
nsubj(3,cub,it).
cop(3,cub,is).
det(3,cub,the).
ccomp(3,know,cub).
case(3,fox,of).
det(3,fox,a).
nmod:of(3,cub,fox).
cc(3,cub,or).
det(3,whelp,the).
ccomp(3,know,whelp).
conj:or(3,cub,whelp).
case(3,wolf,of).
det(3,wolf,a).
nmod:of(3,whelp,wolf).
cc(3,cub,but).
det(3,i,this).
nsubj(3,know,i).
ccomp(3,know,know).
conj:or(3,cub,know).
advmod(3,well,full).
advmod(3,know,well).
root(4,ROOT,safe).
nsubj(4,safe,it).
nsubj:xsubj(4,admit,it).
aux(4,safe,would).
neg(4,safe,not).
cop(4,safe,be).
mark(4,admit,to).
xcomp(4,safe,admit).
dobj(4,admit,him).
case(4,sheepfold,to).
det(4,sheepfold,the).
nmod:to(4,admit,sheepfold).
