root(0,ROOT,began).
det(0,cobbler,a).
nsubj(0,began,cobbler).
nsubj:xsubj(0,practice,cobbler).
amod(0,cobbler,unable).
mark(0,make,to).
xcomp(0,unable,make).
det(0,living,a).
dobj(0,make,living).
case(0,trade,by).
nmod:poss(0,trade,his).
nmod:by(0,make,trade).
cc(0,make,and).
xcomp(0,unable,made).
conj:and(0,make,made).
xcomp(0,made,desperate).
case(0,poverty,by).
nmod:by(0,made,poverty).
mark(0,practice,to).
xcomp(0,began,practice).
dobj(0,practice,medicine).
case(0,town,in).
det(0,town,a).
nmod:in(0,practice,town).
nmod:in(0,known,town).
case(0,which,in).
ref(0,town,which).
nsubjpass(0,known,he).
auxpass(0,known,was).
neg(0,known,not).
acl:relcl(0,town,known).
made(0,living,desperate).
made_by(0,living,poverty).
practice(0,cobbler,medicine).
practice(0,cobbler_unable,medicine).
root(1,ROOT,sold).
nsubj(1,sold,he).
det(1,drug,a).
dobj(1,sold,drug).
xcomp(1,sold,pretending).
mark(1,antidote,that).
nsubjpass(1,antidote,it).
nsubjpass(1,obtained,it).
auxpass(1,antidote,was).
det(1,antidote,an).
ccomp(1,pretending,antidote).
case(1,poisons,to).
det(1,poisons,all).
nmod:to(1,antidote,poisons).
cc(1,antidote,and).
ccomp(1,pretending,obtained).
conj:and(1,antidote,obtained).
det(1,name,a).
amod(1,name,great).
dobj(1,obtained,name).
case(1,himself,for).
nmod:for(1,name,himself).
case(1,puffs,by).
amod(1,puffs,long-winded).
nmod:by(1,obtained,puffs).
cc(1,puffs,and).
nmod:by(1,obtained,advertisements).
conj:and(1,puffs,advertisements).
obtained(1,it,name).
obtained_name_by(1,it,long-winded_puffs).
obtained(1,it,great_name).
sold(1,he,drug).
was_antidote_to(1,it,poisons).
obtained_name_by(1,it,puffs).
obtained(1,it,great_name_for_himself).
obtained(1,it,name_for_himself).
root(2,ROOT,happened).
advmod(2,happened,when).
det(2,cobbler,the).
nsubj(2,happened,cobbler).
nsubj:xsubj(2,fall,cobbler).
mark(2,fall,to).
xcomp(2,happened,fall).
xcomp(2,fall,sick).
dep(2,sick,himself).
case(2,illness,of).
det(2,illness,a).
amod(2,illness,serious).
nmod:of(2,himself,illness).
det(2,governor,the).
nsubj(2,determined,governor).
nsubj:xsubj(2,test,governor).
case(2,town,of).
det(2,town,the).
nmod:of(2,governor,town).
acl:relcl(2,illness,determined).
mark(2,test,to).
xcomp(2,determined,test).
nmod:poss(2,skill,his).
dobj(2,test,skill).
happened(2,cobbler,fall).
test(2,governor,his_skill).
fall(2,cobbler,sick).
root(3,ROOT,purpose).
case(3,purpose,for).
det(3,purpose,this).
nsubj(3,called,he).
acl:relcl(3,purpose,called).
case(3,cup,for).
det(3,cup,a).
nmod:for(3,called,cup).
cc(3,purpose,and).
mark(3,pretended,while).
csubj(3,pretended,filling).
dobj(3,filling,it).
case(3,water,with).
nmod:with(3,filling,water).
conj:and(3,purpose,pretended).
mark(3,mix,to).
xcomp(3,pretended,mix).
dobj(3,mix,poison).
case(3,antidote,with).
det(3,cobbler,the).
nmod:poss(3,antidote,cobbler).
case(3,cobbler,'s).
nmod:with(3,mix,antidote).
dep(3,antidote,commanding).
dobj(3,commanding,him).
nsubj:xsubj(3,drink,him).
mark(3,drink,to).
xcomp(3,commanding,drink).
dobj(3,drink,it).
case(3,promise,on).
det(3,promise,the).
nmod:on(3,drink,promise).
case(3,reward,of).
det(3,reward,a).
nmod:of(3,promise,reward).
with(3,cobbler,antidote).
called_for(3,he,cup).
drink(3,him,it).
root(4,ROOT,confessed).
det(4,cobbler,the).
nsubj(4,confessed,cobbler).
case(4,fear,under).
det(4,fear,the).
nmod:under(4,cobbler,fear).
case(4,death,of).
nmod:of(4,fear,death).
mark(4,had,that).
nsubj(4,had,he).
nsubjpass(4,made,he).
ccomp(4,confessed,had).
neg(4,knowledge,no).
dobj(4,had,knowledge).
case(4,medicine,of).
nmod:of(4,knowledge,medicine).
cc(4,had,and).
auxpass(4,made,was).
advmod(4,made,only).
ccomp(4,confessed,made).
conj:and(4,had,made).
xcomp(4,made,famous).
case(4,clamors,by).
det(4,clamors,the).
amod(4,clamors,stupid).
nmod:agent(4,made,clamors).
case(4,crowd,of).
det(4,crowd,the).
nmod:of(4,clamors,crowd).
was(4,he,made).
was_made(4,he,famous).
was_made_by(4,he,stupid_clamors_of_crowd).
was(4,he,only_made).
was_made_by(4,he,clamors).
was_only_made_by(4,he,stupid_clamors).
was_made_by(4,he,stupid_clamors).
was_only_made_by(4,he,clamors).
was_only_made_by(4,he,clamors_of_crowd).
was_made_by(4,he,clamors_of_crowd).
was_only_made_by(4,he,stupid_clamors_of_crowd).
was_only_made(4,he,famous).
root(5,ROOT,called).
det(5,governor,the).
nsubj(5,called,governor).
nsubj(5,addressed,governor).
advmod(5,called,then).
det(5,assembly,a).
amod(5,assembly,public).
dobj(5,called,assembly).
cc(5,called,and).
conj:and(5,called,addressed).
det(5,citizens,the).
dobj(5,addressed,citizens).
called(5,governor,public_assembly).
called(5,governor,assembly).
addressed(5,governor,citizens).
root(6,ROOT,guilty).
case(6,folly,of).
det(6,folly,what).
nmod:of(6,guilty,folly).
aux(6,guilty,have).
nsubj(6,guilty,you).
cop(6,guilty,been).
have(6,you,have_guilty).
root(7,ROOT,hesitated).
nsubj(7,hesitated,you).
nsubj:xsubj(7,entrust,you).
aux(7,hesitated,have).
neg(7,hesitated,not).
mark(7,entrust,to).
xcomp(7,hesitated,entrust).
nmod:poss(7,heads,your).
dobj(7,entrust,heads).
case(7,man,to).
det(7,man,a).
nmod:to(7,entrust,man).
dobj(7,make,man).
ref(7,man,whom).
neg(7,one,no).
nsubj(7,employ,one).
nsubj:xsubj(7,make,one).
aux(7,employ,could).
acl:relcl(7,man,employ).
mark(7,make,to).
xcomp(7,employ,make).
advmod(7,shoes,even).
det(7,shoes,the).
dobj(7,make,shoes).
case(7,feet,for).
nmod:poss(7,feet,their).
nmod:for(7,shoes,feet).
