root(0,ROOT,turns).
det(0,birds,the).
nsubj(0,waged,birds).
dep(0,turns,waged).
dobj(0,waged,war).
case(0,beasts,with).
det(0,beasts,the).
nmod:with(0,waged,beasts).
cc(0,waged,and).
nsubj(0,by,each).
cop(0,by,were).
conj:and(0,waged,by).
dep(0,turns,by).
det(0,conquerors,the).
nsubj(0,turns,conquerors).
root(1,ROOT,strongest).
det(1,bat,a).
nsubj(1,strongest,bat).
acl(1,bat,fearing).
det(1,issues,the).
amod(1,issues,uncertain).
dobj(1,fearing,issues).
case(1,fight,of).
det(1,fight,the).
nmod:of(1,issues,fight).
advmod(1,fought,always).
acl(1,fight,fought).
case(1,side,on).
det(1,side,the).
nmod:on(1,fought,side).
dobj(1,felt,side).
ref(1,side,which).
nsubj(1,felt,he).
acl:relcl(1,side,felt).
cop(1,strongest,was).
det(1,strongest,the).
uncertain_issues_of(1,fearing,fight).
fearing(1,bat,uncertain_issues).
fearing(1,bat,uncertain_issues_of_fight_fought).
was(1,bat,strongest).
uncertain_issues_of(1,fearing,fight_fought).
uncertain_issues_of(1,fearing,fight_always_fought).
fearing(1,bat,uncertain_issues_of_fight).
fearing(1,bat,uncertain_issues_of_fight_always_fought).
root(2,ROOT,proclaimed).
advmod(2,proclaimed,when).
nsubjpass(2,proclaimed,peace).
auxpass(2,proclaimed,was).
nmod:poss(2,conduct,his).
amod(2,conduct,deceitful).
nsubj(2,apparent,conduct).
cop(2,apparent,was).
ccomp(2,proclaimed,apparent).
case(2,combatants,to).
det(2,combatants,both).
nmod:to(2,apparent,combatants).
was_apparent_to(2,his_conduct,combatants).
was(2,peace,proclaimed).
was(2,peace,when_proclaimed).
was_apparent_to(2,his_deceitful_conduct,combatants).
root(3,ROOT,condemned).
advmod(3,condemned,therefore).
auxpass(3,condemned,being).
case(3,each,by).
nmod:agent(3,condemned,each).
case(3,treachery,for).
nmod:poss(3,treachery,his).
nmod:for(3,each,treachery).
nsubjpass(3,driven,he).
auxpass(3,driven,was).
acl:relcl(3,treachery,driven).
advmod(3,driven,forth).
case(3,light,from).
det(3,light,the).
nmod:from(3,driven,light).
case(3,day,of).
nmod:of(3,light,day).
cc(3,day,and).
nmod:of(3,light,henceforth).
conj:and(3,day,henceforth).
dep(3,condemned,concealed).
nsubjpass(3,condemned,himself).
nsubjpass(3,condemned,himself).
conj:and(3,himself,himself).
case(3,hiding-places,in).
amod(3,hiding-places,dark).
nmod:in(3,himself,hiding-places).
acl(3,hiding-places,flying).
advmod(3,flying,always).
advmod(3,flying,alone).
cc(3,himself,and).
case(3,night,at).
nmod:at(3,himself,night).
was_driven_from(3,he,light_of_day).
being(3,himself,therefore_condemned).
therefore_being_condemned_by(3,himself,each).
was_driven_forth_from(3,he,light_of_day).
was(3,he,driven).
being_condemned_by(3,himself,each).
was_driven_forth_from(3,he,light).
was_driven_from(3,he,light).
being(3,himself,condemned).
was(3,he,driven_forth).
