root(0,ROOT,striving).
det(0,bull,a).
nsubj(0,striving,bull).
aux(0,striving,was).
case(0,all,with).
nmod:with(0,striving,all).
nsubj(0,might,his).
nsubj:xsubj(0,squeeze,his).
acl:relcl(0,all,might).
mark(0,squeeze,to).
xcomp(0,might,squeeze).
dobj(0,squeeze,himself).
case(0,passage,through).
det(0,passage,a).
amod(0,passage,narrow).
nmod:through(0,squeeze,passage).
nsubj(0,led,passage).
ref(0,passage,which).
acl:relcl(0,passage,led).
dep(0,stall,to).
nsubj(0,stall,his).
ccomp(0,led,stall).
root(1,ROOT,came).
det(1,calf,a).
amod(1,calf,young).
nsubj(1,came,calf).
nsubj(1,offered,calf).
nsubj:xsubj(1,go,calf).
advmod(1,came,up).
cc(1,came,and).
conj:and(1,came,offered).
mark(1,go,to).
xcomp(1,offered,go).
advmod(1,go,before).
cc(1,go,and).
xcomp(1,offered,show).
conj:and(1,go,show).
dobj(1,show,him).
det(1,way,the).
nmod(1,show,way).
mark(1,way,by).
dobj(1,pass,which).
nsubj(1,manage,he).
nsubj:xsubj(1,pass,he).
aux(1,manage,could).
dep(1,way,manage).
mark(1,pass,to).
xcomp(1,manage,pass).
offered(1,calf,go_before).
offered(1,young_calf,go).
offered(1,calf,go).
offered(1,young_calf,go_before).
root(2,ROOT,trouble).
case(2,yourself,save).
nmod:save(2,trouble,yourself).
det(2,trouble,the).
root(3,ROOT,said).
det(3,bull,the).
nsubj(3,said,bull).
root(4,ROOT,knew).
nsubj(4,knew,i).
det(4,way,that).
dobj(4,knew,way).
advmod(4,born,long).
mark(4,born,before).
nsubjpass(4,born,you).
auxpass(4,born,were).
advcl:before(4,knew,born).
knew_way(4,i,born).
knew_way(4,i,long_born).
knew(4,i,long_born).
knew(4,i,way).
were(4,you,long_born).
knew(4,i,born).
were(4,you,born).
