root(0,ROOT,carried).
det(0,charcoal-burner,a).
nsubj(0,carried,charcoal-burner).
case(0,trade,on).
nmod:poss(0,trade,his).
nmod:on(0,carried,trade).
case(0,house,in).
nmod:poss(0,house,his).
amod(0,house,own).
nmod:in(0,carried,house).
carried_in(0,charcoal-burner,his_house).
carried_on(0,charcoal-burner,his_trade).
carried_in(0,charcoal-burner,his_own_house).
root(1,ROOT,day).
nummod(1,day,one).
nsubj(1,met,he).
nsubj(1,entreated,he).
acl:relcl(1,day,met).
det(1,friend,a).
dobj(1,met,friend).
det(1,fuller,a).
amod(1,friend,fuller).
cc(1,met,and).
acl:relcl(1,day,entreated).
conj:and(1,met,entreated).
dobj(1,entreated,him).
nsubj:xsubj(1,come,him).
nsubj:xsubj(1,live,him).
mark(1,come,to).
xcomp(1,entreated,come).
cc(1,come,and).
xcomp(1,entreated,live).
conj:and(1,come,live).
mark(1,saying,with).
nsubj(1,saying,him).
acl:with(1,day,saying).
mark(1,neighbors,that).
nsubj(1,neighbors,they).
aux(1,neighbors,should).
cop(1,neighbors,be).
advmod(1,better,far).
amod(1,neighbors,better).
ccomp(1,saying,neighbors).
cc(1,neighbors,and).
mark(1,lessened,that).
nmod:poss(1,expenses,their).
amod(1,expenses,housekeeping).
nsubjpass(1,lessened,expenses).
aux(1,lessened,would).
auxpass(1,lessened,be).
ccomp(1,saying,lessened).
conj:and(1,neighbors,lessened).
entreated(1,he,him).
met(1,he,friend_fuller).
met(1,he,friend).
root(2,ROOT,replied).
det(2,fuller,the).
dep(2,replied,fuller).
root(3,ROOT,impossible).
det(3,arrangement,the).
nsubj(3,impossible,arrangement).
cop(3,impossible,is).
case(3,far,as).
advmod(3,impossible,far).
mark(3,concerned,as).
nsubjpass(3,concerned,i).
auxpass(3,concerned,am).
advcl:as(3,impossible,concerned).
mark(3,whiten,for).
dobj(3,whiten,whatever).
nsubj(3,whiten,i).
aux(3,whiten,should).
advcl:for(3,concerned,whiten).
nsubj(3,blacken,you).
aux(3,blacken,would).
advmod(3,blacken,immediately).
ccomp(3,whiten,blacken).
advmod(3,blacken,again).
case(3,charcoal,with).
nmod:poss(3,charcoal,your).
nmod:with(3,blacken,charcoal).
is_impossible(3,arrangement,concerned).
immediately_blacken_again_with(3,you,your_charcoal).
is(3,arrangement,impossible).
blacken_with(3,you,your_charcoal).
is_impossible_far(3,arrangement,concerned).
blacken_again_with(3,you,your_charcoal).
is(3,arrangement,impossible_as_far).
immediately_blacken_with(3,you,your_charcoal).
am(3,i,concerned).
root(4,ROOT,draw).
mark(4,draw,like).
aux(4,draw,will).
nmod(4,draw,like).
