root(0,ROOT,boasted).
det(0,man,a).
nsubj(0,traveled,man).
nsubj(0,boasted,man).
ref(0,man,who).
aux(0,traveled,had).
acl:relcl(0,man,traveled).
case(0,lands,in).
amod(0,lands,foreign).
nmod:in(0,traveled,lands).
advmod(0,much,very).
advmod(0,boasted,much).
mark(0,returning,on).
advcl:on(0,boasted,returning).
case(0,country,to).
nmod:poss(0,country,his).
amod(0,country,own).
nmod:to(0,returning,country).
case(0,wonderful,of).
det(0,wonderful,the).
amod(0,wonderful,many).
nmod:of(0,country,wonderful).
cc(0,wonderful,and).
amod(0,feats,heroic).
nmod:of(0,country,feats).
conj:and(0,wonderful,feats).
nsubj(0,performed,he).
aux(0,performed,had).
ccomp(0,returning,performed).
case(0,places,in).
det(0,places,the).
amod(0,places,different).
nmod:in(0,performed,places).
nsubj(0,visited,he).
aux(0,visited,had).
acl:relcl(0,places,visited).
root(1,ROOT,said).
case(1,things,among).
amod(1,things,other).
nmod:among(1,said,things).
nsubj(1,said,he).
mark(1,leaped,that).
advmod(1,rhodes,when).
nsubj(1,rhodes,he).
cop(1,rhodes,was).
case(1,rhodes,at).
advcl:at(1,leaped,rhodes).
nsubj(1,leaped,he).
aux(1,leaped,had).
ccomp(1,said,leaped).
case(1,distance,to).
det:predet(1,distance,such).
det(1,distance,a).
nmod:to(1,leaped,distance).
mark(1,leap,that).
neg(1,man,no).
nsubj(1,leap,man).
case(1,day,of).
nmod:poss(1,day,his).
nmod:of(1,man,day).
aux(1,leap,could).
ccomp(1,leaped,leap).
advmod(1,leap,anywhere).
case(1,him,near).
nmod:near(1,anywhere,him).
case(1,were,as).
mark(1,were,to).
mark(1,were,that).
expl(1,were,there).
dep(1,leap,were).
case(1,rhodes,in).
nmod:in(1,were,rhodes).
amod(1,persons,many).
nsubj(1,were,persons).
nsubj(1,saw,persons).
ref(1,persons,who).
acl:relcl(1,persons,saw).
nsubj(1,do,him).
ccomp(1,saw,do).
dobj(1,do,it).
cc(1,were,and).
dobj(1,call,whom).
nsubj(1,call,he).
aux(1,call,could).
dep(1,leap,call).
conj:and(1,were,call).
case(1,witnesses,as).
nmod:as(1,call,witnesses).
said_among(1,he,things).
said_among(1,he,other_things).
root(2,ROOT,interrupted).
det:qmod(2,bystanders,one).
mwe(2,one,of).
det(2,bystanders,the).
nsubj(2,interrupted,bystanders).
nsubj(2,saying,him).
dep(2,interrupted,saying).
root(3,ROOT,man).
dep(3,man,now).
nmod:poss(3,man,my).
amod(3,man,good).
mark(3,true,if).
nsubj(3,true,this).
cop(3,true,be).
det(3,true,all).
advcl:if(3,is,true).
expl(3,is,there).
acl:relcl(3,man,is).
neg(3,need,no).
nsubj(3,is,need).
case(3,witnesses,of).
nmod:of(3,need,witnesses).
root(4,ROOT,suppose).
dobj(4,suppose,this).
nsubj:xsubj(4,rhodes,this).
mark(4,rhodes,to).
cop(4,rhodes,be).
xcomp(4,suppose,rhodes).
cc(4,rhodes,and).
xcomp(4,suppose,leap).
conj:and(4,rhodes,leap).
case(4,us,for).
nmod:for(4,rhodes,us).
