root(0,ROOT,gored).
det(0,bull,a).
nsubj(0,gored,bull).
acl(0,bull,finding).
det(0,lion,a).
nmod:poss(0,cub,lion).
case(0,lion,'s).
nsubj(0,asleep,cub).
xcomp(0,finding,asleep).
dobj(0,gored,him).
case(0,death,to).
nmod:to(0,gored,death).
case(0,horns,with).
nmod:poss(0,horns,his).
nmod:with(0,gored,horns).
has(0,lion,cub).
gored(0,bull,him).
root(1,ROOT,came).
det(1,lioness,the).
nsubj(1,came,lioness).
nsubj(1,lamented,lioness).
advmod(1,came,up).
cc(1,came,and).
advmod(1,lamented,bitterly).
conj:and(1,came,lamented).
det(1,death,the).
dobj(1,lamented,death).
case(1,whelp,of).
nmod:poss(1,whelp,her).
nmod:of(1,death,whelp).
bitterly_lamented(1,lioness,death_of_her_whelp).
lamented(1,lioness,death).
bitterly_lamented(1,lioness,death).
lamented(1,lioness,death_of_her_whelp).
root(2,ROOT,stood).
det(2,hunter,a).
amod(2,hunter,wild-boar).
nsubj(2,stood,hunter).
nsubj(2,said,hunter).
acl(2,hunter,seeing).
nmod:poss(2,distress,her).
dobj(2,seeing,distress).
case(2,distance,at).
det(2,distance,a).
nmod:at(2,stood,distance).
cc(2,stood,and).
conj:and(2,stood,said).
case(2,her,to).
nmod:to(2,said,her).
said_to(2,wild-boar_hunter,her).
stood_at(2,hunter,distance).
stood_at(2,wild-boar_hunter,distance).
said_to(2,hunter,her).
root(3,ROOT,think).
advmod(3,are,how).
amod(3,men,many).
dep(3,how,men).
expl(3,are,there).
ccomp(3,think,are).
nsubj(3,have,who).
ccomp(3,are,have).
dobj(3,have,reason).
case(3,lament,to).
nmod:to(3,have,lament).
det(3,loss,the).
nsubj(3,think,loss).
nmod:poss(3,deaths,loss).
case(3,children,of).
nmod:poss(3,children,their).
nmod:of(3,loss,children).
ref(3,loss,whose).
nsubjpass(3,caused,deaths).
aux(3,caused,have).
auxpass(3,caused,been).
acl:relcl(3,loss,caused).
case(3,you,by).
nmod:agent(3,caused,you).
have(3,deaths,have_caused).
have(3,deaths,have_caused_by_you).
