root(0,ROOT,about).
det(0,conflict,a).
amod(0,conflict,great).
nsubj(0,about,conflict).
nsubj:xsubj(0,come,conflict).
aux(0,about,was).
mark(0,come,to).
xcomp(0,about,come).
compound:prt(0,come,off).
case(0,birds,between).
det(0,birds,the).
nmod:between(0,come,birds).
cc(0,birds,and).
det(0,beasts,the).
nmod:between(0,come,beasts).
conj:and(0,birds,beasts).
come_off_between(0,conflict,birds).
come_off_between(0,great_conflict,birds).
root(1,ROOT,collected).
advmod(1,collected,when).
det(1,armies,the).
nummod(1,armies,two).
nsubjpass(1,collected,armies).
auxpass(1,collected,were).
advmod(1,collected,together).
det(1,bat,the).
nsubj(1,hesitated,bat).
ccomp(1,collected,hesitated).
nsubj(1,join,which).
mark(1,join,to).
ccomp(1,hesitated,join).
were(1,armies,collected).
were(1,armies,when_collected).
were(1,two_armies,collected_together).
were(1,two_armies,collected).
were(1,two_armies,when_collected_together).
were(1,armies,collected_together).
were(1,armies,when_collected_together).
were(1,two_armies,when_collected).
root(2,ROOT,said).
det(2,birds,the).
nsubj(2,passed,birds).
nsubj(2,said,birds).
ref(2,birds,that).
acl:relcl(2,birds,passed).
nmod:poss(2,perch,his).
dobj(2,passed,perch).
root(3,ROOT,come).
case(3,us,with).
nmod:with(3,come,us).
root(4,ROOT,said).
cc(4,said,but).
nsubj(4,said,he).
root(5,ROOT,am).
advmod(5,am,i).
det(5,beast,a).
nsubj(5,am,beast).
root(6,ROOT,beasts).
advmod(6,beasts,later).
case(6,beasts,on).
det(6,beasts,some).
nsubj(6,passing,beasts).
ref(6,beasts,who).
aux(6,passing,were).
acl:relcl(6,beasts,passing).
mark(6,looked,underneath).
nsubj(6,looked,him).
nsubj(6,said,him).
advcl:underneath(6,passing,looked).
compound:prt(6,looked,up).
cc(6,looked,and).
advcl:underneath(6,passing,said).
conj:and(6,looked,said).
root(7,ROOT,come).
case(7,us,with).
nmod:with(7,come,us).
root(8,ROOT,said).
cc(8,said,but).
nsubj(8,said,he).
root(9,ROOT,am).
advmod(9,am,i).
det(9,bird,a).
nsubj(9,am,bird).
root(10,ROOT,made).
advmod(10,made,luckily).
case(10,moment,at).
det(10,moment,the).
amod(10,moment,last).
nmod:at(10,made,moment).
nsubjpass(10,made,peace).
auxpass(10,made,was).
cc(10,made,and).
neg(10,battle,no).
nsubj(10,took,battle).
conj:and(10,made,took).
dobj(10,took,place).
mark(10,came,so).
det(10,bat,the).
nsubj(10,came,bat).
nsubj(10,wished,bat).
nsubj:xsubj(10,join,bat).
advcl:so(10,took,came).
case(10,birds,to).
det(10,birds,the).
nmod:to(10,came,birds).
cc(10,came,and).
advcl:so(10,took,wished).
conj:and(10,came,wished).
mark(10,join,to).
xcomp(10,wished,join).
case(10,rejoicings,in).
det(10,rejoicings,the).
nmod:in(10,join,rejoicings).
cc(10,made,but).
nsubj(10,turned,they).
advmod(10,turned,all).
conj:but(10,made,turned).
case(10,him,against).
nmod:against(10,turned,him).
cc(10,made,and).
nsubj(10,had,he).
nsubj:xsubj(10,fly,he).
conj:but(10,made,had).
mark(10,fly,to).
xcomp(10,had,fly).
advmod(10,fly,away).
all_turned_against(10,they,him).
had(10,he,fly).
had(10,he,fly_away).
turned_against(10,they,him).
root(11,ROOT,went).
nsubj(11,went,he).
nsubj(11,had,he).
nsubj:xsubj(11,beat,he).
advmod(11,went,then).
case(11,beasts,to).
det(11,beasts,the).
nmod:to(11,went,beasts).
cc(11,went,but).
advmod(11,had,soon).
conj:but(11,went,had).
mark(11,beat,to).
xcomp(11,had,beat).
det(11,retreat,a).
dobj(11,beat,retreat).
cc(11,retreat,or).
dobj(11,beat,else).
conj:or(11,retreat,else).
nsubj(11,torn,they).
aux(11,torn,would).
aux(11,torn,have).
dep(11,else,torn).
dobj(11,torn,him).
case(11,pieces,to).
nmod:to(11,torn,pieces).
went_to(11,he,beasts).
root(12,ROOT,ah).
root(13,ROOT,said).
det(13,bat,the).
nsubj(13,said,bat).
