root(0,ROOT,sent).
det(0,charger,a).
nsubjpass(0,sent,charger).
nsubj:xsubj(0,work,charger).
acl(0,charger,feeling).
det(0,infirmities,the).
dobj(0,feeling,infirmities).
case(0,age,of).
nmod:of(0,infirmities,age).
auxpass(0,sent,was).
mark(0,work,to).
xcomp(0,sent,work).
case(0,mill,in).
det(0,mill,a).
nmod:in(0,work,mill).
mark(0,going,instead).
mwe(0,instead,of).
acl:instead_of(0,mill,going).
compound:prt(0,going,out).
case(0,battle,to).
nmod:to(0,going,battle).
was(0,charger,sent).
infirmities_of(0,feeling,age).
was_sent(0,charger,work).
root(1,ROOT,compelled).
cc(1,compelled,but).
advmod(1,compelled,when).
nsubjpass(1,compelled,he).
nsubj:xsubj(1,grind,he).
nsubjpass(1,called,he).
nsubj:xsubj(1,mind,he).
auxpass(1,compelled,was).
mark(1,grind,to).
xcomp(1,compelled,grind).
mark(1,serving,instead).
mwe(1,instead,of).
advcl:instead_of(1,grind,serving).
case(1,wars,in).
det(1,wars,the).
nmod:in(1,serving,wars).
nsubj(1,bewailed,he).
acl:relcl(1,wars,bewailed).
nmod:poss(1,change,his).
dobj(1,bewailed,change).
case(1,fortune,of).
nmod:of(1,change,fortune).
cc(1,compelled,and).
conj:and(1,compelled,called).
mark(1,mind,to).
xcomp(1,called,mind).
nmod:poss(1,state,his).
amod(1,state,former).
dobj(1,mind,state).
acl(1,state,saying).
grind(1,he,serving).
bewailed(1,he,his_change_of_fortune).
was(1,he,compelled).
was_compelled(1,he,grind).
was(1,he,when_compelled).
bewailed(1,he,his_change).
root(2,ROOT,ah).
root(3,ROOT,miller).
nsubj(3,had,i).
nsubj:xsubj(3,go,i).
acl:relcl(3,miller,had).
advmod(3,had,indeed).
mark(3,go,to).
xcomp(3,had,go).
dobj(3,go,campaigning).
mark(3,barbed,before).
cc(3,barbed,but).
nsubjpass(3,barbed,i).
auxpass(3,barbed,was).
advcl:before(3,go,barbed).
case(3,counter,from).
nmod:from(3,barbed,counter).
case(3,tail,to).
nmod:to(3,barbed,tail).
cc(3,barbed,and).
det(3,man,a).
nsubj(3,went,man).
nsubj:xsubj(3,groom,man).
advcl:before(3,go,went).
conj:but(3,barbed,went).
advmod(3,went,along).
mark(3,groom,to).
xcomp(3,went,groom).
dobj(3,groom,me).
go_campaigning(3,i,barbed_to_tail).
go(3,i,barbed).
was_barbed_from(3,i,counter).
go_campaigning(3,i,barbed).
go(3,i,barbed_from_counter).
groom(3,man,me).
go_campaigning(3,i,barbed_from_counter_to_tail).
had(3,i,go).
had_indeed(3,i,go).
was(3,i,barbed).
go(3,i,barbed_from_counter_to_tail).
go(3,i,campaigning).
was_barbed_to(3,i,tail).
go(3,i,barbed_to_tail).
go_campaigning(3,i,barbed_from_counter).
was(3,i,barbed_from_counter_to_tail).
root(4,ROOT,now).
cc(4,now,and).
nsubj(4,ailed,now).
nsubj(4,understand,i).
aux(4,understand,can).
neg(4,understand,not).
acl:relcl(4,now,understand).
ref(4,now,what).
ccomp(4,understand,ailed).
dobj(4,ailed,me).
nsubj:xsubj(4,prefer,me).
mark(4,prefer,to).
xcomp(4,ailed,prefer).
det(4,mill,the).
dobj(4,prefer,mill).
case(4,battle,before).
det(4,battle,the).
nmod:before(4,prefer,battle).
root(5,ROOT,forbear).
root(6,ROOT,said).
det(6,miller,the).
nsubj(6,said,miller).
case(6,him,to).
nmod:to(6,miller,him).
root(7,ROOT,harping).
mark(7,yore,on).
nsubj(7,yore,what).
cop(7,yore,was).
case(7,yore,of).
advcl:of(7,harping,yore).
mark(7,lot,for).
nsubj(7,lot,it).
cop(7,lot,is).
det(7,lot,the).
amod(7,lot,common).
advcl:for(7,yore,lot).
case(7,mortals,of).
nmod:of(7,lot,mortals).
mark(7,sustain,to).
acl:to(7,mortals,sustain).
det(7,ups,the).
dobj(7,sustain,ups).
cc(7,ups,and).
dobj(7,sustain,downs).
conj:and(7,ups,downs).
case(7,fortune,of).
nmod:of(7,ups,fortune).
is(7,it,lot).
is(7,it,common_lot).
