root(0,ROOT,pleaded).
det(0,bat,a).
nsubj(0,fell,bat).
nsubjpass(0,caught,bat).
nsubj(0,pleaded,bat).
nsubjpass:xsubj(0,spared,bat).
ref(0,bat,who).
acl:relcl(0,bat,fell).
case(0,ground,upon).
det(0,ground,the).
nmod:upon(0,fell,ground).
cc(0,fell,and).
auxpass(0,caught,was).
acl:relcl(0,bat,caught).
conj:and(0,fell,caught).
case(0,weasel,by).
det(0,weasel,a).
nmod:agent(0,caught,weasel).
mark(0,spared,to).
auxpass(0,spared,be).
xcomp(0,pleaded,spared).
nmod:poss(0,life,his).
dobj(0,spared,life).
root(1,ROOT,refused).
det(1,weasel,the).
nsubj(1,refused,weasel).
xcomp(1,refused,saying).
mark(1,enemy,that).
nsubj(1,enemy,he).
cop(1,enemy,was).
case(1,nature,by).
nmod:by(1,enemy,nature).
det(1,enemy,the).
ccomp(1,saying,enemy).
case(1,birds,of).
det(1,birds,all).
nmod:of(1,enemy,birds).
refused(1,weasel,saying).
root(2,ROOT,assured).
det(2,bat,the).
nsubj(2,assured,bat).
dobj(2,assured,him).
mark(2,bird,that).
nsubj(2,bird,he).
cop(2,bird,was).
neg(2,bird,not).
det(2,bird,a).
ccomp(2,assured,bird).
case(2,mouse,but).
det(2,mouse,a).
nmod:but(2,bird,mouse).
cc(2,mouse,and).
nmod:but(2,bird,thus).
conj:and(2,mouse,thus).
auxpass(2,set,was).
dep(2,mouse,set).
xcomp(2,set,free).
root(3,ROOT,fell).
advmod(3,fell,shortly).
advmod(3,fell,afterwards).
det(3,bat,the).
nmod:npmod(3,again,bat).
advmod(3,fell,again).
case(3,ground,to).
det(3,ground,the).
nmod:to(3,fell,ground).
cc(3,fell,and).
auxpass(3,caught,was).
conj:and(3,fell,caught).
case(3,weasel,by).
det(3,weasel,another).
nmod:agent(3,caught,weasel).
dobj(3,entreated,whom).
nsubj:xsubj(3,eat,whom).
nsubj(3,entreated,he).
advmod(3,entreated,likewise).
dep(3,fell,entreated).
neg(3,eat,not).
mark(3,eat,to).
xcomp(3,entreated,eat).
dobj(3,eat,him).
root(4,ROOT,said).
det(4,weasel,the).
nsubj(4,said,weasel).
mark(4,had,that).
nsubj(4,had,he).
ccomp(4,said,had).
det(4,hostility,a).
amod(4,hostility,special).
dobj(4,had,hostility).
case(4,mice,to).
nmod:to(4,hostility,mice).
root(5,ROOT,assured).
det(5,bat,the).
nsubj(5,assured,bat).
dobj(5,assured,him).
mark(5,mouse,that).
nsubj(5,mouse,he).
cop(5,mouse,was).
neg(5,mouse,not).
det(5,mouse,a).
ccomp(5,assured,mouse).
case(5,bat,but).
det(5,bat,a).
nmod:but(5,mouse,bat).
cc(5,bat,and).
nmod:but(5,mouse,thus).
conj:and(5,bat,thus).
det(5,time,a).
amod(5,time,second).
nsubj(5,escaped,time).
dep(5,bat,escaped).
