root(0,ROOT,traveling).
nummod(0,men,two).
nsubj(0,traveling,men).
aux(0,traveling,were).
advmod(0,traveling,together).
advmod(0,met,when).
det(0,bear,a).
nsubj(0,met,bear).
advmod(0,met,suddenly).
advcl(0,traveling,met).
dobj(0,met,them).
case(0,path,on).
nmod:poss(0,path,their).
nmod:on(0,met,path).
met(0,bear,them).
suddenly_met(0,bear,them).
root(1,ROOT,climbed).
det:qmod(1,them,one).
mwe(1,one,of).
nsubj(1,climbed,them).
nsubj(1,concealed,them).
compound:prt(1,climbed,up).
advmod(1,tree,quickly).
case(1,tree,into).
det(1,tree,a).
nmod:into(1,climbed,tree).
cc(1,climbed,and).
conj:and(1,climbed,concealed).
dobj(1,concealed,himself).
case(1,branches,in).
det(1,branches,the).
nmod:in(1,concealed,branches).
root(2,ROOT,held).
det(2,other,the).
nsubj(2,held,other).
nsubj(2,feigned,other).
acl(2,other,seeing).
mark(2,attacked,that).
nsubjpass(2,attacked,he).
nsubjpass(2,smelt,he).
aux(2,attacked,must).
auxpass(2,attacked,be).
ccomp(2,seeing,attacked).
dep(2,attacked,fell).
xcomp(2,fell,flat).
case(2,ground,on).
det(2,ground,the).
nmod:on(2,fell,ground).
cc(2,fell,and).
advmod(2,came,when).
det(2,bear,the).
nsubj(2,came,bear).
nsubj(2,felt,bear).
dep(2,attacked,came).
conj:and(2,fell,came).
advmod(2,came,up).
cc(2,came,and).
conj:and(2,fell,felt).
conj:and(2,came,felt).
dobj(2,felt,him).
case(2,snout,with).
nmod:poss(2,snout,his).
nmod:with(2,felt,snout).
cc(2,attacked,and).
ccomp(2,seeing,smelt).
conj:and(2,attacked,smelt).
dobj(2,smelt,him).
dep(2,he,all).
case(2,he,over).
nmod:over(2,smelt,he).
nmod:poss(2,breath,his).
dobj(2,held,breath).
cc(2,held,and).
conj:and(2,held,feigned).
det(2,appearance,the).
dobj(2,feigned,appearance).
case(2,death,of).
nmod:of(2,appearance,death).
advmod(2,much,as).
advmod(2,feigned,much).
mark(2,could,as).
nsubj(2,could,he).
advcl:as(2,much,could).
be(2,he,attacked).
feigned(2,other,appearance).
felt(2,bear,him).
felt_with(2,bear,his_snout).
held(2,other,his_breath).
smelt(2,he,him).
root(3,ROOT,left).
det(3,bear,the).
nsubj(3,left,bear).
advmod(3,left,soon).
dobj(3,left,him).
mark(3,said,for).
nsubjpass(3,said,it).
auxpass(3,said,is).
advcl:for(3,left,said).
nsubj(3,touch,he).
aux(3,touch,will).
neg(3,touch,not).
ccomp(3,said,touch).
det(3,body,a).
amod(3,body,dead).
dobj(3,touch,body).
soon_left(3,bear,him).
left(3,bear,him).
root(4,ROOT,gone).
advmod(4,gone,when).
nsubjpass(4,gone,he).
auxpass(4,gone,was).
advmod(4,gone,quite).
det(4,traveler,the).
amod(4,traveler,other).
nsubj(4,descended,traveler).
nsubj(4,inquired,traveler).
ccomp(4,gone,descended).
case(4,tree,from).
det(4,tree,the).
nmod:from(4,descended,tree).
cc(4,descended,and).
advmod(4,inquired,jocularly).
ccomp(4,gone,inquired).
conj:and(4,descended,inquired).
case(4,friend,of).
nmod:poss(4,friend,his).
nmod:of(4,inquired,friend).
dobj(4,bear,friend).
ref(4,friend,what).
nsubj(4,bear,it).
cop(4,bear,was).
det(4,bear,the).
acl:relcl(4,friend,bear).
aux(4,whispered,had).
acl:relcl(4,bear,whispered).
case(4,ear,in).
nmod:poss(4,ear,his).
nmod:in(4,whispered,ear).
was(4,he,when_quite_gone).
was(4,he,when_gone).
descended_from(4,other_traveler,tree).
was_bear(4,it,had_whispered).
was(4,he,quite_gone).
was_bear(4,it,had_whispered_in_his_ear).
was(4,he,gone).
descended_from(4,traveler,tree).
root(5,ROOT,gave).
nsubj(5,gave,he).
iobj(5,gave,me).
det(5,advice,this).
dobj(5,gave,advice).
gave(5,he,me).
gave(5,he,advice).
root(6,ROOT,replied).
nmod:poss(6,companion,his).
nsubj(6,replied,companion).
root(7,ROOT,travel).
neg(7,travel,never).
case(7,friend,with).
det(7,friend,a).
nmod:with(7,travel,friend).
dep(7,you,friend).
ref(7,friend,who).
dep(7,you,deserts).
acl:relcl(7,friend,you).
case(7,approach,at).
det(7,approach,the).
nmod:at(7,travel,approach).
case(7,danger,of).
nmod:of(7,approach,danger).
