root(0,ROOT,summoned).
det(0,man,an).
amod(0,man,old).
nsubj(0,summoned,man).
case(0,point,on).
det(0,point,the).
nmod:on(0,man,point).
case(0,death,of).
nmod:of(0,point,death).
nmod:poss(0,sons,his).
dobj(0,summoned,sons).
case(0,him,around).
nmod:around(0,summoned,him).
mark(0,give,to).
advcl:to(0,summoned,give).
iobj(0,give,them).
det(0,advice,some).
compound(0,advice,parting).
dobj(0,give,advice).
give(0,man,them).
give(0,old_man,them).
give(0,old_man,parting_advice).
give(0,man,parting_advice).
summoned(0,man,his_sons).
summoned(0,old_man,his_sons).
root(1,ROOT,ordered).
nsubj(1,ordered,he).
nsubj(1,said,he).
nmod:poss(1,servants,his).
dobj(1,ordered,servants).
nsubj:xsubj(1,bring,servants).
mark(1,bring,to).
xcomp(1,ordered,bring).
compound:prt(1,bring,in).
det(1,faggot,a).
dobj(1,bring,faggot).
case(1,sticks,of).
nmod:of(1,faggot,sticks).
cc(1,ordered,and).
conj:and(1,ordered,said).
case(1,son,to).
nmod:poss(1,son,his).
amod(1,son,eldest).
nmod:to(1,said,son).
bring_in(1,his_servants,faggot).
bring_in(1,his_servants,faggot_of_sticks).
said_to(1,he,his_son).
said_to(1,he,his_eldest_son).
ordered(1,he,his_servants).
root(2,ROOT,break).
dobj(2,break,it).
root(3,ROOT,unable).
det(3,son,the).
nsubj(3,unable,son).
nsubj:xsubj(3,break,son).
amod(3,son,strained).
cc(3,strained,and).
amod(3,son,strained).
conj:and(3,strained,strained).
cc(3,efforts,but).
case(3,efforts,with).
det:predet(3,efforts,all).
nmod:poss(3,efforts,his).
nmod:with(3,son,efforts).
cop(3,unable,was).
mark(3,break,to).
xcomp(3,unable,break).
det(3,bundle,the).
dobj(3,break,bundle).
is_with(3,son_strained,efforts).
root(4,ROOT,tried).
det(4,sons,the).
amod(4,sons,other).
nsubj(4,tried,sons).
advmod(4,tried,also).
cc(4,successful,but).
nsubj(4,successful,none).
case(4,them,of).
nmod:of(4,none,them).
cop(4,successful,was).
ccomp(4,tried,successful).
was(4,none,successful).
root(5,ROOT,untie).
det(5,faggots,the).
dobj(5,untie,faggots).
root(6,ROOT,said).
det(6,father,the).
nsubj(6,said,father).
root(7,ROOT,take).
cc(7,take,and).
nsubj(7,take,each).
case(7,you,of).
nmod:of(7,each,you).
det(7,stick,a).
dobj(7,take,stick).
root(8,ROOT,done).
advmod(8,done,when).
nsubj(8,done,they).
aux(8,done,had).
advmod(8,called,so).
nsubj(8,called,he).
ccomp(8,done,called).
compound:prt(8,called,out).
case(8,them,to).
nmod:to(8,called,them).
called_out_to(8,he,them).
so_called_out_to(8,he,them).
root(9,ROOT,break).
dep(9,break,now).
root(10,ROOT,stick).
cc(10,stick,and).
det(10,stick,each).
auxpass(10,broken,was).
advmod(10,broken,easily).
ccomp(10,stick,broken).
root(11,ROOT,see).
nsubj(11,see,you).
nmod:poss(11,meaning,my).
dobj(11,see,meaning).
see(11,you,my_meaning).
root(12,ROOT,said).
nmod:poss(12,father,their).
nsubj(12,said,father).
