root(0,ROOT,was).
case(0,country,at).
det(0,country,a).
nmod:at(0,was,country).
amod(0,country,fair).
expl(0,was,there).
det(0,buffoon,a).
nsubj(0,was,buffoon).
nsubj(0,made,buffoon).
ref(0,buffoon,who).
acl:relcl(0,buffoon,made).
det:predet(0,people,all).
det(0,people,the).
nsubj(0,laugh,people).
ccomp(0,made,laugh).
mark(0,imitating,by).
advcl:by(0,laugh,imitating).
nsubj(0,cries,the).
ccomp(0,imitating,cries).
case(0,animals,of).
amod(0,animals,various).
nmod:of(0,cries,animals).
root(1,ROOT,finished).
nsubj(1,finished,he).
compound:prt(1,finished,off).
mark(1,squeaking,by).
advcl:by(1,finished,squeaking).
advmod(1,squeaking,so).
case(1,pig,like).
det(1,pig,a).
nmod:like(1,so,pig).
mark(1,thought,that).
det(1,spectators,the).
nsubj(1,thought,spectators).
ccomp(1,squeaking,thought).
mark(1,had,that).
nsubj(1,had,he).
ccomp(1,thought,had).
det(1,porker,a).
dobj(1,had,porker).
acl:relcl(1,porker,concealed).
case(1,him,about).
nmod:about(1,concealed,him).
finished_off(1,he,squeaking_so_like_pig).
finished_off(1,he,squeaking).
finished_off(1,he,squeaking_so).
root(2,ROOT,countryman).
cc(2,countryman,but).
det(2,countryman,a).
nsubj(2,stood,countryman).
ref(2,countryman,who).
acl:relcl(2,countryman,stood).
mark(2,said,by).
advcl:by(2,stood,said).
root(3,ROOT,call).
mark(3,squeak,that).
det(3,pig,a).
nsubj(3,squeak,pig).
aux(3,squeak,s).
ccomp(3,call,squeak).
root(4,ROOT,nothing).
case(4,it,like).
nmod:like(4,nothing,it).
root(5,ROOT,give).
nsubj(5,give,you).
dobj(5,give,me).
mark(5,show,till).
nsubj(5,show,tomorrow).
cc(5,tomorrow,and).
conj:and(5,tomorrow,i).
nsubj(5,show,i).
aux(5,show,will).
advcl:till(5,give,show).
dobj(5,show,you).
dobj(5,like,what).
nsubj(5,like,it).
cop(5,like,'s).
dep(5,show,like).
will_show(5,i,you).
give(5,you,me).
will_show(5,tomorrow,you).
root(6,ROOT,laughed).
det(6,audience,the).
nsubj(6,laughed,audience).
cc(6,appeared,but).
amod(6,day,next).
dep(6,appeared,day).
advmod(6,appeared,sure).
advmod(6,appeared,enough).
det(6,countryman,the).
nmod:npmod(6,enough,countryman).
dep(6,laughed,appeared).
case(6,stage,on).
det(6,stage,the).
nmod:on(6,appeared,stage).
cc(6,appeared,and).
csubj(6,squealed,putting).
nmod:poss(6,head,his).
dobj(6,putting,head).
advmod(6,putting,down).
dep(6,laughed,squealed).
conj:and(6,appeared,squealed).
advmod(6,hideously,so).
xcomp(6,squealed,hideously).
mark(6,hissed,that).
det(6,spectators,the).
nsubj(6,hissed,spectators).
nsubj(6,threw,spectators).
ccomp(6,squealed,hissed).
cc(6,hissed,and).
ccomp(6,squealed,threw).
conj:and(6,hissed,threw).
dobj(6,threw,stones).
case(6,him,at).
nmod:at(6,threw,him).
mark(6,make,to).
advcl:to(6,threw,make).
nsubj(6,stop,him).
xcomp(6,make,stop).
threw_stones_at(6,spectators,him).
threw(6,spectators,stones).
threw_stones(6,spectators,make).
root(7,ROOT,you).
dep(7,you,fools).
root(8,ROOT,cried).
nsubj(8,cried,he).
root(9,ROOT,see).
dobj(9,hissing,what).
nsubj(9,hissing,you).
aux(9,hissing,have).
aux(9,hissing,been).
ccomp(9,see,hissing).
root(10,ROOT,held).
cc(10,held,and).
compound:prt(10,held,up).
det(10,pig,a).
amod(10,pig,little).
dobj(10,held,pig).
nmod:poss(10,ear,pig).
ref(10,pig,whose).
dobj(10,pinching,ear).
nsubj:xsubj(10,make,ear).
nsubj(10,pinching,he).
aux(10,pinching,had).
aux(10,pinching,been).
acl:relcl(10,pig,pinching).
mark(10,make,to).
xcomp(10,pinching,make).
iobj(10,make,him).
amod(10,him,utter).
det(10,squeals,the).
dobj(10,make,squeals).
make(10,ear,him).
make(10,ear,squeals).
make(10,ear,him_utter).
