root(0,ROOT,stung).
det(0,boy,a).
nsubjpass(0,stung,boy).
auxpass(0,stung,was).
case(0,nettle,by).
det(0,nettle,a).
nmod:agent(0,stung,nettle).
was(0,boy,stung).
was_stung_by(0,boy,nettle).
root(1,ROOT,ran).
nsubj(1,ran,he).
nsubj(1,told,he).
dobj(1,ran,home).
cc(1,ran,and).
conj:and(1,ran,told).
nmod:poss(1,mother,his).
dobj(1,told,mother).
xcomp(1,told,saying).
ran(1,he,home).
told(1,he,his_mother).
root(2,ROOT,hurts).
mark(2,hurts,although).
nsubj(2,hurts,it).
nsubj(2,touched,me).
advmod(2,much,very).
dep(2,touched,much).
nsubj(2,touched,i).
advmod(2,touched,only).
xcomp(2,hurts,touched).
dobj(2,touched,it).
advmod(2,touched,gently).
touched_gently(2,i,it).
only_touched(2,me,it).
touched(2,i,it).
only_touched_gently(2,me,it).
touched_gently(2,me,it).
only_touched_gently(2,i,it).
only_touched(2,i,it).
touched(2,me,it).
root(3,ROOT,was).
nsubj(3,was,that).
advmod(3,was,just).
advmod(3,stung,why).
nsubj(3,stung,it).
advcl(3,was,stung).
dobj(3,stung,you).
stung(3,it,you).
root(4,ROOT,said).
nmod:poss(4,mother,his).
nsubj(4,said,mother).
root(5,ROOT,time).
det(5,time,the).
amod(5,time,next).
nsubj(5,touch,you).
acl:relcl(5,time,touch).
det(5,grasp,a).
amod(5,grasp,nettle).
dobj(5,touch,grasp).
nsubj(5,boldly,it).
acl:relcl(5,grasp,boldly).
cc(5,boldly,and).
nsubj(5,soft,it).
aux(5,soft,will).
cop(5,soft,be).
acl:relcl(5,grasp,soft).
conj:and(5,boldly,soft).
case(5,silk,as).
nmod:as(5,soft,silk).
case(5,hand,to).
nmod:poss(5,hand,your).
nmod:to(5,you,hand).
cc(5,you,and).
neg(5,hurt,not).
case(5,hurt,in).
det(5,hurt,the).
dep(5,hurt,least).
nmod(5,soft,hurt).
conj:and(5,you,hurt).
nmod(5,soft,you).
