root(0,ROOT,hunting).
det(0,boy,a).
nsubj(0,hunting,boy).
cop(0,hunting,was).
case(0,locusts,for).
nmod:for(0,hunting,locusts).
was_hunting_for(0,boy,locusts).
was(0,boy,hunting).
root(1,ROOT,caught).
nsubj(1,caught,he).
aux(1,caught,had).
det(1,number,a).
amod(1,number,goodly).
dobj(1,caught,number).
advmod(1,saw,when).
nsubj(1,saw,he).
advcl(1,caught,saw).
det(1,scorpion,a).
dobj(1,saw,scorpion).
cc(1,saw,and).
csubj(1,reached,mistaking).
dobj(1,mistaking,him).
case(1,locust,for).
det(1,locust,a).
nmod:for(1,mistaking,locust).
advcl(1,caught,reached).
conj:and(1,saw,reached).
compound:prt(1,reached,out).
nmod:poss(1,hand,his).
dobj(1,reached,hand).
mark(1,take,to).
acl:to(1,hand,take).
dobj(1,take,him).
had_caught(1,he,number).
saw(1,he,scorpion).
had_caught(1,he,goodly_number).
root(2,ROOT,said).
det(2,scorpion,the).
nsubj(2,said,scorpion).
acl(2,scorpion,showing).
nmod:poss(2,sting,his).
dobj(2,showing,sting).
mark(2,had,if).
nsubj(2,had,you).
nsubj(2,touched,you).
advcl:if(2,lost,had).
cc(2,had,but).
conj:but(2,had,touched).
advcl:if(2,lost,touched).
nsubj(2,friend,me).
nmod:poss(2,friend,my).
xcomp(2,touched,friend).
nsubj(2,lost,you).
aux(2,lost,would).
aux(2,lost,have).
ccomp(2,said,lost).
dobj(2,lost,me).
cc(2,lost,and).
det:predet(2,locusts,all).
nmod:poss(2,locusts,your).
ccomp(2,said,locusts).
conj:and(2,lost,locusts).
advmod(2,locusts,too).
showing(2,scorpion,his_sting).
