%% a cat fell in love with a handsome young man and entreated venus to change her into the form of a woman.
% dependencies.
root(0,root,fall).
det(0,cat,a).
nsubj(0,fall,cat).
nsubj:xsubj(0,change,cat).
case(0,love,in).
nmod:in(0,fall,love).
case(0,man,with).
det(0,man,a).
amod(0,man,handsome).
amod(0,man,young).
nmod:with(0,fall,man).
cc(0,man,and).
amod(0,venus,entreated).
nmod:with(0,fall,venus).
conj:and(0,man,venus).
mark(0,change,to).
xcomp(0,fall,change).
dobj(0,change,she).
case(0,form,into).
det(0,form,the).
nmod:into(0,change,form).
case(0,woman,of).
det(0,woman,a).
nmod:of(0,form,woman).
% relations.
aos(0,change,cat,she).
aos(0,fall_in,cat,love).
aos(0,fall_with,cat,man).
aos(0,fall_with,cat,young_man).
aos(0,fall_with,cat,handsome_man).
aos(0,fall_with,cat,handsome_young_man).
%% venus consented to her request and transformed her into a beautiful damsel so that the youth saw her and loved her and took her home as his bride.
% dependencies.
root(1,root,consent).
nsubj(1,consent,venus).
nsubj(1,transform,venus).
case(1,request,to).
nmod:poss(1,request,she).
nmod:to(1,consent,request).
cc(1,consent,and).
conj:and(1,consent,transform).
dobj(1,transform,she).
case(1,damsel,into).
det(1,damsel,a).
amod(1,damsel,beautiful).
nmod:into(1,transform,damsel).
mark(1,see,so).
mwe(1,so,that).
det(1,youth,the).
nsubj(1,see,youth).
nsubj(1,love,youth).
advcl:so_that(1,transform,see).
dobj(1,see,she).
cc(1,see,and).
advcl:so_that(1,transform,love).
conj:and(1,see,love).
dobj(1,love,she).
cc(1,love,and).
conj:and(1,see,take).
conj:and(1,love,take).
nmod:poss(1,home,she).
dobj(1,take,home).
case(1,bride,as).
nmod:poss(1,bride,he).
nmod:as(1,take,bride).
% relations.
aos(1,see,youth,she).
aos(1,consent_to,venus,she_request).
aos(1,transform,venus,she).
aos(1,take,she,she_home).
aos(1,love,youth,she).
%% while the two were reclining in their chamber venus wishing to discover if the cat in her change of shape had also altered her habits of life let down a mouse in the middle of the room.
% dependencies.
root(2,root,recline).
mark(2,recline,while).
det(2,two,the).
nsubj(2,recline,two).
aux(2,recline,be).
case(2,venus,in).
nmod:poss(2,venus,they).
compound(2,venus,chamber).
nmod:in(2,recline,venus).
acl(2,venus,wish).
mark(2,discover,to).
xcomp(2,wish,discover).
mark(2,alter,if).
det(2,cat,the).
nsubj(2,alter,cat).
case(2,change,in).
nmod:poss(2,change,she).
nmod:in(2,cat,change).
case(2,shape,of).
nmod:of(2,change,shape).
aux(2,alter,have).
advmod(2,alter,also).
advcl:if(2,discover,alter).
nmod:poss(2,habit,she).
nsubj(2,let,habit).
case(2,life,of).
nmod:of(2,habit,life).
ccomp(2,alter,let).
compound:prt(2,let,down).
det(2,mouse,a).
dobj(2,let,mouse).
case(2,middle,in).
det(2,middle,the).
nmod:in(2,mouse,middle).
case(2,room,of).
det(2,room,the).
nmod:of(2,middle,room).
% relations.
aos(2,let_down,she_habit,mouse_in_middle).
aos(2,mouse_in,she_habit,middle_of_room).
aos(2,mouse_in,she_habit,middle).
aos(2,is_in,mouse,middle_of_room).
aos(2,let_down,she_habit,mouse_in_middle_of_room).
aos(2,is_in,cat,she_change_of_shape).
aos(2,be_recline_in,two,they_chamber_venus).
aos(2,be_recline_in,two,they_chamber_venus_wish).
aos(2,let_down,she_habit,mouse).
%% the cat quite forgetting her present condition started up from the couch and pursued the mouse wishing to eat it.
% dependencies.
root(3,root,start).
det(3,cat,the).
nsubj(3,start,cat).
nsubj(3,pursue,cat).
advmod(3,forget,quite).
acl(3,cat,forget).
nmod:poss(3,condition,she).
amod(3,condition,present).
dobj(3,forget,condition).
compound:prt(3,start,up).
case(3,couch,from).
det(3,couch,the).
nmod:from(3,start,couch).
cc(3,start,and).
conj:and(3,start,pursue).
det(3,mouse,the).
dobj(3,pursue,mouse).
acl(3,mouse,wish).
mark(3,eat,to).
xcomp(3,wish,eat).
dobj(3,eat,it).
% relations.
aos(3,forget,cat,she_condition).
aos(3,pursue,cat,mouse).
aos(3,pursue,cat,mouse_wish).
aos(3,quite_forget,cat,she_present_condition).
aos(3,quite_forget,cat,she_condition).
aos(3,forget,cat,she_present_condition).
aos(3,start_up_from,cat,couch).
%% venus was much disappointed and again caused her to return to her former shape.
% dependencies.
root(4,root,disappointed).
nsubj(4,disappointed,venus).
nsubj(4,cause,venus).
cop(4,disappointed,be).
advmod(4,disappointed,much).
cc(4,disappointed,and).
advmod(4,cause,again).
conj:and(4,disappointed,cause).
dobj(4,cause,she).
nsubj:xsubj(4,return,she).
mark(4,return,to).
xcomp(4,cause,return).
case(4,shape,to).
nmod:poss(4,shape,she).
amod(4,shape,former).
nmod:to(4,return,shape).
% relations.
aos(4,cause,venus,she).
aos(4,be,venus,disappointed).
aos(4,be,venus,much_disappointed).
aos(4,again_cause,venus,she).
aos(4,return_to,she,she_former_shape).
