root(0,ROOT,saw).
det(0,boys,some).
nsubj(0,saw,boys).
nsubj(0,began,boys).
nsubj:xsubj(0,pelt,boys).
acl(0,boys,playing).
case(0,pond,near).
det(0,pond,a).
nmod:near(0,playing,pond).
det:qmod(0,frogs,a).
mwe(0,a,number).
mwe(0,a,of).
dobj(0,saw,frogs).
case(0,water,in).
det(0,water,the).
nmod:in(0,frogs,water).
cc(0,saw,and).
conj:and(0,saw,began).
mark(0,pelt,to).
xcomp(0,began,pelt).
dobj(0,pelt,them).
case(0,stones,with).
nmod:with(0,pelt,stones).
is_in(0,frogs,water).
root(1,ROOT,killed).
nsubj(1,killed,they).
det:qmod(1,them,several).
mwe(1,several,of).
dobj(1,killed,them).
advmod(1,cried,when).
det:qmod(1,frogs,one).
mwe(1,one,of).
det(1,frogs,the).
nsubj(1,cried,frogs).
acl(1,frogs,lifting).
nmod:poss(1,head,his).
dobj(1,lifting,head).
case(1,water,out).
mwe(1,out,of).
det(1,water,the).
nmod:out_of(1,lifting,water).
advcl(1,killed,cried).
compound:prt(1,cried,out).
root(2,ROOT,pray).
xcomp(2,pray,stop).
nmod:poss(2,boys,my).
dobj(2,stop,boys).
nsubj(2,sport,boys).
ref(2,boys,what).
cop(2,sport,is).
acl:relcl(2,boys,sport).
dep(2,death,to).
nsubj(2,death,you).
cop(2,death,is).
dep(2,sport,death).
case(2,us,to).
nmod:to(2,death,us).
