root(0,ROOT,looks).
det(0,father,a).
nsubj(0,looks,father).
acl(0,father,had).
nummod(0,son,one).
iobj(0,had,son).
cc(0,son,and).
nummod(0,daughter,one).
iobj(0,had,daughter).
conj:and(0,son,daughter).
det(0,remarkable,the).
amod(0,remarkable,former).
dobj(0,had,remarkable).
case(0,good,for).
nmod:poss(0,good,his).
nmod:for(0,had,good).
det(0,latter,the).
dobj(0,looks,latter).
case(0,ugliness,for).
nmod:poss(0,ugliness,her).
amod(0,ugliness,extraordinary).
nmod:for(0,latter,ugliness).
looks(0,father,latter).
looks(0,father,latter_for_her_extraordinary_ugliness).
looks(0,father,latter_for_her_ugliness).
root(1,ROOT,playing).
mark(1,playing,while).
nsubj(1,playing,they).
aux(1,playing,were).
nummod(1,day,one).
dobj(1,playing,day).
case(1,children,as).
nmod:as(1,day,children).
nsubj(1,happened,they).
nsubj:xsubj(1,look,they).
acl:relcl(1,children,happened).
case(1,chance,by).
nmod:by(1,happened,chance).
mark(1,look,to).
xcomp(1,happened,look).
advmod(1,look,together).
case(1,mirror,into).
det(1,mirror,a).
nmod:into(1,look,mirror).
nsubjpass(1,placed,mirror).
ref(1,mirror,that).
auxpass(1,placed,was).
acl:relcl(1,mirror,placed).
case(1,chair,on).
nmod:poss(1,mother,their).
nmod:poss(1,chair,mother).
case(1,mother,'s).
nmod:on(1,placed,chair).
happened(1,they,look_together).
happened_by(1,they,chance).
happened(1,they,look).
were_playing(1,they,one_day).
on(1,mother,chair).
root(2,ROOT,congratulated).
det(2,boy,the).
nsubj(2,congratulated,boy).
dobj(2,congratulated,himself).
case(2,looks,on).
nmod:poss(2,looks,his).
amod(2,looks,good).
nmod:on(2,congratulated,looks).
congratulated(2,boy,himself).
root(3,ROOT,grew).
det(3,girl,the).
nsubj(3,grew,girl).
nsubj(3,bear,girl).
xcomp(3,grew,angry).
cc(3,grew,and).
aux(3,bear,could).
neg(3,bear,not).
conj:and(3,grew,bear).
det(3,self-praises,the).
dobj(3,bear,self-praises).
case(3,brother,of).
nmod:poss(3,brother,her).
nmod:of(3,self-praises,brother).
acl(3,brother,interpreting).
dobj(3,interpreting,all).
nsubj(3,said,he).
acl:relcl(3,all,said).
punct(3,could,-LRB-).
cc(3,could,and).
advmod(3,could,how).
dep(3,bear,could).
dobj(3,bear,she).
dep(3,grew,do).
advmod(3,do,otherwise).
root(4,ROOT,reflection).
punct(4,reflection,-RRB-).
case(4,reflection,into).
case(4,herself,on).
nmod:on(4,reflection,herself).
root(5,ROOT,ran).
nsubj(5,ran,she).
advmod(5,ran,off).
case(5,father,to).
nmod:poss(5,father,her).
nmod:to(5,ran,father).
ran_off_to(5,she,her_father).
ran_to(5,she,her_father).
root(6,ROOT,avenged).
mark(6,avenged,to).
auxpass(6,avenged,be).
case(6,brother,on).
nmod:poss(6,brother,her).
nmod:on(6,avenged,brother).
cc(6,avenged,and).
advmod(6,accused,spitefully).
conj:and(6,avenged,accused).
dobj(6,accused,him).
mark(6,made,of).
aux(6,made,having).
case(6,boy,as).
det(6,boy,a).
advmod(6,made,boy).
advcl:of(6,accused,made).
dobj(6,made,use).
case(6,that,of).
nmod:of(6,use,that).
nsubj(6,belonged,that).
ref(6,that,which).
acl:relcl(6,that,belonged).
advmod(6,belonged,only).
case(6,girls,to).
nmod:to(6,belonged,girls).
root(7,ROOT,embraced).
det(7,father,the).
nsubj(7,embraced,father).
dep(7,both,them).
dep(7,embraced,both).
cc(7,both,and).
csubj(7,said,bestowing).
nmod:poss(7,kisses,his).
dobj(7,bestowing,kisses).
cc(7,kisses,and).
dobj(7,bestowing,affection).
conj:and(7,kisses,affection).
advmod(7,bestowing,impartially).
case(7,each,on).
nmod:on(7,bestowing,each).
dep(7,embraced,said).
conj:and(7,both,said).
root(8,ROOT,wish).
nsubj(8,wish,i).
nsubj(8,look,you).
dep(8,look,both).
aux(8,look,would).
ccomp(8,wish,look).
case(8,mirror,into).
det(8,mirror,the).
nmod:into(8,look,mirror).
det(8,day,every).
dep(8,mirror,day).
dep(8,spoil,you).
nmod:poss(8,son,my).
dep(8,you,son).
mark(8,spoil,that).
nsubj(8,spoil,you).
aux(8,spoil,may).
neg(8,spoil,not).
ccomp(8,look,spoil).
nmod:poss(8,beauty,your).
dobj(8,spoil,beauty).
case(8,conduct,by).
amod(8,conduct,evil).
nmod:by(8,spoil,conduct).
root(9,ROOT,you).
cc(9,you,and).
nmod:poss(9,daughter,my).
dep(9,you,daughter).
mark(9,make,that).
nsubj(9,make,you).
aux(9,make,may).
dep(9,daughter,make).
compound:prt(9,make,up).
case(9,lack,for).
nmod:poss(9,lack,your).
nmod:for(9,make,lack).
case(9,beauty,of).
nmod:of(9,lack,beauty).
case(9,virtues,by).
nmod:poss(9,virtues,your).
nmod:by(9,make,virtues).
