root(0,ROOT,overrun).
det(0,house,a).
amod(0,house,certain).
nsubjpass(0,overrun,house).
auxpass(0,overrun,was).
case(0,mice,with).
nmod:with(0,overrun,mice).
was(0,house,overrun).
was_overrun_with(0,certain_house,mice).
was(0,certain_house,overrun).
was_overrun_with(0,house,mice).
root(1,ROOT,made).
det(1,cat,a).
nsubj(1,made,cat).
nsubj(1,began,cat).
nsubj:xsubj(1,catch,cat).
acl(1,cat,discovering).
dobj(1,discovering,this).
nmod:poss(1,way,her).
dobj(1,made,way).
case(1,it,into).
nmod:into(1,made,it).
cc(1,made,and).
conj:and(1,made,began).
mark(1,catch,to).
xcomp(1,began,catch).
cc(1,catch,and).
xcomp(1,began,eat).
conj:and(1,catch,eat).
dobj(1,catch,them).
nmod:by(1,catch,one).
case(1,one,by).
dep(1,one,one).
made(1,cat,her_way).
root(2,ROOT,fearing).
case(2,lives,for).
nmod:poss(2,lives,their).
nmod:for(2,fearing,lives).
det(2,mice,the).
nsubj(2,kept,mice).
acl:relcl(2,lives,kept).
nsubj(2,close,themselves).
xcomp(2,kept,close).
case(2,holes,in).
nmod:poss(2,holes,their).
nmod:in(2,close,holes).
kept(2,mice,themselves_close_in_their_holes).
kept(2,mice,themselves_close).
root(3,ROOT,able).
det(3,cat,the).
nsubj(3,able,cat).
nsubj:xsubj(3,get,cat).
nsubj(3,perceived,cat).
cop(3,able,was).
neg(3,longer,no).
advmod(3,able,longer).
mark(3,get,to).
xcomp(3,able,get).
case(3,them,at).
nmod:at(3,get,them).
cc(3,able,and).
conj:and(3,able,perceived).
mark(3,tempt,that).
nsubj(3,tempt,she).
aux(3,tempt,must).
ccomp(3,perceived,tempt).
dobj(3,tempt,them).
advmod(3,tempt,forth).
case(3,device,by).
det(3,device,some).
nmod:by(3,forth,device).
tempt(3,she,them).
was(3,cat,able).
tempt_forth(3,she,them).
get_at(3,cat,them).
root(4,ROOT,jumped).
case(4,purpose,for).
det(4,purpose,this).
nmod:for(4,jumped,purpose).
nsubj(4,jumped,she).
mark(4,peg,upon).
nsubj(4,peg,a).
advcl:upon(4,jumped,peg).
cc(4,peg,and).
csubj(4,pretended,suspending).
dobj(4,suspending,herself).
case(4,it,from).
nmod:from(4,suspending,it).
advcl:upon(4,jumped,pretended).
conj:and(4,peg,pretended).
mark(4,dead,to).
cop(4,dead,be).
xcomp(4,pretended,dead).
jumped_for(4,she,purpose).
jumped(4,she,peg).
root(5,ROOT,saw).
det:qmod(5,mice,one).
mwe(5,one,of).
det(5,mice,the).
nsubj(5,saw,mice).
nsubj(5,said,mice).
acl(5,mice,peeping).
advmod(5,peeping,stealthily).
advmod(5,saw,out).
dobj(5,saw,her).
cc(5,saw,and).
conj:and(5,saw,said).
root(6,ROOT,ah).
nmod:poss(6,madam,my).
amod(6,madam,good).
dobj(6,ah,madam).
advmod(6,turn,even).
mark(6,turn,though).
nsubj(6,turn,you).
aux(6,turn,should).
advcl:though(6,ah,turn).
case(6,meal-bag,into).
det(6,meal-bag,a).
nmod:into(6,turn,meal-bag).
nsubj(6,come,we).
aux(6,come,will).
neg(6,come,not).
acl:relcl(6,meal-bag,come).
case(6,you,near).
nmod:near(6,come,you).
