root(0,ROOT,went).
det(0,bowman,a).
advmod(0,bowman,very).
amod(0,bowman,skillful).
nsubj(0,went,bowman).
case(0,mountains,to).
det(0,mountains,the).
nmod:to(0,went,mountains).
case(0,search,in).
nmod:in(0,mountains,search).
case(0,game,of).
nmod:of(0,search,game).
cc(0,fled,but).
det:predet(0,beasts,all).
det(0,beasts,the).
nsubj(0,fled,beasts).
case(0,forest,of).
det(0,forest,the).
nmod:of(0,beasts,forest).
ccomp(0,went,fled).
case(0,approach,at).
nmod:poss(0,approach,his).
nmod:at(0,fled,approach).
is_in(0,mountains,search_of_game).
went_to(0,skillful_bowman,mountains_in_search).
went_to(0,bowman,mountains_in_search_of_game).
went_to(0,skillful_bowman,mountains).
went_to(0,bowman,mountains_in_search).
went_to(0,skillful_bowman,mountains_in_search_of_game).
went_to(0,bowman,mountains).
root(1,ROOT,challenged).
det(1,lion,the).
nsubj(1,challenged,lion).
advmod(1,challenged,alone).
dobj(1,challenged,him).
nsubj:xsubj(1,combat,him).
mark(1,combat,to).
xcomp(1,challenged,combat).
alone_challenged(1,lion,him).
challenged(1,lion,him).
root(2,ROOT,shot).
det(2,bowman,the).
nsubj(2,shot,bowman).
nsubj(2,said,bowman).
advmod(2,shot,immediately).
compound:prt(2,shot,out).
det(2,arrow,an).
dobj(2,shot,arrow).
cc(2,shot,and).
conj:and(2,shot,said).
case(2,lion,to).
det(2,lion,the).
nmod:to(2,said,lion).
said_to(2,bowman,lion).
shot_out(2,bowman,arrow).
immediately_shot_out(2,bowman,arrow).
root(3,ROOT,send).
dep(3,send,i).
dobj(3,send,thee).
nmod:poss(3,messenger,my).
nsubj(3,send,messenger).
mark(3,learn,that).
case(3,him,from).
nmod:from(3,learn,him).
nsubj(3,learn,thou).
advmod(3,learn,mayest).
dep(3,send,learn).
dobj(3,be,what).
nsubj(3,be,i).
nmod:npmod(3,i,myself).
aux(3,be,shall).
ccomp(3,learn,be).
advmod(3,assail,when).
compound(3,assail,i).
advcl(3,be,assail).
dep(3,assail,thee).
send(3,my_messenger,thee).
root(4,ROOT,rushed).
det(4,lion,the).
amod(4,lion,wounded).
nsubj(4,rushed,lion).
advmod(4,rushed,away).
case(4,fear,in).
amod(4,fear,great).
nmod:in(4,rushed,fear).
cc(4,rushed,and).
advmod(4,told,when).
det(4,fox,a).
nsubj(4,seen,fox).
nsubj(4,told,fox).
ref(4,fox,who).
aux(4,seen,had).
acl:relcl(4,fox,seen).
nsubj(4,happen,it).
advmod(4,happen,all).
ccomp(4,seen,happen).
conj:and(4,rushed,told).
dobj(4,told,him).
nsubj:xsubj(4,courage,him).
mark(4,courage,to).
cop(4,courage,be).
case(4,courage,of).
amod(4,courage,good).
xcomp(4,told,courage).
cc(4,courage,and).
xcomp(4,told,not).
conj:and(4,courage,not).
mark(4,back,to).
dep(4,courage,back).
compound:prt(4,back,off).
case(4,attack,at).
det(4,attack,the).
amod(4,attack,first).
nmod:at(4,back,attack).
nsubj(4,replied,he).
acl:relcl(4,attack,replied).
be_of(4,him,good_courage).
be_of(4,him,courage).
root(5,ROOT,counsel).
dep(5,counsel,you).
dep(5,counsel,me).
case(5,vain,in).
nmod:in(5,me,vain).
root(6,ROOT,abide).
mark(6,abide,for).
mark(6,sends,if).
nsubj(6,sends,he).
advcl:if(6,abide,sends).
advmod(6,fearful,so).
amod(6,messenger,fearful).
det(6,messenger,a).
dobj(6,sends,messenger).
advmod(6,shall,how).
dep(6,sends,shall).
nsubj(6,abide,i).
det(6,attack,the).
nsubj(6,himself,attack).
case(6,man,of).
det(6,man,the).
nmod:of(6,attack,man).
xcomp(6,abide,himself).
sends(6,he,messenger).
sends(6,he,so_fearful_messenger).
sends(6,he,fearful_messenger).
abide(6,i,attack_of_man_himself).
abide(6,i,attack_himself).
