root(0,ROOT,hid).
det(0,bull,a).
nsubj(0,hid,bull).
acl(0,bull,escaping).
case(0,lion,from).
det(0,lion,a).
nmod:from(0,escaping,lion).
case(0,cave,in).
det(0,cave,a).
nmod:in(0,hid,cave).
dobj(0,occupied,which).
det(0,shepherds,some).
nsubj(0,had,shepherds).
ccomp(0,hid,had).
advmod(0,occupied,recently).
xcomp(0,had,occupied).
hid_in(0,bull,cave).
escaping_from(0,bull,lion).
root(1,ROOT,soon).
advmod(1,soon,as).
mark(1,entered,as).
nsubj(1,entered,he).
dep(1,soon,entered).
det(1,left,a).
amod(1,left,he-goat).
nsubj(1,attacked,left).
case(1,cave,in).
det(1,cave,the).
nmod:in(1,left,cave).
advmod(1,attacked,sharply).
ccomp(1,entered,attacked).
dobj(1,attacked,him).
case(1,horns,with).
nmod:poss(1,horns,his).
nmod:with(1,attacked,horns).
left_in(1,him,cave).
sharply_attacked(1,he-goat_left,him).
sharply_attacked(1,left,him).
is_in(1,he-goat_left,cave).
attacked(1,left,him).
attacked(1,he-goat_left,him).
he-goat_left_in(1,him,cave).
root(2,ROOT,addressed).
det(2,bull,the).
nsubj(2,addressed,bull).
advmod(2,addressed,quietly).
dobj(2,addressed,him).
addressed(2,bull,him).
quietly_addressed(2,bull,him).
root(3,ROOT,butt).
advmod(3,as,away).
advmod(3,much,as).
dep(3,butt,much).
mark(3,will,as).
nsubj(3,will,you).
dep(3,much,will).
root(4,ROOT,have).
nsubj(4,have,i).
neg(4,fear,no).
dobj(4,have,fear).
dobj(4,have,fear).
conj:but(4,fear,fear).
case(4,you,of).
nmod:of(4,fear,you).
cc(4,fear,but).
case(4,lion,of).
det(4,lion,the).
nmod:of(4,fear,lion).
root(5,ROOT,let).
det(5,monster,that).
nsubj(5,go,monster).
xcomp(5,let,go).
advmod(5,go,away).
cc(5,go,and).
nsubj(5,let,i).
aux(5,let,will).
advmod(5,let,soon).
xcomp(5,let,let).
conj:and(5,go,let).
nsubj(5,know,you).
ccomp(5,let,know).
nsubj(5,strength,what).
cop(5,strength,is).
det(5,strength,the).
amod(5,strength,respective).
ccomp(5,know,strength).
case(5,goat,of).
det(5,goat,a).
nmod:of(5,strength,goat).
cc(5,goat,and).
det(5,bull,a).
nmod:of(5,strength,bull).
conj:and(5,goat,bull).
root(6,ROOT,distress).
