root(0,ROOT,fell).
det(0,cat,a).
nsubj(0,fell,cat).
nsubj:xsubj(0,change,cat).
case(0,love,in).
nmod:in(0,fell,love).
case(0,man,with).
det(0,man,a).
amod(0,man,handsome).
amod(0,man,young).
nmod:with(0,fell,man).
cc(0,man,and).
amod(0,venus,entreated).
nmod:with(0,fell,venus).
conj:and(0,man,venus).
mark(0,change,to).
xcomp(0,fell,change).
dobj(0,change,her).
case(0,form,into).
det(0,form,the).
nmod:into(0,change,form).
case(0,woman,of).
det(0,woman,a).
nmod:of(0,form,woman).
change(0,cat,her).
fell_in(0,cat,love).
fell_with(0,cat,man).
fell_with(0,cat,young_man).
fell_with(0,cat,handsome_man).
fell_with(0,cat,handsome_young_man).
root(1,ROOT,consented).
nsubj(1,consented,venus).
nsubj(1,transformed,venus).
case(1,request,to).
nmod:poss(1,request,her).
nmod:to(1,consented,request).
cc(1,consented,and).
conj:and(1,consented,transformed).
dobj(1,transformed,her).
case(1,damsel,into).
det(1,damsel,a).
amod(1,damsel,beautiful).
nmod:into(1,transformed,damsel).
mark(1,saw,so).
mwe(1,so,that).
det(1,youth,the).
nsubj(1,saw,youth).
nsubj(1,loved,youth).
advcl:so_that(1,transformed,saw).
dobj(1,saw,her).
cc(1,saw,and).
advcl:so_that(1,transformed,loved).
conj:and(1,saw,loved).
dobj(1,loved,her).
cc(1,loved,and).
conj:and(1,saw,took).
conj:and(1,loved,took).
nmod:poss(1,home,her).
dobj(1,took,home).
case(1,bride,as).
nmod:poss(1,bride,his).
nmod:as(1,took,bride).
saw(1,youth,her).
consented_to(1,venus,her_request).
transformed(1,venus,her).
took(1,her,her_home).
loved(1,youth,her).
root(2,ROOT,reclining).
mark(2,reclining,while).
det(2,two,the).
nsubj(2,reclining,two).
aux(2,reclining,were).
case(2,venus,in).
nmod:poss(2,venus,their).
compound(2,venus,chamber).
nmod:in(2,reclining,venus).
acl(2,venus,wishing).
mark(2,discover,to).
xcomp(2,wishing,discover).
mark(2,altered,if).
det(2,cat,the).
nsubj(2,altered,cat).
case(2,change,in).
nmod:poss(2,change,her).
nmod:in(2,cat,change).
case(2,shape,of).
nmod:of(2,change,shape).
aux(2,altered,had).
advmod(2,altered,also).
advcl:if(2,discover,altered).
nmod:poss(2,habits,her).
nsubj(2,let,habits).
case(2,life,of).
nmod:of(2,habits,life).
ccomp(2,altered,let).
compound:prt(2,let,down).
det(2,mouse,a).
dobj(2,let,mouse).
case(2,middle,in).
det(2,middle,the).
nmod:in(2,mouse,middle).
case(2,room,of).
det(2,room,the).
nmod:of(2,middle,room).
let_down(2,her_habits,mouse_in_middle).
mouse_in(2,her_habits,middle_of_room).
mouse_in(2,her_habits,middle).
is_in(2,mouse,middle_of_room).
let_down(2,her_habits,mouse_in_middle_of_room).
is_in(2,cat,her_change_of_shape).
were_reclining_in(2,two,their_chamber_venus).
were_reclining_in(2,two,their_chamber_venus_wishing).
let_down(2,her_habits,mouse).
root(3,ROOT,started).
det(3,cat,the).
nsubj(3,started,cat).
nsubj(3,pursued,cat).
advmod(3,forgetting,quite).
acl(3,cat,forgetting).
nmod:poss(3,condition,her).
amod(3,condition,present).
dobj(3,forgetting,condition).
compound:prt(3,started,up).
case(3,couch,from).
det(3,couch,the).
nmod:from(3,started,couch).
cc(3,started,and).
conj:and(3,started,pursued).
det(3,mouse,the).
dobj(3,pursued,mouse).
acl(3,mouse,wishing).
mark(3,eat,to).
xcomp(3,wishing,eat).
dobj(3,eat,it).
forgetting(3,cat,her_condition).
pursued(3,cat,mouse).
pursued(3,cat,mouse_wishing).
quite_forgetting(3,cat,her_present_condition).
quite_forgetting(3,cat,her_condition).
forgetting(3,cat,her_present_condition).
started_up_from(3,cat,couch).
root(4,ROOT,disappointed).
nsubj(4,disappointed,venus).
nsubj(4,caused,venus).
cop(4,disappointed,was).
advmod(4,disappointed,much).
cc(4,disappointed,and).
advmod(4,caused,again).
conj:and(4,disappointed,caused).
dobj(4,caused,her).
nsubj:xsubj(4,return,her).
mark(4,return,to).
xcomp(4,caused,return).
case(4,shape,to).
nmod:poss(4,shape,her).
amod(4,shape,former).
nmod:to(4,return,shape).
caused(4,venus,her).
was(4,venus,disappointed).
was(4,venus,much_disappointed).
again_caused(4,venus,her).
return_to(4,her,her_former_shape).
