%% one fine day it occurred to the members of the body that they were doing all the work and the belly was having all the food.
% dependencies.
root(0,root,have).
nummod(0,day,one).
amod(0,day,fine).
mark(0,do,day).
nsubj(0,have,day).
nsubj(0,occur,it).
acl:relcl(0,day,occur).
case(0,member,to).
det(0,member,the).
nmod:to(0,occur,member).
case(0,body,of).
det(0,body,the).
nmod:of(0,member,body).
ref(0,day,that).
nsubj(0,do,they).
aux(0,do,be).
ccomp(0,occur,do).
dep(0,work,all).
det(0,work,the).
dobj(0,do,work).
cc(0,work,and).
det(0,belly,the).
dobj(0,do,belly).
conj:and(0,work,belly).
aux(0,have,be).
det:predet(0,food,all).
det(0,food,the).
dobj(0,have,food).
% relations.
%% so they held a meeting and after a long discussion decided to strike work till the belly consented to take its proper share of the work.
% dependencies.
root(1,root,hold).
mark(1,hold,so).
nsubj(1,hold,they).
det(1,meeting,a).
dobj(1,hold,meeting).
cc(1,hold,and).
mark(1,decide,after).
det(1,discussion,a).
amod(1,discussion,long).
nsubj(1,decide,discussion).
nsubj:xsubj(1,strike,discussion).
conj:and(1,hold,decide).
mark(1,strike,to).
xcomp(1,decide,strike).
dobj(1,strike,work).
mark(1,consent,till).
det(1,belly,the).
nsubj(1,consent,belly).
nsubj:xsubj(1,take,belly).
advcl:till(1,strike,consent).
mark(1,take,to).
xcomp(1,consent,take).
nmod:poss(1,share,its).
amod(1,share,proper).
dobj(1,take,share).
case(1,work,of).
det(1,work,the).
nmod:of(1,share,work).
% relations.
aos(1,take,belly,its_share).
aos(1,take,belly,its_share_of_work).
aos(1,strike,long_discussion,work).
aos(1,take,belly,its_proper_share_of_work).
aos(1,hold,they,meeting).
aos(1,strike_work,discussion,belly_consent).
aos(1,take,belly,its_proper_share).
aos(1,strike,discussion,work).
aos(1,strike_work,long_discussion,belly_consent).
%% so for a day or two the hands refused to take the food the mouth refused to receive it and the teeth had no work to do.
% dependencies.
root(2,root,so).
mark(2,refuse,for).
det(2,day,a).
dep(2,refuse,day).
cc(2,day,or).
conj:or(2,day,two).
dep(2,refuse,two).
det(2,hand,the).
nsubj(2,refuse,hand).
nsubj:xsubj(2,take,hand).
dep(2,so,refuse).
mark(2,take,to).
xcomp(2,refuse,take).
det(2,food,the).
dobj(2,take,food).
det(2,mouth,the).
nsubj(2,refuse,mouth).
nsubj:xsubj(2,receive,mouth).
acl:relcl(2,food,refuse).
mark(2,receive,to).
xcomp(2,refuse,receive).
dobj(2,receive,it).
cc(2,refuse,and).
det(2,tooth,the).
nsubj(2,have,tooth).
dep(2,so,have).
conj:and(2,refuse,have).
neg(2,work,no).
dobj(2,have,work).
mark(2,do,to).
acl:to(2,work,do).
% relations.
aos(2,receive,mouth,it).
%% but after a day or two the members began to find that they themselves were not in a very active condition the hands could hardly move and the mouth was all parched and dry while the legs were unable to support the rest.
% dependencies.
root(3,root,begin).
cc(3,begin,but).
mark(3,begin,after).
det(3,day,a).
dep(3,begin,day).
cc(3,day,or).
conj:or(3,day,two).
dep(3,begin,two).
det(3,member,the).
nsubj(3,begin,member).
nsubj:xsubj(3,find,member).
mark(3,find,to).
xcomp(3,begin,find).
mark(3,condition,that).
nsubj(3,condition,they).
advmod(3,condition,themselves).
cop(3,condition,be).
neg(3,condition,not).
case(3,condition,in).
det(3,condition,a).
advmod(3,active,very).
amod(3,condition,active).
ccomp(3,find,condition).
det(3,hand,the).
nsubj(3,move,hand).
aux(3,move,could).
advmod(3,move,hardly).
acl:relcl(3,condition,move).
cc(3,begin,and).
det(3,mouth,the).
nsubj(3,parched,mouth).
nsubj(3,dry,mouth).
cop(3,parched,be).
dep(3,parched,all).
conj:and(3,begin,parched).
cc(3,parched,and).
conj:and(3,begin,dry).
conj:and(3,parched,dry).
mark(3,unable,while).
det(3,leg,the).
nsubj(3,unable,leg).
nsubj:xsubj(3,support,leg).
cop(3,unable,be).
advcl:while(3,parched,unable).
mark(3,support,to).
xcomp(3,unable,support).
det(3,rest,the).
dobj(3,support,rest).
% relations.
aos(3,support,leg,rest).
aos(3,be,leg,unable).
aos(3,be_parched,mouth,unable).
aos(3,be,mouth,parched).
%% so thus they found that even the belly in its dull quiet way was doing necessary work for the body and that all must work together or the body will go to pieces.
% dependencies.
root(4,root,so).
advmod(4,find,thus).
nsubj(4,find,they).
ccomp(4,so,find).
mark(4,do,that).
advmod(4,belly,even).
det(4,belly,the).
nsubj(4,do,belly).
case(4,way,in).
nmod:poss(4,way,its).
amod(4,way,dull).
amod(4,way,quiet).
nmod:in(4,belly,way).
aux(4,do,be).
ccomp(4,find,do).
amod(4,work,necessary).
dobj(4,do,work).
case(4,body,for).
det(4,body,the).
nmod:for(4,do,body).
cc(4,do,and).
mark(4,work,that).
nsubj(4,work,all).
aux(4,work,must).
ccomp(4,find,work).
conj:and(4,do,work).
advmod(4,work,together).
cc(4,find,or).
det(4,body,the).
nsubj(4,go,body).
aux(4,go,will).
ccomp(4,so,go).
conj:or(4,find,go).
case(4,piece,to).
nmod:to(4,go,piece).
% relations.
aos(4,is_in,belly,its_dull_quiet_way).
aos(4,even_belly_in,work,its_dull_quiet_way).
aos(4,belly_in,work,its_quiet_way).
aos(4,do,belly,work).
aos(4,belly_in,work,its_way).
aos(4,do_work_for,belly,body).
aos(4,belly_in,necessary_work,its_dull_quiet_way).
aos(4,belly_in,necessary_work,its_way).
aos(4,belly_in,necessary_work,its_dull_way).
aos(4,even_belly_in,necessary_work,its_dull_way).
aos(4,belly_in,work,its_dull_way).
aos(4,even_belly_in,necessary_work,its_quiet_way).
aos(4,even_belly_in,necessary_work,its_dull_quiet_way).
aos(4,even_belly_in,work,its_quiet_way).
aos(4,do,belly,necessary_work).
aos(4,even_belly_in,necessary_work,its_way).
aos(4,will_go_to,body,piece).
aos(4,even_belly_in,work,its_way).
aos(4,even_belly_in,work,its_dull_way).
aos(4,belly_in,work,its_dull_quiet_way).
aos(4,belly_in,necessary_work,its_quiet_way).
