root(0,ROOT,ready).
det(0,bitch,a).
dep(0,ready,bitch).
mark(0,whelp,to).
xcomp(0,ready,whelp).
advmod(0,begged,earnestly).
dep(0,whelp,begged).
det(0,shepherd,a).
dobj(0,begged,shepherd).
case(0,place,for).
det(0,place,a).
nmod:for(0,begged,place).
advmod(0,litter,where).
nsubj(0,litter,she).
aux(0,litter,might).
advcl(0,begged,litter).
root(1,ROOT,granted).
advmod(1,granted,when).
nmod:poss(1,request,her).
nsubjpass(1,granted,request).
auxpass(1,granted,was).
iobj(1,granted,she).
amod(1,permission,besought).
dobj(1,granted,permission).
case(1,puppies,to).
amod(1,puppies,rear).
nmod:poss(1,puppies,her).
nmod:to(1,granted,puppies).
case(1,spot,in).
det(1,spot,the).
amod(1,spot,same).
nmod:in(1,puppies,spot).
was_granted_permission_to(1,her_request,rear_her_puppies).
is_in(1,rear_her_puppies,same_spot).
was_granted_permission_to(1,her_request,her_puppies).
was_granted_permission_to(1,her_request,her_puppies_in_same_spot).
was_granted_permission_to(1,her_request,her_puppies_in_spot).
was_granted_permission_to(1,her_request,rear_her_puppies_in_same_spot).
was_granted_permission_to(1,her_request,rear_her_puppies_in_spot).
was_granted(1,her_request,she).
was_granted(1,her_request,besought_permission).
was_granted(1,her_request,permission).
root(2,ROOT,consented).
det(2,shepherd,the).
nsubj(2,consented,shepherd).
advmod(2,consented,again).
root(3,ROOT,but).
case(3,bitch,at).
amod(3,bitch,last).
det(3,bitch,the).
nmod:at(3,but,bitch).
acl(3,bitch,protected).
case(3,bodyguard,by).
det(3,bodyguard,the).
nmod:by(3,protected,bodyguard).
nsubj(3,grown,bodyguard).
nsubj(3,able,bodyguard).
nsubj:xsubj(3,defend,bodyguard).
case(3,whelps,of).
nmod:poss(3,whelps,her).
nmod:of(3,bodyguard,whelps).
ref(3,bodyguard,who).
aux(3,grown,had).
advmod(3,grown,now).
acl:relcl(3,bodyguard,grown).
advmod(3,grown,up).
cc(3,grown,and).
cop(3,able,were).
acl:relcl(3,bodyguard,able).
conj:and(3,grown,able).
mark(3,defend,to).
xcomp(3,able,defend).
nsubj(3,asserted,themselves).
nsubj(3,permit,themselves).
ccomp(3,defend,asserted).
nmod:poss(3,right,her).
amod(3,right,exclusive).
dobj(3,asserted,right).
case(3,place,to).
det(3,place,the).
nmod:to(3,asserted,place).
cc(3,asserted,and).
aux(3,permit,would).
neg(3,permit,not).
ccomp(3,defend,permit).
conj:and(3,asserted,permit).
det(3,shepherd,the).
dobj(3,permit,shepherd).
case(3,approach,to).
nmod:to(3,permit,approach).
