root(0,ROOT,having).
nummod(0,day,one).
amod(0,day,fine).
mark(0,doing,day).
nsubj(0,having,day).
nsubj(0,occurred,it).
acl:relcl(0,day,occurred).
case(0,members,to).
det(0,members,the).
nmod:to(0,occurred,members).
case(0,body,of).
det(0,body,the).
nmod:of(0,members,body).
ref(0,day,that).
nsubj(0,doing,they).
aux(0,doing,were).
ccomp(0,occurred,doing).
dep(0,work,all).
det(0,work,the).
dobj(0,doing,work).
cc(0,work,and).
det(0,belly,the).
dobj(0,doing,belly).
conj:and(0,work,belly).
aux(0,having,was).
det:predet(0,food,all).
det(0,food,the).
dobj(0,having,food).
root(1,ROOT,held).
mark(1,held,so).
nsubj(1,held,they).
det(1,meeting,a).
dobj(1,held,meeting).
cc(1,held,and).
mark(1,decided,after).
det(1,discussion,a).
amod(1,discussion,long).
nsubj(1,decided,discussion).
nsubj:xsubj(1,strike,discussion).
conj:and(1,held,decided).
mark(1,strike,to).
xcomp(1,decided,strike).
dobj(1,strike,work).
mark(1,consented,till).
det(1,belly,the).
nsubj(1,consented,belly).
nsubj:xsubj(1,take,belly).
advcl:till(1,strike,consented).
mark(1,take,to).
xcomp(1,consented,take).
nmod:poss(1,share,its).
amod(1,share,proper).
dobj(1,take,share).
case(1,work,of).
det(1,work,the).
nmod:of(1,share,work).
take(1,belly,its_share).
take(1,belly,its_share_of_work).
strike(1,long_discussion,work).
take(1,belly,its_proper_share_of_work).
held(1,they,meeting).
strike_work(1,discussion,belly_consented).
take(1,belly,its_proper_share).
strike(1,discussion,work).
strike_work(1,long_discussion,belly_consented).
root(2,ROOT,so).
mark(2,refused,for).
det(2,day,a).
dep(2,refused,day).
cc(2,day,or).
conj:or(2,day,two).
dep(2,refused,two).
det(2,hands,the).
nsubj(2,refused,hands).
nsubj:xsubj(2,take,hands).
dep(2,so,refused).
mark(2,take,to).
xcomp(2,refused,take).
det(2,food,the).
dobj(2,take,food).
det(2,mouth,the).
nsubj(2,refused,mouth).
nsubj:xsubj(2,receive,mouth).
acl:relcl(2,food,refused).
mark(2,receive,to).
xcomp(2,refused,receive).
dobj(2,receive,it).
cc(2,refused,and).
det(2,teeth,the).
nsubj(2,had,teeth).
dep(2,so,had).
conj:and(2,refused,had).
neg(2,work,no).
dobj(2,had,work).
mark(2,do,to).
acl:to(2,work,do).
receive(2,mouth,it).
root(3,ROOT,began).
cc(3,began,but).
mark(3,began,after).
det(3,day,a).
dep(3,began,day).
cc(3,day,or).
conj:or(3,day,two).
dep(3,began,two).
det(3,members,the).
nsubj(3,began,members).
nsubj:xsubj(3,find,members).
mark(3,find,to).
xcomp(3,began,find).
mark(3,condition,that).
nsubj(3,condition,they).
advmod(3,condition,themselves).
cop(3,condition,were).
neg(3,condition,not).
case(3,condition,in).
det(3,condition,a).
advmod(3,active,very).
amod(3,condition,active).
ccomp(3,find,condition).
det(3,hands,the).
nsubj(3,move,hands).
aux(3,move,could).
advmod(3,move,hardly).
acl:relcl(3,condition,move).
cc(3,began,and).
det(3,mouth,the).
nsubj(3,parched,mouth).
nsubj(3,dry,mouth).
cop(3,parched,was).
dep(3,parched,all).
conj:and(3,began,parched).
cc(3,parched,and).
conj:and(3,began,dry).
conj:and(3,parched,dry).
mark(3,unable,while).
det(3,legs,the).
nsubj(3,unable,legs).
nsubj:xsubj(3,support,legs).
cop(3,unable,were).
advcl:while(3,parched,unable).
mark(3,support,to).
xcomp(3,unable,support).
det(3,rest,the).
dobj(3,support,rest).
support(3,legs,rest).
were(3,legs,unable).
was_parched(3,mouth,unable).
was(3,mouth,parched).
root(4,ROOT,so).
advmod(4,found,thus).
nsubj(4,found,they).
ccomp(4,so,found).
mark(4,doing,that).
advmod(4,belly,even).
det(4,belly,the).
nsubj(4,doing,belly).
case(4,way,in).
nmod:poss(4,way,its).
amod(4,way,dull).
amod(4,way,quiet).
nmod:in(4,belly,way).
aux(4,doing,was).
ccomp(4,found,doing).
amod(4,work,necessary).
dobj(4,doing,work).
case(4,body,for).
det(4,body,the).
nmod:for(4,doing,body).
cc(4,doing,and).
mark(4,work,that).
nsubj(4,work,all).
aux(4,work,must).
ccomp(4,found,work).
conj:and(4,doing,work).
advmod(4,work,together).
cc(4,found,or).
det(4,body,the).
nsubj(4,go,body).
aux(4,go,will).
ccomp(4,so,go).
conj:or(4,found,go).
case(4,pieces,to).
nmod:to(4,go,pieces).
is_in(4,belly,its_dull_quiet_way).
even_belly_in(4,work,its_dull_quiet_way).
belly_in(4,work,its_quiet_way).
doing(4,belly,work).
belly_in(4,work,its_way).
doing_work_for(4,belly,body).
belly_in(4,necessary_work,its_dull_quiet_way).
belly_in(4,necessary_work,its_way).
belly_in(4,necessary_work,its_dull_way).
even_belly_in(4,necessary_work,its_dull_way).
belly_in(4,work,its_dull_way).
even_belly_in(4,necessary_work,its_quiet_way).
even_belly_in(4,necessary_work,its_dull_quiet_way).
even_belly_in(4,work,its_quiet_way).
doing(4,belly,necessary_work).
even_belly_in(4,necessary_work,its_way).
will_go_to(4,body,pieces).
even_belly_in(4,work,its_way).
even_belly_in(4,work,its_dull_way).
belly_in(4,work,its_dull_quiet_way).
belly_in(4,necessary_work,its_quiet_way).
