root(0,ROOT,camel).
det(0,camel,the).
advmod(0,saw,when).
nsubj(0,saw,man).
advmod(0,saw,first).
dep(0,camel,saw).
det(0,camel,the).
dobj(0,saw,camel).
mark(0,ran,camel).
nsubj(0,frightened,he).
cop(0,frightened,was).
advmod(0,frightened,so).
acl:relcl(0,camel,frightened).
case(0,size,at).
nmod:poss(0,size,his).
amod(0,size,vast).
nmod:at(0,frightened,size).
ref(0,camel,that).
nsubj(0,ran,he).
ccomp(0,frightened,ran).
advmod(0,ran,away).
was(0,he,frightened).
was_so_frightened_at(0,he,his_vast_size).
was(0,he,so_frightened).
was_frightened_at(0,he,his_size).
was_so_frightened_at(0,he,his_size).
was_frightened_at(0,he,his_vast_size).
root(1,ROOT,time).
case(1,time,after).
det(1,time,a).
acl(1,time,perceiving).
det(1,meekness,the).
dobj(1,perceiving,meekness).
cc(1,meekness,and).
dobj(1,perceiving,gentleness).
conj:and(1,meekness,gentleness).
case(1,temper,of).
det(1,beast,the).
nmod:poss(1,temper,beast).
case(1,beast,'s).
nmod:of(1,meekness,temper).
nsubj(1,summoned,he).
acl:relcl(1,meekness,summoned).
dobj(1,summoned,courage).
advmod(1,summoned,enough).
mark(1,approach,to).
dep(1,enough,approach).
dobj(1,approach,him).
of(1,beast,temper).
perceiving(1,time,gentleness).
summoned_enough(1,he,courage).
summoned(1,he,courage).
root(2,ROOT,observing).
advmod(2,observing,soon).
advmod(2,observing,afterwards).
mark(2,animal,that).
nsubj(2,animal,he).
cop(2,animal,was).
det(2,animal,an).
ccomp(2,observing,animal).
advmod(2,deficient,altogether).
amod(2,animal,deficient).
case(2,spirit,in).
nmod:in(2,deficient,spirit).
nsubj(2,assumed,he).
acl:relcl(2,animal,assumed).
amod(2,boldness,such).
dobj(2,assumed,boldness).
case(2,put,as).
mark(2,put,to).
nmod:as(2,assumed,put).
det(2,bridle,a).
dobj(2,put,bridle).
case(2,mouth,in).
nmod:poss(2,mouth,his).
nmod:in(2,bridle,mouth).
cc(2,put,and).
mark(2,let,to).
nmod:as(2,assumed,let).
conj:and(2,put,let).
det(2,drive,a).
compound(2,drive,child).
nsubj(2,him,drive).
xcomp(2,let,him).
is_in(2,bridle,his_mouth).
was(2,he,deficient).
assumed(2,he,boldness).
assumed(2,he,such_boldness).
let(2,bridle,child_drive_him).
