root(0,ROOT,lay).
det(0,stag,the).
amod(0,stag,sick).
nsubj(0,lay,stag).
det(0,stag,a).
amod(0,stag,sick).
dep(0,stag,stag).
compound:prt(0,lay,down).
case(0,corner,in).
det(0,corner,a).
amod(0,corner,quiet).
nmod:in(0,lay,corner).
case(0,pasture-ground,of).
nmod:poss(0,pasture-ground,its).
nmod:of(0,corner,pasture-ground).
lay_down_in(0,stag,corner_of_its_pasture-ground).
lay_down_in(0,sick_stag,corner_of_its_pasture-ground).
lay_down_in(0,sick_stag,quiet_corner_of_its_pasture-ground).
lay_down_in(0,stag,corner).
lay_down_in(0,stag,quiet_corner_of_its_pasture-ground).
lay_down_in(0,sick_stag,quiet_corner).
lay_down_in(0,sick_stag,corner).
lay_down_in(0,stag,quiet_corner).
root(1,ROOT,came).
nmod:poss(1,companions,his).
nsubj(1,came,companions).
nsubj:xsubj(1,inquire,companions).
case(1,numbers,in).
amod(1,numbers,great).
nmod:in(1,came,numbers).
mark(1,inquire,to).
xcomp(1,came,inquire).
mark(1,helped,after).
nmod:poss(1,health,his).
nsubj(1,helped,health).
cc(1,health,and).
det(1,one,each).
conj:and(1,health,one).
nsubj(1,helped,one).
advcl:after(1,inquire,helped).
dobj(1,helped,himself).
case(1,share,to).
det(1,share,a).
nmod:to(1,helped,share).
case(1,food,of).
det(1,food,the).
nmod:of(1,share,food).
nsubjpass(1,placed,food).
ref(1,food,which).
aux(1,placed,had).
auxpass(1,placed,been).
acl:relcl(1,food,placed).
case(1,use,for).
nmod:poss(1,use,his).
nmod:for(1,placed,use).
came_in(1,his_companions,numbers).
came_in(1,his_companions,great_numbers).
came(1,his_companions,inquire).
root(2,ROOT,so).
mark(2,died,that).
nsubj(2,died,he).
nsubj(2,died,he).
dep(2,so,died).
dep(2,so,died).
conj:but(2,died,died).
neg(2,sickness,not).
case(2,sickness,from).
nmod:poss(2,sickness,his).
nmod:from(2,died,sickness).
cc(2,died,but).
case(2,failure,from).
det(2,failure,the).
nmod:from(2,died,failure).
case(2,means,of).
det(2,means,the).
nmod:of(2,failure,means).
case(2,living,of).
nmod:of(2,means,living).
