root(0,ROOT,hired).
det(0,thief,a).
nsubj(0,hired,thief).
nsubj(0,stayed,thief).
det(0,room,a).
dobj(0,hired,room).
case(0,tavern,in).
det(0,tavern,a).
nmod:in(0,hired,tavern).
cc(0,hired,and).
conj:and(0,hired,stayed).
det(0,while,a).
dobj(0,stayed,while).
case(0,hope,in).
det(0,hope,the).
nmod:in(0,stayed,hope).
mark(0,stealing,of).
acl:of(0,hope,stealing).
dobj(0,stealing,something).
nsubj(0,enable,something).
ref(0,something,which).
aux(0,enable,should).
acl:relcl(0,something,enable).
dobj(0,enable,him).
nsubj:xsubj(0,pay,him).
mark(0,pay,to).
xcomp(0,enable,pay).
nmod:poss(0,reckoning,his).
dobj(0,pay,reckoning).
hired(0,thief,room).
hired_room_in(0,thief,tavern).
stayed(0,thief,while).
pay(0,him,his_reckoning).
root(1,ROOT,waited).
advmod(1,waited,when).
nsubj(1,waited,he).
aux(1,waited,had).
det(1,days,some).
nmod:tmod(1,waited,days).
case(1,vain,in).
nmod:in(1,waited,vain).
nsubj(1,saw,he).
acl:relcl(1,vain,saw).
det(1,innkeeper,the).
nsubj(1,dressed,innkeeper).
nsubj(1,sitting,innkeeper).
ccomp(1,saw,dressed).
case(1,coat,in).
det(1,coat,a).
amod(1,coat,new).
cc(1,new,and).
conj:and(1,new,handsome).
amod(1,coat,handsome).
nmod:in(1,dressed,coat).
cc(1,dressed,and).
ccomp(1,saw,sitting).
conj:and(1,dressed,sitting).
case(1,door,before).
nmod:poss(1,door,his).
nmod:before(1,sitting,door).
sitting_before(1,innkeeper,his_door).
dressed_in(1,innkeeper,coat).
dressed_in(1,innkeeper,new_coat).
had_waited_at_time(1,he,days).
root(2,ROOT,sat).
det(2,thief,the).
nsubj(2,sat,thief).
nsubj(2,talked,thief).
compound:prt(2,sat,down).
advmod(2,him,beside).
nmod(2,sat,him).
cc(2,sat,and).
conj:and(2,sat,talked).
case(2,him,with).
nmod:with(2,talked,him).
talked_with(2,thief,him).
root(3,ROOT,began).
mark(3,began,as).
det(3,conversation,the).
nsubj(3,began,conversation).
nsubj(3,began,conversation).
conj:and(3,began,began).
case(3,flag,to).
nmod:to(3,began,flag).
det(3,thief,the).
nsubj(3,yawned,thief).
acl:relcl(3,flag,yawned).
advmod(3,yawned,terribly).
cc(3,began,and).
case(3,time,at).
det(3,time,the).
amod(3,time,same).
nmod:at(3,began,time).
acl(3,time,howled).
case(3,wolf,like).
det(3,wolf,a).
nmod:like(3,howled,wolf).
began_at(3,conversation,same_time_howled).
began_at(3,conversation,time_howled_like_wolf).
began_at(3,conversation,time_howled).
began_at(3,conversation,same_time_howled_like_wolf).
began_at(3,conversation,time).
began_at(3,conversation,same_time).
root(4,ROOT,said).
det(4,innkeeper,the).
nsubj(4,said,innkeeper).
root(5,ROOT,do).
advmod(5,do,why).
nsubj(5,howl,you).
xcomp(5,do,howl).
advmod(5,fearfully,so).
amod(5,howl,fearfully).
root(6,ROOT,').
root(7,ROOT,tell).
nsubj(7,tell,i).
aux(7,tell,will).
dobj(7,tell,you).
will_tell(7,i,you).
root(8,ROOT,said).
det(8,thief,the).
nsubj(8,said,thief).
root(9,ROOT,let).
cc(9,let,but).
advmod(9,let,first).
nsubj(9,ask,me).
ccomp(9,let,ask).
dobj(9,ask,you).
nsubj:xsubj(9,hold,you).
mark(9,hold,to).
xcomp(9,ask,hold).
nmod:poss(9,clothes,my).
nsubj(9,tear,clothes).
cc(9,clothes,or).
conj:or(9,clothes,i).
nsubj(9,tear,i).
aux(9,tear,shall).
ccomp(9,hold,tear).
dobj(9,tear,them).
case(9,pieces,to).
nmod:to(9,tear,pieces).
tear(9,i,them).
tear(9,my_clothes,them).
ask(9,me,you).
root(10,ROOT,know).
nsubj(10,know,i).
neg(10,know,not).
dep(10,know,sir).
advmod(10,got,when).
nsubj(10,got,i).
advcl(10,sir,got).
det(10,habit,this).
dobj(10,got,habit).
case(10,yawning,of).
acl:of(10,habit,yawning).
cc(10,yawning,nor).
mark(10,inflicted,whether).
det(10,attacks,these).
nsubjpass(10,inflicted,attacks).
nsubjpass(10,inflicted,attacks).
case(10,howling,of).
nmod:of(10,attacks,howling).
auxpass(10,inflicted,were).
acl:of(10,habit,inflicted).
conj:nor(10,yawning,inflicted).
conj:nor(10,yawning,inflicted).
conj:or(10,inflicted,inflicted).
case(10,me,on).
nmod:on(10,inflicted,me).
case(10,judgment,as).
det(10,judgment,a).
nmod:as(10,inflicted,judgment).
case(10,crimes,for).
nmod:poss(10,crimes,my).
nmod:for(10,judgment,crimes).
cc(10,inflicted,or).
case(10,cause,for).
det(10,cause,any).
amod(10,cause,other).
nmod:for(10,inflicted,cause).
were(10,attacks,inflicted_on_me_as_judgment_for_other_cause).
were(10,attacks,inflicted_as_judgment_for_other_cause).
were(10,attacks,inflicted_on_me_for_other_cause).
were(10,attacks,inflicted_as_judgment_for_my_crimes_for_other_cause).
were_inflicted_for(10,attacks,other_cause).
were(10,attacks,inflicted_on_me_as_judgment_for_my_crimes_for_other_cause).
got(10,i,habit_of_yawning).
root(11,ROOT,know).
cc(11,know,but).
det(11,i,this).
nsubj(11,know,i).
aux(11,know,do).
dobj(11,know,that).
advmod(11,turn,when).
compound(11,yawn,i).
nsubj(11,turn,yawn).
case(11,time,for).
det(11,time,the).
amod(11,time,third).
nmod:for(11,yawn,time).
dep(11,time,i).
advmod(11,turn,actually).
acl:relcl(11,that,turn).
case(11,men,into).
det(11,men,a).
compound(11,men,wolf).
cc(11,wolf,and).
conj:and(11,wolf,attack).
compound(11,men,attack).
nmod:into(11,turn,men).
actually_turn_into(11,i_yawn,wolf_men).
turn_into(11,i_yawn,wolf_men).
root(12,ROOT,commenced).
case(12,speech,with).
det(12,speech,this).
nmod:with(12,commenced,speech).
nsubj(12,commenced,he).
nsubj(12,howled,he).
det(12,fit,a).
amod(12,fit,second).
dobj(12,commenced,fit).
case(12,yawning,of).
nmod:of(12,fit,yawning).
cc(12,commenced,and).
advmod(12,howled,again).
conj:and(12,commenced,howled).
case(12,wolf,like).
det(12,wolf,a).
nmod:like(12,howled,wolf).
mark(12,had,as).
nsubj(12,had,he).
advcl:as(12,commenced,had).
case(12,first,at).
nmod:at(12,had,first).
again_howled_like(12,he,wolf).
commenced(12,he,second_fit_of_yawning).
howled_like(12,he,wolf).
commenced_fit(12,he,he_had_at_first).
commenced(12,he,fit).
commenced(12,he,second_fit).
commenced_fit(12,he,he_had).
had_at(12,he,first).
commenced(12,he,fit_of_yawning).
commenced_fit_with(12,he,speech).
root(13,ROOT,innkeeper).
det(13,innkeeper,the).
root(14,ROOT,hearing).
nmod:poss(14,tale,his).
dobj(14,hearing,tale).
cc(14,hearing,and).
conj:and(14,hearing,believing).
dobj(14,said,what).
nsubj(14,said,he).
ccomp(14,believing,said).
ccomp(14,said,became).
advmod(14,alarmed,greatly).
xcomp(14,became,alarmed).
cc(14,believing,and).
conj:and(14,hearing,rising).
conj:and(14,believing,rising).
case(14,seat,from).
nmod:poss(14,seat,his).
nmod:from(14,rising,seat).
acl:relcl(14,seat,attempted).
mark(14,run,to).
xcomp(14,attempted,run).
advmod(14,run,away).
root(15,ROOT,laid).
det(15,thief,the).
nsubj(15,laid,thief).
nsubj(15,entreated,thief).
dobj(15,laid,hold).
case(15,coat,of).
nmod:poss(15,coat,his).
nmod:of(15,hold,coat).
cc(15,laid,and).
conj:and(15,laid,entreated).
dobj(15,entreated,him).
nsubj:xsubj(15,stop,him).
mark(15,stop,to).
xcomp(15,entreated,stop).
xcomp(15,stop,saying).
laid(15,thief,hold).
stop(15,him,saying).
entreated(15,thief,him).
laid(15,thief,hold_of_his_coat).
root(16,ROOT,pray).
dep(16,pray,wait).
dobj(16,wait,sir).
cc(16,wait,and).
dep(16,pray,hold).
conj:and(16,wait,hold).
nmod:poss(16,clothes,my).
nsubj(16,tear,clothes).
cc(16,clothes,or).
conj:or(16,clothes,i).
nsubj(16,tear,i).
aux(16,tear,shall).
ccomp(16,hold,tear).
dobj(16,tear,them).
case(16,pieces,to).
nmod:to(16,tear,pieces).
case(16,fury,in).
nmod:poss(16,fury,my).
nmod:in(16,pieces,fury).
advmod(16,turn,when).
nsubj(16,turn,i).
advcl(16,tear,turn).
case(16,wolf,into).
det(16,wolf,a).
nmod:into(16,turn,wolf).
tear(16,i,them).
turn_into(16,i,wolf).
is_in(16,pieces,my_fury).
tear(16,my_clothes,them).
root(17,ROOT,yawned).
case(17,moment,at).
det(17,moment,the).
amod(17,moment,same).
nmod:at(17,yawned,moment).
nsubj(17,yawned,he).
nsubj(17,set,he).
det(17,time,the).
amod(17,time,third).
dobj(17,yawned,time).
cc(17,yawned,and).
conj:and(17,yawned,set).
compound:prt(17,set,up).
det(17,howl,a).
amod(17,howl,terrible).
dobj(17,set,howl).
set_up(17,he,howl).
yawned(17,he,time).
yawned_time_at(17,he,same_moment).
yawned(17,he,third_time).
set_up(17,he,terrible_howl).
yawned_time_at(17,he,moment).
root(18,ROOT,left).
det(18,innkeeper,the).
nsubj(18,left,innkeeper).
nsubj(18,ran,innkeeper).
acl:relcl(18,innkeeper,frightened).
mark(18,attacked,lest).
nsubjpass(18,attacked,he).
aux(18,attacked,should).
auxpass(18,attacked,be).
advcl:lest(18,frightened,attacked).
nmod:poss(18,coat,his).
amod(18,coat,new).
dobj(18,left,coat).
case(18,hand,in).
det(18,thief,the).
nmod:poss(18,hand,thief).
case(18,thief,'s).
nmod:in(18,left,hand).
cc(18,left,and).
conj:and(18,left,ran).
advmod(18,fast,as).
advmod(18,ran,fast).
mark(18,could,as).
nsubj(18,could,he).
advcl:as(18,ran,could).
case(18,inn,into).
det(18,inn,the).
nmod:into(18,could,inn).
case(18,safety,for).
nmod:for(18,inn,safety).
should(18,he,should_attacked).
in(18,thief,hand).
root(19,ROOT,made).
det(19,thief,the).
nsubj(19,made,thief).
nsubj(19,return,thief).
compound:prt(19,made,off).
case(19,coat,with).
det(19,coat,the).
nmod:with(19,made,coat).
cc(19,made,and).
aux(19,return,did).
neg(19,return,not).
conj:and(19,made,return).
advmod(19,return,again).
case(19,inn,to).
det(19,inn,the).
nmod:to(19,return,inn).
