root(0,ROOT,sobbed).
det(0,hare,a).
nsubj(0,sobbed,hare).
nsubj(0,uttered,hare).
acl(0,hare,pounced).
case(0,eagle,upon).
case(0,eagle,by).
det(0,eagle,an).
nmod:by(0,pounced,eagle).
advmod(0,much,very).
xcomp(0,sobbed,much).
cc(0,sobbed,and).
conj:and(0,sobbed,uttered).
dep(0,uttered,cries).
case(0,child,like).
det(0,child,a).
nmod:like(0,uttered,child).
uttered_like(0,hare,child).
sobbed(0,hare,very_much).
sobbed(0,hare,much).
root(1,ROOT,upbraided).
det(1,sparrow,a).
nsubj(1,upbraided,sparrow).
nsubj(1,said,sparrow).
dobj(1,upbraided,her).
cc(1,upbraided,and).
conj:and(1,upbraided,said).
upbraided(1,sparrow,her).
root(2,ROOT,is).
advmod(2,now,where).
advmod(2,is,now).
nmod:poss(2,swiftness,thy).
amod(2,swiftness,remarkable).
nsubj(2,is,swiftness).
case(2,foot,of).
nmod:of(2,swiftness,foot).
root(3,ROOT,were).
advmod(3,were,why).
nmod:poss(3,feet,your).
nsubj(3,were,feet).
advmod(3,slow,so).
amod(3,feet,slow).
root(4,ROOT,speaking).
mark(4,speaking,while).
det(4,sparrow,the).
nsubj(4,speaking,sparrow).
aux(4,speaking,was).
advmod(4,speaking,thus).
det(4,hawk,a).
nsubj(4,seized,hawk).
nsubj(4,killed,hawk).
advmod(4,seized,suddenly).
ccomp(4,speaking,seized).
dobj(4,seized,him).
cc(4,seized,and).
ccomp(4,speaking,killed).
conj:and(4,seized,killed).
dobj(4,killed,him).
seized(4,hawk,him).
killed(4,hawk,him).
suddenly_seized(4,hawk,him).
root(5,ROOT,said).
det(5,hare,the).
nsubj(5,said,hare).
auxpass(5,comforted,was).
acl:relcl(5,hare,comforted).
case(5,death,in).
nmod:poss(5,death,her).
nmod:in(5,comforted,death).
cc(5,hare,and).
conj:and(5,hare,expiring).
nsubj(5,said,expiring).
root(6,ROOT,ah).
root(7,ROOT,you).
dep(7,have,who).
advmod(7,supposed,so).
advmod(7,when,lately).
advmod(7,supposed,when).
nsubj(7,supposed,you).
advcl(7,have,supposed).
nsubj(7,exulted,yourself).
dep(7,exulted,safe).
xcomp(7,supposed,exulted).
case(7,calamity,over).
nmod:poss(7,calamity,my).
nmod:over(7,exulted,calamity).
dep(7,you,have).
advmod(7,reason,now).
dobj(7,have,reason).
mark(7,deplore,to).
acl:to(7,reason,deplore).
det(7,misfortune,a).
amod(7,misfortune,similar).
dobj(7,deplore,misfortune).
exulted_over(7,yourself,my_calamity).
so_supposed(7,you,yourself_exulted).
so_supposed(7,you,yourself_exulted_over_my_calamity).
supposed(7,you,yourself_exulted).
supposed(7,you,yourself_exulted_over_my_calamity).
