root(0,ROOT,slept).
det(0,man,a).
amod(0,man,shipwrecked).
nsubj(0,slept,man).
aux(0,cast,having).
auxpass(0,cast,been).
dep(0,man,cast).
case(0,shore,upon).
det(0,shore,a).
amod(0,shore,certain).
nmod:upon(0,cast,shore).
case(0,buffetings,after).
nmod:poss(0,buffetings,his).
nmod:after(0,slept,buffetings).
case(0,deep,with).
det(0,deep,the).
nmod:with(0,slept,deep).
slept_after(0,man,his_buffetings).
slept_after(0,shipwrecked_man,his_buffetings).
slept_with(0,shipwrecked_man,deep).
slept_with(0,man,deep).
root(1,ROOT,a).
case(1,a,after).
mark(1,awoke,while).
nsubj(1,awoke,he).
dep(1,a,awoke).
cc(1,awoke,and).
csubj(1,loaded,looking).
case(1,sea,upon).
det(1,sea,the).
nmod:upon(1,looking,sea).
dep(1,a,loaded).
conj:and(1,awoke,loaded).
dobj(1,loaded,it).
case(1,reproaches,with).
nmod:with(1,loaded,reproaches).
looking_upon(1,it,sea).
loaded(1,looking,it).
root(2,ROOT,argued).
nsubj(2,argued,he).
mark(2,enticed,that).
nsubj(2,enticed,it).
ccomp(2,argued,enticed).
dobj(2,enticed,men).
case(2,calmness,with).
det(2,calmness,the).
nmod:with(2,enticed,calmness).
case(2,looks,of).
nmod:poss(2,looks,its).
nmod:of(2,calmness,looks).
cc(2,enticed,but).
advmod(2,induced,when).
nsubj(2,induced,it).
aux(2,induced,had).
ccomp(2,argued,induced).
conj:but(2,enticed,induced).
dobj(2,induced,them).
nsubj:xsubj(2,plow,them).
mark(2,plow,to).
xcomp(2,induced,plow).
nmod:poss(2,waters,its).
dobj(2,plow,waters).
nsubj(2,grew,it).
nsubj(2,destroyed,it).
acl:relcl(2,waters,grew).
xcomp(2,grew,rough).
cc(2,grew,and).
acl:relcl(2,waters,destroyed).
conj:and(2,grew,destroyed).
dobj(2,destroyed,them).
enticed(2,it,men).
enticed_men_with(2,it,calmness_of_its_looks).
had_induced(2,it,them).
enticed_men_with(2,it,calmness).
grew(2,it,rough).
destroyed(2,it,them).
root(3,ROOT,replied).
det(3,sea,the).
nsubj(3,replied,sea).
acl(3,sea,assuming).
det(3,form,the).
dobj(3,assuming,form).
case(3,woman,of).
det(3,woman,a).
nmod:of(3,form,woman).
case(3,him,to).
nmod:to(3,replied,him).
form_of(3,assuming,woman).
replied_to(3,sea,him).
root(4,ROOT,nature).
nsubj(4,nature,blame).
neg(4,blame,not).
dep(4,blame,me).
nmod:poss(4,sir,my).
amod(4,sir,good).
dep(4,blame,sir).
case(4,winds,but).
det(4,winds,the).
nmod:but(4,sir,winds).
case(4,i,for).
nmod:for(4,winds,i).
cop(4,nature,am).
case(4,nature,by).
nmod:poss(4,nature,my).
amod(4,nature,own).
case(4,calm,as).
advcl:as(4,nature,calm).
cc(4,calm,and).
advcl:as(4,nature,firm).
conj:and(4,calm,firm).
advmod(4,nature,even).
case(4,earth,as).
det(4,earth,this).
nmod:as(4,nature,earth).
root(5,ROOT,winds).
cc(5,winds,but).
det(5,winds,the).
advmod(5,falling,suddenly).
acl:relcl(5,winds,falling).
mark(5,create,on).
nsubj(5,create,me).
nsubj(5,lash,me).
advcl:on(5,falling,create).
det(5,waves,these).
dobj(5,create,waves).
cc(5,create,and).
advcl:on(5,falling,lash).
conj:and(5,create,lash).
dobj(5,lash,me).
case(5,fury,into).
nmod:into(5,lash,fury).
create(5,me,waves).
lash(5,me,me).
