root(0,ROOT,complained).
det(0,tortoise,a).
nsubj(0,complained,tortoise).
advmod(0,basking,lazily).
acl(0,tortoise,basking).
case(0,sun,in).
det(0,sun,the).
nmod:in(0,basking,sun).
case(0,sea-birds,to).
det(0,sea-birds,the).
nmod:to(0,complained,sea-birds).
case(0,fate,of).
nmod:poss(0,fate,her).
amod(0,fate,hard).
nmod:of(0,sea-birds,fate).
mark(0,teach,that).
neg(0,one,no).
nsubj(0,teach,one).
aux(0,teach,would).
ccomp(0,complained,teach).
dobj(0,teach,her).
nsubj:xsubj(0,fly,her).
mark(0,fly,to).
xcomp(0,teach,fly).
lazily_basking_in(0,tortoise,sun).
basking_in(0,tortoise,sun).
root(1,ROOT,eagle).
det(1,eagle,an).
dep(1,eagle,hovering).
mark(1,heard,near).
advcl:near(1,hovering,heard).
nmod:poss(1,lamentation,her).
dobj(1,heard,lamentation).
cc(1,heard,and).
advcl:near(1,hovering,demanded).
conj:and(1,heard,demanded).
dep(1,reward,what).
dep(1,eagle,reward).
nsubj(1,give,she).
aux(1,give,would).
acl:relcl(1,reward,give).
dobj(1,give,him).
mark(1,take,if).
nsubj(1,take,he).
nsubj(1,float,he).
aux(1,take,would).
advcl:if(1,give,take).
dobj(1,take,her).
advmod(1,take,aloft).
cc(1,take,and).
advcl:if(1,give,float).
conj:and(1,take,float).
dobj(1,float,her).
case(1,air,in).
det(1,air,the).
nmod:in(1,float,air).
would_take(1,he,her).
would_take_aloft(1,he,her).
float(1,he,her).
would_give(1,she,him).
root(2,ROOT,give).
nsubj(2,give,i).
aux(2,give,will).
dobj(2,give,you).
will_give(2,i,you).
root(3,ROOT,said).
nsubj(3,said,she).
root(4,ROOT,all).
det(4,riches,the).
dep(4,all,riches).
case(4,sea,of).
det(4,sea,the).
amod(4,sea,red).
nmod:of(4,riches,sea).
root(5,ROOT,teach).
nsubj(5,teach,i).
aux(5,teach,will).
dobj(5,teach,you).
nsubj:xsubj(5,fly,you).
mark(5,fly,to).
xcomp(5,teach,fly).
advmod(5,fly,then).
will_teach(5,i,you).
root(6,ROOT,said).
det(6,eagle,the).
nsubj(6,said,eagle).
root(7,ROOT,carried).
cc(7,carried,and).
dep(7,carried,taking).
dobj(7,taking,her).
compound:prt(7,taking,up).
case(7,talons,in).
nmod:poss(7,talons,his).
nmod:in(7,taking,talons).
nsubj(7,carried,he).
nsubj(7,let,her).
dep(7,let,almost).
case(7,clouds,to).
det(7,clouds,the).
nmod:to(7,almost,clouds).
advmod(7,let,suddenly).
nsubj(7,let,he).
xcomp(7,carried,let).
nsubj(7,go,her).
ccomp(7,let,go).
cc(7,carried,and).
nsubj(7,fell,she).
conj:and(7,carried,fell).
case(7,mountain,on).
det(7,mountain,a).
amod(7,mountain,lofty).
nmod:on(7,fell,mountain).
xcomp(7,fell,dashing).
nmod:poss(7,shell,her).
dobj(7,dashing,shell).
case(7,pieces,to).
nmod:to(7,dashing,pieces).
fell_on(7,she,mountain).
carried(7,he,her_suddenly_he_let).
carried(7,he,her_suddenly_let).
fell_on(7,she,lofty_mountain).
carried(7,he,suddenly_he_let).
carried(7,he,her_let).
carried(7,he,he_let).
dashing(7,she,her_shell).
carried(7,he,her_he_let).
root(8,ROOT,exclaimed).
det(8,tortoise,the).
nsubj(8,exclaimed,tortoise).
case(8,moment,in).
det(8,moment,the).
nmod:in(8,exclaimed,moment).
case(8,death,of).
nmod:of(8,moment,death).
exclaimed_in(8,tortoise,moment).
exclaimed_in(8,tortoise,moment_of_death).
root(9,ROOT,deserved).
nsubj(9,deserved,i).
aux(9,deserved,have).
nmod:poss(9,fate,my).
amod(9,fate,present).
dobj(9,deserved,fate).
have_deserved(9,i,my_present_fate).
have_deserved(9,i,my_fate).
root(10,ROOT,had).
mark(10,had,for).
nsubj(10,had,what).
dobj(10,had,i).
mark(10,do,to).
ccomp(10,had,do).
case(10,wings,with).
nmod:with(10,do,wings).
nsubj(10,can,wings).
cc(10,wings,and).
nmod:with(10,do,clouds).
conj:and(10,wings,clouds).
nsubj(10,can,clouds).
ref(10,wings,who).
acl:relcl(10,wings,can).
case(10,difficulty,with).
nmod:with(10,can,difficulty).
nmod:tmod(10,had,move).
advmod(10,move,about).
case(10,earth,on).
det(10,earth,the).
nmod:on(10,move,earth).
root(11,ROOT,had).
punct(11,had,').
mark(11,had,if).
nsubj(11,had,men).
dobj(11,had,all).
nsubj(11,wished,they).
acl:relcl(11,all,wished).
nsubjpass(11,ruined,they).
aux(11,ruined,would).
auxpass(11,ruined,be).
advmod(11,ruined,often).
ccomp(11,wished,ruined).
be(11,they,often_ruined).
be(11,they,ruined).
