root(0,ROOT,clinging).
det(0,chimpanzee,the).
amod(0,chimpanzee,shipwrecked).
nsubj(0,clinging,chimpanzee).
nsubj(0,offered,chimpanzee).
nsubj:xsubj(0,carry,chimpanzee).
aux(0,clinging,had).
aux(0,clinging,been).
case(0,time,for).
det(0,time,a).
amod(0,time,long).
nmod:for(0,clinging,time).
case(0,spar,to).
det(0,spar,a).
amod(0,spar,slender).
nmod:to(0,clinging,spar).
advmod(0,came,when).
det(0,dolphin,a).
nsubj(0,came,dolphin).
acl:relcl(0,spar,came).
advmod(0,came,up).
cc(0,clinging,and).
conj:and(0,clinging,offered).
mark(0,carry,to).
xcomp(0,offered,carry).
dobj(0,carry,him).
advmod(0,carry,ashore).
root(1,ROOT,accepted).
det(1,proposition,this).
compound(1,proposition,kind).
nsubjpass(1,accepted,proposition).
auxpass(1,accepted,was).
advmod(1,accepted,immediately).
cc(1,accepted,and).
mark(1,moved,as).
nsubj(1,moved,they).
conj:and(1,accepted,moved).
case(1,chimp,along).
det(1,chimp,the).
advmod(1,commenced,chimp).
dep(1,moved,commenced).
mark(1,tell,to).
xcomp(1,commenced,tell).
det(1,fish,the).
iobj(1,tell,fish).
amod(1,tales,many).
amod(1,tales,marvelous).
dobj(1,tell,tales).
det(1,one,every).
det:qmod(1,them,one).
mwe(1,one,of).
nmod:tmod(1,tell,them).
det(1,bundle,a).
nsubj(1,commenced,bundle).
nsubj:xsubj(1,tell,bundle).
case(1,falsehoods,of).
nmod:of(1,bundle,falsehoods).
tell(1,bundle,many_marvelous_tales).
was(1,kind_proposition,accepted).
was(1,kind_proposition,immediately_accepted).
tell(1,bundle,marvelous_tales).
root(2,ROOT,you).
advmod(2,well,well).
dep(2,you,well).
cop(2,chap,are).
advmod(2,chap,indeed).
det(2,chap,an).
amod(2,chap,educated).
acl:relcl(2,you,chap).
root(3,ROOT,said).
det(3,dolphin,the).
nsubj(3,said,dolphin).
case(3,admiration,in).
nmod:in(3,dolphin,admiration).
is_in(3,dolphin,admiration).
root(4,ROOT,neglected).
nmod:poss(4,schooling,my).
nsubjpass(4,neglected,schooling).
aux(4,neglected,has).
auxpass(4,neglected,been).
advmod(4,neglected,sadly).
mark(4,went,as).
nsubj(4,went,i).
nsubj(4,old,i).
advcl:as(4,neglected,went).
case(4,sea,to).
nmod:to(4,went,sea).
dep(4,sea,when).
cc(4,went,but).
det(4,week,a).
dep(4,old,week).
advcl:as(4,neglected,old).
conj:but(4,went,old).
has(4,my_schooling,has_neglected).
went_to(4,i,sea).
has(4,my_schooling,has_sadly_neglected).
root(5,ROOT,entered).
advmod(5,entered,just).
advmod(5,entered,then).
nsubj(5,entered,they).
det(5,bay,a).
amod(5,bay,large).
dobj(5,entered,bay).
cc(5,entered,and).
det(5,dolphin,the).
nsubj(5,said,dolphin).
acl(5,dolphin,referring).
case(5,it,to).
nmod:to(5,referring,it).
conj:and(5,entered,said).
entered(5,they,bay).
referring_to(5,dolphin,it).
entered(5,they,large_bay).
just_entered(5,they,bay).
just_entered(5,they,large_bay).
root(6,ROOT,suppose).
dep(6,suppose,i).
nsubj(6,know,you).
ccomp(6,suppose,know).
amod(6,roads,herring).
nsubj(6,suppose,roads).
root(7,ROOT,replied).
det(7,chimp,the).
nsubj(7,replied,chimp).
dep(7,chimp,taking).
dobj(7,taking,this).
case(7,name,for).
det(7,name,the).
nmod:for(7,this,name).
case(7,fellow,of).
det(7,fellow,a).
nmod:of(7,name,fellow).
cc(7,taking,and).
neg(7,wishing,not).
dep(7,chimp,wishing).
conj:and(7,taking,wishing).
mark(7,appear,to).
xcomp(7,wishing,appear).
xcomp(7,appear,ignorant).
root(8,ROOT,do).
nsubj(8,know,i).
ccomp(8,do,know).
dobj(8,know,rhodes).
know(8,i,rhodes).
root(9,ROOT,i).
dep(9,i,well).
aux(9,think,should).
advmod(9,think,almost).
acl:relcl(9,i,think).
advmod(9,think,so).
root(10,ROOT,chum).
nsubj(10,chum,he).
nsubj(10,related,he).
cop(10,chum,'s).
det(10,chum,an).
amod(10,chum,old).
compound(10,chum,college).
case(10,mine,of).
nmod:of(10,chum,mine).
cc(10,chum,and).
conj:and(10,chum,related).
case(10,family,to).
nmod:poss(10,family,our).
nmod:by(10,related,family).
case(10,family,by).
punct(10,chum,-).
has(10,he,old_college_chum).
has(10,he,college_chum_of_mine).
has(10,he,old_college_chum_of_mine).
has(10,he,old).
has(10,he,college_chum).
root(11,ROOT,much).
nsubj(11,much,this).
cop(11,much,was).
advmod(11,much,too).
case(11,dolphin,for).
det(11,dolphin,the).
nmod:for(11,much,dolphin).
nsubj(11,made,dolphin).
ref(11,dolphin,who).
advmod(11,made,immediately).
acl:relcl(11,dolphin,made).
det(11,leap,a).
amod(11,leap,great).
nsubj(11,left,leap).
cc(11,leap,and).
advmod(11,diving,then).
conj:and(11,leap,diving).
nsubj(11,left,diving).
advmod(11,left,quickly).
ccomp(11,made,left).
det(11,impostor,the).
dobj(11,left,impostor).
case(11,air,in).
det(11,air,the).
nmod:in(11,left,air).
case(11,instant,for).
det(11,instant,an).
nmod:for(11,air,instant).
mark(11,splashed,before).
nsubj(11,splashed,he).
nsubj(11,disappeared,he).
advcl:before(11,left,splashed).
advmod(11,splashed,back).
cc(11,splashed,and).
advcl:before(11,left,disappeared).
conj:and(11,splashed,disappeared).
left_impostor_in(11,diving,air_for_instant).
left(11,great_leap,impostor).
left_impostor_in(11,leap,air).
left_impostor(11,leap,he_splashed).
quickly_left_impostor_in(11,great_leap,air).
quickly_left_impostor_in(11,leap,air_for_instant).
left_impostor(11,great_leap,he_splashed).
left_impostor_in(11,leap,air_for_instant).
quickly_left_impostor(11,great_leap,he_splashed_back).
quickly_left(11,diving,impostor).
left_impostor_in(11,great_leap,air).
quickly_left_impostor(11,leap,he_splashed).
quickly_left_impostor(11,diving,he_splashed_back).
quickly_left_impostor(11,great_leap,he_splashed).
quickly_left_impostor(11,diving,he_splashed).
quickly_left(11,great_leap,impostor).
left(11,diving,impostor).
left_impostor(11,diving,he_splashed).
quickly_left_impostor_in(11,great_leap,air_for_instant).
quickly_left_impostor_in(11,leap,air).
quickly_left_impostor_in(11,diving,air_for_instant).
left_impostor(11,leap,he_splashed_back).
left_impostor_in(11,great_leap,air_for_instant).
left_impostor(11,diving,he_splashed_back).
quickly_left_impostor(11,leap,he_splashed_back).
quickly_left(11,leap,impostor).
left(11,leap,impostor).
quickly_left_impostor_in(11,diving,air).
left_impostor_in(11,diving,air).
left_impostor(11,great_leap,he_splashed_back).
