root(0,ROOT,came).
det(0,man,a).
nsubj(0,came,man).
nsubj(0,asked,man).
case(0,forest,into).
det(0,forest,a).
nmod:into(0,came,forest).
cc(0,came,and).
conj:and(0,came,asked).
det(0,trees,the).
dobj(0,asked,trees).
nsubj:xsubj(0,provide,trees).
mark(0,provide,to).
xcomp(0,asked,provide).
nsubj(0,handle,him).
dep(0,him,a).
ccomp(0,provide,handle).
case(0,axe,for).
nmod:poss(0,axe,his).
nmod:for(0,handle,axe).
came_into(0,man,forest).
asked(0,man,trees).
handle_for(0,him,his_axe).
root(1,ROOT,consented).
det(1,trees,the).
nsubj(1,consented,trees).
nsubj(1,gave,trees).
case(1,request,to).
nmod:poss(1,request,his).
nmod:to(1,consented,request).
cc(1,consented,and).
conj:and(1,consented,gave).
iobj(1,gave,him).
det(1,ash-tree,a).
amod(1,ash-tree,young).
dobj(1,gave,ash-tree).
gave(1,trees,him).
consented_to(1,trees,his_request).
gave(1,trees,ash-tree).
gave(1,trees,young_ash-tree).
root(2,ROOT,had).
neg(2,sooner,no).
advmod(2,had,sooner).
det(2,man,the).
dobj(2,had,man).
acl:relcl(2,man,fitted).
det(2,new,a).
nsubj(2,handle,new).
ccomp(2,fitted,handle).
case(2,axe,to).
nmod:poss(2,axe,his).
nmod:to(2,handle,axe).
case(2,it,from).
nmod:from(2,had,it).
mark(2,began,than).
nsubj(2,began,he).
nsubj:xsubj(2,use,he).
nsubj(2,felled,he).
advcl:than(2,had,began).
mark(2,use,to).
xcomp(2,began,use).
dobj(2,use,it).
cc(2,began,and).
advmod(2,felled,quickly).
advcl:than(2,had,felled).
conj:and(2,began,felled).
case(2,strokes,with).
nmod:poss(2,strokes,his).
nmod:with(2,felled,strokes).
det(2,giants,the).
amod(2,giants,noblest).
nsubj(2,had,giants).
case(2,forest,of).
det(2,forest,the).
nmod:of(2,giants,forest).
handle_to(2,new,his_axe).
felled_with(2,he,his_strokes).
quickly_felled_with(2,he,his_strokes).
use(2,he,it).
root(3,ROOT,oak).
det(3,oak,an).
amod(3,oak,old).
dep(3,oak,lamenting).
advmod(3,said,when).
advmod(3,late,too).
advmod(3,said,late).
det(3,destruction,the).
nsubj(3,said,destruction).
case(3,companions,of).
nmod:poss(3,companions,his).
nmod:of(3,destruction,companions).
advcl(3,lamenting,said).
case(3,cedar,to).
det(3,cedar,a).
amod(3,cedar,neighboring).
nmod:to(3,said,cedar).
said_to(3,destruction,cedar).
late_said_to(3,destruction,cedar).
said_to(3,destruction,neighboring_cedar).
too_late_said_to(3,destruction,neighboring_cedar).
late_said_to(3,destruction,neighboring_cedar).
too_late_said_to(3,destruction,cedar).
root(4,ROOT,lost).
det(4,step,the).
amod(4,step,first).
nsubj(4,lost,step).
aux(4,lost,has).
nsubj(4,all,us).
xcomp(4,lost,all).
has_lost(4,first_step,us_all).
has_lost(4,step,us_all).
root(5,ROOT,given).
mark(5,given,if).
nsubj(5,given,we).
nsubj(5,stood,we).
aux(5,given,had).
neg(5,given,not).
compound:prt(5,given,up).
det(5,rights,the).
dobj(5,given,rights).
case(5,ash,of).
det(5,ash,the).
nmod:of(5,rights,ash).
nsubj(5,retained,we).
aux(5,retained,might).
advmod(5,retained,yet).
aux(5,retained,have).
dep(5,given,retained).
nmod:poss(5,privileges,our).
amod(5,privileges,own).
dobj(5,retained,privileges).
cc(5,given,and).
aux(5,stood,have).
conj:and(5,given,stood).
case(5,ages,for).
nmod:for(5,stood,ages).
stood_for(5,we,ages).
