root(0,ROOT,came).
det(0,stag,a).
nsubj(0,came,stag).
nsubj:xsubj(0,drink,stag).
acl(0,stag,overpowered).
case(0,heat,by).
nmod:by(0,overpowered,heat).
case(0,spring,to).
det(0,spring,a).
nmod:to(0,came,spring).
mark(0,drink,to).
xcomp(0,came,drink).
came_to(0,stag,spring).
came(0,stag,drink).
overpowered_by(0,stag,heat).
root(1,ROOT,seeing).
nmod:poss(1,shadow,his).
amod(1,shadow,own).
dobj(1,seeing,shadow).
acl(1,shadow,reflected).
case(1,water,in).
det(1,water,the).
nmod:in(1,reflected,water).
nsubj(1,admired,he).
nsubj(1,felt,he).
advmod(1,admired,greatly).
acl:relcl(1,water,admired).
det(1,size,the).
dobj(1,admired,size).
cc(1,size,and).
dobj(1,admired,variety).
conj:and(1,size,variety).
case(1,horns,of).
nmod:poss(1,horns,his).
nmod:of(1,size,horns).
cc(1,admired,but).
acl:relcl(1,water,felt).
conj:but(1,admired,felt).
xcomp(1,felt,angry).
case(1,himself,with).
nmod:with(1,felt,himself).
mark(1,having,for).
advcl:for(1,seeing,having).
amod(1,slender,such).
dobj(1,having,slender).
cc(1,slender,and).
amod(1,feet,weak).
dobj(1,having,feet).
conj:and(1,slender,feet).
size_of(1,he,his_horns).
felt_with(1,he,himself).
greatly_admired(1,he,size_of_his_horns).
admired(1,he,size).
greatly_admired(1,he,variety).
greatly_admired(1,he,size).
felt(1,he,angry).
admired(1,he,size_of_his_horns).
size_of(1,variety,his_horns).
admired(1,he,variety).
root(2,ROOT,contemplating).
mark(2,contemplating,while).
nsubj(2,contemplating,he).
aux(2,contemplating,was).
advmod(2,contemplating,thus).
dobj(2,contemplating,himself).
det(2,lion,a).
nsubj(2,appeared,lion).
nsubj(2,crouched,lion).
nsubj:xsubj(2,spring,lion).
dep(2,contemplating,appeared).
case(2,pool,at).
det(2,pool,the).
nmod:at(2,appeared,pool).
cc(2,appeared,and).
dep(2,contemplating,crouched).
conj:and(2,appeared,crouched).
mark(2,spring,to).
xcomp(2,crouched,spring).
case(2,him,upon).
nmod:upon(2,spring,him).
crouched(2,lion,spring).
was_thus_contemplating(2,he,himself).
was_contemplating(2,he,himself).
crouched(2,lion,spring_upon_him).
root(3,ROOT,took).
det(3,stag,the).
nsubj(3,took,stag).
advmod(3,took,immediately).
case(3,flight,to).
nmod:to(3,took,flight).
cc(3,took,and).
csubj(3,kept,exerting).
nmod:poss(3,speed,his).
amod(3,speed,utmost).
dobj(3,exerting,speed).
advmod(3,long,as).
advmod(3,exerting,long).
mark(3,smooth,as).
det(3,plain,the).
nsubj(3,smooth,plain).
nsubj(3,open,plain).
cop(3,smooth,was).
advcl:as(3,long,smooth).
cc(3,smooth,and).
advcl:as(3,long,open).
conj:and(3,smooth,open).
conj:and(3,took,kept).
dobj(3,kept,himself).
advmod(3,distance,easily).
case(3,distance,at).
det(3,distance,a).
amod(3,distance,safe).
nmod:at(3,kept,distance).
case(3,lion,from).
det(3,lion,the).
nmod:from(3,kept,lion).
exerting(3,himself,his_speed).
exerting_long(3,himself,his_speed).
exerting_as_long(3,himself,his_utmost_speed).
exerting_long(3,himself,his_utmost_speed).
took_to(3,stag,flight).
exerting(3,himself,his_utmost_speed).
immediately_took_to(3,stag,flight).
exerting_as_long(3,himself,his_speed).
root(4,ROOT,entering).
cc(4,entering,but).
det(4,wood,a).
dobj(4,entering,wood).
nsubj(4,became,he).
acl:relcl(4,wood,became).
xcomp(4,became,entangled).
case(4,horns,by).
nmod:poss(4,horns,his).
nmod:by(4,became,horns).
cc(4,became,and).
det(4,lion,the).
nsubj(4,came,lion).
nsubj(4,caught,lion).
advmod(4,came,quickly).
acl:relcl(4,wood,came).
conj:and(4,became,came).
compound:prt(4,came,up).
case(4,him,to).
nmod:to(4,came,him).
cc(4,came,and).
conj:and(4,became,caught).
conj:and(4,came,caught).
dobj(4,caught,him).
became(4,he,entangled).
caught(4,lion,him).
came_up_to(4,lion,him).
became_by(4,he,his_horns).
quickly_came_up_to(4,lion,him).
root(5,ROOT,reproached).
advmod(5,reproached,when).
advmod(5,late,too).
advmod(5,reproached,late).
nsubj(5,reproached,he).
advmod(5,reproached,thus).
dobj(5,reproached,himself).
late_thus_reproached(5,he,himself).
late_reproached(5,he,himself).
too_late_reproached(5,he,himself).
thus_reproached(5,he,himself).
too_late_thus_reproached(5,he,himself).
reproached(5,he,himself).
root(6,ROOT,me).
nsubj(6,me,woe).
cop(6,me,is).
is(6,woe,me).
root(7,ROOT,deceived).
advmod(7,deceived,how).
nsubj(7,deceived,i).
aux(7,deceived,have).
dobj(7,deceived,myself).
have_deceived(7,i,myself).
root(8,ROOT,feet).
det(8,feet,these).
nsubj(8,saved,feet).
ref(8,feet,which).
aux(8,saved,would).
aux(8,saved,have).
acl:relcl(8,feet,saved).
iobj(8,saved,me).
dobj(8,saved,i).
acl(8,i,despised).
cc(8,i,and).
dobj(8,saved,i).
conj:and(8,i,i).
acl(8,i,gloried).
case(8,antlers,in).
det(8,antlers,these).
nmod:in(8,feet,antlers).
nsubj(8,proved,antlers).
ref(8,antlers,which).
aux(8,proved,have).
acl:relcl(8,antlers,proved).
nmod:poss(8,destruction,my).
dobj(8,proved,destruction).
is_in(8,feet,antlers).
