root(0,ROOT,wearied).
det(0,traveler,a).
nsubj(0,wearied,traveler).
case(0,journey,from).
det(0,journey,a).
amod(0,journey,long).
nmod:from(0,wearied,journey).
acl(0,journey,lay).
compound:prt(0,lay,down).
dep(0,lay,overcome).
case(0,fatigue,with).
nmod:with(0,overcome,fatigue).
case(0,brink,on).
det(0,brink,the).
advmod(0,brink,very).
nmod:on(0,overcome,brink).
case(0,well,of).
dep(0,well,a).
advmod(0,well,deep).
acl:of(0,brink,well).
wearied_from(0,traveler,journey).
wearied_from(0,traveler,long_journey).
root(1,ROOT,addressed).
advmod(1,about,just).
mark(1,about,as).
nsubj(1,about,he).
nsubj:xsubj(1,fall,he).
aux(1,about,was).
advcl:as(1,said,about).
mark(1,fall,to).
xcomp(1,about,fall).
case(1,water,into).
det(1,water,the).
nmod:into(1,fall,water).
ccomp(1,fall,dame).
dobj(1,dame,fortune).
nsubjpass(1,said,it).
auxpass(1,said,is).
dep(1,addressed,said).
xcomp(1,said,appeared).
case(1,him,to).
nmod:to(1,appeared,him).
cc(1,appeared,and).
xcomp(1,said,waking).
conj:and(1,appeared,waking).
dobj(1,waking,him).
case(1,slumber,from).
nmod:poss(1,slumber,his).
nmod:from(1,waking,slumber).
advmod(1,addressed,thus).
nsubj(1,addressed,him).
is_said(1,it,appeared).
is_said(1,it,appeared_to_him).
is_said(1,it,just_he_was_about).
is(1,it,said).
appeared_to(1,it,him).
is_said(1,it,he_was_about).
root(2,ROOT,wake).
amod(2,pray,good).
compound(2,pray,sir).
nsubj(2,wake,pray).
compound:prt(2,wake,up).
mark(2,thrown,for).
mark(2,fall,if).
nsubj(2,fall,you).
advcl:if(2,thrown,fall).
case(2,well,into).
det(2,well,the).
nmod:into(2,fall,well).
det(2,blame,the).
nsubjpass(2,thrown,blame).
aux(2,thrown,will).
auxpass(2,thrown,be).
advcl:for(2,wake,thrown).
case(2,me,on).
nmod:on(2,thrown,me).
cc(2,thrown,and).
nsubj(2,get,i).
aux(2,get,shall).
advcl:for(2,wake,get).
conj:and(2,thrown,get).
det(2,name,an).
amod(2,name,ill).
dobj(2,get,name).
case(2,mortals,among).
nmod:among(2,get,mortals).
wake_up(2,good_sir_pray,will_thrown_on_me).
shall_get(2,i,name).
shall_get(2,i,ill_name).
wake_up(2,sir_pray,will_thrown).
be(2,blame,will_thrown).
fall_into(2,you,well).
wake_up(2,good_sir_pray,will_thrown).
wake_up(2,sir_pray,will_thrown_on_me).
be(2,blame,will_thrown_on_me).
shall_get_name_among(2,i,mortals).
root(3,ROOT,find).
mark(3,find,for).
nsubj(3,find,i).
det(3,men,that).
nsubj(3,sure,men).
nsubj:xsubj(3,impute,men).
cop(3,sure,are).
ccomp(3,find,sure).
mark(3,impute,to).
xcomp(3,sure,impute).
nmod:poss(3,calamities,their).
dobj(3,impute,calamities).
case(3,me,to).
nmod:to(3,impute,me).
advmod(3,folly,however).
advmod(3,folly,much).
case(3,folly,by).
nmod:poss(3,folly,their).
amod(3,folly,own).
nmod:by(3,impute,folly).
nsubj(3,brought,they).
aux(3,brought,have).
advmod(3,brought,really).
acl:relcl(3,folly,brought).
dobj(3,brought,them).
case(3,themselves,on).
nmod:on(3,brought,themselves).
have_really_brought(3,they,them).
impute(3,men,their_calamities).
are(3,men,sure).
have_brought(3,they,them).
