root(0,ROOT,broke).
det(0,thieves,some).
nsubj(0,broke,thieves).
nsubj(0,found,thieves).
case(0,house,into).
det(0,house,a).
nmod:into(0,broke,house).
cc(0,broke,and).
conj:and(0,broke,found).
dobj(0,found,nothing).
cc(0,cock,but).
det(0,cock,a).
dep(0,broke,cock).
dobj(0,stole,cock).
ref(0,cock,whom).
nsubj(0,stole,they).
nsubj(0,got,they).
acl:relcl(0,cock,stole).
cc(0,stole,and).
acl:relcl(0,cock,got).
conj:and(0,stole,got).
compound:prt(0,got,off).
case(0,fast,as).
advcl:as(0,got,fast).
mark(0,could,as).
nsubj(0,could,they).
advcl:as(0,broke,could).
broke_into(0,thieves,house).
found(0,thieves,nothing).
got_off_as(0,they,fast).
broke(0,thieves,they_could).
root(1,ROOT,arriving).
mark(1,arriving,upon).
case(1,home,at).
nmod:at(1,arriving,home).
nsubj(1,prepared,they).
nsubj:xsubj(1,kill,they).
acl:relcl(1,home,prepared).
mark(1,kill,to).
xcomp(1,prepared,kill).
det(1,cock,the).
dobj(1,kill,cock).
nsubj(1,pleaded,cock).
ref(1,cock,who).
advmod(1,pleaded,thus).
acl:relcl(1,cock,pleaded).
case(1,life,for).
nmod:poss(1,life,his).
nmod:for(1,pleaded,life).
root(2,ROOT,pray).
dep(2,pray,spare).
dep(2,pray,me).
root(3,ROOT,serviceable).
nsubj(3,serviceable,i).
cop(3,serviceable,am).
advmod(3,serviceable,very).
case(3,men,to).
nmod:to(3,serviceable,men).
am_serviceable_to(3,i,men).
am(3,i,serviceable).
am(3,i,very_serviceable).
am_very_serviceable_to(3,i,men).
root(4,ROOT,wake).
nsubj(4,wake,i).
dobj(4,wake,them).
compound:prt(4,wake,up).
case(4,night,in).
det(4,night,the).
nmod:in(4,wake,night).
case(4,work,to).
nmod:poss(4,work,their).
nmod:to(4,wake,work).
wake_up(4,i,them).
root(5,ROOT,reason).
nsubj(5,reason,that).
cop(5,reason,is).
det(5,reason,the).
amod(5,reason,very).
advmod(5,kill,why).
nsubj(5,kill,we).
aux(5,kill,must).
dep(5,more,the).
advmod(5,kill,more).
acl:relcl(5,reason,kill).
dobj(5,kill,you).
must_kill(5,we,you).
must_more_kill(5,we,you).
root(6,ROOT,replied).
nsubj(6,replied,they).
root(7,ROOT,wake).
mark(7,wake,for).
advmod(7,wake,when).
nsubj(7,wake,you).
nmod:poss(7,neighbors,your).
dobj(7,wake,neighbors).
nsubj(7,put,you).
advmod(7,put,entirely).
dep(7,wake,put).
det(7,end,an).
dobj(7,put,end).
case(7,business,to).
nmod:poss(7,business,our).
nmod:to(7,put,business).
put(7,you,end).
entirely_put(7,you,end).
entirely_put_end_to(7,you,our_business).
wake(7,you,your_neighbors).
put_end_to(7,you,our_business).
root(8,ROOT,intentions).
