root(0,ROOT,come).
det(0,lion,a).
nsubj(0,come,lion).
nsubj(0,lay,lion).
aux(0,come,had).
case(0,end,to).
det(0,end,the).
nmod:to(0,come,end).
case(0,days,of).
nmod:poss(0,days,his).
nmod:of(0,end,days).
cc(0,come,and).
conj:and(0,come,lay).
amod(0,death,sick).
amod(0,death,unto).
dobj(0,lay,death).
case(0,mouth,at).
det(0,mouth,the).
nmod:at(0,lay,mouth).
case(0,cave,of).
nmod:poss(0,cave,his).
nmod:of(0,mouth,cave).
acl(0,cave,gasping).
case(0,breath,for).
nmod:for(0,gasping,breath).
lay_at(0,lion,mouth_of_his_cave_gasping_for_breath).
had_come_to(0,lion,end).
lay_death_at(0,lion,mouth).
lay_death_at(0,lion,mouth_of_his_cave_gasping).
lay(0,lion,sick_death).
lay(0,lion,sick_unto_death).
lay_at(0,lion,mouth_of_his_cave).
lay_death_at(0,lion,mouth_of_his_cave_gasping_for_breath).
lay(0,lion,death).
lay(0,lion,unto_death).
lay_at(0,lion,mouth).
lay_at(0,lion,mouth_of_his_cave_gasping).
lay_death_at(0,lion,mouth_of_his_cave).
had_come_to(0,lion,end_of_his_days).
root(1,ROOT,animals).
det(1,animals,the).
nmod:poss(1,subjects,his).
nsubj(1,came,subjects).
nsubj(1,drew,subjects).
acl:relcl(1,animals,came).
nsubj(1,him,round).
xcomp(1,came,him).
cc(1,came,and).
acl:relcl(1,animals,drew).
conj:and(1,came,drew).
mark(1,grew,nearer).
mark(1,grew,as).
nsubj(1,grew,he).
advcl:as(1,drew,grew).
advmod(1,helpless,more).
cc(1,more,and).
conj:and(1,more,more).
advmod(1,helpless,more).
xcomp(1,grew,helpless).
drew(1,his_subjects,he_grew).
grew(1,he,more_helpless).
grew(1,he,helpless).
came(1,his_subjects,round_him).
root(2,ROOT,saw).
advmod(2,saw,when).
nsubj(2,saw,they).
dobj(2,saw,him).
case(2,point,on).
det(2,point,the).
nmod:on(2,saw,point).
case(2,death,of).
nmod:of(2,point,death).
nsubj(2,thought,they).
acl:relcl(2,death,thought).
case(2,themselves,to).
nmod:to(2,thought,themselves).
saw(2,they,him).
thought_to(2,they,themselves).
root(3,ROOT,is).
advmod(3,is,now).
det(3,time,the).
nsubj(3,is,time).
mark(3,pay,to).
acl:to(3,time,pay).
compound:prt(3,pay,off).
amod(3,grudges,old).
dobj(3,pay,grudges).
root(4,ROOT,came).
mark(4,came,so).
det(4,boar,the).
nsubj(4,came,boar).
nsubj(4,drove,boar).
advmod(4,came,up).
cc(4,came,and).
conj:and(4,came,drove).
case(4,him,at).
nmod:at(4,drove,him).
case(4,tusks,with).
nmod:poss(4,tusks,his).
nmod:with(4,drove,tusks).
drove_with(4,boar,his_tusks).
drove_at(4,boar,him).
root(5,ROOT,bull).
dep(5,bull,then).
det(5,bull,a).
ccomp(5,bull,gored).
dobj(5,gored,him).
case(5,horns,with).
nmod:poss(5,horns,his).
nmod:with(5,gored,horns).
root(6,ROOT,lion).
dep(6,lion,still).
det(6,lion,the).
ccomp(6,lion,lay).
xcomp(6,lay,helpless).
case(6,them,before).
nmod:before(6,helpless,them).
mark(6,came,so).
det(6,feeling,the).
compound(6,feeling,ass).
nsubj(6,came,feeling).
advmod(6,safe,quite).
amod(6,feeling,safe).
case(6,danger,from).
nmod:from(6,safe,danger).
advcl:so(6,lay,came).
advmod(6,came,up).
cc(6,came,and).
csubj(6,kicked,turning).
nmod:poss(6,tail,his).
dobj(6,turning,tail).
case(6,lion,to).
det(6,lion,the).
nmod:to(6,turning,lion).
advcl:so(6,lay,kicked).
conj:and(6,came,kicked).
compound:prt(6,kicked,up).
nmod:poss(6,heels,his).
dobj(6,kicked,heels).
case(6,face,into).
nmod:poss(6,face,his).
nmod:into(6,kicked,face).
turning(6,his_heels,his_tail).
root(7,ROOT,death).
nsubj(7,death,this).
cop(7,death,is).
det(7,death,a).
amod(7,death,double).
is(7,this,double).
root(8,ROOT,growled).
det(8,lion,the).
nsubj(8,growled,lion).
