root(0,ROOT,saw).
det(0,pigeon,a).
nsubj(0,saw,pigeon).
acl(0,pigeon,oppressed).
case(0,thirst,by).
amod(0,thirst,excessive).
nmod:by(0,oppressed,thirst).
det(0,goblet,a).
dobj(0,saw,goblet).
case(0,water,of).
nmod:of(0,goblet,water).
acl(0,water,painted).
case(0,signboard,on).
det(0,signboard,a).
nmod:on(0,painted,signboard).
saw(0,pigeon,goblet_of_water_painted).
saw(0,pigeon,goblet_of_water).
saw(0,pigeon,goblet).
oppressed_by(0,pigeon,thirst).
oppressed_by(0,pigeon,excessive_thirst).
saw(0,pigeon,goblet_of_water_painted_on_signboard).
root(1,ROOT,supposing).
neg(1,supposing,not).
dobj(1,supposing,it).
nsubj:xsubj(1,picture,it).
mark(1,picture,to).
cop(1,picture,be).
advmod(1,picture,only).
det(1,picture,a).
xcomp(1,supposing,picture).
nsubj(1,flew,she).
nsubj(1,dashed,she).
acl:relcl(1,picture,flew).
case(1,it,towards).
nmod:towards(1,flew,it).
case(1,whir,with).
det(1,whir,a).
amod(1,whir,loud).
nmod:with(1,flew,whir).
cc(1,flew,and).
advmod(1,dashed,unwittingly).
acl:relcl(1,picture,dashed).
conj:and(1,flew,dashed).
case(1,signboard,against).
det(1,signboard,the).
nmod:against(1,dashed,signboard).
amod(1,signboard,jarring).
nmod:npmod(1,terribly,herself).
amod(1,signboard,terribly).
root(2,ROOT,broken).
aux(2,broken,having).
nmod:poss(2,wings,her).
dobj(2,broken,wings).
case(2,blow,by).
det(2,blow,the).
nmod:by(2,broken,blow).
nsubj(2,fell,she).
nsubjpass(2,caught,she).
acl:relcl(2,blow,fell).
case(2,ground,to).
det(2,ground,the).
nmod:to(2,fell,ground).
cc(2,fell,and).
auxpass(2,caught,was).
acl:relcl(2,blow,caught).
conj:and(2,fell,caught).
case(2,one,by).
det:qmod(2,bystanders,one).
mwe(2,one,of).
det(2,bystanders,the).
nmod(2,caught,bystanders).
was(2,she,caught).
fell_to(2,she,ground).
