root(0,ROOT,feeding).
det(0,thrush,a).
nsubj(0,feeding,thrush).
nsubj(0,move,thrush).
aux(0,feeding,was).
case(0,myrtle-tree,on).
det(0,myrtle-tree,a).
nmod:on(0,feeding,myrtle-tree).
cc(0,feeding,and).
aux(0,move,did).
neg(0,move,not).
conj:and(0,feeding,move).
case(0,it,from).
nmod:from(0,move,it).
mark(0,delicious,because).
nmod:poss(0,berries,its).
nsubj(0,delicious,berries).
cop(0,delicious,were).
advmod(0,delicious,so).
advcl:because(0,move,delicious).
root(1,ROOT,observed).
det(1,fowler,a).
nsubj(1,observed,fowler).
nmod:poss(1,staying,her).
dobj(1,observed,staying).
advmod(1,long,so).
advmod(1,and,long).
case(1,spot,in).
nummod(1,spot,one).
nmod:in(1,long,spot).
advmod(1,observed,and).
conj(1,and,having).
advmod(1,bird-limed,well).
dobj(1,having,bird-limed).
nmod:poss(1,reeds,his).
nsubj(1,caught,reeds).
acl:relcl(1,bird-limed,caught).
dobj(1,caught,her).
observed(1,fowler,her_staying).
observed_and(1,fowler,her_staying).
observed_long_and(1,fowler,her_staying).
observed_so_long_and(1,fowler,her_staying).
root(2,ROOT,exclaimed).
det(2,thrush,the).
nsubj(2,exclaimed,thrush).
cop(2,point,being).
case(2,point,at).
det(2,point,the).
dep(2,thrush,point).
case(2,death,of).
nmod:of(2,point,death).
root(3,ROOT,creature).
compound(3,creature,o).
amod(3,creature,foolish).
dobj(3,am,creature).
ref(3,creature,that).
nsubj(3,am,i).
acl:relcl(3,creature,am).
root(4,ROOT,deprived).
case(4,sake,for).
det(4,sake,the).
nmod:for(4,deprived,sake).
case(4,food,of).
det(4,food,a).
amod(4,food,little).
amod(4,food,pleasant).
nmod:of(4,sake,food).
nsubj(4,deprived,i).
aux(4,deprived,have).
dobj(4,deprived,myself).
case(4,life,of).
nmod:poss(4,life,my).
nmod:of(4,deprived,life).
have_deprived(4,i,myself).
