root(0,ROOT,besieged).
det(0,city,a).
amod(0,city,great).
nsubjpass(0,besieged,city).
auxpass(0,besieged,was).
cc(0,besieged,and).
nmod:poss(0,inhabitants,its).
nsubjpass(0,called,inhabitants).
nsubj:xsubj(0,consider,inhabitants).
auxpass(0,called,were).
conj:and(0,besieged,called).
advmod(0,called,together).
mark(0,consider,to).
xcomp(0,called,consider).
det(0,means,the).
amod(0,means,best).
dobj(0,consider,means).
mark(0,protecting,of).
acl:of(0,means,protecting).
dobj(0,protecting,it).
case(0,enemy,from).
det(0,enemy,the).
nmod:from(0,protecting,enemy).
were(0,its_inhabitants,called_together).
was(0,great_city,besieged).
were_called_together(0,its_inhabitants,consider).
were(0,its_inhabitants,called).
were_called(0,its_inhabitants,consider).
was(0,city,besieged).
root(1,ROOT,recommended).
det(1,bricklayer,a).
nsubj(1,recommended,bricklayer).
advmod(1,recommended,earnestly).
dobj(1,recommended,bricks).
mark(1,affording,as).
advcl:as(1,recommended,affording).
det(1,material,the).
amod(1,material,best).
dobj(1,affording,material).
case(1,resistance,for).
det(1,resistance,an).
amod(1,resistance,effective).
nmod:for(1,material,resistance).
affording(1,bricklayer,material_for_effective_resistance).
affording(1,bricklayer,best_material_for_resistance).
affording(1,bricklayer,best_material).
affording(1,bricklayer,material).
affording(1,bricklayer,material_for_resistance).
affording(1,bricklayer,best_material_for_effective_resistance).
recommended(1,bricklayer,bricks).
earnestly_recommended(1,bricklayer,bricks).
root(2,ROOT,proposed).
det(2,carpenter,a).
nsubj(2,proposed,carpenter).
case(2,enthusiasm,with).
amod(2,enthusiasm,equal).
nmod:with(2,carpenter,enthusiasm).
dobj(2,proposed,timber).
case(2,method,as).
det(2,method,a).
amod(2,method,preferable).
nmod:as(2,proposed,method).
case(2,defense,of).
nmod:of(2,method,defense).
proposed_timber_as(2,carpenter,preferable_method).
proposed_timber_as(2,carpenter,method_of_defense).
is_with(2,carpenter,equal_enthusiasm).
proposed(2,carpenter,timber).
proposed_timber_as(2,carpenter,preferable_method_of_defense).
proposed_timber_as(2,carpenter,method).
root(3,ROOT,stood).
mark(3,stood,upon).
dobj(3,stood,which).
det(3,currier,a).
nsubj(3,stood,currier).
nsubj(3,said,currier).
advmod(3,stood,up).
cc(3,stood,and).
conj:and(3,stood,said).
root(4,ROOT,sirs).
nsubj(4,differ,i).
acl:relcl(4,sirs,differ).
case(4,you,from).
nmod:from(4,differ,you).
advmod(4,differ,altogether).
expl(4,is,there).
acl:relcl(4,sirs,is).
neg(4,material,no).
nsubj(4,is,material).
case(4,resistance,for).
nmod:for(4,material,resistance).
amod(4,resistance,equal).
case(4,covering,to).
det(4,covering,a).
nmod:to(4,equal,covering).
case(4,hides,of).
nmod:of(4,covering,hides).
differ_altogether_from(4,i,you).
differ_from(4,i,you).
root(5,ROOT,nothing).
cc(5,nothing,and).
advmod(5,good,so).
amod(5,nothing,good).
case(5,leather,as).
nmod:as(5,good,leather).
