root(0,ROOT,stole).
det(0,boy,a).
nsubj(0,stole,boy).
nsubj(0,took,boy).
det(0,lesson-book,a).
dobj(0,stole,lesson-book).
case(0,one,from).
nmod:from(0,stole,one).
case(0,schoolfellows,of).
nmod:poss(0,schoolfellows,his).
nmod:of(0,one,schoolfellows).
cc(0,stole,and).
conj:and(0,stole,took).
dobj(0,took,it).
advmod(0,took,home).
case(0,mother,to).
nmod:poss(0,mother,his).
nmod:to(0,home,mother).
took(0,boy,it).
stole_lesson-book_from(0,boy,one_his_schoolfellows).
stole(0,boy,lesson-book).
took_home(0,boy,it).
stole_lesson-book_from(0,boy,one_of_his_schoolfellows).
root(1,ROOT,abstained).
nsubj(1,abstained,she).
nsubj(1,encouraged,she).
neg(1,only,not).
cc:preconj(1,abstained,only).
mark(1,beating,from).
advcl:from(1,abstained,beating).
dobj(1,beating,him).
cc(1,abstained,but).
conj:but(1,abstained,encouraged).
dobj(1,encouraged,him).
beating(1,she,him).
encouraged(1,she,him).
root(2,ROOT,stole).
nsubj(2,stole,he).
nsubj(2,brought,he).
amod(2,time,next).
nmod:tmod(2,stole,time).
det(2,cloak,a).
dobj(2,stole,cloak).
cc(2,stole,and).
conj:and(2,stole,brought).
dobj(2,brought,it).
case(2,her,to).
nmod:to(2,brought,her).
cc(2,stole,and).
nsubj(2,commended,she).
advmod(2,commended,again).
conj:and(2,stole,commended).
dobj(2,commended,him).
stole_cloak_at_time(2,he,time).
brought(2,he,it).
commended(2,she,him).
stole_cloak_at_time(2,he,next_time).
stole(2,he,cloak).
again_commended(2,she,him).
root(3,ROOT,advanced).
det(3,youth,the).
nsubj(3,advanced,youth).
case(3,adulthood,to).
nmod:to(3,advanced,adulthood).
acl:relcl(3,adulthood,proceeded).
mark(3,steal,to).
xcomp(3,proceeded,steal).
dobj(3,steal,things).
case(3,value,of).
advmod(3,greater,still).
amod(3,value,greater).
nmod:of(3,things,value).
root(4,ROOT,last).
case(4,last,at).
nsubjpass(4,caught,he).
auxpass(4,caught,was).
acl:relcl(4,last,caught).
case(4,act,in).
det(4,act,the).
amod(4,act,very).
nmod:in(4,caught,act).
cc(4,last,and).
conj:and(4,last,having).
nmod:poss(4,hands,his).
nsubj(4,bound,hands).
ccomp(4,having,bound).
advmod(4,bound,behind).
nsubjpass(4,led,him).
auxpass(4,led,was).
ccomp(4,bound,led).
advmod(4,led,away).
case(4,place,to).
det(4,place,the).
nmod:to(4,led,place).
case(4,execution,of).
amod(4,execution,public).
nmod:of(4,place,execution).
was(4,he,caught).
was_caught_in(4,he,very_act).
was(4,him,led_away).
was_caught_in(4,he,act).
was_led_to(4,him,place_of_execution).
was_led_to(4,him,place_of_public_execution).
was_led_away_to(4,him,place_of_public_execution).
was_led_away_to(4,him,place_of_execution).
was_led_to(4,him,place).
was_led_away_to(4,him,place).
was(4,him,led).
root(5,ROOT,followed).
nmod:poss(5,mother,his).
nsubj(5,followed,mother).
nsubj(5,beat,mother).
case(5,crowd,in).
det(5,crowd,the).
nmod:in(5,followed,crowd).
cc(5,followed,and).
advmod(5,beat,violently).
conj:and(5,followed,beat).
nmod:poss(5,breast,her).
dobj(5,beat,breast).
case(5,whereupon,in).
compound(5,whereupon,sorrow).
nmod:in(5,beat,whereupon).
det(5,man,the).
amod(5,man,young).
nsubj(5,said,man).
dep(5,beat,said).
beat(5,his_mother,her_breast).
followed_in(5,his_mother,crowd).
violently_beat(5,his_mother,her_breast).
root(6,ROOT,wish).
nsubj(6,wish,i).
nsubj:xsubj(6,say,i).
mark(6,say,to).
xcomp(6,wish,say).
dobj(6,say,something).
case(6,mother,to).
nmod:poss(6,mother,my).
nmod:to(6,say,mother).
case(6,ear,in).
nmod:poss(6,ear,her).
nmod:in(6,mother,ear).
say(6,i,something).
wish(6,i,say).
say_something_to(6,i,my_mother_in_her_ear).
wish(6,i,say_to_my_mother_in_her_ear).
say_to(6,i,my_mother).
is_in(6,my_mother,her_ear).
wish(6,i,say_to_my_mother).
say_something_to(6,i,my_mother).
say_to(6,i,my_mother_in_her_ear).
root(7,ROOT,came).
nsubj(7,came,she).
xcomp(7,came,close).
mark(7,seized,to).
nsubj(7,seized,him).
cc(7,him,and).
conj:and(7,him,he).
nsubj(7,seized,he).
advmod(7,seized,quickly).
advcl:to(7,close,seized).
nmod:poss(7,ear,her).
dobj(7,seized,ear).
case(7,teeth,with).
nmod:poss(7,teeth,his).
nmod:with(7,seized,teeth).
cc(7,seized,and).
dep(7,it,bit).
advcl:to(7,close,it).
conj:and(7,seized,it).
advcl(7,came,off).
came(7,she,close).
root(8,ROOT,upbraided).
det(8,mother,the).
nsubj(8,upbraided,mother).
dobj(8,upbraided,him).
case(8,whereon,as).
det(8,whereon,an).
amod(8,whereon,unnatural).
compound(8,whereon,child).
nmod:as(8,upbraided,whereon).
nsubj(8,replied,he).
acl:relcl(8,whereon,replied).
upbraided(8,mother,him).
root(9,ROOT,ah).
root(10,ROOT,beaten).
mark(10,beaten,if).
nsubj(10,beaten,you).
aux(10,beaten,had).
dobj(10,beaten,me).
advmod(10,stole,when).
nsubj(10,stole,i).
nsubj(10,brought,i).
nsubjpass(10,led,i).
advmod(10,stole,first).
advcl(10,beaten,stole).
cc(10,stole,and).
advcl(10,beaten,brought).
conj:and(10,stole,brought).
case(10,you,to).
nmod:to(10,stole,you).
mark(10,come,that).
nsubj(10,come,lesson-book).
dep(10,lesson-book,i).
aux(10,come,should).
neg(10,come,not).
aux(10,come,have).
ccomp(10,stole,come).
case(10,this,to).
nmod:to(10,come,this).
cc(10,stole,nor).
aux(10,led,have).
auxpass(10,led,been).
advmod(10,led,thus).
advcl(10,beaten,led).
conj:and(10,stole,led).
case(10,death,to).
det(10,death,a).
amod(10,death,disgraceful).
nmod:to(10,led,death).
been(10,i,thus_led).
been(10,i,led).
been_led_to(10,i,disgraceful_death).
been_led_to(10,i,death).
been_thus_led_to(10,i,disgraceful_death).
had_beaten(10,you,me).
been_thus_led_to(10,i,death).
