root(0,ROOT,traveler).
det(0,traveler,a).
dep(0,traveler,about).
mark(0,set,to).
xcomp(0,about,set).
compound:prt(0,set,out).
case(0,journey,on).
det(0,journey,a).
nmod:on(0,set,journey).
acl:relcl(0,journey,saw).
nmod:poss(0,dog,his).
nsubj(0,stand,dog).
ccomp(0,saw,stand).
case(0,door,at).
det(0,door,the).
nmod:at(0,stand,door).
acl(0,door,stretching).
dobj(0,stretching,himself).
root(1,ROOT,asked).
nsubj(1,asked,he).
dobj(1,asked,him).
advmod(1,asked,sharply).
asked(1,he,him).
asked_sharply(1,he,him).
root(2,ROOT,stand).
advmod(2,stand,why).
aux(2,stand,do).
nsubj(2,stand,you).
expl(2,gaping,there).
xcomp(2,stand,gaping).
do_stand(2,you,gaping).
root(3,ROOT,ready).
nsubj(3,ready,everything).
cop(3,ready,is).
cc(3,come,but).
nsubj(3,come,you).
advmod(3,come,so).
ccomp(3,ready,come).
case(3,me,with).
nmod:with(3,come,me).
advmod(3,come,instantly).
so_come_instantly_with(3,you,me).
come_instantly_with(3,you,me).
is(3,everything,ready).
so_come_with(3,you,me).
come_with(3,you,me).
root(4,ROOT,replied).
det(4,dog,the).
nsubj(4,replied,dog).
acl(4,dog,wagging).
nmod:poss(4,tail,his).
dobj(4,wagging,tail).
root(5,ROOT,master).
compound(5,master,o).
root(6,ROOT,ready).
nsubj(6,ready,i).
cop(6,ready,am).
advmod(6,ready,quite).
am(6,i,ready).
am(6,i,quite_ready).
root(7,ROOT,you).
nsubj(7,you,it).
cop(7,you,is).
mark(7,waiting,for).
dobj(7,waiting,whom).
nsubj(7,waiting,i).
aux(7,waiting,am).
advcl:for(7,you,waiting).
is_you(7,it,i_am_waiting).
is(7,it,you).
