root(0,ROOT,ventured).
det(0,trumpeter,a).
nsubj(0,ventured,trumpeter).
nsubjpass(0,captured,trumpeter).
case(0,battle,during).
det(0,battle,a).
nmod:during(0,trumpeter,battle).
advmod(0,ventured,too).
case(0,enemy,near).
det(0,enemy,the).
nmod:near(0,ventured,enemy).
cc(0,ventured,and).
auxpass(0,captured,was).
conj:and(0,ventured,captured).
case(0,them,by).
nmod:agent(0,captured,them).
ventured_near(0,trumpeter,enemy).
was_captured_by(0,trumpeter,them).
ventured_too_near(0,trumpeter,enemy).
was(0,trumpeter,captured).
root(1,ROOT,about).
nsubj(1,about,they).
nsubj:xsubj(1,proceed,they).
cop(1,about,were).
mark(1,proceed,to).
xcomp(1,about,proceed).
mark(1,put,to).
xcomp(1,proceed,put).
dobj(1,put,him).
case(1,death,to).
nmod:to(1,put,death).
advmod(1,begged,when).
nsubj(1,begged,he).
advcl(1,put,begged).
dobj(1,begged,them).
nsubj:xsubj(1,hear,them).
mark(1,hear,to).
xcomp(1,begged,hear).
nmod:poss(1,plea,his).
dobj(1,hear,plea).
case(1,mercy,for).
nmod:for(1,hear,mercy).
hear(1,them,his_plea).
were(1,they,about).
begged(1,he,them).
root(2,ROOT,fight).
nsubj(2,fight,i).
aux(2,fight,do).
neg(2,fight,not).
root(3,ROOT,said).
nsubj(3,said,he).
root(4,ROOT,carry).
cc(4,carry,and).
advmod(4,carry,indeed).
neg(4,weapon,no).
dobj(4,carry,weapon).
root(5,ROOT,blow).
dep(5,blow,i).
advmod(5,blow,only).
det(5,trumpet,this).
dep(5,blow,trumpet).
cc(5,blow,and).
conj:and(5,blow,surely).
nsubj(5,harm,that).
aux(5,harm,can).
neg(5,harm,not).
conj:and(5,blow,harm).
dobj(5,harm,you).
root(6,ROOT,kill).
advmod(6,why,then).
advmod(6,kill,why).
aux(6,kill,should).
nsubj(6,kill,you).
dobj(6,kill,me).
should_kill(6,you,me).
root(7,ROOT,fight).
nsubj(7,fight,you).
aux(7,fight,may).
neg(7,fight,not).
dobj(7,fight,yourself).
root(8,ROOT,said).
det(8,others,the).
nsubj(8,said,others).
root(9,ROOT,encourage).
cc(9,encourage,but).
nsubj(9,encourage,you).
nsubj(9,guide,you).
cc(9,encourage,and).
conj:and(9,encourage,guide).
nmod:poss(9,men,your).
dobj(9,encourage,men).
case(9,fight,to).
det(9,fight,the).
nmod:to(9,encourage,fight).
encourage(9,you,your_men).
