root(0,ROOT,had).
det(0,dogs,the).
nummod(0,dogs,two).
nsubj(0,had,dogs).
det(0,man,a).
dep(0,dogs,man).
nummod(0,dogs,two).
dobj(0,had,dogs).
det(0,hound,a).
nsubj(0,taught,hound).
nsubj:xsubj(0,watch,hound).
acl(0,hound,trained).
mark(0,assist,to).
xcomp(0,trained,assist).
dobj(0,assist,him).
case(0,sports,in).
nmod:poss(0,sports,his).
nmod:in(0,assist,sports).
cc(0,sports,and).
det(0,housedog,a).
nmod:in(0,assist,housedog).
conj:and(0,sports,housedog).
acl:relcl(0,dogs,taught).
mark(0,watch,to).
xcomp(0,taught,watch).
det(0,house,the).
dobj(0,watch,house).
watch(0,hound,house).
root(1,ROOT,returned).
advmod(1,returned,when).
nsubj(1,returned,he).
dobj(1,returned,home).
case(1,sport,after).
det(1,day,a).
amod(1,day,good).
nmod:poss(1,sport,day).
case(1,day,'s).
nmod:after(1,returned,sport).
nsubj(1,gave,he).
advmod(1,gave,always).
acl:relcl(1,sport,gave).
det(1,housedog,the).
iobj(1,gave,housedog).
det(1,share,a).
amod(1,share,large).
dobj(1,gave,share).
case(1,spoil,of).
nmod:poss(1,spoil,his).
nmod:of(1,share,spoil).
always_gave(1,he,share_of_his_spoil).
always_gave(1,he,share).
gave(1,he,large_share).
share_of(1,he,his_spoil).
always_gave(1,he,large_share).
gave(1,he,large_share_of_his_spoil).
returned(1,he,home).
gave(1,he,share_of_his_spoil).
gave(1,he,housedog).
after(1,good_day,sport).
gave(1,he,share).
large_share_of(1,he,his_spoil).
large_share_of(1,housedog,his_spoil).
share_of(1,housedog,his_spoil).
always_gave(1,he,housedog).
always_gave(1,he,large_share_of_his_spoil).
root(2,ROOT,reproached).
det(2,feeling,the).
compound(2,feeling,hound).
nsubj(2,reproached,feeling).
amod(2,aggrieved,much).
amod(2,feeling,aggrieved).
case(2,this,at).
nmod:at(2,feeling,this).
nmod:poss(2,companion,his).
dobj(2,reproached,companion).
xcomp(2,reproached,saying).
reproached(2,hound_feeling_much_aggrieved,his_companion).
reproached(2,hound_feeling_aggrieved,his_companion).
reproached(2,hound_feeling,his_companion).
root(3,ROOT,hard).
nsubj(3,hard,it).
nsubj:xsubj(3,have,it).
cop(3,hard,is).
advmod(3,hard,very).
mark(3,have,to).
xcomp(3,hard,have).
det:predet(3,labor,all).
det(3,labor,this).
dobj(3,have,labor).
mark(3,luxuriate,while).
nsubj(3,assist,you).
nsubj(3,luxuriate,you).
ref(3,you,who).
aux(3,assist,do).
neg(3,assist,not).
acl:relcl(3,you,assist).
case(3,chase,in).
det(3,chase,the).
nmod:in(3,assist,chase).
advcl:while(3,hard,luxuriate).
case(3,fruits,on).
det(3,fruits,the).
nmod:on(3,luxuriate,fruits).
case(3,exertions,of).
nmod:poss(3,exertions,my).
nmod:of(3,fruits,exertions).
have(3,it,labor).
root(4,ROOT,replied).
det(4,housedog,the).
nsubj(4,replied,housedog).
root(5,ROOT,do).
neg(5,blame,not).
dep(5,do,blame).
nsubj(5,friend,me).
nmod:poss(5,friend,my).
xcomp(5,blame,friend).
cc(5,blame,but).
dep(5,do,find).
conj:but(5,blame,find).
dobj(5,find,fault).
case(5,master,with).
det(5,master,the).
nmod:with(5,find,master).
nsubj(5,taught,master).
ref(5,master,who).
aux(5,taught,has).
neg(5,taught,not).
acl:relcl(5,master,taught).
dobj(5,taught,me).
case(5,labor,to).
nmod:to(5,taught,labor).
cc(5,blame,but).
mark(5,depend,to).
dep(5,do,depend).
conj:but(5,blame,depend).
case(5,subsistence,for).
nmod:for(5,depend,subsistence).
case(5,labor,on).
det(5,labor,the).
nmod:on(5,depend,labor).
case(5,others,of).
nmod:of(5,labor,others).
