%% a traveler wearied from a long journey lay down overcome with fatigue on the very brink of a deep well.
% dependencies.
root(0,root,weary).
det(0,traveler,a).
nsubj(0,weary,traveler).
case(0,journey,from).
det(0,journey,a).
amod(0,journey,long).
nmod:from(0,weary,journey).
acl(0,journey,lay).
compound:prt(0,lay,down).
dep(0,lay,overcome).
case(0,fatigue,with).
nmod:with(0,overcome,fatigue).
case(0,brink,on).
det(0,brink,the).
advmod(0,brink,very).
nmod:on(0,overcome,brink).
case(0,well,of).
dep(0,well,a).
advmod(0,well,deep).
acl:of(0,brink,well).
% relations.
aos(0,weary_from,traveler,journey).
aos(0,weary_from,traveler,long_journey).
%% just as he was about to fall into the water dame fortune it is said appeared to him and waking him from his slumber thus addressed him.
% dependencies.
root(1,root,address).
advmod(1,about,just).
mark(1,about,as).
nsubj(1,about,he).
nsubj:xsubj(1,fall,he).
aux(1,about,be).
advcl:as(1,say,about).
mark(1,fall,to).
xcomp(1,about,fall).
case(1,water,into).
det(1,water,the).
nmod:into(1,fall,water).
ccomp(1,fall,dame).
dobj(1,dame,fortune).
nsubjpass(1,say,it).
auxpass(1,say,be).
dep(1,address,say).
xcomp(1,say,appear).
case(1,he,to).
nmod:to(1,appear,he).
cc(1,appear,and).
xcomp(1,say,wake).
conj:and(1,appear,wake).
dobj(1,wake,he).
case(1,slumber,from).
nmod:poss(1,slumber,he).
nmod:from(1,wake,slumber).
advmod(1,address,thus).
nsubj(1,address,he).
% relations.
aos(1,be_say,it,appear).
aos(1,be_say,it,appear_to_he).
aos(1,be_say,it,just_he_be_about).
aos(1,be,it,say).
aos(1,appear_to,it,he).
aos(1,be_say,it,he_be_about).
%% good sir pray wake up for if you fall into the well the blame will be thrown on me and i shall get an ill name among mortals.
% dependencies.
root(2,root,wake).
amod(2,pray,good).
compound(2,pray,sir).
nsubj(2,wake,pray).
compound:prt(2,wake,up).
mark(2,throw,for).
mark(2,fall,if).
nsubj(2,fall,you).
advcl:if(2,throw,fall).
case(2,well,into).
det(2,well,the).
nmod:into(2,fall,well).
det(2,blame,the).
nsubjpass(2,throw,blame).
aux(2,throw,will).
auxpass(2,throw,be).
advcl:for(2,wake,throw).
case(2,I,on).
nmod:on(2,throw,I).
cc(2,throw,and).
nsubj(2,get,i).
aux(2,get,shall).
advcl:for(2,wake,get).
conj:and(2,throw,get).
det(2,name,a).
amod(2,name,ill).
dobj(2,get,name).
case(2,mortal,among).
nmod:among(2,get,mortal).
% relations.
aos(2,wake_up,good_sir_pray,will_throw_on_I).
aos(2,shall_get,i,name).
aos(2,shall_get,i,ill_name).
aos(2,wake_up,sir_pray,will_throw).
aos(2,be,blame,will_throw).
aos(2,fall_into,you,well).
aos(2,wake_up,good_sir_pray,will_throw).
aos(2,wake_up,sir_pray,will_throw_on_I).
aos(2,be,blame,will_throw_on_I).
aos(2,shall_get_name_among,i,mortal).
%% for i find that men are sure to impute their calamities to me however much by their own folly they have really brought them on themselves.
% dependencies.
root(3,root,find).
mark(3,find,for).
nsubj(3,find,i).
det(3,man,that).
nsubj(3,sure,man).
nsubj:xsubj(3,impute,man).
cop(3,sure,be).
ccomp(3,find,sure).
mark(3,impute,to).
xcomp(3,sure,impute).
nmod:poss(3,calamity,they).
dobj(3,impute,calamity).
case(3,I,to).
nmod:to(3,impute,I).
advmod(3,folly,however).
advmod(3,folly,much).
case(3,folly,by).
nmod:poss(3,folly,they).
amod(3,folly,own).
nmod:by(3,impute,folly).
nsubj(3,bring,they).
aux(3,bring,have).
advmod(3,bring,really).
acl:relcl(3,folly,bring).
dobj(3,bring,they).
case(3,themselves,on).
nmod:on(3,bring,themselves).
% relations.
aos(3,have_really_bring,they,they).
aos(3,impute,man,they_calamity).
aos(3,be,man,sure).
aos(3,have_bring,they,they).
