root(0,ROOT,the).
dep(0,the,swallow).
cc(0,the,and).
det(0,crow,the).
dep(0,the,crow).
dep(0,crow,had).
det(0,contention,a).
dobj(0,had,contention).
case(0,plumage,about).
nmod:poss(0,plumage,their).
nmod:about(0,contention,plumage).
root(1,ROOT,put).
det(1,crow,the).
nsubj(1,put,crow).
det(1,end,an).
dobj(1,put,end).
case(1,dispute,to).
det(1,dispute,the).
nmod:to(1,put,dispute).
mark(1,saying,by).
advcl:by(1,put,saying).
put_end_to(1,crow,dispute).
put_end(1,crow,saying).
put(1,crow,end).
root(2,ROOT,spring).
nmod:poss(2,feathers,your).
nsubj(2,spring,feathers).
cop(2,spring,are).
dep(2,well,all).
advmod(2,well,very).
advmod(2,spring,well).
case(2,spring,in).
det(2,spring,the).
cc(2,protect,but).
nsubj(2,protect,mine).
ccomp(2,spring,protect).
dobj(2,protect,me).
case(2,winter,against).
det(2,winter,the).
nmod:against(2,protect,winter).
are_in(2,your_feathers,well_spring).
protect(2,mine,me).
are_in(2,your_feathers,spring).
are_in(2,your_feathers,very_well_spring).
