root(0,ROOT,kite).
det(0,kite,the).
dep(0,kite,sick).
dep(0,kite,kite).
det(0,kite,a).
amod(0,death,sick).
amod(0,death,unto).
nsubj(0,said,death).
acl:relcl(0,kite,said).
case(0,mother,to).
nmod:poss(0,mother,his).
nmod:to(0,said,mother).
said_to(0,sick_death,his_mother).
said_to(0,death,his_mother).
said_to(0,sick_unto_death,his_mother).
said_to(0,unto_death,his_mother).
root(1,ROOT,mother).
compound(1,mother,o).
root(2,ROOT,mourn).
aux(2,mourn,do).
neg(2,mourn,not).
cc(2,invoke,but).
case(2,once,at).
advmod(2,invoke,once).
parataxis(2,mourn,invoke).
det(2,gods,the).
dobj(2,invoke,gods).
dobj(2,prolonged,that).
nmod:poss(2,life,my).
nsubjpass(2,prolonged,life).
aux(2,prolonged,may).
auxpass(2,prolonged,be).
ccomp(2,mourn,prolonged).
root(3,ROOT,replied).
nsubj(3,replied,she).
root(4,ROOT,alas).
root(5,ROOT,pity).
nmod:poss(5,son,my).
nsubj(5,do,son).
nsubj(5,pity,son).
ref(5,son,which).
case(5,gods,of).
det(5,gods,the).
nmod:of(5,do,gods).
acl:relcl(5,son,do).
nsubj(5,think,you).
ccomp(5,do,think).
aux(5,pity,will).
dobj(5,pity,you).
root(6,ROOT,there).
cop(6,there,is).
nsubj(6,there,one).
dobj(6,outraged,whom).
nsubj(6,outraged,you).
aux(6,outraged,have).
neg(6,outraged,not).
dep(6,there,outraged).
mark(6,filching,by).
advcl:by(6,outraged,filching).
case(6,altars,from).
nmod:poss(6,altars,their).
amod(6,altars,very).
nmod:from(6,filching,altars).
det(6,part,a).
dobj(6,filching,part).
case(6,sacrifice,of).
det(6,sacrifice,the).
nmod:of(6,part,sacrifice).
acl(6,sacrifice,offered).
compound:prt(6,offered,up).
case(6,them,to).
nmod:to(6,offered,them).
root(7,ROOT,make).
punct(7,make,').
nsubj(7,make,we).
aux(7,make,must).
dobj(7,make,friends).
case(7,prosperity,in).
nmod:in(7,make,prosperity).
mark(7,have,if).
nsubj(7,have,we).
aux(7,have,would).
advcl:if(7,make,have).
nmod:poss(7,help,their).
dobj(7,have,help).
nmod(7,have,in).
dep(7,make,adversity).
must_make(7,we,friends).
would_have(7,we,their_help).
must_make_friends_in(7,we,prosperity).
