root(0,ROOT,happened).
nsubj(0,happened,it).
mark(0,sowing,that).
det(0,countryman,a).
nsubj(0,sowing,countryman).
aux(0,sowing,was).
ccomp(0,happened,sowing).
det(0,seeds,some).
compound(0,seeds,hemp).
dobj(0,sowing,seeds).
case(0,field,in).
det(0,field,a).
nmod:in(0,seeds,field).
advmod(0,swallow,where).
nsubj(0,swallow,a).
acl:relcl(0,field,swallow).
cc(0,sowing,and).
det(0,birds,some).
amod(0,birds,other).
nsubj(0,hopping,birds).
aux(0,hopping,were).
ccomp(0,happened,hopping).
conj:and(0,sowing,hopping).
mark(0,picking,about).
advcl:about(0,hopping,picking).
compound:prt(0,picking,up).
nmod:poss(0,food,their).
dobj(0,picking,food).
picking_up(0,other_birds,their_food).
picking_up(0,birds,their_food).
sowing(0,countryman,hemp_seeds).
is_in(0,hemp_seeds,field).
root(1,ROOT,beware).
case(1,man,of).
det(1,man,that).
nmod:of(1,beware,man).
root(2,ROOT,swallow).
mark(2,swallow,quoth).
nsubj(2,swallow,the).
root(3,ROOT,doing).
advmod(3,doing,why).
dep(3,why,what).
aux(3,doing,is).
nsubj(3,doing,he).
root(4,ROOT,said).
det(4,others,the).
nsubj(4,said,others).
root(5,ROOT,seed).
nsubj(5,seed,that).
cop(5,seed,is).
compound(5,seed,hemp).
nsubj(5,sowing,he).
cop(5,sowing,is).
acl:relcl(5,seed,sowing).
is(5,he,sowing).
root(6,ROOT,careful).
cop(6,careful,be).
mark(6,pick,to).
xcomp(6,careful,pick).
compound:prt(6,pick,up).
det(6,one,every).
det:qmod(6,seeds,one).
mwe(6,one,of).
det(6,seeds,the).
dobj(6,pick,seeds).
cc(6,seeds,or).
dobj(6,pick,else).
conj:or(6,seeds,else).
nsubj(6,repent,you).
aux(6,repent,will).
ccomp(6,careful,repent).
dobj(6,repent,it).
repent(6,you,it).
root(7,ROOT,paid).
det(7,birds,the).
nsubj(7,paid,birds).
nsubj(7,heed,no).
ccomp(7,paid,heed).
case(7,hemp,to).
det(7,hemp,the).
dep(7,hemp,swallow).
dep(7,words,'s).
dep(7,swallow,words).
cc(7,words,and).
nmod(7,grew,by).
cc(7,by,and).
conj:and(7,by,by).
nmod(7,grew,by).
det(7,hemp,the).
nsubj(7,grew,hemp).
nsubjpass(7,made,hemp).
dep(7,swallow,grew).
conj:and(7,words,grew).
advmod(7,grew,up).
cc(7,grew,and).
auxpass(7,made,was).
conj:and(7,words,made).
conj:and(7,grew,made).
case(7,cord,into).
nmod:into(7,made,cord).
cc(7,swallow,and).
mark(7,made,of).
det(7,nets,the).
compound(7,nets,cords).
nsubjpass(7,made,nets).
auxpass(7,made,were).
conj:and(7,swallow,made).
dep(7,hemp,made).
cc(7,made,and).
amod(7,bird,many).
det(7,bird,a).
nsubj(7,despised,bird).
nsubjpass(7,caught,bird).
ref(7,bird,that).
aux(7,despised,had).
acl:relcl(7,bird,despised).
nsubj(7,swallow,the).
ccomp(7,despised,swallow).
nsubj(7,advice,'s).
ccomp(7,swallow,advice).
auxpass(7,caught,was).
conj:and(7,swallow,caught).
conj:and(7,made,caught).
case(7,nets,in).
nmod:in(7,caught,nets).
acl(7,nets,made).
compound:prt(7,made,out).
case(7,very,of).
det(7,very,that).
nmod:of(7,made,very).
nmod:to(7,heed,hemp).
were(7,cords_nets,made).
heed_to(7,no,hemp).
root(8,ROOT,tell).
dep(8,tell,what).
aux(8,tell,did).
nsubj(8,tell,i).
dobj(8,tell,you).
did_tell(8,i,you).
root(9,ROOT,said).
dobj(9,said,the).
nsubj(9,said,swallow).
said(9,swallow,the).
