root(0,ROOT,bought).
det(0,man,a).
amod(0,man,certain).
amod(0,man,rich).
nsubj(0,bought,man).
case(0,market,in).
det(0,market,the).
nmod:in(0,bought,market).
det(0,goose,a).
dobj(0,bought,goose).
cc(0,goose,and).
det(0,swan,a).
dobj(0,bought,swan).
conj:and(0,goose,swan).
bought_swan_in(0,certain_rich_man,market).
bought(0,rich_man,goose).
bought_swan_in(0,rich_man,market).
bought_goose_in(0,certain_man,market).
bought_goose_in(0,certain_rich_man,market).
bought(0,man,swan).
bought(0,rich_man,swan).
bought_goose_in(0,man,market).
bought(0,certain_man,swan).
bought(0,certain_rich_man,goose).
bought_swan_in(0,man,market).
bought_goose_in(0,rich_man,market).
bought(0,man,goose).
bought_swan_in(0,certain_man,market).
bought(0,certain_man,goose).
bought(0,certain_rich_man,swan).
root(1,ROOT,fed).
nsubj(1,fed,he).
nsubj(1,kept,he).
det(1,one,the).
dobj(1,fed,one).
case(1,table,for).
nmod:poss(1,table,his).
nmod:for(1,one,table).
cc(1,fed,and).
conj:and(1,fed,kept).
det(1,other,the).
dobj(1,kept,other).
case(1,sake,for).
det(1,sake,the).
nmod:for(1,kept,sake).
case(1,song,of).
nmod:poss(1,song,its).
nmod:of(1,sake,song).
kept(1,he,other).
fed(1,he,one_for_his_table).
root(2,ROOT,came).
advmod(2,came,when).
det(2,time,the).
nsubj(2,came,time).
mark(2,killing,for).
advcl:for(2,came,killing).
det(2,goose,the).
dobj(2,killing,goose).
det(2,cook,the).
nsubj(2,went,cook).
nsubj:xsubj(2,get,cook).
acl:relcl(2,goose,went).
mark(2,get,to).
xcomp(2,went,get).
dobj(2,get,him).
case(2,night,at).
nmod:at(2,get,night).
advmod(2,dark,when).
nsubj(2,dark,it).
cop(2,dark,was).
advcl(2,get,dark).
cc(2,dark,and).
nsubj(2,able,he).
nsubj:xsubj(2,distinguish,he).
cop(2,able,was).
neg(2,able,not).
advcl(2,get,able).
conj:and(2,dark,able).
mark(2,distinguish,to).
xcomp(2,able,distinguish).
nummod(2,bird,one).
dobj(2,distinguish,bird).
case(2,other,from).
det(2,other,the).
nmod:from(2,distinguish,other).
get(2,cook,him).
root(3,ROOT,caught).
case(3,mistake,by).
nmod:by(3,caught,mistake).
nsubj(3,caught,he).
det(3,swan,the).
dobj(3,caught,swan).
case(3,goose,instead).
mwe(3,instead,of).
det(3,goose,the).
nmod:instead_of(3,swan,goose).
caught_swan_by(3,he,mistake).
caught(3,he,swan).
root(4,ROOT,threatened).
det(4,swan,the).
nsubj(4,threatened,swan).
case(4,burst,with).
compound(4,burst,death).
dep(4,threatened,burst).
advmod(4,burst,forth).
case(4,song,into).
nmod:into(4,forth,song).
cc(4,burst,and).
dep(4,threatened,thus).
conj:and(4,burst,thus).
dep(4,burst,made).
nsubj(4,known,himself).
dep(4,made,known).
case(4,voice,by).
nmod:poss(4,voice,his).
nmod:by(4,known,voice).
cc(4,made,and).
dep(4,burst,preserved).
conj:and(4,made,preserved).
nmod:poss(4,life,his).
dobj(4,preserved,life).
case(4,melody,by).
nmod:poss(4,melody,his).
nmod:by(4,preserved,melody).
