root(0,ROOT,left).
det(0,man,a).
amod(0,man,young).
nsubj(0,left,man).
det(0,spendthrift,a).
amod(0,spendthrift,great).
nsubj(0,run,spendthrift).
nsubj(0,had,spendthrift).
aux(0,run,had).
acl:relcl(0,man,run).
case(0,patrimony,through).
det:predet(0,patrimony,all).
nmod:poss(0,patrimony,his).
nmod:through(0,run,patrimony).
cc(0,run,and).
acl:relcl(0,man,had).
conj:and(0,run,had).
case(0,cloak,but).
nummod(0,cloak,one).
amod(0,cloak,good).
nmod:but(0,had,cloak).
had_run_through(0,spendthrift,his_patrimony).
had_run_through(0,great_spendthrift,patrimony).
had_but(0,spendthrift,one_good_cloak).
had_but(0,great_spendthrift,one_cloak).
had_run_through(0,great_spendthrift,his_patrimony).
had_run_through(0,spendthrift,patrimony).
had_but(0,spendthrift,one_cloak).
had_but(0,great_spendthrift,one_good_cloak).
root(1,ROOT,day).
nummod(1,day,one).
nsubj(1,happened,he).
nsubj:xsubj(1,see,he).
acl:relcl(1,day,happened).
mark(1,see,to).
xcomp(1,happened,see).
nsubj(1,swallow,a).
ccomp(1,see,swallow).
nsubj(1,appeared,which).
aux(1,appeared,had).
ccomp(1,swallow,appeared).
case(1,season,before).
nmod:poss(1,season,its).
nmod:before(1,appeared,season).
ccomp(1,appeared,skimming).
case(1,pool,along).
det(1,pool,a).
nmod:along(1,skimming,pool).
cc(1,skimming,and).
ccomp(1,appeared,twittering).
conj:and(1,skimming,twittering).
advmod(1,twittering,gaily).
happened(1,he,see).
root(2,ROOT,supposed).
nsubj(2,supposed,he).
nsubj(2,went,he).
mark(2,come,that).
nsubj(2,come,summer).
aux(2,come,had).
ccomp(2,supposed,come).
cc(2,supposed,and).
conj:and(2,supposed,went).
cc(2,went,and).
conj:and(2,supposed,sold).
conj:and(2,went,sold).
nmod:poss(2,cloak,his).
dobj(2,went,cloak).
went(2,he,his_cloak).
root(3,ROOT,days).
dep(3,days,not).
amod(3,days,many).
advmod(3,winter,later).
dep(3,set,winter).
acl:relcl(3,days,set).
case(3,again,in).
advcl:in(3,set,again).
case(3,frost,with).
amod(3,frost,renewed).
nmod:with(3,days,frost).
cc(3,frost,and).
nmod:with(3,days,cold).
conj:and(3,frost,cold).
is_with(3,many_days,renewed_frost).
root(4,ROOT,found).
advmod(4,found,when).
nsubj(4,found,he).
det(4,unfortunate,the).
dep(4,found,unfortunate).
ccomp(4,found,swallow).
xcomp(4,swallow,lifeless).
case(4,ground,on).
det(4,ground,the).
nmod:on(4,lifeless,ground).
nsubj(4,said,he).
acl:relcl(4,ground,said).
root(5,ROOT,bird).
amod(5,bird,unhappy).
root(6,ROOT,done).
dobj(6,done,what).
aux(6,done,have).
nsubj(6,done,you).
root(7,ROOT,appearing).
mark(7,appearing,by).
advmod(7,appearing,thus).
case(7,springtime,before).
det(7,springtime,the).
nmod:before(7,killed,springtime).
nsubj(7,killed,you).
aux(7,killed,have).
neg(7,killed,not).
advmod(7,killed,only).
dep(7,appearing,killed).
dobj(7,killed,yourself).
cc(7,killed,but).
nsubj(7,wrought,you).
aux(7,wrought,have).
dep(7,appearing,wrought).
conj:but(7,killed,wrought).
nmod:poss(7,destruction,my).
dobj(7,wrought,destruction).
advmod(7,wrought,also).
have_wrought_also(7,you,my_destruction).
have_wrought(7,you,my_destruction).
