root(0,ROOT,know).
advmod(0,know,now).
nsubj(0,know,you).
aux(0,know,must).
mark(0,went,that).
det(0,mouse,a).
compound(0,mouse,town).
nsubj(0,went,mouse).
advmod(0,went,once).
case(0,time,upon).
det(0,time,a).
nmod:upon(0,once,time).
ccomp(0,know,went).
case(0,visit,on).
det(0,visit,a).
nmod:on(0,went,visit).
case(0,cousin,to).
nmod:poss(0,cousin,his).
nmod:to(0,went,cousin).
case(0,country,in).
det(0,country,the).
nmod:in(0,cousin,country).
once_went_on(0,town_mouse,visit).
went_on(0,town_mouse,visit).
went_to(0,town_mouse,his_cousin_in_country).
is_in(0,his_cousin,country).
once_went_to(0,town_mouse,his_cousin_in_country).
once_went_to(0,town_mouse,his_cousin).
went_to(0,town_mouse,his_cousin).
root(1,ROOT,rough).
nsubj(1,rough,he).
nsubj(1,ready,he).
cop(1,rough,was).
cc(1,rough,and).
conj:and(1,rough,ready).
det(1,cousin,this).
dep(1,rough,cousin).
cc(1,loved,but).
nsubj(1,loved,he).
nsubj(1,made,he).
ccomp(1,rough,loved).
nmod:poss(1,friend,his).
compound(1,friend,town).
dobj(1,loved,friend).
cc(1,loved,and).
ccomp(1,rough,made).
conj:and(1,loved,made).
nsubj(1,welcome,him).
advmod(1,welcome,heartily).
ccomp(1,made,welcome).
loved(1,he,his_town_friend).
was(1,he,rough).
root(2,ROOT,all).
nsubj(2,all,beans).
cc(2,beans,and).
compound(2,cheese,bacon).
conj:and(2,beans,cheese).
nsubj(2,all,cheese).
cc(2,cheese,and).
conj:and(2,beans,bread).
conj:and(2,cheese,bread).
cop(2,all,were).
nsubj(2,had,he).
nsubj:xsubj(2,offer,he).
acl:relcl(2,all,had).
mark(2,offer,to).
xcomp(2,had,offer).
cc(2,offered,but).
nsubj(2,offered,he).
ccomp(2,offer,offered).
dobj(2,offered,them).
advmod(2,offered,freely).
had(2,he,offer).
were_all(2,beans,he_had).
were_all(2,bacon_cheese,he_had).
offered(2,he,them).
offered_freely(2,he,them).
root(3,ROOT,turned).
det(3,mouse,the).
compound(3,mouse,town).
nsubj(3,turned,mouse).
nsubj(3,said,mouse).
advmod(3,turned,rather).
compound:prt(3,turned,up).
nmod:poss(3,nose,his).
amod(3,nose,long).
dobj(3,turned,nose).
case(3,fare,at).
det(3,fare,this).
compound(3,fare,country).
nmod:at(3,turned,fare).
cc(3,turned,and).
conj:and(3,turned,said).
turned_up_at(3,town_mouse,country_fare).
rather_turned_up(3,town_mouse,his_long_nose).
rather_turned_up_at(3,town_mouse,country_fare).
turned_up(3,town_mouse,his_nose).
rather_turned_up(3,town_mouse,his_nose).
turned_up(3,town_mouse,his_long_nose).
root(4,ROOT,understand).
nsubj(4,understand,i).
aux(4,understand,can).
neg(4,understand,not).
dobj(4,understand,cousin).
advmod(4,put,how).
nsubj(4,put,you).
aux(4,put,can).
dep(4,understand,put).
compound:prt(4,put,up).
case(4,food,with).
amod(4,food,such).
amod(4,food,poor).
nmod:with(4,put,food).
case(4,this,as).
nmod:as(4,food,this).
cc(4,put,but).
case(4,course,of).
nmod:of(4,expect,course).
nsubj(4,expect,you).
aux(4,expect,can).
neg(4,expect,not).
dep(4,understand,expect).
conj:but(4,put,expect).
dep(4,better,anything).
dobj(4,expect,better).
case(4,country,in).
det(4,country,the).
nmod:in(4,expect,country).
root(5,ROOT,come).
dobj(5,come,you).
mark(5,show,with).
nsubj(5,show,me).
cc(5,me,and).
conj:and(5,me,i).
nsubj(5,show,i).
aux(5,show,will).
advcl:with(5,come,show).
dobj(5,show,you).
nsubj:xsubj(5,live,you).
advmod(5,live,how).
mark(5,live,to).
xcomp(5,show,live).
will_show(5,i,you).
will_show(5,me,you).
root(6,ROOT,stood).
advmod(6,town,when).
nsubj(6,town,you).
aux(6,town,have).
cop(6,town,been).
case(6,town,in).
advcl:in(6,wonder,town).
det(6,week,a).
nmod:tmod(6,town,week).
nsubj(6,wonder,you).
aux(6,wonder,will).
dep(6,stood,wonder).
advmod(6,have,how).
nsubj(6,have,you).
aux(6,have,could).
advmod(6,have,ever).
ccomp(6,wonder,have).
det(6,life,a).
compound(6,life,country).
nsubj(6,stood,life).
have_in(6,you,when_have_town).
have_in(6,you,when_have_town_week).
have_in(6,you,have_town_week).
have_in(6,you,have_town).
root(7,ROOT,said).
neg(7,sooner,no).
advmod(7,said,sooner).
mark(7,done,than).
advcl:than(7,said,done).
det(7,mice,the).
nummod(7,mice,two).
nsubj(7,said,mice).
dep(7,mice,set).
compound:prt(7,set,off).
case(7,town,for).
det(7,town,the).
nmod:for(7,set,town).
cc(7,set,and).
dep(7,mice,arrived).
conj:and(7,set,arrived).
case(7,residence,at).
det(7,mouse,the).
compound(7,mouse,town).
nmod:poss(7,residence,mouse).
case(7,mouse,'s).
nmod:at(7,arrived,residence).
advmod(7,residence,late).
case(7,night,at).
nmod:at(7,arrived,night).
root(8,ROOT,want).
nsubj(8,want,you).
aux(8,want,will).
det(8,refreshment,some).
dobj(8,want,refreshment).
case(8,journey,after).
nmod:poss(8,journey,our).
amod(8,journey,long).
nmod:after(8,want,journey).
will_want_after(8,you,our_long_journey).
will_want(8,you,refreshment).
will_want_refreshment_after(8,you,our_journey).
will_want_refreshment_after(8,you,our_long_journey).
will_want_after(8,you,our_journey).
root(9,ROOT,said).
det(9,mouse,the).
amod(9,mouse,polite).
compound(9,mouse,town).
dobj(9,said,mouse).
cc(9,said,and).
conj:and(9,said,took).
nmod:poss(9,friend,his).
nsubj(9,said,friend).
nsubj(9,took,friend).
case(9,dining-room,into).
det(9,dining-room,the).
amod(9,dining-room,grand).
nmod:into(9,said,dining-room).
said_into(9,his_friend,grand_dining-room).
said_town_mouse_into(9,his_friend,grand_dining-room).
said_into(9,his_friend,dining-room).
said(9,his_friend,polite_town_mouse).
said(9,his_friend,town_mouse).
said_town_mouse_into(9,his_friend,dining-room).
root(10,ROOT,found).
advmod(10,found,there).
nsubj(10,found,they).
det(10,remains,the).
dobj(10,found,remains).
case(10,feast,of).
det(10,feast,a).
amod(10,feast,fine).
nmod:of(10,remains,feast).
cc(10,found,and).
advmod(10,eating,soon).
det(10,mice,the).
nummod(10,mice,two).
nsubj(10,eating,mice).
aux(10,eating,were).
conj:and(10,found,eating).
compound:prt(10,eating,up).
dobj(10,eating,jellies).
cc(10,jellies,and).
dobj(10,eating,cakes).
conj:and(10,jellies,cakes).
cc(10,jellies,and).
dobj(10,eating,all).
conj:and(10,jellies,all).
nsubj(10,nice,all).
ref(10,all,that).
cop(10,nice,was).
acl:relcl(10,all,nice).
were_eating_up(10,two_mice,cakes).
there_found(10,they,remains).
found(10,they,remains_of_feast).
soon_were_eating_up(10,two_mice,jellies).
found(10,they,remains).
were_eating_up(10,mice,cakes).
there_found(10,they,remains_of_fine_feast).
were_eating_up(10,mice,jellies).
soon_were_eating_up(10,mice,jellies).
found(10,they,remains_of_fine_feast).
soon_were_eating_up(10,mice,cakes).
were_eating_up(10,two_mice,jellies).
there_found(10,they,remains_of_feast).
soon_were_eating_up(10,two_mice,cakes).
root(11,ROOT,they).
dep(11,they,suddenly).
acl:relcl(11,they,heard).
xcomp(11,heard,growling).
cc(11,growling,and).
xcomp(11,heard,barking).
conj:and(11,growling,barking).
root(12,ROOT,that).
nsubj(12,that,what).
cop(12,that,is).
root(13,ROOT,said).
det(13,mouse,the).
compound(13,mouse,country).
nsubj(13,said,mouse).
root(14,ROOT,dogs).
nsubj(14,dogs,it).
cop(14,dogs,is).
advmod(14,dogs,only).
det(14,dogs,the).
case(14,house,of).
det(14,house,the).
nmod:of(14,dogs,house).
is(14,it,dogs).
is_only_dogs_of(14,it,house).
is(14,it,only_dogs).
is_dogs_of(14,it,house).
root(15,ROOT,answered).
det(15,other,the).
dobj(15,answered,other).
root(16,ROOT,only).
root(17,ROOT,said).
det(17,mouse,the).
compound(17,mouse,country).
nsubj(17,said,mouse).
root(18,ROOT,like).
nsubj(18,like,i).
aux(18,like,do).
neg(18,like,not).
mark(18,music,that).
dep(18,like,music).
case(18,dinner,at).
nmod:poss(18,dinner,my).
dep(18,music,dinner).
root(19,ROOT,moment).
advmod(19,moment,just).
case(19,moment,at).
det(19,moment,that).
det(19,door,the).
nsubj(19,flew,door).
acl:relcl(19,moment,flew).
xcomp(19,flew,open).
mark(19,came,in).
advcl:in(19,flew,came).
nummod(19,mastiffs,two).
amod(19,mastiffs,huge).
nsubj(19,had,mastiffs).
nsubj:xsubj(19,scamper,mastiffs).
nsubj:xsubj(19,run,mastiffs).
cc(19,mastiffs,and).
det(19,mice,the).
nummod(19,mice,two).
conj:and(19,mastiffs,mice).
nsubj(19,had,mice).
nsubj:xsubj(19,scamper,mice).
ccomp(19,came,had).
mark(19,scamper,to).
xcomp(19,had,scamper).
advmod(19,scamper,down).
cc(19,scamper,and).
xcomp(19,had,run).
conj:and(19,scamper,run).
compound:prt(19,run,off).
flew(19,door,open).
flew(19,door,came).
root(20,ROOT,cousin).
compound(20,cousin,good-bye).
root(21,ROOT,said).
det(21,mouse,the).
compound(21,mouse,country).
nsubj(21,said,mouse).
root(22,ROOT,what).
root(23,ROOT,going).
advmod(23,soon,so).
advmod(23,going,soon).
root(24,ROOT,said).
det(24,other,the).
nsubj(24,said,other).
root(25,ROOT,yes).
root(26,ROOT,replied).
nsubj(26,replied,he).
root(27,ROOT,better).
nmod:npmod(27,better,beans).
cc(27,beans,and).
nmod:npmod(27,better,bacon).
conj:and(27,beans,bacon).
case(27,peace,in).
nmod:in(27,bacon,peace).
case(27,cakes,than).
nmod:than(27,better,cakes).
cc(27,cakes,and).
nmod:than(27,better,ale).
conj:and(27,cakes,ale).
case(27,fear,in).
nmod:in(27,better,fear).
is_in(27,bacon,peace).
