root(0,ROOT,made).
det(0,gods,the).
nsubj(0,made,gods).
case(0,legend,according).
mwe(0,according,to).
det(0,legend,an).
amod(0,legend,ancient).
nmod:according_to(0,gods,legend).
dobj(0,made,choice).
case(0,trees,of).
amod(0,trees,certain).
nmod:of(0,choice,trees).
mark(0,protection,to).
cop(0,protection,be).
case(0,protection,under).
nmod:poss(0,protection,their).
amod(0,protection,special).
advcl:under(0,made,protection).
made(0,gods,choice_of_trees).
made_choice_under(0,gods,their_special_protection).
be_under(0,gods,their_special_protection).
made(0,gods,choice_of_certain_trees).
be_under(0,gods,their_protection).
made_choice_under(0,gods,their_protection).
made(0,gods,choice).
root(1,ROOT,chose).
nsubj(1,chose,jupiter).
det(1,oak,the).
nsubj(1,venus,oak).
nsubj(1,hercules,oak).
ccomp(1,chose,venus).
det(1,apollo,the).
amod(1,apollo,myrtle).
dobj(1,venus,apollo).
det(1,laurel,the).
nsubj(1,cybele,laurel).
acl:relcl(1,apollo,cybele).
nsubj(1,pine,the).
ccomp(1,cybele,pine).
cc(1,venus,and).
ccomp(1,chose,hercules).
conj:and(1,venus,hercules).
det(1,poplar,the).
dobj(1,hercules,poplar).
hercules(1,oak,poplar).
root(2,ROOT,inquired).
nsubj(2,inquired,minerva).
acl(2,minerva,wondering).
advmod(2,preferred,why).
nsubj(2,preferred,they).
aux(2,preferred,had).
ccomp(2,wondering,preferred).
dobj(2,preferred,trees).
neg(2,yielding,not).
xcomp(2,preferred,yielding).
dobj(2,yielding,fruit).
det(2,reason,the).
dobj(2,inquired,reason).
case(2,choice,for).
nmod:poss(2,choice,their).
nmod:for(2,inquired,choice).
inquired_reason_for(2,minerva,their_choice).
root(3,ROOT,replied).
nsubj(3,replied,jupiter).
root(4,ROOT,is).
nsubj(4,is,it).
mark(4,seem,lest).
nsubj(4,seem,we).
nsubj:xsubj(4,covet,we).
aux(4,seem,should).
advcl:lest(4,is,seem).
mark(4,covet,to).
xcomp(4,seem,covet).
det(4,honor,the).
dobj(4,covet,honor).
case(4,fruit,for).
det(4,fruit,the).
nmod:for(4,honor,fruit).
is(4,it,we_should_seem).
covet(4,we,honor).
covet(4,we,honor_for_fruit).
root(5,ROOT,said).
cc(5,said,but).
dobj(5,said,minerva).
root(6,ROOT,let).
nsubj(6,say,anyone).
ccomp(6,let,say).
dobj(6,olive,what).
nsubj(6,olive,he).
aux(6,olive,will).
det(6,olive,the).
ccomp(6,say,olive).
cop(6,dear,is).
advmod(6,dear,more).
acl:relcl(6,olive,dear).
case(6,me,to).
nmod:to(6,olive,me).
case(6,fruit,on).
mwe(6,on,account).
mwe(6,on,of).
nmod:poss(6,fruit,its).
nmod:on_account_of(6,olive,fruit).
root(7,ROOT,said).
advmod(7,said,then).
nsubj(7,said,jupiter).
root(8,ROOT,daughter).
nmod:poss(8,daughter,my).
nsubjpass(8,called,you).
auxpass(8,called,are).
advmod(8,called,rightly).
acl:relcl(8,daughter,called).
xcomp(8,called,wise).
are(8,you,called).
are_called(8,you,wise).
are_rightly_called(8,you,wise).
are(8,you,rightly_called).
root(9,ROOT,useful).
mark(9,useful,for).
mark(9,useful,unless).
dobj(9,do,what).
nsubj(9,do,we).
csubj(9,useful,do).
cop(9,useful,is).
det(9,glory,the).
nsubj(9,vain,glory).
case(9,it,of).
nmod:of(9,glory,it).
cop(9,vain,is).
ccomp(9,useful,vain).
is(9,glory,vain).
