root(0,ROOT,escaped).
det(0,slave,a).
nsubj(0,escaped,slave).
nsubj(0,fled,slave).
acl(0,slave,named).
dobj(0,named,androcles).
advmod(0,escaped,once).
case(0,master,from).
nmod:poss(0,master,his).
nmod:from(0,escaped,master).
cc(0,escaped,and).
conj:and(0,escaped,fled).
case(0,forest,to).
det(0,forest,the).
nmod:to(0,fled,forest).
escaped_from(0,slave,his_master).
once_escaped_from(0,slave,his_master).
fled_to(0,slave,forest).
named(0,slave,androcles).
root(1,ROOT,wandering).
mark(1,wandering,as).
nsubj(1,wandering,he).
aux(1,wandering,was).
case(1,there,about).
nmod:about(1,wandering,there).
nsubj(1,came,he).
acl:relcl(1,there,came).
case(1,lion,upon).
det(1,lion,a).
nmod:upon(1,came,lion).
acl(1,lion,lying).
mark(1,moaning,down).
advcl:down(1,lying,moaning).
cc(1,moaning,and).
advcl:down(1,lying,groaning).
conj:and(1,moaning,groaning).
root(2,ROOT,turned).
case(2,first,at).
advcl:at(2,turned,first).
nsubj(2,turned,he).
mark(2,flee,to).
dep(2,turned,flee).
cc(2,flee,but).
dep(2,turned,finding).
conj:but(2,flee,finding).
mark(2,pursue,that).
det(2,lion,the).
nsubj(2,pursue,lion).
aux(2,pursue,did).
neg(2,pursue,not).
ccomp(2,finding,pursue).
dobj(2,pursue,him).
nsubj(2,turned,he).
nsubj(2,went,he).
dep(2,pursue,turned).
advmod(2,turned,back).
cc(2,turned,and).
dep(2,pursue,went).
conj:and(2,turned,went).
compound:prt(2,went,up).
case(2,him,to).
nmod:to(2,went,him).
went_up_to(2,he,him).
turned_at(2,he,first).
root(3,ROOT,came).
mark(3,came,as).
nsubj(3,came,he).
nsubj(3,causing,he).
mark(3,put,near).
det(3,lion,the).
nsubj(3,put,lion).
advcl:near(3,came,put).
compound:prt(3,put,out).
nmod:poss(3,paw,his).
dobj(3,put,paw).
nsubj(3,swollen,paw).
nsubj(3,bleeding,paw).
ref(3,paw,which).
cop(3,swollen,was).
dep(3,swollen,all).
acl:relcl(3,paw,swollen).
cc(3,swollen,and).
acl:relcl(3,paw,bleeding).
conj:and(3,swollen,bleeding).
cc(3,put,and).
nsubj(3,found,androcles).
advcl:near(3,came,found).
conj:and(3,put,found).
mark(3,got,that).
det(3,thorn,a).
amod(3,thorn,huge).
nsubj(3,got,thorn).
aux(3,got,had).
ccomp(3,found,got).
case(3,it,into).
nmod:into(3,got,it).
cc(3,came,and).
aux(3,causing,was).
conj:and(3,came,causing).
det:predet(3,pain,all).
det(3,pain,the).
dobj(3,causing,pain).
got_into(3,thorn,it).
got_into(3,huge_thorn,it).
causing(3,he,pain).
root(4,ROOT,pulled).
nsubj(4,pulled,he).
nsubj(4,bound,he).
compound:prt(4,pulled,out).
det(4,thorn,the).
dobj(4,pulled,thorn).
cc(4,pulled,and).
conj:and(4,pulled,bound).
compound:prt(4,bound,up).
det(4,paw,the).
dobj(4,bound,paw).
case(4,lion,of).
det(4,lion,the).
nmod:of(4,paw,lion).
nsubj(4,able,lion).
nsubj:xsubj(4,rise,lion).
nsubj:xsubj(4,lick,lion).
ref(4,lion,who).
cop(4,able,was).
advmod(4,able,soon).
acl:relcl(4,lion,able).
mark(4,rise,to).
xcomp(4,able,rise).
cc(4,rise,and).
xcomp(4,able,lick).
conj:and(4,rise,lick).
det(4,hand,the).
dobj(4,rise,hand).
case(4,androcles,of).
nmod:of(4,hand,androcles).
case(4,dog,like).
det(4,dog,a).
nmod:like(4,rise,dog).
pulled_out(4,he,thorn).
bound_up(4,he,paw).
root(5,ROOT,lion).
dep(5,lion,then).
det(5,lion,the).
ccomp(5,lion,took).
dobj(5,took,androcles).
case(5,cave,to).
nmod:poss(5,cave,his).
nmod:to(5,took,cave).
cc(5,cave,and).
det(5,day,every).
nmod:to(5,took,day).
conj:and(5,cave,day).
acl(5,day,used).
mark(5,bring,to).
xcomp(5,used,bring).
iobj(5,bring,him).
dobj(5,bring,meat).
mark(5,live,from).
nsubj(5,live,which).
mark(5,live,to).
acl:to(5,meat,live).
root(6,ROOT,but).
advmod(6,afterwards,shortly).
nmod(6,captured,afterwards).
dep(6,captured,both).
nsubjpass(6,captured,androcles).
cc(6,androcles,and).
det(6,lion,the).
conj:and(6,androcles,lion).
nsubjpass(6,captured,lion).
auxpass(6,captured,were).
dep(6,but,captured).
cc(6,captured,and).
det(6,slave,the).
nsubjpass(6,sentenced,slave).
nsubjpass:xsubj(6,thrown,slave).
auxpass(6,sentenced,was).
dep(6,but,sentenced).
conj:and(6,captured,sentenced).
mark(6,thrown,to).
auxpass(6,thrown,be).
xcomp(6,sentenced,thrown).
case(6,lion,to).
det(6,lion,the).
nmod:to(6,thrown,lion).
mark(6,kept,after).
det(6,latter,the).
nsubjpass(6,kept,latter).
aux(6,kept,had).
auxpass(6,kept,been).
advcl:after(6,thrown,kept).
case(6,food,without).
nmod:without(6,kept,food).
case(6,days,for).
amod(6,days,several).
nmod:for(6,food,days).
was_sentenced(6,lion,thrown).
had(6,latter,had_kept_without_food).
had(6,latter,had_kept_without_food_for_days).
had(6,latter,had_kept).
had(6,latter,had_kept_without_food_for_several_days).
was_sentenced(6,lion,thrown_to_lion).
was(6,lion,sentenced).
root(7,ROOT,came).
det(7,emperor,the).
nsubj(7,came,emperor).
nsubj:xsubj(7,see,emperor).
cc(7,emperor,and).
det:predet(7,court,all).
nmod:poss(7,court,his).
conj:and(7,emperor,court).
nsubj(7,came,court).
nsubj:xsubj(7,see,court).
mark(7,see,to).
xcomp(7,came,see).
det(7,spectacle,the).
nsubjpass(7,led,spectacle).
cc(7,spectacle,and).
conj:and(7,spectacle,androcles).
nsubjpass(7,led,androcles).
auxpass(7,led,was).
ccomp(7,see,led).
compound:prt(7,led,out).
case(7,middle,into).
det(7,middle,the).
nmod:into(7,led,middle).
case(7,arena,of).
det(7,arena,the).
nmod:of(7,middle,arena).
came(7,court,see).
came(7,his_court,see).
root(8,ROOT,lion).
dep(8,lion,soon).
det(8,lion,the).
ccomp(8,lion,was).
ccomp(8,was,let).
advmod(8,let,loose).
case(8,den,from).
nmod:poss(8,den,his).
nmod:from(8,let,den).
cc(8,let,and).
ccomp(8,was,rushed).
conj:and(8,let,rushed).
xcomp(8,rushed,bounding).
cc(8,bounding,and).
xcomp(8,rushed,roaring).
conj:and(8,bounding,roaring).
case(8,victim,towards).
nmod:poss(8,victim,his).
nmod:towards(8,bounding,victim).
root(9,ROOT,soon).
cc(9,soon,but).
advmod(9,soon,as).
mark(9,came,as).
nsubj(9,came,he).
nsubj(9,licked,he).
dep(9,soon,came).
case(9,androcles,near).
mwe(9,near,to).
nmod:near_to(9,came,androcles).
nsubj(9,recognised,he).
nsubj(9,fawned,he).
acl:relcl(9,androcles,recognised).
nmod:poss(9,friend,his).
dobj(9,recognised,friend).
cc(9,recognised,and).
acl:relcl(9,androcles,fawned).
conj:and(9,recognised,fawned).
case(9,him,upon).
nmod:upon(9,fawned,him).
cc(9,came,and).
dep(9,soon,licked).
conj:and(9,came,licked).
nmod:poss(9,hands,his).
dobj(9,licked,hands).
case(9,dog,like).
det(9,dog,a).
amod(9,dog,friendly).
nmod:like(9,licked,dog).
fawned_upon(9,he,him).
recognised(9,he,his_friend).
licked(9,he,his_hands).
root(10,ROOT,surprised).
det(10,emperor,the).
nsubj(10,surprised,emperor).
case(10,this,at).
nmod:at(10,surprised,this).
acl(10,this,summoned).
dobj(10,summoned,androcles).
case(10,him,to).
nmod:to(10,summoned,him).
nsubj(10,told,him).
ref(10,him,who).
acl:relcl(10,him,told).
nsubj(10,story,him).
det(10,story,the).
amod(10,story,whole).
xcomp(10,told,story).
surprised_at(10,emperor,this).
root(11,ROOT,pardoned).
nsubjpass(11,pardoned,whereupon).
nsubjpass(11,freed,whereupon).
det(11,slave,the).
dep(11,whereupon,slave).
auxpass(11,pardoned,was).
cc(11,pardoned,and).
conj:and(11,pardoned,freed).
cc(11,pardoned,and).
det(11,lion,the).
conj:and(11,pardoned,lion).
dep(11,loose,let).
advmod(11,lion,loose).
case(11,forest,to).
nmod:poss(11,forest,his).
amod(11,forest,native).
nmod:to(11,lion,forest).
lion_to(11,whereupon,his_native_forest).
lion_to(11,whereupon,his_forest).
lion_loose_to(11,whereupon,his_native_forest).
lion_loose_to(11,whereupon,his_forest).
was(11,whereupon,pardoned).
