root(0,ROOT,came).
nummod(0,neighbours,two).
nsubj(0,came,neighbours).
nsubj(0,prayed,neighbours).
case(0,jupiter,before).
nmod:before(0,came,jupiter).
cc(0,came,and).
conj:and(0,came,prayed).
dobj(0,prayed,him).
nsubj:xsubj(0,grant,him).
mark(0,grant,to).
xcomp(0,prayed,grant).
nmod:poss(0,hearts,their).
nmod:poss(0,desire,hearts).
case(0,hearts,').
dobj(0,grant,desire).
grant(0,him,their_hearts__desire).
prayed(0,two_neighbours,him).
came_before(0,two_neighbours,jupiter).
came_before(0,neighbours,jupiter).
prayed(0,neighbours,him).
root(1,ROOT,full).
dep(1,one,now).
det(1,one,the).
dep(1,full,one).
cop(1,full,was).
case(1,avarice,of).
nmod:of(1,full,avarice).
cc(1,avarice,and).
det(1,other,the).
nmod:of(1,full,other).
conj:and(1,avarice,other).
acl(1,other,eaten).
compound:prt(1,eaten,up).
case(1,envy,with).
nmod:with(1,eaten,envy).
root(2,ROOT,so).
mark(2,punish,to).
xcomp(2,so,punish).
nsubj(2,jupiter,them).
det(2,jupiter,both).
xcomp(2,punish,jupiter).
acl(2,jupiter,granted).
mark(2,have,that).
nsubj(2,have,each).
aux(2,have,might).
ccomp(2,granted,have).
dobj(2,wished,whatever).
nsubj(2,wished,he).
nsubj(2,wished,he).
ccomp(2,have,wished).
ccomp(2,have,wished).
conj:only(2,wished,wished).
case(2,himself,for).
nmod:for(2,wished,himself).
cc(2,only,but).
cc(2,wished,only).
case(2,condition,on).
nmod:on(2,wished,condition).
mark(2,had,that).
nmod:poss(2,neighbour,his).
nsubj(2,had,neighbour).
ccomp(2,wished,had).
advmod(2,much,twice).
advmod(2,much,as).
dobj(2,had,much).
had(2,his_neighbour,twice_as_much).
root(3,ROOT,prayed).
det(3,man,the).
amod(3,man,avaricious).
nsubj(3,prayed,man).
nsubj:xsubj(3,have,man).
mark(3,have,to).
xcomp(3,prayed,have).
det(3,room,a).
dobj(3,have,room).
case(3,gold,full).
case(3,gold,of).
nmod:of(3,room,gold).
have(3,man,room_full_of_gold).
have(3,avaricious_man,room_full_of_gold).
have(3,man,room).
have(3,avaricious_man,room).
root(4,ROOT,said).
neg(4,sooner,no).
advmod(4,said,sooner).
mark(4,done,than).
advcl:than(4,said,done).
root(5,ROOT,turned).
cc(5,turned,but).
det:predet(5,joy,all).
nmod:poss(5,joy,his).
nsubjpass(5,turned,joy).
auxpass(5,turned,was).
case(5,grief,to).
nmod:to(5,turned,grief).
advmod(5,found,when).
nsubj(5,found,he).
advcl(5,turned,found).
mark(5,had,that).
nmod:poss(5,neighbour,his).
nsubj(5,had,neighbour).
ccomp(5,found,had).
nummod(5,rooms,two).
dobj(5,had,rooms).
case(5,metal,full).
case(5,metal,of).
det(5,metal,the).
amod(5,metal,precious).
nmod:of(5,rooms,metal).
had(5,his_neighbour,two_rooms_full_of_precious_metal).
was(5,joy,turned).
had(5,his_neighbour,two_rooms_full_of_metal).
had(5,his_neighbour,two_rooms).
was(5,his_joy,turned).
was_turned_to(5,his_joy,grief).
was_turned_to(5,joy,grief).
root(6,ROOT,came).
advmod(6,came,then).
det(6,turn,the).
dobj(6,came,turn).
case(6,man,of).
det(6,man,the).
amod(6,man,envious).
nmod:of(6,turn,man).
nsubj(6,bear,who).
nsubj:xsubj(6,think,who).
aux(6,bear,could).
neg(6,bear,not).
dep(6,came,bear).
mark(6,think,to).
xcomp(6,bear,think).
mark(6,had,that).
nmod:poss(6,neighbour,his).
nsubj(6,had,neighbour).
ccomp(6,think,had).
det(6,joy,any).
dobj(6,had,joy).
case(6,all,at).
nmod:at(6,joy,all).
root(7,ROOT,so).
nsubj(7,prayed,he).
ccomp(7,so,prayed).
mark(7,have,that).
nsubj(7,have,he).
aux(7,have,might).
ccomp(7,prayed,have).
dobj(7,have,one).
nsubj(7,means,one).
case(7,eyes,of).
nmod:poss(7,eyes,his).
amod(7,eyes,own).
nmod:of(7,one,eyes).
acl:relcl(7,one,put).
compound:prt(7,put,out).
mark(7,means,by).
ref(7,one,which).
advcl:by(7,put,means).
nmod:poss(7,companion,his).
nsubj(7,become,companion).
aux(7,become,would).
ccomp(7,means,become).
advmod(7,blind,totally).
xcomp(7,become,blind).
