root(0,ROOT,came).
nsubj(0,came,hercules).
advmod(0,journeying,once).
acl(0,hercules,journeying).
case(0,roadway,along).
det(0,roadway,a).
amod(0,roadway,narrow).
nmod:along(0,journeying,roadway).
case(0,animal,across).
det(0,animal,a).
amod(0,animal,strange-looking).
nmod:across(0,came,animal).
nsubj(0,reared,animal).
nsubj(0,threatened,animal).
ref(0,animal,that).
acl:relcl(0,animal,reared).
nmod:poss(0,head,its).
dobj(0,reared,head).
cc(0,reared,and).
acl:relcl(0,animal,threatened).
conj:and(0,reared,threatened).
dobj(0,threatened,him).
once_journeying_along(0,hercules,narrow_roadway).
once_journeying_along(0,hercules,roadway).
journeying_along(0,hercules,narrow_roadway).
journeying_along(0,hercules,roadway).
threatened(0,its_head,him).
root(1,ROOT,daunted).
nsubj(1,daunted,nothing).
det(1,hero,the).
nsubj(1,gave,hero).
nsubj(1,thought,hero).
nsubj:xsubj(1,gone,hero).
ccomp(1,daunted,gave).
iobj(1,gave,him).
det(1,blows,a).
amod(1,blows,few).
amod(1,blows,lusty).
dobj(1,gave,blows).
case(1,club,with).
nmod:poss(1,club,his).
nmod:with(1,blows,club).
cc(1,gave,and).
ccomp(1,daunted,thought).
conj:and(1,gave,thought).
mark(1,gone,to).
aux(1,gone,have).
xcomp(1,thought,gone).
case(1,way,on).
nmod:poss(1,way,his).
nmod:on(1,gone,way).
is_with(1,few_lusty_blows,his_club).
thought(1,hero,have_gone).
few_lusty_blows_with(1,hero,his_club).
gave(1,hero,few_blows_with_his_club).
few_blows_with(1,hero,his_club).
gave(1,hero,few_lusty_blows).
gave(1,hero,lusty_blows_with_his_club).
gave(1,hero,blows).
lusty_blows_with(1,hero,his_club).
gave(1,hero,blows_with_his_club).
gave(1,hero,few_blows).
gave(1,hero,lusty_blows).
gave(1,hero,him).
blows_with(1,hero,his_club).
gave(1,hero,few_lusty_blows_with_his_club).
thought(1,hero,have_gone_on_his_way).
root(2,ROOT,was).
det(2,monster,the).
nsubj(2,was,monster).
advmod(2,much,however).
amod(2,monster,much).
case(2,astonishment,to).
det(2,astonishment,the).
nmod:to(2,much,astonishment).
case(2,hercules,of).
nmod:of(2,astonishment,hercules).
advmod(2,was,now).
nummod(2,times,three).
nmod:npmod(2,now,times).
case(2,big,as).
advcl:as(2,now,big).
mark(2,was,as).
nsubj(2,was,it).
advcl:as(2,now,was).
advmod(2,and,before).
advmod(2,was,and).
case(2,aspect,of).
det(2,aspect,a).
advmod(2,threatening,still).
advmod(2,threatening,more).
amod(2,aspect,threatening).
conj(2,and,aspect).
however_much_to(2,monster,astonishment).
however_much_to(2,monster,astonishment_of_hercules).
much_to(2,monster,astonishment_of_hercules).
much_to(2,monster,astonishment).
root(3,ROOT,redoubled).
nsubj(3,redoubled,he).
nsubj(3,laid,he).
advmod(3,redoubled,thereupon).
nmod:poss(3,blows,his).
dobj(3,redoubled,blows).
cc(3,redoubled,and).
conj:and(3,redoubled,laid).
case(3,him,about).
nmod:about(3,laid,him).
advmod(3,laid,fast).
cc(3,fast,and).
advmod(3,laid,furiously).
conj:and(3,fast,furiously).
laid_fast_and_furiously_about(3,he,him).
redoubled(3,he,his_blows).
laid_about(3,he,him).
thereupon_redoubled(3,he,his_blows).
laid_fast_about(3,he,him).
root(4,ROOT,grew).
case(4,strokes,but).
det(4,strokes,the).
amod(4,strokes,harder).
cc(4,harder,and).
conj:and(4,harder,quicker).
amod(4,strokes,quicker).
det(4,strokes,the).
nmod:but(4,grew,strokes).
case(4,club,of).
det(4,club,the).
nmod:of(4,strokes,club).
dep(4,bigger,the).
amod(4,club,bigger).
cc(4,bigger,and).
advmod(4,frightful,more).
amod(4,club,frightful).
conj:and(4,bigger,frightful).
det(4,monster,the).
nsubj(4,grew,monster).
cc(4,monster,and).
nsubj(4,grew,now).
conj:and(4,monster,now).
advmod(4,filled,completely).
acl(4,now,filled).
case(4,road,up).
det(4,road,the).
nmod:up(4,filled,road).
grew_but(4,monster,strokes_of_club).
grew_but(4,monster,harder_strokes_of_club).
grew_but(4,now,strokes_of_club).
grew_but(4,now,strokes_of_club_bigger).
grew_but(4,now,harder_strokes_of_club_bigger).
grew_but(4,now,harder_strokes_of_club).
grew_but(4,monster,strokes).
grew_but(4,monster,harder_strokes_of_club_bigger).
grew_but(4,now,strokes).
grew_but(4,monster,harder_strokes).
grew_but(4,now,harder_strokes).
grew_but(4,monster,strokes_of_club_bigger).
root(5,ROOT,pallas).
advmod(5,appeared,then).
dep(5,pallas,appeared).
case(5,scene,upon).
det(5,scene,the).
nmod:upon(5,appeared,scene).
root(6,ROOT,stop).
dobj(6,stop,hercules).
root(7,ROOT,said).
nsubj(7,said,she).
root(8,ROOT,cease).
nmod:poss(8,blows,your).
dobj(8,cease,blows).
root(9,ROOT,strife).
det(9,monster,the).
nmod:poss(9,name,monster).
case(9,monster,'s).
nsubj(9,strife,name).
cop(9,strife,is).
has(9,monster,name).
is(9,monster_s_name,strife).
root(10,ROOT,let).
dep(10,alone,it).
dep(10,let,alone).
cc(10,alone,and).
nsubj(10,become,it).
aux(10,become,will).
advmod(10,become,soon).
dep(10,let,become).
conj:and(10,alone,become).
advmod(10,little,as).
xcomp(10,become,little).
mark(10,first,as).
nsubj(10,first,it).
cop(10,first,was).
case(10,first,at).
advcl:at(10,become,first).
