root(0,ROOT,driving).
det(0,carter,a).
nsubj(0,driving,carter).
aux(0,driving,was).
det(0,wagon,a).
dobj(0,driving,wagon).
case(0,lane,along).
det(0,lane,a).
compound(0,lane,country).
nmod:along(0,wagon,lane).
advmod(0,sank,when).
det(0,wheels,the).
nsubj(0,sank,wheels).
advcl(0,driving,sank).
advmod(0,deep,down).
advmod(0,sank,deep).
case(0,rut,into).
det(0,rut,a).
nmod:into(0,sank,rut).
sank_into(0,wheels,rut).
was_driving(0,carter,wagon_along_country_lane).
sank_deep_into(0,wheels,rut).
sank_down_deep_into(0,wheels,rut).
was_driving(0,carter,wagon).
root(1,ROOT,stupefied).
det(1,driver,the).
amod(1,driver,rustic).
nsubj(1,stupefied,driver).
cc(1,stood,and).
nsubj(1,stood,aghast).
nsubj(1,did,aghast).
dep(1,stupefied,stood).
xcomp(1,stood,looking).
case(1,wagon,at).
det(1,wagon,the).
nmod:at(1,looking,wagon).
cc(1,stood,and).
dep(1,stupefied,did).
conj:and(1,stood,did).
dobj(1,did,nothing).
cc(1,stood,but).
nsubj(1,cries,utter).
nsubj:xsubj(1,come,utter).
nsubj:xsubj(1,help,utter).
advmod(1,cries,loud).
dep(1,stupefied,cries).
conj:but(1,stood,cries).
case(1,hercules,to).
nmod:to(1,cries,hercules).
mark(1,come,to).
xcomp(1,cries,come).
cc(1,come,and).
xcomp(1,cries,help).
conj:and(1,come,help).
dobj(1,come,him).
did(1,aghast,nothing).
cries(1,utter,come).
come(1,utter,him).
loud_cries_to(1,utter,hercules).
looking_at(1,aghast,wagon).
loud_cries(1,utter,come).
cries_to(1,utter,hercules).
root(2,ROOT,said).
nsubj(2,said,hercules).
nsubj(2,addressed,hercules).
nsubj(2,is,it).
acl:relcl(2,hercules,is).
dep(2,said,appeared).
cc(2,said,and).
advmod(2,addressed,thus).
conj:and(2,said,addressed).
dobj(2,addressed,him).
root(3,ROOT,put).
nmod:poss(3,shoulders,your).
dobj(3,put,shoulders).
case(3,wheels,to).
det(3,wheels,the).
nmod:to(3,put,wheels).
nmod:poss(3,man,my).
nsubj(3,put,man).
put(3,my_man,your_shoulders).
root(4,ROOT,pray).
nsubj(4,pray,goad).
case(4,bullocks,on).
nmod:poss(4,bullocks,your).
nmod:on(4,goad,bullocks).
cc(4,bullocks,and).
neg(4,pray,never).
advmod(4,pray,more).
nmod:on(4,goad,pray).
conj:and(4,bullocks,pray).
case(4,me,to).
nmod:to(4,pray,me).
case(4,help,for).
nmod:for(4,pray,help).
mark(4,done,until).
nsubj(4,done,you).
aux(4,done,have).
advcl:until(4,pray,done).
nmod:poss(4,best,your).
dobj(4,done,best).
mark(4,help,to).
advcl:to(4,done,help).
dobj(4,help,yourself).
cc(4,help,or).
advcl:to(4,done,depend).
conj:or(4,help,depend).
case(4,it,upon).
nmod:upon(4,depend,it).
dobj(4,help,you).
aux(4,pray,will).
advmod(4,pray,henceforth).
case(4,vain,in).
nmod:in(4,pray,vain).
will_henceforth_pray_in(4,goad,vain).
will_pray_in(4,goad,vain).
root(5,ROOT,help).
nsubj(5,help,self-help).
cop(5,help,is).
det(5,help,the).
amod(5,help,best).
is(5,self-help,help).
is(5,self-help,best_help).
