root(0,ROOT,driving).
det(0,waggoner,a).
nsubj(0,driving,waggoner).
aux(0,driving,was).
advmod(0,driving,once).
det(0,load,a).
amod(0,load,heavy).
dobj(0,driving,load).
case(0,way,along).
det(0,way,a).
advmod(0,muddy,very).
amod(0,way,muddy).
nmod:along(0,load,way).
was_once_driving(0,waggoner,heavy_load_along_very_muddy_way).
was_driving(0,waggoner,heavy_load).
was_driving(0,waggoner,load_along_way).
was_once_driving(0,waggoner,load_along_very_muddy_way).
was_once_driving(0,waggoner,heavy_load).
was_driving(0,waggoner,load).
was_once_driving(0,waggoner,heavy_load_along_way).
was_once_driving(0,waggoner,load_along_way).
was_once_driving(0,waggoner,load).
was_driving(0,waggoner,heavy_load_along_very_muddy_way).
was_driving(0,waggoner,load_along_muddy_way).
was_driving(0,waggoner,heavy_load_along_way).
was_driving(0,waggoner,heavy_load_along_muddy_way).
was_driving(0,waggoner,load_along_very_muddy_way).
was_once_driving(0,waggoner,load_along_muddy_way).
was_once_driving(0,waggoner,heavy_load_along_muddy_way).
root(1,ROOT,came).
case(1,last,at).
nmod:at(1,came,last).
nsubj(1,came,he).
case(1,part,to).
det(1,part,a).
nmod:to(1,came,part).
case(1,road,of).
det(1,road,the).
nmod:of(1,part,road).
advmod(1,sank,where).
det(1,wheels,the).
nsubj(1,sank,wheels).
advcl(1,came,sank).
dobj(1,sank,half-way).
case(1,mire,into).
det(1,mire,the).
nmod:into(1,sank,mire).
cc(1,sank,and).
det(1,more,the).
dep(1,pulled,more).
det(1,horses,the).
nsubj(1,pulled,horses).
advcl(1,came,pulled).
conj:and(1,sank,pulled).
det(1,deeper,the).
nsubj(1,sank,deeper).
ccomp(1,pulled,sank).
det(1,wheels,the).
dobj(1,sank,wheels).
came_to(1,he,part_of_road).
sank_half-way_into(1,wheels,mire).
came_at(1,he,last).
sank(1,deeper,wheels).
came_to(1,he,part).
sank(1,wheels,half-way).
root(2,ROOT,threw).
mark(2,threw,so).
det(2,waggoner,the).
nsubj(2,threw,waggoner).
nsubj(2,knelt,waggoner).
compound:prt(2,threw,down).
nmod:poss(2,whip,his).
dobj(2,threw,whip).
cc(2,threw,and).
conj:and(2,threw,knelt).
advmod(2,knelt,down).
cc(2,knelt,and).
conj:and(2,threw,prayed).
conj:and(2,knelt,prayed).
mark(2,hercules,to).
xcomp(2,prayed,hercules).
det(2,strong,the).
dobj(2,hercules,strong).
threw_down(2,waggoner,his_whip).
root(3,ROOT,help).
compound(3,hercules,o).
nsubj(3,help,hercules).
dobj(3,help,me).
case(3,hour,in).
det(3,hour,this).
nmod:poss(3,hour,my).
nmod:in(3,help,hour).
case(3,distress,of).
nmod:of(3,hour,distress).
help(3,o_hercules,me).
root(4,ROOT,he).
case(4,he,quoth).
root(5,ROOT,appeared).
cc(5,appeared,but).
nsubj(5,appeared,hercules).
nsubj(5,said,hercules).
case(5,him,to).
nmod:to(5,appeared,him).
cc(5,appeared,and).
conj:and(5,appeared,said).
appeared_to(5,hercules,him).
root(6,ROOT,do).
compound(6,man,tut).
nsubj(6,do,man).
neg(6,do,n't).
dobj(6,do,sprawl).
advmod(6,do,there).
root(7,ROOT,get).
compound:prt(7,get,up).
cc(7,get,and).
conj:and(7,get,put).
nmod:poss(7,shoulder,your).
dobj(7,put,shoulder).
case(7,wheel,to).
det(7,wheel,the).
nmod:to(7,put,wheel).
