root(0,ROOT,issued).
nsubj(0,issued,jupiter).
nsubj(0,promised,jupiter).
det(0,proclamation,a).
dobj(0,issued,proclamation).
case(0,beasts,to).
det:predet(0,beasts,all).
det(0,beasts,the).
nmod:to(0,issued,beasts).
case(0,forest,of).
det(0,forest,the).
nmod:of(0,beasts,forest).
cc(0,issued,and).
conj:and(0,issued,promised).
det(0,reward,a).
amod(0,reward,royal).
dobj(0,promised,reward).
case(0,one,to).
det(0,one,the).
nmod:to(0,promised,one).
nmod:poss(0,offspring,one).
ref(0,one,whose).
nsubjpass(0,deemed,offspring).
aux(0,deemed,should).
auxpass(0,deemed,be).
acl:relcl(0,one,deemed).
det(0,handsomest,the).
dobj(0,deemed,handsomest).
promised(0,jupiter,reward).
promised(0,jupiter,royal_reward).
issued_proclamation_to(0,jupiter,beasts_of_forest).
root(1,ROOT,came).
det(1,monkey,the).
nsubj(1,came,monkey).
nsubj(1,presented,monkey).
case(1,rest,with).
det(1,rest,the).
nmod:with(1,came,rest).
cc(1,came,and).
conj:and(1,came,presented).
case(1,tenderness,with).
dep(1,tenderness,all).
det(1,mother,a).
nmod:poss(1,tenderness,mother).
case(1,mother,'s).
nmod:with(1,presented,tenderness).
det(1,monkey,a).
amod(1,monkey,flat-nosed).
amod(1,monkey,hairless).
amod(1,monkey,ill-featured).
amod(1,monkey,young).
dep(1,tenderness,monkey).
case(1,candidate,as).
det(1,candidate,a).
nmod:as(1,presented,candidate).
case(1,reward,for).
det(1,reward,the).
amod(1,reward,promised).
nmod:for(1,candidate,reward).
presented_with(1,monkey,mother_s_tenderness).
presented_as(1,monkey,candidate).
with(1,mother,tenderness).
presented_as(1,monkey,candidate_for_reward).
presented_as(1,monkey,candidate_for_promised_reward).
came_with(1,monkey,rest).
root(2,ROOT,saluted).
det(2,laugh,a).
amod(2,laugh,general).
nsubj(2,saluted,laugh).
dobj(2,saluted,her).
case(2,presentation,on).
det(2,presentation,the).
nmod:on(2,saluted,presentation).
case(2,son,of).
nmod:poss(2,son,her).
nmod:of(2,presentation,son).
saluted(2,general_laugh,her).
saluted(2,laugh,her).
root(3,ROOT,said).
nsubj(3,said,she).
advmod(3,said,resolutely).
root(4,ROOT,know).
nsubj(4,know,i).
dep(4,allot,not).
mark(4,allot,whether).
nsubj(4,allot,jupiter).
aux(4,allot,will).
dep(4,know,allot).
det(4,prize,the).
dobj(4,allot,prize).
case(4,son,to).
nmod:poss(4,son,my).
nmod:to(4,allot,son).
cc(4,allot,but).
det(4,i,this).
nsubj(4,know,i).
aux(4,know,do).
dep(4,know,know).
conj:but(4,allot,know).
mark(4,mother,that).
nsubj(4,mother,he).
cop(4,mother,is).
advmod(4,mother,at).
mwe(4,at,least).
case(4,eyes,in).
det(4,eyes,the).
nmod:in(4,at,eyes).
case(4,me,of).
nmod:of(4,eyes,me).
nmod:poss(4,mother,his).
ccomp(4,know,mother).
det(4,handsomest,the).
amod(4,handsomest,dearest).
dep(4,mother,handsomest).
cc(4,handsomest,and).
advmod(4,beautiful,most).
dep(4,mother,beautiful).
conj:and(4,handsomest,beautiful).
case(4,all,of).
nmod:of(4,beautiful,all).
is(4,he,his_mother).
