root(0,ROOT,legend).
case(0,legend,according).
mwe(0,according,to).
det(0,legend,an).
amod(0,legend,ancient).
det(0,man,the).
amod(0,man,first).
nsubjpass(0,made,man).
auxpass(0,made,was).
acl:relcl(0,legend,made).
case(0,jupiter,by).
nmod:agent(0,made,jupiter).
det(0,bull,the).
amod(0,bull,first).
dep(0,jupiter,bull).
case(0,neptune,by).
nmod:agent(0,made,neptune).
cc(0,neptune,and).
det(0,house,the).
amod(0,house,first).
nmod:agent(0,made,house).
conj:and(0,neptune,house).
case(0,minerva,by).
nmod:agent(0,made,minerva).
was_made_by(0,first_man,neptune).
was(0,man,made_by_jupiter_by_minerva).
was(0,man,made_by_neptune_by_minerva).
was(0,first_man,made_by_jupiter_by_neptune_by_minerva).
was_made_by(0,first_man,jupiter).
was(0,first_man,made_by_jupiter_by_minerva).
was_made_by(0,man,minerva).
was_made_by(0,man,neptune).
was(0,man,made_by_jupiter_by_neptune).
was_made_by(0,man,jupiter).
was(0,man,made).
was(0,man,made_by_jupiter_by_neptune_by_minerva).
was(0,first_man,made_by_jupiter_by_neptune).
was_made_by(0,first_man,minerva).
was(0,first_man,made).
was(0,first_man,made_by_neptune_by_minerva).
root(1,ROOT,arose).
case(1,completion,on).
det(1,completion,the).
nmod:on(1,arose,completion).
case(1,labors,of).
nmod:poss(1,labors,their).
nmod:of(1,completion,labors).
det(1,dispute,a).
nsubj(1,arose,dispute).
case(1,made,as).
mark(1,made,to).
nsubj(1,made,which).
aux(1,made,had).
dep(1,arose,made).
det(1,work,the).
advmod(1,perfect,most).
amod(1,work,perfect).
dobj(1,made,work).
arose_on(1,dispute,completion).
arose_on(1,dispute,completion_of_their_labors).
root(2,ROOT,agreed).
nsubj(2,agreed,they).
mark(2,appoint,to).
ccomp(2,agreed,appoint).
dobj(2,appoint,momus).
case(2,judge,as).
nmod:as(2,appoint,judge).
cc(2,appoint,and).
mark(2,abide,to).
ccomp(2,agreed,abide).
conj:and(2,appoint,abide).
case(2,decision,by).
nmod:poss(2,decision,his).
nmod:by(2,abide,decision).
abide_by(2,momus,his_decision).
root(3,ROOT,momus).
advmod(3,momus,however).
cop(3,envious,being).
advmod(3,envious,very).
dep(3,momus,envious).
case(3,handicraft,of).
det(3,handicraft,the).
nmod:of(3,momus,handicraft).
case(3,each,of).
nmod:of(3,handicraft,each).
acl(3,each,found).
dobj(3,found,fault).
case(3,all,with).
nmod:with(3,found,all).
root(4,ROOT,blamed).
nsubj(4,blamed,he).
advmod(4,blamed,first).
det(4,work,the).
dobj(4,blamed,work).
case(4,neptune,of).
nmod:of(4,work,neptune).
mark(4,made,because).
nsubj(4,made,he).
aux(4,made,had).
neg(4,made,not).
advcl:because(4,blamed,made).
det(4,horns,the).
dobj(4,made,horns).
case(4,bull,of).
det(4,bull,the).
nmod:of(4,horns,bull).
case(4,eyes,below).
nmod:poss(4,eyes,his).
nmod:below(4,made,eyes).
mark(4,see,so).
nsubj(4,see,he).
nsubj:xsubj(4,strike,he).
aux(4,see,might).
advmod(4,see,better).
advcl:so(4,made,see).
advmod(4,strike,where).
mark(4,strike,to).
xcomp(4,see,strike).
horns_of(4,he,bull).
root(5,ROOT,condemned).
nsubj(5,condemned,he).
advmod(5,condemned,then).
det(5,work,the).
dobj(5,condemned,work).
case(5,jupiter,of).
nmod:of(5,work,jupiter).
mark(5,placed,because).
nsubj(5,placed,he).
aux(5,placed,had).
neg(5,placed,not).
advcl:because(5,condemned,placed).
det(5,heart,the).
dobj(5,placed,heart).
case(5,man,of).
nmod:of(5,heart,man).
case(5,outside,on).
det(5,outside,the).
nmod:on(5,placed,outside).
mark(5,read,that).
nsubj(5,read,everyone).
nsubj(5,take,everyone).
aux(5,read,might).
ccomp(5,placed,read).
det(5,thoughts,the).
dobj(5,read,thoughts).
case(5,disposed,of).
det(5,disposed,the).
amod(5,disposed,evil).
nmod:of(5,thoughts,disposed).
cc(5,read,and).
ccomp(5,placed,take).
conj:and(5,read,take).
dobj(5,take,precautions).
case(5,mischief,against).
det(5,mischief,the).
amod(5,mischief,intended).
nmod:against(5,take,mischief).
heart_of(5,he,man).
root(6,ROOT,lastly).
cc(6,lastly,and).
nsubj(6,inveighed,he).
ccomp(6,lastly,inveighed).
case(6,minerva,against).
nmod:against(6,inveighed,minerva).
mark(6,had,because).
nsubj(6,had,she).
advcl:because(6,inveighed,had).
neg(6,wheels,not).
amod(6,wheels,contrived).
compound(6,wheels,iron).
dobj(6,had,wheels).
case(6,foundation,in).
det(6,foundation,the).
nmod:in(6,had,foundation).
case(6,house,of).
nmod:poss(6,house,her).
nmod:of(6,foundation,house).
mark(6,remove,so).
nmod:poss(6,inhabitants,its).
nsubj(6,remove,inhabitants).
aux(6,remove,might).
advmod(6,easily,more).
advmod(6,remove,easily).
acl:relcl(6,foundation,remove).
mark(6,proved,if).
det(6,neighbor,a).
nsubj(6,proved,neighbor).
advcl:if(6,remove,proved).
xcomp(6,proved,unpleasant).
might_easily_remove(6,its_inhabitants,neighbor_proved).
might_remove(6,its_inhabitants,neighbor_proved).
proved(6,neighbor,unpleasant).
might_more_easily_remove(6,its_inhabitants,neighbor_proved).
inveighed_against(6,he,minerva).
root(7,ROOT,drove).
nsubj(7,drove,jupiter).
nsubj(7,expelled,jupiter).
amod(7,jupiter,indignant).
case(7,faultfinding,at).
amod(7,faultfinding,such).
amod(7,faultfinding,inveterate).
nmod:at(7,indignant,faultfinding).
dobj(7,drove,him).
case(7,office,from).
nmod:poss(7,office,his).
nmod:from(7,drove,office).
case(7,judge,of).
nmod:of(7,office,judge).
cc(7,drove,and).
conj:and(7,drove,expelled).
dobj(7,expelled,him).
case(7,mansions,from).
det(7,mansions,the).
nmod:from(7,expelled,mansions).
case(7,olympus,of).
nmod:of(7,mansions,olympus).
indignant_at(7,jupiter,inveterate_faultfinding).
expelled(7,jupiter,him).
expelled(7,jupiter_indignant,him).
indignant_at(7,jupiter,such_inveterate_faultfinding).
drove(7,jupiter_indignant,him).
indignant_at(7,jupiter,such_faultfinding).
indignant_at(7,jupiter,faultfinding).
drove(7,jupiter,him).
