root(0,ROOT,felling).
det(0,woodman,a).
nsubj(0,felling,woodman).
aux(0,felling,was).
det(0,tree,a).
dobj(0,felling,tree).
case(0,bank,on).
det(0,bank,the).
nmod:on(0,felling,bank).
case(0,river,of).
det(0,river,a).
nmod:of(0,bank,river).
advmod(0,flew,when).
nmod:poss(0,axe,his).
nsubj(0,flew,axe).
nsubj(0,fell,axe).
acl(0,axe,glancing).
compound:prt(0,glancing,off).
det(0,trunk,the).
dobj(0,glancing,trunk).
acl:relcl(0,river,flew).
compound:prt(0,flew,out).
case(0,hands,of).
nmod:poss(0,hands,his).
nmod:of(0,flew,hands).
cc(0,flew,and).
acl:relcl(0,river,fell).
conj:and(0,flew,fell).
case(0,water,into).
det(0,water,the).
nmod:into(0,fell,water).
was_felling(0,woodman,tree).
flew_out_of(0,his_axe,his_hands).
fell_into(0,his_axe,water).
was_felling_tree_on(0,woodman,bank).
root(1,ROOT,stood).
mark(1,stood,as).
nsubj(1,stood,he).
case(1,edge,by).
det(1,water,the).
nmod:poss(1,edge,water).
case(1,water,'s).
nmod:by(1,stood,edge).
xcomp(1,stood,lamenting).
nmod:poss(1,mercury,his).
compound(1,mercury,loss).
nsubj(1,appeared,mercury).
nsubj(1,asked,mercury).
ccomp(1,lamenting,appeared).
cc(1,appeared,and).
ccomp(1,lamenting,asked).
conj:and(1,appeared,asked).
nsubj(1,reason,him).
det(1,reason,the).
xcomp(1,asked,reason).
case(1,grief,for).
nmod:poss(1,grief,his).
nmod:for(1,reason,grief).
reason_for(1,him,his_grief).
asked(1,his_loss_mercury,him_reason_for_his_grief).
stood_by(1,he,water_s_edge).
asked(1,his_loss_mercury,him_reason).
stood(1,he,lamenting).
by(1,water,edge).
root(2,ROOT,learning).
mark(2,learning,on).
nsubj(2,happened,what).
aux(2,happened,had).
ccomp(2,learning,happened).
compound:prt(2,happened,out).
case(2,pity,of).
nmod:of(2,happened,pity).
mark(2,dived,for).
nmod:poss(2,mercury,his).
compound(2,mercury,distress).
nsubj(2,dived,mercury).
advcl:for(2,happened,dived).
case(2,river,into).
det(2,river,the).
nmod:into(2,dived,river).
cc(2,learning,and).
conj:and(2,learning,bringing).
compound:prt(2,bringing,up).
det(2,axe,a).
amod(2,axe,golden).
dobj(2,bringing,axe).
nsubj(2,one,axe).
acl:relcl(2,axe,asked).
dobj(2,asked,him).
mark(2,one,if).
ref(2,axe,that).
cop(2,one,was).
det(2,one,the).
advcl:if(2,asked,one).
nsubj(2,lost,he).
aux(2,lost,had).
acl:relcl(2,one,lost).
dived_into(2,his_distress_mercury,river).
root(3,ROOT,replied).
det(3,woodman,the).
nsubj(3,replied,woodman).
mark(3,was,that).
nsubj(3,was,it).
ccomp(3,replied,was).
neg(3,was,not).
cc(3,was,and).
nsubj(3,dived,mercury).
advmod(3,dived,then).
ccomp(3,replied,dived).
conj:and(3,was,dived).
det(3,time,a).
amod(3,time,second).
dobj(3,dived,time).
cc(3,dived,and).
csubj(3,asked,bringing).
compound:prt(3,bringing,up).
det(3,axe,a).
compound(3,axe,silver).
dobj(3,bringing,axe).
conj:and(3,was,asked).
conj:and(3,dived,asked).
mark(3,his,if).
nsubj(3,his,that).
cop(3,his,was).
advcl:if(3,asked,his).
dived(3,mercury,time).
dived(3,mercury,second_time).
root(4,ROOT,no).
nsubj(4,mine,that).
cop(4,mine,is).
neg(4,mine,not).
dep(4,no,mine).
advmod(4,mine,either).
root(5,ROOT,said).
det(5,woodman,the).
nsubj(5,said,woodman).
root(6,ROOT,dived).
advmod(6,mercury,once).
amod(6,mercury,more).
nsubj(6,dived,mercury).
nsubj(6,brought,mercury).
case(6,river,into).
det(6,river,the).
nmod:into(6,dived,river).
cc(6,dived,and).
conj:and(6,dived,brought).
dep(6,axe,up).
det(6,axe,the).
amod(6,axe,missing).
nmod(6,brought,axe).
dived_into(6,mercury,river).
dived_into(6,more_mercury,river).
root(7,ROOT,overjoyed).
det(7,woodman,the).
nsubjpass(7,overjoyed,woodman).
nsubjpass(7,thanked,woodman).
auxpass(7,overjoyed,was).
mark(7,recovering,at).
advcl:at(7,overjoyed,recovering).
nmod:poss(7,property,his).
dobj(7,recovering,property).
cc(7,overjoyed,and).
conj:and(7,overjoyed,thanked).
nmod:poss(7,benefactor,his).
dobj(7,thanked,benefactor).
advmod(7,thanked,warmly).
was(7,woodman,overjoyed).
thanked_warmly(7,woodman,his_benefactor).
recovering(7,woodman,his_property).
thanked(7,woodman,his_benefactor).
root(8,ROOT,latter).
cc(8,latter,and).
det(8,latter,the).
cop(8,pleased,was).
advmod(8,pleased,so).
ccomp(8,latter,pleased).
case(8,honesty,with).
nmod:poss(8,honesty,his).
nmod:with(8,pleased,honesty).
mark(8,made,that).
nsubj(8,made,he).
ccomp(8,pleased,made).
nsubj(8,present,him).
det(8,present,a).
xcomp(8,made,present).
case(8,axes,of).
det(8,axes,the).
amod(8,axes,other).
nummod(8,axes,two).
nmod:of(8,present,axes).
made(8,he,him_present_of_other_two_axes).
made(8,he,him_present).
made(8,he,him_present_of_two_axes).
present_of(8,him,two_axes).
present_of(8,him,other_two_axes).
root(9,ROOT,told).
advmod(9,told,when).
det(9,woodman,the).
nsubj(9,told,woodman).
det(9,story,the).
dobj(9,told,story).
case(9,companions,to).
nmod:poss(9,companions,his).
nmod:to(9,told,companions).
nsubjpass(9,filled,one).
nsubjpass(9,determined,one).
nsubj:xsubj(9,try,one).
case(9,these,of).
nmod:of(9,one,these).
auxpass(9,filled,was).
acl:relcl(9,companions,filled).
case(9,envy,with).
nmod:with(9,filled,envy).
case(9,fortune,of).
nmod:poss(9,fortune,his).
amod(9,fortune,good).
nmod:of(9,envy,fortune).
cc(9,filled,and).
acl:relcl(9,companions,determined).
conj:and(9,filled,determined).
mark(9,try,to).
xcomp(9,determined,try).
nmod:poss(9,luck,his).
dobj(9,try,luck).
case(9,himself,for).
nmod:for(9,try,himself).
told(9,woodman,story).
root(10,ROOT,so).
nsubj(10,went,he).
nsubj(10,began,he).
nsubj:xsubj(10,fell,he).
ccomp(10,so,went).
cc(10,went,and).
ccomp(10,so,began).
conj:and(10,went,began).
mark(10,fell,to).
xcomp(10,began,fell).
det(10,tree,a).
dobj(10,fell,tree).
case(10,edge,at).
det(10,edge,the).
nmod:at(10,fell,edge).
case(10,river,of).
det(10,river,the).
nmod:of(10,edge,river).
cc(10,fell,and).
advmod(10,contrived,presently).
xcomp(10,began,contrived).
conj:and(10,fell,contrived).
mark(10,let,to).
xcomp(10,contrived,let).
nmod:poss(10,drop,his).
amod(10,drop,axe).
dobj(10,let,drop).
case(10,water,into).
det(10,water,the).
nmod:into(10,let,water).
began(10,he,fell_at_edge).
began(10,he,fell_at_edge_of_river).
began(10,he,fell).
root(11,ROOT,appeared).
nsubj(11,appeared,mercury).
case(11,before,as).
dep(11,appeared,before).
cc(11,before,and).
mark(11,learning,on).
dep(11,appeared,learning).
conj:and(11,before,learning).
mark(11,fallen,that).
nmod:poss(11,axe,his).
nsubj(11,fallen,axe).
aux(11,fallen,had).
ccomp(11,learning,fallen).
mark(11,dived,in).
nsubj(11,dived,he).
nsubj(11,brought,he).
advcl:in(11,fallen,dived).
cc(11,dived,and).
advcl:in(11,fallen,brought).
conj:and(11,dived,brought).
compound:prt(11,dived,up).
det(11,axe,a).
amod(11,axe,golden).
dobj(11,dived,axe).
mark(11,done,as).
nsubj(11,done,he).
aux(11,done,had).
advcl:as(11,appeared,done).
case(11,occasion,on).
det(11,occasion,the).
amod(11,occasion,previous).
nmod:on(11,done,occasion).
appeared(11,mercury,he_had_done_on_previous_occasion).
had_done_on(11,he,occasion).
had_done_on(11,he,previous_occasion).
appeared(11,mercury,he_had_done).
appeared(11,mercury,he_had_done_on_occasion).
root(12,ROOT,waiting).
mark(12,waiting,without).
mark(12,asked,to).
auxpass(12,asked,be).
xcomp(12,waiting,asked).
mark(12,his,whether).
nsubj(12,his,it).
cop(12,his,was).
ccomp(12,asked,his).
cc(12,waiting,or).
dep(12,cried,not).
det(12,fellow,the).
nsubj(12,cried,fellow).
conj:or(12,waiting,cried).
was(12,it,his).
root(13,ROOT,mine).
nsubj(13,mine,that).
cop(13,mine,'s).
nsubj(13,mine,mine).
ref(13,mine,that).
cop(13,mine,'s).
acl:relcl(13,mine,mine).
root(14,ROOT,stretched).
cc(14,stretched,and).
compound:prt(14,stretched,out).
nmod:poss(14,hand,his).
dobj(14,stretched,hand).
advmod(14,prize,eagerly).
case(14,prize,for).
det(14,prize,the).
nmod:for(14,stretched,prize).
cc(14,disgusted,but).
nsubj(14,disgusted,mercury).
cop(14,disgusted,was).
advmod(14,disgusted,so).
dep(14,stretched,disgusted).
case(14,dishonesty,at).
nmod:poss(14,dishonesty,his).
nmod:at(14,disgusted,dishonesty).
mark(14,declined,that).
nsubj(14,declined,he).
nsubj:xsubj(14,give,he).
nsubj(14,refused,he).
nsubj:xsubj(14,recover,he).
neg(14,only,not).
cc:preconj(14,declined,only).
ccomp(14,disgusted,declined).
mark(14,give,to).
xcomp(14,declined,give).
iobj(14,give,him).
det(14,axe,the).
amod(14,axe,golden).
dobj(14,give,axe).
cc(14,declined,but).
advmod(14,refused,also).
ccomp(14,disgusted,refused).
conj:and(14,declined,refused).
mark(14,recover,to).
xcomp(14,refused,recover).
case(14,him,for).
nmod:for(14,recover,him).
det(14,one,the).
dobj(14,recover,one).
nsubj(14,let,he).
aux(14,let,had).
acl:relcl(14,one,let).
ccomp(14,let,fall).
case(14,stream,into).
det(14,stream,the).
nmod:into(14,fall,stream).
give(14,he,him).
give(14,he,axe).
give(14,he,golden_axe).
