root(0,ROOT,workman).
det(0,workman,a).
amod(0,wood,felling).
nsubj(0,let,wood).
case(0,side,by).
det(0,side,the).
nmod:by(0,wood,side).
case(0,river,of).
det(0,river,a).
nmod:of(0,side,river).
ccomp(0,workman,let).
nmod:poss(0,drop,his).
amod(0,drop,axe).
dobj(0,let,drop).
punct(0,let,-).
case(0,accident,by).
dep(0,let,accident).
case(0,pool,into).
det(0,pool,a).
amod(0,pool,deep).
nmod:into(0,accident,pool).
felling_wood_by(0,his_axe_drop,side_of_river).
let(0,felling_wood,his_axe_drop).
let(0,wood,his_axe_drop).
let(0,wood,his_drop).
let(0,felling_wood,his_drop).
felling_wood_by(0,his_drop,side).
wood_by(0,his_axe_drop,side).
wood_by(0,his_drop,side_of_river).
wood_by(0,his_drop,side).
wood_by(0,his_axe_drop,side_of_river).
felling_wood_by(0,his_axe_drop,side).
felling_wood_by(0,his_drop,side_of_river).
root(1,ROOT,deprived).
auxpass(1,deprived,being).
advmod(1,deprived,thus).
case(1,means,of).
det(1,means,the).
nmod:of(1,deprived,means).
case(1,livelihood,of).
nmod:poss(1,livelihood,his).
nmod:of(1,means,livelihood).
nsubj(1,sat,he).
nsubj(1,lamented,he).
acl:relcl(1,livelihood,sat).
compound:prt(1,sat,down).
case(1,bank,on).
det(1,bank,the).
nmod:on(1,sat,bank).
cc(1,sat,and).
acl:relcl(1,livelihood,lamented).
conj:and(1,sat,lamented).
nmod:poss(1,fate,his).
amod(1,fate,hard).
dobj(1,lamented,fate).
lamented(1,he,his_hard_fate).
sat_down_on(1,he,bank).
lamented(1,he,his_fate).
root(2,ROOT,appeared).
nsubj(2,appeared,mercury).
nsubj(2,demanded,mercury).
cc(2,appeared,and).
conj:and(2,appeared,demanded).
det(2,cause,the).
dobj(2,demanded,cause).
case(2,tears,of).
nmod:poss(2,tears,his).
nmod:of(2,cause,tears).
demanded(2,mercury,cause).
cause_of(2,demanded,his_tears).
demanded(2,mercury,cause_of_his_tears).
root(3,ROOT,told).
mark(3,told,after).
nsubj(3,told,he).
dobj(3,told,him).
nmod:poss(3,mercury,his).
compound(3,mercury,misfortune).
nsubj(3,plunged,mercury).
dep(3,told,plunged).
case(3,stream,into).
det(3,stream,the).
nmod:into(3,plunged,stream).
cc(3,plunged,and).
csubj(3,inquired,bringing).
compound:prt(3,bringing,up).
det(3,axe,a).
amod(3,axe,golden).
dobj(3,bringing,axe).
dep(3,told,inquired).
conj:and(3,plunged,inquired).
mark(3,one,if).
nsubj(3,one,that).
cop(3,one,were).
det(3,one,the).
advcl:if(3,inquired,one).
nsubj(3,lost,he).
aux(3,lost,had).
acl:relcl(3,one,lost).
told(3,he,him).
root(4,ROOT,disappeared).
mark(4,saying,on).
nsubj(4,saying,his).
dep(4,disappeared,saying).
mark(4,mercury,that).
nsubj(4,mercury,it).
cop(4,mercury,was).
neg(4,mercury,not).
nmod:poss(4,mercury,his).
ccomp(4,saying,mercury).
case(4,water,beneath).
det(4,water,the).
nmod:beneath(4,disappeared,water).
det(4,time,a).
amod(4,time,second).
nsubj(4,disappeared,time).
acl:relcl(4,time,returned).
case(4,axe,with).
det(4,axe,a).
compound(4,axe,silver).
nmod:with(4,returned,axe).
case(4,hand,in).
nmod:poss(4,hand,his).
nmod:in(4,returned,hand).
cc(4,returned,and).
advmod(4,asked,again).
acl:relcl(4,time,asked).
conj:and(4,returned,asked).
det(4,workman,the).
dobj(4,asked,workman).
mark(4,his,if).
nsubj(4,his,it).
cop(4,his,were).
advcl:if(4,asked,his).
were(4,it,his).
root(5,ROOT,said).
advmod(5,said,when).
det(5,workman,the).
nsubj(5,said,workman).
nsubj(5,was,it).
ccomp(5,said,was).
dep(5,dived,not).
nsubj(5,dived,he).
nsubj(5,brought,he).
ccomp(5,was,dived).
case(5,pool,into).
det(5,pool,the).
nmod:into(5,dived,pool).
case(5,time,for).
det(5,time,the).
amod(5,time,third).
nmod:for(5,pool,time).
cc(5,dived,and).
ccomp(5,was,brought).
conj:and(5,dived,brought).
compound:prt(5,brought,up).
det(5,axe,the).
dobj(5,brought,axe).
nsubjpass(5,lost,axe).
ref(5,axe,that).
aux(5,lost,had).
auxpass(5,lost,been).
acl:relcl(5,axe,lost).
root(6,ROOT,claimed).
det(6,workman,the).
nsubj(6,claimed,workman).
nsubj(6,expressed,workman).
dobj(6,claimed,it).
cc(6,claimed,and).
conj:and(6,claimed,expressed).
nmod:poss(6,joy,his).
dobj(6,expressed,joy).
case(6,recovery,at).
nmod:poss(6,recovery,its).
nmod:at(6,expressed,recovery).
expressed(6,workman,his_joy).
claimed(6,workman,it).
root(7,ROOT,gave).
nsubj(7,gave,mercury).
amod(7,mercury,pleased).
case(7,honesty,with).
nmod:poss(7,honesty,his).
nmod:with(7,pleased,honesty).
iobj(7,gave,him).
det(7,axes,the).
amod(7,axes,golden).
cc(7,golden,and).
conj:and(7,golden,silver).
amod(7,axes,silver).
dobj(7,gave,axes).
case(7,addition,in).
nmod:in(7,axes,addition).
case(7,own,to).
nmod:poss(7,own,his).
nmod:to(7,gave,own).
gave(7,mercury_pleased,axes_in_addition).
gave_axes_to(7,mercury_pleased,his_own).
gave(7,mercury,golden_axes_in_addition).
pleased_with(7,mercury,his_honesty).
gave(7,mercury,golden_axes).
gave(7,mercury_pleased,golden_axes).
gave(7,mercury,him).
gave(7,mercury,axes).
gave(7,mercury_pleased,axes).
gave(7,mercury,axes_in_addition).
gave(7,mercury_pleased,him).
gave(7,mercury_pleased,golden_axes_in_addition).
gave_axes_to(7,mercury,his_own).
is_in(7,golden_axes,addition).
root(8,ROOT,workman).
det(8,workman,the).
case(8,return,on).
nmod:poss(8,return,his).
nmod:on(8,workman,return).
case(8,house,to).
nmod:poss(8,house,his).
nmod:to(8,workman,house).
nsubj(8,happened,house).
amod(8,house,related).
case(8,companions,to).
nmod:poss(8,companions,his).
nmod:to(8,related,companions).
det:predet(8,that,all).
ref(8,house,that).
aux(8,happened,had).
acl:relcl(8,house,happened).
root(9,ROOT,them).
det:qmod(9,them,one).
mwe(9,one,of).
case(9,once,at).
nmod:at(9,one,once).
acl(9,once,resolved).
mark(9,try,to).
xcomp(9,resolved,try).
cc(9,try,and).
xcomp(9,resolved,secure).
conj:and(9,try,secure).
det(9,fortune,the).
amod(9,fortune,same).
amod(9,fortune,good).
dobj(9,try,fortune).
case(9,himself,for).
nmod:for(9,fortune,himself).
root(10,ROOT,ran).
nsubj(10,ran,he).
nsubj(10,threw,he).
case(10,river,to).
det(10,river,the).
nmod:to(10,ran,river).
cc(10,ran,and).
conj:and(10,ran,threw).
nmod:poss(10,axe,his).
dobj(10,threw,axe).
case(10,purpose,on).
nmod:on(10,threw,purpose).
case(10,pool,into).
det(10,pool,the).
nmod:into(10,threw,pool).
case(10,place,at).
det(10,place,the).
amod(10,place,same).
nmod:at(10,pool,place).
cc(10,threw,and).
conj:and(10,ran,sat).
conj:and(10,threw,sat).
compound:prt(10,sat,down).
case(10,bank,on).
det(10,bank,the).
nmod:on(10,sat,bank).
mark(10,weep,to).
acl:to(10,bank,weep).
ran_to(10,he,river).
threw(10,he,his_axe).
sat_down_on(10,his_axe,bank_weep).
root(11,ROOT,appeared).
nsubj(11,appeared,mercury).
case(11,him,to).
nmod:to(11,appeared,him).
advmod(11,hoped,just).
mark(11,hoped,as).
nsubj(11,hoped,he).
advcl:as(11,appeared,hoped).
nsubj(11,would,he).
ccomp(11,hoped,would).
appeared(11,mercury,he_hoped).
appeared_to(11,mercury,him).
appeared(11,mercury,just_he_hoped).
root(12,ROOT,learned).
cc(12,learned,and).
aux(12,learned,having).
det(12,cause,the).
nsubj(12,plunged,cause).
nsubj(12,brought,cause).
case(12,grief,of).
nmod:poss(12,grief,his).
nmod:of(12,cause,grief).
ccomp(12,learned,plunged).
case(12,stream,into).
det(12,stream,the).
nmod:into(12,plunged,stream).
cc(12,plunged,and).
ccomp(12,learned,brought).
conj:and(12,plunged,brought).
compound:prt(12,brought,up).
det(12,axe,a).
amod(12,axe,golden).
dobj(12,brought,axe).
acl(12,axe,inquiring).
mark(12,lost,if).
nsubj(12,lost,he).
aux(12,lost,had).
advcl:if(12,inquiring,lost).
dobj(12,lost,it).
brought_up(12,cause,axe).
plunged_into(12,cause,stream).
brought_up(12,cause,golden_axe).
brought_up(12,cause,axe_inquiring).
had_lost(12,he,it).
brought_up(12,cause,golden_axe_inquiring).
root(13,ROOT,seized).
det(13,workman,the).
nsubj(13,seized,workman).
nsubj(13,declared,workman).
dobj(13,seized,it).
advmod(13,seized,greedily).
cc(13,seized,and).
conj:and(13,seized,declared).
mark(13,axe,that).
advmod(13,axe,truly).
nsubj(13,axe,it).
cop(13,axe,was).
det(13,axe,the).
advmod(13,axe,very).
amod(13,axe,same).
ccomp(13,declared,axe).
mark(13,lost,that).
nsubj(13,lost,he).
aux(13,lost,had).
ccomp(13,axe,lost).
seized_greedily(13,workman,it).
was(13,it,truly_very_axe).
seized(13,workman,it).
was(13,it,truly_same_axe).
was(13,it,very_same_axe).
was(13,it,very_axe).
was(13,it,same_axe).
was(13,it,axe).
was(13,it,truly_very_same_axe).
was(13,it,truly_axe).
root(14,ROOT,took).
nsubj(14,took,mercury).
nsubj(14,refused,mercury).
nsubj:xsubj(14,recover,mercury).
amod(14,mercury,displeased).
case(14,knavery,at).
nmod:poss(14,knavery,his).
nmod:at(14,displeased,knavery).
neg(14,only,not).
cc:preconj(14,took,only).
compound:prt(14,took,away).
det(14,axe,the).
amod(14,axe,golden).
dobj(14,took,axe).
cc(14,took,but).
conj:but(14,took,refused).
mark(14,recover,to).
xcomp(14,refused,recover).
case(14,him,for).
nmod:for(14,recover,him).
det(14,axe,the).
dobj(14,recover,axe).
nsubj(14,thrown,he).
aux(14,thrown,had).
acl:relcl(14,axe,thrown).
case(14,pool,into).
det(14,pool,the).
nmod:into(14,thrown,pool).
took_away(14,mercury,golden_axe).
took_away(14,mercury_displeased,axe).
took_away(14,mercury_displeased,golden_axe).
displeased_at(14,mercury,his_knavery).
took_away(14,mercury,axe).
had_thrown_into(14,he,pool).
