root(0,ROOT,determined).
nsubj(0,determined,mercury).
nsubj:xsubj(0,learn,mercury).
advmod(0,determined,once).
mark(0,learn,to).
xcomp(0,determined,learn).
case(0,esteem,in).
det(0,esteem,what).
nmod:in(0,learn,esteem).
nsubjpass(0,held,he).
auxpass(0,held,was).
ccomp(0,learn,held).
case(0,mortals,among).
nmod:among(0,held,mortals).
determined(0,mercury,learn).
was(0,he,held).
was_held_among(0,he,mortals).
once_determined(0,mercury,learn).
root(1,ROOT,purpose).
case(1,purpose,for).
det(1,purpose,this).
nsubj(1,assumed,he).
acl:relcl(1,purpose,assumed).
det(1,character,the).
dobj(1,assumed,character).
case(1,man,of).
det(1,man,a).
nmod:of(1,character,man).
cc(1,purpose,and).
conj:and(1,purpose,visited).
case(1,this,in).
nmod:in(1,visited,this).
ccomp(1,visited,disguise).
det(1,sculptor,a).
nmod:poss(1,studio,sculptor).
case(1,sculptor,'s).
nsubj(1,looked,studio).
aux(1,looked,having).
dep(1,disguise,looked).
case(1,statues,at).
amod(1,statues,various).
nmod:at(1,looked,statues).
nsubj(1,demanded,he).
acl:relcl(1,statues,demanded).
det(1,price,the).
dobj(1,demanded,price).
case(1,figures,of).
nummod(1,figures,two).
nmod:of(1,price,figures).
case(1,jupiter,of).
nmod:of(1,figures,jupiter).
cc(1,jupiter,and).
nmod:of(1,figures,juno).
conj:and(1,jupiter,juno).
character_of(1,he,man).
has(1,sculptor,studio).
assumed(1,he,character).
assumed(1,he,character_of_man).
root(2,ROOT,named).
advmod(2,named,when).
det(2,sum,the).
nmod:at(2,valued,sum).
nsubjpass(2,named,sum).
case(2,which,at).
ref(2,sum,which).
nsubjpass(2,valued,they).
auxpass(2,valued,were).
acl:relcl(2,sum,valued).
auxpass(2,named,was).
nsubj(2,pointed,he).
ccomp(2,named,pointed).
case(2,figure,to).
det(2,figure,a).
nmod:to(2,pointed,figure).
mark(2,saying,of).
nsubj(2,saying,himself).
acl:of(2,figure,saying).
case(2,sculptor,to).
det(2,sculptor,the).
nmod:to(2,saying,sculptor).
pointed_to(2,he,figure_himself_saying).
pointed_to(2,he,figure_himself_saying_to_sculptor).
were(2,they,valued).
saying_to(2,himself,sculptor).
root(3,ROOT,want).
nsubj(3,want,you).
aux(3,want,will).
advmod(3,want,certainly).
advmod(3,more,much).
advmod(3,want,more).
case(3,this,for).
nmod:for(3,want,this).
mark(3,statue,as).
nsubj(3,statue,it).
cop(3,statue,is).
det(3,statue,the).
advcl:as(3,want,statue).
case(3,messenger,of).
det(3,messenger,the).
nmod:of(3,statue,messenger).
case(3,gods,of).
det(3,gods,the).
nmod:of(3,messenger,gods).
cc(3,gods,and).
nmod:of(3,messenger,author).
conj:and(3,gods,author).
case(3,gain,of).
det:predet(3,gain,all).
nmod:poss(3,gain,your).
nmod:of(3,gods,gain).
will_want_much_more(3,you,statue_of_messenger_of_gods_of_gain).
is(3,it,statue).
will_want_more(3,you,statue_of_messenger).
will_want_more(3,you,statue).
is_statue_of(3,it,messenger_of_gods_of_gain).
will_certainly_want(3,you,statue_of_messenger_of_gods_of_your_gain).
will_want_more(3,you,statue_of_messenger_of_gods_of_gain).
will_certainly_want_much_more(3,you,statue_of_messenger).
is_statue_of(3,it,messenger_of_gods_of_your_gain).
will_want_much_more_for(3,you,this).
will_certainly_want_much_more_for(3,you,this).
will_want_much_more(3,you,statue_of_messenger_of_gods_of_your_gain).
will_certainly_want_much_more(3,you,statue_of_messenger_of_gods_of_your_gain).
will_certainly_want_more(3,you,statue).
will_certainly_want_much_more(3,you,statue).
will_certainly_want(3,you,statue_of_messenger).
will_certainly_want_for(3,you,this).
will_certainly_want(3,you,statue_of_messenger_of_gods_of_gain).
will_certainly_want_much_more(3,you,statue_of_messenger_of_gods_of_gain).
will_want(3,you,statue_of_messenger).
will_certainly_want_more_for(3,you,this).
will_certainly_want(3,you,statue).
will_certainly_want_more(3,you,statue_of_messenger_of_gods_of_gain).
is_statue_of(3,it,messenger).
will_want_much_more(3,you,statue_of_messenger).
will_want_more(3,you,statue_of_messenger_of_gods_of_your_gain).
will_want(3,you,statue).
will_want_much_more(3,you,statue).
will_certainly_want_more(3,you,statue_of_messenger_of_gods_of_your_gain).
will_want_for(3,you,this).
will_want_more_for(3,you,this).
will_certainly_want_more(3,you,statue_of_messenger).
will_want(3,you,statue_of_messenger_of_gods_of_your_gain).
will_want(3,you,statue_of_messenger_of_gods_of_gain).
root(4,ROOT,replied).
det(4,sculptor,the).
nsubj(4,replied,sculptor).
root(5,ROOT,well).
mark(5,buy,if).
nsubj(5,buy,you).
aux(5,buy,will).
dep(5,well,buy).
det(5,i,these).
nsubj(5,fling,i).
aux(5,fling,'ll).
ccomp(5,buy,fling).
dobj(5,fling,you).
dep(5,you,that).
case(5,bargain,into).
det(5,bargain,the).
nmod:into(5,fling,bargain).
fling(5,i,you).
