root(0,ROOT,ass).
det(0,ass,an).
dep(0,ass,carrying).
det(0,load,a).
dobj(0,carrying,load).
case(0,wood,of).
nmod:of(0,load,wood).
acl(0,wood,passed).
case(0,pond,through).
det(0,pond,a).
nmod:through(0,passed,pond).
load(0,carrying,wood_passed_through_pond).
load_of(0,carrying,wood_passed_through_pond).
root(1,ROOT,crossing).
mark(1,crossing,as).
nsubj(1,crossing,he).
nsubj(1,able,he).
nsubj:xsubj(1,rise,he).
aux(1,crossing,was).
case(1,water,through).
det(1,water,the).
nmod:through(1,crossing,water).
nsubj(1,lost,he).
acl:relcl(1,water,lost).
nmod:poss(1,footing,his).
nsubj(1,stumbled,footing).
nsubj(1,fell,footing).
ccomp(1,lost,stumbled).
cc(1,stumbled,and).
ccomp(1,lost,fell).
conj:and(1,stumbled,fell).
cc(1,crossing,and).
neg(1,able,not).
cop(1,able,being).
conj:and(1,crossing,able).
mark(1,rise,to).
xcomp(1,able,rise).
case(1,load,on).
mwe(1,on,account).
mwe(1,on,of).
nmod:poss(1,load,his).
nmod:on_account_of(1,rise,load).
acl(1,load,groaned).
advmod(1,groaned,heavily).
root(2,ROOT,heard).
det(2,frogs,some).
nsubj(2,heard,frogs).
nsubj(2,said,frogs).
acl(2,frogs,frequenting).
det(2,pool,the).
dobj(2,frequenting,pool).
nmod:poss(2,lamentation,his).
dobj(2,heard,lamentation).
cc(2,heard,and).
conj:and(2,heard,said).
heard(2,frogs,his_lamentation).
root(3,ROOT,do).
dobj(3,do,what).
aux(3,do,would).
nsubj(3,do,you).
mark(3,had,if).
nsubj(3,had,you).
nsubj:xsubj(3,live,you).
advcl:if(3,do,had).
mark(3,live,to).
xcomp(3,had,live).
advmod(3,live,here).
advmod(3,live,always).
mark(3,do,as).
nsubj(3,do,we).
advcl:as(3,had,do).
advmod(3,make,when).
nsubj(3,make,you).
advcl(3,do,make).
case(3,fuss,such).
det(3,fuss,a).
nmod:such(3,make,fuss).
case(3,fall,about).
det(3,fall,a).
amod(3,fall,mere).
nmod:about(3,fuss,fall).
case(3,water,into).
det(3,water,the).
nmod:into(3,make,water).
make_into(3,you,water).
had(3,you,live_here).
had(3,you,we_do).
had(3,you,live_here_always).
make_such(3,you,fuss).
had(3,you,live).
make_such(3,you,fuss_about_mere_fall).
make_such(3,you,fuss_about_fall).
had(3,you,live_always).
root(4,ROOT,bear).
nsubj(4,bear,men).
advmod(4,bear,often).
amod(4,grievances,little).
dobj(4,bear,grievances).
case(4,courage,with).
amod(4,courage,less).
nmod:with(4,bear,courage).
mark(4,do,than).
nsubj(4,do,they).
dep(4,courage,do).
amod(4,misfortunes,large).
dobj(4,do,misfortunes).
often_bear_grievances_with(4,men,less_courage).
often_bear(4,men,grievances).
bear(4,men,grievances).
often_bear(4,men,little_grievances).
often_bear_grievances_with(4,men,courage).
bear(4,men,little_grievances).
bear_grievances_with(4,men,less_courage).
bear_grievances_with(4,men,courage).
do(4,they,misfortunes).
do(4,they,large_misfortunes).
