root(0,ROOT,carried).
det(0,ass,an).
nsubj(0,carried,ass).
advmod(0,ass,once).
case(0,streets,through).
det(0,streets,the).
nmod:through(0,carried,streets).
case(0,city,of).
det(0,city,a).
nmod:of(0,streets,city).
det(0,image,a).
amod(0,image,famous).
amod(0,image,wooden).
dobj(0,carried,image).
mark(0,placed,to).
auxpass(0,placed,be).
acl:to(0,image,placed).
case(0,one,in).
nmod:in(0,placed,one).
case(0,temples,of).
nmod:poss(0,temples,its).
nmod:of(0,one,temples).
root(1,ROOT,passed).
mark(1,passed,as).
nsubj(1,passed,he).
case(1,crowd,along).
det(1,crowd,the).
nmod:along(1,passed,crowd).
acl(1,crowd,made).
amod(1,prostration,lowly).
dobj(1,made,prostration).
case(1,image,before).
det(1,image,the).
nmod:before(1,made,image).
passed_along(1,he,crowd).
root(2,ROOT,gave).
det(2,ass,the).
nsubj(2,gave,ass).
acl(2,ass,thinking).
mark(2,bowed,that).
nsubj(2,bowed,they).
ccomp(2,thinking,bowed).
nmod:poss(2,heads,their).
dobj(2,bowed,heads).
case(2,token,in).
nmod:in(2,bowed,token).
case(2,respect,of).
nmod:of(2,token,respect).
mark(2,bristled,for).
nsubj(2,bristled,himself).
advcl:for(2,bowed,bristled).
compound:prt(2,bristled,up).
case(2,pride,with).
nmod:with(2,bristled,pride).
nsubj(2,airs,himself).
nsubj(2,refused,himself).
nsubj:xsubj(2,move,himself).
ccomp(2,gave,airs).
cc(2,airs,and).
ccomp(2,gave,refused).
conj:and(2,airs,refused).
mark(2,move,to).
xcomp(2,refused,move).
det(2,step,another).
dobj(2,move,step).
root(3,ROOT,stop).
det(3,driver,the).
nsubj(3,stop,driver).
nsubj(3,said,driver).
acl(3,driver,seeing).
dobj(3,seeing,him).
advmod(3,stop,thus).
dep(3,stop,laid).
nmod:poss(3,whip,his).
dobj(3,laid,whip).
advmod(3,shoulders,lustily).
case(3,shoulders,about).
nmod:poss(3,shoulders,his).
nmod:about(3,laid,shoulders).
cc(3,stop,and).
conj:and(3,stop,said).
root(4,ROOT,o).
dep(4,o,you).
amod(4,dull-head,perverse).
amod(4,you,dull-head).
root(5,ROOT,come).
nsubjpass(5,come,it).
auxpass(5,come,is).
neg(5,come,not).
advmod(5,come,yet).
case(5,this,to).
nmod:to(5,come,this).
dobj(5,pay,this).
ref(5,this,that).
nsubj(5,pay,men).
acl:relcl(5,this,pay).
dobj(5,pay,worship).
case(5,ass,to).
det(5,ass,an).
nmod:to(5,pay,ass).
root(6,ROOT,others).
