root(0,ROOT,straw-yard).
det(0,ass,an).
nsubj(0,straw-yard,ass).
cc(0,ass,and).
det(0,cock,a).
conj:and(0,ass,cock).
nsubj(0,straw-yard,cock).
cop(0,straw-yard,were).
case(0,straw-yard,in).
det(0,straw-yard,a).
advmod(0,approached,together).
advmod(0,approached,when).
det(0,lion,a).
nsubj(0,approached,lion).
amod(0,lion,desperate).
case(0,hunger,from).
nmod:from(0,desperate,hunger).
advcl(0,straw-yard,approached).
det(0,spot,the).
dobj(0,approached,spot).
were_in(0,cock,straw-yard).
approached(0,lion_desperate,spot).
together_approached(0,lion_desperate,spot).
approached(0,lion,spot).
were_in(0,ass,straw-yard).
together_approached(0,lion,spot).
desperate_from(0,lion,hunger).
root(1,ROOT,ass).
nsubj(1,ass,he).
cop(1,ass,was).
advmod(1,ass,about).
case(1,spring,to).
nmod:to(1,about,spring).
case(1,ass,upon).
det(1,ass,the).
advmod(1,crowed,when).
det(1,cock,the).
nsubj(1,crowed,cock).
punct(1,sound,-LRB-).
case(1,sound,to).
det(1,sound,the).
nmod:to(1,cock,sound).
mark(1,has,of).
nmod:poss(1,voice,whose).
dobj(1,has,voice).
det(1,lion,the).
nsubj(1,has,lion).
nsubjpass(1,said,it).
auxpass(1,said,is).
acl:relcl(1,lion,said).
acl:of(1,sound,has).
det(1,aversion,a).
amod(1,aversion,singular).
dobj(1,has,aversion).
punct(1,sound,-RRB-).
advcl(1,ass,crowed).
advmod(1,crowed,loudly).
cc(1,crowed,and).
det(1,lion,the).
nsubj(1,fled,lion).
advcl(1,ass,fled).
conj:and(1,crowed,fled).
advmod(1,fast,away).
advmod(1,fast,as).
advmod(1,fled,fast).
mark(1,could,as).
nsubj(1,could,he).
advcl:as(1,fled,could).
fled_fast(1,lion,he_could).
fled_away_as_fast(1,lion,he_could).
is(1,it,said).
fled(1,lion,he_could).
fled_away_fast(1,lion,he_could).
was_upon(1,he,ass).
fled_as_fast(1,lion,he_could).
was_upon(1,he,about_ass).
was_upon(1,he,about_to_spring_ass).
root(2,ROOT,summoned).
det(2,ass,the).
nsubj(2,summoned,ass).
nsubj(2,galloped,ass).
acl(2,ass,observing).
nmod:poss(2,trepidation,his).
dobj(2,observing,trepidation).
case(2,crowing,at).
det(2,crowing,the).
amod(2,crowing,mere).
nmod:at(2,observing,crowing).
case(2,cock,of).
det(2,cock,a).
nmod:of(2,crowing,cock).
dobj(2,summoned,courage).
mark(2,attack,to).
advcl:to(2,summoned,attack).
dobj(2,attack,him).
cc(2,summoned,and).
conj:and(2,summoned,galloped).
case(2,him,after).
nmod:after(2,galloped,him).
case(2,purpose,for).
det(2,purpose,that).
nmod:for(2,galloped,purpose).
observing(2,ass,his_trepidation).
galloped_for(2,ass,purpose).
observing_his_trepidation_at(2,ass,crowing_cock).
galloped_after(2,ass,him).
observing_his_trepidation_at(2,ass,crowing).
summoned(2,ass,courage).
attack(2,ass,him).
observing_his_trepidation_at(2,ass,mere_crowing).
observing_his_trepidation_at(2,ass,mere_crowing_cock).
root(3,ROOT,run).
nsubj(3,run,he).
aux(3,run,had).
neg(3,distance,no).
amod(3,distance,long).
dobj(3,run,distance).
advmod(3,seized,when).
det(3,lion,the).
nsubj(3,seized,lion).
nsubj(3,tore,lion).
acl(3,lion,turning).
advmod(3,turning,about).
advcl(3,run,seized).
dobj(3,seized,him).
cc(3,seized,and).
advcl(3,run,tore).
conj:and(3,seized,tore).
dobj(3,tore,him).
case(3,pieces,to).
nmod:to(3,tore,pieces).
seized(3,lion,him).
tore(3,lion,him).
root(4,ROOT,leads).
amod(4,confidence,false).
nsubj(4,leads,confidence).
advmod(4,leads,often).
case(4,danger,into).
nmod:into(4,leads,danger).
leads_into(4,false_confidence,danger).
often_leads_into(4,false_confidence,danger).
