root(0,ROOT,was).
expl(0,was,there).
advmod(0,was,once).
det(0,man,a).
amod(0,man,bald).
nsubj(0,was,man).
nsubj(0,sat,man).
ref(0,man,who).
acl:relcl(0,man,sat).
compound:prt(0,sat,down).
case(0,work,after).
nmod:after(0,sat,work).
case(0,day,on).
det(0,summer,a).
amod(0,summer,hot).
nmod:poss(0,day,summer).
case(0,summer,'s).
nmod:on(0,sat,day).
on(0,hot_summer,day).
root(1,ROOT,came).
det(1,fly,a).
nsubj(1,came,fly).
nsubj(1,kept,fly).
advmod(1,came,up).
cc(1,came,and).
conj:and(1,came,kept).
ccomp(1,kept,buzzing).
case(1,pate,about).
nmod:poss(1,pate,his).
amod(1,pate,bald).
nmod:about(1,buzzing,pate).
cc(1,buzzing,and).
ccomp(1,kept,stinging).
conj:and(1,buzzing,stinging).
dobj(1,stinging,him).
case(1,time,from).
nmod:from(1,stinging,time).
case(1,time,to).
nmod:to(1,stinging,time).
root(2,ROOT,came).
det(2,man,the).
nsubj(2,came,man).
acl(2,man,aimed).
det(2,blow,a).
dobj(2,aimed,blow).
case(2,enemy,at).
nmod:poss(2,enemy,his).
amod(2,enemy,little).
nmod:at(2,aimed,enemy).
case(2,palm,but).
compound(2,palm,acks).
nmod:but(2,enemy,palm).
case(2,head,on).
nmod:poss(2,head,his).
nmod:on(2,came,head).
advmod(2,came,instead).
came_on(2,man,his_head).
came_instead_on(2,man,his_head).
aimed(2,man,blow).
aimed_blow_at(2,man,his_little_enemy).
aimed_blow_at(2,man,his_little_enemy_acks_palm).
aimed_blow_at(2,man,his_enemy_acks_palm).
aimed_blow_at(2,man,his_enemy).
root(3,ROOT,fly).
dep(3,fly,again).
det(3,fly,the).
ccomp(3,fly,tormented).
dobj(3,tormented,him).
case(3,time,but).
det(3,time,this).
nmod:but(3,tormented,time).
det(3,man,the).
nsubj(3,wiser,man).
cop(3,wiser,was).
acl:relcl(3,time,wiser).
cc(3,tormented,and).
ccomp(3,fly,said).
conj:and(3,tormented,said).
was(3,man,wiser).
root(4,ROOT,injure).
nsubj(4,injure,you).
aux(4,injure,will).
advmod(4,injure,only).
dobj(4,injure,yourself).
mark(4,take,if).
nsubj(4,take,you).
advcl:if(4,injure,take).
dobj(4,take,notice).
case(4,enemies,of).
amod(4,enemies,despicable).
nmod:of(4,notice,enemies).
will_only_injure(4,you,yourself).
notice_of(4,you,enemies).
take(4,you,notice_of_despicable_enemies).
take(4,you,notice_of_enemies).
take(4,you,notice).
will_injure(4,you,yourself).
notice_of(4,you,despicable_enemies).
