root(0,ROOT,went).
det(0,knight,a).
amod(0,knight,bald).
nsubj(0,wore,knight).
nsubj(0,went,knight).
ref(0,knight,who).
acl:relcl(0,knight,wore).
det(0,wig,a).
dobj(0,wore,wig).
advmod(0,went,out).
case(0,hunt,to).
nmod:to(0,went,hunt).
root(1,ROOT,blew).
det(1,puff,a).
amod(1,puff,sudden).
nsubj(1,blew,puff).
case(1,wind,of).
nmod:of(1,puff,wind).
compound:prt(1,blew,off).
nmod:poss(1,hat,his).
dobj(1,blew,hat).
nmod:at(1,rang,hat).
cc(1,hat,and).
dobj(1,blew,wig).
conj:and(1,hat,wig).
nmod:at(1,rang,wig).
case(1,which,at).
ref(1,hat,which).
det(1,laugh,a).
amod(1,laugh,loud).
nsubj(1,rang,laugh).
acl:relcl(1,hat,rang).
advmod(1,rang,forth).
case(1,companions,from).
nmod:poss(1,companions,his).
nmod:from(1,rang,companions).
rang_from(1,laugh,his_companions).
rang_forth_from(1,laugh,his_companions).
rang_forth_from(1,loud_laugh,his_companions).
rang_from(1,loud_laugh,his_companions).
root(2,ROOT,pulled).
nsubj(2,pulled,he).
nsubj(2,joined,he).
compound:prt(2,pulled,up).
nmod:poss(2,horse,his).
dobj(2,pulled,horse).
cc(2,pulled,and).
case(2,glee,with).
amod(2,glee,great).
nmod:with(2,joined,glee).
conj:and(2,pulled,joined).
case(2,joke,in).
det(2,joke,the).
nmod:in(2,joined,joke).
mark(2,saying,by).
advcl:by(2,joined,saying).
joined(2,he,saying).
joined_with(2,he,glee).
joined_with(2,he,great_glee).
pulled_up(2,he,his_horse).
joined_in(2,he,joke).
root(3,ROOT,marvel).
dobj(3,marvel,what).
nsubj(3,marvel,a).
nsubj(3,is,it).
ccomp(3,marvel,is).
mark(3,fly,that).
nsubj(3,mine,hairs).
nsubj(3,fly,hairs).
ref(3,hairs,which).
cop(3,mine,are).
neg(3,mine,not).
acl:relcl(3,hairs,mine).
aux(3,fly,should).
ccomp(3,is,fly).
case(3,me,from).
nmod:from(3,fly,me).
advmod(3,forsaken,when).
nsubj(3,forsaken,they).
aux(3,forsaken,have).
advcl(3,fly,forsaken).
advmod(3,man,even).
det(3,man,the).
dobj(3,forsaken,man).
mark(3,grew,on).
nmod:poss(3,head,whose).
dobj(3,grew,head).
nsubj(3,grew,they).
advcl:on(3,forsaken,grew).
