root(0,ROOT,contracted).
det(0,aethiop,the).
mark(0,arose,aethiop).
nsubj(0,contracted,aethiop).
det(0,purchaser,the).
nsubjpass(0,persuaded,purchaser).
case(0,servant,of).
det(0,servant,a).
amod(0,servant,black).
nmod:of(0,purchaser,servant).
auxpass(0,persuaded,was).
acl:relcl(0,aethiop,persuaded).
ref(0,aethiop,that).
det(0,color,the).
nsubj(0,arose,color).
case(0,skin,of).
nmod:poss(0,skin,his).
nmod:of(0,color,skin).
ccomp(0,persuaded,arose).
case(0,dirt,from).
nmod:from(0,arose,dirt).
case(0,neglect,through).
det(0,neglect,the).
nmod:through(0,contracted,neglect).
case(0,masters,of).
nmod:poss(0,masters,his).
amod(0,masters,former).
nmod:of(0,neglect,masters).
arose_from(0,color,dirt).
was(0,purchaser,persuaded).
root(1,ROOT,bringing).
mark(1,bringing,on).
iobj(1,bringing,him).
dobj(1,bringing,home).
nsubj(1,resorted,he).
acl:relcl(1,home,resorted).
case(1,means,to).
det(1,means,every).
nmod:to(1,resorted,means).
case(1,cleaning,of).
nmod:of(1,means,cleaning).
cc(1,bringing,and).
conj:and(1,bringing,subjected).
det(1,man,the).
dobj(1,subjected,man).
case(1,scrubbings,to).
amod(1,scrubbings,incessant).
nmod:to(1,subjected,scrubbings).
resorted_to(1,he,means_of_cleaning).
root(2,ROOT,caught).
det(2,servant,the).
nsubj(2,caught,servant).
det(2,cold,a).
amod(2,cold,severe).
dobj(2,caught,cold).
cc(2,changed,but).
nsubj(2,changed,he).
neg(2,changed,never).
dep(2,caught,changed).
nmod:poss(2,color,his).
dobj(2,changed,color).
cc(2,color,or).
dobj(2,changed,complexion).
conj:or(2,color,complexion).
caught(2,servant,severe_cold).
caught(2,servant,cold).
