root(0,ROOT,came).
det(0,ant,an).
nsubj(0,came,ant).
advmod(0,running,nimbly).
acl(0,ant,running).
advmod(0,running,about).
case(0,sunshine,in).
det(0,sunshine,the).
nmod:in(0,running,sunshine).
case(0,search,in).
nmod:in(0,sunshine,search).
case(0,food,of).
nmod:of(0,search,food).
case(0,chrysalis,across).
det(0,chrysalis,a).
nmod:across(0,came,chrysalis).
nsubj(0,very,chrysalis).
ref(0,chrysalis,that).
cop(0,very,was).
acl:relcl(0,chrysalis,very).
case(0,time,near).
nmod:poss(0,time,its).
nmod:near(0,very,time).
case(0,change,of).
nmod:of(0,time,change).
nimbly_running_about_in(0,ant,sunshine).
nimbly_running_in(0,ant,sunshine).
running_about_in(0,ant,sunshine).
running_in(0,ant,sunshine_search_food).
running_in(0,ant,sunshine_search).
running_in(0,ant,sunshine).
nimbly_running_about_in(0,ant,sunshine_search).
running_about_in(0,ant,sunshine_search).
running_about_in(0,ant,sunshine_search_food).
is_in(0,sunshine,search_of_food).
nimbly_running_about_in(0,ant,sunshine_search_food).
nimbly_running_in(0,ant,sunshine_search).
nimbly_running_in(0,ant,sunshine_search_food).
root(1,ROOT,moved).
det(1,chrysalis,the).
nsubj(1,moved,chrysalis).
nsubj(1,attracted,chrysalis).
nmod:poss(1,tail,its).
dobj(1,moved,tail).
cc(1,moved,and).
advmod(1,attracted,thus).
conj:and(1,moved,attracted).
det(1,attention,the).
dobj(1,attracted,attention).
case(1,ant,of).
det(1,ant,the).
nmod:of(1,attention,ant).
nsubj(1,saw,ant).
ref(1,ant,who).
advmod(1,saw,then).
acl:relcl(1,ant,saw).
case(1,time,for).
det(1,time,the).
amod(1,time,first).
nmod:for(1,saw,time).
mark(1,alive,that).
nsubj(1,alive,it).
cop(1,alive,was).
ccomp(1,saw,alive).
thus_attracted(1,chrysalis,attention).
was(1,it,alive).
moved(1,chrysalis,its_tail).
attracted(1,chrysalis,attention).
root(2,ROOT,animal).
amod(2,animal,poor).
amod(2,animal,pitiable).
root(3,ROOT,cried).
det(3,ant,the).
nsubj(3,cried,ant).
advmod(3,ant,disdainfully).
root(4,ROOT,yours).
dobj(4,yours,what).
det(4,fate,a).
amod(4,fate,sad).
nsubj(4,yours,fate).
cop(4,yours,is).
is(4,sad_fate,yours).
is(4,fate,yours).
root(5,ROOT,run).
mark(5,run,while).
nsubj(5,run,i).
aux(5,run,can).
advmod(5,run,hither).
cc(5,run,and).
advmod(5,pleasure,thither).
case(5,pleasure,at).
nmod:poss(5,pleasure,my).
dep(5,lie,pleasure).
cc(5,pleasure,and).
mark(5,wish,if).
nsubj(5,wish,i).
conj:and(5,pleasure,wish).
dep(5,lie,wish).
case(5,tree,ascend).
det(5,tree,the).
amod(5,tree,tallest).
nmod:ascend(5,wish,tree).
nsubj(5,lie,you).
conj:and(5,run,lie).
dep(5,lie,imprisoned).
advmod(5,imprisoned,here).
case(5,shell,in).
nmod:poss(5,shell,your).
nmod:in(5,imprisoned,shell).
case(5,power,with).
nmod:with(5,imprisoned,power).
advmod(5,power,only).
mark(5,move,to).
xcomp(5,imprisoned,move).
det(5,two,a).
amod(5,two,joint).
cc(5,two,or).
dobj(5,move,two).
case(5,tail,of).
nmod:poss(5,tail,your).
amod(5,tail,scaly).
nmod:of(5,two,tail).
imprisoned_here_in(5,you,your_shell).
imprisoned_with(5,you,power_only).
imprisoned_here_with(5,you,power).
imprisoned_here_with(5,you,power_only).
imprisoned_in(5,you,your_shell).
imprisoned_with(5,you,power).
root(6,ROOT,heard).
det(6,chrysalis,the).
nsubj(6,heard,chrysalis).
nsubj(6,try,chrysalis).
nsubj:xsubj(6,make,chrysalis).
det:predet(6,this,all).
dobj(6,heard,this).
cc(6,heard,but).
aux(6,try,did).
neg(6,try,not).
conj:but(6,heard,try).
mark(6,make,to).
xcomp(6,try,make).
det(6,reply,any).
dobj(6,make,reply).
root(7,ROOT,days).
det(7,days,a).
amod(7,days,few).
mark(7,passed,after).
advmod(7,passed,when).
det(7,ant,the).
nsubj(7,passed,ant).
dep(7,days,passed).
det(7,way,that).
dobj(7,passed,way).
advmod(7,passed,again).
dep(7,again,nothing).
cc(7,passed,but).
det(7,shell,the).
nsubj(7,remained,shell).
dep(7,days,remained).
conj:but(7,passed,remained).
root(8,ROOT,wondering).
nsubj(8,become,what).
nsubj(8,fanned,what).
aux(8,become,had).
ccomp(8,wondering,become).
case(8,contents,of).
nmod:poss(8,contents,its).
nmod:of(8,become,contents).
nsubj(8,felt,he).
acl:relcl(8,contents,felt).
dep(8,shaded,himself).
advmod(8,shaded,suddenly).
xcomp(8,felt,shaded).
cc(8,become,and).
ccomp(8,wondering,fanned).
conj:and(8,become,fanned).
case(8,wings,by).
det(8,wings,the).
amod(8,wings,gorgeous).
nmod:by(8,fanned,wings).
case(8,butterfly,of).
det(8,butterfly,a).
amod(8,butterfly,beautiful).
nmod:of(8,wings,butterfly).
felt(8,he,suddenly_shaded).
felt(8,he,shaded).
root(9,ROOT,behold).
case(9,me,in).
nmod:in(9,behold,me).
root(10,ROOT,said).
det(10,butterfly,the).
nsubj(10,said,butterfly).
root(11,ROOT,friend).
nmod:poss(11,friend,your).
amod(11,friend,much-pitied).
root(12,ROOT,boast).
advmod(12,powers,now).
case(12,powers,of).
nmod:poss(12,powers,your).
nmod:of(12,boast,powers).
mark(12,run,to).
acl:to(12,powers,run).
cc(12,run,and).
acl:to(12,powers,climb).
conj:and(12,run,climb).
advmod(12,long,as).
advmod(12,climb,long).
mark(12,get,as).
nsubj(12,get,you).
aux(12,get,can).
advcl:as(12,long,get).
dobj(12,get,me).
nsubj:xsubj(12,listen,me).
mark(12,listen,to).
xcomp(12,get,listen).
root(13,ROOT,and).
advmod(13,and,so).
dep(13,so,saying).
det(13,butterfly,the).
nsubj(13,rose,butterfly).
nsubj(13,borne,butterfly).
ccomp(13,saying,rose).
case(13,air,in).
det(13,air,the).
nmod:in(13,rose,air).
cc(13,rose,and).
ccomp(13,saying,borne).
conj:and(13,rose,borne).
advmod(13,borne,along).
advmod(13,breeze,aloft).
case(13,breeze,on).
det(13,breeze,the).
compound(13,breeze,summer).
conj(13,and,breeze).
auxpass(13,lost,was).
advmod(13,lost,soon).
acl:relcl(13,breeze,lost).
case(13,sight,to).
det(13,sight,the).
nmod:to(13,lost,sight).
case(13,ant,of).
det(13,ant,the).
nmod:of(13,sight,ant).
advmod(13,lost,forever).
