root(0,ROOT,came).
det(0,farmer,a).
nsubj(0,came,farmer).
nsubj:xsubj(0,see,farmer).
nsubj(0,carried,farmer).
nummod(0,day,one).
nmod:tmod(0,came,day).
case(0,stables,to).
det(0,stables,the).
nmod:to(0,came,stables).
mark(0,see,to).
xcomp(0,came,see).
case(0,beasts,to).
nmod:poss(0,beasts,his).
nmod:to(0,see,beasts).
case(0,burden,of).
nmod:of(0,beasts,burden).
mark(0,ass,among).
nsubj(0,ass,them).
cop(0,ass,was).
nmod:poss(0,ass,his).
amod(0,ass,favourite).
advcl:among(0,see,ass).
nsubjpass(0,fed,ass).
ref(0,ass,that).
auxpass(0,fed,was).
advmod(0,fed,always).
advmod(0,fed,well).
acl:relcl(0,ass,fed).
cc(0,came,and).
advmod(0,carried,often).
conj:and(0,came,carried).
nmod:poss(0,master,his).
dobj(0,carried,master).
came(0,farmer,see_to_his_beasts).
came(0,farmer,see_to_his_beasts_of_burden).
see_to(0,farmer,his_beasts).
came_at_time(0,farmer,one_day).
often_carried(0,farmer,his_master).
came(0,farmer,see).
came_to(0,farmer,stables).
carried(0,farmer,his_master).
see_to(0,farmer,his_beasts_of_burden).
root(1,ROOT,came).
mark(1,came,with).
det(1,farmer,the).
nsubj(1,came,farmer).
nsubj(1,frisked,farmer).
nmod:poss(1,lapdog,his).
dobj(1,came,lapdog).
nsubj(1,danced,lapdog).
nsubj(1,licked,lapdog).
ref(1,lapdog,who).
acl:relcl(1,lapdog,danced).
advmod(1,danced,about).
cc(1,danced,and).
acl:relcl(1,lapdog,licked).
conj:and(1,danced,licked).
nmod:poss(1,hand,his).
dobj(1,licked,hand).
cc(1,came,and).
conj:and(1,came,frisked).
advmod(1,happy,about).
advmod(1,happy,as).
xcomp(1,frisked,happy).
mark(1,be,as).
aux(1,be,could).
dep(1,happy,be).
frisked(1,farmer,happy).
frisked(1,farmer,about_as_happy).
frisked(1,farmer,as_happy).
frisked(1,farmer,about_happy).
root(2,ROOT,felt).
det(2,farmer,the).
nsubj(2,felt,farmer).
mark(2,gave,in).
nmod:poss(2,pocket,his).
nsubj(2,gave,pocket).
nsubj(2,sat,pocket).
advcl:in(2,felt,gave).
det(2,lapdog,the).
iobj(2,gave,lapdog).
det(2,food,some).
amod(2,food,dainty).
dobj(2,gave,food).
cc(2,gave,and).
advcl:in(2,felt,sat).
conj:and(2,gave,sat).
compound:prt(2,sat,down).
mark(2,gave,while).
nsubj(2,gave,he).
advcl:while(2,gave,gave).
nmod:poss(2,orders,his).
dobj(2,gave,orders).
case(2,servants,to).
nmod:poss(2,servants,his).
nmod:to(2,gave,servants).
gave(2,he,his_orders).
gave(2,his_pocket,food).
gave(2,his_pocket,dainty_food).
gave(2,his_pocket,lapdog).
root(3,ROOT,jumped).
det(3,lapdog,the).
nsubj(3,jumped,lapdog).
nsubj(3,lay,lapdog).
case(3,lap,into).
nmod:poss(3,master,his).
nmod:poss(3,lap,master).
case(3,master,'s).
nmod:into(3,jumped,lap).
cc(3,jumped,and).
conj:and(3,jumped,lay).
expl(3,stroked,there).
dep(3,stroked,blinking).
mark(3,stroked,while).
det(3,farmer,the).
nsubj(3,stroked,farmer).
xcomp(3,lay,stroked).
nmod:poss(3,ears,his).
dobj(3,stroked,ears).
into(3,master,lap).
stroked(3,farmer,his_ears).
jumped_into(3,lapdog,his_master_s_lap).
root(4,ROOT,broke).
det(4,ass,the).
nsubj(4,broke,ass).
nsubj(4,commenced,ass).
acl(4,ass,seeing).
dobj(4,seeing,this).
advmod(4,broke,loose).
case(4,halter,from).
nmod:poss(4,halter,his).
nmod:from(4,broke,halter).
cc(4,broke,and).
conj:and(4,broke,commenced).
xcomp(4,commenced,prancing).
advmod(4,prancing,about).
case(4,imitation,in).
nmod:in(4,prancing,imitation).
case(4,lapdog,of).
det(4,lapdog,the).
nmod:of(4,imitation,lapdog).
commenced(4,ass,prancing_in_imitation).
commenced(4,ass,prancing).
commenced(4,ass,prancing_about_in_imitation_of_lapdog).
commenced(4,ass,prancing_about_in_imitation).
commenced(4,ass,prancing_about).
broke_from(4,ass,his_halter).
broke_loose_from(4,ass,his_halter).
commenced(4,ass,prancing_in_imitation_of_lapdog).
root(5,ROOT,hold).
det(5,farmer,the).
nsubj(5,hold,farmer).
aux(5,hold,could).
neg(5,hold,not).
nmod:poss(5,sides,his).
dobj(5,hold,sides).
case(5,laughter,with).
nmod:with(5,hold,laughter).
mark(5,went,so).
det(5,ass,the).
nsubj(5,went,ass).
advcl:so(5,hold,went).
advmod(5,went,up).
case(5,him,to).
nmod:to(5,up,him).
cc(5,went,and).
csubj(5,attempted,putting).
nmod:poss(5,feet,his).
dobj(5,putting,feet).
case(5,shoulder,upon).
det(5,farmer,the).
nmod:poss(5,shoulder,farmer).
case(5,farmer,'s).
nmod:upon(5,putting,shoulder).
advcl:so(5,hold,attempted).
conj:and(5,went,attempted).
mark(5,climb,to).
xcomp(5,attempted,climb).
case(5,lap,into).
nmod:poss(5,lap,his).
nmod:into(5,climb,lap).
