root(0,ROOT,spending).
det(0,ants,the).
nsubj(0,spending,ants).
aux(0,spending,were).
det(0,winter,a).
amod(0,winter,fine).
nmod:poss(0,day,winter).
case(0,winter,'s).
dobj(0,spending,day).
acl(0,day,drying).
dobj(0,drying,grain).
acl(0,grain,collected).
case(0,summertime,in).
det(0,summertime,the).
nmod:in(0,collected,summertime).
were_spending(0,ants,winter_s_day).
were_spending(0,ants,fine_winter_s_day).
has(0,fine_winter,day_drying).
collected_in(0,grain,summertime).
root(1,ROOT,grasshopper).
det(1,grasshopper,a).
dep(1,grasshopper,perishing).
case(1,famine,with).
nmod:with(1,perishing,famine).
dep(1,famine,passed).
nmod(1,passed,by).
cc(1,passed,and).
advmod(1,begged,earnestly).
dep(1,famine,begged).
conj:and(1,passed,begged).
case(1,food,for).
det(1,food,a).
amod(1,food,little).
nmod:for(1,begged,food).
root(2,ROOT,inquired).
det(2,ants,the).
nsubj(2,inquired,ants).
case(2,him,of).
nmod:of(2,inquired,him).
inquired_of(2,ants,him).
root(3,ROOT,did).
advmod(3,did,why).
dobj(3,did,you).
neg(3,treasure,not).
nmod(3,did,treasure).
dep(3,food,up).
nmod(3,did,food).
case(3,summer,during).
det(3,summer,the).
nmod:during(3,food,summer).
root(4,ROOT,replied).
punct(4,replied,').
nsubj(4,replied,he).
root(5,ROOT,had).
advmod(5,had,i).
neg(5,leisure,not).
dobj(5,had,leisure).
nsubj(5,had,enough).
root(6,ROOT,passed).
nsubj(6,passed,i).
det(6,days,the).
nmod:tmod(6,passed,days).
case(6,singing,in).
nmod:in(6,passed,singing).
passed_at_time(6,i,days).
passed_in(6,i,singing).
root(7,ROOT,said).
nsubj(7,said,they).
advmod(7,said,then).
case(7,derision,in).
nmod:in(7,said,derision).
said_in(7,they,derision).
root(8,ROOT,foolish).
mark(8,foolish,if).
nsubj(8,foolish,you).
cop(8,foolish,were).
xcomp(8,foolish,enough).
mark(8,sing,to).
xcomp(8,enough,sing).
det:predet(8,summer,all).
det(8,summer,the).
dobj(8,sing,summer).
nsubj(8,dance,you).
aux(8,dance,must).
acl:relcl(8,summer,dance).
xcomp(8,dance,supperless).
case(8,bed,to).
nmod:to(8,supperless,bed).
case(8,winter,in).
det(8,winter,the).
nmod:in(8,dance,winter).
were(8,you,foolish).
