root(0,ROOT,saw).
det(0,feeding,an).
compound(0,feeding,ass).
nsubj(0,saw,feeding).
nsubj(0,pretended,feeding).
nsubj:xsubj(0,lame,feeding).
case(0,meadow,in).
det(0,meadow,a).
nmod:in(0,feeding,meadow).
det(0,wolf,a).
dobj(0,saw,wolf).
acl(0,wolf,approaching).
mark(0,seize,to).
xcomp(0,approaching,seize).
dobj(0,seize,him).
cc(0,saw,and).
advmod(0,pretended,immediately).
conj:and(0,saw,pretended).
mark(0,lame,to).
cop(0,lame,be).
xcomp(0,pretended,lame).
saw(0,ass_feeding,wolf_approaching).
saw(0,ass_feeding,wolf).
pretended(0,ass_feeding,lame).
immediately_pretended(0,ass_feeding,lame).
is_in(0,ass_feeding,meadow).
root(1,ROOT,inquired).
det(1,wolf,the).
nsubj(1,inquired,wolf).
acl(1,wolf,coming).
compound:prt(1,coming,up).
det(1,cause,the).
dobj(1,inquired,cause).
case(1,lameness,of).
nmod:poss(1,lameness,his).
nmod:of(1,cause,lameness).
inquired(1,wolf,cause_of_his_lameness).
inquired(1,wolf,cause).
root(2,ROOT,replied).
det(2,ass,the).
nsubj(2,replied,ass).
mark(2,passing,that).
ccomp(2,replied,passing).
case(2,hedge,through).
det(2,hedge,a).
nmod:through(2,passing,hedge).
nsubj(2,trod,he).
aux(2,trod,had).
acl:relcl(2,hedge,trod).
case(2,foot,with).
nmod:poss(2,foot,his).
nmod:with(2,trod,foot).
case(2,thorn,upon).
det(2,thorn,a).
amod(2,thorn,sharp).
nmod:upon(2,trod,thorn).
had_trod_upon(2,he,thorn).
had_trod_upon(2,he,sharp_thorn).
had_trod_with(2,he,his_foot).
root(3,ROOT,requested).
nsubj(3,requested,he).
mark(3,pull,that).
det(3,wolf,the).
nsubj(3,pull,wolf).
ccomp(3,requested,pull).
dobj(3,pull,it).
compound:prt(3,pull,out).
mark(3,injure,lest).
advmod(3,ate,when).
nsubj(3,ate,he).
advcl(3,injure,ate).
dobj(3,ate,him).
nsubj(3,injure,it).
aux(3,injure,should).
advcl:lest(3,pull,injure).
nmod:poss(3,throat,his).
dobj(3,injure,throat).
pull_out(3,wolf,it).
ate(3,he,him).
should_injure(3,it,his_throat).
root(4,ROOT,consented).
det(4,wolf,the).
nsubj(4,consented,wolf).
nsubj(4,lifted,wolf).
cc(4,consented,and).
conj:and(4,consented,lifted).
compound:prt(4,lifted,up).
det(4,foot,the).
dobj(4,lifted,foot).
cc(4,lifted,and).
aux(4,giving,was).
conj:and(4,consented,giving).
conj:and(4,lifted,giving).
nmod:poss(4,mind,his).
amod(4,mind,whole).
dobj(4,giving,mind).
case(4,discovery,to).
det(4,discovery,the).
nmod:to(4,giving,discovery).
case(4,thorn,of).
det(4,thorn,the).
nmod:of(4,discovery,thorn).
advmod(4,kicked,when).
det(4,ass,the).
nsubj(4,kicked,ass).
nsubj(4,galloped,ass).
case(4,heels,with).
nmod:poss(4,heels,his).
nmod:with(4,ass,heels).
acl:relcl(4,thorn,kicked).
nmod:poss(4,teeth,his).
dobj(4,kicked,teeth).
case(4,mouth,into).
nmod:poss(4,mouth,his).
nmod:into(4,kicked,mouth).
cc(4,kicked,and).
acl:relcl(4,thorn,galloped).
conj:and(4,kicked,galloped).
advmod(4,galloped,away).
is_with(4,ass,his_heels).
giving(4,foot,his_mind).
lifted_up(4,wolf,foot).
giving(4,foot,his_whole_mind).
kicked(4,ass,his_teeth).
ass_with(4,his_teeth,his_heels).
root(5,ROOT,said).
det(5,wolf,the).
nsubj(5,said,wolf).
auxpass(5,mauled,being).
advmod(5,mauled,thus).
advmod(5,mauled,fearfully).
acl(5,wolf,mauled).
root(6,ROOT,served).
nsubjpass(6,served,i).
auxpass(6,served,am).
advmod(6,served,rightly).
case(6,attempt,for).
advmod(6,attempt,why).
aux(6,attempt,did).
nsubj(6,attempt,i).
advcl:for(6,served,attempt).
det(6,art,the).
dobj(6,attempt,art).
case(6,healing,of).
nmod:of(6,art,healing).
advmod(6,taught,when).
nmod:poss(6,father,my).
nsubj(6,taught,father).
advmod(6,taught,only).
advcl(6,attempt,taught).
nsubj(6,trade,me).
det(6,trade,the).
xcomp(6,taught,trade).
case(6,butcher,of).
det(6,butcher,a).
nmod:of(6,trade,butcher).
taught(6,my_father,me_trade_of_butcher).
trade_of(6,me,butcher).
am(6,i,served).
art_of(6,i,healing).
taught(6,my_father,me_trade).
am(6,i,rightly_served).
only_taught(6,my_father,me_trade).
only_taught(6,my_father,me_trade_of_butcher).
