root(0,ROOT,went).
det(0,ass,the).
nsubj(0,went,ass).
cc(0,ass,and).
det(0,fox,the).
conj:and(0,ass,fox).
nsubj(0,went,fox).
aux(0,entered,having).
dep(0,fox,entered).
case(0,partnership,into).
nmod:into(0,entered,partnership).
advmod(0,protection,together).
case(0,protection,for).
nmod:poss(0,protection,their).
amod(0,protection,mutual).
nmod:for(0,entered,protection).
compound:prt(0,went,out).
case(0,forest,into).
det(0,forest,the).
nmod:into(0,went,forest).
case(0,hunt,to).
nmod:to(0,went,hunt).
went_out_into(0,fox,forest).
went_out_to(0,ass,hunt).
went_out_into(0,ass,forest).
went_out_to(0,fox,hunt).
root(1,ROOT,proceeded).
nsubj(1,proceeded,they).
aux(1,proceeded,had).
neg(1,proceeded,not).
advmod(1,when,far).
advmod(1,met,when).
nsubj(1,met,they).
advcl(1,proceeded,met).
det(1,lion,a).
dobj(1,met,lion).
root(2,ROOT,approached).
det(2,fox,the).
nsubj(2,approached,fox).
nsubj(2,promised,fox).
nsubj:xsubj(2,contrive,fox).
acl(2,fox,seeing).
amod(2,danger,imminent).
dobj(2,seeing,danger).
det(2,lion,the).
dobj(2,approached,lion).
cc(2,approached,and).
conj:and(2,approached,promised).
mark(2,contrive,to).
xcomp(2,promised,contrive).
case(2,him,for).
nmod:for(2,contrive,him).
det(2,capture,the).
dobj(2,contrive,capture).
case(2,ass,of).
det(2,ass,the).
nmod:of(2,capture,ass).
mark(2,pledge,if).
det(2,lion,the).
nsubj(2,pledge,lion).
aux(2,pledge,would).
dep(2,ass,pledge).
nmod:poss(2,word,his).
dobj(2,pledge,word).
neg(2,harm,not).
mark(2,harm,to).
acl:to(2,capture,harm).
det(2,fox,the).
dobj(2,harm,fox).
approached(2,fox,lion).
seeing(2,fox,danger).
would_pledge(2,lion,his_word).
seeing(2,fox,imminent_danger).
root(3,ROOT,then).
mark(3,assuring,upon).
dep(3,then,assuring).
det(3,ass,the).
dobj(3,assuring,ass).
mark(3,injured,that).
nsubjpass(3,injured,he).
aux(3,injured,would).
neg(3,injured,not).
auxpass(3,injured,be).
ccomp(3,assuring,injured).
det(3,fox,the).
nsubj(3,led,fox).
nsubj(3,arranged,fox).
ccomp(3,injured,led).
dobj(3,led,him).
case(3,pit,to).
det(3,pit,a).
amod(3,pit,deep).
nmod:to(3,led,pit).
cc(3,led,and).
ccomp(3,injured,arranged).
conj:and(3,led,arranged).
mark(3,fall,that).
nsubj(3,fall,he).
aux(3,fall,should).
ccomp(3,arranged,fall).
case(3,it,into).
nmod:into(3,fall,it).
root(4,ROOT,lion).
det(4,lion,the).
dep(4,lion,seeing).
mark(4,secured,that).
det(4,ass,the).
nsubjpass(4,secured,ass).
auxpass(4,secured,was).
ccomp(4,seeing,secured).
advmod(4,clutched,immediately).
ccomp(4,secured,clutched).
det(4,fox,the).
dobj(4,clutched,fox).
cc(4,clutched,and).
ccomp(4,secured,attacked).
conj:and(4,clutched,attacked).
det(4,ass,the).
dobj(4,attacked,ass).
case(4,leisure,at).
nmod:poss(4,leisure,his).
nmod:at(4,attacked,leisure).
was(4,ass,secured).
attacked_ass_at(4,fox,his_leisure).
attacked(4,fox,ass).
