root(0,ROOT,roamed).
det(0,ass,an).
nsubj(0,roamed,ass).
nsubj(0,amused,ass).
aux(0,put,having).
dep(0,ass,put).
case(0,skin,on).
det(0,lion,the).
nmod:poss(0,skin,lion).
case(0,lion,'s).
nmod:on(0,put,skin).
advmod(0,roamed,about).
case(0,forest,in).
det(0,forest,the).
nmod:in(0,roamed,forest).
cc(0,roamed,and).
conj:and(0,roamed,amused).
dobj(0,amused,himself).
case(0,frightening,by).
advcl:by(0,amused,frightening).
det:predet(0,animals,all).
det(0,animals,the).
amod(0,animals,foolish).
dobj(0,roamed,animals).
nsubj(0,met,he).
acl:relcl(0,animals,met).
case(0,wanderings,in).
nmod:poss(0,wanderings,his).
nmod:in(0,met,wanderings).
on(0,lion,skin).
amused(0,ass,himself).
root(1,ROOT,last).
case(1,last,at).
amod(1,last,coming).
case(1,fox,upon).
det(1,fox,a).
nmod:upon(1,last,fox).
nsubj(1,tried,he).
nsubj:xsubj(1,frighten,he).
acl:relcl(1,fox,tried).
mark(1,frighten,to).
xcomp(1,tried,frighten).
dobj(1,frighten,him).
advmod(1,frighten,also).
cc(1,tried,but).
det(1,fox,the).
nsubj(1,heard,fox).
neg(1,sooner,no).
advmod(1,heard,sooner).
acl:relcl(1,fox,heard).
conj:but(1,tried,heard).
det(1,sound,the).
dobj(1,heard,sound).
case(1,voice,of).
nmod:poss(1,voice,his).
nmod:of(1,sound,voice).
mark(1,exclaimed,than).
nsubj(1,exclaimed,he).
advcl:than(1,heard,exclaimed).
heard(1,fox,sound_of_his_voice).
heard(1,fox,sound).
heard_sound(1,fox,he_exclaimed).
frighten(1,he,him).
frighten_also(1,he,him).
sound_of(1,fox,his_voice).
root(2,ROOT,frightened).
advmod(2,frightened,i).
aux(2,frightened,might).
advmod(2,frightened,possibly).
aux(2,frightened,have).
cop(2,frightened,been).
nsubj(2,frightened,myself).
mark(2,heard,if).
nsubj(2,heard,i).
aux(2,heard,had).
neg(2,heard,not).
dep(2,frightened,heard).
nmod:poss(2,bray,your).
dobj(2,heard,bray).
