root(0,ROOT,enchanted).
det(0,ass,an).
nsubj(0,enchanted,ass).
aux(0,heard,having).
dep(0,ass,heard).
det(0,grasshoppers,some).
dobj(0,heard,grasshoppers).
acl(0,grasshoppers,chirping).
cop(0,enchanted,was).
advmod(0,enchanted,highly).
was(0,ass,highly_enchanted).
was(0,ass,enchanted).
root(1,ROOT,desiring).
cc(1,desiring,and).
mark(1,possess,to).
xcomp(1,desiring,possess).
det(1,charms,the).
amod(1,charms,same).
nsubj(1,demanded,charms).
case(1,melody,of).
nmod:of(1,charms,melody).
ccomp(1,possess,demanded).
det(1,sort,what).
dobj(1,demanded,sort).
case(1,food,of).
nmod:of(1,sort,food).
nsubj(1,lived,they).
nsubj:xsubj(1,give,they).
acl:relcl(1,sort,lived).
nmod(1,lived,on).
mark(1,give,to).
xcomp(1,lived,give).
iobj(1,give,them).
amod(1,voices,such).
amod(1,voices,beautiful).
dobj(1,give,voices).
give(1,they,voices).
give(1,they,such_beautiful_voices).
give(1,they,them).
give(1,they,such_voices).
give(1,they,beautiful_voices).
root(2,ROOT,replied).
nsubj(2,replied,they).
root(3,ROOT,dew).
det(3,dew,the).
root(4,ROOT,resolved).
det(4,ass,the).
nsubj(4,resolved,ass).
mark(4,live,that).
nsubj(4,live,he).
aux(4,live,would).
advcl:that(4,resolved,live).
advmod(4,live,only).
case(4,dew,upon).
nmod:upon(4,live,dew).
cc(4,live,and).
mark(4,died,in).
det(4,time,a).
amod(4,time,short).
nsubj(4,died,time).
advcl:that(4,resolved,died).
conj:and(4,live,died).
case(4,hunger,of).
nmod:of(4,died,hunger).
died_of(4,time,hunger).
resolved(4,ass,he_would_live_only).
would_live_upon(4,he,dew).
would_live_only_upon(4,he,dew).
died_of(4,short_time,hunger).
resolved(4,ass,he_would_live_only_upon_dew).
resolved(4,ass,he_would_live).
resolved(4,ass,he_would_live_upon_dew).
