root(0,ROOT,hired).
det(0,traveler,a).
nsubj(0,hired,traveler).
det(0,ass,an).
dobj(0,hired,ass).
mark(0,convey,to).
acl:to(0,ass,convey).
dobj(0,convey,him).
case(0,place,to).
det(0,place,a).
amod(0,place,distant).
nmod:to(0,convey,place).
root(1,ROOT,day).
dep(1,day,the).
cop(1,hot,being).
advmod(1,hot,intensely).
acl(1,day,hot).
cc(1,day,and).
det(1,sun,the).
conj:and(1,day,sun).
acl(1,sun,shining).
case(1,strength,in).
nmod:poss(1,strength,its).
nmod:in(1,shining,strength).
det(1,traveler,the).
nsubj(1,stopped,traveler).
nsubj:xsubj(1,rest,traveler).
nsubj(1,sought,traveler).
acl:relcl(1,strength,stopped).
mark(1,rest,to).
xcomp(1,stopped,rest).
cc(1,stopped,and).
acl:relcl(1,strength,sought).
conj:and(1,stopped,sought).
dobj(1,sought,shelter).
case(1,heat,from).
det(1,heat,the).
nmod:from(1,sought,heat).
case(1,shadow,under).
det(1,shadow,the).
nmod:under(1,sought,shadow).
case(1,ass,of).
det(1,ass,the).
nmod:of(1,shadow,ass).
sought_shelter_from(1,traveler,heat).
stopped(1,traveler,rest).
sought(1,traveler,shelter).
sought_shelter_under(1,traveler,shadow_of_ass).
sought_shelter_under(1,traveler,shadow).
root(2,ROOT,afforded).
mark(2,afforded,as).
nsubj(2,afforded,this).
nsubj(2,afforded,this).
nsubj(2,claimed,this).
conj:and(2,afforded,afforded).
advmod(2,protection,only).
dobj(2,afforded,protection).
case(2,one,for).
nmod:for(2,afforded,one).
cc(2,afforded,and).
case(2,traveler,as).
det(2,traveler,the).
nmod:as(2,afforded,traveler).
cc(2,traveler,and).
det(2,owner,the).
nmod:as(2,afforded,owner).
conj:and(2,traveler,owner).
case(2,ass,of).
det(2,ass,the).
nmod:of(2,owner,ass).
dep(2,afforded,both).
conj:and(2,afforded,claimed).
dobj(2,claimed,it).
det(2,dispute,a).
amod(2,dispute,violent).
nsubj(2,arose,dispute).
dep(2,claimed,arose).
case(2,them,between).
nmod:between(2,arose,them).
case(2,had,as).
mark(2,had,to).
nsubj(2,had,which).
case(2,them,of).
nmod:of(2,had,them).
dep(2,arose,had).
det(2,right,the).
dobj(2,had,right).
case(2,shadow,to).
det(2,shadow,the).
nmod:to(2,right,shadow).
claimed(2,protection,it).
root(3,ROOT,maintained).
det(3,owner,the).
nsubj(3,maintained,owner).
mark(3,had,that).
nsubj(3,had,he).
ccomp(3,maintained,had).
ccomp(3,had,let).
det(3,ass,the).
dobj(3,let,ass).
advmod(3,not,only).
cc(3,not,and).
advcl(3,let,not).
nmod:poss(3,shadow,his).
dep(3,not,shadow).
root(4,ROOT,asserted).
det(4,traveler,the).
nsubj(4,asserted,traveler).
mark(4,had,that).
nsubj(4,had,he).
ccomp(4,asserted,had).
mark(4,hired,with).
det(4,hire,the).
nsubj(4,hired,hire).
case(4,ass,of).
det(4,ass,the).
nmod:of(4,hire,ass).
advcl:with(4,had,hired).
nmod:poss(4,shadow,his).
dobj(4,hired,shadow).
advmod(4,hired,also).
root(5,ROOT,quarrel).
dep(5,quarrel,the).
advcl(5,quarrel,proceeded).
case(5,words,from).
nmod:from(5,proceeded,words).
case(5,blows,to).
nmod:to(5,proceeded,blows).
cc(5,proceeded,and).
mark(5,fought,while).
det(5,men,the).
nsubj(5,fought,men).
advcl(5,quarrel,fought).
conj:and(5,proceeded,fought).
det(5,ass,the).
nsubj(5,galloped,ass).
ccomp(5,fought,galloped).
compound:prt(5,galloped,off).
