root(0,ROOT,point).
det(0,ant,an).
nsubj(0,point,ant).
dep(0,ant,went).
case(0,bank,to).
det(0,bank,the).
nmod:to(0,went,bank).
case(0,river,of).
det(0,river,a).
nmod:of(0,bank,river).
mark(0,quench,to).
xcomp(0,went,quench).
nmod:poss(0,thirst,its).
dobj(0,quench,thirst).
cc(0,went,and).
auxpass(0,carried,being).
dep(0,ant,carried).
conj:and(0,went,carried).
advmod(0,carried,away).
case(0,rush,by).
det(0,rush,the).
nmod:agent(0,carried,rush).
case(0,stream,of).
det(0,stream,the).
nmod:of(0,rush,stream).
cop(0,point,was).
case(0,point,on).
det(0,point,the).
case(0,drowning,of).
nmod:of(0,point,drowning).
was_on(0,ant,point_of_drowning).
was_on(0,ant,point).
root(1,ROOT,plucked).
det(1,dove,a).
nsubj(1,plucked,dove).
nsubj(1,let,dove).
acl(1,dove,sitting).
case(1,tree,on).
det(1,tree,a).
nmod:on(1,sitting,tree).
acl(1,tree,overhanging).
det(1,water,the).
dobj(1,overhanging,water).
det(1,leaf,a).
dobj(1,plucked,leaf).
cc(1,plucked,and).
conj:and(1,plucked,let).
nsubj(1,fall,it).
ccomp(1,let,fall).
case(1,close,into).
det(1,close,the).
compound(1,close,stream).
nmod:into(1,fall,close).
case(1,her,to).
nmod:to(1,fall,her).
fall_to(1,it,her).
fall_into(1,it,stream_close).
plucked(1,dove,leaf).
root(2,ROOT,climbed).
det(2,ant,the).
nsubj(2,climbed,ant).
nsubj(2,floated,ant).
case(2,it,onto).
nmod:onto(2,climbed,it).
cc(2,climbed,and).
conj:and(2,climbed,floated).
case(2,safety,in).
nmod:in(2,floated,safety).
case(2,bank,to).
det(2,bank,the).
nmod:to(2,floated,bank).
floated_to(2,ant,bank).
climbed_onto(2,ant,it).
floated_in(2,ant,safety).
root(3,ROOT,came).
advmod(3,came,shortly).
advmod(3,birdcatcher,afterwards).
det(3,birdcatcher,a).
advmod(3,came,birdcatcher).
cc(3,came,and).
conj:and(3,came,stood).
case(3,tree,under).
det(3,tree,the).
nmod:under(3,came,tree).
cc(3,came,and).
conj:and(3,came,laid).
nmod:poss(3,lime-twigs,his).
dobj(3,laid,lime-twigs).
case(3,the,for).
nmod:for(3,laid,the).
amod(3,the,dove).
nsubj(3,sat,which).
dep(3,came,sat).
case(3,branches,in).
det(3,branches,the).
nmod:in(3,sat,branches).
root(4,ROOT,stung).
det(4,ant,the).
nsubj(4,stung,ant).
acl(4,ant,perceiving).
nmod:poss(4,design,his).
dobj(4,perceiving,design).
dobj(4,stung,him).
case(4,foot,in).
det(4,foot,the).
nmod:in(4,stung,foot).
perceiving(4,ant,his_design).
stung(4,ant,him).
root(5,ROOT,threw).
case(5,pain,in).
nmod:in(5,threw,pain).
det(5,birdcatcher,the).
nsubj(5,threw,birdcatcher).
compound:prt(5,threw,down).
det(5,twigs,the).
nsubj(5,made,twigs).
cc(5,twigs,and).
det(5,noise,the).
conj:and(5,twigs,noise).
nsubj(5,made,noise).
ccomp(5,threw,made).
nsubj(5,take,the).
amod(5,the,dove).
ccomp(5,made,take).
dobj(5,take,wing).
threw_down_in(5,birdcatcher,pain).
take(5,the_dove,wing).
take(5,the,wing).
