root(0,ROOT,started).
det(0,ass,an).
nsubj(0,started,ass).
nsubj(0,bolted,ass).
auxpass(0,driven,being).
acl(0,ass,driven).
case(0,road,along).
det(0,road,a).
amod(0,road,high).
nmod:along(0,driven,road).
advmod(0,started,suddenly).
compound:prt(0,started,off).
cc(0,started,and).
conj:and(0,started,bolted).
case(0,brink,to).
det(0,brink,the).
nmod:to(0,bolted,brink).
case(0,precipice,of).
det(0,precipice,a).
amod(0,precipice,deep).
nmod:of(0,brink,precipice).
bolted_to(0,ass,brink_of_precipice).
bolted_to(0,ass,brink).
bolted_to(0,ass,brink_of_deep_precipice).
root(1,ROOT,act).
mark(1,act,while).
nsubj(1,act,he).
cop(1,act,was).
case(1,act,in).
det(1,act,the).
mark(1,throwing,of).
acl:of(1,act,throwing).
dobj(1,throwing,himself).
compound:prt(1,throwing,over).
nmod:poss(1,owner,his).
nsubj(1,seized,owner).
acl:relcl(1,act,seized).
dobj(1,seized,him).
case(1,tail,by).
det(1,tail,the).
nmod:by(1,seized,tail).
acl(1,tail,endeavoring).
mark(1,pull,to).
xcomp(1,endeavoring,pull).
dobj(1,pull,him).
advmod(1,pull,back).
seized(1,his_owner,him).
root(2,ROOT,persisted).
advmod(2,persisted,when).
det(2,ass,the).
nsubj(2,persisted,ass).
nsubj(2,said,ass).
case(2,effort,in).
nmod:poss(2,effort,his).
nmod:in(2,persisted,effort).
det(2,man,the).
nsubj(2,let,man).
acl:relcl(2,effort,let).
nsubj(2,go,him).
ccomp(2,let,go).
cc(2,persisted,and).
conj:and(2,persisted,said).
root(3,ROOT,conquer).
cc(3,conquer,but).
conj:but(3,conquer,conquer).
case(3,cost,to).
nmod:poss(3,cost,your).
nmod:to(3,conquer,cost).
