root(0,ROOT,congratulated).
det(0,ass,an).
nsubj(0,congratulated,ass).
det(0,horse,a).
dobj(0,congratulated,horse).
mark(0,ungrudgingly,on).
auxpass(0,ungrudgingly,being).
advmod(0,ungrudgingly,so).
advcl:on(0,congratulated,ungrudgingly).
cc(0,ungrudgingly,and).
advmod(0,provided,carefully).
advcl:on(0,congratulated,provided).
conj:and(0,ungrudgingly,provided).
mark(0,enough,for).
case(0,he,while).
nmod:while(0,enough,he).
nsubj(0,enough,himself).
nsubj:xsubj(0,eat,himself).
aux(0,enough,had).
advmod(0,enough,scarcely).
ccomp(0,provided,enough).
mark(0,eat,to).
xcomp(0,enough,eat).
cc(0,eat,and).
xcomp(0,enough,not).
conj:and(0,eat,not).
advmod(0,that,even).
nmod(0,eat,that).
case(0,work,without).
amod(0,work,hard).
nmod:without(0,enough,work).
enough_while(0,himself,he).
scarcely_enough_while(0,himself,he).
scarcely_enough_without(0,himself,hard_work).
enough_without(0,himself,work).
congratulated_horse(0,ass,so_ungrudgingly).
enough_without(0,himself,hard_work).
congratulated(0,ass,horse).
scarcely_enough_without(0,himself,work).
scarcely_enough(0,himself,eat_that).
enough(0,himself,eat_that).
enough(0,himself,eat).
scarcely_enough(0,himself,eat).
enough(0,himself,eat_even_that).
congratulated_horse(0,ass,ungrudgingly).
scarcely_enough(0,himself,eat_even_that).
root(1,ROOT,broke).
cc(1,broke,but).
advmod(1,broke,when).
nsubj(1,broke,war).
compound:prt(1,broke,out).
det(1,soldier,a).
advmod(1,armed,heavily).
amod(1,soldier,armed).
dobj(1,broke,soldier).
acl:relcl(1,soldier,mounted).
det(1,horse,the).
dobj(1,mounted,horse).
cc(1,broke,and).
csubj(1,rushed,riding).
dobj(1,riding,him).
case(1,charge,to).
det(1,charge,the).
nmod:to(1,riding,charge).
conj:and(1,broke,rushed).
case(1,midst,into).
det(1,midst,the).
advmod(1,midst,very).
nmod:into(1,rushed,midst).
case(1,enemy,of).
det(1,enemy,the).
nmod:of(1,midst,enemy).
root(2,ROOT,wounded).
det(2,horse,the).
nsubjpass(2,wounded,horse).
nsubjpass(2,fell,horse).
auxpass(2,wounded,was).
cc(2,wounded,and).
conj:and(2,wounded,fell).
xcomp(2,fell,dead).
case(2,battlefield,on).
det(2,battlefield,the).
nmod:on(2,fell,battlefield).
was(2,horse,wounded).
fell(2,horse,dead).
fell_on(2,horse,battlefield).
root(3,ROOT,changed).
advmod(3,ass,then).
det(3,ass,the).
nsubj(3,changed,ass).
nsubj(3,commiserated,ass).
acl(3,ass,seeing).
det:predet(3,things,all).
det(3,things,these).
dobj(3,seeing,things).
nmod:poss(3,mind,his).
dobj(3,changed,mind).
cc(3,changed,and).
conj:and(3,changed,commiserated).
det(3,horse,the).
dobj(3,commiserated,horse).
changed(3,ass,his_mind).
commiserated(3,ass,horse).
