root(0,ROOT,set).
det(0,set,a).
amod(0,set,muleteer).
advmod(0,journey,forth).
case(0,journey,on).
det(0,journey,a).
nmod:on(0,set,journey).
acl(0,journey,driving).
case(0,him,before).
nmod:before(0,driving,him).
det(0,ass,an).
dep(0,him,ass).
cc(0,ass,and).
det(0,mule,a).
dep(0,him,mule).
conj:and(0,ass,mule).
cc:preconj(0,ass,both).
advmod(0,laden,well).
dep(0,him,laden).
conj:and(0,ass,laden).
root(1,ROOT,felt).
det(1,ass,the).
nsubj(1,felt,ass).
advmod(1,long,as).
advmod(1,traveled,long).
mark(1,traveled,as).
nsubj(1,traveled,he).
dep(1,ass,traveled).
case(1,plain,along).
det(1,plain,the).
nmod:along(1,traveled,plain).
acl(1,plain,carried).
nmod:poss(1,load,his).
dobj(1,carried,load).
case(1,ease,with).
nmod:with(1,carried,ease).
cc(1,traveled,but).
advmod(1,began,when).
nsubj(1,began,he).
nsubj:xsubj(1,ascend,he).
dep(1,ass,began).
conj:but(1,traveled,began).
mark(1,ascend,to).
xcomp(1,began,ascend).
det(1,path,the).
amod(1,path,steep).
dobj(1,ascend,path).
case(1,mountain,of).
det(1,mountain,the).
nmod:of(1,path,mountain).
nmod:poss(1,load,his).
dobj(1,felt,load).
mark(1,more,to).
cop(1,more,be).
acl:to(1,load,more).
mark(1,bear,than).
nsubj(1,bear,he).
aux(1,bear,could).
ccomp(1,more,bear).
ascend(1,he,steep_path).
ascend(1,he,steep_path_of_mountain).
carried(1,plain,his_load).
carried_his_load_with(1,plain,ease).
ascend(1,he,path).
ascend(1,he,path_of_mountain).
root(2,ROOT,entreated).
nsubj(2,entreated,he).
nmod:poss(2,companion,his).
dobj(2,entreated,companion).
mark(2,relieve,to).
acl:to(2,companion,relieve).
dobj(2,relieve,him).
case(2,portion,of).
det(2,portion,a).
amod(2,portion,small).
nmod:of(2,relieve,portion).
mark(2,carry,that).
nsubj(2,carry,he).
aux(2,carry,might).
ccomp(2,relieve,carry).
advmod(2,carry,home).
det(2,rest,the).
dobj(2,carry,rest).
carry_home(2,he,rest).
carry(2,he,rest).
root(3,ROOT,paid).
cc(3,paid,but).
det(3,mule,the).
nsubj(3,paid,mule).
neg(3,attention,no).
dobj(3,paid,attention).
case(3,request,to).
det(3,request,the).
nmod:to(3,paid,request).
root(4,ROOT,fell).
det(4,ass,the).
nmod:npmod(4,shortly,ass).
advmod(4,fell,shortly).
advmod(4,fell,afterwards).
compound:prt(4,fell,down).
nsubj(4,fell,dead).
case(4,burden,under).
nmod:poss(4,burden,his).
nmod:under(4,dead,burden).
root(5,ROOT,knowing).
neg(5,knowing,not).
nsubj(5,do,what).
dep(5,do,else).
mark(5,do,to).
xcomp(5,knowing,do).
case(5,region,in).
advmod(5,wild,so).
amod(5,region,wild).
det(5,region,a).
nmod:in(5,do,region).
det(5,muleteer,the).
dobj(5,do,muleteer).
acl(5,muleteer,placed).
case(5,mule,upon).
det(5,mule,the).
nmod:upon(5,placed,mule).
det(5,load,the).
nsubj(5,placed,load).
acl(5,load,carried).
acl(5,load,carried).
conj:and(5,carried,carried).
case(5,ass,by).
det(5,ass,the).
nmod:by(5,carried,ass).
case(5,addition,in).
nmod:in(5,ass,addition).
case(5,own,to).
nmod:poss(5,own,his).
nmod:to(5,carried,own).
cc(5,carried,and).
case(5,top,at).
det(5,top,the).
nmod:at(5,carried,top).
case(5,all,of).
nmod:of(5,top,all).
acl:relcl(5,mule,placed).
nsubj(5,hide,the).
ccomp(5,placed,hide).
case(5,ass,of).
det(5,ass,the).
nmod:of(5,hide,ass).
mark(5,skinned,after).
nsubj(5,skinned,he).
aux(5,skinned,had).
advcl:after(5,hide,skinned).
dobj(5,skinned,him).
root(6,ROOT,said).
det(6,mule,the).
nsubj(6,said,mule).
acl(6,mule,groaning).
case(6,burden,beneath).
nmod:poss(6,burden,his).
amod(6,burden,heavy).
nmod:beneath(6,groaning,burden).
case(6,himself,to).
nmod:to(6,said,himself).
said_to(6,mule,himself).
root(7,ROOT,treated).
nsubjpass(7,treated,i).
auxpass(7,treated,am).
case(7,deserts,according).
mwe(7,according,to).
nmod:poss(7,deserts,my).
nmod:according_to(7,treated,deserts).
am_treated_according_to(7,i,my_deserts).
am(7,i,treated).
root(8,ROOT,willing).
mark(8,willing,if).
nsubj(8,willing,i).
nsubj:xsubj(8,assist,i).
aux(8,willing,had).
advmod(8,willing,only).
cop(8,willing,been).
mark(8,assist,to).
xcomp(8,willing,assist).
det(8,ass,the).
dobj(8,assist,ass).
det(8,little,a).
nmod:in(8,assist,little).
case(8,little,in).
nmod:poss(8,need,his).
dep(8,little,need).
nsubj(8,bearing,i).
aux(8,bearing,should).
neg(8,bearing,not).
advmod(8,bearing,now).
aux(8,bearing,be).
acl:relcl(8,need,bearing).
advmod(8,bearing,together).
case(8,burden,with).
nmod:poss(8,burden,his).
nmod:with(8,bearing,burden).
nmod:npmod(8,burden,himself).
advmod(8,bearing,as).
mwe(8,as,well).
assist_ass_in(8,i,little).
had(8,i,had_only_willing).
assist(8,i,ass).
had(8,i,had_willing).
