root(0,ROOT,used).
det(0,astronomer,an).
nsubj(0,used,astronomer).
nsubj:xsubj(0,go,astronomer).
mark(0,go,to).
xcomp(0,used,go).
compound:prt(0,go,out).
case(0,night,at).
nmod:at(0,go,night).
mark(0,observe,to).
xcomp(0,go,observe).
det(0,stars,the).
dobj(0,observe,stars).
go_out_at(0,astronomer,night).
root(1,ROOT,evening).
nummod(1,evening,one).
mark(1,wandered,as).
nsubj(1,wandered,he).
dep(1,evening,wandered).
case(1,suburbs,through).
det(1,suburbs,the).
nmod:through(1,wandered,suburbs).
case(1,attention,with).
nmod:poss(1,attention,his).
amod(1,attention,whole).
nmod:with(1,wandered,attention).
acl(1,attention,fixed).
case(1,sky,on).
det(1,sky,the).
nmod:on(1,fixed,sky).
nsubj(1,fell,he).
acl:relcl(1,sky,fell).
advmod(1,fell,accidentally).
case(1,well,into).
dep(1,well,a).
advmod(1,well,deep).
advcl:into(1,fell,well).
wandered_with(1,he,his_whole_attention).
wandered_through(1,he,suburbs).
fell_into(1,he,deep_well).
wandered_with(1,he,his_attention).
wandered_with(1,he,his_attention_fixed).
fell_accidentally_into(1,he,well).
fell_into(1,he,well).
fell_accidentally_into(1,he,deep_well).
wandered_with(1,he,his_whole_attention_fixed).
root(2,ROOT,lamented).
mark(2,lamented,while).
nsubj(2,lamented,he).
nsubj(2,bewailed,he).
nsubj(2,cried,he).
cc(2,lamented,and).
conj:and(2,lamented,bewailed).
nmod:poss(2,sores,his).
dobj(2,lamented,sores).
cc(2,sores,and).
dobj(2,lamented,bruises).
conj:and(2,sores,bruises).
cc(2,lamented,and).
conj:and(2,lamented,cried).
advmod(2,ran,loudly).
case(2,help,for).
nmod:for(2,loudly,help).
det(2,neighbor,a).
nsubj(2,ran,neighbor).
dep(2,cried,ran).
case(2,well,to).
det(2,well,the).
nmod:to(2,ran,well).
cc(2,ran,and).
csubj(2,said,learning).
nsubj(2,happened,what).
aux(2,happened,had).
ccomp(2,learning,happened).
dep(2,cried,said).
conj:and(2,ran,said).
lamented(2,he,his_sores).
lamented(2,he,bruises).
root(3,ROOT,hark).
nmod:npmod(3,old,ye).
amod(3,fellow,old).
dep(3,hark,fellow).
advmod(3,do,why).
mark(3,striving,in).
csubj(3,do,striving).
mark(3,pry,to).
xcomp(3,striving,pry).
mark(3,heaven,into).
nsubj(3,heaven,what).
cop(3,heaven,is).
case(3,heaven,in).
advcl:in(3,pry,heaven).
dep(3,hark,do).
nsubj(3,manage,you).
nsubj:xsubj(3,see,you).
neg(3,manage,not).
ccomp(3,do,manage).
mark(3,see,to).
xcomp(3,manage,see).
nsubj(3,earth,what).
cop(3,earth,is).
case(3,earth,on).
ccomp(3,see,earth).
