root(0,ROOT,came).
nummod(0,men,two).
nsubj(0,spoke,men).
nsubj(0,came,men).
nsubj(0,spoke,one).
nsubj(0,traveling,one).
ref(0,men,who).
ref(0,one,who).
advmod(0,spoke,always).
acl:relcl(0,one,spoke).
det(0,truth,the).
dobj(0,spoke,truth).
cc(0,truth,and).
det(0,other,the).
dobj(0,spoke,other).
conj:and(0,truth,other).
nsubj(0,told,other).
ref(0,other,who).
acl:relcl(0,other,told).
dobj(0,told,nothing).
case(0,lies,but).
nmod:but(0,nothing,lies).
aux(0,traveling,were).
acl:relcl(0,men,traveling).
advmod(0,and,together).
advmod(0,traveling,and).
case(0,chance,by).
conj(0,and,chance).
case(0,land,to).
det(0,land,the).
nmod:to(0,came,land).
case(0,apes,of).
nmod:of(0,land,apes).
root(1,ROOT,commanded).
det:qmod(1,apes,one).
mwe(1,one,of).
det(1,apes,the).
nsubj(1,raised,apes).
nsubj(1,commanded,apes).
ref(1,apes,who).
aux(1,raised,had).
acl:relcl(1,apes,raised).
dobj(1,raised,himself).
nsubj:xsubj(1,king,himself).
mark(1,king,to).
cop(1,king,be).
xcomp(1,raised,king).
dobj(1,commanded,them).
nsubjpass:xsubj(1,seized,them).
mark(1,seized,to).
auxpass(1,seized,be).
xcomp(1,commanded,seized).
cc(1,seized,and).
xcomp(1,commanded,brought).
conj:and(1,seized,brought).
advmod(1,him,before).
nmod(1,seized,him).
mark(1,know,that).
nsubj(1,know,he).
aux(1,know,might).
ccomp(1,commanded,know).
nsubjpass(1,said,what).
auxpass(1,said,was).
ccomp(1,know,said).
case(1,him,of).
nmod:of(1,said,him).
case(1,men,among).
nmod:among(1,said,men).
be(1,himself,king).
root(2,ROOT,ordered).
nsubj(2,ordered,he).
case(2,time,at).
det(2,time,the).
amod(2,time,same).
nmod:at(2,ordered,time).
mark(2,arranged,that).
det:predet(2,apes,all).
det(2,apes,the).
nsubjpass(2,arranged,apes).
nsubjpass(2,arranged,apes).
auxpass(2,arranged,be).
ccomp(2,ordered,arranged).
ccomp(2,ordered,arranged).
conj:and(2,arranged,arranged).
case(2,row,in).
det(2,row,a).
amod(2,row,long).
nmod:in(2,arranged,row).
case(2,hand,on).
nmod:poss(2,hand,his).
amod(2,hand,right).
nmod:on(2,row,hand).
cc(2,arranged,and).
case(2,left,on).
nmod:poss(2,left,his).
nmod:on(2,arranged,left).
cc(2,arranged,and).
mark(2,placed,that).
det(2,throne,a).
nsubjpass(2,placed,throne).
auxpass(2,placed,be).
ccomp(2,ordered,placed).
conj:and(2,arranged,placed).
case(2,him,for).
nmod:for(2,placed,him).
advmod(2,custom,as).
cop(2,custom,was).
det(2,custom,the).
ccomp(2,placed,custom).
case(2,men,among).
nmod:among(2,custom,men).
be(2,apes,arranged_in_row_on_his_left).
be(2,apes,arranged_in_row_on_his_hand_on_his_left).
ordered_at(2,he,same_time).
be(2,throne,placed).
be(2,apes,arranged_in_row_on_his_right_hand_on_his_left).
be(2,apes,arranged).
be_arranged_in(2,apes,long_row_on_his_right_hand).
be_arranged_in(2,apes,long_row_on_his_hand).
be_arranged_in(2,apes,row).
be_arranged_in(2,apes,row_on_his_hand).
be(2,apes,arranged_in_long_row_on_his_hand_on_his_left).
ordered_at(2,he,time).
be_arranged_in(2,apes,long_row).
be(2,apes,arranged_in_long_row_on_his_left).
be_placed_for(2,throne,him).
be_arranged_in(2,apes,row_on_his_right_hand).
be_arranged_on(2,apes,his_left).
be(2,apes,arranged_in_long_row_on_his_right_hand_on_his_left).
root(3,ROOT,signified).
case(3,preparations,after).
det(3,preparations,these).
nmod:after(3,signified,preparations).
nsubj(3,signified,he).
nsubj(3,greeted,he).
mark(3,brought,that).
det(3,men,the).
nummod(3,men,two).
nsubjpass(3,brought,men).
aux(3,brought,should).
auxpass(3,brought,be).
ccomp(3,signified,brought).
advmod(3,him,before).
nmod(3,brought,him).
cc(3,signified,and).
conj:and(3,signified,greeted).
dobj(3,greeted,them).
case(3,salutation,with).
det(3,salutation,this).
nmod:with(3,greeted,salutation).
be(3,men,brought_before_him).
be(3,two_men,brought_before_him).
signified_after(3,he,preparations).
be(3,men,brought_him).
be(3,men,brought).
be(3,two_men,brought).
be(3,two_men,brought_him).
greeted(3,he,them).
root(4,ROOT,seem).
det(4,sort,what).
dep(4,seem,sort).
case(4,king,of).
det(4,king,a).
nmod:of(4,sort,king).
aux(4,seem,do).
nsubj(4,seem,i).
nsubj:xsubj(4,strangers,i).
case(4,you,to).
nmod:to(4,seem,you).
mark(4,strangers,to).
cop(4,strangers,be).
compound(4,strangers,o).
xcomp(4,seem,strangers).
do_seem(4,i,o_strangers).
do_seem_to(4,i,you).
be(4,i,o_strangers).
root(5,ROOT,replied).
punct(5,replied,').
det(5,traveler,the).
amod(5,traveler,lying).
nsubj(5,replied,traveler).
root(6,ROOT,seem).
nsubj(6,seem,you).
case(6,me,to).
nmod:to(6,seem,me).
det(6,king,a).
advmod(6,king,most).
amod(6,king,mighty).
dep(6,me,king).
root(7,ROOT,what).
cc(7,what,and).
cop(7,estimate,is).
nmod:poss(7,estimate,your).
acl:relcl(7,what,estimate).
case(7,those,of).
nmod:of(7,estimate,those).
nsubj(7,see,you).
acl:relcl(7,those,see).
case(7,me,around).
nmod:around(7,see,me).
see_around(7,you,me).
root(8,ROOT,').
root(9,ROOT,these).
root(10,ROOT,made).
nsubj(10,made,he).
dobj(10,made,answer).
made(10,he,answer).
root(11,ROOT,worthy).
cop(11,worthy,are).
nsubj(11,worthy,companions).
mark(11,fit,of).
nsubj(11,fit,yourself).
nsubj:xsubj(11,ambassadors,yourself).
acl:of(11,companions,fit).
advmod(11,fit,at).
mwe(11,at,least).
mark(11,ambassadors,to).
cop(11,ambassadors,be).
xcomp(11,fit,ambassadors).
cc(11,ambassadors,and).
xcomp(11,fit,leaders).
conj:and(11,ambassadors,leaders).
case(11,armies,of).
nmod:of(11,ambassadors,armies).
be(11,yourself,ambassadors).
be_ambassadors_of(11,yourself,armies).
root(12,ROOT,commanded).
det(12,ape,the).
nsubj(12,commanded,ape).
cc(12,ape,and).
det:predet(12,court,all).
nmod:poss(12,court,his).
conj:and(12,ape,court).
nsubj(12,commanded,court).
acl(12,court,gratified).
case(12,lie,with).
det(12,lie,the).
nmod:with(12,gratified,lie).
mark(12,given,that).
det(12,present,a).
amod(12,present,handsome).
nsubjpass(12,given,present).
auxpass(12,given,be).
ccomp(12,commanded,given).
case(12,flatterer,to).
det(12,flatterer,the).
nmod:to(12,given,flatterer).
be(12,present,given).
be_given_to(12,present,flatterer).
be(12,handsome_present,given).
be_given_to(12,handsome_present,flatterer).
root(13,ROOT,thought).
case(13,this,on).
nmod:on(13,thought,this).
det(13,traveler,the).
amod(13,traveler,truthful).
nsubj(13,thought,traveler).
case(13,himself,to).
nmod:to(13,thought,himself).
thought_to(13,traveler,himself).
thought_to(13,truthful_traveler,himself).
thought_on(13,traveler,this).
thought_on(13,truthful_traveler,this).
root(14,ROOT,given).
mark(14,given,if).
advmod(14,great,so).
amod(14,reward,great).
det(14,reward,a).
nsubjpass(14,given,reward).
auxpass(14,given,be).
case(14,lie,for).
det(14,lie,a).
nmod:for(14,given,lie).
mark(14,rewarded,with).
dobj(14,rewarded,what).
nsubjpass(14,rewarded,gift).
aux(14,rewarded,may).
neg(14,i,not).
nmod(14,rewarded,i).
auxpass(14,rewarded,be).
acl:with(14,lie,rewarded).
advmod(14,rewarded,if).
case(14,custom,according).
mwe(14,according,to).
nmod:poss(14,custom,my).
nmod:according_to(14,rewarded,custom).
nsubj(14,tell,i).
acl:relcl(14,custom,tell).
det(14,truth,the).
dobj(14,tell,truth).
be(14,reward,given).
be(14,great_reward,given).
root(15,ROOT,turned).
punct(15,turned,').
det(15,ape,the).
nsubj(15,turned,ape).
advmod(15,turned,quickly).
nmod(15,turned,to).
dep(15,turned,him).
root(16,ROOT,pray).
cc(16,pray,and).
advmod(16,do,how).
ccomp(16,pray,do).
iobj(16,do,i).
cc(16,i,and).
iobj(16,do,these).
conj:and(16,i,these).
nmod:poss(16,friends,my).
dobj(16,do,friends).
mark(16,seem,around).
nsubj(16,seem,me).
advcl:around(16,do,seem).
case(16,you,to).
nmod:to(16,seem,you).
seem_to(16,me,you).
root(17,ROOT,').
root(18,ROOT,thou).
dep(18,thou,art).
root(19,ROOT,said).
nsubj(19,said,he).
root(20,ROOT,apes).
det(20,ape,a).
advmod(20,excellent,most).
amod(20,ape,excellent).
nsubj(20,apes,ape).
cc(20,ape,and).
det:predet(20,companions,all).
det:predet(20,companions,these).
nmod:poss(20,companions,thy).
conj:and(20,ape,companions).
nsubj(20,apes,companions).
case(20,example,after).
nmod:poss(20,example,thy).
nmod:after(20,companions,example).
cop(20,apes,are).
amod(20,apes,excellent).
advmod(20,apes,too).
root(21,ROOT,enraged).
det(21,king,the).
nsubj(21,enraged,king).
case(21,apes,of).
det(21,apes,the).
nmod:of(21,king,apes).
mark(21,hearing,at).
advcl:at(21,enraged,hearing).
det(21,truths,these).
nsubj(21,gave,truths).
ccomp(21,hearing,gave).
dobj(21,gave,him).
case(21,teeth,over).
case(21,teeth,to).
det(21,teeth,the).
nmod:to(21,gave,teeth).
cc(21,teeth,and).
nmod:to(21,gave,claws).
conj:and(21,teeth,claws).
case(21,companions,of).
nmod:poss(21,companions,his).
nmod:of(21,teeth,companions).
enraged(21,king,hearing).
gave(21,truths,him).
