root(0,ROOT,took).
det(0,fisherman,a).
nsubj(0,took,fisherman).
amod(0,fisherman,skilled).
case(0,music,in).
nmod:in(0,skilled,music).
nmod:poss(0,flute,his).
dobj(0,took,flute).
cc(0,flute,and).
nmod:poss(0,nets,his).
dobj(0,took,nets).
conj:and(0,flute,nets).
case(0,seashore,to).
det(0,seashore,the).
nmod:to(0,took,seashore).
skilled_in(0,fisherman,music).
took(0,fisherman_skilled,his_nets).
took(0,fisherman,his_flute).
took(0,fisherman_skilled,his_flute).
took(0,fisherman,his_nets).
root(1,ROOT,standing).
case(1,rock,on).
det(1,rock,a).
amod(1,rock,projecting).
nmod:on(1,standing,rock).
mark(1,dance,rock).
nsubj(1,played,he).
acl:relcl(1,rock,played).
amod(1,tunes,several).
dobj(1,played,tunes).
case(1,hope,in).
det(1,hope,the).
nmod:in(1,played,hope).
ref(1,rock,that).
det(1,fish,the).
nsubj(1,dance,fish).
acl(1,fish,attracted).
case(1,melody,by).
nmod:poss(1,melody,his).
nmod:by(1,attracted,melody).
aux(1,dance,would).
case(1,dance,of).
nmod:poss(1,dance,their).
amod(1,dance,own).
compound(1,dance,accord).
ccomp(1,played,dance).
case(1,net,into).
nmod:poss(1,net,his).
nmod:into(1,dance,net).
nmod:below(1,placed,net).
ref(1,net,which).
nsubj(1,placed,he).
aux(1,placed,had).
acl:relcl(1,net,placed).
case(1,which,below).
attracted_by(1,fish,his_melody).
played_tunes_in(1,he,hope).
played(1,he,several_tunes).
played(1,he,tunes).
root(2,ROOT,waited).
mark(2,waited,at).
nsubj(2,waited,last).
nsubj(2,casting,last).
aux(2,waited,having).
advmod(2,waited,long).
case(2,vain,in).
nmod:in(2,waited,vain).
nsubj(2,laid,he).
acl:relcl(2,vain,laid).
advmod(2,laid,aside).
nmod:poss(2,flute,his).
dobj(2,laid,flute).
cc(2,waited,and).
conj:and(2,waited,casting).
nmod:poss(2,net,his).
dobj(2,casting,net).
case(2,sea,into).
det(2,sea,the).
nmod:into(2,casting,sea).
acl(2,sea,made).
det(2,haul,an).
amod(2,haul,excellent).
dobj(2,made,haul).
case(2,fish,of).
nmod:of(2,haul,fish).
casting(2,last,his_net).
made(2,sea,haul).
made(2,sea,excellent_haul).
made(2,sea,excellent_haul_of_fish).
laid_aside(2,he,his_flute).
made(2,sea,haul_of_fish).
laid(2,he,his_flute).
root(3,ROOT,saw).
advmod(3,saw,when).
nsubj(3,saw,he).
nsubj(3,leaping,them).
dep(3,saw,leaping).
advmod(3,leaping,about).
case(3,net,in).
det(3,net,the).
nmod:in(3,about,net).
case(3,rock,upon).
det(3,rock,the).
nmod:upon(3,leaping,rock).
nsubj(3,said,he).
acl:relcl(3,rock,said).
root(4,ROOT,do).
nsubj(4,do,o).
nmod(4,o,you).
advmod(4,perverse,most).
amod(4,you,perverse).
dep(4,you,creatures).
advmod(4,piped,when).
nsubj(4,piped,i).
dep(4,creatures,piped).
nsubj(4,dance,you).
aux(4,dance,would).
neg(4,dance,not).
ccomp(4,piped,dance).
cc(4,piped,but).
advmod(4,ceased,now).
mark(4,ceased,that).
nsubj(4,ceased,i).
aux(4,ceased,have).
dep(4,creatures,ceased).
conj:but(4,piped,ceased).
dobj(4,ceased,you).
advmod(4,do,so).
advmod(4,do,merrily).
