root(0,ROOT,fell).
case(0,chance,by).
det(0,chance,an).
amod(0,chance,unlucky).
nmod:by(0,fell,chance).
det(0,fox,a).
nsubj(0,fell,fox).
case(0,well,into).
dep(0,well,a).
advmod(0,well,deep).
advcl:into(0,fell,well).
mark(0,get,from).
dobj(0,get,which).
nsubj(0,get,he).
aux(0,get,could).
neg(0,get,not).
advcl:from(0,fell,get).
compound:prt(0,get,out).
root(1,ROOT,passed).
det(1,goat,a).
nsubj(1,passed,goat).
nsubj(1,asked,goat).
case(1,shortly,by).
advcl:by(1,passed,shortly).
advmod(1,passed,afterwards).
cc(1,passed,and).
conj:and(1,passed,asked).
det(1,fox,the).
dobj(1,asked,fox).
dobj(1,doing,fox).
ref(1,fox,what).
nsubj(1,doing,he).
aux(1,doing,was).
acl:relcl(1,fox,doing).
advmod(1,there,down).
advmod(1,doing,there).
passed_afterwards_by(1,goat,shortly).
passed_by(1,goat,shortly).
root(2,ROOT,have).
nsubj(2,have,oh).
dobj(2,have,you).
neg(2,have,not).
dep(2,have,heard).
root(3,ROOT,said).
det(3,fox,the).
nsubj(3,said,fox).
root(4,ROOT,going).
expl(4,going,there).
aux(4,going,is).
mark(4,drought,to).
cop(4,drought,be).
det(4,drought,a).
amod(4,drought,great).
xcomp(4,going,drought).
mark(4,jumped,so).
nsubj(4,jumped,i).
advcl:so(4,drought,jumped).
advmod(4,here,down).
advmod(4,jumped,here).
mark(4,sure,in).
mwe(4,in,order).
mark(4,sure,to).
cop(4,sure,be).
advcl:in_order(4,jumped,sure).
mark(4,have,to).
xcomp(4,sure,have).
dobj(4,have,water).
case(4,me,by).
nmod:by(4,have,me).
jumped(4,i,sure).
jumped_here(4,i,sure).
jumped_down_here(4,i,sure).
root(5,ROOT,do).
advmod(5,do,why).
neg(5,do,n't).
nsubj(5,come,you).
ccomp(5,do,come).
advmod(5,too,down).
advmod(5,come,too).
root(6,ROOT,thought).
det(6,goat,the).
nsubj(6,thought,goat).
nsubj(6,jumped,goat).
advmod(6,thought,well).
case(6,advice,of).
det(6,advice,this).
nmod:of(6,thought,advice).
cc(6,thought,and).
conj:and(6,thought,jumped).
compound:prt(6,jumped,down).
case(6,well,into).
det(6,well,the).
nmod:into(6,jumped,well).
thought_of(6,goat,advice).
thought_well_of(6,goat,advice).
jumped_down_into(6,goat,well).
root(7,ROOT,jumped).
cc(7,jumped,but).
det(7,fox,the).
nsubj(7,jumped,fox).
advmod(7,jumped,immediately).
case(7,back,on).
nmod:poss(7,back,her).
nmod:on(7,jumped,back).
cc(7,back,and).
mark(7,putting,by).
nmod:on(7,jumped,putting).
conj:and(7,back,putting).
nmod:poss(7,foot,his).
nsubj(7,managed,foot).
nsubj:xsubj(7,jump,foot).
case(7,horns,on).
nmod:poss(7,horns,her).
amod(7,horns,long).
nmod:on(7,foot,horns).
ccomp(7,putting,managed).
mark(7,jump,to).
xcomp(7,managed,jump).
compound:prt(7,jump,up).
case(7,edge,to).
det(7,edge,the).
nmod:to(7,jump,edge).
case(7,well,of).
det(7,well,the).
nmod:of(7,edge,well).
jump_up_to(7,his_foot,edge_of_well).
immediately_jumped_on(7,fox,her_back).
jump_up_to(7,his_foot,edge).
jumped_on(7,fox,her_back).
root(8,ROOT,friend).
compound(8,friend,good-bye).
root(9,ROOT,said).
det(9,fox,the).
nsubj(9,said,fox).
