root(0,ROOT,fishermen).
det(0,fishermen,the).
det(0,fishermen,some).
nsubj(0,trawling,fishermen).
cop(0,trawling,were).
mark(0,trawling,out).
acl:relcl(0,fishermen,trawling).
nmod:poss(0,nets,their).
dobj(0,trawling,nets).
root(1,ROOT,perceiving).
dobj(1,perceiving,them).
nsubj:xsubj(1,heavy,them).
mark(1,heavy,to).
cop(1,heavy,be).
advmod(1,heavy,very).
xcomp(1,perceiving,heavy).
nsubj(1,danced,they).
nsubj(1,supposed,they).
ccomp(1,heavy,danced).
case(1,joy,about).
case(1,joy,for).
nmod:for(1,danced,joy).
cc(1,danced,and).
ccomp(1,heavy,supposed).
conj:and(1,danced,supposed).
mark(1,taken,that).
nsubj(1,taken,they).
aux(1,taken,had).
ccomp(1,supposed,taken).
det(1,catch,a).
amod(1,catch,large).
dobj(1,taken,catch).
danced_about(1,they,about_joy).
root(2,ROOT,found).
advmod(2,dragged,when).
nsubj(2,dragged,they).
aux(2,dragged,had).
advcl(2,found,dragged).
det(2,nets,the).
dobj(2,dragged,nets).
case(2,shore,to).
det(2,shore,the).
nmod:to(2,dragged,shore).
nsubj(2,found,they).
cc(2,found,but).
amod(2,fish,few).
nsubj(2,full,fish).
det(2,nets,the).
dep(2,fish,nets).
cop(2,full,were).
conj:but(2,found,full).
case(2,sand,of).
nmod:of(2,full,sand).
cc(2,sand,and).
nmod:of(2,full,stones).
conj:and(2,sand,stones).
cc(2,found,and).
det(2,men,the).
nsubj(2,measure,men).
cop(2,measure,were).
case(2,measure,beyond).
conj:but(2,found,measure).
advcl(2,measure,cast).
advmod(2,much,downso).
xcomp(2,cast,much).
case(2,disappointment,at).
det(2,disappointment,the).
nmod:at(2,cast,disappointment).
nsubj(2,befallen,disappointment).
ref(2,disappointment,which).
aux(2,befallen,had).
acl:relcl(2,disappointment,befallen).
dobj(2,befallen,them).
cc(2,cast,but).
mark(2,formed,because).
nsubj(2,formed,they).
aux(2,formed,had).
advcl(2,measure,formed).
conj:but(2,cast,formed).
amod(2,expectations,such).
advmod(2,different,very).
amod(2,expectations,different).
dobj(2,formed,expectations).
cast(2,men,much).
cast(2,men,downso_much).
had_formed(2,they,such_expectations).
had_formed(2,they,such_very_different_expectations).
had_dragged_nets_to(2,they,shore).
had_formed(2,they,very_different_expectations).
had_dragged(2,they,nets).
had_formed(2,they,such_different_expectations).
had_formed(2,they,different_expectations).
were_beyond(2,men,measure).
had_formed(2,they,expectations).
root(3,ROOT,said).
nsubj(3,said,one).
case(3,company,of).
nmod:poss(3,company,their).
nmod:of(3,one,company).
det(3,man,an).
amod(3,man,old).
dep(3,company,man).
root(4,ROOT,let).
nsubj(4,cease,us).
ccomp(4,let,cease).
xcomp(4,cease,lamenting).
nmod:poss(4,mates,my).
dobj(4,lamenting,mates).
mark(4,sister,for).
mark(4,seems,as).
nsubj(4,seems,it).
advcl:as(4,sister,seems).
case(4,me,to).
nmod:to(4,seems,me).
nsubj(4,sister,sorrow).
cop(4,sister,is).
advmod(4,sister,always).
det(4,sister,the).
amod(4,sister,twin).
advcl:for(4,cease,sister).
case(4,joy,of).
nmod:of(4,sister,joy).
is_always_sister_of(4,sorrow,joy).
is_always_sister(4,sorrow,it_seems).
cease(4,us,always_sister_of_joy).
cease(4,us,sister).
cease(4,us,always_twin_sister_of_joy).
is(4,sorrow,always_sister).
is_twin_sister(4,sorrow,it_seems_to_me).
cease(4,us,always_twin_sister).
seems_to(4,it,me).
is_always_sister(4,sorrow,it_seems_to_me).
is_sister(4,sorrow,it_seems_to_me).
is_always_twin_sister_of(4,sorrow,joy).
is_sister(4,sorrow,it_seems).
is_twin_sister(4,sorrow,it_seems).
cease(4,us,twin_sister_of_joy).
is(4,sorrow,always_twin_sister).
is_sister_of(4,sorrow,joy).
cease(4,us,always_sister).
is_twin_sister_of(4,sorrow,joy).
cease(4,us,sister_of_joy).
is(4,sorrow,sister).
is_always_twin_sister(4,sorrow,it_seems).
lamenting(4,us,my_mates).
cease(4,us,twin_sister).
is(4,sorrow,twin_sister).
is_always_twin_sister(4,sorrow,it_seems_to_me).
root(5,ROOT,was).
cc(5,was,and).
nsubj(5,was,it).
nsubjpass:xsubj(5,looked,it).
advmod(5,was,only).
mark(5,looked,to).
auxpass(5,looked,be).
xcomp(5,was,looked).
mark(5,have,for).
mark(5,have,that).
nsubj(5,over-rejoiced,we).
nsubj(5,have,we).
ref(5,we,who).
advmod(5,now,just).
advmod(5,over-rejoiced,now).
cop(5,over-rejoiced,were).
acl:relcl(5,we,over-rejoiced).
aux(5,have,should).
advmod(5,have,next).
advcl:that(5,looked,have).
dobj(5,have,something).
mark(5,make,to).
advcl:to(5,have,make).
nsubj(5,sad,us).
xcomp(5,make,sad).
be(5,it,looked).
was_only(5,it,looked).
was(5,it,looked).
