root(0,ROOT,engaged).
det(0,fisherman,a).
nsubj(0,engaged,fisherman).
mark(0,calling,in).
nsubj(0,calling,his).
advcl:in(0,engaged,calling).
dep(0,calling,made).
det(0,cast,a).
advmod(0,successful,very).
amod(0,cast,successful).
dobj(0,made,cast).
cc(0,made,and).
dep(0,calling,captured).
conj:and(0,made,captured).
det(0,haul,a).
amod(0,haul,great).
dobj(0,captured,haul).
case(0,fish,of).
nmod:of(0,haul,fish).
captured(0,cast,haul).
captured(0,cast,haul_of_fish).
captured(0,cast,great_haul).
captured(0,successful_cast,great_haul).
engaged(0,fisherman,his_calling).
captured(0,successful_cast,haul_of_fish).
captured(0,cast,great_haul_of_fish).
captured(0,successful_cast,haul).
haul_of(0,captured,fish).
great_haul_of(0,captured,fish).
captured(0,successful_cast,great_haul_of_fish).
root(1,ROOT,managed).
nsubj(1,managed,he).
case(1,handling,by).
det(1,handling,a).
amod(1,handling,skillful).
nmod:by(1,managed,handling).
case(1,net,of).
nmod:poss(1,net,his).
nmod:of(1,handling,net).
mark(1,retain,to).
ccomp(1,managed,retain).
det:predet(1,fish,all).
det(1,fish,the).
amod(1,fish,large).
dobj(1,retain,fish).
cc(1,retain,and).
mark(1,draw,to).
ccomp(1,managed,draw).
conj:and(1,retain,draw).
dobj(1,draw,them).
case(1,shore,to).
det(1,shore,the).
nmod:to(1,draw,shore).
managed_by(1,he,skillful_handling).
managed_by(1,he,skillful_handling_of_his_net).
managed_by(1,he,handling_of_his_net).
managed_by(1,he,handling).
draw(1,large_fish,them).
root(2,ROOT,prevent).
cc(2,prevent,but).
nsubj(2,prevent,he).
aux(2,prevent,could).
neg(2,prevent,not).
det(2,fish,the).
amod(2,fish,smaller).
dobj(2,prevent,fish).
mark(2,falling,from).
advcl:from(2,prevent,falling).
advmod(2,falling,back).
case(2,meshes,through).
det(2,meshes,the).
nmod:through(2,falling,meshes).
case(2,net,of).
det(2,net,the).
nmod:of(2,meshes,net).
case(2,sea,into).
det(2,sea,the).
nmod:into(2,falling,sea).
