root(0,ROOT,escaped).
det(0,fox,a).
nsubj(0,escaped,fox).
acl(0,fox,caught).
case(0,trap,in).
det(0,trap,a).
nmod:in(0,caught,trap).
cc(0,doing,but).
mark(0,doing,in).
advmod(0,doing,so).
dep(0,escaped,doing).
dep(0,doing,lost).
nmod:poss(0,tail,his).
dobj(0,lost,tail).
root(1,ROOT,feeling).
advmod(1,feeling,thereafter).
nmod:poss(1,life,his).
dobj(1,feeling,life).
det(1,burden,a).
nsubj(1,making,burden).
case(1,shame,from).
det(1,shame,the).
nmod:from(1,burden,shame).
nmod:to(1,exposed,shame).
cc(1,shame,and).
nmod:from(1,burden,ridicule).
conj:and(1,shame,ridicule).
nmod:to(1,exposed,ridicule).
case(1,which,to).
ref(1,shame,which).
nsubjpass(1,exposed,he).
auxpass(1,exposed,was).
acl:relcl(1,shame,exposed).
nsubj(1,schemed,he).
nsubj:xsubj(1,convince,he).
ccomp(1,exposed,schemed).
mark(1,convince,to).
xcomp(1,schemed,convince).
det:predet(1,foxes,all).
det(1,foxes,the).
amod(1,foxes,other).
dobj(1,convince,foxes).
nsubj(1,tailless,foxes).
ref(1,foxes,that).
cop(1,tailless,being).
acl:relcl(1,foxes,tailless).
cop(1,making,was).
advmod(1,attractive,much).
advmod(1,attractive,more).
xcomp(1,making,attractive).
advmod(1,making,thus).
acl:relcl(1,life,making).
compound:prt(1,making,up).
case(1,deprivation,for).
nmod:poss(1,deprivation,his).
amod(1,deprivation,own).
nmod:for(1,making,deprivation).
was_thus_making_up_for(1,burden,his_deprivation).
was_making_up_for(1,burden,his_deprivation).
was_thus_making_up_for(1,burden,his_own_deprivation).
was(1,he,exposed).
was_making_up_for(1,burden,his_own_deprivation).
root(2,ROOT,assembled).
nsubj(2,assembled,he).
nsubj(2,advised,he).
det(2,foxes,a).
amod(2,foxes,good).
amod(2,foxes,many).
dobj(2,assembled,foxes).
cc(2,assembled,and).
advmod(2,advised,publicly).
conj:and(2,assembled,advised).
dobj(2,advised,them).
nsubj:xsubj(2,cut,them).
mark(2,cut,to).
xcomp(2,advised,cut).
compound:prt(2,cut,off).
nmod:poss(2,tails,their).
dobj(2,cut,tails).
xcomp(2,cut,saying).
mark(2,look,that).
nsubj(2,look,they).
aux(2,look,would).
neg(2,look,not).
advmod(2,look,only).
ccomp(2,saying,look).
advmod(2,better,much).
xcomp(2,look,better).
case(2,them,without).
nmod:without(2,look,them).
cc(2,look,but).
mark(2,get,that).
nsubj(2,get,they).
aux(2,get,would).
ccomp(2,saying,get).
conj:but(2,look,get).
xcomp(2,get,rid).
case(2,weight,of).
det(2,weight,the).
nmod:of(2,get,weight).
case(2,brush,of).
det(2,brush,the).
nmod:of(2,weight,brush).
nsubj(2,inconvenience,brush).
ref(2,brush,which).
cop(2,inconvenience,was).
det(2,inconvenience,a).
advmod(2,great,very).
amod(2,inconvenience,great).
acl:relcl(2,brush,inconvenience).
assembled(2,he,good_foxes).
assembled(2,he,many_foxes).
assembled(2,he,good_many_foxes).
assembled(2,he,foxes).
advised(2,he,them).
publicly_advised(2,he,them).
cut_off(2,them,their_tails).
root(3,ROOT,said).
nsubj(3,said,one).
mark(3,interrupting,of).
nsubj(3,interrupting,them).
acl:of(3,one,interrupting).
dobj(3,interrupting,him).
interrupting(3,them,him).
root(4,ROOT,had).
mark(4,had,if).
nsubj(4,had,you).
dep(4,lost,not).
nsubj(4,lost,yourself).
advcl(4,would,lost).
nmod:poss(4,tail,your).
nsubj(4,friend,tail).
nmod:poss(4,friend,my).
xcomp(4,lost,friend).
nsubj(4,would,you).
ccomp(4,had,would).
neg(4,would,not).
advmod(4,counsel,thus).
nmod:tmod(4,had,counsel).
dep(4,counsel,us).
