root(0,ROOT,went).
det(0,fowler,a).
nsubj(0,went,fowler).
nsubj:xsubj(0,catch,fowler).
acl(0,fowler,taking).
nmod:poss(0,bird-lime,his).
dobj(0,taking,bird-lime).
cc(0,bird-lime,and).
nmod:poss(0,twigs,his).
dobj(0,taking,twigs).
conj:and(0,bird-lime,twigs).
compound:prt(0,went,out).
mark(0,catch,to).
xcomp(0,went,catch).
dobj(0,catch,birds).
catch(0,fowler,birds).
root(1,ROOT,seeing).
det(1,thrush,a).
dobj(1,seeing,thrush).
amod(1,thrush,sitting).
case(1,tree,upon).
det(1,tree,a).
nmod:upon(1,thrush,tree).
nsubj(1,wished,he).
nsubj:xsubj(1,take,he).
acl:relcl(1,tree,wished).
mark(1,take,to).
xcomp(1,wished,take).
dobj(1,take,it).
cc(1,wished,and).
amod(1,twigs,fitting).
nmod:poss(1,twigs,his).
nsubj(1,watched,twigs).
case(1,length,to).
det(1,length,a).
amod(1,length,proper).
nmod:to(1,twigs,length).
acl:relcl(1,tree,watched).
conj:and(1,wished,watched).
advmod(1,having,intently).
xcomp(1,watched,having).
nmod:poss(1,thoughts,his).
amod(1,thoughts,whole).
nsubj(1,directed,thoughts).
ccomp(1,having,directed).
case(1,sky,towards).
det(1,sky,the).
nmod:towards(1,directed,sky).
watched(1,fitting_his_twigs,intently_having).
directed_towards(1,his_thoughts,sky).
watched(1,fitting_his_twigs,having).
take(1,he,it).
directed_towards(1,his_whole_thoughts,sky).
watched(1,his_twigs,having).
watched(1,his_twigs,intently_having).
root(2,ROOT,looking).
mark(2,looking,while).
advmod(2,looking,thus).
dobj(2,looking,upwards).
nsubj(2,trod,he).
advmod(2,trod,unknowingly).
acl:relcl(2,upwards,trod).
case(2,viper,upon).
det(2,viper,a).
nmod:upon(2,trod,viper).
amod(2,viper,asleep).
advmod(2,feet,just).
case(2,feet,before).
nmod:poss(2,feet,his).
nmod:before(2,trod,feet).
trod_before(2,he,his_feet).
unknowingly_trod_before(2,he,his_feet).
trod_before(2,he,just_his_feet).
unknowingly_trod_upon(2,he,viper).
trod_upon(2,he,viper_asleep).
unknowingly_trod_upon(2,he,viper_asleep).
trod_upon(2,he,viper).
unknowingly_trod_before(2,he,just_his_feet).
root(3,ROOT,viper).
det(3,viper,the).
dep(3,viper,turning).
mark(3,stung,about).
advcl:about(3,turning,stung).
dobj(3,stung,him).
cc(3,turning,and).
dep(3,viper,falling).
conj:and(3,turning,falling).
case(3,swoon,into).
det(3,swoon,a).
nmod:into(3,falling,swoon).
det(3,man,the).
nsubj(3,said,man).
acl:relcl(3,swoon,said).
case(3,himself,to).
nmod:to(3,said,himself).
said_to(3,man,himself).
root(4,ROOT,me).
nsubj(4,me,woe).
cop(4,me,is).
is(4,woe,me).
root(5,ROOT,fallen).
mark(5,fallen,that).
case(5,purposed,while).
compound(5,purposed,i).
nmod:while(5,fallen,purposed).
case(5,hunt,to).
nmod:to(5,purposed,hunt).
det(5,i,another).
nsubjpass(5,fallen,i).
auxpass(5,fallen,am).
dobj(5,fallen,myself).
advmod(5,snares,unawares).
case(5,snares,into).
det(5,snares,the).
nmod:into(5,fallen,snares).
case(5,death,of).
nmod:of(5,snares,death).
