root(0,ROOT,settled).
det(0,flea,a).
nsubj(0,settled,flea).
case(0,foot,upon).
det(0,foot,the).
amod(0,foot,bare).
nmod:upon(0,settled,foot).
case(0,wrestler,of).
det(0,wrestler,a).
nmod:of(0,foot,wrestler).
cc(0,wrestler,and).
nmod:of(0,foot,bit).
conj:and(0,wrestler,bit).
dobj(0,settled,him).
acl(0,him,causing).
det(0,man,the).
dobj(0,causing,man).
mark(0,call,to).
acl:to(0,man,call).
advmod(0,call,loudly).
case(0,hercules,upon).
nmod:upon(0,loudly,hercules).
case(0,help,for).
nmod:for(0,call,help).
settled_upon(0,flea,bare_foot_of_wrestler).
man(0,causing,call_loudly).
man(0,causing,call).
man(0,causing,call_loudly_upon_hercules_for_help).
man(0,causing,call_loudly_for_help).
man(0,causing,call_for_help).
settled_upon(0,flea,bare_foot).
settled_upon(0,flea,foot_of_wrestler).
settled(0,flea,him).
man(0,causing,call_loudly_upon_hercules).
settled_upon(0,flea,foot).
root(1,ROOT,hopped).
advmod(1,hopped,when).
det(1,flea,the).
nsubj(1,hopped,flea).
det(1,time,a).
amod(1,time,second).
dep(1,flea,time).
case(1,foot,upon).
nmod:poss(1,foot,his).
nmod:upon(1,hopped,foot).
nsubj(1,groaned,he).
nsubj(1,said,he).
acl:relcl(1,foot,groaned).
cc(1,groaned,and).
acl:relcl(1,foot,said).
conj:and(1,groaned,said).
root(2,ROOT,hercules).
compound(2,hercules,o).
root(3,ROOT,help).
mark(3,help,if).
nsubj(3,help,you).
aux(3,help,will).
neg(3,help,not).
dobj(3,help,me).
case(3,flea,against).
det(3,flea,a).
nmod:against(3,help,flea).
advmod(3,hope,how).
aux(3,hope,can).
compound(3,hope,i).
dep(3,help,hope).
case(3,assistance,for).
nmod:poss(3,assistance,your).
nmod:for(3,hope,assistance).
case(3,antagonists,against).
amod(3,antagonists,greater).
nmod:against(3,hope,antagonists).
