%% when first the fox saw the lion he was terribly frightened and ran away and hid himself in the wood.
% dependencies.
root(0,root,see).
advmod(0,see,when).
advmod(0,fox,first).
det(0,fox,the).
nsubj(0,see,fox).
nsubj(0,hide,fox).
det(0,lion,the).
dobj(0,see,lion).
nsubj(0,frightened,he).
nsubj(0,run,he).
cop(0,frightened,be).
advmod(0,frightened,terribly).
dep(0,see,frightened).
cc(0,frightened,and).
dep(0,see,run).
conj:and(0,frightened,run).
advmod(0,run,away).
cc(0,see,and).
conj:and(0,see,hide).
dobj(0,hide,himself).
case(0,wood,in).
det(0,wood,the).
nmod:in(0,hide,wood).
% relations.
hide(0,fox,himself).
see(0,fox,lion).
be(0,he,terribly_frightened).
be(0,he,frightened).
%% next time however he came near the king of beasts he stopped at a safe distance and watched him pass by.
% dependencies.
root(1,root,next).
dep(1,next,time).
advmod(1,come,however).
nsubj(1,come,he).
dep(1,next,come).
case(1,king,near).
det(1,king,the).
nmod:near(1,come,king).
case(1,beast,of).
nmod:of(1,king,beast).
nsubj(1,stop,he).
nsubj(1,watch,he).
ccomp(1,come,stop).
case(1,distance,at).
det(1,distance,a).
amod(1,distance,safe).
nmod:at(1,stop,distance).
cc(1,stop,and).
ccomp(1,come,watch).
conj:and(1,stop,watch).
nsubj(1,pass,he).
ccomp(1,watch,pass).
nmod(1,pass,by).
% relations.
stop_at(1,he,distance).
stop_at(1,he,safe_distance).
%% the third time they came near one another the fox went straight up to the lion and passed the time of day with him asking him how his family were and when he should have the pleasure of seeing him again.
% dependencies.
root(2,root,time).
det(2,time,the).
amod(2,time,third).
nsubj(2,come,they).
acl:relcl(2,time,come).
case(2,one,near).
nmod:near(2,come,one).
dobj(2,come,another).
det(2,fox,the).
nsubj(2,go,fox).
nsubj(2,pass,fox).
acl:relcl(2,another,go).
xcomp(2,go,straight).
advmod(2,go,up).
case(2,lion,to).
det(2,lion,the).
nmod:to(2,up,lion).
cc(2,go,and).
acl:relcl(2,another,pass).
conj:and(2,go,pass).
det(2,time,the).
dobj(2,pass,time).
case(2,day,of).
nmod:of(2,time,day).
mark(2,ask,with).
nsubj(2,ask,he).
advcl:with(2,come,ask).
dobj(2,ask,he).
advmod(2,be,how).
nmod:poss(2,family,he).
nsubj(2,be,family).
dep(2,ask,be).
cc(2,be,and).
advmod(2,have,when).
nsubj(2,have,he).
aux(2,have,should).
dep(2,ask,have).
conj:and(2,be,have).
det(2,pleasure,the).
dobj(2,have,pleasure).
mark(2,see,of).
acl:of(2,pleasure,see).
dobj(2,see,he).
advmod(2,see,again).
% relations.
go(2,fox,straight).
pass(2,fox,time).
time_of(2,pass,day).
ask(2,he,he).
go_up(2,fox,straight).
come_near(2,they,one).
pass(2,fox,time_of_day).
%% then turning his tail he parted from the lion without much ceremony.
% dependencies.
root(3,root,turn).
advmod(3,turn,then).
nmod:poss(3,tail,he).
dobj(3,turn,tail).
nsubj(3,part,he).
acl:relcl(3,tail,part).
case(3,lion,from).
det(3,lion,the).
nmod:from(3,part,lion).
case(3,ceremony,without).
amod(3,ceremony,much).
nmod:without(3,part,ceremony).
% relations.
part_from(3,he,lion).
part_without(3,he,ceremony).
part_without(3,he,much_ceremony).
