root(0,ROOT,saw).
advmod(0,saw,when).
advmod(0,fox,first).
det(0,fox,the).
nsubj(0,saw,fox).
nsubj(0,hid,fox).
det(0,lion,the).
dobj(0,saw,lion).
nsubj(0,frightened,he).
nsubj(0,ran,he).
cop(0,frightened,was).
advmod(0,frightened,terribly).
dep(0,saw,frightened).
cc(0,frightened,and).
dep(0,saw,ran).
conj:and(0,frightened,ran).
advmod(0,ran,away).
cc(0,saw,and).
conj:and(0,saw,hid).
dobj(0,hid,himself).
case(0,wood,in).
det(0,wood,the).
nmod:in(0,hid,wood).
hid(0,fox,himself).
saw(0,fox,lion).
was(0,he,terribly_frightened).
was(0,he,frightened).
root(1,ROOT,next).
dep(1,next,time).
advmod(1,came,however).
nsubj(1,came,he).
dep(1,next,came).
case(1,king,near).
det(1,king,the).
nmod:near(1,came,king).
case(1,beasts,of).
nmod:of(1,king,beasts).
nsubj(1,stopped,he).
nsubj(1,watched,he).
ccomp(1,came,stopped).
case(1,distance,at).
det(1,distance,a).
amod(1,distance,safe).
nmod:at(1,stopped,distance).
cc(1,stopped,and).
ccomp(1,came,watched).
conj:and(1,stopped,watched).
nsubj(1,pass,him).
ccomp(1,watched,pass).
nmod(1,pass,by).
stopped_at(1,he,distance).
stopped_at(1,he,safe_distance).
root(2,ROOT,time).
det(2,time,the).
amod(2,time,third).
nsubj(2,came,they).
acl:relcl(2,time,came).
case(2,one,near).
nmod:near(2,came,one).
dobj(2,came,another).
det(2,fox,the).
nsubj(2,went,fox).
nsubj(2,passed,fox).
acl:relcl(2,another,went).
xcomp(2,went,straight).
advmod(2,went,up).
case(2,lion,to).
det(2,lion,the).
nmod:to(2,up,lion).
cc(2,went,and).
acl:relcl(2,another,passed).
conj:and(2,went,passed).
det(2,time,the).
dobj(2,passed,time).
case(2,day,of).
nmod:of(2,time,day).
mark(2,asking,with).
nsubj(2,asking,him).
advcl:with(2,came,asking).
dobj(2,asking,him).
advmod(2,were,how).
nmod:poss(2,family,his).
nsubj(2,were,family).
dep(2,asking,were).
cc(2,were,and).
advmod(2,have,when).
nsubj(2,have,he).
aux(2,have,should).
dep(2,asking,have).
conj:and(2,were,have).
det(2,pleasure,the).
dobj(2,have,pleasure).
mark(2,seeing,of).
acl:of(2,pleasure,seeing).
dobj(2,seeing,him).
advmod(2,seeing,again).
went(2,fox,straight).
passed(2,fox,time).
time_of(2,passed,day).
asking(2,him,him).
went_up(2,fox,straight).
came_near(2,they,one).
passed(2,fox,time_of_day).
root(3,ROOT,turning).
advmod(3,turning,then).
nmod:poss(3,tail,his).
dobj(3,turning,tail).
nsubj(3,parted,he).
acl:relcl(3,tail,parted).
case(3,lion,from).
det(3,lion,the).
nmod:from(3,parted,lion).
case(3,ceremony,without).
amod(3,ceremony,much).
nmod:without(3,parted,ceremony).
parted_from(3,he,lion).
parted_without(3,he,ceremony).
parted_without(3,he,much_ceremony).
