root(0,ROOT,prowling).
nummod(0,night,one).
compound(0,night,moonlight).
nsubj(0,prowling,night).
nsubj(0,saw,night).
det(0,fox,a).
dep(0,night,fox).
aux(0,prowling,was).
case(0,hen-coop,about).
det(0,farmer,a).
nmod:poss(0,hen-coop,farmer).
case(0,farmer,'s).
nmod:about(0,prowling,hen-coop).
cc(0,prowling,and).
conj:and(0,prowling,saw).
det(0,cock,a).
dobj(0,saw,cock).
acl(0,cock,roosting).
advmod(0,roosting,high).
case(0,high,up).
case(0,reach,beyond).
nmod:poss(0,reach,his).
nmod:beyond(0,roosting,reach).
about(0,farmer,hen-coop).
root(1,ROOT,news).
amod(1,news,good).
amod(1,news,good).
dep(1,news,news).
root(2,ROOT,cried).
nsubj(2,cried,he).
root(3,ROOT,that).
advmod(3,that,why).
nsubj(3,that,what).
cop(3,that,is).
root(4,ROOT,said).
det(4,cock,the).
nsubj(4,said,cock).
root(5,ROOT,declared).
compound(5,lion,king).
nsubj(5,declared,lion).
aux(5,declared,has).
det(5,truce,a).
amod(5,truce,universal).
dobj(5,declared,truce).
has_declared(5,king_lion,truce).
has_declared(5,king_lion,universal_truce).
root(6,ROOT,hurt).
neg(6,beast,no).
nsubj(6,hurt,beast).
aux(6,hurt,may).
det(6,henceforth,a).
compound(6,henceforth,bird).
dobj(6,hurt,henceforth).
cc(6,dwell,but).
nsubj(6,dwell,all).
aux(6,dwell,shall).
dep(6,hurt,dwell).
advmod(6,dwell,together).
case(6,friendship,in).
amod(6,friendship,brotherly).
nmod:in(6,dwell,friendship).
root(7,ROOT,news).
advmod(7,news,why).
nsubj(7,news,that).
cop(7,news,is).
amod(7,news,good).
is(7,that,why_good_news).
root(8,ROOT,said).
det(8,cock,the).
nsubj(8,said,cock).
root(9,ROOT,there).
cc(9,there,and).
nsubj(9,see,i).
acl:relcl(9,there,see).
det(9,one,some).
dobj(9,see,one).
acl(9,one,coming).
mark(9,share,with).
dobj(9,share,whom).
nsubj(9,share,we).
aux(9,share,can).
advcl:with(9,coming,share).
det(9,tidings,the).
amod(9,tidings,good).
dobj(9,share,tidings).
root(10,ROOT,so).
cc(10,so,and).
dep(10,so,saying).
nsubj(10,craned,he).
nsubj(10,looked,he).
ccomp(10,saying,craned).
nmod:poss(10,neck,his).
dobj(10,craned,neck).
advmod(10,craned,forward).
cc(10,craned,and).
ccomp(10,saying,looked).
conj:and(10,craned,looked).
dobj(10,looked,afar).
compound:prt(10,looked,off).
root(11,ROOT,what).
cop(11,what,is).
nsubj(11,what,it).
nsubj(11,see,you).
acl:relcl(11,it,see).
root(12,ROOT,said).
det(12,fox,the).
nsubj(12,said,fox).
root(13,ROOT,dog).
nsubj(13,dog,it).
cop(13,dog,is).
advmod(13,dog,only).
nmod:poss(13,master,my).
nmod:poss(13,dog,master).
case(13,master,'s).
nsubj(13,coming,that).
aux(13,coming,is).
ccomp(13,dog,coming).
case(13,us,towards).
nmod:towards(13,coming,us).
is(13,it,only_my_master_s_dog).
is(13,it,my_master_s_dog).
root(14,ROOT,going).
dep(14,going,what).
advmod(14,soon,so).
advmod(14,going,soon).
root(15,ROOT,continued).
nsubj(15,continued,he).
mark(15,began,as).
det(15,fox,the).
nsubj(15,began,fox).
nsubj:xsubj(15,turn,fox).
advcl:as(15,continued,began).
mark(15,turn,to).
xcomp(15,began,turn).
compound:prt(15,turn,away).
advmod(15,soon,as).
advmod(15,turn,soon).
mark(15,heard,as).
nsubj(15,heard,he).
aux(15,heard,had).
advcl:as(15,soon,heard).
det(15,news,the).
dobj(15,heard,news).
continued(15,he,fox_began).
root(16,ROOT,stop).
aux(16,stop,will).
nsubj(16,stop,you).
nsubj(16,congratulate,you).
neg(16,stop,not).
cc(16,stop,and).
conj:and(16,stop,congratulate).
det(16,dog,the).
dobj(16,congratulate,dog).
case(16,reign,on).
det(16,reign,the).
nmod:on(16,congratulate,reign).
case(16,peace,of).
amod(16,peace,universal).
nmod:of(16,reign,peace).
congratulate_dog_on(16,you,reign_of_universal_peace).
congratulate_dog_on(16,you,reign).
congratulate(16,you,dog).
congratulate_dog_on(16,you,reign_of_peace).
root(17,ROOT,do).
nsubj(17,do,i).
aux(17,do,would).
advmod(17,do,gladly).
advmod(17,do,so).
root(18,ROOT,said).
det(18,fox,the).
nsubj(18,said,fox).
root(19,ROOT,fear).
cc(19,fear,but).
nsubj(19,fear,i).
nsubj(19,heard,he).
aux(19,heard,may).
neg(19,heard,not).
aux(19,heard,have).
ccomp(19,fear,heard).
case(19,decree,of).
compound(19,lion,king).
nmod:poss(19,decree,lion).
case(19,lion,'s).
nmod:of(19,heard,decree).
