%% a fox invited a crane to supper and provided nothing for his entertainment but some soup made of pulse which was poured out into a broad flat stone dish.
% dependencies.
root(0,root,invite).
det(0,fox,a).
nsubj(0,invite,fox).
nsubj(0,provide,fox).
det(0,crane,a).
dobj(0,invite,crane).
case(0,supper,to).
nmod:to(0,invite,supper).
cc(0,invite,and).
conj:and(0,invite,provide).
dobj(0,provide,nothing).
case(0,entertainment,for).
nmod:poss(0,entertainment,he).
nmod:for(0,provide,entertainment).
cc(0,soup,but).
det(0,soup,some).
dep(0,provide,soup).
acl(0,soup,make).
case(0,pulse,of).
nmod:of(0,make,pulse).
nsubjpass(0,pour,which).
auxpass(0,pour,be).
dep(0,provide,pour).
compound:prt(0,pour,out).
case(0,dish,into).
det(0,dish,a).
amod(0,dish,broad).
amod(0,dish,flat).
compound(0,dish,stone).
nmod:into(0,pour,dish).
% relations.
aos(0,invite,fox,crane).
aos(0,provide,fox,nothing).
aos(0,invite_crane_to,fox,supper).
aos(0,provide_nothing_for,fox,he_entertainment).
%% the soup fell out of the long bill of the crane at every mouthful and his vexation at not being able to eat afforded the fox much amusement.
% dependencies.
root(1,root,fall).
det(1,soup,the).
nsubj(1,fall,soup).
case(1,bill,out).
mwe(1,out,of).
det(1,bill,the).
amod(1,bill,long).
nmod:out_of(1,fall,bill).
case(1,crane,of).
det(1,crane,the).
nmod:of(1,bill,crane).
case(1,mouthful,at).
det(1,mouthful,every).
nmod:at(1,fall,mouthful).
cc(1,mouthful,and).
nmod:poss(1,vexation,he).
nmod:at(1,fall,vexation).
conj:and(1,mouthful,vexation).
mark(1,able,at).
neg(1,able,not).
cop(1,able,be).
advcl:at(1,fall,able).
mark(1,eat,to).
xcomp(1,able,eat).
dep(1,eat,afford).
det(1,amusement,the).
compound(1,amusement,fox).
amod(1,amusement,much).
dobj(1,afford,amusement).
% relations.
%% the crane in his turn asked the fox to sup with him and set before her a flagon with a long narrow mouth so that he could easily insert his neck and enjoy its contents at his leisure.
% dependencies.
root(2,root,ask).
det(2,crane,the).
nsubj(2,ask,crane).
nsubj(2,set,crane).
case(2,turn,in).
nmod:poss(2,turn,he).
nmod:in(2,crane,turn).
det(2,fox,the).
dobj(2,ask,fox).
case(2,sup,to).
nmod:to(2,ask,sup).
case(2,he,with).
nmod:with(2,ask,he).
cc(2,ask,and).
conj:and(2,ask,set).
case(2,flagon,before).
nmod:poss(2,flagon,she).
det(2,flagon,a).
nmod:before(2,set,flagon).
case(2,mouth,with).
det(2,mouth,a).
amod(2,mouth,long).
amod(2,mouth,narrow).
nmod:with(2,flagon,mouth).
mark(2,insert,so).
mwe(2,so,that).
nsubj(2,insert,he).
nsubj(2,enjoy,he).
aux(2,insert,could).
advmod(2,insert,easily).
advcl:so_that(2,set,insert).
nmod:poss(2,neck,he).
dobj(2,insert,neck).
cc(2,insert,and).
advcl:so_that(2,set,enjoy).
conj:and(2,insert,enjoy).
nmod:poss(2,contents,its).
dobj(2,enjoy,contents).
case(2,leisure,at).
nmod:poss(2,leisure,he).
nmod:at(2,enjoy,leisure).
% relations.
aos(2,set_before,crane,she_flagon_with_long_narrow_mouth).
aos(2,could_easily_insert,he,he_neck).
aos(2,could_insert,he,he_neck).
aos(2,set_before,crane,she_flagon_with_long_mouth).
aos(2,ask,crane,fox).
aos(2,ask_fox_to,crane,sup).
aos(2,set_before,crane,she_flagon_with_mouth).
aos(2,set_before,crane,she_flagon).
aos(2,is_with,she_flagon,long_narrow_mouth).
aos(2,ask_fox_with,crane,he).
aos(2,enjoy,he,its_contents).
aos(2,set_before,crane,she_flagon_with_narrow_mouth).
aos(2,is_in,crane,he_turn).
%% the fox unable even to taste it met with a fitting requital after the fashion of her own hospitality.
% dependencies.
root(3,root,meet).
det(3,fox,the).
nsubj(3,meet,fox).
amod(3,fox,unable).
advmod(3,unable,even).
mark(3,taste,to).
xcomp(3,unable,taste).
dobj(3,taste,it).
case(3,requital,with).
det(3,requital,a).
amod(3,requital,fitting).
nmod:with(3,meet,requital).
case(3,fashion,after).
det(3,fashion,the).
nmod:after(3,meet,fashion).
case(3,hospitality,of).
nmod:poss(3,hospitality,she).
amod(3,hospitality,own).
nmod:of(3,fashion,hospitality).
% relations.
aos(3,meet_with,fox,requital).
aos(3,meet_with,fox,fitting_requital).
aos(3,meet_after,fox,fashion_of_she_own_hospitality).
aos(3,meet_with,fox_unable,fitting_requital).
aos(3,meet_after,fox_unable,fashion).
aos(3,meet_after,fox_unable,fashion_of_she_own_hospitality).
aos(3,meet_after,fox_unable,fashion_of_she_hospitality).
aos(3,meet_with,fox_unable,requital).
aos(3,meet_after,fox,fashion).
aos(3,meet_after,fox,fashion_of_she_hospitality).
