root(0,ROOT,fighting).
nummod(0,cocks,two).
compound(0,cocks,game).
nsubj(0,fighting,cocks).
aux(0,fighting,were).
advmod(0,fighting,fiercely).
case(0,mastery,for).
det(0,mastery,the).
nmod:for(0,fighting,mastery).
case(0,farmyard,of).
det(0,farmyard,the).
nmod:of(0,mastery,farmyard).
were_fighting_for(0,two_game_cocks,mastery_of_farmyard).
were_fiercely_fighting_for(0,game_cocks,mastery_of_farmyard).
were_fighting_for(0,two_game_cocks,mastery).
were_fighting_for(0,game_cocks,mastery_of_farmyard).
were_fiercely_fighting_for(0,game_cocks,mastery).
were_fiercely_fighting_for(0,two_game_cocks,mastery_of_farmyard).
were_fighting_for(0,game_cocks,mastery).
were_fiercely_fighting_for(0,two_game_cocks,mastery).
root(1,ROOT,put).
nsubj(1,put,one).
case(1,last,at).
nmod:at(1,one,last).
det(1,other,the).
dobj(1,put,other).
case(1,flight,to).
nmod:to(1,put,flight).
root(2,ROOT,skulked).
nsubj(2,skulked,the).
nsubj(2,hid,the).
acl(2,the,vanquished).
dobj(2,vanquished,cock).
advmod(2,skulked,away).
cc(2,skulked,and).
conj:and(2,skulked,hid).
dobj(2,hid,himself).
case(2,corner,in).
det(2,corner,a).
amod(2,corner,quiet).
nmod:in(2,hid,corner).
mark(2,flapped,while).
det(2,conqueror,the).
nsubj(2,flapped,conqueror).
nsubj(2,crowed,conqueror).
acl(2,conqueror,flying).
compound:prt(2,flying,up).
case(2,wall,to).
det(2,wall,a).
amod(2,wall,high).
nmod:to(2,flying,wall).
advcl:while(2,hid,flapped).
nmod:poss(2,wings,his).
dobj(2,flapped,wings).
cc(2,flapped,and).
advcl:while(2,hid,crowed).
conj:and(2,flapped,crowed).
advmod(2,crowed,exultingly).
case(2,all,with).
nmod:with(2,crowed,all).
nsubj(2,might,his).
acl:relcl(2,all,might).
hid(2,the,himself).
vanquished(2,the,cock).
flapped(2,conqueror,his_wings).
root(3,ROOT,sailing).
det(3,sailing,an).
compound(3,sailing,eagle).
case(3,air,through).
det(3,air,the).
nmod:through(3,sailing,air).
dep(3,air,pounced).
case(3,him,upon).
nmod:upon(3,pounced,him).
cc(3,pounced,and).
dep(3,air,carried).
conj:and(3,pounced,carried).
dobj(3,carried,him).
compound:prt(3,carried,off).
case(3,talons,in).
nmod:poss(3,talons,his).
nmod:in(3,carried,talons).
root(4,ROOT,came).
nsubj(4,came,the).
nsubj(4,ruled,the).
acl(4,the,vanquished).
dobj(4,vanquished,cock).
advmod(4,vanquished,immediately).
compound:prt(4,came,out).
case(4,corner,of).
nmod:poss(4,corner,his).
nmod:of(4,came,corner).
cc(4,came,and).
conj:and(4,came,ruled).
dobj(4,ruled,henceforth).
case(4,mastery,with).
amod(4,mastery,undisputed).
nmod:with(4,ruled,mastery).
ruled_henceforth_with(4,the,undisputed_mastery).
came_out_of(4,the,his_corner).
vanquished_immediately(4,the,cock).
ruled_henceforth_with(4,the,mastery).
ruled(4,the,henceforth).
