root(0,ROOT,once).
case(0,time,upon).
det(0,time,a).
nmod:upon(0,once,time).
advmod(0,announced,when).
det(0,sun,the).
nsubj(0,announced,sun).
dep(0,once,announced).
nmod:poss(0,intention,his).
dobj(0,announced,intention).
mark(0,take,to).
acl:to(0,intention,take).
det(0,wife,a).
dobj(0,take,wife).
det(0,frogs,the).
nsubj(0,lifted,frogs).
acl:relcl(0,wife,lifted).
compound:prt(0,lifted,up).
nmod:poss(0,voices,their).
dobj(0,lifted,voices).
case(0,clamor,in).
nmod:in(0,lifted,clamor).
case(0,sky,to).
det(0,sky,the).
nmod:to(0,lifted,sky).
lifted_up(0,frogs,their_voices).
root(1,ROOT,inquired).
nsubj(1,inquired,jupiter).
acl(1,jupiter,disturbed).
case(1,noise,by).
det(1,noise,the).
nmod:by(1,disturbed,noise).
case(1,their,of).
nmod:of(1,noise,their).
amod(1,their,croaking).
det(1,cause,the).
dobj(1,inquired,cause).
case(1,complaint,of).
nmod:poss(1,complaint,their).
nmod:of(1,cause,complaint).
inquired(1,jupiter,cause).
disturbed_by(1,jupiter,noise_of_their_croaking).
disturbed_by(1,jupiter,noise_of_their).
disturbed_by(1,jupiter,noise).
inquired(1,jupiter,cause_of_their_complaint).
root(2,ROOT,said).
det:qmod(2,them,one).
mwe(2,one,of).
nsubj(2,said,them).
root(3,ROOT,now).
det(3,sun,the).
nmod:npmod(3,now,sun).
mark(3,parches,while).
nsubj(3,parches,he).
nsubj(3,compels,he).
cop(3,parches,is).
amod(3,parches,single).
dep(3,now,parches).
case(3,marsh,up).
det(3,marsh,the).
nmod:up(3,parches,marsh).
cc(3,parches,and).
dep(3,now,compels).
conj:and(3,parches,compels).
dobj(3,compels,us).
nsubj:xsubj(3,die,us).
mark(3,die,to).
xcomp(3,compels,die).
advmod(3,die,miserably).
case(3,homes,in).
nmod:poss(3,homes,our).
amod(3,homes,arid).
nmod:in(3,miserably,homes).
compels(3,he,us).
is(3,he,parches).
is_single_parches_up(3,he,marsh).
is(3,he,single_parches).
is_parches_up(3,he,marsh).
root(4,ROOT,condition).
nsubj(4,condition,what).
aux(4,condition,will).
cop(4,condition,be).
nmod:poss(4,condition,our).
amod(4,condition,future).
mark(4,beget,if).
nsubj(4,beget,he).
aux(4,beget,should).
advcl:if(4,condition,beget).
amod(4,suns,other).
dobj(4,beget,suns).
should_beget(4,he,suns).
should_beget(4,he,other_suns).
