root(0,ROOT,mounting).
det(0,fox,a).
nsubj(0,mounting,fox).
aux(0,mounting,was).
det(0,hedge,a).
dobj(0,mounting,hedge).
advmod(0,lost,when).
nsubj(0,lost,he).
nsubj(0,caught,he).
acl:relcl(0,hedge,lost).
nmod:poss(0,footing,his).
dobj(0,lost,footing).
cc(0,lost,and).
acl:relcl(0,hedge,caught).
conj:and(0,lost,caught).
dobj(0,caught,hold).
case(0,bramble,of).
det(0,bramble,a).
nmod:of(0,hold,bramble).
mark(0,save,to).
advcl:to(0,caught,save).
dobj(0,save,himself).
caught(0,he,hold_of_bramble).
lost(0,he,his_footing).
caught(0,he,hold).
root(1,ROOT,pricked).
aux(1,pricked,having).
cc(1,pricked,and).
advmod(1,tom,grievously).
conj:and(1,pricked,tom).
det(1,soles,the).
dobj(1,tom,soles).
case(1,feet,of).
nmod:poss(1,feet,his).
nmod:of(1,soles,feet).
nsubj(1,accused,he).
acl:relcl(1,soles,accused).
det(1,bramble,the).
dobj(1,accused,bramble).
mark(1,used,because).
advmod(1,fled,when).
nsubj(1,fled,he).
aux(1,fled,had).
advcl(1,used,fled).
case(1,her,to).
nmod:to(1,fled,her).
case(1,assistance,for).
nmod:for(1,fled,assistance).
nsubj(1,used,she).
aux(1,used,had).
advcl:because(1,accused,used).
nsubj(1,worse,him).
xcomp(1,used,worse).
case(1,hedge,than).
det(1,hedge,the).
nmod:than(1,tom,hedge).
dobj(1,pricked,itself).
had_fled_for(1,he,assistance).
accused_bramble(1,he,she_had_used).
accused(1,he,bramble).
had_fled_to(1,he,her).
had_used(1,she,him_worse).
root(2,ROOT,said).
det(2,bramble,the).
nsubj(2,said,bramble).
acl(2,bramble,interrupting).
dobj(2,interrupting,him).
root(3,ROOT,senses).
cc(3,senses,but).
nsubj(3,senses,you).
nsubj:xsubj(3,fasten,you).
advmod(3,senses,really).
aux(3,senses,must).
aux(3,senses,have).
cop(3,senses,been).
case(3,senses,out).
mwe(3,out,of).
nmod:poss(3,senses,your).
mark(3,fasten,to).
xcomp(3,senses,fasten).
dobj(3,fasten,yourself).
case(3,me,on).
nmod:on(3,senses,me).
nsubj(3,am,me).
ref(3,me,who).
acl:relcl(3,me,am).
nsubj(3,accustomed,myself).
nsubj:xsubj(3,fasten,myself).
advmod(3,accustomed,always).
ccomp(3,am,accustomed).
mark(3,fasten,to).
xcomp(3,accustomed,fasten).
case(3,others,upon).
nmod:upon(3,fasten,others).
fasten(3,you,yourself).
always_accustomed(3,myself,fasten).
accustomed(3,myself,fasten).
fasten_upon(3,myself,others).
must_out_of(3,you,really_must_have_your_senses).
accustomed(3,myself,fasten_upon_others).
always_accustomed(3,myself,fasten_upon_others).
must_out_of(3,you,must_have_your_senses).
