root(0,ROOT,used).
det(0,lion,a).
nsubj(0,used,lion).
case(0,prowl,to).
nmod:to(0,used,prowl).
case(0,field,about).
det(0,field,a).
nmod:about(0,used,field).
nmod:in(0,used,field).
case(0,which,in).
ref(0,field,which).
nummod(0,oxen,four).
nsubj(0,used,oxen).
nsubj:xsubj(0,dwell,oxen).
acl:relcl(0,field,used).
mark(0,dwell,to).
xcomp(0,used,dwell).
used_to(0,lion,prowl).
used(0,oxen,dwell).
used(0,four_oxen,dwell).
root(1,ROOT,time).
dep(1,time,many).
det(1,time,a).
nsubj(1,tried,he).
nsubj:xsubj(1,attack,he).
ccomp(1,time,tried).
mark(1,attack,to).
xcomp(1,tried,attack).
dobj(1,attack,them).
attack(1,he,them).
root(2,ROOT,came).
cc(2,came,but).
advmod(2,came,whenever).
nsubj(2,came,he).
mark(2,turned,near).
nsubj(2,turned,they).
advcl:near(2,came,turned).
nmod:poss(2,tails,their).
dobj(2,turned,tails).
case(2,one,to).
nmod:to(2,turned,one).
dep(2,one,another).
mark(2,met,so).
mwe(2,so,that).
det(2,way,whichever).
dobj(2,approached,way).
nsubj(2,approached,he).
advcl(2,met,approached).
dobj(2,approached,them).
nsubjpass(2,met,he).
auxpass(2,met,was).
advcl:so_that(2,turned,met).
case(2,horns,by).
det(2,horns,the).
nmod:agent(2,met,horns).
case(2,one,of).
det:qmod(2,them,one).
mwe(2,one,of).
nmod(2,horns,them).
turned(2,they,met_by_horns).
came(2,he,they_turned).
turned(2,they,their_tails).
approached(2,he,them).
turned(2,they,met).
was_met_by(2,he,horns).
was(2,he,met).
root(3,ROOT,last).
dep(3,last,at).
advmod(3,fell,however).
nsubj(3,fell,they).
acl:relcl(3,last,fell).
dobj(3,fell,a-quarrelling).
case(3,themselves,among).
nmod:among(3,fell,themselves).
cc(3,fell,and).
nsubj(3,went,each).
acl:relcl(3,last,went).
conj:and(3,fell,went).
advmod(3,went,off).
case(3,pasture,to).
nmod:to(3,off,pasture).
advmod(3,went,alone).
case(3,corner,in).
det(3,corner,a).
amod(3,corner,separate).
nmod:in(3,went,corner).
case(3,field,of).
det(3,field,the).
nmod:of(3,corner,field).
however_fell_among(3,they,themselves).
went_off_alone_in(3,each,separate_corner_of_field).
went_alone_in(3,each,corner).
went_off_in(3,each,separate_corner_of_field).
went_alone_in(3,each,separate_corner).
however_fell_a-quarrelling_among(3,they,themselves).
went_off_in(3,each,corner).
went_off_alone_in(3,each,corner).
however_fell(3,they,a-quarrelling).
went_off_alone_in(3,each,corner_of_field).
went_in(3,each,separate_corner).
went_in(3,each,corner_of_field).
went_in(3,each,separate_corner_of_field).
fell_among(3,they,themselves).
went_off_in(3,each,separate_corner).
went_off_alone_in(3,each,separate_corner).
went_alone_in(3,each,separate_corner_of_field).
fell_a-quarrelling_among(3,they,themselves).
went_alone_in(3,each,corner_of_field).
went_in(3,each,corner).
fell(3,they,a-quarrelling).
went_off_in(3,each,corner_of_field).
root(4,ROOT,lion).
dep(4,lion,then).
det(4,lion,the).
ccomp(4,lion,attacked).
nsubj(4,one,them).
xcomp(4,attacked,one).
case(4,one,by).
nmod:by(4,one,one).
cc(4,attacked,and).
advmod(4,made,soon).
ccomp(4,lion,made).
conj:and(4,attacked,made).
det(4,end,an).
dobj(4,made,end).
case(4,four,of).
det(4,four,all).
nmod:of(4,end,four).
