root(0,ROOT,lived).
nummod(0,frogs,two).
nsubj(0,lived,frogs).
advmod(0,lived,together).
case(0,marsh,in).
det(0,marsh,a).
nmod:in(0,lived,marsh).
lived_in(0,frogs,marsh).
lived_together_in(0,frogs,marsh).
lived_in(0,two_frogs,marsh).
lived_together_in(0,two_frogs,marsh).
root(1,ROOT,dried).
cc(1,dried,but).
nummod(1,summer,one).
amod(1,summer,hot).
nmod:tmod(1,dried,summer).
det(1,marsh,the).
nsubj(1,dried,marsh).
advmod(1,dried,up).
cc(1,dried,and).
nsubj(1,left,they).
conj:and(1,dried,left).
dobj(1,left,it).
nsubj:xsubj(1,look,it).
mark(1,look,to).
xcomp(1,left,look).
case(1,place,for).
det(1,place,another).
nmod:for(1,look,place).
mark(1,live,to).
acl:to(1,place,live).
case(1,frogs,in).
case(1,frogs,for).
nmod:for(1,live,frogs).
case(1,places,like).
amod(1,places,damp).
nmod:like(1,frogs,places).
mark(1,get,if).
nsubj(1,get,they).
aux(1,get,can).
advcl:if(1,live,get).
dobj(1,get,them).
dried_up_at_time(1,marsh,one_summer).
dried_at_time(1,marsh,one_hot_summer).
left(1,they,it).
dried_at_time(1,marsh,one_summer).
dried_up_at_time(1,marsh,one_hot_summer).
root(2,ROOT,by).
cc(2,by,and).
mark(2,came,by).
nsubj(2,came,they).
conj:and(2,by,came).
case(2,well,to).
det(2,well,a).
advmod(2,well,deep).
nmod:to(2,came,well).
cc(2,came,and).
det:qmod(2,them,one).
mwe(2,one,of).
nsubj(2,looked,them).
nsubj(2,said,them).
conj:and(2,by,looked).
conj:and(2,came,looked).
compound:prt(2,looked,down).
case(2,it,into).
nmod:into(2,looked,it).
cc(2,looked,and).
conj:and(2,came,said).
conj:and(2,looked,said).
case(2,other,to).
det(2,other,the).
nmod:to(2,said,other).
came_to(2,they,deep_well).
came_to(2,they,well).
root(3,ROOT,looks).
nsubj(3,looks,this).
det(3,place,a).
amod(3,place,nice).
amod(3,place,cool).
dobj(3,looks,place).
root(4,ROOT,let).
nsubj(4,jump,us).
nsubj(4,settle,us).
ccomp(4,let,jump).
nmod(4,jump,in).
cc(4,jump,and).
ccomp(4,let,settle).
conj:and(4,jump,settle).
advmod(4,settle,here).
root(5,ROOT,other).
cc(5,other,but).
det(5,other,the).
nsubj(5,had,other).
ref(5,other,who).
acl:relcl(5,other,had).
det(5,head,a).
amod(5,head,wiser).
dobj(5,had,head).
case(5,shoulders,on).
nmod:poss(5,shoulders,his).
nmod:on(5,had,shoulders).
acl(5,shoulders,replied).
root(6,ROOT,fast).
neg(6,fast,not).
advmod(6,fast,so).
nmod:poss(6,friend,my).
dep(6,fast,friend).
root(7,ROOT,supposing).
xcomp(7,supposing,this).
advmod(7,dried,well).
acl(7,this,dried).
compound:prt(7,dried,up).
case(7,marsh,like).
det(7,marsh,the).
nmod:like(7,dried,marsh).
advmod(7,get,how).
aux(7,get,should).
nsubj(7,get,we).
parataxis(7,this,get).
compound:prt(7,get,out).
advmod(7,get,again).
