%% the fishermen some fishermen were out trawling their nets.
% dependencies.
root(0,root,fisherman).
det(0,fisherman,the).
det(0,fisherman,some).
nsubj(0,trawl,fisherman).
cop(0,trawl,be).
mark(0,trawl,out).
acl:relcl(0,fisherman,trawl).
nmod:poss(0,net,they).
dobj(0,trawl,net).
% relations.
%% perceiving them to be very heavy they danced about for joy and supposed that they had taken a large catch.
% dependencies.
root(1,root,perceive).
dobj(1,perceive,they).
nsubj:xsubj(1,heavy,they).
mark(1,heavy,to).
cop(1,heavy,be).
advmod(1,heavy,very).
xcomp(1,perceive,heavy).
nsubj(1,dance,they).
nsubj(1,suppose,they).
ccomp(1,heavy,dance).
case(1,joy,about).
case(1,joy,for).
nmod:for(1,dance,joy).
cc(1,dance,and).
ccomp(1,heavy,suppose).
conj:and(1,dance,suppose).
mark(1,take,that).
nsubj(1,take,they).
aux(1,take,have).
ccomp(1,suppose,take).
det(1,catch,a).
amod(1,catch,large).
dobj(1,take,catch).
% relations.
aos(1,dance_about,they,about_joy).
%% when they had dragged the nets to the shore they found but few fish the nets were full of sand and stones and the men were beyond measure cast downso much at the disappointment which had befallen them but because they had formed such very different expectations.
% dependencies.
root(2,root,find).
advmod(2,drag,when).
nsubj(2,drag,they).
aux(2,drag,have).
advcl(2,find,drag).
det(2,net,the).
dobj(2,drag,net).
case(2,shore,to).
det(2,shore,the).
nmod:to(2,drag,shore).
nsubj(2,find,they).
cc(2,find,but).
amod(2,fish,few).
nsubj(2,full,fish).
det(2,net,the).
dep(2,fish,net).
cop(2,full,be).
conj:but(2,find,full).
case(2,sand,of).
nmod:of(2,full,sand).
cc(2,sand,and).
nmod:of(2,full,stone).
conj:and(2,sand,stone).
cc(2,find,and).
det(2,man,the).
nsubj(2,measure,man).
cop(2,measure,be).
case(2,measure,beyond).
conj:but(2,find,measure).
advcl(2,measure,cast).
advmod(2,much,downso).
xcomp(2,cast,much).
case(2,disappointment,at).
det(2,disappointment,the).
nmod:at(2,cast,disappointment).
nsubj(2,befall,disappointment).
ref(2,disappointment,which).
aux(2,befall,have).
acl:relcl(2,disappointment,befall).
dobj(2,befall,they).
cc(2,cast,but).
mark(2,form,because).
nsubj(2,form,they).
aux(2,form,have).
advcl(2,measure,form).
conj:but(2,cast,form).
amod(2,expectation,such).
advmod(2,different,very).
amod(2,expectation,different).
dobj(2,form,expectation).
% relations.
aos(2,cast,man,much).
aos(2,cast,man,downso_much).
aos(2,have_form,they,such_expectation).
aos(2,have_form,they,such_very_different_expectation).
aos(2,have_drag_net_to,they,shore).
aos(2,have_form,they,very_different_expectation).
aos(2,have_drag,they,net).
aos(2,have_form,they,such_different_expectation).
aos(2,have_form,they,different_expectation).
aos(2,be_beyond,man,measure).
aos(2,have_form,they,expectation).
%% one of their company an old man said.
% dependencies.
root(3,root,say).
nsubj(3,say,one).
case(3,company,of).
nmod:poss(3,company,they).
nmod:of(3,one,company).
det(3,man,a).
amod(3,man,old).
dep(3,company,man).
% relations.
%% let us cease lamenting my mates for as it seems to me sorrow is always the twin sister of joy.
% dependencies.
root(4,root,let).
nsubj(4,cease,we).
ccomp(4,let,cease).
xcomp(4,cease,lament).
nmod:poss(4,mate,my).
dobj(4,lament,mate).
mark(4,sister,for).
mark(4,seem,as).
nsubj(4,seem,it).
advcl:as(4,sister,seem).
case(4,I,to).
nmod:to(4,seem,I).
nsubj(4,sister,sorrow).
cop(4,sister,be).
advmod(4,sister,always).
det(4,sister,the).
amod(4,sister,twin).
advcl:for(4,cease,sister).
case(4,joy,of).
nmod:of(4,sister,joy).
% relations.
aos(4,be_always_sister_of,sorrow,joy).
aos(4,be_always_sister,sorrow,it_seem).
aos(4,cease,we,always_sister_of_joy).
aos(4,cease,we,sister).
aos(4,cease,we,always_twin_sister_of_joy).
aos(4,be,sorrow,always_sister).
aos(4,be_twin_sister,sorrow,it_seem_to_I).
aos(4,cease,we,always_twin_sister).
aos(4,seem_to,it,I).
aos(4,be_always_sister,sorrow,it_seem_to_I).
aos(4,be_sister,sorrow,it_seem_to_I).
aos(4,be_always_twin_sister_of,sorrow,joy).
aos(4,be_sister,sorrow,it_seem).
aos(4,be_twin_sister,sorrow,it_seem).
aos(4,cease,we,twin_sister_of_joy).
aos(4,be,sorrow,always_twin_sister).
aos(4,be_sister_of,sorrow,joy).
aos(4,cease,we,always_sister).
aos(4,be_twin_sister_of,sorrow,joy).
aos(4,cease,we,sister_of_joy).
aos(4,be,sorrow,sister).
aos(4,be_always_twin_sister,sorrow,it_seem).
aos(4,lament,we,my_mate).
aos(4,cease,we,twin_sister).
aos(4,be,sorrow,twin_sister).
aos(4,be_always_twin_sister,sorrow,it_seem_to_I).
%% and it was only to be looked for that we who just now were over-rejoiced should next have something to make us sad.
% dependencies.
root(5,root,be).
cc(5,be,and).
nsubj(5,be,it).
nsubjpass:xsubj(5,look,it).
advmod(5,be,only).
mark(5,look,to).
auxpass(5,look,be).
xcomp(5,be,look).
mark(5,have,for).
mark(5,have,that).
nsubj(5,over-rejoiced,we).
nsubj(5,have,we).
ref(5,we,who).
advmod(5,now,just).
advmod(5,over-rejoiced,now).
cop(5,over-rejoiced,be).
acl:relcl(5,we,over-rejoiced).
aux(5,have,should).
advmod(5,have,next).
advcl:that(5,look,have).
dobj(5,have,something).
mark(5,make,to).
advcl:to(5,have,make).
nsubj(5,sad,we).
xcomp(5,make,sad).
% relations.
aos(5,be,it,look).
aos(5,be_only,it,look).
aos(5,be,it,look).
