root(0,ROOT,carried).
det(0,swimming,a).
compound(0,swimming,fox).
nsubjpass(0,carried,swimming).
case(0,river,across).
det(0,river,a).
amod(0,river,rapid).
nmod:across(0,swimming,river).
auxpass(0,carried,was).
case(0,force,by).
det(0,force,the).
nmod:agent(0,carried,force).
case(0,current,of).
det(0,current,the).
nmod:of(0,force,current).
case(0,ravine,into).
det(0,ravine,a).
advmod(0,deep,very).
amod(0,ravine,deep).
nmod:into(0,carried,ravine).
advmod(0,lay,where).
nsubj(0,lay,he).
acl:relcl(0,ravine,lay).
case(0,time,for).
det(0,time,a).
amod(0,time,long).
nmod:for(0,lay,time).
advmod(0,much,very).
amod(0,bruised,much).
dobj(0,lay,bruised).
amod(0,bruised,sick).
cc(0,sick,and).
amod(0,bruised,unable).
conj:and(0,sick,unable).
mark(0,move,to).
advcl:to(0,lay,move).
was(0,fox_swimming,carried).
lay_for(0,he,time).
lay(0,he,very_much_bruised_sick).
lay_for(0,he,long_time).
lay(0,he,move).
lay(0,he,very_much_bruised).
lay(0,he,much_bruised).
lay(0,he,bruised).
lay(0,he,bruised_sick).
lay(0,he,much_bruised_sick).
root(1,ROOT,flies).
det(1,swarm,a).
nsubj(1,flies,swarm).
case(1,blood-sucking,of).
amod(1,blood-sucking,hungry).
nmod:of(1,swarm,blood-sucking).
dep(1,flies,settled).
case(1,him,upon).
nmod:upon(1,settled,him).
root(2,ROOT,saw).
det(2,passing,a).
compound(2,passing,hedgehog).
nsubj(2,saw,passing).
nsubj(2,inquired,passing).
nmod(2,saw,by).
nmod:poss(2,anguish,his).
dobj(2,saw,anguish).
cc(2,saw,and).
conj:and(2,saw,inquired).
mark(2,drive,if).
nsubj(2,drive,he).
aux(2,drive,should).
advcl:if(2,inquired,drive).
compound:prt(2,drive,away).
det(2,flies,the).
dobj(2,drive,flies).
nsubj(2,tormenting,flies).
ref(2,flies,that).
aux(2,tormenting,were).
acl:relcl(2,flies,tormenting).
dobj(2,tormenting,him).
saw(2,hedgehog_passing,his_anguish).
root(3,ROOT,means).
case(3,means,by).
neg(3,means,no).
root(4,ROOT,replied).
det(4,fox,the).
nsubj(4,replied,fox).
root(5,ROOT,molest).
nsubj(5,molest,pray).
aux(5,molest,do).
neg(5,molest,not).
dobj(5,molest,them).
root(6,ROOT,is).
advmod(6,is,how).
nsubj(6,is,this).
root(7,ROOT,said).
nsubj(7,said,').
det(7,hedgehog,the).
dobj(7,said,hedgehog).
said(7,,hedgehog).
root(8,ROOT,want).
aux(8,want,do).
dobj(8,want,you).
nsubj:xsubj(8,rid,you).
neg(8,want,not).
mark(8,rid,to).
cop(8,rid,be).
xcomp(8,want,rid).
case(8,them,of).
nmod:of(8,rid,them).
root(9,ROOT,').
root(10,ROOT,no).
root(11,ROOT,returned).
det(11,fox,the).
nsubj(11,returned,fox).
root(12,ROOT,come).
mark(12,come,for).
det(12,flies,these).
dobj(12,see,flies).
nsubj(12,come,flies).
nsubj(12,drink,flies).
ref(12,flies,which).
nsubj(12,see,you).
acl:relcl(12,flies,see).
cop(12,full,are).
advcl(12,see,full).
case(12,blood,of).
nmod:of(12,full,blood).
cc(12,blood,and).
nmod:of(12,full,sting).
conj:and(12,blood,sting).
dep(12,blood,me).
cc(12,me,but).
dep(12,blood,little).
conj:but(12,me,little).
cc(12,full,and).
mark(12,rid,if).
nsubj(12,rid,you).
advcl(12,see,rid).
conj:and(12,full,rid).
dobj(12,rid,me).
case(12,these,of).
nmod:of(12,rid,these).
nsubj(12,hungry,these).
ref(12,these,which).
cop(12,hungry,are).
advmod(12,hungry,already).
amod(12,others,satiated).
dep(12,hungry,others).
advmod(12,hungry,more).
acl:relcl(12,these,hungry).
aux(12,come,will).
case(12,place,in).
nmod:poss(12,place,their).
nmod:in(12,come,place).
cc(12,come,and).
aux(12,drink,will).
conj:and(12,come,drink).
compound:prt(12,drink,up).
det:predet(12,blood,all).
det(12,blood,the).
dobj(12,drink,blood).
nsubj(12,left,i).
aux(12,left,have).
acl:relcl(12,blood,left).
rid(12,you,me).
