root(0,ROOT,got).
det(0,fox,a).
nsubj(0,got,fox).
acl(0,fox,had).
case(0,means,by).
det(0,means,some).
nmod:by(0,had,means).
case(0,store-room,into).
det(0,store-room,the).
nmod:into(0,got,store-room).
case(0,theatre,of).
det(0,theatre,a).
nmod:of(0,store-room,theatre).
got_into(0,fox,store-room_of_theatre).
had_by(0,fox,means).
got_into(0,fox,store-room).
root(1,ROOT,he).
dep(1,he,suddenly).
acl:relcl(1,he,observed).
det(1,face,a).
dobj(1,observed,face).
xcomp(1,observed,glaring).
compound:prt(1,glaring,down).
case(1,him,on).
nmod:on(1,glaring,him).
cc(1,observed,and).
acl:relcl(1,he,began).
conj:and(1,observed,began).
mark(1,frightened,to).
cop(1,frightened,be).
advmod(1,frightened,very).
xcomp(1,began,frightened).
glaring_down_on(1,face,him).
began(1,face,very_frightened).
began(1,face,frightened).
root(2,ROOT,looking).
cc(2,looking,but).
advmod(2,closely,more).
advmod(2,looking,closely).
nsubj(2,found,he).
advcl(2,closely,found).
nsubj(2,mask,it).
cop(2,mask,was).
advmod(2,mask,only).
det(2,mask,a).
ccomp(2,found,mask).
case(2,actors,such).
mwe(2,such,as).
nmod:such_as(2,mask,actors).
acl:relcl(2,actors,use).
mark(2,put,to).
xcomp(2,use,put).
compound:prt(2,put,over).
nmod:poss(2,face,their).
dobj(2,put,face).
root(3,ROOT,ah).
root(4,ROOT,said).
det(4,fox,the).
nsubj(4,said,fox).
root(5,ROOT,look).
nsubj(5,look,you).
advmod(5,fine,very).
xcomp(5,look,fine).
look(5,you,very_fine).
look(5,you,fine).
root(6,ROOT,pity).
nsubj(6,pity,it).
cop(6,pity,is).
det(6,pity,a).
nsubj(6,got,you).
aux(6,got,have).
neg(6,got,not).
acl:relcl(6,pity,got).
det(6,brains,any).
dobj(6,got,brains).
