root(0,ROOT,fox).
det(0,fox,the).
cc(0,fox,and).
det(0,leopard,the).
conj:and(0,fox,leopard).
acl(0,fox,disputed).
nsubj(0,beautiful,which).
cop(0,beautiful,was).
det(0,beautiful,the).
advmod(0,beautiful,more).
ccomp(0,disputed,beautiful).
case(0,two,of).
det(0,two,the).
nmod:of(0,beautiful,two).
root(1,ROOT,exhibited).
det(1,leopard,the).
nsubj(1,exhibited,leopard).
dobj(1,exhibited,one).
case(1,one,by).
nmod:by(1,exhibited,one).
det(1,spots,the).
amod(1,spots,various).
xcomp(1,exhibited,spots).
nsubj(1,decorated,spots).
ref(1,spots,which).
acl:relcl(1,spots,decorated).
nmod:poss(1,skin,his).
dobj(1,decorated,skin).
exhibited(1,leopard,one).
root(2,ROOT,fox).
cc(2,fox,but).
det(2,fox,the).
dep(2,fox,interrupting).
nsubj(2,said,him).
ccomp(2,interrupting,said).
root(3,ROOT,beautiful).
cc(3,beautiful,and).
advmod(3,much,how).
advmod(3,beautiful,much).
advmod(3,beautiful,more).
mark(3,i,than).
nsubj(3,i,you).
cop(3,i,am).
ccomp(3,beautiful,i).
nsubjpass(3,decorated,i).
nsubjpass(3,decorated,i).
ref(3,i,who).
auxpass(3,decorated,am).
acl:relcl(3,i,decorated).
acl:relcl(3,i,decorated).
conj:but(3,decorated,decorated).
neg(3,body,not).
case(3,body,in).
nmod:in(3,decorated,body).
cc(3,decorated,but).
case(3,mind,in).
nmod:in(3,decorated,mind).
