root(0,ROOT,caught).
det(0,man,a).
nsubj(0,caught,man).
nsubj(0,said,man).
advmod(0,much,very).
amod(0,man,much).
amod(0,man,annoyed).
case(0,flea,with).
det(0,flea,a).
nmod:with(0,annoyed,flea).
dobj(0,caught,him).
case(0,last,at).
nmod:at(0,caught,last).
cc(0,caught,and).
conj:and(0,caught,said).
annoyed_with(0,man,flea).
caught(0,man,him).
caught(0,man_much_annoyed,him).
caught(0,man_much,him).
annoyed_with(0,man_much,flea).
caught(0,man_annoyed,him).
root(1,ROOT,who).
cop(1,who,are).
nsubj(1,who,you).
nsubj(1,dare,who).
dep(1,who,dare).
mark(1,feed,to).
ccomp(1,dare,feed).
case(1,limbs,on).
nmod:poss(1,limbs,my).
nmod:on(1,feed,limbs).
cc(1,feed,and).
mark(1,cost,to).
ccomp(1,dare,cost).
conj:and(1,feed,cost).
iobj(1,cost,me).
advmod(1,much,so).
amod(1,trouble,much).
dobj(1,cost,trouble).
mark(1,catching,in).
acl:in(1,trouble,catching).
dobj(1,catching,you).
catching(1,trouble,you).
catching(1,much_trouble,you).
root(2,ROOT,replied).
punct(2,replied,').
det(2,flea,the).
nsubj(2,replied,flea).
root(3,ROOT,do).
nsubj(3,do,o).
nmod:poss(3,pray,my).
amod(3,pray,dear).
amod(3,pray,sir).
nmod(3,o,pray).
dep(3,pray,spare).
nmod:poss(3,life,my).
dep(3,spare,life).
cc(3,spare,and).
dep(3,pray,destroy).
conj:and(3,spare,destroy).
dobj(3,destroy,me).
neg(3,i,not).
case(3,i,for).
nmod:for(3,destroy,i).
aux(3,do,can).
neg(3,do,not).
advmod(3,do,possibly).
dep(3,harm,you).
amod(3,harm,much).
dobj(3,do,harm).
root(4,ROOT,replied).
det(4,laughing,the).
compound(4,laughing,man).
nsubj(4,replied,laughing).
root(5,ROOT,ought).
nsubj(5,ought,now).
nsubjpass:xsubj(5,tolerated,now).
nsubj(5,die,you).
aux(5,die,shall).
advmod(5,die,certainly).
acl:relcl(5,now,die).
case(5,hands,by).
amod(5,hands,mine).
amod(5,hands,own).
nmod:by(5,die,hands).
case(5,evil,for).
neg(5,evil,no).
nmod:for(5,hands,evil).
mark(5,small,whether).
nsubj(5,small,it).
nsubj(5,large,it).
cop(5,small,be).
ccomp(5,die,small).
cc(5,small,or).
ccomp(5,die,large).
conj:or(5,small,large).
mark(5,tolerated,to).
auxpass(5,tolerated,be).
xcomp(5,ought,tolerated).
