root(0,ROOT,strolling).
nsubj(0,strolling,one).
amod(0,summer,hot).
nmod:poss(0,day,summer).
case(0,summer,'s).
dep(0,one,day).
det(0,fox,a).
dep(0,one,fox).
aux(0,strolling,was).
case(0,orchard,through).
det(0,orchard,an).
nmod:through(0,strolling,orchard).
mark(0,came,till).
nsubj(0,came,he).
advcl:till(0,strolling,came).
case(0,bunch,to).
det:qmod(0,grapes,a).
mwe(0,a,bunch).
mwe(0,a,of).
nmod(0,came,grapes).
advmod(0,ripening,just).
acl(0,grapes,ripening).
case(0,vine,on).
det(0,vine,a).
nmod:on(0,ripening,vine).
nsubjpass(0,trained,vine).
ref(0,vine,which).
aux(0,trained,had).
auxpass(0,trained,been).
acl:relcl(0,vine,trained).
case(0,branch,over).
det(0,branch,a).
amod(0,branch,lofty).
nmod:over(0,trained,branch).
has(0,hot_summer,day).
root(1,ROOT,thing).
advmod(1,thing,just).
det(1,thing,the).
mark(1,quench,to).
dep(1,thing,quench).
nmod:poss(1,thirst,my).
dobj(1,quench,thirst).
root(2,ROOT,he).
case(2,he,quoth).
root(3,ROOT,drawing).
compound:prt(3,drawing,back).
det(3,paces,a).
amod(3,paces,few).
dobj(3,drawing,paces).
nsubj(3,took,he).
nsubj(3,missed,he).
acl:relcl(3,paces,took).
det(3,run,a).
dobj(3,took,run).
cc(3,run,and).
det(3,jump,a).
dobj(3,took,jump).
conj:and(3,run,jump).
cc(3,took,and).
advmod(3,missed,just).
acl:relcl(3,paces,missed).
conj:and(3,took,missed).
det(3,bunch,the).
dobj(3,missed,bunch).
took(3,he,run).
just_missed(3,he,bunch).
took(3,he,jump).
missed(3,he,bunch).
root(4,ROOT,turning).
dobj(4,turning,round).
advmod(4,turning,again).
case(4,one,with).
det(4,one,a).
nmod:with(4,turning,one).
nummod(4,three,two).
dobj(4,turning,three).
nsubj(4,jumped,he).
acl:relcl(4,three,jumped).
compound:prt(4,jumped,up).
cc(4,success,but).
case(4,success,with).
neg(4,success,no).
amod(4,success,greater).
nmod:with(4,jumped,success).
root(5,ROOT,he).
dep(5,he,again).
cc(5,again,and).
conj:and(5,again,again).
dep(5,he,again).
acl:relcl(5,he,tried).
mark(5,had,after).
det(5,morsel,the).
amod(5,morsel,tempting).
nsubj(5,had,morsel).
nsubj:xsubj(5,give,morsel).
nsubj(5,walked,morsel).
cc(5,last,but).
case(5,last,at).
nmod:at(5,morsel,last).
advcl:after(5,tried,had).
mark(5,give,to).
xcomp(5,had,give).
dobj(5,give,it).
compound:prt(5,give,up).
cc(5,had,and).
advcl:after(5,tried,walked).
conj:and(5,had,walked).
compound:prt(5,walked,away).
case(5,nose,with).
nmod:poss(5,nose,his).
nmod:with(5,walked,nose).
case(5,air,in).
det(5,air,the).
nmod:in(5,walked,air).
acl(5,air,saying).
give_up(5,morsel,it).
walked_away_with(5,morsel,his_nose).
walked_away_in(5,tempting_morsel,air).
walked_away_in(5,morsel,air_saying).
give_up(5,tempting_morsel,it).
walked_away_with(5,tempting_morsel,his_nose).
walked_away_in(5,tempting_morsel,air_saying).
walked_away_in(5,morsel,air).
root(6,ROOT,sure).
nsubj(6,sure,i).
cop(6,sure,am).
nsubj(6,sour,they).
cop(6,sour,are).
ccomp(6,sure,sour).
am(6,i,sure).
are(6,they,sour).
