root(0,ROOT,happened).
nsubj(0,happened,it).
mark(0,caught,that).
det(0,fox,a).
nsubj(0,caught,fox).
ccomp(0,happened,caught).
nmod:poss(0,tail,its).
dobj(0,caught,tail).
case(0,trap,in).
det(0,trap,a).
nmod:in(0,caught,trap).
cc(0,trap,and).
mark(0,struggling,in).
nmod:in(0,caught,struggling).
conj:and(0,trap,struggling).
mark(0,release,to).
xcomp(0,struggling,release).
nsubj(0,lost,himself).
dep(0,release,lost).
det:qmod(0,it,all).
mwe(0,all,of).
dobj(0,lost,it).
case(0,stump,but).
det(0,stump,the).
nmod:but(0,all,stump).
caught(0,fox,its_tail).
root(1,ROOT,ashamed).
case(1,first,at).
advcl:at(1,ashamed,first).
nsubj(1,ashamed,he).
nsubj:xsubj(1,show,he).
cop(1,ashamed,was).
mark(1,show,to).
xcomp(1,ashamed,show).
dobj(1,show,himself).
case(1,foxes,among).
nmod:poss(1,foxes,his).
amod(1,foxes,fellow).
nmod:among(1,show,foxes).
was(1,he,ashamed).
was_ashamed_at(1,he,first).
show(1,he,himself).
root(2,ROOT,but).
case(2,last,at).
nmod:at(2,but,last).
nsubj(2,determined,he).
nsubj:xsubj(2,put,he).
nsubj(2,summoned,he).
acl:relcl(2,last,determined).
mark(2,put,to).
xcomp(2,determined,put).
det(2,face,a).
amod(2,face,bolder).
dobj(2,put,face).
case(2,misfortune,upon).
nmod:poss(2,misfortune,his).
nmod:upon(2,put,misfortune).
cc(2,determined,and).
acl:relcl(2,last,summoned).
conj:and(2,determined,summoned).
det:predet(2,foxes,all).
det(2,foxes,the).
dobj(2,summoned,foxes).
case(2,meeting,to).
det(2,meeting,a).
amod(2,meeting,general).
nmod:to(2,summoned,meeting).
mark(2,consider,to).
advcl:to(2,summoned,consider).
det(2,proposal,a).
dobj(2,consider,proposal).
dobj(2,had,proposal).
nsubj:xsubj(2,place,proposal).
ref(2,proposal,which).
nsubj(2,had,he).
acl:relcl(2,proposal,had).
mark(2,place,to).
xcomp(2,had,place).
case(2,them,before).
nmod:before(2,place,them).
had(2,he,place_before_them).
put_face_upon(2,he,his_misfortune).
summoned(2,he,foxes).
summoned_foxes(2,he,consider).
had(2,he,place).
summoned_foxes_to(2,he,meeting).
place_before(2,he,them).
put(2,he,face).
put(2,he,bolder_face).
summoned_foxes_to(2,he,general_meeting).
root(3,ROOT,assembled).
advmod(3,assembled,when).
nsubj(3,assembled,they).
aux(3,assembled,had).
advmod(3,assembled,together).
det(3,fox,the).
nsubj(3,proposed,fox).
ccomp(3,assembled,proposed).
mark(3,do,that).
nsubj(3,do,they).
aux(3,do,should).
advmod(3,do,all).
ccomp(3,proposed,do).
advmod(3,do,away).
case(3,tails,with).
nmod:poss(3,tails,their).
nmod:with(3,do,tails).
do_with(3,they,their_tails).
all_do_away_with(3,they,their_tails).
all_do_with(3,they,their_tails).
do_away_with(3,they,their_tails).
root(4,ROOT,pointed).
nsubj(4,pointed,he).
compound:prt(4,pointed,out).
advmod(4,was,how).
dep(4,how,inconvenient).
det(4,tail,a).
nsubj(4,was,tail).
ccomp(4,pointed,was).
advmod(4,pursued,when).
nsubjpass(4,pursued,they).
auxpass(4,pursued,were).
advcl(4,was,pursued).
case(4,enemies,by).
nmod:poss(4,enemies,their).
nmod:agent(4,pursued,enemies).
det(4,dogs,the).
dep(4,enemies,dogs).
were_pursued_by(4,they,their_enemies).
were(4,they,pursued).
were(4,they,when_pursued_by_their_enemies).
were(4,they,when_pursued).
root(5,ROOT,way).
advmod(5,much,how).
advmod(5,way,much).
nsubj(5,way,it).
cop(5,way,was).
case(5,way,in).
det(5,way,the).
advmod(5,desired,when).
nsubj(5,desired,they).
nsubj:xsubj(5,sit,they).
nsubj:xsubj(5,hold,they).
advcl(5,way,desired).
mark(5,sit,to).
xcomp(5,desired,sit).
advmod(5,sit,down).
cc(5,sit,and).
xcomp(5,desired,hold).
conj:and(5,sit,hold).
det(5,conversation,a).
amod(5,conversation,friendly).
dobj(5,hold,conversation).
case(5,one,with).
nmod:with(5,hold,one).
dep(5,one,another).
desired(5,they,sit_down).
desired(5,they,sit).
was_in(5,it,much_way).
was_in(5,it,way).
was_in(5,it,how_much_way).
root(6,ROOT,failed).
nsubj(6,failed,he).
nsubj:xsubj(6,see,he).
mark(6,see,to).
xcomp(6,failed,see).
det(6,advantage,any).
dobj(6,see,advantage).
mark(6,carrying,in).
advcl:in(6,see,carrying).
case(6,encumbrance,about).
det:predet(6,encumbrance,such).
det(6,encumbrance,a).
amod(6,encumbrance,useless).
nmod:about(6,carrying,encumbrance).
see(6,he,advantage).
see_advantage(6,he,carrying).
root(7,ROOT,is).
nsubj(7,is,that).
dep(7,very,all).
advmod(7,is,very).
advmod(7,is,well).
root(8,ROOT,said).
det:qmod(8,foxes,one).
mwe(8,one,of).
det(8,foxes,the).
amod(8,foxes,older).
nsubj(8,said,foxes).
root(9,ROOT,think).
cc(9,think,but).
nsubj(9,think,i).
aux(9,think,do).
neg(9,think,not).
nsubj(9,recommended,you).
aux(9,recommended,would).
aux(9,recommended,have).
ccomp(9,think,recommended).
dobj(9,recommended,us).
nsubj:xsubj(9,dispense,us).
mark(9,dispense,to).
xcomp(9,recommended,dispense).
case(9,ornament,with).
nmod:poss(9,ornament,our).
compound(9,ornament,chief).
nmod:with(9,dispense,ornament).
mark(9,happened,if).
nsubj(9,happened,you).
nsubj:xsubj(9,lose,you).
aux(9,happened,had).
neg(9,happened,not).
advcl:if(9,dispense,happened).
mark(9,lose,to).
xcomp(9,happened,lose).
nsubj(9,yourself,it).
xcomp(9,lose,yourself).
