root(0,ROOT,grieved).
det(0,frogs,the).
nsubj(0,grieved,frogs).
mark(0,having,at).
advcl:at(0,grieved,having).
neg(0,ruler,no).
amod(0,ruler,established).
nsubj(0,sent,ruler).
ccomp(0,having,sent).
dobj(0,sent,ambassadors).
mark(0,jupiter,to).
advcl:to(0,sent,jupiter).
xcomp(0,jupiter,entreating).
case(0,king,for).
det(0,king,a).
nmod:for(0,entreating,king).
root(1,ROOT,perceiving).
nmod:poss(1,simplicity,their).
dobj(1,perceiving,simplicity).
nsubj(1,cast,he).
acl:relcl(1,simplicity,cast).
compound:prt(1,cast,down).
det(1,log,a).
amod(1,log,huge).
dobj(1,cast,log).
case(1,lake,into).
det(1,lake,the).
nmod:into(1,cast,lake).
cast_down_log_into(1,he,lake).
cast_down(1,he,log).
cast_down(1,he,huge_log).
root(2,ROOT,terrified).
det(2,frogs,the).
nsubjpass(2,terrified,frogs).
nsubjpass(2,hid,frogs).
auxpass(2,terrified,were).
case(2,splash,at).
det(2,splash,the).
nmod:at(2,terrified,splash).
acl(2,splash,occasioned).
case(2,fall,by).
nmod:poss(2,fall,its).
nmod:by(2,occasioned,fall).
cc(2,terrified,and).
conj:and(2,terrified,hid).
dobj(2,hid,themselves).
case(2,depths,in).
det(2,depths,the).
nmod:in(2,hid,depths).
case(2,pool,of).
det(2,pool,the).
nmod:of(2,depths,pool).
were(2,frogs,terrified).
were_terrified_at(2,frogs,splash).
were_terrified_at(2,frogs,splash_occasioned_by_its_fall).
were_terrified_at(2,frogs,splash_occasioned).
hid(2,frogs,themselves).
root(3,ROOT,soon).
cc(3,soon,but).
advmod(3,soon,as).
mark(3,realized,as).
nsubj(3,realized,they).
dep(3,soon,realized).
mark(3,motionless,that).
det(3,log,the).
amod(3,log,huge).
nsubj(3,motionless,log).
cop(3,motionless,was).
ccomp(3,realized,motionless).
nsubj(3,swam,they).
ccomp(3,motionless,swam).
advmod(3,swam,again).
case(3,top,to).
det(3,top,the).
nmod:to(3,swam,top).
case(3,water,of).
det(3,water,the).
nmod:of(3,top,water).
acl:relcl(3,water,dismissed).
nmod:poss(3,fears,their).
nsubj(3,climbed,fears).
nsubj(3,began,fears).
ccomp(3,dismissed,climbed).
advmod(3,climbed,up).
cc(3,climbed,and).
ccomp(3,dismissed,began).
conj:and(3,climbed,began).
xcomp(3,began,squatting).
case(3,it,on).
nmod:on(3,squatting,it).
case(3,contempt,in).
nmod:in(3,squatting,contempt).
swam_to(3,they,top).
was(3,log,motionless).
was(3,huge_log,motionless).
began(3,their_fears,squatting).
began(3,their_fears,squatting_on_it_in_contempt).
swam_again_to(3,they,top).
began(3,their_fears,squatting_in_contempt).
began(3,their_fears,squatting_on_it).
root(4,ROOT,began).
case(4,time,after).
det(4,time,some).
nmod:after(4,began,time).
nsubj(4,began,they).
nsubj:xsubj(4,think,they).
nsubj(4,sent,they).
mark(4,think,to).
xcomp(4,began,think).
nsubj(4,ill-treated,themselves).
xcomp(4,think,ill-treated).
case(4,appointment,in).
det(4,appointment,the).
nmod:in(4,ill-treated,appointment).
case(4,ruler,of).
advmod(4,inert,so).
amod(4,ruler,inert).
det(4,ruler,a).
nmod:of(4,appointment,ruler).
cc(4,began,and).
conj:and(4,began,sent).
det(4,deputation,a).
amod(4,deputation,second).
dobj(4,sent,deputation).
case(4,jupiter,to).
nmod:to(4,sent,jupiter).
mark(4,pray,to).
advcl:to(4,sent,pray).
mark(4,set,that).
nsubj(4,set,he).
aux(4,set,would).
ccomp(4,pray,set).
case(4,them,over).
nmod:over(4,set,them).
det(4,sovereign,another).
nmod:tmod(4,set,sovereign).
ill-treated_in(4,themselves,appointment_of_so_inert_ruler).
ill-treated_in(4,themselves,appointment_of_inert_ruler).
set_over(4,he,them).
think(4,they,themselves_ill-treated_in_appointment_of_so_inert_ruler).
think(4,they,themselves_ill-treated_in_appointment).
sent_deputation(4,they,pray).
think(4,they,themselves_ill-treated_in_appointment_of_ruler).
sent(4,they,deputation).
think(4,they,themselves_ill-treated).
think(4,they,themselves_ill-treated_in_appointment_of_inert_ruler).
began_after(4,they,time).
ill-treated_in(4,themselves,appointment).
sent(4,they,second_deputation).
sent_deputation_to(4,they,jupiter).
ill-treated_in(4,themselves,appointment_of_ruler).
began(4,they,think).
root(5,ROOT,gave).
nsubj(5,gave,he).
advmod(5,gave,then).
iobj(5,gave,them).
det(5,eel,an).
dobj(5,gave,eel).
mark(5,govern,to).
acl:to(5,eel,govern).
dobj(5,govern,them).
gave(5,he,them).
root(6,ROOT,discovered).
advmod(6,discovered,when).
det(6,frogs,the).
nsubj(6,discovered,frogs).
nmod:poss(6,nature,his).
amod(6,nature,easy).
amod(6,nature,good).
dobj(6,discovered,nature).
nsubj(6,sent,they).
nsubj:xsubj(6,beg,they).
dep(6,discovered,sent).
advmod(6,sent,yet).
det(6,time,a).
amod(6,time,third).
nmod:tmod(6,sent,time).
case(6,jupiter,to).
nmod:to(6,sent,jupiter).
mark(6,beg,to).
xcomp(6,sent,beg).
dobj(6,beg,him).
nsubj:xsubj(6,choose,him).
mark(6,choose,to).
xcomp(6,beg,choose).
case(6,them,for).
nmod:for(6,choose,them).
advmod(6,choose,still).
det(6,king,another).
nmod:npmod(6,still,king).
discovered(6,frogs,his_nature).
discovered(6,frogs,his_easy_nature).
beg(6,they,him).
discovered(6,frogs,his_easy_good_nature).
choose_still_for(6,him,them).
discovered(6,frogs,his_good_nature).
choose_for(6,him,them).
root(7,ROOT,jupiter).
dep(7,jupiter,displeased).
case(7,all,with).
nmod:with(7,displeased,all).
nmod:poss(7,complaints,their).
nsubj(7,sent,complaints).
acl:relcl(7,all,sent).
det(7,heron,a).
nsubj(7,preyed,heron).
nsubj(7,left,heron).
nsubj:xsubj(7,croak,heron).
ref(7,heron,who).
acl:relcl(7,heron,preyed).
case(7,day,upon).
det(7,day,the).
compound(7,day,frogs).
nmod:upon(7,preyed,day).
case(7,day,by).
nmod:by(7,preyed,day).
mark(7,were,till).
expl(7,were,there).
advcl:till(7,preyed,were).
nsubj(7,were,none).
ccomp(7,sent,left).
mark(7,croak,to).
xcomp(7,left,croak).
case(7,lake,upon).
det(7,lake,the).
nmod:upon(7,croak,lake).
