root(0,ROOT,attracted).
det:qmod(0,flies,a).
mwe(0,a,number).
mwe(0,a,of).
nsubjpass(0,attracted,flies).
auxpass(0,attracted,were).
case(0,jar,to).
det(0,jar,a).
nmod:to(0,attracted,jar).
nsubjpass(0,overturned,jar).
nsubjpass(0,placing,jar).
case(0,honey,of).
nmod:of(0,jar,honey).
ref(0,jar,which).
aux(0,overturned,had).
auxpass(0,overturned,been).
acl:relcl(0,jar,overturned).
case(0,room,in).
det(0,housekeeper,a).
nmod:poss(0,room,housekeeper).
case(0,housekeeper,'s).
nmod:in(0,overturned,room).
cc(0,overturned,and).
acl:relcl(0,jar,placing).
conj:and(0,overturned,placing).
nmod:poss(0,feet,their).
dobj(0,placing,feet).
mark(0,ate,in).
nsubj(0,ate,it).
advcl:in(0,placing,ate).
advmod(0,ate,greedily).
in(0,housekeeper,room).
were(0,flies,attracted).
root(1,ROOT,became).
nmod:poss(1,feet,their).
nsubj(1,became,feet).
nsubjpass(1,suffocated,feet).
advmod(1,became,however).
advmod(1,smeared,so).
ccomp(1,became,smeared).
case(1,honey,with).
det(1,honey,the).
nmod:with(1,smeared,honey).
mark(1,use,that).
nsubj(1,use,they).
aux(1,use,could).
neg(1,use,not).
ccomp(1,smeared,use).
nmod:poss(1,wings,their).
dobj(1,use,wings).
cc(1,smeared,nor).
ccomp(1,became,release).
conj:nor(1,smeared,release).
dobj(1,release,themselves).
cc(1,became,and).
auxpass(1,suffocated,were).
conj:and(1,became,suffocated).
were(1,their_feet,suffocated).
root(2,ROOT,just).
mark(2,expiring,as).
nsubj(2,expiring,they).
cop(2,expiring,were).
dep(2,just,expiring).
nsubj(2,exclaimed,they).
acl:relcl(2,expiring,exclaimed).
root(3,ROOT,creatures).
compound(3,creatures,o).
amod(3,creatures,foolish).
mark(3,sake,that).
nsubj(3,sake,we).
cop(3,sake,are).
case(3,sake,for).
det(3,sake,the).
dep(3,creatures,sake).
case(3,pleasure,of).
det(3,pleasure,a).
amod(3,pleasure,little).
nmod:of(3,creatures,pleasure).
nsubj(3,destroyed,we).
aux(3,destroyed,have).
acl:relcl(3,pleasure,destroyed).
dobj(3,destroyed,ourselves).
have_destroyed(3,we,ourselves).
are_for(3,we,sake).
