root(0,ROOT,saw).
det(0,kid,a).
nsubj(0,saw,kid).
auxpass(0,perched,was).
acl:relcl(0,kid,perched).
compound:prt(0,perched,up).
case(0,top,on).
det(0,top,the).
nmod:on(0,perched,top).
case(0,house,of).
det(0,house,a).
nmod:of(0,top,house).
cc(0,perched,and).
acl:relcl(0,kid,looking).
conj:and(0,perched,looking).
compound:prt(0,looking,down).
det(0,wolf,a).
dobj(0,saw,wolf).
acl(0,wolf,passing).
case(0,him,under).
nmod:under(0,passing,him).
root(1,ROOT,began).
advmod(1,began,immediately).
nsubj(1,began,he).
nsubj:xsubj(1,revile,he).
nsubj:xsubj(1,attack,he).
mark(1,revile,to).
xcomp(1,began,revile).
cc(1,revile,and).
xcomp(1,began,attack).
conj:and(1,revile,attack).
nmod:poss(1,enemy,his).
dobj(1,revile,enemy).
revile(1,he,his_enemy).
root(2,ROOT,murderer).
cc(2,murderer,and).
conj:and(2,murderer,thief).
root(3,ROOT,cried).
nsubj(3,cried,he).
root(4,ROOT,do).
nsubj(4,do,what).
dobj(4,do,you).
advmod(4,do,here).
case(4,houses,near).
amod(4,folks,honest).
nmod:poss(4,houses,folks).
case(4,folks,').
nmod:near(4,do,houses).
root(5,ROOT,dare).
advmod(5,dare,how).
nsubj(5,make,you).
ccomp(5,dare,make).
det(5,appearance,an).
dobj(5,make,appearance).
advmod(5,known,where).
nmod:poss(5,deeds,your).
amod(5,deeds,vile).
nsubjpass(5,known,deeds).
auxpass(5,known,are).
advcl(5,make,known).
are(5,your_deeds,where_known).
are(5,your_vile_deeds,known).
make(5,you,appearance).
are(5,your_deeds,known).
are(5,your_vile_deeds,where_known).
root(6,ROOT,curse).
advmod(6,curse,away).
nmod:poss(6,friend,my).
amod(6,friend,young).
dep(6,curse,friend).
root(7,ROOT,said).
det(7,wolf,the).
nsubj(7,said,wolf).
