%% jupiter announced that he intended to appoint a king over the birds and named a day on which they were to appear before his throne when he would select the most beautiful of them all to be their ruler.
% dependencies.
root(0,root,announce).
nsubj(0,announce,jupiter).
mark(0,intend,that).
nsubj(0,intend,he).
nsubj:xsubj(0,appoint,he).
nsubj(0,name,he).
ccomp(0,announce,intend).
mark(0,appoint,to).
xcomp(0,intend,appoint).
det(0,king,a).
dobj(0,appoint,king).
case(0,bird,over).
det(0,bird,the).
nmod:over(0,king,bird).
cc(0,intend,and).
ccomp(0,announce,name).
conj:and(0,intend,name).
det(0,day,a).
dobj(0,name,day).
nmod:on(0,be,day).
case(0,which,on).
ref(0,day,which).
nsubj(0,be,they).
nsubj:xsubj(0,appear,they).
acl:relcl(0,day,be).
mark(0,appear,to).
xcomp(0,be,appear).
case(0,throne,before).
nmod:poss(0,throne,he).
nmod:before(0,appear,throne).
advmod(0,select,when).
nsubj(0,select,he).
aux(0,select,would).
advcl(0,appear,select).
det(0,beautiful,the).
advmod(0,beautiful,most).
dobj(0,select,beautiful).
case(0,they,of).
nmod:of(0,beautiful,they).
nsubj(0,ruler,all).
mark(0,ruler,to).
cop(0,ruler,be).
nmod:poss(0,ruler,they).
acl:relcl(0,beautiful,ruler).
% relations.
appear_before(0,they,he_throne).
appoint(0,he,king).
be(0,they,appear_before_he_throne).
appoint(0,he,king_over_bird).
be(0,they,appear).
be(0,all,they_ruler).
%% wishing to look their best on the occasion they repaired to the banks of a stream where they busied themselves in washing and preening their feathers.
% dependencies.
root(1,root,wish).
mark(1,look,to).
xcomp(1,wish,look).
nmod:poss(1,best,they).
dobj(1,look,best).
case(1,occasion,on).
det(1,occasion,the).
nmod:on(1,look,occasion).
nsubj(1,repair,they).
acl:relcl(1,occasion,repair).
case(1,bank,to).
det(1,bank,the).
nmod:to(1,repair,bank).
case(1,stream,of).
det(1,stream,a).
nmod:of(1,bank,stream).
advmod(1,busy,where).
nsubj(1,busy,they).
advcl(1,repair,busy).
dobj(1,busy,themselves).
mark(1,wash,in).
advcl:in(1,busy,wash).
cc(1,wash,and).
advcl:in(1,busy,preen).
conj:and(1,wash,preen).
nmod:poss(1,feather,they).
dobj(1,wash,feather).
% relations.
wash(1,they,they_feather).
repair_to(1,they,bank).
busy(1,they,themselves).
repair_to(1,they,bank_of_stream).
%% the jackdaw was there along with the rest and realized that with his ugly plumage he would have no chance of being chosen as he was so he waited till they were all gone and then picked up the most gaudy of the feathers they had dropped and fastened them about his own body with the result that he looked gayer than any of them.
% dependencies.
root(2,root,rest).
det(2,jackdaw,the).
nsubj(2,rest,jackdaw).
nsubj(2,realize,jackdaw).
cop(2,rest,be).
advmod(2,rest,there).
case(2,there,along).
case(2,rest,with).
det(2,rest,the).
cc(2,rest,and).
conj:and(2,rest,realize).
mark(2,have,that).
case(2,plumage,with).
nmod:poss(2,plumage,he).
amod(2,plumage,ugly).
nmod:with(2,have,plumage).
nsubj(2,have,he).
aux(2,have,would).
ccomp(2,realize,have).
neg(2,chance,no).
dobj(2,have,chance).
mark(2,choose,of).
auxpass(2,choose,be).
acl:of(2,chance,choose).
mark(2,so,as).
nsubj(2,so,he).
cop(2,so,be).
advcl:as(2,choose,so).
nsubj(2,wait,he).
nsubj(2,pick,he).
ccomp(2,so,wait).
mark(2,go,till).
nsubjpass(2,go,they).
auxpass(2,go,be).
advmod(2,go,all).
advcl:till(2,wait,go).
cc(2,wait,and).
advmod(2,pick,then).
ccomp(2,so,pick).
conj:and(2,wait,pick).
compound:prt(2,pick,up).
det(2,gaudy,the).
advmod(2,gaudy,most).
dobj(2,pick,gaudy).
case(2,feather,of).
det(2,feather,the).
nmod:of(2,gaudy,feather).
nsubj(2,drop,they).
nsubj(2,fasten,they).
aux(2,drop,have).
acl:relcl(2,gaudy,drop).
cc(2,drop,and).
acl:relcl(2,gaudy,fasten).
conj:and(2,drop,fasten).
dobj(2,drop,they).
case(2,body,about).
nmod:poss(2,body,he).
amod(2,body,own).
nmod:about(2,drop,body).
case(2,result,with).
det(2,result,the).
nmod:with(2,pick,result).
mark(2,look,that).
nsubj(2,look,he).
ccomp(2,so,look).
dobj(2,look,gayer).
case(2,any,than).
nmod:than(2,look,any).
case(2,they,of).
nmod:of(2,any,they).
% relations.
be_with(2,jackdaw,there_along_rest).
be_with(2,jackdaw,rest).
%% when the appointed day came the birds assembled before jupiter 's throne.
% dependencies.
root(3,root,come).
advmod(3,come,when).
det(3,day,the).
amod(3,day,appoint).
nsubj(3,come,day).
det(3,bird,the).
dobj(3,come,bird).
acl(3,bird,assemble).
case(3,throne,before).
nmod:poss(3,throne,jupiter).
case(3,jupiter,'s).
nmod:before(3,assemble,throne).
% relations.
come(3,day,bird).
come(3,appoint_day,bird_assemble_before_jupiter_'s_throne).
come(3,day,bird_assemble_before_jupiter_'s_throne).
come(3,appoint_day,bird_assemble).
before(3,jupiter,throne).
come(3,appoint_day,bird).
come(3,day,bird_assemble).
%% after passing them in review he was about to make the jackdaw king when all the rest set upon the king-select stripped him of his borrowed plumes and exposed him for the jackdaw that he was.
% dependencies.
root(4,root,pass).
mark(4,pass,after).
dobj(4,pass,they).
case(4,review,in).
nmod:in(4,pass,review).
nsubj(4,about,he).
nsubj:xsubj(4,make,he).
aux(4,about,be).
acl:relcl(4,review,about).
mark(4,make,to).
xcomp(4,about,make).
det(4,king,the).
compound(4,king,jackdaw).
dobj(4,make,king).
advmod(4,strip,when).
det:predet(4,rest,all).
det(4,rest,the).
nsubj(4,strip,rest).
nsubj(4,expose,rest).
acl(4,rest,set).
case(4,king-select,upon).
det(4,king-select,the).
nmod:upon(4,set,king-select).
advcl(4,make,strip).
dobj(4,strip,he).
case(4,plume,of).
nmod:poss(4,plume,he).
amod(4,plume,borrow).
nmod:of(4,strip,plume).
cc(4,strip,and).
advcl(4,make,expose).
conj:and(4,strip,expose).
dobj(4,expose,he).
case(4,jackdaw,for).
det(4,jackdaw,the).
nmod:for(4,expose,jackdaw).
mark(4,be,that).
nsubj(4,be,he).
ccomp(4,expose,be).
% relations.
