root(0,ROOT,journeying).
nummod(0,men,two).
nsubj(0,journeying,men).
aux(0,journeying,were).
advmod(0,journeying,together).
root(1,ROOT,picked).
det:qmod(1,them,one).
mwe(1,one,of).
nsubj(1,picked,them).
compound:prt(1,picked,up).
det(1,axe,an).
dobj(1,picked,axe).
nsubj(1,lay,axe).
nsubj(1,said,axe).
ref(1,axe,that).
acl:relcl(1,axe,lay).
case(1,path,upon).
det(1,path,the).
nmod:upon(1,lay,path).
cc(1,lay,and).
acl:relcl(1,axe,said).
conj:and(1,lay,said).
root(2,ROOT,found).
nsubj(2,found,i).
aux(2,found,have).
det(2,axe,an).
dobj(2,found,axe).
have_found(2,i,axe).
root(3,ROOT,nay).
nmod:poss(3,friend,my).
dobj(3,nay,friend).
root(4,ROOT,replied).
det(4,other,the).
nsubj(4,replied,other).
root(5,ROOT,say).
aux(5,say,do).
neg(5,say,not).
punct(5,say,').
dobj(5,say,i).
punct(5,i,').
case(5,we,but).
punct(5,we,`).
nmod:but(5,i,we).
punct(5,we,').
aux(5,found,have).
acl:relcl(5,we,found).
det(5,axe,an).
dobj(5,found,axe).
root(6,ROOT,gone).
nsubj(6,gone,they).
aux(6,gone,had).
neg(6,gone,not).
advmod(6,gone,far).
mark(6,saw,before).
nsubj(6,saw,they).
advcl:before(6,gone,saw).
det(6,owner,the).
nsubj(6,said,owner).
case(6,axe,of).
det(6,axe,the).
nmod:of(6,owner,axe).
acl(6,axe,pursuing).
dobj(6,pursuing,them).
cc(6,axe,and).
nmod:of(6,owner,he).
conj:and(6,axe,he).
nsubj(6,picked,he).
ref(6,he,who).
aux(6,picked,had).
acl:relcl(6,he,picked).
case(6,axe,up).
det(6,axe,the).
nmod:up(6,picked,axe).
ccomp(6,saw,said).
root(7,ROOT,undone).
nsubjpass(7,undone,we).
auxpass(7,undone,are).
are(7,we,undone).
root(8,ROOT,nay).
root(9,ROOT,replied).
det(9,other,the).
nsubj(9,replied,other).
root(10,ROOT,keep).
case(10,mode,to).
nmod:poss(10,mode,your).
amod(10,mode,first).
nmod:to(10,keep,mode).
case(10,speech,of).
nmod:of(10,mode,speech).
nmod:poss(10,friend,my).
nsubj(10,keep,friend).
keep_to(10,my_friend,your_mode).
keep_to(10,my_friend,your_first_mode).
keep_to(10,my_friend,your_mode_of_speech).
keep_to(10,my_friend,your_first_mode_of_speech).
root(11,ROOT,thought).
dobj(11,thought,what).
nsubj(11,thought,you).
advmod(11,then,right).
advmod(11,thought,then).
dep(11,thought,think).
advmod(11,now,right).
advmod(11,think,now).
root(12,ROOT,say).
punct(12,say,').
dobj(12,say,i).
punct(12,i,').
nsubjpass(12,undone,not).
punct(12,not,`).
dep(12,not,we).
punct(12,not,').
auxpass(12,undone,are).
acl:relcl(12,i,undone).
are(12,not,undone).
