root(0,ROOT,left).
nummod(0,pots,two).
nsubjpass(0,left,pots).
aux(0,left,had).
auxpass(0,left,been).
case(0,bank,on).
det(0,bank,the).
nmod:on(0,left,bank).
case(0,river,of).
det(0,river,a).
nmod:of(0,bank,river).
nummod(0,river,one).
case(0,brass,of).
nmod:of(0,bank,brass).
cc(0,bank,and).
nmod:on(0,left,one).
conj:and(0,bank,one).
case(0,earthenware,of).
acl:of(0,one,earthenware).
had(0,pots,had_left_on_bank).
had(0,pots,had_left_on_bank_of_river_one).
had(0,pots,had_left_on_bank_of_river_one_brass).
had(0,two_pots,had_left_on_bank_of_river_one).
had(0,pots,had_left).
had(0,two_pots,had_left_on_bank).
had(0,pots,had_left_on_bank_of_brass).
had(0,two_pots,had_left_on_bank_of_river_one_of_brass).
had(0,two_pots,had_left_on_bank_brass).
had(0,two_pots,had_left_on_bank_of_brass).
had(0,pots,had_left_on_bank_of_river_one_of_brass).
had(0,pots,had_left_on_bank_brass).
had(0,two_pots,had_left).
had(0,two_pots,had_left_on_bank_of_river_one_brass).
root(1,ROOT,rose).
advmod(1,rose,when).
det(1,tide,the).
nsubj(1,rose,tide).
nsubj(1,floated,they).
dep(1,floated,both).
ccomp(1,rose,floated).
compound:prt(1,floated,off).
case(1,stream,down).
det(1,stream,the).
advmod(1,floated,stream).
root(2,ROOT,pot).
dep(2,pot,now).
det(2,pot,the).
amod(2,pot,earthenware).
acl:relcl(2,pot,tried).
nmod:poss(2,best,its).
dobj(2,tried,best).
mark(2,keep,to).
advcl:to(2,tried,keep).
dobj(2,keep,aloof).
nsubj(2,cried,aloof).
case(2,brass,from).
det(2,brass,the).
nmod:from(2,aloof,brass).
nummod(2,brass,one).
ref(2,aloof,which).
acl:relcl(2,aloof,cried).
compound:prt(2,cried,out).
root(3,ROOT,friend).
compound(3,friend,fear).
compound(3,friend,nothing).
nsubj(3,strike,i).
aux(3,strike,will).
neg(3,strike,not).
acl:relcl(3,friend,strike).
dobj(3,strike,you).
root(4,ROOT,come).
cc(4,come,but).
nsubj(4,come,i).
aux(4,come,may).
case(4,contact,in).
nmod:in(4,come,contact).
case(4,you,with).
nmod:with(4,come,you).
may_come_with(4,i,you).
may_come_in(4,i,contact).
root(5,ROOT,said).
det(5,other,the).
nsubj(5,said,other).
root(6,ROOT,come).
mark(6,come,if).
nsubj(6,come,i).
advmod(6,close,too).
advmod(6,come,close).
root(7,ROOT,hit).
cc(7,hit,and).
mark(7,hit,whether).
nsubj(7,hit,i).
nsubj(7,hit,you).
cc(7,you,or).
conj:or(7,you,you).
nsubj(7,hit,you).
ccomp(7,hit,hit).
dobj(7,hit,me).
nsubj(7,suffer,i).
aux(7,suffer,shall).
dep(7,hit,suffer).
case(7,it,for).
nmod:for(7,suffer,it).
hit(7,you,me).
hit(7,you,me).
