root(0,ROOT,wounded).
det(0,wasp,a).
nsubj(0,wounded,wasp).
dep(0,wasp,seated).
dobj(0,seated,himself).
case(0,head,upon).
det(0,head,the).
nmod:upon(0,seated,head).
case(0,snake,of).
det(0,snake,a).
nmod:of(0,head,snake).
cc(0,seated,and).
dep(0,wasp,striking).
conj:and(0,seated,striking).
dep(0,striking,him).
advmod(0,stings,unceasingly).
case(0,stings,with).
nmod:poss(0,stings,his).
nmod:with(0,striking,stings).
dobj(0,wounded,him).
case(0,death,to).
nmod:to(0,wounded,death).
wounded(0,wasp,him).
root(1,ROOT,saw).
det(1,snake,the).
nsubj(1,saw,snake).
nsubj(1,placed,snake).
cop(1,great,being).
case(1,great,in).
dep(1,snake,great).
ccomp(1,great,torment).
cc(1,great,and).
neg(1,knowing,not).
dep(1,snake,knowing).
conj:and(1,great,knowing).
advmod(1,rid,how).
mark(1,rid,to).
ccomp(1,knowing,rid).
dobj(1,rid,himself).
case(1,enemy,of).
nmod:poss(1,enemy,his).
nmod:of(1,rid,enemy).
det(1,wagon,a).
dobj(1,saw,wagon).
advmod(1,laden,heavily).
amod(1,wagon,laden).
case(1,wood,with).
nmod:with(1,laden,wood).
cc(1,saw,and).
aux(1,saw,went).
cc(1,saw,and).
advmod(1,placed,purposely).
conj:and(1,saw,placed).
nmod:poss(1,head,his).
dobj(1,placed,head).
case(1,wheels,under).
det(1,wheels,the).
nmod:under(1,placed,wheels).
xcomp(1,placed,saying).
heavily_laden_with(1,wagon,wood).
root(2,ROOT,perish).
case(2,least,at).
nummod(2,enemy,least).
nmod:poss(2,enemy,my).
nsubj(2,perish,enemy).
cc(2,enemy,and).
conj:and(2,enemy,i).
nsubj(2,perish,i).
aux(2,perish,shall).
advmod(2,perish,together).
