root(0,ROOT,tramping).
nummod(0,day,one).
amod(0,day,wintry).
nsubj(0,tramping,day).
det(0,woodman,a).
dep(0,day,woodman).
aux(0,tramping,was).
dobj(0,tramping,home).
case(0,work,from).
nmod:poss(0,work,his).
nmod:from(0,tramping,work).
advmod(0,saw,when).
nsubj(0,saw,he).
acl:relcl(0,work,saw).
nsubj(0,lying,something).
dep(0,lying,black).
xcomp(0,saw,lying).
case(0,snow,on).
det(0,snow,the).
nmod:on(0,lying,snow).
saw(0,he,something_lying).
lying_on(0,something,snow).
saw(0,he,something_lying_on_snow).
root(1,ROOT,came).
advmod(1,came,when).
nsubj(1,came,he).
advmod(1,came,closer).
nsubj(1,saw,he).
ccomp(1,came,saw).
nsubj(1,serpent,it).
cop(1,serpent,was).
det(1,serpent,a).
ccomp(1,saw,serpent).
case(1,appearance,to).
det(1,appearance,all).
nmod:to(1,serpent,appearance).
amod(1,appearance,dead).
was_serpent_to(1,it,appearance_dead).
root(2,ROOT,took).
cc(2,took,but).
nsubj(2,took,he).
nsubj(2,put,he).
dobj(2,took,it).
compound:prt(2,took,up).
cc(2,took,and).
conj:and(2,took,put).
dobj(2,put,it).
case(2,bosom,in).
nmod:poss(2,bosom,his).
nmod:in(2,put,bosom).
mark(2,warm,to).
acl:to(2,bosom,warm).
mark(2,hurried,while).
nsubj(2,hurried,he).
advcl:while(2,warm,hurried).
dobj(2,hurried,home).
took_up(2,he,it).
put(2,he,it).
root(3,ROOT,soon).
advmod(3,soon,as).
mark(3,got,as).
nsubj(3,got,he).
dep(3,soon,got).
advmod(3,got,indoors).
nsubj(3,put,he).
ccomp(3,got,put).
det(3,serpent,the).
dobj(3,put,serpent).
compound:prt(3,put,down).
case(3,hearth,on).
det(3,hearth,the).
nmod:on(3,put,hearth).
case(3,fire,before).
det(3,fire,the).
nmod:before(3,hearth,fire).
put_serpent_down_on(3,he,hearth_before_fire).
put_down(3,he,serpent).
put_serpent_down_on(3,he,hearth).
root(4,ROOT,watched).
det(4,children,the).
nsubj(4,watched,children).
nsubj(4,saw,children).
dobj(4,watched,it).
cc(4,watched,and).
conj:and(4,watched,saw).
nsubj(4,come,it).
advmod(4,come,slowly).
ccomp(4,saw,come).
case(4,life,to).
nmod:to(4,come,life).
advmod(4,come,again).
slowly_come_again_to(4,it,life).
slowly_come_to(4,it,life).
come_again_to(4,it,life).
watched(4,children,it).
come_to(4,it,life).
root(5,ROOT,stooped).
advmod(5,one,then).
det:qmod(5,them,one).
mwe(5,one,of).
nsubj(5,stooped,them).
nsubj(5,was,them).
compound:prt(5,stooped,down).
case(5,stroke,to).
nmod:to(5,stooped,stroke).
nsubj(5,raised,it).
nsubj(5,put,it).
case(5,serpent,but).
amod(5,serpent,thc).
nmod:but(5,it,serpent).
acl:relcl(5,stroke,raised).
nmod:poss(5,head,its).
dobj(5,raised,head).
cc(5,raised,and).
acl:relcl(5,stroke,put).
conj:and(5,raised,put).
compound:prt(5,put,out).
nmod:poss(5,fangs,its).
dobj(5,put,fangs).
cc(5,stooped,and).
conj:and(5,stooped,was).
advmod(5,was,about).
mark(5,sting,to).
advcl:to(5,about,sting).
det(5,child,the).
dobj(5,sting,child).
case(5,death,to).
nmod:to(5,sting,death).
put_out(5,it,its_fangs).
raised(5,it,its_head).
root(6,ROOT,seized).
mark(6,seized,so).
det(6,woodman,the).
nsubj(6,seized,woodman).
nmod:poss(6,axe,his).
dobj(6,seized,axe).
cc(6,seized,and).
mark(6,cut,with).
nummod(6,stroke,one).
nsubj(6,cut,stroke).
conj:and(6,seized,cut).
det(6,serpent,the).
dobj(6,cut,serpent).
case(6,two,in).
nmod:in(6,cut,two).
seized(6,woodman,his_axe).
cut(6,one_stroke,serpent).
cut_serpent_in(6,one_stroke,two).
cut_serpent_in(6,stroke,two).
cut(6,stroke,serpent).
root(7,ROOT,ah).
