root(0,ROOT,carrying).
det(0,wolf,a).
nsubj(0,carrying,wolf).
aux(0,stolen,having).
dep(0,wolf,stolen).
det(0,lamb,a).
dobj(0,stolen,lamb).
case(0,fold,from).
det(0,fold,a).
nmod:from(0,stolen,fold).
aux(0,carrying,was).
dobj(0,carrying,him).
dep(0,lair,off).
case(0,lair,to).
nmod:poss(0,lair,his).
advcl:to(0,carrying,lair).
was_carrying(0,wolf,him).
root(1,ROOT,met).
det(1,lion,a).
nsubj(1,met,lion).
dobj(1,met,him).
case(1,path,in).
det(1,path,the).
dep(1,met,path).
cc(1,path,and).
dep(1,met,seizing).
conj:and(1,path,seizing).
det(1,lamb,the).
nsubj(1,took,lamb).
ccomp(1,seizing,took).
dobj(1,took,it).
case(1,him,from).
nmod:from(1,took,him).
met(1,lion,him).
root(2,ROOT,standing).
case(2,distance,at).
det(2,distance,a).
amod(2,distance,safe).
nmod:at(2,standing,distance).
det(2,wolf,the).
nsubj(2,exclaimed,wolf).
acl:relcl(2,distance,exclaimed).
root(3,ROOT,taken).
nsubj(3,taken,you).
aux(3,taken,have).
advmod(3,taken,unrighteously).
mark(3,mine,that).
nsubj(3,mine,which).
cop(3,mine,was).
ccomp(3,taken,mine).
case(3,me,from).
nmod:from(3,mine,me).
root(4,ROOT,replied).
case(4,which,to).
nmod:to(4,replied,which).
det(4,lion,the).
nsubj(4,replied,lion).
advmod(4,replied,jeeringly).
root(5,ROOT,yours).
nsubj(5,yours,it).
cop(5,yours,was).
advmod(5,yours,righteously).
dep(5,yours,eh).
was(5,it,righteously_yours).
was(5,it,yours).
root(6,ROOT,gift).
det(6,gift,the).
case(6,friend,of).
det(6,friend,a).
nmod:of(6,gift,friend).
