root(0,ROOT,neighbors).
det(0,frogs,the).
nummod(0,frogs,two).
nsubj(0,neighbors,frogs).
nummod(0,frogs,two).
dep(0,frogs,frogs).
cop(0,neighbors,were).
were(0,frogs,neighbors).
were(0,two_frogs,neighbors).
root(1,ROOT,inhabited).
nsubj(1,inhabited,one).
det(1,pond,a).
amod(1,pond,deep).
dobj(1,inhabited,pond).
advmod(1,removed,far).
amod(1,pond,removed).
case(1,view,from).
amod(1,view,public).
nmod:from(1,inhabited,view).
inhabited(1,one,pond).
inhabited_pond_from(1,one,view).
inhabited(1,one,pond_far_removed).
inhabited(1,one,pond_removed).
inhabited(1,one,deep_pond_removed).
inhabited_pond_from(1,one,public_view).
inhabited(1,one,deep_pond_far_removed).
inhabited(1,one,deep_pond).
root(2,ROOT,lived).
det(2,other,the).
nsubj(2,lived,other).
nsubj(2,traversed,other).
case(2,gully,in).
det(2,gully,a).
nmod:in(2,lived,gully).
acl(2,gully,containing).
amod(2,water,little).
dobj(2,containing,water).
cc(2,lived,and).
conj:and(2,lived,traversed).
case(2,road,by).
det(2,road,a).
compound(2,road,country).
nmod:by(2,traversed,road).
lived_in(2,other,gully).
traversed_by(2,other,country_road).
root(3,ROOT,warned).
det(3,frog,the).
nsubj(3,lived,frog).
nsubj(3,warned,frog).
nsubj(3,entreated,frog).
ref(3,frog,that).
acl:relcl(3,frog,lived).
case(3,pond,in).
det(3,pond,the).
nmod:in(3,lived,pond).
nmod:poss(3,friend,his).
dobj(3,warned,friend).
mark(3,change,to).
advcl:to(3,warned,change).
nmod:poss(3,residence,his).
dobj(3,change,residence).
cc(3,warned,and).
conj:and(3,warned,entreated).
dobj(3,entreated,him).
nsubj:xsubj(3,come,him).
nsubj:xsubj(3,live,him).
mark(3,come,to).
xcomp(3,entreated,come).
cc(3,come,and).
xcomp(3,entreated,live).
conj:and(3,come,live).
mark(3,saying,with).
nsubj(3,saying,him).
advcl:with(3,live,saying).
mark(3,enjoy,that).
nsubj(3,enjoy,he).
aux(3,enjoy,would).
ccomp(3,saying,enjoy).
amod(3,safety,greater).
dobj(3,enjoy,safety).
case(3,danger,from).
nmod:from(3,enjoy,danger).
cc(3,danger,and).
amod(3,food,more).
amod(3,food,abundant).
nmod:from(3,enjoy,food).
conj:and(3,danger,food).
root(4,ROOT,refused).
det(4,other,the).
nsubj(4,refused,other).
xcomp(4,refused,saying).
mark(4,felt,that).
nsubj(4,felt,he).
ccomp(4,saying,felt).
nsubj(4,leave,it).
advmod(4,hard,so).
advmod(4,hard,very).
dep(4,leave,hard).
mark(4,leave,to).
xcomp(4,felt,leave).
det(4,place,a).
dobj(4,leave,place).
nmod:to(4,become,place).
case(4,which,to).
ref(4,place,which).
nsubj(4,become,he).
aux(4,become,had).
acl:relcl(4,place,become).
xcomp(4,become,accustomed).
refused(4,other,saying).
root(5,ROOT,afterwards).
det(5,days,a).
amod(5,days,few).
nsubj(5,afterwards,days).
det(5,wagon,a).
amod(5,wagon,heavy).
xcomp(5,afterwards,wagon).
dep(5,wagon,passed).
case(5,gully,through).
det(5,gully,the).
nmod:through(5,passed,gully).
cc(5,passed,and).
dep(5,wagon,crushed).
conj:and(5,passed,crushed).
dobj(5,crushed,him).
case(5,death,to).
nmod:to(5,crushed,death).
case(5,wheels,under).
nmod:poss(5,wheels,its).
nmod:under(5,crushed,wheels).
afterwards(5,few_days,wagon).
afterwards(5,days,heavy_wagon).
afterwards(5,days,wagon).
afterwards(5,few_days,heavy_wagon).
