root(0,ROOT,had).
det(0,widow,a).
nsubj(0,fond,widow).
nsubj(0,had,widow).
ref(0,widow,who).
cop(0,fond,was).
acl:relcl(0,widow,fond).
case(0,cleaning,of).
nmod:of(0,fond,cleaning).
nummod(0,maidens,two).
amod(0,maidens,little).
dobj(0,had,maidens).
mark(0,wait,to).
advcl:to(0,had,wait).
case(0,her,on).
nmod:on(0,wait,her).
root(1,ROOT,habit).
nsubj(1,habit,she).
cop(1,habit,was).
case(1,habit,in).
det(1,habit,the).
mark(1,waking,of).
acl:of(1,habit,waking).
dobj(1,waking,them).
advmod(1,waking,early).
case(1,morning,in).
det(1,morning,the).
nmod:in(1,early,morning).
case(1,cockcrow,at).
nmod:at(1,waking,cockcrow).
root(2,ROOT,aggravated).
det(2,maidens,the).
nsubj(2,aggravated,maidens).
case(2,labor,by).
amod(2,labor,such).
amod(2,labor,excessive).
nmod:by(2,aggravated,labor).
acl(2,labor,resolved).
mark(2,kill,to).
xcomp(2,resolved,kill).
det(2,cock,the).
dobj(2,kill,cock).
nsubj(2,roused,cock).
ref(2,cock,who).
acl:relcl(2,cock,roused).
nmod:poss(2,mistress,their).
dobj(2,roused,mistress).
advmod(2,early,so).
advmod(2,roused,early).
aggravated_by(2,maidens,labor_resolved).
aggravated_by(2,maidens,excessive_labor_resolved).
aggravated_by(2,maidens,excessive_labor).
aggravated_by(2,maidens,such_labor_resolved).
aggravated_by(2,maidens,such_labor).
aggravated_by(2,maidens,such_excessive_labor).
aggravated_by(2,maidens,labor).
aggravated_by(2,maidens,such_excessive_labor_resolved).
root(3,ROOT,done).
advmod(3,done,when).
nsubj(3,done,they).
aux(3,done,had).
dobj(3,done,this).
mark(3,prepared,this).
nsubj(3,found,they).
acl:relcl(3,this,found).
ref(3,this,that).
nsubj(3,prepared,they).
aux(3,prepared,had).
advmod(3,prepared,only).
ccomp(3,found,prepared).
case(3,themselves,for).
nmod:for(3,prepared,themselves).
amod(3,troubles,greater).
dep(3,woke,troubles).
mark(3,woke,for).
nmod:poss(3,mistress,their).
nsubj(3,woke,mistress).
neg(3,longer,no).
advmod(3,hearing,longer).
acl(3,mistress,hearing).
det(3,hour,the).
dobj(3,hearing,hour).
case(3,cock,from).
det(3,cock,the).
nmod:from(3,hearing,cock).
advcl:for(3,prepared,woke).
dobj(3,woke,them).
compound:prt(3,woke,up).
case(3,work,to).
nmod:poss(3,work,their).
nmod:to(3,woke,work).
case(3,middle,in).
det(3,middle,the).
nmod:in(3,work,middle).
case(3,night,of).
det(3,night,the).
nmod:of(3,middle,night).
