root(0,ROOT,disputing).
det(0,wind,the).
nsubj(0,disputing,wind).
cc(0,wind,and).
det(0,sun,the).
conj:and(0,wind,sun).
nsubj(0,disputing,sun).
aux(0,disputing,were).
nsubj(0,stronger,which).
cop(0,stronger,was).
det(0,stronger,the).
ccomp(0,disputing,stronger).
root(1,ROOT,saw).
advmod(1,saw,suddenly).
nsubj(1,saw,they).
det(1,traveller,a).
dobj(1,saw,traveller).
acl(1,traveller,coming).
compound:prt(1,coming,down).
det(1,road,the).
dobj(1,coming,road).
cc(1,saw,and).
det(1,sun,the).
nsubj(1,said,sun).
conj:and(1,saw,said).
saw(1,they,traveller).
suddenly_saw(1,they,traveller).
root(2,ROOT,see).
advmod(2,see,i).
det(2,way,a).
dobj(2,see,way).
mark(2,decide,to).
acl:to(2,way,decide).
nmod:poss(2,dispute,our).
dobj(2,decide,dispute).
root(3,ROOT,whichever).
mark(3,cause,of).
nsubj(3,cause,us).
aux(3,cause,can).
dep(3,whichever,cause).
mark(3,regarded,that).
nsubjpass(3,regarded,traveller).
mark(3,take,to).
acl:to(3,traveller,take).
compound:prt(3,take,off).
nmod:poss(3,cloak,his).
dobj(3,take,cloak).
aux(3,regarded,shall).
auxpass(3,regarded,be).
ccomp(3,cause,regarded).
case(3,stronger,as).
det(3,stronger,the).
nmod:as(3,regarded,stronger).
root(4,ROOT,begin).
nsubj(4,begin,you).
root(5,ROOT,retired).
mark(5,retired,so).
det(5,sun,the).
nsubj(5,retired,sun).
case(5,cloud,behind).
det(5,cloud,a).
nmod:behind(5,retired,cloud).
cc(5,retired,and).
det(5,wind,the).
nsubj(5,began,wind).
nsubj:xsubj(5,blow,wind).
conj:and(5,retired,began).
mark(5,blow,to).
xcomp(5,began,blow).
advmod(5,hard,as).
advmod(5,blow,hard).
mark(5,could,as).
nsubj(5,could,it).
advcl:as(5,hard,could).
case(5,traveller,upon).
det(5,traveller,the).
nmod:upon(5,blow,traveller).
began(5,wind,blow_upon_traveller).
began(5,wind,blow).
began(5,wind,blow_as_hard_upon_traveller).
blow_as_hard_upon(5,wind,traveller).
retired_behind(5,sun,cloud).
began(5,wind,blow_as_hard).
blow_upon(5,wind,traveller).
began(5,wind,blow_hard).
blow_hard_upon(5,wind,traveller).
began(5,wind,blow_hard_upon_traveller).
root(6,ROOT,blew).
cc(6,blew,but).
det(6,harder,the).
dep(6,blew,harder).
nsubj(6,blew,he).
det(6,more,the).
dep(6,closely,more).
dep(6,blew,closely).
ccomp(6,closely,did).
det(6,traveller,the).
nsubj(6,wrap,traveller).
ccomp(6,did,wrap).
nmod:poss(6,round,his).
compound(6,round,cloak).
nsubj(6,him,round).
xcomp(6,wrap,him).
mark(6,had,till).
case(6,last,at).
nmod:at(6,had,last).
det(6,wind,the).
nsubj(6,had,wind).
nsubj:xsubj(6,give,wind).
advcl:till(6,wrap,had).
mark(6,give,to).
xcomp(6,had,give).
compound:prt(6,give,up).
case(6,despair,in).
nmod:in(6,give,despair).
root(7,ROOT,sun).
dep(7,sun,then).
det(7,sun,the).
ccomp(7,sun,came).
compound:prt(7,came,out).
cc(7,sun,and).
dep(7,sun,shone).
case(7,glory,in).
det:predet(7,glory,all).
nmod:poss(7,glory,his).
nmod:in(7,shone,glory).
case(7,traveller,upon).
det(7,traveller,the).
nmod:upon(7,shone,traveller).
nsubj(7,found,traveller).
ref(7,traveller,who).
advmod(7,found,soon).
acl:relcl(7,traveller,found).
nsubj(7,walk,it).
advmod(7,hot,too).
dep(7,walk,hot).
mark(7,walk,to).
xcomp(7,found,walk).
case(7,cloak,with).
nmod:poss(7,cloak,his).
nmod:on(7,walk,cloak).
case(7,cloak,on).
is_in(7,shone,his_glory).
