root(0,ROOT,announced).
nsubj(0,announced,jupiter).
mark(0,intended,that).
nsubj(0,intended,he).
nsubj:xsubj(0,appoint,he).
nsubj(0,named,he).
ccomp(0,announced,intended).
mark(0,appoint,to).
xcomp(0,intended,appoint).
det(0,king,a).
dobj(0,appoint,king).
case(0,birds,over).
det(0,birds,the).
nmod:over(0,king,birds).
cc(0,intended,and).
ccomp(0,announced,named).
conj:and(0,intended,named).
det(0,day,a).
dobj(0,named,day).
nmod:on(0,were,day).
case(0,which,on).
ref(0,day,which).
nsubj(0,were,they).
nsubj:xsubj(0,appear,they).
acl:relcl(0,day,were).
mark(0,appear,to).
xcomp(0,were,appear).
case(0,throne,before).
nmod:poss(0,throne,his).
nmod:before(0,appear,throne).
advmod(0,select,when).
nsubj(0,select,he).
aux(0,select,would).
advcl(0,appear,select).
det(0,beautiful,the).
advmod(0,beautiful,most).
dobj(0,select,beautiful).
case(0,them,of).
nmod:of(0,beautiful,them).
nsubj(0,ruler,all).
mark(0,ruler,to).
cop(0,ruler,be).
nmod:poss(0,ruler,their).
acl:relcl(0,beautiful,ruler).
appear_before(0,they,his_throne).
appoint(0,he,king).
were(0,they,appear_before_his_throne).
appoint(0,he,king_over_birds).
were(0,they,appear).
be(0,all,their_ruler).
root(1,ROOT,wishing).
mark(1,look,to).
xcomp(1,wishing,look).
nmod:poss(1,best,their).
dobj(1,look,best).
case(1,occasion,on).
det(1,occasion,the).
nmod:on(1,look,occasion).
nsubj(1,repaired,they).
acl:relcl(1,occasion,repaired).
case(1,banks,to).
det(1,banks,the).
nmod:to(1,repaired,banks).
case(1,stream,of).
det(1,stream,a).
nmod:of(1,banks,stream).
advmod(1,busied,where).
nsubj(1,busied,they).
advcl(1,repaired,busied).
dobj(1,busied,themselves).
mark(1,washing,in).
advcl:in(1,busied,washing).
cc(1,washing,and).
advcl:in(1,busied,preening).
conj:and(1,washing,preening).
nmod:poss(1,feathers,their).
dobj(1,washing,feathers).
washing(1,they,their_feathers).
repaired_to(1,they,banks).
busied(1,they,themselves).
repaired_to(1,they,banks_of_stream).
root(2,ROOT,rest).
det(2,jackdaw,the).
nsubj(2,rest,jackdaw).
nsubj(2,realized,jackdaw).
cop(2,rest,was).
advmod(2,rest,there).
case(2,there,along).
case(2,rest,with).
det(2,rest,the).
cc(2,rest,and).
conj:and(2,rest,realized).
mark(2,have,that).
case(2,plumage,with).
nmod:poss(2,plumage,his).
amod(2,plumage,ugly).
nmod:with(2,have,plumage).
nsubj(2,have,he).
aux(2,have,would).
ccomp(2,realized,have).
neg(2,chance,no).
dobj(2,have,chance).
mark(2,chosen,of).
auxpass(2,chosen,being).
acl:of(2,chance,chosen).
mark(2,so,as).
nsubj(2,so,he).
cop(2,so,was).
advcl:as(2,chosen,so).
nsubj(2,waited,he).
nsubj(2,picked,he).
ccomp(2,so,waited).
mark(2,gone,till).
nsubjpass(2,gone,they).
auxpass(2,gone,were).
advmod(2,gone,all).
advcl:till(2,waited,gone).
cc(2,waited,and).
advmod(2,picked,then).
ccomp(2,so,picked).
conj:and(2,waited,picked).
compound:prt(2,picked,up).
det(2,gaudy,the).
advmod(2,gaudy,most).
dobj(2,picked,gaudy).
case(2,feathers,of).
det(2,feathers,the).
nmod:of(2,gaudy,feathers).
nsubj(2,dropped,they).
nsubj(2,fastened,they).
aux(2,dropped,had).
acl:relcl(2,gaudy,dropped).
cc(2,dropped,and).
acl:relcl(2,gaudy,fastened).
conj:and(2,dropped,fastened).
dobj(2,dropped,them).
case(2,body,about).
nmod:poss(2,body,his).
amod(2,body,own).
nmod:about(2,dropped,body).
case(2,result,with).
det(2,result,the).
nmod:with(2,picked,result).
mark(2,looked,that).
nsubj(2,looked,he).
ccomp(2,so,looked).
dobj(2,looked,gayer).
case(2,any,than).
nmod:than(2,looked,any).
case(2,them,of).
nmod:of(2,any,them).
was_with(2,jackdaw,there_along_rest).
was_with(2,jackdaw,rest).
root(3,ROOT,came).
advmod(3,came,when).
det(3,day,the).
amod(3,day,appointed).
nsubj(3,came,day).
det(3,birds,the).
dobj(3,came,birds).
acl(3,birds,assembled).
case(3,throne,before).
nmod:poss(3,throne,jupiter).
case(3,jupiter,'s).
nmod:before(3,assembled,throne).
came(3,day,birds).
came(3,appointed_day,birds_assembled_before_jupiter_s_throne).
came(3,day,birds_assembled_before_jupiter_s_throne).
came(3,appointed_day,birds_assembled).
before(3,jupiter,throne).
came(3,appointed_day,birds).
came(3,day,birds_assembled).
root(4,ROOT,passing).
mark(4,passing,after).
dobj(4,passing,them).
case(4,review,in).
nmod:in(4,passing,review).
nsubj(4,about,he).
nsubj:xsubj(4,make,he).
aux(4,about,was).
acl:relcl(4,review,about).
mark(4,make,to).
xcomp(4,about,make).
det(4,king,the).
compound(4,king,jackdaw).
dobj(4,make,king).
advmod(4,stripped,when).
det:predet(4,rest,all).
det(4,rest,the).
nsubj(4,stripped,rest).
nsubj(4,exposed,rest).
acl(4,rest,set).
case(4,king-select,upon).
det(4,king-select,the).
nmod:upon(4,set,king-select).
advcl(4,make,stripped).
dobj(4,stripped,him).
case(4,plumes,of).
nmod:poss(4,plumes,his).
amod(4,plumes,borrowed).
nmod:of(4,stripped,plumes).
cc(4,stripped,and).
advcl(4,make,exposed).
conj:and(4,stripped,exposed).
dobj(4,exposed,him).
case(4,jackdaw,for).
det(4,jackdaw,the).
nmod:for(4,exposed,jackdaw).
mark(4,was,that).
nsubj(4,was,he).
ccomp(4,exposed,was).
