root(0,ROOT,set).
nummod(0,soldiers,two).
nsubjpass(0,set,soldiers).
acl(0,soldiers,traveling).
advmod(0,traveling,together).
auxpass(0,set,were).
case(0,robber,upon).
case(0,robber,by).
det(0,robber,a).
nmod:agent(0,set,robber).
root(1,ROOT,fled).
det(1,one,the).
nsubj(1,fled,one).
advmod(1,fled,away).
root(2,ROOT,stood).
det(2,other,the).
nsubj(2,stood,other).
nsubj(2,defended,other).
nmod:poss(2,ground,his).
dobj(2,stood,ground).
cc(2,stood,and).
conj:and(2,stood,defended).
dobj(2,defended,himself).
case(2,hand,with).
nmod:poss(2,hand,his).
compound(2,hand,stout).
amod(2,hand,right).
nmod:with(2,defended,hand).
defended(2,other,himself).
stood(2,other,his_ground).
root(3,ROOT,said).
det(3,robber,the).
nsubj(3,said,robber).
auxpass(3,slain,being).
dep(3,robber,slain).
det(3,companion,the).
amod(3,companion,timid).
nsubj(3,ran,companion).
nsubj(3,drew,companion).
ccomp(3,slain,ran).
advmod(3,ran,up).
cc(3,ran,and).
ccomp(3,slain,drew).
conj:and(3,ran,drew).
nmod:poss(3,sword,his).
dobj(3,drew,sword).
cc(3,slain,and).
advmod(3,throwing,then).
dep(3,robber,throwing).
conj:and(3,slain,throwing).
compound:prt(3,throwing,back).
nmod:poss(3,cloak,his).
amod(3,cloak,traveling).
dobj(3,throwing,cloak).
drew(3,companion,his_sword).
drew(3,timid_companion,his_sword).
root(4,ROOT,'ll).
nsubj(4,'ll,i).
case(4,him,at).
nmod:at(4,'ll,him).
cc(4,'ll,and).
nsubj(4,take,i).
aux(4,take,'ll).
conj:and(4,'ll,take).
dobj(4,take,care).
dobj(4,attacked,care).
nsubj(4,learn,he).
aux(4,learn,shall).
acl:relcl(4,care,learn).
ref(4,care,whom).
nsubj(4,attacked,he).
aux(4,attacked,has).
ccomp(4,learn,attacked).
ll_at(4,i,him).
root(5,ROOT,he).
case(5,he,on).
det(5,he,this).
nsubj(5,fought,he).
ref(5,he,who).
aux(5,fought,had).
acl:relcl(5,he,fought).
case(5,robber,with).
det(5,robber,the).
nmod:with(5,fought,robber).
acl(5,robber,made).
dobj(5,made,answer).
root(6,ROOT,wish).
dep(6,only,i).
nsubj(6,wish,only).
mark(6,helped,that).
nsubj(6,helped,you).
aux(6,helped,had).
ccomp(6,wish,helped).
dobj(6,helped,me).
advmod(6,words,just).
advmod(6,words,now).
advmod(6,words,even).
mark(6,words,if).
nsubj(6,words,it).
aux(6,words,had).
cop(6,words,been).
advmod(6,words,only).
case(6,words,with).
det(6,words,those).
advcl:if(6,helped,words).
mark(6,encouraged,for).
nsubj(6,encouraged,i).
aux(6,encouraged,should).
aux(6,encouraged,have).
cop(6,encouraged,been).
det(6,encouraged,the).
advmod(6,encouraged,more).
dep(6,words,encouraged).
acl(6,encouraged,believing).
dobj(6,believing,them).
nsubj:xsubj(6,true,them).
mark(6,true,to).
cop(6,true,be).
xcomp(6,believing,true).
believing(6,i,true).
should(6,i,should_have_encouraged_believing).
had_with(6,it,now_even_had_only_words).
should(6,i,should_have_more_encouraged_believing).
believing(6,i,them).
had_with(6,it,just_had_words).
had_with(6,it,just_even_had_words).
had_with(6,it,just_now_had_words).
had_with(6,it,even_had_words).
had_with(6,it,now_even_had_words).
helped(6,you,me).
had_with(6,it,just_had_only_words).
had_with(6,it,now_had_words).
should(6,i,should_have_more_encouraged).
had_with(6,it,even_had_only_words).
had_with(6,it,just_now_had_only_words).
had_with(6,it,just_even_had_only_words).
had_with(6,it,had_only_words).
believing(6,should_have_encouraged,them).
had_with(6,it,just_now_even_had_only_words).
had_with(6,it,now_had_only_words).
had_with(6,it,had_words).
had_with(6,it,just_now_even_had_words).
should(6,i,should_have_encouraged).
root(7,ROOT,put).
cc(7,put,but).
nsubj(7,put,now).
nsubj(7,hold,now).
compound:prt(7,put,up).
nmod:poss(7,sword,your).
dobj(7,put,sword).
case(7,sheath,in).
nmod:poss(7,sheath,its).
nmod:in(7,sword,sheath).
cc(7,put,and).
conj:and(7,put,hold).
nmod:poss(7,tongue,your).
advmod(7,useless,equally).
amod(7,tongue,useless).
dobj(7,hold,tongue).
mark(7,deceive,till).
nsubj(7,deceive,you).
aux(7,deceive,can).
advcl:till(7,hold,deceive).
dobj(7,deceive,others).
nsubj(7,know,others).
ref(7,others,who).
aux(7,know,do).
neg(7,know,not).
acl:relcl(7,others,know).
dobj(7,know,you).
is_in(7,your_sword,its_sheath).
put_up(7,now,your_sword_in_its_sheath).
hold(7,now,your_tongue).
put_up(7,now,your_sword).
hold(7,now,your_equally_useless_tongue).
hold(7,now,your_useless_tongue).
root(8,ROOT,indeed).
dep(8,indeed,i).
nsubj(8,experienced,who).
aux(8,experienced,have).
dep(8,indeed,experienced).
mark(8,run,with).
det(8,speed,what).
dobj(8,run,speed).
nsubj(8,run,you).
advcl:with(8,experienced,run).
advmod(8,run,away).
dep(8,run,know).
advmod(8,well,right).
advmod(8,know,well).
mark(8,placed,that).
neg(8,dependence,no).
nsubjpass(8,placed,dependence).
aux(8,placed,can).
auxpass(8,placed,be).
advcl:that(8,well,placed).
case(8,valor,on).
nmod:poss(8,valor,your).
nmod:on(8,placed,valor).
