root(0,ROOT,followed).
det(0,wolf,a).
nsubj(0,followed,wolf).
nsubj(0,attempt,wolf).
nsubj:xsubj(0,injure,wolf).
det(0,flock,a).
dobj(0,followed,flock).
case(0,sheep,of).
nmod:of(0,flock,sheep).
case(0,time,for).
det(0,time,a).
amod(0,time,long).
nmod:for(0,followed,time).
cc(0,followed,and).
aux(0,attempt,did).
neg(0,attempt,not).
conj:and(0,followed,attempt).
mark(0,injure,to).
xcomp(0,attempt,injure).
det:qmod(0,them,one).
mwe(0,one,of).
dobj(0,injure,them).
root(1,ROOT,stood).
det(1,shepherd,the).
nsubj(1,stood,shepherd).
nsubj(1,kept,shepherd).
case(1,first,at).
nmod:at(1,shepherd,first).
case(1,guard,on).
nmod:poss(1,guard,his).
nmod:on(1,stood,guard).
case(1,him,against).
nmod:against(1,guard,him).
case(1,enemy,as).
case(1,enemy,against).
det(1,enemy,an).
nmod:against(1,stood,enemy).
cc(1,stood,and).
conj:and(1,stood,kept).
det(1,watch,a).
amod(1,watch,strict).
dobj(1,kept,watch).
case(1,movements,over).
nmod:poss(1,movements,his).
nmod:over(1,kept,movements).
stood_on(1,shepherd,his_guard).
stood_as(1,shepherd,as_enemy).
kept(1,shepherd,strict_watch).
kept(1,shepherd,watch).
stood_on(1,shepherd,his_guard_against_him).
kept_watch_over(1,shepherd,his_movements).
root(2,ROOT,kept).
cc(2,kept,but).
advmod(2,kept,when).
det(2,day,the).
compound(2,day,wolf).
nsubj(2,kept,day).
nsubj(2,make,day).
case(2,day,after).
nmod:after(2,day,day).
case(2,company,in).
det(2,company,the).
nmod:in(2,kept,company).
case(2,sheep,of).
det(2,sheep,the).
nmod:of(2,company,sheep).
cc(2,kept,and).
aux(2,make,did).
neg(2,make,not).
conj:and(2,kept,make).
det(2,effort,the).
amod(2,effort,slightest).
dobj(2,make,effort).
mark(2,seize,to).
advcl:to(2,make,seize).
dobj(2,seize,them).
det(2,shepherd,the).
nsubj(2,began,shepherd).
nsubj:xsubj(2,look,shepherd).
nsubj:xsubj(2,look,shepherd).
dep(2,seize,began).
mark(2,look,to).
xcomp(2,began,look).
xcomp(2,began,look).
conj:negcc(2,look,look).
case(2,him,upon).
nmod:upon(2,look,him).
case(2,guardian,as).
det(2,guardian,a).
nmod:as(2,look,guardian).
case(2,flock,of).
nmod:poss(2,flock,his).
nmod:of(2,guardian,flock).
cc(2,look,rather).
mwe(2,rather,than).
case(2,plotter,as).
det(2,plotter,a).
nmod:as(2,look,plotter).
case(2,evil,of).
nmod:of(2,plotter,evil).
case(2,it,against).
nmod:against(2,evil,it).
root(3,ROOT,called).
cc(3,called,and).
advmod(3,called,when).
nsubj(3,called,occasion).
dobj(3,called,him).
nummod(3,day,one).
nmod:tmod(3,called,day).
case(3,city,into).
det(3,city,the).
nmod:into(3,called,city).
nsubj(3,left,he).
acl:relcl(3,city,left).
det(3,sheep,the).
dobj(3,left,sheep).
advmod(3,left,entirely).
case(3,charge,in).
nmod:poss(3,charge,his).
nmod:in(3,left,charge).
left_entirely(3,he,sheep).
left(3,he,sheep).
left_sheep_entirely_in(3,he,his_charge).
left_sheep_in(3,he,his_charge).
called_at_time(3,occasion,one_day).
called(3,occasion,him).
root(4,ROOT,now).
det(4,wolf,the).
nmod:npmod(4,now,wolf).
mark(4,had,that).
nsubj(4,had,he).
dep(4,now,had).
det(4,opportunity,the).
dobj(4,had,opportunity).
acl:relcl(4,opportunity,fell).
case(4,sheep,upon).
det(4,sheep,the).
nmod:upon(4,fell,sheep).
cc(4,fell,and).
acl:relcl(4,opportunity,destroyed).
conj:and(4,fell,destroyed).
det(4,part,the).
amod(4,part,greater).
dobj(4,destroyed,part).
case(4,flock,of).
det(4,flock,the).
nmod:of(4,part,flock).
root(5,ROOT,returned).
advmod(5,returned,when).
det(5,shepherd,the).
nsubj(5,returned,shepherd).
nsubj:xsubj(5,find,shepherd).
mark(5,find,to).
xcomp(5,returned,find).
nmod:poss(5,flock,his).
nsubj(5,destroyed,flock).
ccomp(5,find,destroyed).
nsubj(5,exclaimed,he).
ccomp(5,destroyed,exclaimed).
returned(5,shepherd,find).
root(6,ROOT,served).
nsubjpass(6,served,i).
aux(6,served,have).
auxpass(6,served,been).
advmod(6,served,rightly).
have(6,i,have_rightly_served).
have(6,i,have_served).
root(7,ROOT,did).
advmod(7,did,why).
iobj(7,did,i).
compound(7,sheep,trust).
nmod:poss(7,sheep,my).
dobj(7,did,sheep).
case(7,wolf,to).
det(7,wolf,a).
nmod:to(7,sheep,wolf).
