root(0,ROOT,wolf).
dep(0,wolf,once).
case(0,time,upon).
det(0,time,a).
nmod:upon(0,once,time).
det(0,wolf,a).
acl(0,wolf,resolved).
mark(0,disguise,to).
xcomp(0,resolved,disguise).
nmod:poss(0,appearance,his).
dobj(0,disguise,appearance).
mark(0,secure,in).
mwe(0,in,order).
mark(0,secure,to).
advcl:in_order(0,disguise,secure).
dobj(0,secure,food).
advmod(0,easily,more).
advmod(0,secure,easily).
root(1,ROOT,encased).
case(1,skin,in).
det(1,skin,the).
nmod:in(1,encased,skin).
case(1,sheep,of).
det(1,sheep,a).
nmod:of(1,skin,sheep).
nsubj(1,pastured,he).
acl:relcl(1,sheep,pastured).
case(1,flock,with).
det(1,flock,the).
nmod:with(1,pastured,flock).
xcomp(1,pastured,deceiving).
det(1,shepherd,the).
dobj(1,deceiving,shepherd).
case(1,costume,by).
nmod:poss(1,costume,his).
nmod:by(1,deceiving,costume).
pastured_with(1,he,flock).
deceiving(1,he,shepherd).
deceiving_shepherd_by(1,he,his_costume).
root(2,ROOT,shut).
case(2,evening,in).
det(2,evening,the).
nmod:in(2,shut,evening).
nsubjpass(2,shut,he).
auxpass(2,shut,was).
compound:prt(2,shut,up).
case(2,shepherd,by).
det(2,shepherd,the).
nmod:agent(2,shut,shepherd).
case(2,fold,in).
det(2,fold,the).
nmod:in(2,shepherd,fold).
was_shut_up_by(2,he,shepherd_in_fold).
was_shut_up_in(2,he,evening).
was_shut_up_by(2,he,shepherd).
is_in(2,shepherd,fold).
root(3,ROOT,closed).
det(3,gate,the).
nsubjpass(3,closed,gate).
auxpass(3,closed,was).
cc(3,closed,and).
det(3,entrance,the).
nsubj(3,made,entrance).
conj:and(3,closed,made).
advmod(3,secure,thoroughly).
xcomp(3,made,secure).
was(3,gate,closed).
made(3,entrance,thoroughly_secure).
made(3,entrance,secure).
root(4,ROOT,shepherd).
cc(4,shepherd,but).
det(4,shepherd,the).
csubj(4,caught,returning).
csubj(4,killed,returning).
case(4,fold,to).
det(4,fold,the).
nmod:to(4,returning,fold).
case(4,night,during).
det(4,night,the).
nmod:during(4,returning,night).
mark(4,obtain,to).
acl:to(4,night,obtain).
dobj(4,obtain,meat).
case(4,day,for).
det(4,day,the).
amod(4,day,next).
nmod:for(4,obtain,day).
advmod(4,caught,mistakenly).
acl:relcl(4,shepherd,caught).
compound:prt(4,caught,up).
det(4,wolf,the).
dobj(4,caught,wolf).
case(4,sheep,instead).
mwe(4,instead,of).
det(4,sheep,a).
nmod:instead_of(4,wolf,sheep).
cc(4,caught,and).
acl:relcl(4,shepherd,killed).
conj:and(4,caught,killed).
dobj(4,killed,him).
advmod(4,killed,instantly).
mistakenly_caught_up(4,returning,wolf).
returning_to(4,wolf,fold).
killed(4,returning,him).
caught_up(4,returning,wolf).
killed_instantly(4,returning,him).
