root(0,ROOT,travelling).
nummod(0,fellows,two).
nsubj(0,travelling,fellows).
aux(0,travelling,were).
advmod(0,travelling,together).
case(0,wood,through).
det(0,wood,a).
nmod:through(0,travelling,wood).
advmod(0,rushed,when).
det(0,bear,a).
nsubj(0,rushed,bear).
acl:relcl(0,wood,rushed).
compound:prt(0,rushed,out).
case(0,them,upon).
nmod:upon(0,rushed,them).
rushed_out_upon(0,bear,them).
root(1,ROOT,happened).
det:qmod(1,travellers,one).
nsubj:xsubj(1,front,one).
mwe(1,one,of).
det(1,travellers,the).
nsubj(1,happened,travellers).
nsubj:xsubj(1,front,travellers).
mark(1,front,to).
cop(1,front,be).
case(1,front,in).
xcomp(1,happened,front).
cc(1,happened,and).
nsubj(1,seized,he).
nsubj(1,hid,he).
conj:and(1,happened,seized).
dobj(1,seized,hold).
case(1,branch,of).
det(1,branch,the).
nmod:of(1,hold,branch).
case(1,tree,of).
det(1,tree,a).
nmod:of(1,branch,tree).
cc(1,seized,and).
conj:and(1,happened,hid).
conj:and(1,seized,hid).
dobj(1,hid,himself).
case(1,leaves,among).
det(1,leaves,the).
nmod:among(1,hid,leaves).
seized(1,he,hold_of_branch_of_tree).
hold_of(1,he,branch_of_tree).
hid(1,he,himself).
hold_of(1,he,branch).
seized(1,he,hold).
seized(1,he,hold_of_branch).
root(2,ROOT,threw).
det(2,other,the).
nsubj(2,threw,other).
acl(2,other,seeing).
neg(2,help,no).
dobj(2,seeing,help).
case(2,it,for).
nmod:for(2,help,it).
nsubj(2,flat,himself).
xcomp(2,threw,flat).
advmod(2,flat,down).
case(2,ground,upon).
det(2,ground,the).
nmod:upon(2,flat,ground).
case(2,face,with).
nmod:poss(2,face,his).
nmod:with(2,ground,face).
case(2,dust,in).
det(2,dust,the).
nmod:in(2,flat,dust).
threw(2,other,himself_flat_down_upon_ground_with_face_in_dust).
threw(2,other,himself_flat_down_upon_ground_with_his_face_in_dust).
root(3,ROOT,put).
det(3,bear,the).
nsubj(3,put,bear).
nsubj(3,sniffed,bear).
acl(3,bear,coming).
compound:prt(3,coming,up).
case(3,him,to).
nmod:to(3,coming,him).
nmod:poss(3,close,his).
compound(3,close,muzzle).
dobj(3,put,close).
case(3,ear,to).
nmod:poss(3,ear,his).
nmod:to(3,put,ear).
cc(3,put,and).
conj:and(3,put,sniffed).
cc(3,sniffed,and).
conj:and(3,put,sniffed).
conj:and(3,sniffed,sniffed).
put(3,bear,his_muzzle_close).
root(4,ROOT,but).
case(4,last,at).
nmod:at(4,but,last).
case(4,growl,with).
det(4,growl,a).
nmod:with(4,last,growl).
nsubj(4,shook,he).
nsubj(4,slouched,he).
acl:relcl(4,growl,shook).
nmod:poss(4,head,his).
dobj(4,shook,head).
cc(4,shook,and).
acl:relcl(4,growl,slouched).
conj:and(4,shook,slouched).
compound:prt(4,slouched,off).
case(4,bears,for).
nmod:for(4,slouched,bears).
aux(4,touch,will).
neg(4,touch,not).
acl:relcl(4,growl,touch).
amod(4,meat,dead).
dobj(4,touch,meat).
shook(4,he,his_head).
slouched_off_for(4,he,bears).
root(5,ROOT,came).
advmod(5,fellow,then).
det(5,fellow,the).
nsubj(5,came,fellow).
case(5,tree,in).
det(5,tree,the).
nmod:in(5,fellow,tree).
advmod(5,came,down).
case(5,comrade,to).
nmod:poss(5,comrade,his).
nmod:to(5,down,comrade).
cc(5,comrade,and).
nmod:to(5,down,laughing).
conj:and(5,comrade,laughing).
acl(5,comrade,said).
is_in(5,fellow,tree).
root(6,ROOT,what).
cop(6,what,was).
nsubj(6,what,it).
mark(6,whispered,that).
compound(6,bruin,master).
nsubj(6,whispered,bruin).
dep(6,what,whispered).
case(6,you,to).
nmod:to(6,whispered,you).
root(7,ROOT,told).
nsubj(7,told,he).
dobj(7,told,me).
told(7,he,me).
