root(0,ROOT,caught).
det(0,man,a).
amod(0,man,young).
nsubjpass(0,caught,man).
nsubjpass(0,condemned,man).
nsubjpass:xsubj(0,executed,man).
aux(0,caught,had).
auxpass(0,caught,been).
case(0,act,in).
det(0,act,a).
amod(0,act,daring).
nmod:in(0,caught,act).
case(0,theft,of).
nmod:of(0,act,theft).
cc(0,caught,and).
aux(0,condemned,had).
auxpass(0,condemned,been).
conj:and(0,caught,condemned).
mark(0,executed,to).
auxpass(0,executed,be).
xcomp(0,condemned,executed).
case(0,it,for).
nmod:for(0,executed,it).
had(0,man,had_caught).
had(0,man,had_caught_in_daring_act_of_theft).
been(0,young_man,condemned).
been_condemned(0,man,executed).
had(0,young_man,had_caught).
been_condemned(0,man,executed_for_it).
had(0,man,had_caught_in_act).
had(0,young_man,had_caught_in_act).
been(0,man,condemned).
had(0,young_man,had_caught_in_daring_act).
had(0,young_man,had_caught_in_act_of_theft).
had(0,man,had_caught_in_act_of_theft).
had(0,man,had_caught_in_daring_act).
had(0,young_man,had_caught_in_daring_act_of_theft).
been_condemned(0,young_man,executed).
been_condemned(0,young_man,executed_for_it).
root(1,ROOT,expressed).
nsubj(1,expressed,he).
nmod:poss(1,desire,his).
dobj(1,expressed,desire).
mark(1,see,to).
dep(1,desire,see).
nmod:poss(1,mother,his).
dobj(1,see,mother).
cc(1,see,and).
mark(1,speak,to).
dep(1,desire,speak).
conj:and(1,see,speak).
case(1,her,with).
nmod:with(1,speak,her).
mark(1,led,before).
nsubjpass(1,led,he).
auxpass(1,led,was).
advcl:before(1,speak,led).
case(1,execution,to).
nmod:to(1,led,execution).
cc(1,led,and).
case(1,course,of).
nmod:of(1,granted,course).
nsubjpass(1,granted,this).
auxpass(1,granted,was).
advcl:before(1,speak,granted).
conj:and(1,led,granted).
speak(1,his_mother,led).
speak_with(1,his_mother,her).
was_led_to(1,he,execution).
speak(1,his_mother,led_to_execution).
was(1,he,led).
expressed(1,he,his_desire).
was_granted_of(1,this,course).
root(2,ROOT,came).
advmod(2,came,when).
nmod:poss(2,mother,his).
nsubj(2,came,mother).
case(2,him,to).
nmod:to(2,came,him).
nsubj(2,said,he).
ccomp(2,came,said).
came_to(2,his_mother,him).
root(3,ROOT,want).
nsubj(3,want,i).
nsubj:xsubj(3,whisper,i).
mark(3,whisper,to).
xcomp(3,want,whisper).
case(3,you,to).
nmod:to(3,whisper,you).
whisper_to(3,i,you).
want(3,i,whisper).
want(3,i,whisper_to_you).
root(4,ROOT,brought).
cc(4,brought,and).
advmod(4,brought,when).
nsubj(4,brought,she).
nmod:poss(4,ear,her).
dobj(4,brought,ear).
case(4,him,near).
nmod:near(4,ear,him).
nsubj(4,bit,he).
advmod(4,bit,nearly).
acl:relcl(4,ear,bit).
dobj(4,bit,it).
compound:prt(4,bit,off).
bit_off(4,he,it).
nearly_bit_off(4,he,it).
root(5,ROOT,horrified).
det:predet(5,bystanders,all).
det(5,bystanders,the).
nsubjpass(5,horrified,bystanders).
nsubjpass(5,asked,bystanders).
auxpass(5,horrified,were).
cc(5,horrified,and).
conj:and(5,horrified,asked).
dobj(5,asked,him).
dobj(5,mean,what).
nsubj(5,mean,he).
aux(5,mean,could).
dep(5,asked,mean).
case(5,brutal,by).
amod(5,brutal,such).
nmod:by(5,mean,brutal).
cc(5,brutal,and).
amod(5,conduct,inhuman).
nmod:by(5,mean,conduct).
conj:and(5,brutal,conduct).
asked(5,bystanders,him).
were(5,bystanders,horrified).
root(6,ROOT,is).
nsubj(6,is,it).
nsubj:xsubj(6,punish,it).
mark(6,punish,to).
xcomp(6,is,punish).
dobj(6,punish,her).
punish(6,it,her).
root(7,ROOT,said).
nsubj(7,said,he).
root(8,ROOT,young).
advmod(8,young,when).
nsubj(8,young,i).
cop(8,young,was).
nsubj(8,began,i).
nsubj(8,brought,i).
ccomp(8,young,began).
mark(8,stealing,with).
advcl:with(8,began,stealing).
amod(8,things,little).
dobj(8,stealing,things).
cc(8,began,and).
ccomp(8,young,brought).
conj:and(8,began,brought).
dobj(8,brought,them).
advmod(8,brought,home).
case(8,mother,to).
nmod:to(8,home,mother).
was(8,i,when_young).
was(8,i,young).
brought_home(8,i,them).
stealing(8,i,things).
brought(8,i,them).
stealing(8,i,little_things).
root(9,ROOT,rebuking).
cc(9,rebuking,instead).
mwe(9,instead,of).
cc(9,rebuking,and).
conj:and(9,rebuking,punishing).
dobj(9,rebuking,me).
nsubj(9,laughed,she).
nsubj(9,said,she).
acl:relcl(9,me,laughed).
cc(9,laughed,and).
acl:relcl(9,me,said).
conj:and(9,laughed,said).
root(10,ROOT,noticed).
nsubjpass(10,noticed,it).
aux(10,noticed,will).
neg(10,noticed,not).
auxpass(10,noticed,be).
root(11,ROOT,her).
nsubj(11,her,it).
cop(11,her,is).
case(11,her,because).
mwe(11,because,of).
dobj(11,to-day,her).
ref(11,her,that).
nsubj(11,to-day,i).
cop(11,to-day,am).
advmod(11,to-day,here).
acl:relcl(11,her,to-day).
am(11,i,here_to-day).
am(11,i,to-day).
root(12,ROOT,woman).
nsubj(12,woman,he).
cop(12,woman,is).
amod(12,woman,right).
is(12,he,woman).
is(12,he,right_woman).
root(13,ROOT,said).
det(13,priest,the).
nsubj(13,said,priest).
root(14,ROOT,hath).
det(14,lord,the).
nsubj(14,hath,lord).
ccomp(14,hath,said).
root(15,ROOT,train).
case(15,child,up).
det(15,child,a).
nmod:up(15,train,child).
case(15,way,in).
det(15,way,the).
nmod:in(15,child,way).
nsubj(15,go,he).
aux(15,go,should).
acl:relcl(15,way,go).
is_in(15,child,way).
root(16,ROOT,old).
cc(16,old,and).
advmod(16,old,when).
nsubj(16,old,he).
cop(16,old,is).
nsubj(16,depart,he).
aux(16,depart,will).
neg(16,depart,not).
ccomp(16,old,depart).
advmod(16,depart,therefrom).
