root(0,ROOT,had).
det(0,widow,a).
amod(0,widow,certain).
amod(0,widow,poor).
nsubj(0,had,widow).
nummod(0,sheep,one).
amod(0,sheep,solitary).
dobj(0,had,sheep).
had(0,poor_widow,one_solitary_sheep).
had(0,certain_poor_widow,one_solitary_sheep).
had(0,poor_widow,one_sheep).
had(0,widow,one_sheep).
had(0,certain_widow,one_solitary_sheep).
had(0,certain_widow,one_sheep).
had(0,certain_poor_widow,one_sheep).
had(0,widow,one_solitary_sheep).
root(1,ROOT,time).
case(1,time,at).
amod(1,time,shearing).
acl(1,time,wishing).
mark(1,take,to).
xcomp(1,wishing,take).
nmod:poss(1,fleece,his).
dobj(1,take,fleece).
cc(1,time,and).
mark(1,avoid,to).
conj:and(1,time,avoid).
dobj(1,avoid,expense).
nsubj(1,sheared,she).
nsubj(1,used,she).
acl:relcl(1,expense,sheared).
nsubj(1,herself,him).
xcomp(1,sheared,herself).
cc(1,sheared,but).
acl:relcl(1,expense,used).
conj:but(1,sheared,used).
det(1,shears,the).
dobj(1,used,shears).
advmod(1,used,so).
advmod(1,sheared,unskillfully).
mark(1,sheared,that).
case(1,fleece,with).
det(1,fleece,the).
nmod:with(1,sheared,fleece).
nsubj(1,sheared,she).
dep(1,used,sheared).
det(1,flesh,the).
dobj(1,sheared,flesh).
used(1,she,shears).
used_so(1,she,shears).
unskillfully_sheared_flesh_with(1,she,fleece).
sheared_flesh_with(1,she,fleece).
sheared(1,she,him_herself).
unskillfully_sheared(1,she,flesh).
sheared(1,she,flesh).
root(2,ROOT,said).
det(2,sheep,the).
nsubj(2,said,sheep).
acl(2,sheep,writhing).
case(2,pain,with).
nmod:with(2,writhing,pain).
root(3,ROOT,hurt).
advmod(3,hurt,why).
aux(3,hurt,do).
nsubj(3,hurt,you).
dobj(3,hurt,me).
mark(3,mistress,so).
advcl:so(3,hurt,mistress).
do_hurt(3,you,me).
root(4,ROOT,add).
det(4,weight,what).
dobj(4,add,weight).
aux(4,add,can).
nmod:poss(4,blood,my).
nsubj(4,add,blood).
case(4,wool,to).
det(4,wool,the).
nmod:to(4,add,wool).
root(5,ROOT,want).
mark(5,want,if).
nsubj(5,want,you).
nmod:poss(5,flesh,my).
dobj(5,want,flesh).
nsubj(5,kill,flesh).
expl(5,is,there).
acl:relcl(5,flesh,is).
det(5,butcher,the).
nsubj(5,is,butcher).
nsubj(5,kill,butcher).
ref(5,flesh,who).
ref(5,butcher,who).
aux(5,kill,will).
acl:relcl(5,butcher,kill).
dobj(5,kill,me).
case(5,instant,in).
det(5,instant,an).
nmod:in(5,kill,instant).
root(6,ROOT,want).
cc(6,want,but).
mark(6,want,if).
nsubj(6,want,you).
nsubj(6,hurt,you).
nmod:poss(6,fleece,my).
dobj(6,want,fleece).
nsubj(6,shear,fleece).
cc(6,fleece,and).
dobj(6,want,wool).
conj:and(6,fleece,wool).
nsubj(6,shear,wool).
expl(6,is,there).
acl:relcl(6,fleece,is).
det(6,shearer,the).
nsubj(6,is,shearer).
nsubj(6,shear,shearer).
ref(6,fleece,who).
ref(6,shearer,who).
aux(6,shear,will).
acl:relcl(6,shearer,shear).
cc(6,want,and).
neg(6,hurt,not).
conj:but(6,want,hurt).
dobj(6,hurt,me).
