root(0,ROOT,overcome).
det(0,wasps,the).
nsubj(0,overcome,wasps).
cc(0,wasps,and).
det(0,partridges,the).
conj:and(0,wasps,partridges).
nsubj(0,overcome,partridges).
mark(0,came,with).
nsubj(0,came,thirst).
nsubj:xsubj(0,give,thirst).
advcl:with(0,overcome,came).
case(0,farmer,to).
det(0,farmer,a).
nmod:to(0,came,farmer).
cc(0,farmer,and).
nmod:to(0,came,besought).
conj:and(0,farmer,besought).
dep(0,farmer,him).
mark(0,give,to).
xcomp(0,came,give).
iobj(0,give,them).
det(0,water,some).
dobj(0,give,water).
mark(0,drink,to).
acl:to(0,water,drink).
give(0,thirst,them).
came_to(0,thirst,farmer).
overcome(0,partridges,thirst_came).
give(0,thirst,water_drink).
overcome(0,wasps,thirst_came).
overcome(0,wasps,thirst_came_to_farmer).
overcome(0,partridges,thirst_came_to_farmer).
root(1,ROOT,promised).
nsubj(1,promised,they).
nsubj:xsubj(1,repay,they).
advmod(1,promised,amply).
mark(1,repay,to).
xcomp(1,promised,repay).
nsubj(1,favor,him).
det(1,favor,the).
xcomp(1,repay,favor).
dobj(1,asked,favor).
ref(1,favor,which).
nsubj(1,asked,they).
acl:relcl(1,favor,asked).
promised(1,they,repay).
promised_amply(1,they,repay).
root(2,ROOT,declared).
det(2,partridges,the).
nsubj(2,declared,partridges).
mark(2,dig,that).
nsubj(2,dig,they).
nsubj(2,make,they).
aux(2,dig,would).
ccomp(2,declared,dig).
case(2,vines,around).
nmod:poss(2,vines,his).
nmod:around(2,dig,vines).
cc(2,dig,and).
ccomp(2,declared,make).
conj:and(2,dig,make).
nsubj(2,produce,them).
ccomp(2,make,produce).
compound(2,grapes,finer).
dobj(2,produce,grapes).
dig_around(2,they,his_vines).
produce(2,them,finer_grapes).
root(3,ROOT,said).
det(3,wasps,the).
nsubj(3,said,wasps).
mark(3,keep,that).
nsubj(3,keep,they).
nsubj(3,drive,they).
aux(3,keep,would).
ccomp(3,said,keep).
dobj(3,keep,guard).
cc(3,keep,and).
ccomp(3,said,drive).
conj:and(3,keep,drive).
compound:prt(3,drive,off).
dobj(3,drive,thieves).
case(3,stings,with).
nmod:poss(3,stings,their).
nmod:with(3,thieves,stings).
is_with(3,thieves,their_stings).
root(4,ROOT,interrupted).
cc(4,interrupted,but).
det(4,farmer,the).
nsubj(4,interrupted,farmer).
nsubj(4,saying,them).
dep(4,interrupted,saying).
root(5,ROOT,have).
nsubj(5,have,i).
advmod(5,oxen,already).
nummod(5,oxen,two).
dobj(5,have,oxen).
nsubj(5,do,oxen).
ref(5,oxen,who).
mark(5,making,without).
advcl:without(5,do,making).
det(5,promises,any).
dobj(5,making,promises).
acl:relcl(5,oxen,do).
det:predet(5,things,all).
det(5,things,these).
dobj(5,do,things).
root(6,ROOT,better).
nsubj(6,better,it).
nsubj:xsubj(6,give,it).
cop(6,better,is).
advmod(6,better,surely).
case(6,me,for).
nmod:for(6,better,me).
mark(6,give,to).
xcomp(6,better,give).
det(6,water,the).
dobj(6,give,water).
case(6,them,to).
nmod:to(6,give,them).
case(6,you,than).
case(6,you,to).
nmod:to(6,give,you).
is_better_for(6,it,me).
is_surely_better_for(6,it,me).
give(6,it,water).
give_water_to(6,it,them).
give_water_than(6,it,than_you).
is(6,it,better).
is(6,it,surely_better).
