root(0,ROOT,accused).
det(0,wolf,a).
nsubj(0,accused,wolf).
nsubj(0,denied,wolf).
det(0,fox,a).
dobj(0,accused,fox).
case(0,theft,of).
nmod:of(0,fox,theft).
cc(0,accused,but).
det(0,fox,the).
nmod:npmod(0,entirely,fox).
advmod(0,denied,entirely).
conj:but(0,accused,denied).
det(0,charge,the).
dobj(0,denied,charge).
denied(0,wolf,charge).
entirely_denied(0,wolf,charge).
accused(0,wolf,fox_of_theft).
accused(0,wolf,fox).
root(1,ROOT,undertook).
det(1,ape,an).
nsubj(1,undertook,ape).
nsubj:xsubj(1,adjudge,ape).
mark(1,adjudge,to).
xcomp(1,undertook,adjudge).
det(1,matter,the).
dobj(1,adjudge,matter).
case(1,them,between).
nmod:between(1,matter,them).
adjudge(1,ape,matter_between_them).
adjudge(1,ape,matter).
root(2,ROOT,stated).
advmod(2,stated,when).
nsubj(2,stated,each).
aux(2,stated,had).
advmod(2,stated,fully).
nmod:poss(2,case,his).
dobj(2,stated,case).
det(2,ape,the).
nsubj(2,announced,ape).
acl:relcl(2,case,announced).
det(2,sentence,this).
dobj(2,announced,sentence).
announced(2,ape,sentence).
root(3,ROOT,think).
nsubj(3,think,i).
aux(3,think,do).
neg(3,think,not).
nsubj(3,wolf,you).
ccomp(3,think,wolf).
advmod(3,lost,ever).
dep(3,wolf,lost).
dobj(3,claim,what).
nsubj(3,claim,you).
ccomp(3,lost,claim).
root(4,ROOT,i).
cc(4,i,and).
acl:relcl(4,i,do).
ccomp(4,do,believe).
dobj(4,believe,you).
nsubj(4,deny,fox).
mark(4,stolen,to).
aux(4,stolen,have).
acl:to(4,fox,stolen).
nsubj(4,you,what).
xcomp(4,stolen,you).
advmod(4,deny,so).
advmod(4,deny,stoutly).
dep(4,believe,deny).
