root(0,ROOT,able).
det(0,weasel,a).
nsubj(0,able,weasel).
nsubj:xsubj(0,catch,weasel).
amod(0,weasel,inactive).
case(0,age,from).
nmod:from(0,inactive,age).
cc(0,age,and).
nmod:from(0,inactive,infirmities).
conj:and(0,age,infirmities).
cop(0,able,was).
neg(0,able,not).
mark(0,catch,to).
xcomp(0,able,catch).
dobj(0,catch,mice).
mark(0,did,as).
nsubj(0,did,he).
advmod(0,did,once).
advcl:as(0,catch,did).
inactive_from(0,weasel,age).
root(1,ROOT,rolled).
nsubj(1,rolled,he).
nsubj(1,lay,he).
advmod(1,rolled,therefore).
dobj(1,rolled,himself).
case(1,flour,in).
nmod:in(1,rolled,flour).
cc(1,rolled,and).
conj:and(1,rolled,lay).
compound:prt(1,lay,down).
case(1,corner,in).
det(1,corner,a).
amod(1,corner,dark).
nmod:in(1,lay,corner).
lay_down_in(1,he,dark_corner).
lay_down_in(1,he,corner).
therefore_rolled(1,he,himself).
rolled(1,he,himself).
root(2,ROOT,leaped).
det(2,mouse,a).
nsubj(2,leaped,mouse).
nsubjpass(2,caught,mouse).
acl(2,mouse,supposing).
dobj(2,supposing,him).
nsubj:xsubj(2,food,him).
mark(2,food,to).
cop(2,food,be).
xcomp(2,supposing,food).
case(2,him,upon).
nmod:upon(2,leaped,him).
cc(2,leaped,and).
auxpass(2,caught,was).
advmod(2,caught,instantly).
conj:and(2,leaped,caught).
cc(2,caught,and).
conj:and(2,leaped,squeezed).
conj:and(2,caught,squeezed).
case(2,death,to).
nmod:to(2,caught,death).
was_instantly_caught_to(2,mouse,death).
leaped_upon(2,mouse,him).
was_caught_to(2,mouse,death).
was(2,mouse,caught).
was(2,mouse,instantly_caught).
be(2,him,food).
root(3,ROOT,perished).
nsubj(3,perished,another).
case(3,manner,in).
det(3,manner,a).
amod(3,manner,similar).
nmod:in(3,others,manner).
cc(3,manner,and).
advmod(3,third,then).
det(3,third,a).
conj:and(3,manner,third).
nmod:in(3,others,third).
cc(3,manner,and).
conj:and(3,manner,still).
nmod:in(3,others,still).
dobj(3,perished,others).
case(3,them,after).
nmod:after(3,perished,them).
perished(3,another,in_similar_manner_others).
perished(3,another,others).
perished_others_after(3,another,them).
perished(3,another,in_manner_others).
perished_after(3,another,them).
is_in(3,others,similar_manner).
root(4,ROOT,mouse).
det(4,mouse,a).
advmod(4,old,very).
amod(4,mouse,old).
nsubj(4,escaped,mouse).
nsubj(4,snare,mouse).
nsubj(4,said,mouse).
ref(4,mouse,who).
aux(4,escaped,had).
acl:relcl(4,mouse,escaped).
amod(4,trap,many).
det(4,trap,a).
dobj(4,escaped,trap).
cc(4,escaped,and).
acl:relcl(4,mouse,snare).
conj:and(4,escaped,snare).
dep(4,snare,observed).
case(4,distance,from).
det(4,distance,a).
amod(4,distance,safe).
nmod:from(4,observed,distance).
det(4,trick,the).
dobj(4,observed,trick).
case(4,foe,of).
nmod:poss(4,foe,his).
amod(4,foe,crafty).
nmod:of(4,trick,foe).
cc(4,escaped,and).
acl:relcl(4,mouse,said).
conj:and(4,escaped,said).
observed_from(4,snare,distance).
observed_trick_from(4,snare,distance).
observed_trick_from(4,snare,safe_distance).
observed_from(4,snare,safe_distance).
observed(4,snare,trick_of_his_foe).
observed(4,snare,trick_of_his_crafty_foe).
observed(4,snare,trick).
root(5,ROOT,ah).
root(6,ROOT,you).
nsubj(6,lie,you).
ref(6,you,that).
acl:relcl(6,you,lie).
expl(6,may,there).
ccomp(6,lie,may).
dobj(6,may,you).
dep(6,may,prosper).
advmod(6,prosper,just).
case(6,proportion,in).
det(6,proportion,the).
amod(6,proportion,same).
nmod:in(6,you,proportion).
mark(6,are,as).
nsubj(6,are,you).
dep(6,proportion,are).
dobj(6,pretend,what).
nsubj:xsubj(6,be,what).
nsubj(6,pretend,you).
ccomp(6,are,pretend).
mark(6,be,to).
xcomp(6,pretend,be).
