root(0,ROOT,possessed).
det(0,woman,a).
nsubj(0,possessed,woman).
det(0,hen,a).
dobj(0,possessed,hen).
nsubj(0,gave,hen).
ref(0,hen,that).
acl:relcl(0,hen,gave).
iobj(0,gave,her).
det(0,egg,an).
dobj(0,gave,egg).
det(0,day,every).
dep(0,egg,day).
root(1,ROOT,pondered).
nsubj(1,pondered,she).
advmod(1,pondered,often).
advmod(1,obtain,how).
nsubj(1,obtain,she).
aux(1,obtain,might).
ccomp(1,pondered,obtain).
nummod(1,eggs,two).
dobj(1,obtain,eggs).
nsubj(1,gain,daily).
conj:and(1,daily,daily).
nsubj(1,gain,daily).
advmod(1,one,instead).
case(1,one,of).
nmod:of(1,daily,one).
cc(1,daily,and).
case(1,last,at).
nmod:at(1,daily,last).
mark(1,gain,to).
acl:relcl(1,eggs,gain).
nmod:poss(1,purpose,her).
nsubj(1,determined,purpose).
nsubj:xsubj(1,give,purpose).
ccomp(1,gain,determined).
mark(1,give,to).
xcomp(1,determined,give).
det(1,hen,the).
iobj(1,give,hen).
det(1,allowance,a).
amod(1,allowance,double).
dobj(1,give,allowance).
case(1,barley,of).
nmod:of(1,allowance,barley).
give(1,her_purpose,allowance_of_barley).
give(1,her_purpose,hen).
give(1,her_purpose,allowance).
give(1,her_purpose,double_allowance).
give(1,her_purpose,double_allowance_of_barley).
root(2,ROOT,day).
case(2,day,from).
det(2,day,that).
det(2,hen,the).
nsubj(2,became,hen).
acl:relcl(2,day,became).
xcomp(2,became,fat).
cc(2,fat,and).
xcomp(2,became,sleek).
conj:and(2,fat,sleek).
cc(2,day,and).
dep(2,once,never).
advmod(2,laid,once).
conj:and(2,day,laid).
det(2,egg,another).
dobj(2,laid,egg).
became(2,hen,fat).
