root(0,ROOT,entered).
det(0,ass,a).
amod(0,ass,wild).
nsubj(0,entered,ass).
cc(0,ass,and).
det(0,lion,a).
conj:and(0,ass,lion).
nsubj(0,entered,lion).
case(0,alliance,into).
det(0,alliance,an).
nmod:into(0,entered,alliance).
mark(0,capture,so).
mwe(0,so,that).
nsubj(0,capture,they).
aux(0,capture,might).
advcl:so_that(0,entered,capture).
det(0,beasts,the).
dobj(0,capture,beasts).
case(0,forest,of).
det(0,forest,the).
nmod:of(0,beasts,forest).
case(0,ease,with).
amod(0,ease,greater).
nmod:with(0,capture,ease).
entered_into(0,ass,alliance).
might_capture_beasts_with(0,they,greater_ease).
entered_into(0,wild_ass,alliance).
might_capture_beasts_with(0,they,ease).
might_capture(0,they,beasts).
might_capture(0,they,beasts_of_forest).
entered_into(0,lion,alliance).
beasts_of(0,they,forest).
root(1,ROOT,agreed).
det(1,lion,the).
nsubj(1,agreed,lion).
nsubj:xsubj(1,assist,lion).
mark(1,assist,to).
xcomp(1,agreed,assist).
det(1,ass,the).
amod(1,ass,wild).
dobj(1,assist,ass).
case(1,strength,with).
nmod:poss(1,strength,his).
nmod:with(1,assist,strength).
mark(1,gave,while).
det(1,ass,the).
amod(1,ass,wild).
nsubj(1,gave,ass).
advcl:while(1,assist,gave).
det(1,lion,the).
iobj(1,gave,lion).
det(1,benefit,the).
dobj(1,gave,benefit).
case(1,speed,of).
nmod:poss(1,speed,his).
amod(1,speed,greater).
nmod:of(1,benefit,speed).
gave(1,ass,benefit_of_his_speed).
gave(1,ass,benefit_of_his_greater_speed).
assist_ass_with(1,lion,his_strength).
assist(1,lion,wild_ass).
benefit_of(1,ass,his_greater_speed).
gave(1,ass,benefit).
assist(1,lion,ass).
gave(1,wild_ass,benefit_of_his_speed).
gave(1,ass,lion).
benefit_of(1,wild_ass,his_speed).
gave(1,wild_ass,benefit).
gave(1,wild_ass,lion).
gave(1,wild_ass,benefit_of_his_greater_speed).
benefit_of(1,wild_ass,his_greater_speed).
benefit_of(1,ass,his_speed).
root(2,ROOT,taken).
advmod(2,taken,when).
nsubj(2,taken,they).
aux(2,taken,had).
advmod(2,many,as).
nummod(2,beasts,many).
dobj(2,taken,beasts).
mark(2,required,as).
nmod:poss(2,necessities,their).
nsubj(2,required,necessities).
advcl:as(2,taken,required).
det(2,lion,the).
nsubj(2,undertook,lion).
nsubj:xsubj(2,distribute,lion).
ccomp(2,required,undertook).
mark(2,distribute,to).
xcomp(2,undertook,distribute).
det(2,prey,the).
dobj(2,distribute,prey).
cc(2,taken,and).
case(2,purpose,for).
det(2,purpose,this).
conj:and(2,taken,purpose).
acl(2,purpose,divided).
dobj(2,divided,it).
case(2,shares,into).
nummod(2,shares,three).
nmod:into(2,divided,shares).
divided_it_into(2,they_purpose,three_shares).
had_taken(2,they,many_beasts).
divided_into(2,they_purpose,three_shares).
had_taken(2,they,beasts).
distribute(2,lion,prey).
had_taken(2,they,as_many_beasts).
divided(2,they_purpose,it).
had_taken_beasts(2,they,their_necessities_required).
root(3,ROOT,take).
nsubj(3,take,i).
aux(3,take,will).
det(3,share,the).
amod(3,share,first).
dobj(3,take,share).
will_take(3,i,first_share).
will_take(3,i,share).
root(4,ROOT,said).
nsubj(4,said,he).
root(5,ROOT,king).
mark(5,king,because).
nsubj(5,king,i).
cop(5,king,am).
cc(5,king,and).
det(5,share,the).
amod(5,share,second).
dep(5,source,share).
mark(5,source,as).
det(5,partner,a).
nsubj(5,source,partner).
nsubj(5,set,partner).
case(5,you,with).
nmod:with(5,partner,you).
case(5,chase,in).
det(5,chase,the).
nmod:in(5,you,chase).
cc(5,chase,and).
det(5,share,the).
amod(5,share,third).
nmod:in(5,you,share).
conj:and(5,chase,share).
punct(5,believe,-LRB-).
dep(5,you,believe).
dobj(5,believe,me).
punct(5,believe,-RRB-).
aux(5,source,will).
cop(5,source,be).
det(5,source,a).
conj:and(5,king,source).
case(5,great,of).
nmod:of(5,source,great).
amod(5,great,evil).
case(5,you,to).
nmod:to(5,evil,you).
mark(5,resign,unless).
nsubj(5,resign,you).
advmod(5,resign,willingly).
advcl:unless(5,source,resign).
dobj(5,resign,it).
case(5,me,to).
nmod:to(5,resign,me).
cc(5,source,and).
conj:and(5,king,set).
conj:and(5,source,set).
compound:prt(5,set,off).
advmod(5,fast,as).
advmod(5,set,fast).
mark(5,can,as).
nsubj(5,can,you).
advcl:as(5,fast,can).
is_with(5,partner,you_in_chase).
willingly_resign(5,you,it).
resign(5,you,it).
will(5,partner,will_source).
am(5,i,king).
root(6,ROOT,makes).
aux(6,makes,might).
nsubj(6,makes,right).
