root(0,ROOT,met).
det(0,wolf,a).
nsubj(0,met,wolf).
nsubj(0,addressed,wolf).
acl(0,wolf,coming).
compound:prt(0,coming,out).
case(0,field,of).
det(0,field,a).
nmod:of(0,coming,field).
case(0,oats,of).
nmod:of(0,field,oats).
det(0,horse,a).
dobj(0,met,horse).
cc(0,met,and).
advmod(0,addressed,thus).
conj:and(0,met,addressed).
dobj(0,addressed,him).
met(0,wolf,horse).
thus_addressed(0,wolf,him).
addressed(0,wolf,him).
root(1,ROOT,advise).
nsubj(1,advise,i).
aux(1,advise,would).
dobj(1,advise,you).
nsubj:xsubj(1,go,you).
mark(1,go,to).
xcomp(1,advise,go).
case(1,field,into).
det(1,field,that).
nmod:into(1,go,field).
go_into(1,you,field).
would_advise(1,i,you).
root(2,ROOT,full).
nsubj(2,full,it).
cop(2,full,is).
case(2,oats,of).
amod(2,oats,fine).
nmod:of(2,full,oats).
dobj(2,untouched,which).
nsubj(2,left,i).
aux(2,left,have).
ccomp(2,full,left).
xcomp(2,left,untouched).
case(2,you,for).
nmod:for(2,untouched,you).
mark(2,friend,as).
nsubj(2,friend,you).
cop(2,friend,are).
det(2,friend,a).
advcl:as(2,left,friend).
dobj(2,hear,friend).
ref(2,friend,whom).
nsubj(2,love,i).
nsubj:xsubj(2,hear,i).
aux(2,love,would).
acl:relcl(2,friend,love).
mark(2,hear,to).
xcomp(2,love,hear).
xcomp(2,hear,enjoying).
amod(2,eating,good).
dobj(2,enjoying,eating).
is_full_of(2,it,fine_oats).
would_love(2,i,hear).
is(2,it,full).
is_full_of(2,it,oats).
root(3,ROOT,replied).
det(3,horse,the).
nsubj(3,replied,horse).
root(4,ROOT,food).
mark(4,food,if).
nsubj(4,food,oats).
aux(4,food,had).
cop(4,food,been).
det(4,food,the).
case(4,wolves,of).
nmod:of(4,food,wolves).
nsubj(4,indulged,you).
aux(4,indulged,would).
neg(4,indulged,never).
aux(4,indulged,have).
acl:relcl(4,wolves,indulged).
nmod:poss(4,ears,your).
dobj(4,indulged,ears).
case(4,cost,at).
det(4,cost,the).
nmod:at(4,indulged,cost).
case(4,belly,of).
nmod:poss(4,belly,your).
nmod:of(4,cost,belly).
had(4,oats,had_food).
root(5,ROOT,men).
case(5,reputation,of).
amod(5,reputation,evil).
nmod:of(5,men,reputation).
advmod(5,perform,when).
nsubj(5,perform,they).
dep(5,men,perform).
det(5,deed,a).
amod(5,deed,good).
nsubj(5,fail,deed).
nsubj:xsubj(5,get,deed).
ccomp(5,perform,fail).
mark(5,get,to).
xcomp(5,fail,get).
dobj(5,get,credit).
case(5,it,for).
nmod:for(5,get,it).
get_credit_for(5,good_deed,it).
get(5,deed,credit).
get(5,good_deed,credit).
get_credit_for(5,deed,it).
