root(0,ROOT,stood).
det(0,boar,a).
amod(0,boar,wild).
nsubj(0,stood,boar).
nsubj(0,rubbed,boar).
case(0,tree,under).
det(0,tree,a).
nmod:under(0,stood,tree).
cc(0,stood,and).
conj:and(0,stood,rubbed).
nmod:poss(0,tusks,his).
dobj(0,rubbed,tusks).
case(0,trunk,against).
det(0,trunk,the).
nmod:against(0,rubbed,trunk).
rubbed(0,wild_boar,his_tusks).
stood_under(0,boar,tree).
rubbed(0,boar,his_tusks).
stood_under(0,wild_boar,tree).
root(1,ROOT,asked).
det(1,passing,a).
compound(1,passing,fox).
nsubj(1,asked,passing).
advmod(1,asked,by).
dobj(1,asked,him).
advmod(1,sharpened,why).
nsubj(1,sharpened,he).
advmod(1,sharpened,thus).
advcl(1,asked,sharpened).
nmod:poss(1,teeth,his).
dobj(1,sharpened,teeth).
advmod(1,was,when).
expl(1,was,there).
advcl(1,sharpened,was).
neg(1,danger,no).
nsubj(1,was,danger).
acl(1,danger,threatening).
case(1,huntsman,from).
cc:preconj(1,huntsman,either).
nmod:from(1,threatening,huntsman).
cc(1,huntsman,or).
nmod:from(1,threatening,hound).
conj:or(1,huntsman,hound).
by_asked(1,fox_passing,him).
asked(1,fox_passing,him).
root(2,ROOT,replied).
nsubj(2,replied,he).
root(3,ROOT,do).
nsubj(3,do,i).
dobj(3,do,it).
advmod(3,do,advisedly).
do(3,i,it).
do_advisedly(3,i,it).
root(4,ROOT,do).
mark(4,do,for).
nsubj(4,do,it).
nsubj:xsubj(4,have,it).
aux(4,do,would).
neg(4,do,never).
mark(4,have,to).
xcomp(4,do,have).
mark(4,sharpen,to).
xcomp(4,have,sharpen).
nmod:poss(4,weapons,my).
dobj(4,sharpen,weapons).
advmod(4,sharpen,just).
case(4,time,at).
det(4,time,the).
nmod:at(4,sharpen,time).
nsubj(4,ought,i).
nsubj:xsubj(4,using,i).
acl:relcl(4,time,ought).
mark(4,using,to).
aux(4,using,be).
xcomp(4,ought,using).
dobj(4,using,them).
