root(0,ROOT,lapping).
advmod(0,lapping,once).
case(0,time,upon).
det(0,time,a).
nmod:upon(0,lapping,time).
det(0,wolf,a).
dep(0,time,wolf).
aux(0,lapping,was).
case(0,spring,at).
det(0,spring,a).
nmod:at(0,lapping,spring).
case(0,hillside,on).
det(0,hillside,a).
nmod:on(0,spring,hillside).
advmod(0,looking,when).
advcl(0,lapping,looking).
compound:prt(0,looking,up).
dep(0,see,what).
aux(0,see,should).
nsubj(0,see,he).
dep(0,lapping,see).
case(0,lamb,but).
det(0,lamb,a).
nmod:but(0,see,lamb).
advmod(0,beginning,just).
acl(0,lamb,beginning).
mark(0,drink,to).
xcomp(0,beginning,drink).
det(0,little,a).
dobj(0,drink,little).
advmod(0,drink,lower).
case(0,lower,down).
root(1,ROOT,'s).
expl(1,'s,there).
nmod:poss(1,supper,my).
nsubj(1,'s,supper).
root(2,ROOT,thought).
dobj(2,thought,he).
root(3,ROOT,find).
mark(3,find,if).
advmod(3,find,only).
nsubj(3,find,i).
aux(3,find,can).
det(3,excuse,some).
dobj(3,find,excuse).
mark(3,seize,to).
acl:to(3,excuse,seize).
dobj(3,seize,it).
root(4,ROOT,called).
advmod(4,he,then).
nsubj(4,called,he).
compound:prt(4,called,out).
case(4,lamb,to).
det(4,lamb,the).
nmod:to(4,called,lamb).
called_out_to(4,he,lamb).
root(5,ROOT,dare).
advmod(5,dare,how).
nsubj(5,muddle,you).
ccomp(5,dare,muddle).
det(5,water,the).
dobj(5,muddle,water).
mark(5,drinking,from).
dobj(5,drinking,which).
nsubj(5,drinking,i).
cop(5,drinking,am).
advcl:from(5,muddle,drinking).
muddle(5,you,water).
root(6,ROOT,nay).
compound(6,nay,master).
dep(6,nay,nay).
root(7,ROOT,said).
nsubj(7,said,lambikin).
root(8,ROOT,cause).
mark(8,cause,if).
det(8,water,the).
nsubj(8,cause,water).
cop(8,muddy,be).
dep(8,water,muddy).
case(8,there,up).
nmod:up(8,muddy,there).
dep(8,muddy,i).
aux(8,cause,can).
neg(8,cause,not).
cop(8,cause,be).
det(8,cause,the).
case(8,it,of).
nmod:of(8,cause,it).
mark(8,runs,for).
nsubj(8,runs,it).
advcl:for(8,cause,runs).
compound:prt(8,runs,down).
case(8,you,from).
nmod:from(8,runs,you).
case(8,me,to).
nmod:to(8,runs,me).
root(9,ROOT,then).
dep(9,then,well).
root(10,ROOT,said).
det(10,wolf,the).
nsubj(10,said,wolf).
root(11,ROOT,call).
advmod(11,call,why).
aux(11,call,did).
nsubj(11,call,you).
iobj(11,call,me).
amod(11,names,bad).
dobj(11,call,names).
det(11,time,this).
nmod:tmod(11,call,time).
amod(11,year,last).
dep(11,time,year).
did_call(11,you,names).
did_call(11,you,bad_names).
did_call(11,you,me).
did_call_names_at_time(11,you,time).
root(12,ROOT,be).
nsubj(12,be,that).
aux(12,be,can).
neg(12,be,not).
root(13,ROOT,said).
det(13,lamb,the).
nsubj(13,said,lamb).
root(14,ROOT,old).
nsubj(14,old,i).
cop(14,old,am).
advmod(14,months,only).
nummod(14,months,six).
nmod:npmod(14,old,months).
am_old(14,i,six_months).
am(14,i,old).
am_old(14,i,only_six_months).
root(15,ROOT,care).
nsubj(15,care,i).
aux(15,care,do).
neg(15,care,n't).
root(16,ROOT,snarled).
det(16,wolf,the).
nsubj(16,snarled,wolf).
root(17,ROOT,you).
mark(17,you,if).
nsubj(17,you,it).
cop(17,you,was).
neg(17,you,not).
nsubj(17,father,it).
cop(17,father,was).
nmod:poss(17,father,your).
acl:relcl(17,you,father).
was(17,it,your_father).
root(18,ROOT,rushed).
cc(18,rushed,and).
case(18,that,with).
nmod:with(18,rushed,that).
nsubj(18,rushed,he).
case(18,lamb,upon).
det(18,lamb,the).
amod(18,lamb,poor).
amod(18,lamb,little).
nmod:upon(18,rushed,lamb).
advmod(18,rushed,and).
punct(18,rushed,.).
rushed_with(18,he,that).
rushed_and_with(18,he,that).
rushed_and_upon(18,he,poor_lamb).
rushed_and_upon(18,he,little_lamb).
rushed_upon(18,he,lamb).
rushed_upon(18,he,poor_lamb).
rushed_and_upon(18,he,lamb).
rushed_upon(18,he,little_lamb).
rushed_upon(18,he,poor_little_lamb).
rushed_and_upon(18,he,poor_little_lamb).
