root(0,ROOT,time).
dep(0,time,at).
nummod(0,time,one).
nsubj(0,exceeded,time).
det(0,wolf,a).
advmod(0,large,very).
amod(0,wolf,large).
cc(0,large,and).
conj:and(0,large,strong).
amod(0,wolf,strong).
nsubjpass(0,born,wolf).
auxpass(0,born,was).
acl:relcl(0,time,born).
case(0,wolves,among).
det(0,wolves,the).
nmod:among(0,born,wolves).
nsubj(0,exceeded,wolves).
ref(0,time,who).
ref(0,wolves,who).
acl:relcl(0,wolves,exceeded).
det:predet(0,fellow-wolves,all).
nmod:poss(0,fellow-wolves,his).
dobj(0,exceeded,fellow-wolves).
case(0,size,in).
compound(0,size,strength).
nmod:in(0,exceeded,size).
cc(0,size,and).
nmod:in(0,exceeded,swiftness).
conj:and(0,size,swiftness).
mark(0,decided,so).
mwe(0,so,that).
nsubj(0,decided,they).
nsubj:xsubj(0,call,they).
advmod(0,decided,unanimously).
advcl:so_that(0,exceeded,decided).
mark(0,call,to).
xcomp(0,decided,call).
dobj(0,call,him).
was(0,large_wolf,born).
was(0,wolf,born).
call(0,they,him).
root(1,ROOT,lion).
root(2,ROOT,proportioned).
det(2,wolf,the).
nsubj(2,proportioned,wolf).
case(2,lack,with).
det(2,lack,a).
nmod:with(2,wolf,lack).
case(2,sense,of).
nmod:of(2,lack,sense).
case(2,size,to).
nmod:poss(2,size,his).
amod(2,size,enormous).
nmod:to(2,proportioned,size).
mark(2,gave,size).
acl:relcl(2,size,thought).
ref(2,size,that).
nsubj(2,gave,they).
ccomp(2,thought,gave).
iobj(2,gave,him).
det(2,name,this).
dobj(2,gave,name).
case(2,earnest,in).
nmod:in(2,name,earnest).
cc(2,gave,and).
csubj(2,consorted,leaving).
nmod:poss(2,race,his).
amod(2,race,own).
dobj(2,leaving,race).
ccomp(2,thought,consorted).
conj:and(2,gave,consorted).
advmod(2,consorted,exclusively).
case(2,lions,with).
det(2,lions,the).
nmod:with(2,consorted,lions).
is_with(2,wolf,lack_of_sense).
is_in(2,name,earnest).
root(3,ROOT,said).
det(3,fox,an).
amod(3,fox,old).
amod(3,fox,sly).
nsubj(3,said,fox).
acl(3,fox,seeing).
dobj(3,seeing,this).
root(4,ROOT,may).
nsubj(4,may,i).
neg(4,make,never).
acl:relcl(4,i,make).
nsubj(4,do,myself).
advmod(4,ridiculous,so).
dep(4,do,ridiculous).
mark(4,do,as).
nsubj(4,do,you).
xcomp(4,make,do).
case(4,pride,in).
nmod:poss(4,pride,your).
nmod:in(4,do,pride).
cc(4,pride,and).
nmod:in(4,do,self-conceit).
conj:and(4,pride,self-conceit).
do_in(4,you,your_pride).
do_in(4,myself,your_pride).
root(5,ROOT,wolf).
mark(5,wolf,for).
advmod(5,have,even).
mark(5,have,though).
nsubj(5,have,you).
advcl:though(5,wolf,have).
det(5,size,the).
dobj(5,have,size).
case(5,lion,of).
det(5,lion,a).
nmod:of(5,size,lion).
case(5,wolves,among).
nmod:among(5,lion,wolves).
case(5,herd,in).
det(5,herd,a).
nmod:in(5,wolves,herd).
case(5,lions,of).
nmod:of(5,herd,lions).
nsubj(5,wolf,you).
cop(5,wolf,are).
advmod(5,wolf,definitely).
det(5,wolf,a).
size_of(5,you,lion).
is_in(5,wolves,herd_of_lions).
have(5,you,size).
even_have(5,you,size_of_lion_among_wolves_in_herd).
are(5,you,wolf).
have(5,you,size_of_lion_among_wolves).
have(5,you,size_of_lion_among_wolves_in_herd).
size_of(5,you,lion_among_wolves_in_herd_of_lions).
have(5,you,size_of_lion_among_wolves_in_herd_of_lions).
even_have(5,you,size_of_lion_among_wolves_in_herd_of_lions).
size_of(5,you,lion_among_wolves).
even_have(5,you,size_of_lion_among_wolves).
size_of(5,you,lion_among_wolves_in_herd).
are(5,you,definitely_wolf).
have(5,you,size_of_lion).
even_have(5,you,size).
even_have(5,you,size_of_lion).
