root(0,ROOT,vixen).
det(0,vixen,a).
nsubj(0,taking,vixen).
ref(0,vixen,who).
aux(0,taking,was).
acl:relcl(0,vixen,taking).
nmod:poss(0,babies,her).
dobj(0,taking,babies).
compound:prt(0,taking,out).
case(0,an,for).
nmod:for(0,vixen,an).
amod(0,an,airing).
nummod(0,morning,one).
amod(0,morning,balmy).
nsubj(0,came,morning).
acl:relcl(0,an,came).
case(0,lioness,across).
det(0,lioness,a).
nmod:across(0,came,lioness).
case(0,cub,with).
nmod:poss(0,cub,her).
nmod:with(0,lioness,cub).
case(0,arms,in).
nmod:in(0,came,arms).
came_across(0,balmy_morning,lioness).
came_in(0,balmy_morning,arms).
came_in(0,one_balmy_morning,arms).
is_with(0,lioness,her_cub).
came_across(0,balmy_morning,lioness_with_her_cub).
came_across(0,one_balmy_morning,lioness_with_her_cub).
came_across(0,one_balmy_morning,lioness).
root(1,ROOT,why).
amod(1,airs,such).
nmod:npmod(1,haughty,airs).
amod(1,dame,haughty).
nmod:over(1,why,dame).
case(1,dame,over).
nummod(1,cub,one).
amod(1,cub,solitary).
dep(1,dame,cub).
root(2,ROOT,sneered).
det(2,vixen,the).
nsubj(2,sneered,vixen).
root(3,ROOT,look).
case(3,healthy,at).
nmod:poss(3,healthy,my).
nmod:at(3,look,healthy).
cc(3,healthy,and).
amod(3,litter,numerous).
nmod:at(3,look,litter).
conj:and(3,healthy,litter).
advmod(3,look,here).
cc(3,look,and).
conj:and(3,look,imagine).
mark(3,able,if).
nsubj(3,able,you).
cop(3,able,are).
advcl:if(3,imagine,able).
advmod(3,feel,how).
det(3,mother,a).
amod(3,mother,proud).
nsubj(3,feel,mother).
aux(3,feel,should).
ccomp(3,able,feel).
are(3,you,able).
root(4,ROOT,walked).
det(4,lioness,the).
nsubj(4,walked,lioness).
dep(4,lioness,gave).
iobj(4,gave,her).
det(4,look,a).
compound(4,look,squelching).
dobj(4,gave,look).
cc(4,gave,and).
dep(4,lioness,lifting).
conj:and(4,gave,lifting).
compound:prt(4,lifting,up).
nmod:poss(4,nose,her).
dobj(4,lifting,nose).
advmod(4,saying,away).
xcomp(4,walked,saying).
advmod(4,saying,calmly).
walked(4,lioness,saying_calmly).
walked(4,lioness,away_saying).
walked(4,lioness,saying).
lifting_up(4,squelching_look,her_nose).
walked(4,lioness,away_saying_calmly).
root(5,ROOT,yes).
advmod(5,look,just).
dep(5,yes,look).
case(5,collection,at).
det(5,collection,that).
amod(5,collection,beautiful).
nmod:at(5,look,collection).
root(6,ROOT,what).
cop(6,what,are).
nsubj(6,what,they).
root(7,ROOT,foxes).
root(8,ROOT,'ve).
nsubj(8,'ve,i).
nsubj(8,remember,i).
advmod(8,one,only).
dobj(8,'ve,one).
cc(8,'ve,but).
conj:but(8,'ve,remember).
mark(8,lion,that).
nsubj(8,lion,one).
cop(8,lion,is).
det(8,lion,a).
ccomp(8,remember,lion).
is(8,one,lion).
ve(8,i,only_one).
root(9,ROOT,better).
nsubj(9,better,quality).
cop(9,better,is).
case(9,quantity,than).
nmod:than(9,better,quantity).
is(9,quality,better).
is_better_than(9,quality,quantity).
