root(0,ROOT,be).
advmod(0,be,why).
aux(0,be,should).
expl(0,be,there).
advmod(0,be,always).
det(0,fear,this).
dep(0,be,fear).
cc(0,fear,and).
dep(0,be,slaughter).
conj:and(0,fear,slaughter).
case(0,us,between).
nmod:between(0,fear,us).
root(1,ROOT,said).
det(1,wolves,the).
nsubj(1,said,wolves).
case(1,sheep,to).
det(1,sheep,the).
nmod:to(1,wolves,sheep).
root(2,ROOT,have).
det(2,dogs,those).
amod(2,dogs,evil-disposed).
nsubj(2,have,dogs).
nsubj:xsubj(2,answer,dogs).
advmod(2,have,much).
mark(2,answer,to).
xcomp(2,have,answer).
nmod(2,answer,for).
have(2,dogs,answer_for).
have_much(2,dogs,answer).
have(2,dogs,answer).
have_much(2,evil-disposed_dogs,answer).
have_much(2,evil-disposed_dogs,answer_for).
have_much(2,dogs,answer_for).
have(2,evil-disposed_dogs,answer_for).
have(2,evil-disposed_dogs,answer).
root(3,ROOT,bark).
nsubj(3,bark,they).
advmod(3,bark,always).
advmod(3,approach,whenever).
nsubj(3,approach,we).
nsubj(3,attack,we).
advcl(3,bark,approach).
dobj(3,approach,you).
cc(3,approach,and).
advcl(3,bark,attack).
conj:and(3,approach,attack).
dobj(3,attack,us).
mark(3,done,before).
nsubj(3,done,we).
aux(3,done,have).
advcl:before(3,attack,done).
det(3,harm,any).
dobj(3,done,harm).
attack(3,we,us).
approach(3,we,you).
have_done(3,we,harm).
root(4,ROOT,dismiss).
mark(4,dismiss,if).
nsubj(4,dismiss,you).
aux(4,dismiss,would).
advmod(4,dismiss,only).
dobj(4,dismiss,them).
case(4,heels,from).
nmod:poss(4,heels,your).
nmod:from(4,dismiss,heels).
nsubj(4,treaties,there).
aux(4,treaties,might).
advmod(4,treaties,soon).
cop(4,treaties,be).
dep(4,dismiss,treaties).
case(4,peace,of).
nmod:of(4,treaties,peace).
cc(4,peace,and).
nmod:of(4,treaties,reconciliation).
conj:and(4,peace,reconciliation).
case(4,us,between).
nmod:between(4,treaties,us).
might(4,there,might_soon_treaties_of_peace_between_us).
might(4,there,might_soon_treaties_of_peace).
would_only_dismiss(4,you,them).
might(4,there,might_soon_treaties).
might(4,there,might_treaties_between_us).
might(4,there,might_soon_treaties_between_us).
would_dismiss(4,you,them).
might(4,there,might_treaties_of_peace).
might(4,there,might_treaties).
might(4,there,might_treaties_of_peace_between_us).
root(5,ROOT,whereupon).
det(5,sheep,the).
nsubj(5,whereupon,sheep).
amod(5,creatures,poor).
amod(5,creatures,silly).
nsubjpass(5,beguiled,creatures).
nsubjpass(5,dismissed,creatures).
auxpass(5,beguiled,were).
advmod(5,beguiled,easily).
acl:relcl(5,sheep,beguiled).
cc(5,beguiled,and).
acl:relcl(5,sheep,dismissed).
conj:and(5,beguiled,dismissed).
det(5,dogs,the).
dobj(5,beguiled,dogs).
det(5,wolves,the).
nsubj(5,destroyed,wolves).
ccomp(5,whereupon,destroyed).
det(5,flock,the).
amod(5,flock,unguarded).
dobj(5,destroyed,flock).
case(5,pleasure,at).
nmod:poss(5,pleasure,their).
amod(5,pleasure,own).
nmod:at(5,destroyed,pleasure).
were_beguiled(5,poor_creatures,dogs).
destroyed(5,wolves,unguarded_flock).
were_beguiled(5,poor_silly_creatures,dogs).
destroyed_flock_at(5,wolves,their_own_pleasure).
were_easily_beguiled(5,silly_creatures,dogs).
were_easily_beguiled(5,poor_creatures,dogs).
were_beguiled(5,creatures,dogs).
were_easily_beguiled(5,poor_silly_creatures,dogs).
destroyed_flock_at(5,wolves,their_pleasure).
were_beguiled(5,silly_creatures,dogs).
destroyed(5,wolves,flock).
were_easily_beguiled(5,creatures,dogs).
