root(0,ROOT,met).
det(0,man,a).
amod(0,man,wayfaring).
nsubj(0,met,man).
acl(0,man,traveling).
case(0,desert,in).
det(0,desert,the).
nmod:in(0,traveling,desert).
det(0,standing,a).
compound(0,standing,woman).
nsubj(0,alone,standing).
nsubj(0,dejected,standing).
xcomp(0,met,alone).
cc(0,alone,and).
advmod(0,dejected,terribly).
xcomp(0,met,dejected).
conj:and(0,alone,dejected).
met(0,wayfaring_man,woman_standing_alone).
met(0,man,woman_standing_alone).
root(1,ROOT,inquired).
nsubj(1,inquired,he).
case(1,her,of).
nmod:of(1,inquired,her).
inquired_of(1,he,her).
root(2,ROOT,thou).
nsubj(2,thou,who).
cop(2,thou,art).
root(3,ROOT,truth).
nmod:poss(3,name,my).
nsubj(3,truth,name).
cop(3,truth,is).
is(3,my_name,truth).
root(4,ROOT,replied).
nsubj(4,replied,she).
root(5,ROOT,and).
case(5,what,for).
nmod:for(5,and,what).
dep(5,what,cause).
root(6,ROOT,asked).
nsubj(6,asked,he).
root(7,ROOT,have).
nsubj(7,left,you).
ccomp(7,have,left).
det(7,city,the).
dobj(7,left,city).
case(7,dwell,to).
nmod:to(7,left,dwell).
advmod(7,here,alone).
advmod(7,wilderness,here).
case(7,wilderness,in).
det(7,wilderness,the).
nmod:in(7,left,wilderness).
left(7,you,city).
left_city_in(7,you,wilderness).
left_city_to(7,you,dwell).
left_city_in(7,you,alone_here_wilderness).
left_city_in(7,you,here_wilderness).
root(8,ROOT,made).
nsubj(8,made,she).
dobj(8,made,answer).
made(8,she,answer).
root(9,ROOT,few).
mark(9,few,because).
case(9,times,in).
amod(9,times,former).
nmod:in(9,few,times).
nsubj(9,few,falsehood).
cop(9,few,was).
case(9,few,with).
cc(9,few,but).
cop(9,men,is).
advmod(9,men,now).
case(9,men,with).
det(9,men,all).
conj:but(9,few,men).
is_with(9,falsehood,men).
is_with(9,falsehood,now_men).
