root(0,ROOT,tied).
det(0,farmer,a).
nsubj(0,bore,farmer).
nsubj(0,tied,farmer).
ref(0,farmer,who).
acl:relcl(0,farmer,bore).
det(0,grudge,a).
dobj(0,bore,grudge).
case(0,fox,against).
det(0,fox,a).
nmod:against(0,grudge,fox).
mark(0,robbing,for).
advcl:for(0,bore,robbing).
nmod:poss(0,yard,his).
compound(0,yard,poultry).
nsubj(0,caught,yard).
ccomp(0,robbing,caught).
dobj(0,caught,him).
case(0,last,at).
nmod:at(0,caught,last).
cc(0,robbing,and).
auxpass(0,determined,being).
advcl:for(0,bore,determined).
conj:and(0,robbing,determined).
mark(0,take,to).
xcomp(0,determined,take).
det(0,revenge,an).
amod(0,revenge,ample).
dobj(0,take,revenge).
det(0,rope,some).
nsubj(0,soaked,rope).
nsubj(0,set,rope).
advmod(0,soaked,well).
ccomp(0,tied,soaked).
case(0,oil,in).
nmod:in(0,soaked,oil).
case(0,tail,to).
nmod:poss(0,tail,his).
nmod:to(0,soaked,tail).
cc(0,soaked,and).
ccomp(0,tied,set).
conj:and(0,soaked,set).
dobj(0,set,it).
case(0,fire,on).
nmod:on(0,set,fire).
soaked_to(0,rope,his_tail).
well_soaked_to(0,rope,his_tail).
soaked_in(0,rope,oil).
set(0,rope,it).
caught(0,his_poultry_yard,him).
well_soaked_in(0,rope,oil).
root(1,ROOT,rushed).
det(1,fox,the).
nsubj(1,rushed,fox).
case(1,fatality,by).
det(1,fatality,a).
amod(1,fatality,strange).
nmod:by(1,fox,fatality).
case(1,fields,to).
det(1,fields,the).
nmod:to(1,rushed,fields).
case(1,farmer,of).
det(1,farmer,the).
nmod:of(1,fields,farmer).
nsubj(1,captured,farmer).
ref(1,farmer,who).
aux(1,captured,had).
acl:relcl(1,farmer,captured).
dobj(1,captured,him).
rushed_to(1,fox,fields).
root(2,ROOT,time).
nsubj(2,time,it).
cop(2,time,was).
det(2,time,the).
case(2,harvest,of).
det(2,harvest,the).
compound(2,harvest,wheat).
nmod:of(2,time,harvest).
was(2,it,time).
was_time_of(2,it,wheat_harvest).
root(3,ROOT,reaped).
cc(3,reaped,but).
det(3,farmer,the).
nsubj(3,reaped,farmer).
nsubj(3,returned,farmer).
dobj(3,reaped,nothing).
acl:relcl(3,nothing,that).
nmod:tmod(3,reaped,year).
cc(3,reaped,and).
conj:and(3,reaped,returned).
dobj(3,returned,home).
acl(3,home,grieving).
advmod(3,grieving,sorely).
reaped(3,farmer,nothing).
returned(3,farmer,home_grieving).
returned(3,farmer,home_grieving_sorely).
returned(3,farmer,home).
reaped_nothing_at_time(3,farmer,year).
