root(0,ROOT,boasting).
det(0,dove,a).
nsubj(0,boasting,dove).
acl(0,dove,shut).
compound:prt(0,shut,up).
case(0,cage,in).
det(0,cage,a).
nmod:in(0,shut,cage).
aux(0,boasting,was).
case(0,number,of).
det(0,number,the).
amod(0,number,large).
nmod:of(0,boasting,number).
dobj(0,hatched,number).
case(0,ones,of).
amod(0,ones,young).
nmod:of(0,number,ones).
ref(0,number,which).
nsubj(0,hatched,she).
aux(0,hatched,had).
acl:relcl(0,number,hatched).
root(1,ROOT,said).
det(1,crow,a).
nsubj(1,said,crow).
acl(1,crow,hearing).
dobj(1,hearing,her).
root(2,ROOT,friend).
nmod:poss(2,friend,my).
amod(2,friend,good).
dep(2,friend,cease).
case(2,boasting,from).
det(2,boasting,this).
amod(2,boasting,unseasonable).
nmod:from(2,cease,boasting).
root(3,ROOT,number).
det(3,larger,the).
dep(3,number,larger).
det(3,number,the).
case(3,family,of).
nmod:poss(3,family,your).
nmod:of(3,number,family).
det(3,greater,the).
dep(3,cause,greater).
nmod:poss(3,cause,your).
dep(3,number,cause).
case(3,sorrow,of).
nmod:of(3,cause,sorrow).
mark(3,seeing,in).
acl:in(3,number,seeing).
nsubj(3,shut,them).
ccomp(3,seeing,shut).
compound:prt(3,shut,up).
case(3,prison-house,in).
det(3,prison-house,this).
nmod:in(3,shut,prison-house).
shut_up_in(3,them,prison-house).
