root(0,ROOT,seized).
det(0,eagle,an).
nsubj(0,seized,eagle).
nsubj(0,carried,eagle).
acl(0,eagle,flying).
compound:prt(0,flying,down).
case(0,perch,from).
nmod:poss(0,perch,his).
nmod:from(0,flying,perch).
case(0,rock,on).
det(0,rock,a).
amod(0,rock,lofty).
nmod:on(0,flying,rock).
case(0,lamb,upon).
det(0,lamb,a).
nmod:upon(0,seized,lamb).
cc(0,seized,and).
conj:and(0,seized,carried).
dobj(0,carried,him).
advmod(0,talons,aloft).
case(0,talons,in).
nmod:poss(0,talons,his).
nmod:in(0,carried,talons).
carried(0,eagle,him).
seized_upon(0,eagle,lamb).
root(1,ROOT,stirred).
det(1,jackdaw,a).
nsubj(1,witnessed,jackdaw).
nsubjpass(1,stirred,jackdaw).
nsubjpass(1,determined,jackdaw).
nsubj:xsubj(1,emulate,jackdaw).
ref(1,jackdaw,who).
acl:relcl(1,jackdaw,witnessed).
det(1,capture,the).
dobj(1,witnessed,capture).
case(1,lamb,of).
det(1,lamb,the).
nmod:of(1,capture,lamb).
auxpass(1,stirred,was).
case(1,envy,with).
nmod:with(1,stirred,envy).
cc(1,stirred,and).
conj:and(1,stirred,determined).
mark(1,emulate,to).
xcomp(1,determined,emulate).
det(1,strength,the).
dobj(1,emulate,strength).
cc(1,strength,and).
dobj(1,emulate,flight).
conj:and(1,strength,flight).
case(1,eagle,of).
det(1,eagle,the).
nmod:of(1,strength,eagle).
strength_of(1,flight,eagle).
root(2,ROOT,flew).
nsubj(2,flew,he).
nsubj(2,settled,he).
advmod(2,flew,around).
case(2,whir,with).
det(2,whir,a).
amod(2,whir,great).
nmod:with(2,flew,whir).
case(2,wings,of).
nmod:poss(2,wings,his).
nmod:of(2,whir,wings).
cc(2,flew,and).
conj:and(2,flew,settled).
case(2,ram,upon).
det(2,ram,a).
amod(2,ram,large).
nmod:upon(2,settled,ram).
case(2,intention,with).
det(2,intention,the).
nmod:with(2,settled,intention).
mark(2,carrying,of).
acl:of(2,intention,carrying).
dobj(2,carrying,him).
compound:prt(2,carrying,off).
cc(2,flew,but).
nmod:poss(2,claws,his).
nsubj(2,became,claws).
conj:and(2,flew,became).
xcomp(2,became,entangled).
case(2,fleece,in).
det(2,ram,the).
nmod:poss(2,fleece,ram).
case(2,ram,'s).
nmod:in(2,became,fleece).
cc(2,flew,and).
nsubj(2,able,he).
nsubj:xsubj(2,release,he).
cop(2,able,was).
neg(2,able,not).
conj:and(2,flew,able).
mark(2,release,to).
xcomp(2,able,release).
dobj(2,release,himself).
mark(2,fluttered,although).
nsubj(2,fluttered,he).
advcl:although(2,release,fluttered).
case(2,feathers,with).
nmod:poss(2,feathers,his).
nmod:with(2,fluttered,feathers).
advmod(2,much,as).
advmod(2,fluttered,much).
mark(2,could,as).
nsubj(2,could,he).
advcl:as(2,fluttered,could).
became(2,his_claws,entangled).
settled_upon(2,he,large_ram).
settled_upon(2,he,ram).
became_in(2,his_claws,ram_s_fleece).
in(2,ram,fleece).
root(3,ROOT,ran).
det(3,shepherd,the).
nsubj(3,ran,shepherd).
nsubj(3,caught,shepherd).
acl(3,shepherd,seeing).
nsubj(3,happened,what).
aux(3,happened,had).
ccomp(3,seeing,happened).
advmod(3,ran,up).
cc(3,ran,and).
conj:and(3,ran,caught).
dobj(3,caught,him).
caught(3,shepherd,him).
root(4,ROOT,clipped).
nsubj(4,clipped,he).
nsubj(4,taking,he).
case(4,once,at).
advmod(4,clipped,once).
det(4,jackdaw,the).
nmod:poss(4,wings,jackdaw).
case(4,jackdaw,'s).
dobj(4,clipped,wings).
cc(4,clipped,and).
conj:and(4,clipped,taking).
nsubj(4,gave,him).
advmod(4,gave,home).
case(4,night,at).
nmod:at(4,home,night).
ccomp(4,taking,gave).
dobj(4,gave,him).
case(4,children,to).
nmod:poss(4,children,his).
nmod:to(4,gave,children).
once_clipped(4,he,jackdaw_s_wings).
home_gave(4,him,him).
has(4,jackdaw,wings).
clipped(4,he,jackdaw_s_wings).
gave(4,him,him).
root(5,ROOT,their).
case(5,their,on).
amod(5,their,saying).
root(6,ROOT,father).
det(6,kind,what).
nsubj(6,it,kind).
case(6,bird,of).
nmod:of(6,kind,bird).
cop(6,it,is).
dep(6,father,it).
root(7,ROOT,replied).
punct(7,replied,').
nsubj(7,replied,he).
root(8,ROOT,daw).
case(8,knowledge,to).
nmod:poss(8,knowledge,my).
amod(8,knowledge,certain).
nmod:to(8,daw,knowledge).
nsubj(8,daw,he).
cop(8,daw,is).
det(8,daw,a).
is_daw_to(8,he,my_certain_knowledge).
is(8,he,daw).
is_daw_to(8,he,my_knowledge).
root(9,ROOT,like).
cc(9,like,but).
nsubj(9,like,he).
aux(9,like,would).
dobj(9,like,you).
nsubj:xsubj(9,think,you).
mark(9,think,to).
xcomp(9,like,think).
det(9,eagle,an).
dobj(9,think,eagle).
would_like(9,he,you).
think(9,you,eagle).
