root(0,ROOT,swallowed).
det(0,dog,a).
nsubj(0,swallowed,dog).
acl(0,dog,used).
mark(0,eating,to).
advcl:to(0,used,eating).
nsubj(0,saw,eggs).
ccomp(0,eating,saw).
det(0,oyster,an).
dobj(0,saw,oyster).
cc(0,eating,and).
advcl:to(0,used,opening).
conj:and(0,eating,opening).
nmod:poss(0,mouth,his).
dobj(0,opening,mouth).
case(0,extent,to).
nmod:poss(0,extent,its).
amod(0,extent,widest).
nmod:to(0,opening,extent).
dobj(0,swallowed,it).
compound:prt(0,swallowed,down).
case(0,relish,with).
det(0,relish,the).
amod(0,relish,utmost).
nmod:with(0,swallowed,relish).
xcomp(0,swallowed,supposing).
dobj(0,supposing,it).
nsubj:xsubj(0,egg,it).
mark(0,egg,to).
cop(0,egg,be).
det(0,egg,an).
xcomp(0,supposing,egg).
supposing(0,it,egg).
swallowed_down(0,dog,it).
supposing(0,it,it).
saw(0,eggs,oyster).
be(0,it,egg).
root(1,ROOT,suffering).
advmod(1,suffering,soon).
advmod(1,suffering,afterwards).
amod(1,pain,great).
dobj(1,suffering,pain).
case(1,stomach,in).
nmod:poss(1,stomach,his).
nmod:in(1,suffering,stomach).
nsubj(1,said,he).
acl:relcl(1,stomach,said).
root(2,ROOT,deserve).
advmod(2,deserve,i).
det:predet(2,this,all).
nsubj(2,torment,this).
ccomp(2,deserve,torment).
case(2,folly,for).
nmod:poss(2,folly,my).
nmod:for(2,torment,folly).
mark(2,thinking,in).
advcl:in(2,torment,thinking).
mark(2,egg,that).
compound(2,round,everything).
nsubj(2,egg,round).
aux(2,egg,must).
cop(2,egg,be).
det(2,egg,an).
ccomp(2,thinking,egg).
torment(2,this,thinking).
torment_for(2,this,my_folly).
root(3,ROOT,fall).
nsubj(3,act,they).
nsubj(3,fall,they).
ref(3,they,who).
acl:relcl(3,they,act).
case(3,thought,without).
amod(3,thought,sufficient).
nmod:without(3,act,thought).
aux(3,fall,will).
advmod(3,fall,often).
case(3,danger,into).
amod(3,danger,unsuspected).
nmod:into(3,fall,danger).
