root(0,ROOT,prayed).
det(0,crow,a).
nsubj(0,prayed,crow).
nsubj:xsubj(0,apollo,crow).
acl(0,crow,caught).
case(0,snare,in).
det(0,snare,a).
nmod:in(0,caught,snare).
mark(0,apollo,to).
xcomp(0,prayed,apollo).
mark(0,release,to).
xcomp(0,apollo,release).
nsubj(0,making,him).
dep(0,release,making).
det(0,vow,a).
dobj(0,making,vow).
mark(0,offer,to).
acl:to(0,vow,offer).
det(0,frankincense,some).
dobj(0,offer,frankincense).
case(0,shrine,at).
nmod:poss(0,shrine,his).
nmod:at(0,offer,shrine).
prayed(0,crow,apollo).
apollo(0,crow,release).
caught_in(0,crow,snare).
root(1,ROOT,forgot).
cc(1,forgot,but).
advmod(1,forgot,when).
case(1,danger,rescued).
case(1,danger,from).
nmod:poss(1,danger,his).
advcl:from(1,forgot,danger).
nsubj(1,forgot,he).
nmod:poss(1,promise,his).
dobj(1,forgot,promise).
forgot(1,he,his_promise).
root(2,ROOT,caught).
advmod(2,again,shortly).
advmod(2,again,afterwards).
advmod(2,caught,again).
case(2,snare,in).
det(2,snare,a).
nmod:in(2,caught,snare).
nsubj(2,passed,he).
nsubj(2,made,he).
acl:relcl(2,snare,passed).
case(2,apollo,by).
nmod:by(2,passed,apollo).
cc(2,passed,and).
acl:relcl(2,snare,made).
conj:and(2,passed,made).
det(2,promise,the).
amod(2,promise,same).
dobj(2,made,promise).
mark(2,offer,to).
advcl:to(2,made,offer).
dobj(2,offer,frankincense).
case(2,mercury,to).
nmod:to(2,offer,mercury).
made(2,he,same_promise).
made(2,he,promise).
passed_by(2,he,apollo).
root(3,ROOT,mercury).
advmod(3,appeared,soon).
dep(3,mercury,appeared).
cc(3,appeared,and).
dep(3,mercury,said).
conj:and(3,appeared,said).
case(3,him,to).
nmod:to(3,appeared,him).
root(4,ROOT,o).
dep(4,o,thou).
dep(4,thou,most).
amod(4,fellow,base).
dep(4,o,fellow).
root(5,ROOT,believe).
advmod(5,believe,how).
aux(5,believe,can).
nsubj(5,believe,i).
dobj(5,believe,thee).
nsubj(5,hast,who).
nsubj(5,wronged,who).
dep(5,believe,hast).
xcomp(5,hast,disowned).
cc(5,hast,and).
dep(5,believe,wronged).
conj:and(5,hast,wronged).
nmod:poss(5,patron,thy).
amod(5,patron,former).
dobj(5,wronged,patron).
can_believe(5,i,thee).
