root(0,ROOT,saw).
det(0,dogs,some).
nsubj(0,saw,dogs).
acl(0,dogs,famished).
case(0,hunger,with).
nmod:with(0,famished,hunger).
det:qmod(0,cowhides,a).
mwe(0,a,number).
mwe(0,a,of).
dobj(0,saw,cowhides).
acl(0,cowhides,steeping).
case(0,river,in).
det(0,river,a).
nmod:in(0,steeping,river).
famished_with(0,dogs,hunger).
root(1,ROOT,able).
neg(1,able,not).
cop(1,able,being).
mark(1,reach,to).
xcomp(1,able,reach).
dobj(1,reach,them).
nsubj(1,agreed,they).
nsubj:xsubj(1,drink,they).
dep(1,reach,agreed).
mark(1,drink,to).
xcomp(1,agreed,drink).
compound:prt(1,drink,up).
det(1,river,the).
dobj(1,drink,river).
cc(1,agreed,but).
nsubj(1,happened,it).
dep(1,reach,happened).
conj:but(1,agreed,happened).
mark(1,burst,that).
nsubj(1,burst,they).
ccomp(1,happened,burst).
dobj(1,burst,themselves).
case(1,drinking,with).
nmod:with(1,burst,drinking).
advmod(1,reached,long).
mark(1,reached,before).
nsubj(1,reached,they).
advcl:before(1,reach,reached).
det(1,hides,the).
dobj(1,reached,hides).
