root(0,ROOT,soaring).
det(0,eagle,an).
nsubj(0,soaring,eagle).
aux(0,soaring,was).
case(0,air,through).
det(0,air,the).
nmod:through(0,soaring,air).
advmod(0,heard,when).
advmod(0,heard,suddenly).
nsubj(0,heard,it).
nsubj(0,felt,it).
advcl(0,soaring,heard).
det(0,whizz,the).
dobj(0,heard,whizz).
case(0,arrow,of).
det(0,arrow,an).
nmod:of(0,whizz,arrow).
cc(0,heard,and).
advcl(0,soaring,felt).
conj:and(0,heard,felt).
nsubj(0,wounded,itself).
ccomp(0,felt,wounded).
case(0,death,to).
nmod:to(0,wounded,death).
suddenly_heard(0,it,whizz_of_arrow).
was_soaring_through(0,eagle,air).
whizz_of(0,it,arrow).
heard(0,it,whizz_of_arrow).
wounded_to(0,itself,death).
heard(0,it,whizz).
suddenly_heard(0,it,whizz).
root(1,ROOT,fluttered).
dep(1,it,slowly).
dep(1,fluttered,it).
compound:prt(1,fluttered,down).
case(1,earth,to).
det(1,earth,the).
nmod:to(1,fluttered,earth).
case(1,life-blood,with).
nmod:poss(1,life-blood,its).
nmod:with(1,earth,life-blood).
xcomp(1,fluttered,pouring).
compound:prt(1,pouring,out).
case(1,it,of).
nmod:of(1,pouring,it).
is_with(1,earth,its_life-blood).
root(2,ROOT,looking).
compound:prt(2,looking,down).
case(2,arrow,upon).
det(2,arrow,the).
nmod:upon(2,looking,arrow).
nmod:with(2,pierced,arrow).
case(2,which,with).
ref(2,arrow,which).
nsubjpass(2,pierced,it).
aux(2,pierced,had).
auxpass(2,pierced,been).
acl:relcl(2,arrow,pierced).
nsubj(2,found,it).
ccomp(2,pierced,found).
mark(2,feathered,that).
det(2,shaft,the).
nsubj(2,feathered,shaft).
case(2,arrow,of).
det(2,arrow,the).
nmod:of(2,shaft,arrow).
aux(2,feathered,had).
cop(2,feathered,been).
ccomp(2,found,feathered).
case(2,one,with).
nmod:with(2,feathered,one).
case(2,plumes,of).
nmod:poss(2,plumes,its).
amod(2,plumes,own).
nmod:of(2,one,plumes).
been_feathered_with(2,shaft,one_its_own_plumes).
been_feathered_with(2,shaft,one_of_its_plumes).
had(2,it,had_pierced).
been_feathered_with(2,shaft,one_its_plumes).
been(2,shaft,feathered).
been_feathered_with(2,shaft,one_of_its_own_plumes).
root(3,ROOT,alas).
