root(0,ROOT,began).
det(0,dogs,some).
nsubj(0,began,dogs).
nsubj:xsubj(0,tear,dogs).
acl(0,dogs,finding).
det(0,skin,the).
dobj(0,finding,skin).
case(0,lion,of).
det(0,lion,a).
nmod:of(0,skin,lion).
mark(0,tear,to).
xcomp(0,began,tear).
dobj(0,tear,it).
case(0,pieces,in).
nmod:in(0,tear,pieces).
case(0,teeth,with).
nmod:poss(0,teeth,their).
nmod:with(0,pieces,teeth).
skin_of(0,finding,lion).
finding(0,dogs,skin).
tear(0,dogs,it).
finding(0,dogs,skin_of_lion).
is_with(0,pieces,their_teeth).
root(1,ROOT,said).
det(1,fox,a).
nsubj(1,said,fox).
acl(1,fox,seeing).
dobj(1,seeing,them).
root(2,ROOT,alive).
mark(2,alive,if).
det(2,lion,this).
nsubj(2,alive,lion).
cop(2,alive,were).
nsubj(2,find,you).
aux(2,find,would).
advmod(2,find,soon).
ccomp(2,alive,find).
compound:prt(2,find,out).
mark(2,stronger,that).
nmod:poss(2,claws,his).
nsubj(2,stronger,claws).
cop(2,stronger,were).
ccomp(2,find,stronger).
case(2,teeth,than).
nmod:poss(2,teeth,your).
nmod:than(2,stronger,teeth).
were_stronger_than(2,his_claws,your_teeth).
were(2,lion,alive).
were(2,his_claws,stronger).
