root(0,ROOT,ant).
det(0,ant,an).
dep(0,ant,going).
case(0,river,to).
det(0,river,a).
nmod:to(0,going,river).
mark(0,drink,to).
acl:to(0,river,drink).
ccomp(0,drink,fell).
nmod(0,fell,in).
cc(0,fell,and).
auxpass(0,carried,was).
ccomp(0,drink,carried).
conj:and(0,fell,carried).
advmod(0,carried,along).
case(0,stream,in).
det(0,stream,the).
nmod:in(0,carried,stream).
root(1,ROOT,pitied).
nsubj(1,pitied,a).
nsubj(1,threw,a).
amod(1,a,dove).
nmod:poss(1,condition,her).
dobj(1,pitied,condition).
cc(1,pitied,and).
conj:and(1,pitied,threw).
case(1,river,into).
det(1,river,the).
nmod:into(1,threw,river).
det(1,bough,a).
amod(1,bough,small).
dobj(1,pitied,bough).
case(1,means,by).
nmod:by(1,bough,means).
nmod:of(1,gained,means).
case(1,which,of).
ref(1,means,which).
det(1,ant,the).
nsubj(1,gained,ant).
acl:relcl(1,means,gained).
det(1,shore,the).
dobj(1,gained,shore).
threw_into(1,a_dove,river).
pitied(1,a,her_condition).
pitied(1,a,small_bough).
pitied(1,a_dove,her_condition).
pitied(1,a_dove,small_bough).
pitied(1,a_dove,bough).
threw_into(1,a,river).
pitied(1,a,bough).
gained(1,ant,shore).
root(2,ROOT,stung).
det(2,ant,the).
nsubj(2,stung,ant).
nsubj(2,made,ant).
nsubj(2,saved,ant).
advmod(2,seeing,afterward).
acl(2,ant,seeing).
det(2,man,a).
dobj(2,seeing,man).
case(2,fowling-piece,with).
det(2,fowling-piece,a).
nmod:with(2,man,fowling-piece).
acl(2,fowling-piece,aiming).
case(2,the,at).
nmod:at(2,aiming,the).
amod(2,the,dove).
dobj(2,stung,him).
case(2,foot,in).
det(2,foot,the).
nmod:in(2,stung,foot).
advmod(2,stung,sharply).
cc(2,stung,and).
conj:and(2,stung,made).
nsubj(2,miss,him).
ccomp(2,made,miss).
nmod:poss(2,aim,his).
dobj(2,miss,aim).
cc(2,stung,and).
dep(2,and,so).
conj:and(2,stung,saved).
nmod:poss(2,life,the).
amod(2,the,dove).
case(2,the,'s).
dobj(2,saved,life).
is_with(2,man,fowling-piece_aiming_at_the_dove).
seeing(2,ant,man).
afterward_seeing(2,ant,man_with_fowling-piece_aiming_at_the).
saved(2,ant,the_s_life).
stung(2,ant,him).
afterward_seeing(2,ant,man_with_fowling-piece_aiming).
seeing(2,ant,man_with_fowling-piece_aiming_at_the).
saved(2,ant,the_dove_s_life).
has(2,the_dove,life).
afterward_seeing(2,ant,man_with_fowling-piece).
stung_sharply(2,ant,him).
afterward_seeing(2,ant,man).
seeing(2,ant,man_with_fowling-piece_aiming).
seeing(2,ant,man_with_fowling-piece_aiming_at_the_dove).
seeing(2,ant,man_with_fowling-piece).
afterward_seeing(2,ant,man_with_fowling-piece_aiming_at_the_dove).
miss(2,him,his_aim).
