root(0,ROOT,formed).
det(0,eagle,an).
nsubj(0,formed,eagle).
nsubj(0,decided,eagle).
nsubj:xsubj(0,live,eagle).
cc(0,eagle,and).
det(0,fox,a).
conj:and(0,eagle,fox).
nsubj(0,formed,fox).
det(0,friendship,an).
amod(0,friendship,intimate).
dobj(0,formed,friendship).
cc(0,formed,and).
conj:and(0,formed,decided).
mark(0,live,to).
xcomp(0,decided,live).
case(0,other,near).
det(0,other,each).
nmod:near(0,live,other).
formed(0,eagle,friendship).
formed(0,eagle,intimate_friendship).
formed(0,fox,intimate_friendship).
formed(0,fox,friendship).
decided(0,fox,live).
root(1,ROOT,built).
det(1,eagle,the).
nsubj(1,built,eagle).
nmod:poss(1,nest,her).
dobj(1,built,nest).
case(1,branches,in).
det(1,branches,the).
nmod:in(1,built,branches).
case(1,tree,of).
det(1,tree,a).
amod(1,tree,tall).
nmod:of(1,branches,tree).
mark(1,crept,while).
det(1,fox,the).
nsubj(1,crept,fox).
nsubj(1,produced,fox).
advcl:while(1,built,crept).
case(1,underwood,into).
det(1,underwood,the).
nmod:into(1,crept,underwood).
cc(1,crept,and).
advmod(1,produced,there).
advcl:while(1,built,produced).
conj:and(1,crept,produced).
nmod:poss(1,young,her).
dobj(1,produced,young).
crept_into(1,fox,underwood).
produced(1,fox,her_young).
built(1,eagle,her_nest).
there_produced(1,fox,her_young).
root(2,ROOT,long).
dep(2,long,not).
mark(2,agreed,after).
nsubj(2,agreed,they).
aux(2,agreed,had).
dep(2,long,agreed).
case(2,plan,upon).
det(2,plan,this).
nmod:upon(2,agreed,plan).
det(2,eagle,the).
nsubj(2,swooped,eagle).
aux(2,want,being).
advmod(2,want,in).
acl(2,eagle,want).
case(2,provision,of).
nmod:of(2,want,provision).
case(2,ones,for).
nmod:poss(2,ones,her).
amod(2,ones,young).
nmod:for(2,provision,ones).
acl:relcl(2,plan,swooped).
compound:prt(2,swooped,down).
mark(2,seized,while).
det(2,fox,the).
nsubjpass(2,seized,fox).
nsubjpass(2,feasted,fox).
auxpass(2,seized,was).
advmod(2,seized,out).
advcl:while(2,swooped,seized).
case(2,one,upon).
det:qmod(2,cubs,one).
mwe(2,one,of).
det(2,cubs,the).
amod(2,cubs,little).
nmod(2,seized,cubs).
cc(2,seized,and).
advcl:while(2,swooped,feasted).
conj:and(2,seized,feasted).
dobj(2,feasted,herself).
cc(2,plan,and).
nmod:poss(2,brood,her).
nmod:upon(2,agreed,brood).
conj:and(2,plan,brood).
swooped_down(2,eagle,out_seized).
was(2,fox,seized).
feasted(2,fox,herself).
was(2,fox,out_seized).
swooped_down(2,eagle,seized).
root(3,ROOT,discovered).
det(3,fox,the).
nsubj(3,discovered,fox).
nsubj(3,less,fox).
case(3,return,on).
nmod:poss(3,return,her).
nmod:on(3,fox,return).
nsubj(3,happened,what).
aux(3,happened,had).
ccomp(3,discovered,happened).
cc(3,discovered,but).
cop(3,less,was).
conj:but(3,discovered,less).
ccomp(3,less,grieved).
case(3,death,for).
det(3,death,the).
nmod:for(3,grieved,death).
case(3,young,of).
nmod:poss(3,young,her).
nmod:of(3,death,young).
advmod(3,less,than).
case(3,inability,for).
nmod:poss(3,inability,her).
nmod:for(3,than,inability).
mark(3,avenge,to).
acl:to(3,inability,avenge).
dobj(3,avenge,them).
root(4,ROOT,fell).
det(4,retribution,a).
advmod(4,retribution,just).
nsubj(4,fell,retribution).
advmod(4,retribution,however).
advmod(4,fell,quickly).
case(4,eagle,upon).
det(4,eagle,the).
nmod:upon(4,fell,eagle).
fell_upon(4,retribution,eagle).
quickly_fell_upon(4,retribution,eagle).
root(5,ROOT,hovering).
mark(5,hovering,while).
case(5,altar,near).
det(5,altar,an).
nmod:near(5,hovering,altar).
nmod:on(5,sacrificing,altar).
case(5,which,on).
ref(5,altar,which).
det(5,villagers,some).
nsubj(5,sacrificing,villagers).
aux(5,sacrificing,were).
acl:relcl(5,altar,sacrificing).
det(5,goat,a).
dobj(5,sacrificing,goat).
nsubj(5,seized,she).
nsubj(5,carried,she).
advmod(5,seized,suddenly).
acl:relcl(5,goat,seized).
det(5,piece,a).
dobj(5,seized,piece).
case(5,flesh,of).
det(5,flesh,the).
nmod:of(5,piece,flesh).
cc(5,seized,and).
acl:relcl(5,goat,carried).
conj:and(5,seized,carried).
dobj(5,carried,it).
case(5,cinder,along).
mwe(5,along,with).
det(5,cinder,a).
compound(5,cinder,burning).
nmod:along_with(5,carried,cinder).
case(5,nest,to).
nmod:poss(5,nest,her).
nmod:to(5,carried,nest).
piece_of(5,she,flesh).
carried(5,she,it).
seized(5,she,piece_of_flesh).
seized(5,she,piece).
suddenly_seized(5,she,piece).
suddenly_seized(5,she,piece_of_flesh).
root(6,ROOT,fanned).
det(6,breeze,a).
amod(6,breeze,strong).
nsubj(6,fanned,breeze).
nsubj(6,dropped,breeze).
advmod(6,fanned,soon).
dobj(6,fanned,the).
dep(6,the,spark).
case(6,flame,into).
det(6,flame,a).
nmod:into(6,spark,flame).
cc(6,spark,and).
det(6,eaglets,the).
nsubj(6,roasted,eaglets).
case(6,unfledged,as).
advmod(6,unfledged,yet).
acl:as(6,eaglets,unfledged).
cc(6,unfledged,and).
acl:as(6,eaglets,helpless).
conj:and(6,unfledged,helpless).
cop(6,roasted,were).
dep(6,the,roasted).
conj:and(6,spark,roasted).
case(6,nest,in).
nmod:poss(6,nest,their).
nmod:in(6,roasted,nest).
cc(6,fanned,and).
conj:and(6,fanned,dropped).
dep(6,dead,down).
advmod(6,dropped,dead).
case(6,bottom,at).
det(6,bottom,the).
nmod:at(6,dropped,bottom).
case(6,tree,of).
det(6,tree,the).
nmod:of(6,bottom,tree).
dropped_at(6,breeze,bottom).
dropped_dead_at(6,strong_breeze,bottom).
dropped_at(6,breeze,bottom_of_tree).
dropped_at(6,strong_breeze,bottom).
fanned(6,breeze,the).
fanned(6,strong_breeze,the).
soon_fanned(6,strong_breeze,the).
dropped_dead_at(6,breeze,bottom_of_tree).
dropped_dead_at(6,breeze,bottom).
dropped_dead_at(6,strong_breeze,bottom_of_tree).
dropped_at(6,strong_breeze,bottom_of_tree).
soon_fanned(6,breeze,the).
root(7,ROOT,there).
case(7,sight,in).
det(7,sight,the).
nmod:in(7,there,sight).
case(7,eagle,of).
det(7,eagle,the).
nmod:of(7,sight,eagle).
det(7,fox,the).
nsubj(7,gobbled,fox).
acl:relcl(7,eagle,gobbled).
dobj(7,gobbled,them).
compound:prt(7,gobbled,up).
