%% an eagle and a fox formed an intimate friendship and decided to live near each other.
% dependencies.
root(0,root,form).
det(0,eagle,a).
nsubj(0,form,eagle).
nsubj(0,decide,eagle).
nsubj:xsubj(0,live,eagle).
cc(0,eagle,and).
det(0,fox,a).
conj:and(0,eagle,fox).
nsubj(0,form,fox).
det(0,friendship,a).
amod(0,friendship,intimate).
dobj(0,form,friendship).
cc(0,form,and).
conj:and(0,form,decide).
mark(0,live,to).
xcomp(0,decide,live).
case(0,other,near).
det(0,other,each).
nmod:near(0,live,other).
% relations.
aos(0,form,eagle,friendship).
aos(0,form,eagle,intimate_friendship).
aos(0,form,fox,intimate_friendship).
aos(0,form,fox,friendship).
aos(0,decide,fox,live).
%% the eagle built her nest in the branches of a tall tree while the fox crept into the underwood and there produced her young.
% dependencies.
root(1,root,build).
det(1,eagle,the).
nsubj(1,build,eagle).
nmod:poss(1,nest,she).
dobj(1,build,nest).
case(1,branch,in).
det(1,branch,the).
nmod:in(1,build,branch).
case(1,tree,of).
det(1,tree,a).
amod(1,tree,tall).
nmod:of(1,branch,tree).
mark(1,creep,while).
det(1,fox,the).
nsubj(1,creep,fox).
nsubj(1,produce,fox).
advcl:while(1,build,creep).
case(1,underwood,into).
det(1,underwood,the).
nmod:into(1,creep,underwood).
cc(1,creep,and).
advmod(1,produce,there).
advcl:while(1,build,produce).
conj:and(1,creep,produce).
nmod:poss(1,young,she).
dobj(1,produce,young).
% relations.
aos(1,creep_into,fox,underwood).
aos(1,produce,fox,she_young).
aos(1,build,eagle,she_nest).
aos(1,there_produce,fox,she_young).
%% not long after they had agreed upon this plan the eagle being in want of provision for her young ones swooped down while the fox was out seized upon one of the little cubs and feasted herself and her brood.
% dependencies.
root(2,root,long).
dep(2,long,not).
mark(2,agree,after).
nsubj(2,agree,they).
aux(2,agree,have).
dep(2,long,agree).
case(2,plan,upon).
det(2,plan,this).
nmod:upon(2,agree,plan).
det(2,eagle,the).
nsubj(2,swoop,eagle).
aux(2,want,be).
advmod(2,want,in).
acl(2,eagle,want).
case(2,provision,of).
nmod:of(2,want,provision).
case(2,one,for).
nmod:poss(2,one,she).
amod(2,one,young).
nmod:for(2,provision,one).
acl:relcl(2,plan,swoop).
compound:prt(2,swoop,down).
mark(2,seize,while).
det(2,fox,the).
nsubjpass(2,seize,fox).
nsubjpass(2,feast,fox).
auxpass(2,seize,be).
advmod(2,seize,out).
advcl:while(2,swoop,seize).
case(2,one,upon).
det:qmod(2,cub,one).
mwe(2,one,of).
det(2,cub,the).
amod(2,cub,little).
nmod(2,seize,cub).
cc(2,seize,and).
advcl:while(2,swoop,feast).
conj:and(2,seize,feast).
dobj(2,feast,herself).
cc(2,plan,and).
nmod:poss(2,brood,she).
nmod:upon(2,agree,brood).
conj:and(2,plan,brood).
% relations.
aos(2,swoop_down,eagle,out_seize).
aos(2,be,fox,seize).
aos(2,feast,fox,herself).
aos(2,be,fox,out_seize).
aos(2,swoop_down,eagle,seize).
%% the fox on her return discovered what had happened but was less grieved for the death of her young than for her inability to avenge them.
% dependencies.
root(3,root,discover).
det(3,fox,the).
nsubj(3,discover,fox).
nsubj(3,less,fox).
case(3,return,on).
nmod:poss(3,return,she).
nmod:on(3,fox,return).
nsubj(3,happen,what).
aux(3,happen,have).
ccomp(3,discover,happen).
cc(3,discover,but).
cop(3,less,be).
conj:but(3,discover,less).
ccomp(3,less,grieve).
case(3,death,for).
det(3,death,the).
nmod:for(3,grieve,death).
case(3,young,of).
nmod:poss(3,young,she).
nmod:of(3,death,young).
advmod(3,less,than).
case(3,inability,for).
nmod:poss(3,inability,she).
nmod:for(3,than,inability).
mark(3,avenge,to).
acl:to(3,inability,avenge).
dobj(3,avenge,they).
% relations.
%% a just retribution however quickly fell upon the eagle.
% dependencies.
root(4,root,fall).
det(4,retribution,a).
advmod(4,retribution,just).
nsubj(4,fall,retribution).
advmod(4,retribution,however).
advmod(4,fall,quickly).
case(4,eagle,upon).
det(4,eagle,the).
nmod:upon(4,fall,eagle).
% relations.
aos(4,fall_upon,retribution,eagle).
aos(4,quickly_fall_upon,retribution,eagle).
%% while hovering near an altar on which some villagers were sacrificing a goat she suddenly seized a piece of the flesh and carried it along with a burning cinder to her nest.
% dependencies.
root(5,root,hover).
mark(5,hover,while).
case(5,altar,near).
det(5,altar,a).
nmod:near(5,hover,altar).
nmod:on(5,sacrifice,altar).
case(5,which,on).
ref(5,altar,which).
det(5,villager,some).
nsubj(5,sacrifice,villager).
aux(5,sacrifice,be).
acl:relcl(5,altar,sacrifice).
det(5,goat,a).
dobj(5,sacrifice,goat).
nsubj(5,seize,she).
nsubj(5,carry,she).
advmod(5,seize,suddenly).
acl:relcl(5,goat,seize).
det(5,piece,a).
dobj(5,seize,piece).
case(5,flesh,of).
det(5,flesh,the).
nmod:of(5,piece,flesh).
cc(5,seize,and).
acl:relcl(5,goat,carry).
conj:and(5,seize,carry).
dobj(5,carry,it).
case(5,cinder,along).
mwe(5,along,with).
det(5,cinder,a).
compound(5,cinder,burning).
nmod:along_with(5,carry,cinder).
case(5,nest,to).
nmod:poss(5,nest,she).
nmod:to(5,carry,nest).
% relations.
aos(5,piece_of,she,flesh).
aos(5,carry,she,it).
aos(5,seize,she,piece_of_flesh).
aos(5,seize,she,piece).
aos(5,suddenly_seize,she,piece).
aos(5,suddenly_seize,she,piece_of_flesh).
%% a strong breeze soon fanned the spark into a flame and the eaglets as yet unfledged and helpless were roasted in their nest and dropped down dead at the bottom of the tree.
% dependencies.
root(6,root,fan).
det(6,breeze,a).
amod(6,breeze,strong).
nsubj(6,fan,breeze).
nsubj(6,drop,breeze).
advmod(6,fan,soon).
dobj(6,fan,the).
dep(6,the,spark).
case(6,flame,into).
det(6,flame,a).
nmod:into(6,spark,flame).
cc(6,spark,and).
det(6,eaglet,the).
nsubj(6,roasted,eaglet).
case(6,unfledged,as).
advmod(6,unfledged,yet).
acl:as(6,eaglet,unfledged).
cc(6,unfledged,and).
acl:as(6,eaglet,helpless).
conj:and(6,unfledged,helpless).
cop(6,roasted,be).
dep(6,the,roasted).
conj:and(6,spark,roasted).
case(6,nest,in).
nmod:poss(6,nest,they).
nmod:in(6,roasted,nest).
cc(6,fan,and).
conj:and(6,fan,drop).
dep(6,dead,down).
advmod(6,drop,dead).
case(6,bottom,at).
det(6,bottom,the).
nmod:at(6,drop,bottom).
case(6,tree,of).
det(6,tree,the).
nmod:of(6,bottom,tree).
% relations.
aos(6,drop_at,breeze,bottom).
aos(6,drop_dead_at,strong_breeze,bottom).
aos(6,drop_at,breeze,bottom_of_tree).
aos(6,drop_at,strong_breeze,bottom).
aos(6,fan,breeze,the).
aos(6,fan,strong_breeze,the).
aos(6,soon_fan,strong_breeze,the).
aos(6,drop_dead_at,breeze,bottom_of_tree).
aos(6,drop_dead_at,breeze,bottom).
aos(6,drop_dead_at,strong_breeze,bottom_of_tree).
aos(6,drop_at,strong_breeze,bottom_of_tree).
aos(6,soon_fan,breeze,the).
%% there in the sight of the eagle the fox gobbled them up.
% dependencies.
root(7,root,there).
case(7,sight,in).
det(7,sight,the).
nmod:in(7,there,sight).
case(7,eagle,of).
det(7,eagle,the).
nmod:of(7,sight,eagle).
det(7,fox,the).
nsubj(7,gobble,fox).
acl:relcl(7,eagle,gobble).
dobj(7,gobble,they).
compound:prt(7,gobble,up).
% relations.
