root(0,ROOT,placed).
det(0,farmer,a).
nsubj(0,placed,farmer).
nsubj(0,caught,farmer).
dobj(0,placed,nets).
case(0,plowlands,on).
nmod:poss(0,plowlands,his).
amod(0,plowlands,newly-sown).
nmod:on(0,placed,plowlands).
cc(0,placed,and).
conj:and(0,placed,caught).
det:qmod(0,cranes,a).
mwe(0,a,number).
mwe(0,a,of).
dobj(0,caught,cranes).
nsubj(0,came,cranes).
nsubj:xsubj(0,pick,cranes).
ref(0,cranes,which).
acl:relcl(0,cranes,came).
mark(0,pick,to).
xcomp(0,came,pick).
compound:prt(0,pick,up).
nmod:poss(0,seed,his).
dobj(0,pick,seed).
placed_nets_on(0,farmer,his_plowlands).
placed(0,farmer,nets).
placed_nets_on(0,farmer,his_newly-sown_plowlands).
root(1,ROOT,trapped).
case(1,them,with).
nmod:with(1,trapped,them).
nsubj(1,trapped,he).
nsubj(1,beseeching,he).
det(1,stork,a).
dobj(1,trapped,stork).
nsubj(1,fractured,stork).
ref(1,stork,that).
aux(1,fractured,had).
acl:relcl(1,stork,fractured).
nmod:poss(1,leg,his).
dobj(1,fractured,leg).
case(1,net,in).
det(1,net,the).
nmod:in(1,fractured,net).
cc(1,trapped,and).
aux(1,beseeching,was).
advmod(1,beseeching,earnestly).
conj:and(1,trapped,beseeching).
det(1,farmer,the).
dobj(1,beseeching,farmer).
mark(1,spare,to).
acl:to(1,farmer,spare).
nmod:poss(1,life,his).
dobj(1,spare,life).
root(2,ROOT,pray).
xcomp(2,pray,save).
iobj(2,save,me).
dobj(2,save,master).
root(3,ROOT,said).
nsubj(3,said,he).
root(4,ROOT,let).
cc(4,let,and).
nsubj(4,go,me).
ccomp(4,let,go).
xcomp(4,go,free).
det(4,once,this).
dep(4,free,once).
go(4,me,free).
root(5,ROOT,excite).
nmod:poss(5,limb,my).
amod(5,limb,broken).
nsubj(5,excite,limb).
aux(5,excite,should).
nmod:poss(5,pity,your).
dobj(5,excite,pity).
should_excite(5,my_broken_limb,your_pity).
should_excite(5,my_limb,your_pity).
root(6,ROOT,crane).
case(6,i,besides).
nmod:besides(6,crane,i).
cop(6,crane,am).
neg(6,crane,no).
nsubj(6,stork,i).
cop(6,stork,am).
det(6,stork,a).
ccomp(6,crane,stork).
det(6,bird,a).
nsubj(6,crane,bird).
case(6,character,of).
amod(6,character,excellent).
nmod:of(6,bird,character).
root(7,ROOT,see).
cc(7,see,and).
dobj(7,see,how).
nmod(7,see,i).
dep(7,i,love).
cc(7,love,and).
dep(7,i,slave).
conj:and(7,love,slave).
case(7,father,for).
nmod:poss(7,father,my).
nmod:for(7,love,father).
cc(7,father,and).
nmod:for(7,love,mother).
conj:and(7,father,mother).
root(8,ROOT,look).
advmod(8,feathers,too).
case(8,feathers,at).
nmod:poss(8,feathers,my).
nmod:at(8,look,feathers).
punct(8,look,--).
nsubj(8,least,they).
cop(8,least,are).
neg(8,least,not).
det(8,least,the).
ccomp(8,look,least).
case(8,those,like).
nmod:like(8,least,those).
case(8,crane,of).
det(8,crane,a).
nmod:of(8,those,crane).
root(9,ROOT,laughed).
det(9,farmer,the).
nsubj(9,laughed,farmer).
nsubj(9,said,farmer).
advmod(9,laughed,aloud).
cc(9,laughed,and).
conj:and(9,laughed,said).
root(10,ROOT,all).
nsubj(10,all,it).
aux(10,all,may).
cop(10,all,be).
mark(10,say,as).
nsubj(10,say,you).
advcl:as(10,all,say).
nsubj(10,know,i).
advmod(10,know,only).
dep(10,say,know).
det(10,i,this).
nsubj(10,taken,i).
aux(10,taken,have).
ccomp(10,know,taken).
dobj(10,taken,you).
case(10,robbers,with).
det(10,robbers,these).
nmod:with(10,taken,robbers).
det(10,cranes,the).
dep(10,robbers,cranes).
cc(10,know,and).
nsubj(10,die,you).
aux(10,die,must).
dep(10,say,die).
conj:and(10,know,die).
case(10,company,in).
nmod:poss(10,company,their).
nmod:in(10,die,company).
must_die_in(10,you,their_company).
may(10,it,may_all).
taken(10,i,you).
