root(0,ROOT,sought).
det(0,doe,a).
nsubj(0,sought,doe).
advmod(0,pressed,hard).
acl(0,doe,pressed).
case(0,hunters,by).
nmod:by(0,pressed,hunters).
dobj(0,sought,refuge).
case(0,cave,in).
det(0,cave,a).
nmod:in(0,sought,cave).
acl(0,cave,belonging).
case(0,lion,to).
det(0,lion,a).
nmod:to(0,belonging,lion).
sought_refuge_in(0,doe,cave_belonging_to_lion).
hard_pressed_by(0,doe,hunters).
sought_refuge_in(0,doe,cave).
sought_refuge_in(0,doe,cave_belonging).
sought(0,doe,refuge).
pressed_by(0,doe,hunters).
root(1,ROOT,concealed).
det(1,lion,the).
nsubj(1,concealed,lion).
dobj(1,concealed,himself).
mark(1,seeing,on).
advcl:on(1,concealed,seeing).
nmod:poss(1,approach,her).
dobj(1,seeing,approach).
cc(1,safe,but).
advmod(1,safe,when).
nsubj(1,safe,she).
cop(1,safe,was).
parataxis(1,concealed,safe).
case(1,cave,within).
det(1,cave,the).
nmod:within(1,concealed,cave).
acl:relcl(1,cave,sprang).
case(1,her,upon).
nmod:upon(1,sprang,her).
cc(1,sprang,and).
acl:relcl(1,cave,tore).
conj:and(1,sprang,tore).
dobj(1,tore,her).
case(1,pieces,to).
nmod:to(1,tore,pieces).
was(1,she,when_safe).
was(1,she,safe).
seeing(1,lion,her_approach).
root(2,ROOT,me).
nsubj(2,me,woe).
cop(2,me,is).
is(2,woe,me).
root(3,ROOT,exclaimed).
det(3,doe,the).
nsubj(3,exclaimed,doe).
root(4,ROOT,escaped).
nsubj(4,escaped,who).
nsubj:xsubj(4,throw,who).
aux(4,escaped,have).
case(4,man,from).
nmod:from(4,escaped,man).
advmod(4,man,only).
mark(4,throw,to).
xcomp(4,escaped,throw).
dobj(4,throw,myself).
case(4,mouth,into).
det(4,mouth,the).
nmod:into(4,throw,mouth).
case(4,beast,of).
det(4,beast,a).
amod(4,beast,wild).
nmod:of(4,mouth,beast).
root(5,ROOT,another).
punct(5,another,').
