root(0,ROOT,jumped).
det(0,dog,a).
nsubj(0,jumped,dog).
nsubj(0,lay,dog).
acl(0,dog,looking).
compound:prt(0,looking,out).
case(0,nap,for).
nmod:poss(0,nap,its).
compound(0,nap,afternoon).
nmod:for(0,looking,nap).
case(0,manger,into).
det(0,manger,the).
nmod:into(0,jumped,manger).
case(0,ox,of).
det(0,ox,an).
nmod:of(0,manger,ox).
cc(0,jumped,and).
conj:and(0,jumped,lay).
expl(0,cosily,there).
xcomp(0,lay,cosily).
case(0,straw,upon).
det(0,straw,the).
nmod:upon(0,cosily,straw).
cosily_upon(0,lay,straw).
lay(0,dog,cosily_upon_straw).
jumped_into(0,dog,manger_of_ox).
jumped_into(0,dog,manger).
lay(0,dog,cosily).
root(1,ROOT,came).
cc(1,came,but).
advmod(1,came,soon).
det(1,ox,the).
nsubj(1,came,ox).
nsubj(1,wanted,ox).
nsubj:xsubj(1,eat,ox).
acl(1,ox,returning).
case(1,work,from).
nmod:poss(1,work,its).
compound(1,work,afternoon).
nmod:from(1,returning,work).
compound:prt(1,came,up).
case(1,manger,to).
det(1,manger,the).
nmod:to(1,came,manger).
cc(1,came,and).
conj:and(1,came,wanted).
mark(1,eat,to).
xcomp(1,wanted,eat).
det:qmod(1,straw,some).
mwe(1,some,of).
det(1,straw,the).
dobj(1,eat,straw).
returning_from(1,ox,its_afternoon_work).
soon_came_up_to(1,ox,manger).
came_up_to(1,ox,manger).
root(2,ROOT,dog).
det(2,dog,the).
case(2,rage,in).
det(2,rage,a).
nmod:in(2,dog,rage).
auxpass(2,awakened,being).
acl(2,rage,awakened).
case(2,slumber,from).
nmod:poss(2,slumber,its).
nmod:from(2,awakened,slumber).
dep(2,awakened,stood).
advmod(2,stood,up).
cc(2,stood,and).
dep(2,awakened,barked).
conj:and(2,stood,barked).
case(2,ox,at).
det(2,ox,the).
nmod:at(2,barked,ox).
cc(2,stood,and).
advmod(2,came,whenever).
nsubj(2,came,it).
dep(2,awakened,came).
conj:and(2,stood,came).
mark(2,attempted,near).
advcl:near(2,came,attempted).
mark(2,bite,to).
xcomp(2,attempted,bite).
dobj(2,bite,it).
is_in(2,dog,rage_awakened_from_its_slumber).
came(2,it,attempted).
root(3,ROOT,had).
case(3,last,at).
nmod:at(3,had,last).
det(3,ox,the).
nsubj(3,had,ox).
nsubj:xsubj(3,give,ox).
nsubj(3,went,ox).
mark(3,give,to).
xcomp(3,had,give).
compound:prt(3,give,up).
det(3,hope,the).
dobj(3,give,hope).
mark(3,getting,of).
acl:of(3,hope,getting).
case(3,straw,at).
det(3,straw,the).
nmod:at(3,getting,straw).
cc(3,had,and).
conj:and(3,had,went).
advmod(3,went,away).
xcomp(3,went,muttering).
give_up(3,ox,hope_getting_at_straw).
had_at(3,ox,last).
went(3,ox,muttering).
went_away(3,ox,muttering).
give_up(3,ox,hope_getting).
root(4,ROOT,grudge).
advmod(4,grudge,ah).
nmod:npmod(4,often,people).
advmod(4,grudge,often).
dobj(4,grudge,others).
dobj(4,enjoy,what).
nsubj(4,enjoy,they).
aux(4,enjoy,can).
neg(4,enjoy,not).
dep(4,grudge,enjoy).
dobj(4,enjoy,themselves).
