root(0,ROOT,strutting).
det(0,cock,a).
nsubj(0,strutting,cock).
aux(0,strutting,was).
advmod(0,strutting,once).
compound:prt(0,strutting,up).
cc(0,up,and).
dep(0,up,down).
det(0,farmyard,the).
dobj(0,strutting,farmyard).
case(0,hens,among).
det(0,hens,the).
nmod:among(0,strutting,hens).
advmod(0,espied,when).
advmod(0,espied,suddenly).
nsubj(0,espied,he).
acl:relcl(0,hens,espied).
dobj(0,espied,something).
acl(0,something,shinning).
case(0,straw,amid).
det(0,straw,the).
nmod:amid(0,shinning,straw).
was_strutting_up(0,cock,farmyard).
suddenly_espied(0,he,something).
espied(0,he,something).
espied(0,he,something_shinning).
suddenly_espied(0,he,something_shinning).
suddenly_espied(0,he,something_shinning_amid_straw).
espied(0,he,something_shinning_amid_straw).
was_once_strutting_up(0,cock,farmyard).
root(1,ROOT,ho).
root(2,ROOT,ho).
root(3,ROOT,he).
case(3,he,quoth).
root(4,ROOT,me).
nsubj(4,me,that).
cop(4,me,'s).
case(4,me,for).
s_for(4,that,me).
root(5,ROOT,soon).
cc(5,soon,and).
dep(5,soon,rooted).
dobj(5,rooted,it).
compound:prt(5,rooted,out).
case(5,straw,from).
case(5,straw,beneath).
det(5,straw,the).
nmod:beneath(5,rooted,straw).
root(6,ROOT,turn).
dep(6,turn,what).
aux(6,turn,did).
nsubj(6,turn,it).
nsubj:xsubj(6,pearl,it).
compound:prt(6,turn,out).
mark(6,pearl,to).
cop(6,pearl,be).
case(6,pearl,but).
det(6,pearl,a).
xcomp(6,turn,pearl).
nsubjpass(6,lost,pearl).
ref(6,pearl,that).
case(6,chance,by).
det(6,chance,some).
nmod:agent(6,lost,chance).
aux(6,lost,had).
auxpass(6,lost,been).
acl:relcl(6,pearl,lost).
case(6,yard,in).
det(6,yard,the).
nmod:in(6,lost,yard).
root(7,ROOT,treasure).
nsubj(7,treasure,you).
aux(7,treasure,may).
cop(7,treasure,be).
det(7,treasure,a).
may(7,you,may_treasure).
root(8,ROOT,quoth).
compound(8,cock,master).
dep(8,quoth,cock).
root(9,ROOT,peck).
case(9,men,to).
nmod:to(9,peck,men).
dep(9,peck,that).
dep(9,have,prize).
dep(9,prize,you).
cc(9,prize,but).
case(9,me,for).
conj:but(9,prize,me).
dep(9,have,me).
nsubj(9,have,i).
aux(9,have,would).
advmod(9,have,rather).
csubj(9,peck,have).
det(9,barley-corn,a).
amod(9,barley-corn,single).
iobj(9,have,barley-corn).
advmod(9,a,than).
dobj(9,have,a).
case(9,pearls,of).
nmod:of(9,peck,pearls).
would_have(9,i,single_barley-corn).
would_have(9,i,a).
would_rather_have(9,i,barley-corn).
would_rather_have(9,i,a).
would_have(9,i,than_a).
would_have(9,i,barley-corn).
would_rather_have(9,i,single_barley-corn).
would_rather_have(9,i,than_a).
