root(0,ROOT,jealous).
det(0,crow,a).
nsubj(0,jealous,crow).
cop(0,jealous,was).
case(0,raven,of).
det(0,raven,the).
nmod:of(0,jealous,raven).
mark(0,considered,because).
nsubjpass(0,considered,he).
nsubjpass(0,attracted,he).
auxpass(0,considered,was).
advcl:because(0,jealous,considered).
det(0,bird,a).
dobj(0,considered,bird).
case(0,omen,of).
amod(0,omen,good).
nmod:of(0,bird,omen).
cc(0,considered,and).
advmod(0,attracted,always).
advcl:because(0,jealous,attracted).
conj:and(0,considered,attracted).
det(0,attention,the).
dobj(0,attracted,attention).
case(0,men,of).
nmod:of(0,attention,men).
nsubj(0,noted,men).
ref(0,men,who).
acl:relcl(0,men,noted).
case(0,flight,by).
nmod:poss(0,flight,his).
nmod:by(0,noted,flight).
det(0,course,the).
amod(0,course,good).
cc(0,good,or).
conj:or(0,good,evil).
amod(0,course,evil).
dobj(0,considered,course).
case(0,events,of).
amod(0,events,future).
nmod:of(0,course,events).
was_considered(0,he,good_course_of_future_events).
was_considered(0,he,course).
was_considered(0,he,bird).
was(0,he,considered).
was(0,crow,jealous).
was_considered(0,he,bird_of_good_omen).
was_considered(0,he,course_of_future_events).
bird_of(0,he,good_omen).
bird_of(0,he,omen).
always_attracted(0,he,attention).
good_course_of(0,he,future_events).
good_or_evil_course_of(0,bird,future_events).
was_considered(0,he,good_course).
was_jealous(0,crow,considered).
attracted(0,he,attention).
was_considered(0,he,bird_of_omen).
course_of(0,he,future_events).
course_of(0,bird,future_events).
good_or_evil_course_of(0,he,future_events).
was_jealous_of(0,crow,raven).
good_course_of(0,bird,future_events).
root(1,ROOT,seeing).
det(1,travelers,some).
dobj(1,seeing,travelers).
advcl(1,seeing,approaching).
det(1,crow,the).
nsubj(1,flew,crow).
ccomp(1,approaching,flew).
advmod(1,flew,up).
case(1,tree,into).
det(1,tree,a).
nmod:into(1,flew,tree).
cc(1,seeing,and).
conj:and(1,seeing,perching).
dobj(1,perching,herself).
case(1,one,on).
det:qmod(1,branches,one).
mwe(1,one,of).
det(1,branches,the).
nmod(1,perching,branches).
acl:relcl(1,branches,cawed).
case(1,loudly,as).
advmod(1,cawed,loudly).
mark(1,could,as).
nsubj(1,could,she).
advcl:as(1,cawed,could).
flew_into(1,crow,tree).
flew_up_into(1,crow,tree).
perching(1,travelers,herself).
root(2,ROOT,turned).
det(2,travelers,the).
nsubj(2,turned,travelers).
nsubj(2,wondered,travelers).
case(2,sound,towards).
det(2,sound,the).
nmod:towards(2,turned,sound).
cc(2,turned,and).
conj:and(2,turned,wondered).
dobj(2,foreboded,what).
nsubj(2,foreboded,it).
ccomp(2,wondered,foreboded).
advmod(2,said,when).
det:qmod(2,them,one).
mwe(2,one,of).
nsubj(2,said,them).
advcl(2,foreboded,said).
case(2,companion,to).
nmod:poss(2,companion,his).
nmod:to(2,said,companion).
turned_towards(2,travelers,sound).
root(3,ROOT,let).
nsubj(3,proceed,us).
ccomp(3,let,proceed).
case(3,journey,on).
nmod:poss(3,journey,our).
nmod:on(3,proceed,journey).
nmod:poss(3,friend,my).
nsubj(3,let,friend).
mark(3,caw,for).
nsubj(3,caw,it).
cop(3,caw,is).
advmod(3,caw,only).
det(3,caw,the).
dep(3,friend,caw).
case(3,crow,of).
det(3,crow,a).
nmod:of(3,caw,crow).
cc(3,crow,and).
nmod:poss(3,cry,her).
nmod:of(3,caw,cry).
conj:and(3,crow,cry).
nsubj(3,know,you).
acl:relcl(3,caw,know).
cop(3,omen,is).
neg(3,omen,no).
ccomp(3,know,omen).
root(4,ROOT,make).
nsubj(4,assume,those).
nsubj(4,make,those).
ref(4,those,who).
acl:relcl(4,those,assume).
det(4,character,a).
dobj(4,assume,character).
nsubj(4,belong,character).
ref(4,character,which).
aux(4,belong,does).
neg(4,belong,not).
acl:relcl(4,character,belong).
case(4,them,to).
nmod:to(4,belong,them).
advmod(4,belong,only).
nsubj(4,ridiculous,themselves).
xcomp(4,make,ridiculous).
