root(0,ROOT,chose).
det(0,crab,a).
nsubj(0,chose,crab).
acl(0,crab,forsaking).
det(0,seashore,the).
dobj(0,forsaking,seashore).
det(0,meadow,a).
amod(0,meadow,neighboring).
amod(0,meadow,green).
dobj(0,chose,meadow).
case(0,ground,as).
nmod:poss(0,ground,its).
compound(0,ground,feeding).
nmod:as(0,meadow,ground).
chose(0,crab,neighboring_meadow).
chose(0,crab,green_meadow_as_its_feeding_ground).
chose(0,crab,meadow).
chose(0,crab,neighboring_green_meadow).
chose(0,crab,meadow_as_its_feeding_ground).
chose(0,crab,green_meadow).
chose(0,crab,neighboring_meadow_as_its_feeding_ground).
chose(0,crab,neighboring_green_meadow_as_its_feeding_ground).
forsaking(0,crab,seashore).
root(1,ROOT,came).
det(1,fox,a).
nsubj(1,came,fox).
case(1,him,across).
nmod:across(1,came,him).
cc(1,came,and).
cop(1,hungry,being).
advmod(1,hungry,very).
csubj(1,ate,hungry).
conj:and(1,came,ate).
dobj(1,ate,him).
compound:prt(1,ate,up).
came_across(1,fox,him).
ate_up(1,hungry,him).
root(2,ROOT,just).
mark(2,point,as).
nsubj(2,point,he).
cop(2,point,was).
case(2,point,on).
det(2,point,the).
dep(2,just,point).
mark(2,eaten,of).
auxpass(2,eaten,being).
acl:of(2,point,eaten).
det(2,crab,the).
nsubj(2,said,crab).
ccomp(2,eaten,said).
was_on(2,he,point_eaten).
root(3,ROOT,deserve).
dep(3,well,i).
cc(3,deserve,well).
nmod:poss(3,fate,my).
dobj(3,deserve,fate).
mark(3,had,for).
dobj(3,had,what).
nsubj(3,had,business).
advcl:for(3,deserve,had).
dobj(3,had,i).
case(3,land,on).
det(3,land,the).
nmod:on(3,i,land).
advmod(3,adapted,when).
case(3,nature,by).
nmod:poss(3,nature,my).
nmod:agent(3,adapted,nature).
cc(3,nature,and).
conj:and(3,nature,habits).
nmod:agent(3,adapted,habits).
nsubjpass(3,adapted,i).
auxpass(3,adapted,am).
advmod(3,adapted,only).
advcl(3,deserve,adapted).
case(3,sea,for).
det(3,sea,the).
nmod:for(3,adapted,sea).
am(3,i,when_by_my_nature_adapted_for_sea).
had(3,business,i_on_land).
am(3,i,adapted).
am(3,i,when_by_my_nature_adapted).
am(3,i,by_my_nature_only_adapted_for_sea).
am(3,i,when_by_my_nature_only_adapted).
am(3,i,only_adapted).
had(3,business,i).
am(3,i,by_my_nature_adapted_for_sea).
am_only_adapted_for(3,i,sea).
am(3,i,when_by_my_nature_only_adapted_for_sea).
am(3,i,when_adapted_for_sea).
am(3,i,when_adapted).
am(3,i,when_only_adapted).
am_adapted_for(3,i,sea).
am_only_adapted_by(3,i,my_nature).
am_adapted_by(3,i,my_nature).
am(3,i,when_only_adapted_for_sea).
