root(0,ROOT,found).
nummod(0,winter,one).
nsubj(0,found,winter).
nsubj(0,frozen,winter).
det(0,farmer,a).
dep(0,winter,farmer).
det(0,stiff,a).
compound(0,stiff,snake).
dobj(0,found,stiff).
cc(0,found,and).
conj:and(0,found,frozen).
case(0,cold,with).
nmod:with(0,frozen,cold).
root(1,ROOT,had).
nsubj(1,had,he).
dobj(1,had,compassion).
case(1,it,on).
nmod:on(1,compassion,it).
cc(1,it,and).
nmod:on(1,compassion,taking).
conj:and(1,it,taking).
dobj(1,taking,it).
compound:prt(1,taking,up).
acl(1,compassion,placed).
dobj(1,placed,it).
case(1,bosom,in).
nmod:poss(1,bosom,his).
nmod:in(1,placed,bosom).
had(1,he,compassion).
had(1,he,compassion_on_it).
root(2,ROOT,bit).
det(2,snake,the).
nsubjpass(2,revived,snake).
nsubjpass(2,resuming,snake).
auxpass(2,revived,was).
advmod(2,revived,quickly).
dep(2,bit,revived).
case(2,warmth,by).
det(2,warmth,the).
nmod:agent(2,revived,warmth).
cc(2,revived,and).
conj:and(2,revived,resuming).
dep(2,bit,resuming).
nmod:poss(2,instincts,its).
amod(2,instincts,natural).
dobj(2,resuming,instincts).
nmod:poss(2,benefactor,its).
dobj(2,bit,benefactor).
xcomp(2,bit,inflicting).
case(2,him,on).
nmod:on(2,inflicting,him).
det(2,wound,a).
amod(2,wound,mortal).
nsubj(2,bit,wound).
resuming(2,snake,its_natural_instincts).
bit(2,mortal_wound,its_benefactor).
inflicting_on(2,its_benefactor,him).
resuming(2,snake,its_instincts).
bit(2,wound,its_benefactor).
root(3,ROOT,oh).
root(4,ROOT,cried).
det(4,farmer,the).
nsubj(4,cried,farmer).
case(4,breath,with).
nmod:poss(4,breath,his).
amod(4,breath,last).
nmod:with(4,farmer,breath).
is_with(4,farmer,his_last_breath).
root(5,ROOT,served).
nsubjpass(5,served,i).
auxpass(5,served,am).
advmod(5,served,rightly).
mark(5,pitying,for).
advcl:for(5,served,pitying).
det(5,scoundrel,a).
dobj(5,pitying,scoundrel).
pitying(5,i,scoundrel).
am(5,i,served).
am(5,i,rightly_served).
