root(0,ROOT,happened).
nsubj(0,happened,it).
nsubj(0,carrying,it).
mark(0,got,that).
det(0,dog,a).
nsubj(0,got,dog).
aux(0,got,had).
ccomp(0,happened,got).
det(0,piece,a).
dobj(0,got,piece).
case(0,meat,of).
nmod:of(0,piece,meat).
cc(0,happened,and).
aux(0,carrying,was).
conj:and(0,happened,carrying).
dobj(0,carrying,it).
advmod(0,carrying,home).
case(0,mouth,in).
nmod:poss(0,mouth,his).
nmod:in(0,carrying,mouth).
mark(0,eat,to).
acl:to(0,mouth,eat).
dobj(0,eat,it).
case(0,peace,in).
nmod:in(0,eat,peace).
got(0,dog,piece).
carrying_home(0,it,it).
piece_of(0,dog,meat).
got(0,dog,piece_of_meat).
carrying(0,it,it).
root(1,ROOT,had).
advmod(1,home,now).
case(1,home,on).
nmod:poss(1,home,his).
compound(1,home,way).
nmod:on(1,had,home).
nsubj(1,had,he).
nsubj:xsubj(1,cross,he).
mark(1,cross,to).
xcomp(1,had,cross).
det(1,plank,a).
dobj(1,cross,plank).
acl(1,plank,lying).
case(1,brook,across).
det(1,brook,a).
amod(1,brook,running).
nmod:across(1,lying,brook).
cross(1,he,plank_lying_across_running_brook).
had_on(1,he,now_his_way_home).
cross(1,he,plank_lying).
cross(1,he,plank).
had_on(1,he,his_way_home).
cross(1,he,plank_lying_across_brook).
root(2,ROOT,crossed).
mark(2,crossed,as).
nsubj(2,crossed,he).
nsubj(2,looked,he).
nsubj(2,saw,he).
ccomp(2,crossed,looked).
advmod(2,looked,down).
cc(2,looked,and).
ccomp(2,crossed,saw).
conj:and(2,looked,saw).
nmod:poss(2,shadow,his).
amod(2,shadow,own).
dobj(2,saw,shadow).
acl(2,shadow,reflected).
case(2,water,in).
det(2,water,the).
nmod:in(2,reflected,water).
case(2,water,beneath).
saw(2,he,his_shadow_reflected).
saw(2,he,his_own_shadow).
saw(2,he,his_own_shadow_reflected_in_water_beneath).
saw(2,he,his_own_shadow_reflected).
saw(2,he,his_shadow).
saw(2,he,his_shadow_reflected_in_water_beneath).
root(3,ROOT,thinking).
nsubj(3,dog,it).
cop(3,dog,was).
det(3,dog,another).
ccomp(3,thinking,dog).
case(3,piece,with).
det(3,piece,another).
nmod:with(3,dog,piece).
case(3,meat,of).
nmod:of(3,piece,meat).
nsubj(3,made,he).
acl:relcl(3,dog,made).
compound:prt(3,made,up).
nmod:poss(3,mind,his).
dobj(3,made,mind).
mark(3,have,to).
acl:to(3,mind,have).
dobj(3,have,that).
advmod(3,have,also).
is_with(3,dog,piece_of_meat).
root(4,ROOT,so).
nsubj(4,made,he).
ccomp(4,so,made).
det(4,snap,a).
dobj(4,made,snap).
case(4,shadow,at).
det(4,shadow,the).
nmod:at(4,made,shadow).
case(4,water,in).
det(4,water,the).
nmod:in(4,made,water).
cc(4,opened,but).
mark(4,opened,as).
nsubj(4,opened,he).
parataxis(4,made,opened).
nmod:poss(4,mouth,his).
nsubj(4,dropped,mouth).
nsubjpass(4,seen,mouth).
det(4,piece,the).
nsubj(4,fell,piece).
case(4,meat,of).
nmod:of(4,piece,meat).
acl:relcl(4,mouth,fell).
compound:prt(4,fell,out).
ccomp(4,opened,dropped).
case(4,water,into).
det(4,water,the).
nmod:into(4,dropped,water).
cc(4,dropped,and).
auxpass(4,seen,was).
neg(4,seen,never).
ccomp(4,opened,seen).
conj:and(4,dropped,seen).
advmod(4,seen,more).
