%% a prince had some monkeys trained to dance.
% dependencies.
root(0,root,have).
det(0,prince,a).
nsubj(0,have,prince).
det(0,monkey,some).
dobj(0,have,monkey).
acl(0,monkey,train).
mark(0,dance,to).
xcomp(0,train,dance).
% relations.
have(0,prince,monkey_train).
have(0,prince,monkey).
%% being naturally great mimics of men 's actions they showed themselves most apt pupils and when arrayed in their rich clothes and masks they danced as well as any of the courtiers.
% dependencies.
root(1,root,mimic).
cop(1,mimic,be).
advmod(1,great,naturally).
amod(1,mimic,great).
case(1,action,of).
nmod:poss(1,action,man).
case(1,man,'s).
nmod:of(1,mimic,action).
nsubj(1,show,they).
acl:relcl(1,action,show).
iobj(1,show,themselves).
advmod(1,apt,most).
amod(1,pupil,apt).
dobj(1,show,pupil).
cc(1,show,and).
advmod(1,array,when).
advcl(1,dance,array).
case(1,clothes,in).
nmod:poss(1,clothes,they).
amod(1,clothes,rich).
nmod:in(1,array,clothes).
cc(1,clothes,and).
nmod:in(1,array,mask).
conj:and(1,clothes,mask).
nsubj(1,dance,they).
acl:relcl(1,action,dance).
conj:and(1,show,dance).
cc(1,mimic,as).
mwe(1,as,well).
mwe(1,as,as).
conj:and(1,mimic,any).
case(1,courtier,of).
det(1,courtier,the).
nmod:of(1,any,courtier).
% relations.
array_in(1,they,they_clothes).
show(1,they,themselves).
show(1,they,apt_pupil).
array_in(1,they,they_rich_clothes).
show(1,they,most_apt_pupil).
of(1,man,action).
show(1,they,pupil).
%% the spectacle was often repeated with great applause till on one occasion a courtier bent on mischief took from his pocket a handful of nuts and threw them upon the stage.
% dependencies.
root(2,root,repeat).
det(2,spectacle,the).
nsubjpass(2,repeat,spectacle).
auxpass(2,repeat,be).
advmod(2,repeat,often).
case(2,applause,with).
amod(2,applause,great).
nmod:with(2,repeat,applause).
mark(2,take,till).
case(2,occasion,on).
nummod(2,occasion,one).
nmod:on(2,take,occasion).
det(2,courtier,a).
nsubj(2,take,courtier).
nsubj(2,throw,courtier).
amod(2,courtier,bent).
case(2,mischief,on).
nmod:on(2,bent,mischief).
advcl:till(2,repeat,take).
case(2,pocket,from).
nmod:poss(2,pocket,he).
nmod:from(2,take,pocket).
det:qmod(2,nut,a).
mwe(2,a,handful).
mwe(2,a,of).
nmod:tmod(2,take,nut).
cc(2,take,and).
advcl:till(2,repeat,throw).
conj:and(2,take,throw).
dobj(2,throw,they).
case(2,stage,upon).
det(2,stage,the).
nmod:upon(2,throw,stage).
% relations.
bent_on(2,courtier,mischief).
be_repeat(2,spectacle,courtier_bent_on_mischief_take).
be(2,spectacle,often_repeat).
be_often_repeat(2,spectacle,courtier_bent_take).
be_repeat(2,spectacle,on_one_occasion_courtier_bent_take_from_he_pocket).
be_often_repeat(2,spectacle,courtier_take_from_he_pocket).
be_repeat(2,spectacle,on_one_occasion_courtier_take_from_he_pocket).
be_often_repeat(2,spectacle,on_one_occasion_courtier_bent_take).
be_repeat_with(2,spectacle,applause).
take_on(2,courtier_bent,one_occasion).
be_often_repeat(2,spectacle,on_one_occasion_courtier_take_from_he_pocket).
be_often_repeat(2,spectacle,on_one_occasion_courtier_bent_on_mischief_take_from_he_pocket).
throw(2,courtier_bent,they).
be_repeat(2,spectacle,on_one_occasion_courtier_bent_on_mischief_take).
be_repeat(2,spectacle,courtier_bent_take).
be_often_repeat(2,spectacle,courtier_take).
be_repeat(2,spectacle,on_one_occasion_courtier_take).
be_often_repeat(2,spectacle,on_one_occasion_courtier_bent_on_mischief_take).
be_repeat(2,spectacle,on_one_occasion_courtier_bent_on_mischief_take_from_he_pocket).
be_often_repeat(2,spectacle,courtier_bent_take_from_he_pocket).
take_from(2,courtier_bent,he_pocket).
be_often_repeat(2,spectacle,on_one_occasion_courtier_take).
be_repeat(2,spectacle,courtier_bent_on_mischief_take_from_he_pocket).
be_often_repeat_with(2,spectacle,applause).
take_on(2,courtier,one_occasion).
throw(2,courtier,they).
take_from(2,courtier,he_pocket).
be_repeat(2,spectacle,courtier_take).
be_repeat(2,spectacle,courtier_bent_take_from_he_pocket).
be(2,spectacle,repeat).
be_often_repeat(2,spectacle,courtier_bent_on_mischief_take).
be_repeat(2,spectacle,on_one_occasion_courtier_bent_take).
be_repeat(2,spectacle,courtier_take_from_he_pocket).
be_often_repeat(2,spectacle,on_one_occasion_courtier_bent_take_from_he_pocket).
be_often_repeat(2,spectacle,courtier_bent_on_mischief_take_from_he_pocket).
%% the monkeys at the sight of the nuts forgot their dancing and became ( as indeed they were ) monkeys instead of actors.
% dependencies.
root(3,root,forget).
det(3,monkey,the).
nsubj(3,forget,monkey).
case(3,sight,at).
det(3,sight,the).
nmod:at(3,monkey,sight).
case(3,nut,of).
det(3,nut,the).
nmod:of(3,sight,nut).
nmod:poss(3,dancing,they).
dobj(3,forget,dancing).
cc(3,dancing,and).
dobj(3,forget,become).
conj:and(3,dancing,become).
punct(3,be,-LRB-).
mark(3,be,as).
advmod(3,be,indeed).
nsubj(3,be,they).
parataxis(3,become,be).
punct(3,be,-RRB-).
xcomp(3,become,monkey).
case(3,actor,instead).
mwe(3,instead,of).
nmod:instead_of(3,monkey,actor).
% relations.
forget(3,monkey,they_dancing).
%% pulling off their masks and tearing their robes they fought with one another for the nuts.
% dependencies.
root(4,root,pull).
compound:prt(4,pull,off).
nmod:poss(4,mask,they).
dobj(4,pull,mask).
cc(4,pull,and).
conj:and(4,pull,tear).
nmod:poss(4,robe,they).
dobj(4,tear,robe).
nsubj(4,fight,they).
acl:relcl(4,robe,fight).
case(4,one,with).
nmod:with(4,fight,one).
dep(4,one,another).
case(4,nut,for).
det(4,nut,the).
nmod:for(4,fight,nut).
% relations.
fight_for(4,they,nut).
%% the dancing spectacle thus came to an end amidst the laughter and ridicule of the audience.
% dependencies.
root(5,root,come).
det(5,spectacle,the).
compound(5,spectacle,dancing).
nsubj(5,come,spectacle).
advmod(5,come,thus).
case(5,end,to).
det(5,end,a).
nmod:to(5,come,end).
case(5,laughter,amidst).
det(5,laughter,the).
nmod:amidst(5,come,laughter).
cc(5,laughter,and).
nmod:amidst(5,come,ridicule).
conj:and(5,laughter,ridicule).
case(5,audience,of).
det(5,audience,the).
nmod:of(5,laughter,audience).
% relations.
thus_come_amidst(5,dancing_spectacle,laughter).
come_amidst(5,dancing_spectacle,laughter_of_audience).
thus_come_amidst(5,dancing_spectacle,laughter_of_audience).
come_to(5,dancing_spectacle,end).
come_amidst(5,dancing_spectacle,laughter).
thus_come_to(5,dancing_spectacle,end).
