root(0,ROOT,came).
det(0,crow,a).
nsubj(0,came,crow).
amod(0,crow,half-dead).
case(0,thirst,with).
nmod:with(0,half-dead,thirst).
case(0,pitcher,upon).
det(0,pitcher,a).
nmod:upon(0,came,pitcher).
nsubj(0,full,pitcher).
ref(0,pitcher,which).
aux(0,full,had).
advmod(0,full,once).
cop(0,full,been).
acl:relcl(0,pitcher,full).
case(0,water,of).
nmod:of(0,full,water).
half-dead_with(0,crow,thirst).
root(1,ROOT,put).
cc(1,put,but).
advmod(1,put,when).
det(1,crow,the).
nsubj(1,put,crow).
nmod:poss(1,beak,its).
dobj(1,put,beak).
case(1,mouth,into).
det(1,mouth,the).
nmod:into(1,put,mouth).
case(1,pitcher,of).
det(1,pitcher,the).
nmod:of(1,mouth,pitcher).
nsubj(1,found,he).
ccomp(1,put,found).
mark(1,left,that).
advmod(1,water,only).
advmod(1,water,very).
amod(1,water,little).
nsubjpass(1,left,water).
auxpass(1,left,was).
ccomp(1,found,left).
case(1,it,in).
nmod:in(1,left,it).
cc(1,found,and).
mark(1,reach,that).
nsubj(1,reach,he).
nsubj:xsubj(1,get,he).
aux(1,reach,could).
neg(1,reach,not).
ccomp(1,put,reach).
conj:and(1,found,reach).
advmod(1,enough,far).
advmod(1,reach,enough).
advmod(1,reach,down).
mark(1,get,to).
xcomp(1,reach,get).
case(1,it,at).
nmod:at(1,get,it).
was(1,little_water,left).
was(1,water,left).
was_left_in(1,little_water,it).
get_at(1,he,it).
put(1,crow,its_beak).
was_left_in(1,water,it).
root(2,ROOT,tried).
nsubj(2,tried,he).
cc(2,tried,and).
nsubj(2,tried,he).
nsubj(2,had,he).
nsubj:xsubj(2,give,he).
xcomp(2,tried,tried).
cc(2,tried,but).
case(2,last,at).
nmod:at(2,had,last).
xcomp(2,tried,had).
conj:but(2,tried,had).
mark(2,give,to).
xcomp(2,had,give).
compound:prt(2,give,up).
case(2,despair,in).
nmod:in(2,give,despair).
tried(2,he,he_tried).
had_at(2,he,last).
root(3,ROOT,came).
advmod(3,came,then).
det(3,thought,a).
nsubj(3,came,thought).
case(3,him,to).
nmod:to(3,came,him).
cc(3,came,and).
nsubj(3,took,he).
nsubj(3,dropped,he).
conj:and(3,came,took).
det(3,pebble,a).
dobj(3,took,pebble).
cc(3,took,and).
conj:and(3,came,dropped).
conj:and(3,took,dropped).
dobj(3,dropped,it).
case(3,pitcher,into).
det(3,pitcher,the).
nmod:into(3,dropped,pitcher).
took(3,he,pebble).
came_to(3,thought,him).
dropped(3,he,it).
root(4,ROOT,took).
advmod(4,he,then).
nsubj(4,took,he).
nsubj(4,dropped,he).
det(4,pebble,another).
dobj(4,took,pebble).
cc(4,took,and).
conj:and(4,took,dropped).
dobj(4,dropped,it).
case(4,pitcher,into).
det(4,pitcher,the).
nmod:into(4,dropped,pitcher).
dropped(4,he,it).
root(5,ROOT,took).
advmod(5,he,then).
nsubj(5,took,he).
nsubj(5,dropped,he).
det(5,pebble,another).
dobj(5,took,pebble).
cc(5,took,and).
conj:and(5,took,dropped).
dobj(5,dropped,that).
case(5,pitcher,into).
det(5,pitcher,the).
nmod:into(5,dropped,pitcher).
dropped_into(5,he,pitcher).
root(6,ROOT,took).
advmod(6,he,then).
nsubj(6,took,he).
nsubj(6,dropped,he).
det(6,pebble,another).
dobj(6,took,pebble).
cc(6,took,and).
conj:and(6,took,dropped).
dobj(6,dropped,that).
case(6,pitcher,into).
det(6,pitcher,the).
nmod:into(6,dropped,pitcher).
dropped_into(6,he,pitcher).
root(7,ROOT,took).
advmod(7,he,then).
nsubj(7,took,he).
nsubj(7,dropped,he).
det(7,pebble,another).
dobj(7,took,pebble).
cc(7,took,and).
conj:and(7,took,dropped).
dobj(7,dropped,that).
case(7,pitcher,into).
det(7,pitcher,the).
nmod:into(7,dropped,pitcher).
dropped_into(7,he,pitcher).
root(8,ROOT,took).
advmod(8,he,then).
nsubj(8,took,he).
nsubj(8,dropped,he).
det(8,pebble,another).
dobj(8,took,pebble).
cc(8,took,and).
conj:and(8,took,dropped).
dobj(8,dropped,that).
case(8,pitcher,into).
det(8,pitcher,the).
nmod:into(8,dropped,pitcher).
dropped_into(8,he,pitcher).
root(9,ROOT,saw).
case(9,last,at).
nmod:at(9,saw,last).
case(9,last,at).
nmod:at(9,last,last).
nsubj(9,saw,he).
det(9,water,the).
nsubj(9,mount,water).
ccomp(9,saw,mount).
advmod(9,mount,up).
case(9,him,near).
nmod:near(9,mount,him).
cc(9,him,and).
mark(9,casting,after).
nmod:near(9,mount,casting).
conj:and(9,him,casting).
advmod(9,few,in).
advmod(9,few,a).
nummod(9,pebbles,few).
advmod(9,few,more).
dobj(9,casting,pebbles).
nsubj(9,able,he).
nsubj:xsubj(9,quench,he).
nsubj:xsubj(9,save,he).
cop(9,able,was).
acl:relcl(9,pebbles,able).
mark(9,quench,to).
xcomp(9,able,quench).
nmod:poss(9,thirst,his).
dobj(9,quench,thirst).
cc(9,quench,and).
xcomp(9,able,save).
conj:and(9,quench,save).
nmod:poss(9,life,his).
dobj(9,save,life).
saw_at(9,he,last_at_last).
mount_near(9,water,him).
mount_up_near(9,water,him).
saw_at(9,he,last).
