root(0,ROOT,made).
det(0,eagle,an).
nsubj(0,made,eagle).
nmod:poss(0,nest,her).
dobj(0,made,nest).
case(0,top,at).
det(0,top,the).
nmod:at(0,made,top).
case(0,oak,of).
det(0,oak,a).
amod(0,oak,lofty).
nmod:of(0,top,oak).
made(0,eagle,her_nest).
root(1,ROOT,moved).
det(1,cat,a).
nsubj(1,moved,cat).
aux(1,found,having).
dep(1,cat,found).
det(1,hole,a).
amod(1,hole,convenient).
dobj(1,found,hole).
case(1,middle,into).
det(1,middle,the).
nmod:into(1,moved,middle).
case(1,trunk,of).
det(1,trunk,the).
nmod:of(1,middle,trunk).
moved_into(1,cat,middle_of_trunk).
moved_into(1,cat,middle).
root(2,ROOT,wild).
cc(2,wild,and).
det(2,wild,a).
csubj(2,took,sow).
case(2,young,with).
nmod:poss(2,young,her).
nmod:with(2,sow,young).
acl:relcl(2,wild,took).
dobj(2,took,shelter).
case(2,hollow,in).
det(2,hollow,a).
nmod:in(2,took,hollow).
case(2,foot,at).
nmod:poss(2,foot,its).
nmod:at(2,took,foot).
took(2,sow,shelter).
sow_with(2,shelter,her_young).
took_shelter_in(2,sow,hollow).
took_shelter_at(2,sow,its_foot).
root(3,ROOT,resolved).
det(3,cat,the).
nsubj(3,resolved,cat).
nsubj:xsubj(3,destroy,cat).
advmod(3,resolved,cunningly).
mark(3,destroy,to).
xcomp(3,resolved,destroy).
det(3,colony,this).
amod(3,colony,chance-made).
dobj(3,destroy,colony).
destroy(3,cat,chance-made_colony).
destroy(3,cat,colony).
root(4,ROOT,carry).
mark(4,carry,to).
compound:prt(4,carry,out).
nmod:poss(4,design,her).
dobj(4,carry,design).
nsubj(4,climbed,she).
nsubj(4,said,she).
acl:relcl(4,design,climbed).
case(4,nest,to).
det(4,nest,the).
nmod:to(4,climbed,nest).
case(4,eagle,of).
det(4,eagle,the).
nmod:of(4,nest,eagle).
cc(4,climbed,and).
acl:relcl(4,design,said).
conj:and(4,climbed,said).
climbed_to(4,she,nest).
climbed_to(4,she,nest_of_eagle).
root(5,ROOT,preparing).
nsubj(5,preparing,destruction).
aux(5,preparing,is).
case(5,you,for).
nmod:for(5,too,you).
cc(5,too,and).
case(5,me,for).
nmod(5,preparing,me).
conj:and(5,too,me).
nmod(5,preparing,too).
advmod(5,preparing,unfortunately).
root(6,ROOT,sow).
dep(6,sow,the).
dep(6,sow,wild).
dobj(6,see,whom).
nsubj(6,see,you).
ccomp(6,sow,see).
amod(6,digging,daily).
nsubj(6,wishes,digging).
nsubj:xsubj(6,uproot,digging).
case(6,earth,up).
det(6,earth,the).
advmod(6,wishes,earth).
ccomp(6,see,wishes).
mark(6,uproot,to).
xcomp(6,wishes,uproot).
det(6,oak,the).
dobj(6,uproot,oak).
mark(6,seize,so).
nsubj(6,seize,she).
aux(6,seize,may).
case(6,fall,on).
nmod:poss(6,fall,its).
nmod:on(6,seize,fall).
advcl:so(6,wishes,seize).
nmod:poss(6,families,our).
dobj(6,seize,families).
case(6,food,as).
nmod:as(6,seize,food).
case(6,young,for).
nmod:poss(6,young,her).
nmod:for(6,food,young).
uproot(6,daily_digging,oak).
may_seize(6,she,our_families).
uproot(6,digging,oak).
root(7,ROOT,frightened).
aux(7,frightened,having).
advmod(7,frightened,thus).
det(7,eagle,the).
advmod(7,senses,eagle).
case(7,eagle,out).
case(7,senses,of).
nmod:poss(7,senses,her).
nmod:of(7,frightened,senses).
nsubj(7,crept,she).
nsubj(7,said,she).
acl:relcl(7,senses,crept).
compound:prt(7,crept,down).
case(7,cave,to).
det(7,cave,the).
nmod:to(7,crept,cave).
case(7,the,of).
nmod:of(7,cave,the).
ccomp(7,crept,sow).
cc(7,crept,and).
acl:relcl(7,senses,said).
conj:and(7,crept,said).
crept_down_to(7,she,cave).
crept_down_to(7,she,cave_of_the).
root(8,ROOT,danger).
nmod:poss(8,children,your).
nsubj(8,danger,children).
cop(8,danger,are).
case(8,danger,in).
amod(8,danger,great).
are_in(8,your_children,danger).
are_in(8,your_children,great_danger).
root(9,ROOT,prepared).
mark(9,prepared,for).
advmod(9,go,as).
advmod(9,go,soon).
mark(9,go,as).
nsubj(9,go,you).
advcl:as(9,prepared,go).
compound:prt(9,go,out).
case(9,litter,with).
nmod:poss(9,litter,your).
nmod:with(9,go,litter).
mark(9,find,to).
acl:to(9,litter,find).
dobj(9,find,food).
det(9,eagle,the).
nsubjpass(9,prepared,eagle).
nsubj:xsubj(9,pounce,eagle).
auxpass(9,prepared,is).
mark(9,pounce,to).
xcomp(9,prepared,pounce).
case(9,one,upon).
nmod:upon(9,pounce,one).
case(9,pigs,of).
nmod:poss(9,pigs,your).
amod(9,pigs,little).
nmod:of(9,one,pigs).
is(9,eagle,prepared).
is_prepared(9,eagle,pounce_upon_one_your_pigs).
is_prepared(9,eagle,pounce_upon_one_of_your_pigs).
pounce_upon(9,eagle,one_of_your_pigs).
is_prepared(9,eagle,pounce).
pounce_upon(9,eagle,one_your_pigs).
is_prepared(9,eagle,pounce_upon_one_your_little_pigs).
is_prepared(9,eagle,pounce_upon_one_of_your_little_pigs).
pounce_upon(9,eagle,one_your_little_pigs).
pounce_upon(9,eagle,one_of_your_little_pigs).
root(10,ROOT,instilled).
aux(10,instilled,having).
det(10,fears,these).
dobj(10,instilled,fears).
case(10,the,into).
nmod:into(10,instilled,the).
dep(10,instilled,sow).
nsubj(10,went,she).
nsubj(10,pretended,she).
nsubj:xsubj(10,hide,she).
ccomp(10,sow,went).
cc(10,went,and).
ccomp(10,sow,pretended).
conj:and(10,went,pretended).
mark(10,hide,to).
xcomp(10,pretended,hide).
dobj(10,hide,herself).
case(10,hollow,in).
det(10,hollow,the).
nmod:in(10,hide,hollow).
case(10,tree,of).
det(10,tree,the).
nmod:of(10,hollow,tree).
root(11,ROOT,came).
advmod(11,came,when).
nmod:tmod(11,came,night).
nsubj(11,went,she).
nsubj(11,obtained,she).
ccomp(11,came,went).
advmod(11,went,forth).
case(11,foot,with).
amod(11,foot,silent).
nmod:with(11,went,foot).
cc(11,went,and).
ccomp(11,came,obtained).
conj:and(11,went,obtained).
dobj(11,obtained,food).
case(11,herself,for).
nmod:for(11,obtained,herself).
cc(11,herself,and).
nmod:poss(11,kittens,her).
nmod:for(11,obtained,kittens).
conj:and(11,herself,kittens).
cc(11,obtained,but).
conj:and(11,went,feigning).
conj:but(11,obtained,feigning).
mark(11,afraid,to).
cop(11,afraid,be).
xcomp(11,feigning,afraid).
nsubj(11,kept,she).
ccomp(11,afraid,kept).
det(11,lookout,a).
dobj(11,kept,lookout).
dep(11,day,all).
case(11,day,through).
det(11,day,the).
nmod:through(11,kept,day).
kept(11,she,lookout).
went_forth_with(11,she,foot).
went_with(11,she,silent_foot).
obtained_food_for(11,she,herself).
kept_lookout_through(11,she,day).
feigning(11,food,afraid).
obtained(11,she,food).
went_forth_with(11,she,silent_foot).
went_with(11,she,foot).
root(12,ROOT,eagle).
dep(12,eagle,meanwhile).
det(12,eagle,the).
case(12,fear,full).
case(12,fear,of).
nmod:of(12,eagle,fear).
mark(12,sat,of).
dep(12,sat,the).
csubj(12,sat,sow).
acl:of(12,fear,sat).
advmod(12,sat,still).
case(12,branches,on).
det(12,branches,the).
nmod:on(12,sat,branches).
cc(12,sat,and).
dep(12,dare,the).
csubj(12,dare,sow).
dobj(12,sow,terrified).
case(12,eagle,by).
det(12,eagle,the).
nmod:by(12,terrified,eagle).
aux(12,dare,did).
neg(12,dare,not).
acl:of(12,fear,dare).
conj:and(12,sat,dare).
mark(12,go,to).
xcomp(12,dare,go).
compound:prt(12,go,out).
case(12,cave,from).
nmod:poss(12,cave,her).
nmod:from(12,go,cave).
root(13,ROOT,perished).
cc(13,perished,and).
advmod(13,perished,thus).
nsubj(13,perished,they).
nsubj(13,afforded,they).
dep(13,they,both).
dep(13,families,along).
case(13,families,with).
nmod:poss(13,families,their).
advcl:with(13,both,families).
case(13,hunger,from).
nmod:from(13,perished,hunger).
cc(13,perished,and).
conj:and(13,perished,afforded).
amod(13,provision,ample).
dobj(13,afforded,provision).
case(13,cat,for).
det(13,cat,the).
nmod:for(13,afforded,cat).
cc(13,cat,and).
nmod:poss(13,kittens,her).
nmod:for(13,afforded,kittens).
conj:and(13,cat,kittens).
perished_from(13,they,hunger).
afforded(13,they,ample_provision).
thus_perished_from(13,they,hunger).
afforded(13,they,provision).
afforded_provision_for(13,they,cat).
