root(0,ROOT,had).
det(0,prince,a).
nsubj(0,had,prince).
det(0,monkeys,some).
dobj(0,had,monkeys).
acl(0,monkeys,trained).
mark(0,dance,to).
xcomp(0,trained,dance).
had(0,prince,monkeys_trained).
had(0,prince,monkeys).
root(1,ROOT,mimics).
cop(1,mimics,being).
advmod(1,great,naturally).
amod(1,mimics,great).
case(1,actions,of).
nmod:poss(1,actions,men).
case(1,men,'s).
nmod:of(1,mimics,actions).
nsubj(1,showed,they).
acl:relcl(1,actions,showed).
iobj(1,showed,themselves).
advmod(1,apt,most).
amod(1,pupils,apt).
dobj(1,showed,pupils).
cc(1,showed,and).
advmod(1,arrayed,when).
advcl(1,danced,arrayed).
case(1,clothes,in).
nmod:poss(1,clothes,their).
amod(1,clothes,rich).
nmod:in(1,arrayed,clothes).
cc(1,clothes,and).
nmod:in(1,arrayed,masks).
conj:and(1,clothes,masks).
nsubj(1,danced,they).
acl:relcl(1,actions,danced).
conj:and(1,showed,danced).
cc(1,mimics,as).
mwe(1,as,well).
mwe(1,as,as).
conj:and(1,mimics,any).
case(1,courtiers,of).
det(1,courtiers,the).
nmod:of(1,any,courtiers).
arrayed_in(1,they,their_clothes).
showed(1,they,themselves).
showed(1,they,apt_pupils).
arrayed_in(1,they,their_rich_clothes).
showed(1,they,most_apt_pupils).
of(1,men,actions).
showed(1,they,pupils).
root(2,ROOT,repeated).
det(2,spectacle,the).
nsubjpass(2,repeated,spectacle).
auxpass(2,repeated,was).
advmod(2,repeated,often).
case(2,applause,with).
amod(2,applause,great).
nmod:with(2,repeated,applause).
mark(2,took,till).
case(2,occasion,on).
nummod(2,occasion,one).
nmod:on(2,took,occasion).
det(2,courtier,a).
nsubj(2,took,courtier).
nsubj(2,threw,courtier).
amod(2,courtier,bent).
case(2,mischief,on).
nmod:on(2,bent,mischief).
advcl:till(2,repeated,took).
case(2,pocket,from).
nmod:poss(2,pocket,his).
nmod:from(2,took,pocket).
det:qmod(2,nuts,a).
mwe(2,a,handful).
mwe(2,a,of).
nmod:tmod(2,took,nuts).
cc(2,took,and).
advcl:till(2,repeated,threw).
conj:and(2,took,threw).
dobj(2,threw,them).
case(2,stage,upon).
det(2,stage,the).
nmod:upon(2,threw,stage).
bent_on(2,courtier,mischief).
was_repeated(2,spectacle,courtier_bent_on_mischief_took).
was(2,spectacle,often_repeated).
was_often_repeated(2,spectacle,courtier_bent_took).
was_repeated(2,spectacle,on_one_occasion_courtier_bent_took_from_his_pocket).
was_often_repeated(2,spectacle,courtier_took_from_his_pocket).
was_repeated(2,spectacle,on_one_occasion_courtier_took_from_his_pocket).
was_often_repeated(2,spectacle,on_one_occasion_courtier_bent_took).
was_repeated_with(2,spectacle,applause).
took_on(2,courtier_bent,one_occasion).
was_often_repeated(2,spectacle,on_one_occasion_courtier_took_from_his_pocket).
was_often_repeated(2,spectacle,on_one_occasion_courtier_bent_on_mischief_took_from_his_pocket).
threw(2,courtier_bent,them).
was_repeated(2,spectacle,on_one_occasion_courtier_bent_on_mischief_took).
was_repeated(2,spectacle,courtier_bent_took).
was_often_repeated(2,spectacle,courtier_took).
was_repeated(2,spectacle,on_one_occasion_courtier_took).
was_often_repeated(2,spectacle,on_one_occasion_courtier_bent_on_mischief_took).
was_repeated(2,spectacle,on_one_occasion_courtier_bent_on_mischief_took_from_his_pocket).
was_often_repeated(2,spectacle,courtier_bent_took_from_his_pocket).
took_from(2,courtier_bent,his_pocket).
was_often_repeated(2,spectacle,on_one_occasion_courtier_took).
was_repeated(2,spectacle,courtier_bent_on_mischief_took_from_his_pocket).
was_often_repeated_with(2,spectacle,applause).
took_on(2,courtier,one_occasion).
threw(2,courtier,them).
took_from(2,courtier,his_pocket).
was_repeated(2,spectacle,courtier_took).
was_repeated(2,spectacle,courtier_bent_took_from_his_pocket).
was(2,spectacle,repeated).
was_often_repeated(2,spectacle,courtier_bent_on_mischief_took).
was_repeated(2,spectacle,on_one_occasion_courtier_bent_took).
was_repeated(2,spectacle,courtier_took_from_his_pocket).
was_often_repeated(2,spectacle,on_one_occasion_courtier_bent_took_from_his_pocket).
was_often_repeated(2,spectacle,courtier_bent_on_mischief_took_from_his_pocket).
root(3,ROOT,forgot).
det(3,monkeys,the).
nsubj(3,forgot,monkeys).
case(3,sight,at).
det(3,sight,the).
nmod:at(3,monkeys,sight).
case(3,nuts,of).
det(3,nuts,the).
nmod:of(3,sight,nuts).
nmod:poss(3,dancing,their).
dobj(3,forgot,dancing).
cc(3,dancing,and).
dobj(3,forgot,became).
conj:and(3,dancing,became).
punct(3,were,-LRB-).
mark(3,were,as).
advmod(3,were,indeed).
nsubj(3,were,they).
parataxis(3,became,were).
punct(3,were,-RRB-).
xcomp(3,became,monkeys).
case(3,actors,instead).
mwe(3,instead,of).
nmod:instead_of(3,monkeys,actors).
forgot(3,monkeys,their_dancing).
root(4,ROOT,pulling).
compound:prt(4,pulling,off).
nmod:poss(4,masks,their).
dobj(4,pulling,masks).
cc(4,pulling,and).
conj:and(4,pulling,tearing).
nmod:poss(4,robes,their).
dobj(4,tearing,robes).
nsubj(4,fought,they).
acl:relcl(4,robes,fought).
case(4,one,with).
nmod:with(4,fought,one).
dep(4,one,another).
case(4,nuts,for).
det(4,nuts,the).
nmod:for(4,fought,nuts).
fought_for(4,they,nuts).
root(5,ROOT,came).
det(5,spectacle,the).
compound(5,spectacle,dancing).
nsubj(5,came,spectacle).
advmod(5,came,thus).
case(5,end,to).
det(5,end,an).
nmod:to(5,came,end).
case(5,laughter,amidst).
det(5,laughter,the).
nmod:amidst(5,came,laughter).
cc(5,laughter,and).
nmod:amidst(5,came,ridicule).
conj:and(5,laughter,ridicule).
case(5,audience,of).
det(5,audience,the).
nmod:of(5,laughter,audience).
thus_came_amidst(5,dancing_spectacle,laughter).
came_amidst(5,dancing_spectacle,laughter_of_audience).
thus_came_amidst(5,dancing_spectacle,laughter_of_audience).
came_to(5,dancing_spectacle,end).
came_amidst(5,dancing_spectacle,laughter).
thus_came_to(5,dancing_spectacle,end).
