root(0,ROOT,made).
det(0,cranes,some).
nsubj(0,made,cranes).
nmod:poss(0,grounds,their).
compound(0,grounds,feeding).
dobj(0,made,grounds).
case(0,plowlands,on).
det(0,plowlands,some).
nmod:on(0,made,plowlands).
advmod(0,sown,newly).
acl(0,plowlands,sown).
case(0,wheat,with).
nmod:with(0,sown,wheat).
made(0,cranes,their_feeding_grounds).
root(1,ROOT,time).
case(1,time,for).
det(1,time,a).
amod(1,time,long).
det(1,farmer,the).
nsubj(1,chased,farmer).
acl(1,farmer,brandishing).
det(1,sling,an).
amod(1,sling,empty).
dobj(1,brandishing,sling).
acl:relcl(1,time,chased).
dobj(1,chased,them).
compound:prt(1,chased,away).
case(1,terror,by).
det(1,terror,the).
nmod:by(1,chased,terror).
nsubj(1,inspired,he).
acl:relcl(1,time,inspired).
brandishing(1,farmer,sling).
chased_away(1,farmer,them).
brandishing(1,farmer,empty_sling).
root(2,ROOT,found).
cc(2,found,but).
advmod(2,found,when).
det(2,birds,the).
nsubj(2,found,birds).
mark(2,swung,that).
det(2,sling,the).
nsubjpass(2,swung,sling).
auxpass(2,swung,was).
advmod(2,swung,only).
ccomp(2,found,swung).
case(2,air,in).
det(2,air,the).
nmod:in(2,swung,air).
nsubj(2,ceased,they).
nsubj:xsubj(2,take,they).
nsubj(2,move,they).
acl:relcl(2,air,ceased).
mark(2,take,to).
xcomp(2,ceased,take).
det(2,notice,any).
dobj(2,take,notice).
case(2,it,of).
nmod:of(2,notice,it).
cc(2,ceased,and).
aux(2,move,would).
neg(2,move,not).
acl:relcl(2,air,move).
conj:and(2,ceased,move).
was(2,sling,swung).
take(2,they,notice_of_it).
was(2,sling,only_swung).
root(3,ROOT,charged).
det(3,farmer,the).
nsubj(3,charged,farmer).
nsubj(3,killed,farmer).
mark(3,seeing,on).
acl:on(3,farmer,seeing).
dobj(3,seeing,this).
nmod:poss(3,sling,his).
dobj(3,charged,sling).
case(3,stones,with).
nmod:with(3,charged,stones).
cc(3,charged,and).
conj:and(3,charged,killed).
det(3,number,a).
amod(3,number,great).
dobj(3,killed,number).
root(4,ROOT,forsook).
det(4,birds,the).
amod(4,birds,remaining).
nsubj(4,forsook,birds).
case(4,once,at).
advmod(4,forsook,once).
nmod:poss(4,fields,his).
dobj(4,forsook,fields).
xcomp(4,forsook,crying).
case(4,other,to).
det(4,other,each).
nmod:to(4,crying,other).
once_forsook(4,remaining_birds,his_fields).
forsook(4,birds,his_fields).
once_forsook(4,birds,his_fields).
forsook(4,remaining_birds,his_fields).
root(5,ROOT,time).
nsubj(5,time,it).
cop(5,time,is).
case(5,us,for).
nmod:for(5,time,us).
mark(5,be,to).
acl:to(5,time,be).
advmod(5,be,off).
case(5,liliput,to).
nmod:to(5,off,liliput).
mark(5,content,for).
det(5,man,this).
nsubj(5,content,man).
nsubj:xsubj(5,scare,man).
nsubj(5,begins,man).
nsubj:xsubj(5,show,man).
cop(5,content,is).
neg(5,longer,no).
advmod(5,content,longer).
advcl:for(5,be,content).
mark(5,scare,to).
xcomp(5,content,scare).
dobj(5,scare,us).
cc(5,content,but).
advcl:for(5,be,begins).
conj:but(5,content,begins).
mark(5,show,to).
xcomp(5,begins,show).
dobj(5,show,us).
case(5,earnest,in).
nmod:in(5,show,earnest).
dobj(5,do,earnest).
ref(5,earnest,what).
nsubj(5,do,he).
aux(5,do,can).
acl:relcl(5,earnest,do).
is_time(5,it,be).
is(5,it,time_for_us_be_off).
is(5,man,content).
is(5,it,time_for_us_be).
scare(5,man,us).
is_time(5,it,be_off).
