root(0,ROOT,overwhelmed).
det(0,eagle,an).
nsubj(0,overwhelmed,eagle).
mark(0,sat,with).
nsubj(0,sat,sorrow).
advcl:with(0,overwhelmed,sat).
case(0,branches,upon).
det(0,branches,the).
nmod:upon(0,sat,branches).
case(0,tree,of).
det(0,tree,a).
nmod:of(0,branches,tree).
case(0,company,in).
nmod:in(0,tree,company).
case(0,kite,with).
det(0,kite,a).
nmod:with(0,sat,kite).
overwhelmed(0,eagle,sorrow_sat_upon_branches_of_tree_with_kite).
sat_upon(0,sorrow,branches).
overwhelmed(0,eagle,sorrow_sat).
sat_with(0,sorrow,kite).
sat_upon(0,sorrow,branches_of_tree).
overwhelmed(0,eagle,sorrow_sat_upon_branches_with_kite).
overwhelmed(0,eagle,sorrow_sat_with_kite).
is_in(0,tree,company).
sat_upon(0,sorrow,branches_of_tree_in_company).
overwhelmed(0,eagle,sorrow_sat_upon_branches_of_tree_in_company_with_kite).
overwhelmed(0,eagle,sorrow_sat_upon_branches_of_tree).
overwhelmed(0,eagle,sorrow_sat_upon_branches).
overwhelmed(0,eagle,sorrow_sat_upon_branches_of_tree_in_company).
root(1,ROOT,why).
root(2,ROOT,said).
det(2,kite,the).
nsubj(2,said,kite).
root(3,ROOT,do).
nsubj(3,see,i).
ccomp(3,do,see).
dobj(3,see,you).
case(3,look,with).
det:predet(3,look,such).
det(3,look,a).
amod(3,look,rueful).
nmod:with(3,see,look).
see(3,i,you).
root(4,ROOT,').
root(5,ROOT,seek).
advmod(5,seek,i).
root(6,ROOT,replied).
nsubj(6,replied,she).
root(7,ROOT,suitable).
det(7,mate,a).
nsubj(7,suitable,mate).
nsubj(7,able,mate).
nsubj:xsubj(7,find,mate).
case(7,me,for).
nmod:for(7,suitable,me).
cc(7,suitable,and).
cop(7,able,am).
neg(7,able,not).
conj:and(7,suitable,able).
mark(7,find,to).
xcomp(7,able,find).
dobj(7,find,one).
root(8,ROOT,take).
dobj(8,take,me).
root(9,ROOT,returned).
det(9,kite,the).
nsubj(9,returned,kite).
root(10,ROOT,am).
dep(10,am,i).
advmod(10,stronger,much).
dep(10,am,stronger).
mark(10,are,than).
nsubj(10,are,you).
ccomp(10,stronger,are).
root(11,ROOT,able).
advmod(11,able,why).
aux(11,able,are).
nsubj(11,able,you).
nsubj:xsubj(11,secure,you).
mark(11,secure,to).
xcomp(11,able,secure).
det(11,means,the).
dobj(11,secure,means).
case(11,living,of).
nmod:of(11,means,living).
case(11,plunder,by).
nmod:poss(11,plunder,your).
nmod:by(11,able,plunder).
are_able_by(11,you,your_plunder).
secure(11,you,means_of_living).
secure(11,you,means).
root(12,ROOT,').
root(13,ROOT,well).
nsubj(13,caught,i).
aux(13,caught,have).
advmod(13,caught,often).
ccomp(13,well,caught).
cc(13,well,and).
conj:and(13,well,carried).
compound:prt(13,carried,away).
det(13,ostrich,an).
dobj(13,carried,ostrich).
case(13,talons,in).
nmod:poss(13,talons,my).
nmod:in(13,ostrich,talons).
is_in(13,ostrich,my_talons).
root(14,ROOT,accepted).
det(14,eagle,the).
nsubj(14,accepted,eagle).
acl(14,eagle,persuaded).
case(14,words,by).
det(14,words,these).
nmod:by(14,persuaded,words).
dobj(14,accepted,him).
case(14,mate,as).
nmod:poss(14,mate,her).
nmod:as(14,accepted,mate).
accepted(14,eagle,him).
root(15,ROOT,said).
advmod(15,nuptials,shortly).
case(15,nuptials,after).
det(15,nuptials,the).
nmod:after(15,said,nuptials).
det(15,eagle,the).
nsubj(15,said,eagle).
said_after(15,eagle,nuptials).
said_after(15,eagle,shortly_nuptials).
root(16,ROOT,fly).
advmod(16,fly,off).
cc(16,fly,and).
conj:and(16,fly,bring).
nsubj(16,back,me).
ccomp(16,bring,back).
det(16,ostrich,the).
dobj(16,back,ostrich).
nsubj(16,promised,you).
dep(16,back,promised).
dobj(16,promised,me).
back(16,me,ostrich).
promised(16,you,me).
root(17,ROOT,brought).
det(17,kite,the).
nsubj(17,brought,kite).
acl(17,kite,soaring).
advmod(17,soaring,aloft).
case(17,air,into).
det(17,air,the).
nmod:into(17,soaring,air).
compound:prt(17,brought,back).
det(17,mouse,the).
amod(17,mouse,shabbiest).
amod(17,mouse,possible).
dobj(17,brought,mouse).
acl(17,mouse,stinking).
case(17,length,from).
det(17,length,the).
nmod:from(17,stinking,length).
case(17,time,of).
nmod:of(17,length,time).
nsubj(17,lain,it).
aux(17,lain,had).
acl:relcl(17,time,lain).
case(17,fields,about).
det(17,fields,the).
nmod:about(17,lain,fields).
brought_back(17,kite,possible_mouse_stinking_from_length).
brought_back(17,kite,shabbiest_possible_mouse).
soaring_into(17,kite,air).
brought_back(17,kite,shabbiest_possible_mouse_stinking).
brought_back(17,kite,possible_mouse_stinking).
soaring_aloft_into(17,kite,air).
brought_back(17,kite,possible_mouse).
brought_back(17,kite,shabbiest_possible_mouse_stinking_from_length).
had_lain_about(17,it,fields).
root(18,ROOT,this).
dep(18,this,is).
root(19,ROOT,said).
det(19,eagle,the).
nsubj(19,said,eagle).
root(20,ROOT,faithful).
det(20,faithful,the).
dep(20,faithful,fulfillment).
case(20,promise,of).
nmod:poss(20,promise,your).
nmod:of(20,fulfillment,promise).
case(20,me,to).
nmod:to(20,promise,me).
root(21,ROOT,replied).
punct(21,replied,').
det(21,kite,the).
nsubj(21,replied,kite).
root(22,ROOT,attain).
mark(22,attain,that).
nsubj(22,attain,i).
aux(22,attain,might).
nmod:poss(22,hand,your).
amod(22,hand,royal).
dobj(22,attain,hand).
mark(22,promised,hand).
expl(22,is,there).
acl:relcl(22,hand,is).
nsubj(22,is,nothing).
ref(22,hand,that).
nsubj(22,promised,i).
aux(22,promised,would).
neg(22,promised,not).
aux(22,promised,have).
ccomp(22,is,promised).
advmod(22,much,however).
xcomp(22,promised,much).
nsubj(22,knew,i).
ccomp(22,much,knew).
mark(22,fail,that).
nsubj(22,fail,i).
aux(22,fail,must).
ccomp(22,knew,fail).
case(22,performance,in).
det(22,performance,the).
nmod:in(22,fail,performance).
might_attain(22,i,your_hand).
might_attain(22,i,your_royal_hand).
