root(0,ROOT,given).
det(0,father,a).
nsubj(0,wished,father).
nsubj:xsubj(0,sure,father).
cop(0,point,being).
case(0,point,on).
det(0,point,the).
dep(0,father,point).
case(0,death,of).
nmod:of(0,point,death).
dep(0,given,wished).
mark(0,sure,to).
cop(0,sure,be).
xcomp(0,wished,sure).
mark(0,give,that).
nmod:poss(0,sons,his).
nsubj(0,give,sons).
aux(0,give,would).
ccomp(0,sure,give).
det(0,attention,the).
amod(0,attention,same).
iobj(0,give,attention).
case(0,farm,to).
nmod:poss(0,farm,his).
nmod:to(0,attention,farm).
case(0,he,as).
nmod:as(0,farm,he).
dobj(0,give,himself).
aux(0,given,had).
nsubj(0,given,it).
same_attention_to(0,himself,his_farm_as_he).
attention_to(0,his_sons,his_farm_as_he).
give(0,his_sons,same_attention).
attention_to(0,his_sons,his_farm).
same_attention_to(0,himself,his_farm).
give(0,his_sons,same_attention_to_his_farm_as_he).
same_attention_to(0,his_sons,his_farm).
give(0,his_sons,same_attention_to_his_farm).
give(0,his_sons,attention_to_his_farm_as_he).
same_attention_to(0,his_sons,his_farm_as_he).
attention_to(0,himself,his_farm).
attention_to(0,himself,his_farm_as_he).
give(0,his_sons,attention).
give(0,his_sons,himself).
give(0,his_sons,attention_to_his_farm).
root(1,ROOT,called).
nsubj(1,called,he).
nsubj(1,said,he).
dobj(1,called,them).
case(1,bedside,to).
nmod:poss(1,bedside,his).
nmod:to(1,called,bedside).
cc(1,called,and).
conj:and(1,called,said).
called_to(1,he,his_bedside).
called(1,he,them).
root(2,ROOT,hid).
nmod:poss(2,sons,my).
nsubj(2,hid,sons).
expl(2,is,there).
acl:relcl(2,sons,is).
det(2,treasure,a).
amod(2,treasure,great).
nsubj(2,is,treasure).
case(2,one,in).
nmod:in(2,hid,one).
case(2,vineyards,of).
nmod:poss(2,vineyards,my).
nmod:of(2,one,vineyards).
hid_in(2,my_sons,one_of_my_vineyards).
hid_in(2,my_sons,one_my_vineyards).
root(3,ROOT,took).
det(3,sons,the).
nsubj(3,took,sons).
nsubj(3,dug,sons).
case(3,death,after).
nmod:poss(3,death,his).
nmod:after(3,sons,death).
nmod:poss(3,spades,their).
dobj(3,took,spades).
cc(3,spades,and).
dobj(3,took,mattocks).
conj:and(3,spades,mattocks).
cc(3,took,and).
advmod(3,dug,carefully).
conj:and(3,took,dug).
case(3,portion,over).
det(3,portion,every).
nmod:over(3,dug,portion).
case(3,land,of).
nmod:poss(3,land,their).
nmod:of(3,portion,land).
dug_over(3,sons,portion_of_land).
took(3,sons,mattocks).
carefully_dug_over(3,sons,portion_of_their_land).
took(3,sons,their_spades).
carefully_dug_over(3,sons,portion_of_land).
dug_over(3,sons,portion_of_their_land).
root(4,ROOT,found).
nsubj(4,found,they).
neg(4,treasure,no).
dobj(4,found,treasure).
cc(4,repaid,but).
det(4,vines,the).
nsubj(4,repaid,vines).
dep(4,found,repaid).
nmod:poss(4,labor,their).
dobj(4,repaid,labor).
case(4,crop,by).
det(4,crop,an).
amod(4,crop,extraordinary).
cc(4,extraordinary,and).
conj:and(4,extraordinary,superabundant).
amod(4,crop,superabundant).
nmod:by(4,repaid,crop).
