root(0,ROOT,said).
det(0,fawn,a).
amod(0,fawn,young).
nsubj(0,said,fawn).
advmod(0,said,once).
case(0,mother,to).
nmod:poss(0,mother,his).
nmod:to(0,said,mother).
said_to(0,young_fawn,his_mother).
said_to(0,fawn,his_mother).
once_said_to(0,young_fawn,his_mother).
once_said_to(0,fawn,his_mother).
root(1,ROOT,larger).
nsubj(1,larger,you).
nsubj(1,swifter,you).
cop(1,larger,are).
case(1,dog,than).
det(1,dog,a).
nmod:than(1,larger,dog).
cc(1,larger,and).
conj:and(1,larger,swifter).
cc(1,swifter,and).
advmod(1,used,more).
conj:and(1,larger,used).
conj:and(1,swifter,used).
mark(1,running,to).
advcl:to(1,used,running).
cc(1,larger,and).
nsubj(1,have,you).
conj:and(1,larger,have).
nmod:poss(1,horns,your).
dobj(1,have,horns).
case(1,defense,as).
det(1,defense,a).
nmod:as(1,have,defense).
are(1,you,larger).
have(1,you,your_horns).
are_larger_than(1,you,dog).
root(2,ROOT,why).
dep(2,why,then).
compound(2,mother,o).
dep(2,then,mother).
root(3,ROOT,do).
det(3,hounds,the).
nsubj(3,frighten,hounds).
ccomp(3,do,frighten).
dobj(3,frighten,you).
advmod(3,frighten,so).
frighten_so(3,hounds,you).
frighten(3,hounds,you).
root(4,ROOT,smiled).
nsubj(4,smiled,she).
nsubj(4,said,she).
cc(4,smiled,and).
conj:and(4,smiled,said).
root(5,ROOT,know).
dep(5,know,i).
xcomp(5,know,full).
advmod(5,know,well).
nmod:poss(5,son,my).
nsubj(5,know,son).
mark(5,true,that).
nsubj(5,true,all).
nsubj(5,say,you).
acl:relcl(5,all,say).
cop(5,true,is).
dep(5,know,true).
know_well(5,my_son,full).
know(5,my_son,full).
root(6,ROOT,have).
nsubj(6,have,i).
det(6,advantages,the).
dobj(6,have,advantages).
nsubj(6,mention,you).
acl:relcl(6,advantages,mention).
cc(6,hear,but).
advmod(6,hear,when).
nsubj(6,hear,i).
nsubj(6,fly,i).
parataxis(6,mention,hear).
advmod(6,bark,even).
det(6,bark,the).
dobj(6,hear,bark).
case(6,dog,of).
det(6,dog,a).
amod(6,dog,single).
nmod:of(6,bark,dog).
nsubj(6,feel,i).
acl:relcl(6,dog,feel).
xcomp(6,feel,ready).
case(6,faint,to).
advcl:to(6,ready,faint).
cc(6,hear,and).
parataxis(6,mention,fly).
conj:and(6,hear,fly).
advmod(6,fast,away).
advmod(6,fast,as).
advmod(6,fly,fast).
mark(6,can,as).
nsubj(6,can,i).
advcl:as(6,mention,can).
hear(6,i,even_bark).
feel(6,i,ready).
hear(6,i,bark).
