root(0,ROOT,agreed).
det(0,dog,a).
nsubj(0,agreed,dog).
nsubj:xsubj(0,travel,dog).
cc(0,dog,and).
det(0,cock,a).
conj:and(0,dog,cock).
nsubj(0,agreed,cock).
nsubj:xsubj(0,travel,cock).
cop(0,friends,being).
amod(0,friends,great).
dep(0,cock,friends).
mark(0,travel,to).
xcomp(0,agreed,travel).
advmod(0,travel,together).
agreed(0,dog,travel_together).
agreed(0,cock,travel_together).
agreed(0,cock,travel).
agreed(0,dog,travel).
root(1,ROOT,took).
case(1,nightfall,at).
nmod:at(1,took,nightfall).
nsubj(1,took,they).
dobj(1,took,shelter).
case(1,wood,in).
det(1,wood,a).
amod(1,wood,thick).
nmod:in(1,took,wood).
took(1,they,shelter).
took_shelter_in(1,they,wood).
took_shelter_in(1,they,thick_wood).
took_shelter_at(1,they,nightfall).
root(2,ROOT,cock).
det(2,cock,the).
dep(2,cock,flying).
compound:prt(2,flying,up).
amod(2,himself,perched).
dobj(2,flying,himself).
case(2,branches,on).
det(2,branches,the).
nmod:on(2,himself,branches).
case(2,tree,of).
det(2,tree,a).
nmod:of(2,branches,tree).
mark(2,found,while).
det(2,dog,the).
nsubj(2,found,dog).
advcl:while(2,flying,found).
det(2,bed,a).
dobj(2,found,bed).
case(2,trunk,beneath).
case(2,trunk,in).
det(2,trunk,the).
amod(2,trunk,hollow).
nmod:in(2,found,trunk).
found_bed_beneath(2,dog,beneath_trunk).
found_bed_beneath(2,dog,beneath_hollow_trunk).
found(2,dog,bed).
root(3,ROOT,dawned).
advmod(3,dawned,when).
det(3,morning,the).
nsubj(3,dawned,morning).
det(3,cock,the).
dobj(3,dawned,cock).
case(3,usual,as).
nmod:as(3,dawned,usual).
acl(3,usual,crowed).
advmod(3,loudly,very).
advmod(3,crowed,loudly).
amod(3,times,several).
nmod:tmod(3,crowed,times).
dawned_cock_as(3,morning,usual_crowed_loudly_times).
dawned_cock_as(3,morning,usual).
dawned_as(3,morning,usual_crowed).
dawned_cock_as(3,morning,usual_crowed_times).
dawned_as(3,morning,usual_crowed_loudly).
dawned_cock_as(3,morning,usual_crowed_loudly_several_times).
dawned(3,morning,cock).
dawned_cock_as(3,morning,usual_crowed_very_loudly).
dawned_cock_as(3,morning,usual_crowed_several_times).
dawned_cock_as(3,morning,usual_crowed_loudly).
dawned_as(3,morning,usual_crowed_loudly_several_times).
dawned_as(3,morning,usual_crowed_several_times).
dawned_as(3,morning,usual_crowed_times).
dawned_cock_as(3,morning,usual_crowed_very_loudly_several_times).
dawned_as(3,morning,usual_crowed_loudly_times).
dawned_cock_as(3,morning,usual_crowed_very_loudly_times).
dawned_as(3,morning,usual_crowed_very_loudly_several_times).
dawned_as(3,morning,usual).
dawned_as(3,morning,usual_crowed_very_loudly).
dawned_cock_as(3,morning,usual_crowed).
dawned_as(3,morning,usual_crowed_very_loudly_times).
root(4,ROOT,heard).
det(4,fox,a).
nsubj(4,heard,fox).
nsubj(4,wishing,fox).
nsubj:xsubj(4,make,fox).
nsubj(4,stood,fox).
det(4,sound,the).
dobj(4,heard,sound).
cc(4,heard,and).
conj:and(4,heard,wishing).
mark(4,make,to).
xcomp(4,wishing,make).
det(4,breakfast,a).
dobj(4,make,breakfast).
mark(4,came,on).
nsubj(4,came,him).
advcl:on(4,make,came).
cc(4,heard,and).
conj:and(4,heard,stood).
case(4,branches,under).
det(4,branches,the).
nmod:under(4,stood,branches).
xcomp(4,stood,saying).
advmod(4,desired,how).
advmod(4,desired,earnestly).
nsubj(4,desired,he).
nsubj:xsubj(4,make,he).
ccomp(4,saying,desired).
mark(4,make,to).
xcomp(4,desired,make).
det(4,acquaintance,the).
dobj(4,make,acquaintance).
case(4,owner,of).
det(4,owner,the).
nmod:of(4,acquaintance,owner).
case(4,voice,of).
advmod(4,magnificent,so).
amod(4,voice,magnificent).
det(4,voice,a).
nmod:of(4,owner,voice).
stood_under(4,fox,branches).
heard(4,fox,sound).
stood(4,fox,saying).
root(5,ROOT,said).
det(5,cock,the).
nsubj(5,said,cock).
acl(5,cock,suspecting).
nmod:poss(5,civilities,his).
dobj(5,suspecting,civilities).
root(6,ROOT,sir).
nsubj(6,wish,i).
acl:relcl(6,sir,wish).
nsubj(6,do,you).
aux(6,do,would).
ccomp(6,wish,do).
iobj(6,do,me).
det(6,favor,the).
dobj(6,do,favor).
mark(6,going,of).
acl:of(6,favor,going).
advmod(6,going,around).
case(6,trunk,to).
det(6,trunk,the).
amod(6,trunk,hollow).
nmod:to(6,going,trunk).
case(6,me,below).
nmod:below(6,trunk,me).
cc(6,going,and).
acl:of(6,favor,waking).
conj:and(6,going,waking).
nmod:poss(6,porter,my).
dobj(6,waking,porter).
mark(6,open,so).
mwe(6,so,that).
nsubj(6,open,he).
nsubj(6,let,he).
aux(6,open,may).
advcl:so_that(6,waking,open).
det(6,door,the).
dobj(6,open,door).
cc(6,open,and).
advcl:so_that(6,waking,let).
conj:and(6,open,let).
dobj(6,let,you).
nmod(6,let,in).
let(6,he,you).
do(6,you,favor_going_around_to_hollow_trunk).
do(6,you,favor_going).
do(6,you,favor_going_to_trunk).
may_open(6,he,door).
do(6,you,me).
do(6,you,favor_going_to_hollow_trunk).
do(6,you,favor_going_around_to_hollow_trunk_below_me).
do(6,you,favor_going_around).
do(6,you,favor_going_around_to_trunk).
do(6,you,favor_going_around_to_trunk_below_me).
do(6,you,favor_going_to_hollow_trunk_below_me).
do(6,you,favor_going_to_trunk_below_me).
root(7,ROOT,approached).
advmod(7,approached,when).
det(7,fox,the).
nsubj(7,approached,fox).
nsubj(7,tore,fox).
det(7,tree,the).
dobj(7,approached,tree).
det(7,dog,the).
nsubj(7,sprang,dog).
nsubj(7,caught,dog).
dep(7,approached,sprang).
compound:prt(7,sprang,out).
cc(7,sprang,and).
dep(7,approached,caught).
conj:and(7,sprang,caught).
dobj(7,caught,him).
cc(7,approached,and).
conj:and(7,approached,tore).
dobj(7,tore,him).
case(7,pieces,to).
nmod:to(7,tore,pieces).
approached(7,fox,tree).
tore(7,fox,him).
caught(7,dog,him).
