root(0,ROOT,waged).
det(0,dolphins,the).
nsubj(0,waged,dolphins).
cc(0,dolphins,and).
conj:and(0,dolphins,whales).
nsubj(0,waged,whales).
det(0,war,a).
amod(0,war,fierce).
dobj(0,waged,war).
case(0,other,with).
det(0,other,each).
nmod:with(0,waged,other).
waged(0,dolphins,fierce_war).
waged(0,whales,fierce_war).
waged(0,dolphins,war).
waged(0,whales,war).
root(1,ROOT,height).
advmod(1,height,when).
det(1,battle,the).
nsubj(1,height,battle).
cop(1,height,was).
case(1,height,at).
nmod:poss(1,height,its).
det(1,sprat,a).
nsubj(1,lifted,sprat).
nsubj(1,said,sprat).
acl:relcl(1,height,lifted).
nmod:poss(1,head,its).
dobj(1,lifted,head).
compound:prt(1,lifted,out).
case(1,waves,of).
det(1,waves,the).
nmod:of(1,lifted,waves).
cc(1,lifted,and).
acl:relcl(1,height,said).
conj:and(1,lifted,said).
mark(1,reconcile,that).
nsubj(1,reconcile,he).
aux(1,reconcile,would).
ccomp(1,said,reconcile).
nmod:poss(1,differences,their).
dobj(1,reconcile,differences).
mark(1,accept,if).
nsubj(1,accept,they).
aux(1,accept,would).
advcl:if(1,reconcile,accept).
dobj(1,accept,him).
case(1,umpire,as).
det(1,umpire,an).
nmod:as(1,accept,umpire).
lifted_out(1,sprat,its_head).
root(2,ROOT,replied).
det:qmod(2,dolphins,one).
mwe(2,one,of).
det(2,dolphins,the).
nsubj(2,replied,dolphins).
root(3,ROOT,destroyed).
nsubjpass(3,destroyed,we).
aux(3,destroyed,would).
advmod(3,rather,far).
advmod(3,destroyed,rather).
auxpass(3,destroyed,be).
case(3,battle,in).
nmod:poss(3,battle,our).
nmod:in(3,destroyed,battle).
case(3,other,with).
det(3,other,each).
nmod:with(3,destroyed,other).
dep(3,destroyed,than).
dep(3,destroyed,admit).
det(3,interference,any).
dobj(3,admit,interference).
case(3,you,from).
nmod:from(3,admit,you).
case(3,affairs,in).
nmod:poss(3,affairs,our).
nmod:in(3,destroyed,affairs).
would(3,we,would_rather_destroyed_in_our_battle).
would(3,we,would_far_rather_destroyed_in_our_battle).
would(3,we,would_destroyed_in_our_affairs).
would(3,we,would_far_rather_destroyed_in_our_affairs).
would(3,we,would_far_rather_destroyed_in_our_battle_in_our_affairs).
would(3,we,would_destroyed_in_our_battle_in_our_affairs).
would(3,we,would_far_rather_destroyed).
would(3,we,would_destroyed).
would(3,we,would_rather_destroyed).
would(3,we,would_rather_destroyed_in_our_battle_in_our_affairs).
would(3,we,would_destroyed_in_our_battle).
would(3,we,would_rather_destroyed_in_our_affairs).
