root(0,ROOT,seated).
det(0,crow,a).
amod(0,crow,troublesome).
nsubj(0,seated,crow).
dobj(0,seated,herself).
case(0,back,on).
det(0,back,the).
nmod:on(0,seated,back).
case(0,sheep,of).
det(0,sheep,a).
nmod:of(0,back,sheep).
seated(0,crow,herself).
seated(0,troublesome_crow,herself).
root(1,ROOT,carried).
det(1,sheep,the).
nsubj(1,carried,sheep).
advmod(1,carried,much).
case(1,his,against).
nmod:against(1,much,his).
aux(1,carried,will).
dobj(1,carried,her).
advmod(1,carried,backward).
cc(1,carried,and).
conj:and(1,carried,forward).
conj:and(1,carried,forward).
conj:and(1,forward,forward).
case(1,time,for).
det(1,time,a).
amod(1,time,long).
nmod:for(1,forward,time).
cc(1,forward,and).
case(1,last,at).
nmod:at(1,forward,last).
acl(1,last,said).
much_will_carried(1,sheep,her).
will_carried_backward(1,sheep,her).
much_will_carried_backward(1,sheep,her).
will_carried(1,sheep,her).
root(2,ROOT,treated).
mark(2,treated,if).
nsubj(2,treated,you).
aux(2,treated,had).
det(2,dog,a).
dobj(2,treated,dog).
case(2,way,in).
det(2,way,this).
nmod:in(2,treated,way).
nsubj(2,had,you).
aux(2,had,would).
aux(2,had,have).
acl:relcl(2,way,had).
nmod:poss(2,deserts,your).
dobj(2,had,deserts).
case(2,teeth,from).
nmod:poss(2,teeth,his).
amod(2,teeth,sharp).
nmod:from(2,had,teeth).
had_treated(2,you,dog).
root(3,ROOT,this).
dep(3,this,to).
det(3,crow,the).
nsubj(3,replied,crow).
acl:relcl(3,this,replied).
root(4,ROOT,despise).
nsubj(4,despise,i).
det(4,weak,the).
dobj(4,despise,weak).
cc(4,weak,and).
dobj(4,despise,yield).
conj:and(4,weak,yield).
case(4,strong,to).
det(4,strong,the).
nmod:to(4,despise,strong).
despise(4,i,weak).
despise(4,i,yield).
despise_yield_to(4,i,strong).
root(5,ROOT,know).
advmod(5,know,i).
dobj(5,bully,whom).
nsubj(5,bully,i).
aux(5,bully,may).
dep(5,know,bully).
cc(5,bully,and).
dobj(5,flatter,whom).
nsubj(5,flatter,i).
aux(5,flatter,must).
dep(5,know,flatter).
conj:and(5,bully,flatter).
root(6,ROOT,i).
cc(6,i,and).
advmod(6,prolong,thus).
acl:relcl(6,i,prolong).
nmod:poss(6,life,my).
dobj(6,prolong,life).
case(6,age,to).
det(6,age,a).
amod(6,age,good).
amod(6,age,old).
nmod:to(6,prolong,age).
