root(0,ROOT,gave).
det(0,man,a).
amod(0,man,rich).
nsubj(0,gave,man).
det(0,feast,a).
amod(0,feast,great).
dobj(0,gave,feast).
nmod:to(0,invited,feast).
case(0,which,to).
ref(0,feast,which).
nsubj(0,invited,he).
acl:relcl(0,feast,invited).
amod(0,friends,many).
dobj(0,invited,friends).
cc(0,friends,and).
dobj(0,invited,acquaintances).
conj:and(0,friends,acquaintances).
root(1,ROOT,availed).
nmod:poss(1,dog,his).
nsubj(1,availed,dog).
dobj(1,availed,himself).
case(1,occasion,of).
det(1,occasion,the).
nmod:of(1,availed,occasion).
mark(1,invite,to).
advcl:to(1,availed,invite).
det(1,dog,a).
compound(1,dog,stranger).
nsubj(1,friend,dog).
det(1,friend,a).
xcomp(1,invite,friend).
case(1,his,of).
nmod:of(1,friend,his).
amod(1,his,saying).
friend_of(1,stranger_dog,his_saying).
invite(1,his_dog,stranger_dog_friend_of_his_saying).
availed(1,his_dog,himself).
invite(1,his_dog,stranger_dog_friend_of_his).
friend_of(1,stranger_dog,his).
invite(1,his_dog,stranger_dog_friend).
root(2,ROOT,gives).
nmod:poss(2,master,my).
nsubj(2,gives,master).
det(2,feast,a).
dobj(2,gives,feast).
cc(2,gives,and).
expl(2,is,there).
conj:and(2,gives,is).
advmod(2,is,always).
amod(2,food,much).
nsubj(2,is,food).
acl(2,food,remaining).
gives(2,my_master,feast).
root(3,ROOT,come).
cc(3,come,and).
conj:and(3,come,sup).
case(3,me,with).
nmod:with(3,sup,me).
nmod:tmod(3,me,tonight).
is_with(3,sup,me_tonight).
root(4,ROOT,went).
det(4,dog,the).
nsubj(4,went,dog).
advmod(4,invited,thus).
acl(4,dog,invited).
case(4,hour,at).
det(4,hour,the).
nmod:at(4,went,hour).
dep(4,hour,appointed).
cc(4,appointed,and).
dep(4,hour,seeing).
conj:and(4,appointed,seeing).
det(4,preparations,the).
dobj(4,seeing,preparations).
case(4,grand,for).
advmod(4,grand,so).
nmod:for(4,seeing,grand).
det(4,entertainment,an).
nsubj(4,said,entertainment).
acl:relcl(4,grand,said).
case(4,joy,in).
det(4,joy,the).
nmod:in(4,said,joy).
case(4,heart,of).
nmod:poss(4,heart,his).
nmod:of(4,joy,heart).
said_in(4,entertainment,joy).
went_at(4,dog,hour).
said_in(4,entertainment,joy_of_his_heart).
root(5,ROOT,am).
advmod(5,am,how).
dep(5,how,glad).
nsubj(5,am,i).
mark(5,came,that).
nsubj(5,came,i).
ccomp(5,am,came).
root(6,ROOT,get).
nsubj(6,get,i).
aux(6,get,do).
neg(6,get,not).
advmod(6,get,often).
det:predet(6,chance,such).
det(6,chance,a).
dobj(6,get,chance).
case(6,this,as).
nmod:as(6,get,this).
root(7,ROOT,take).
nsubj(7,take,i).
nsubj(7,eat,i).
nsubj:xsubj(7,last,i).
aux(7,take,will).
dobj(7,take,care).
cc(7,take,and).
conj:and(7,take,eat).
advmod(7,eat,enough).
mark(7,last,to).
xcomp(7,eat,last).
dobj(7,last,me).
cc:preconj(7,today,both).
nmod:tmod(7,last,today).
cc(7,today,and).
nmod:tmod(7,last,tomorrow).
conj:and(7,today,tomorrow).
will_take(7,i,care).
root(8,ROOT,congratulating).
mark(8,congratulating,while).
nsubj(8,congratulating,he).
aux(8,congratulating,was).
dobj(8,congratulating,himself).
cc(8,congratulating,and).
csubj(8,bundled,wagging).
nmod:poss(8,tail,his).
dobj(8,wagging,tail).
mark(8,convey,to).
acl:to(8,tail,convey).
nmod:poss(8,pleasure,his).
dobj(8,convey,pleasure).
case(8,friend,to).
nmod:poss(8,friend,his).
nmod:to(8,convey,friend).
det(8,cook,the).
nsubj(8,saw,cook).
acl:relcl(8,friend,saw).
nsubj(8,moving,him).
nsubj(8,seizing,him).
ccomp(8,saw,moving).
dep(8,moving,about).
case(8,dishes,among).
nmod:poss(8,dishes,his).
nmod:among(8,moving,dishes).
cc(8,moving,and).
ccomp(8,saw,seizing).
conj:and(8,moving,seizing).
dobj(8,seizing,him).
case(8,fore,by).
nmod:poss(8,fore,his).
nmod:by(8,seizing,fore).
cc(8,fore,and).
compound(8,paws,hind).
nmod:by(8,seizing,paws).
conj:and(8,fore,paws).
conj:and(8,congratulating,bundled).
dobj(8,bundled,him).
case(8,ceremony,without).
nmod:without(8,bundled,ceremony).
case(8,window,out).
mwe(8,out,of).
det(8,window,the).
nmod:out_of(8,bundled,window).
seizing(8,him,him).
was_congratulating(8,he,himself).
moving_among(8,him,his_dishes).
root(9,ROOT,fell).
nsubj(9,fell,he).
nsubj(9,limped,he).
case(9,force,with).
nmod:with(9,fell,force).
case(9,ground,upon).
det(9,ground,the).
nmod:upon(9,fell,ground).
cc(9,fell,and).
conj:and(9,fell,limped).
advmod(9,howling,away).
xcomp(9,limped,howling).
advmod(9,limped,dreadfully).
fell_with(9,he,force).
limped(9,he,away_howling).
fell_upon(9,he,ground).
limped_dreadfully(9,he,away_howling).
limped(9,he,howling).
limped_dreadfully(9,he,howling).
root(10,ROOT,attracted).
nsubj(10,attracted,his).
acl(10,his,yelling).
advmod(10,yelling,soon).
amod(10,dogs,other).
compound(10,dogs,street).
dobj(10,attracted,dogs).
nsubj(10,came,dogs).
nsubj(10,inquired,dogs).
ref(10,dogs,who).
acl:relcl(10,dogs,came).
compound:prt(10,came,up).
case(10,him,to).
nmod:to(10,came,him).
cc(10,came,and).
acl:relcl(10,dogs,inquired).
conj:and(10,came,inquired).
advmod(10,enjoyed,how).
nsubj(10,enjoyed,he).
aux(10,enjoyed,had).
ccomp(10,inquired,enjoyed).
nmod:poss(10,supper,his).
dobj(10,enjoyed,supper).
enjoyed(10,he,his_supper).
root(11,ROOT,replied).
nsubj(11,replied,he).
root(12,ROOT,tell).
advmod(12,tell,why).
mark(12,tell,to).
iobj(12,tell,you).
det(12,truth,the).
dobj(12,tell,truth).
dobj(12,remember,truth).
nsubj(12,drank,i).
acl:relcl(12,truth,drank).
advmod(12,much,so).
amod(12,wine,much).
dobj(12,drank,wine).
ref(12,truth,that).
nsubj(12,remember,i).
dep(12,drank,remember).
dobj(12,remember,nothing).
drank(12,i,so_much_wine).
remember(12,i,nothing).
drank(12,i,wine).
drank(12,i,much_wine).
root(13,ROOT,know).
nsubj(13,know,i).
aux(13,know,do).
neg(13,know,not).
advmod(13,got,how).
nsubj(13,got,i).
ccomp(13,know,got).
compound:prt(13,got,out).
case(13,house,of).
det(13,house,the).
nmod:of(13,got,house).
